# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = ReplaceImagePanel
DESTDIR = ../
CONFIG += debug
DEFINES += REPLACEIMAGEPANEL_LIB
LIBS += -L"./../../Lib/Release" \
    -lComponent \
    -lDisplayImage \
    -lServiceLib
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += GeneratedFiles
RCC_DIR += GeneratedFiles
include(ReplaceImagePanel.pri)
