#ifndef FILTERREVERSECOSINERING_GLOBAL_H
#define FILTERREVERSECOSINERING_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef FILTERREVERSECOSINERING_LIB
# define FILTERREVERSECOSINERING_EXPORT Q_DECL_EXPORT
#else
# define FILTERREVERSECOSINERING_EXPORT Q_DECL_IMPORT
#endif

#endif // FILTERREVERSECOSINERING_GLOBAL_H
