#ifndef LISTCACHTARGETIMAGE_GLOBAL_H
#define LISTCACHTARGETIMAGE_GLOBAL_H

#include <qglobal.h>

#ifdef LISTCACHTARGETIMAGE_LIB
# define LISTCACHTARGETIMAGE_EXPORT Q_DECL_EXPORT
#else
# define LISTCACHTARGETIMAGE_EXPORT Q_DECL_IMPORT
#endif

#endif // LISTCACHTARGETIMAGE_GLOBAL_H
