# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = MTXMLLib
DESTDIR = ../../../Lib/Release
QT += core sql network widgets
CONFIG += staticlib debug
DEFINES += MTXMLLIB_LIB
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += ./GeneratedFiles/$(ConfigurationName)
OBJECTS_DIR += release
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles
include(MTXMLLib.pri)
