#ifndef NGIMAGELISTFORREVIEW_GLOBAL_H
#define NGIMAGELISTFORREVIEW_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef NGIMAGELISTFORREVIEW_LIB
# define NGIMAGELISTFORREVIEW_EXPORT Q_DECL_EXPORT
#else
# define NGIMAGELISTFORREVIEW_EXPORT Q_DECL_IMPORT
#endif

#endif // NGIMAGELISTFORREVIEW_GLOBAL_H
