#ifndef PROPERTYGERBERFAST_GLOBAL_H
#define PROPERTYGERBERFAST_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PROPERTYGERBERFAST_LIB
# define PROPERTYGERBERFAST_EXPORT Q_DECL_EXPORT
#else
# define PROPERTYGERBERFAST_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTYGERBERFAST_GLOBAL_H
