#ifndef INTEGRATIONNEWMASTER_GLOBAL_H
#define INTEGRATIONNEWMASTER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef INTEGRATIONNEWMASTER_LIB
# define INTEGRATIONNEWMASTER_EXPORT Q_DECL_EXPORT
#else
# define INTEGRATIONNEWMASTER_EXPORT Q_DECL_IMPORT
#endif

#endif // INTEGRATIONNEWMASTER_GLOBAL_H
