#ifndef BUTTONFEEDBACK_GLOBAL_H
#define BUTTONFEEDBACK_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONFEEDBACK_LIB
# define BUTTONFEEDBACK_EXPORT Q_DECL_EXPORT
#else
# define BUTTONFEEDBACK_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONFEEDBACK_GLOBAL_H
