#ifndef KEYENCEILSENSOR_GLOBAL_H
#define KEYENCEILSENSOR_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef KEYENCEILSENSOR_LIB
# define KEYENCEILSENSOR_EXPORT Q_DECL_EXPORT
#else
# define KEYENCEILSENSOR_EXPORT Q_DECL_IMPORT
#endif

#endif // KEYENCEILSENSOR_GLOBAL_H
