# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = DummyCamera
DESTDIR = ../../../
CONFIG += release
DEFINES += DUMMYCAMERA_LIB
LIBS += -L"./../../../../Lib/Release" \
    -lServiceLib
DEPENDPATH += .
MOC_DIR += ./GeneratedFiles/$(ConfigurationName)
OBJECTS_DIR += release
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles
include(DummyCamera.pri)
