#ifndef BUTTONLOADRESULTWITHALL_GLOBAL_H
#define BUTTONLOADRESULTWITHALL_GLOBAL_H

#include <qglobal.h>

#ifdef BUTTONLOADRESULTWITHALL_LIB
# define BUTTONLOADRESULTWITHALL_EXPORT Q_DECL_EXPORT
#else
# define BUTTONLOADRESULTWITHALL_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONLOADRESULTWITHALL_GLOBAL_H
