#ifndef BUTTONSELECTMASTER_GLOBAL_H
#define BUTTONSELECTMASTER_GLOBAL_H

#include <qglobal.h>

#ifdef BUTTONSELECTMASTER_LIB
# define BUTTONSELECTMASTER_EXPORT Q_DECL_EXPORT
#else
# define BUTTONSELECTMASTER_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONSELECTMASTER_GLOBAL_H
