#ifndef INTEGRATIONHISTORY_GLOBAL_H
#define INTEGRATIONHISTORY_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef INTEGRATIONHISTORY_LIB
# define INTEGRATIONHISTORY_EXPORT Q_DECL_EXPORT
#else
# define INTEGRATIONHISTORY_EXPORT Q_DECL_IMPORT
#endif

#endif // INTEGRATIONHISTORY_GLOBAL_H
