#ifndef PROPERTYMAKEAVERAGEIMAGE_GLOBAL_H
#define PROPERTYMAKEAVERAGEIMAGE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PROPERTYMAKEAVERAGEIMAGE_LIB
# define PROPERTYMAKEAVERAGEIMAGE_EXPORT Q_DECL_EXPORT
#else
# define PROPERTYMAKEAVERAGEIMAGE_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTYMAKEAVERAGEIMAGE_GLOBAL_H
