#ifndef EASYDXFOPERATIONIMAGEPANEL_GLOBAL_H
#define EASYDXFOPERATIONIMAGEPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef EASYDXFOPERATIONIMAGEPANEL_LIB
# define EASYDXFOPERATIONIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define EASYDXFOPERATIONIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // EASYDXFOPERATIONIMAGEPANEL_GLOBAL_H
