# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = CameraSharerDLL
DESTDIR = ../../
CONFIG += debug
DEFINES += QT_LARGEFILE_SUPPORT CAMERASHARERDLL_LIB
LIBS += -L"./../../../Lib/Release" \
    -lServiceLib
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += .
RCC_DIR += ./GeneratedFiles
include(CameraSharerDLL.pri)
