#ifndef CAMERASHARERDLL_GLOBAL_H
#define CAMERASHARERDLL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef CAMERASHARERDLL_LIB
# define CAMERASHARERDLL_EXPORT Q_DECL_EXPORT
#else
# define CAMERASHARERDLL_EXPORT Q_DECL_IMPORT
#endif

#endif // CAMERASHARERDLL_GLOBAL_H
