#ifndef BUTTONSELECTSMALLLOT_GLOBAL_H
#define BUTTONSELECTSMALLLOT_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONSELECTSMALLLOT_LIB
# define BUTTONSELECTSMALLLOT_EXPORT Q_DECL_EXPORT
#else
# define BUTTONSELECTSMALLLOT_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONSELECTSMALLLOT_GLOBAL_H
