# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../DesktopMachineMenu/DesktopMachineMenu.h \
    ../DesktopMachineMenu/desktopmachinemenu_global.h \
    ./ManualDesktopMachineMenuResource.h \
    ../StartStatisticScanButton/StartStatisticScanBase.h \
    ../StartCaptureButton/XPushCmdPacket.h \
    ../DesktopMachineMenu/DesktopMachineMenuProperty.h \
    ../DesktopMachineMenu/DesktopStartStatisticScan.h \
    ../DesktopMachineMenu/NextMasterForm.h \
    ../StartCaptureButton/StartCaptureButton.h \
    ../StartInspectionButton/StartInspectionButton.h
SOURCES += ../DesktopMachineMenu/DesktopStartStatisticScan.cpp \
    ../../Open/GUIDllCommon.cpp \
    ./ManualDesktopMachineMenu.cpp \
    ./ManualDesktopMachineMenuProperty.cpp \
    ../DesktopMachineMenu/NextMasterForm.cpp \
    ../StartCaptureButton/StartCaptureButtonForm.cpp \
    ../StartInspectionButton/StartInspectionButtonForm.cpp \
    ../StartStatisticScanButton/StartStatisticScanBase.cpp \
    ../../Open/SystemVersion.cpp \
    ../StartCaptureButton/XPushCmdPacket.cpp \
    ./ManualDesktopMachineMenuResource.cpp
FORMS += ../DesktopMachineMenu/DesktopMachineMenuProperty.ui \
    ../DesktopMachineMenu/NextMasterForm.ui
RESOURCES += ManualDesktopMachineMenu.qrc
