#ifndef LIVECAMERAMIGHTEXUSB3_GLOBAL_H
#define LIVECAMERAMIGHTEXUSB3_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef LIVECAMERAMIGHTEXUSB3_LIB
# define LIVECAMERAMIGHTEXUSB3_EXPORT Q_DECL_EXPORT
#else
# define LIVECAMERAMIGHTEXUSB3_EXPORT Q_DECL_IMPORT
#endif

#endif // LIVECAMERAMIGHTEXUSB3_GLOBAL_H
