#ifndef PIECEFORREVIEW_GLOBAL_H
#define PIECEFORREVIEW_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PIECEFORREVIEW_LIB
# define PIECEFORREVIEW_EXPORT Q_DECL_EXPORT
#else
# define PIECEFORREVIEW_EXPORT Q_DECL_IMPORT
#endif

#endif // PIECEFORREVIEW_GLOBAL_H
