#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(PROPERTYFLATINSPECTION_LIB)
#  define PROPERTYFLATINSPECTION_EXPORT Q_DECL_EXPORT
# else
#  define PROPERTYFLATINSPECTION_EXPORT Q_DECL_IMPORT
# endif
#else
# define PROPERTYFLATINSPECTION_EXPORT
#endif
