#ifndef SWITCHPHASEIMAGEPANEL_GLOBAL_H
#define SWITCHPHASEIMAGEPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SWITCHPHASEIMAGEPANEL_LIB
# define SWITCHPHASEIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define SWITCHPHASEIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // SWITCHPHASEIMAGEPANEL_GLOBAL_H
