#ifndef BUSLINEINSPECTION_GLOBAL_H
#define BUSLINEINSPECTION_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUSLINEINSPECTION_LIB
# define BUSLINEINSPECTION_EXPORT Q_DECL_EXPORT
#else
# define BUSLINEINSPECTION_EXPORT Q_DECL_IMPORT
#endif

#endif // BUSLINEINSPECTION_GLOBAL_H
