#ifndef PANELSIZEHOLEINSPECTION_GLOBAL_H
#define PANELSIZEHOLEINSPECTION_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PANELSIZEHOLEINSPECTION_LIB
# define PANELSIZEHOLEINSPECTION_EXPORT Q_DECL_EXPORT
#else
# define PANELSIZEHOLEINSPECTION_EXPORT Q_DECL_IMPORT
#endif

#endif // PANELSIZEHOLEINSPECTION_GLOBAL_H
