#ifndef POPUPGENERALDISPLAYWHOLEIMAGE_GLOBAL_H
#define POPUPGENERALDISPLAYWHOLEIMAGE_GLOBAL_H

#include <qglobal.h>

#ifdef POPUPGENERALDISPLAYWHOLEIMAGE_LIB
# define POPUPGENERALDISPLAYWHOLEIMAGE_EXPORT Q_DECL_EXPORT
#else
# define POPUPGENERALDISPLAYWHOLEIMAGE_EXPORT Q_DECL_IMPORT
#endif

#endif // POPUPGENERALDISPLAYWHOLEIMAGE_GLOBAL_H
