#ifndef BUTTONSAVEMATRIXCELL_GLOBAL_H
#define BUTTONSAVEMATRIXCELL_GLOBAL_H

#include <qglobal.h>

#ifdef BUTTONSAVEMATRIXCELL_LIB
# define BUTTONSAVEMATRIXCELL_EXPORT Q_DECL_EXPORT
#else
# define BUTTONSAVEMATRIXCELL_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONSAVEMATRIXCELL_GLOBAL_H
