#ifndef INTEGRATIONSHOWNGMAP_GLOBAL_H
#define INTEGRATIONSHOWNGMAP_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef INTEGRATIONSHOWNGMAP_LIB
# define INTEGRATIONSHOWNGMAP_EXPORT Q_DECL_EXPORT
#else
# define INTEGRATIONSHOWNGMAP_EXPORT Q_DECL_IMPORT
#endif

#endif // INTEGRATIONSHOWNGMAP_GLOBAL_H
