#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(BUTTONTRANSFERREQUIREIMAGEDATA_LIB)
#  define BUTTONTRANSFERREQUIREIMAGEDATA_EXPORT Q_DECL_EXPORT
# else
#  define BUTTONTRANSFERREQUIREIMAGEDATA_EXPORT Q_DECL_IMPORT
# endif
#else
# define BUTTONTRANSFERREQUIREIMAGEDATA_EXPORT
#endif
