#ifndef PANELMAXSTOCK_GLOBAL_H
#define PANELMAXSTOCK_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PANELMAXSTOCK_LIB
# define PANELMAXSTOCK_EXPORT Q_DECL_EXPORT
#else
# define PANELMAXSTOCK_EXPORT Q_DECL_IMPORT
#endif

#endif // PANELMAXSTOCK_GLOBAL_H
