#ifndef FILTERDIFFERENCIALHV_GLOBAL_H
#define FILTERDIFFERENCIALHV_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef FILTERDIFFERENCIALHV_LIB
# define FILTERDIFFERENCIALHV_EXPORT Q_DECL_EXPORT
#else
# define FILTERDIFFERENCIALHV_EXPORT Q_DECL_IMPORT
#endif

#endif // FILTERDIFFERENCIALHV_GLOBAL_H
