#ifndef ALIGNMENTPROJECTIONIMAGEPANEL_GLOBAL_H
#define ALIGNMENTPROJECTIONIMAGEPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef ALIGNMENTPROJECTIONIMAGEPANEL_LIB
# define ALIGNMENTPROJECTIONIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define ALIGNMENTPROJECTIONIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // ALIGNMENTPROJECTIONIMAGEPANEL_GLOBAL_H
