#ifndef PROPERTYLINEPATTERN_GLOBAL_H
#define PROPERTYLINEPATTERN_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PROPERTYLINEPATTERN_LIB
# define PROPERTYLINEPATTERN_EXPORT Q_DECL_EXPORT
#else
# define PROPERTYLINEPATTERN_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTYLINEPATTERN_GLOBAL_H
