#ifndef BUTTONTHRESHOLD_GLOBAL_H
#define BUTTONTHRESHOLD_GLOBAL_H

#include <qglobal.h>

#ifdef BUTTONTHRESHOLD_LIB
# define BUTTONTHRESHOLD_EXPORT Q_DECL_EXPORT
#else
# define BUTTONTHRESHOLD_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONTHRESHOLD_GLOBAL_H
