#ifndef INTEGRATIONSELECTLOT_GLOBAL_H
#define INTEGRATIONSELECTLOT_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef INTEGRATIONSELECTLOT_LIB
# define INTEGRATIONSELECTLOT_EXPORT Q_DECL_EXPORT
#else
# define INTEGRATIONSELECTLOT_EXPORT Q_DECL_IMPORT
#endif

#endif // INTEGRATIONSELECTLOT_GLOBAL_H
