#ifndef BUTTONSAVEPWAFILE_GLOBAL_H
#define BUTTONSAVEPWAFILE_GLOBAL_H

#include <qglobal.h>

#ifdef BUTTONSAVEPWAFILE_LIB
# define BUTTONSAVEPWAFILE_EXPORT Q_DECL_EXPORT
#else
# define BUTTONSAVEPWAFILE_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONSAVEPWAFILE_GLOBAL_H
