#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(PROPERTYCHECKDATAVALIDATION_LIB)
#  define PROPERTYCHECKDATAVALIDATION_EXPORT Q_DECL_EXPORT
# else
#  define PROPERTYCHECKDATAVALIDATION_EXPORT Q_DECL_IMPORT
# endif
#else
# define PROPERTYCHECKDATAVALIDATION_EXPORT
#endif
