#ifndef LEDCONTROL16C_GLOBAL_H
#define LEDCONTROL16C_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef LEDCONTROL16C_LIB
# define LEDCONTROL16C_EXPORT Q_DECL_EXPORT
#else
# define LEDCONTROL16C_EXPORT Q_DECL_IMPORT
#endif

#endif // LEDCONTROL16C_GLOBAL_H
