/********************************************************************************
** Form generated from reading UI file 'PropertyTrueColorBlockForm.ui'
**
** Created by: Qt User Interface Compiler version 6.10.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_PROPERTYTRUECOLORBLOCKFORM_H
#define UI_PROPERTYTRUECOLORBLOCKFORM_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QToolButton>
#include <QtWidgets/QWidget>
#include "guiformbase.h"

QT_BEGIN_NAMESPACE

class Ui_PropertyTrueColorBlockFormClass
{
public:
    QFrame *frame_3;
    QToolButton *toolButtonEdge;
    QToolButton *toolButtonArea;
    QToolButton *toolButtonInside;
    QFrame *frame_2;
    QToolButton *toolButtonLibrary;
    QToolButton *toolButtonCreateBlock;
    QStackedWidget *stackedWidget;
    QWidget *page;
    QTableWidget *tableWidgetLibList;
    QTableWidget *tableWidgetGeneratedLibList;
    QLabel *labelLibFolderName;
    QPushButton *pushButtonEditLibFolder;
    QPushButton *pushButtonSetFrom;
    QPushButton *pushButtonGetBack;
    QPushButton *pushButtonEditLibrary;
    QPushButton *ButtonPickupTest;
    QPushButton *ButtonPickupClearTest;
    QPushButton *ButtonGenerateLibs;
    QLabel *label_30;
    QLabel *label_31;
    QFrame *frame_4;
    QLineEdit *EditLibName;
    QLabel *label_18;
    QLineEdit *EditLibID;
    QPushButton *ButtonLibSave;
    QTabWidget *tabWidget_2;
    QWidget *tab_3;
    QPushButton *pushButtonGColor;
    QFrame *frameGenerate;
    QWidget *tab_4;
    QFrame *frame_6;
    QSpinBox *EditMinBlockSize;
    QLabel *label_9;
    QSpinBox *EditMaxBlockSize;
    QLabel *label_10;
    QSpinBox *EditMinBlockDots;
    QLabel *label_12;
    QSpinBox *EditMaxBlockDots;
    QLabel *label_11;
    QLabel *label_13;
    QSpinBox *EditLimitBlockSize;
    QLabel *label_57;
    QFrame *frame_5;
    QLabel *label_14;
    QSpinBox *EditSpaceToOutline;
    QLabel *label_15;
    QSpinBox *EditNoiseSize;
    QLabel *label_16;
    QSpinBox *EditPriority;
    QLabel *label_56;
    QLabel *label_17;
    QSpinBox *EditNoiseSizePinHole;
    QPushButton *pushButtonGetBackAll;
    QPushButton *pushButtonSetFromAll;
    QWidget *page_2;
    QLabel *label_32;
    QFrame *frameBlockInfoOnMouse;
    QLabel *label_33;
    QFrame *frame;
    QFrame *frame_15;
    QLabel *label_47;
    QFrame *frame_16;
    QLabel *label_48;
    QSpinBox *EditAdjustBlack;
    QCheckBox *checkBModeAdjustable;
    QSpinBox *EditAdjustWhite;
    QLabel *label_49;
    QLabel *label_50;
    QSpinBox *EditSelfSearch;
    QLabel *label_53;
    QLineEdit *EditLibNameInBlock;
    QLineEdit *EditLibIDInBlock;
    QLabel *label_34;
    QTabWidget *tabWidget;
    QWidget *tab;
    QLabel *label_51;
    QLabel *label_66;
    QSpinBox *EditNMergin;
    QFrame *frameNarrowPanel;
    QSpinBox *EditNOKDot;
    QLabel *label_36;
    QSpinBox *EditNMinNGCount;
    QWidget *tab_2;
    QLabel *label_54;
    QFrame *frameBroadPanel;
    QLabel *label_55;
    QSpinBox *EditBOKDot;
    QSpinBox *EditBMergin;
    QSpinBox *EditBMinNGCount;
    QLabel *label_37;
    QTableWidget *tableWidgetBlockInfo;

    void setupUi(GUIFormBase *PropertyTrueColorBlockFormClass)
    {
        if (PropertyTrueColorBlockFormClass->objectName().isEmpty())
            PropertyTrueColorBlockFormClass->setObjectName("PropertyTrueColorBlockFormClass");
        PropertyTrueColorBlockFormClass->resize(400, 700);
        frame_3 = new QFrame(PropertyTrueColorBlockFormClass);
        frame_3->setObjectName("frame_3");
        frame_3->setGeometry(QRect(310, 10, 71, 21));
        frame_3->setFrameShape(QFrame::NoFrame);
        frame_3->setFrameShadow(QFrame::Plain);
        toolButtonEdge = new QToolButton(frame_3);
        toolButtonEdge->setObjectName("toolButtonEdge");
        toolButtonEdge->setGeometry(QRect(20, 0, 19, 18));
        toolButtonEdge->setCheckable(true);
        toolButtonEdge->setChecked(false);
        toolButtonEdge->setAutoExclusive(true);
        toolButtonArea = new QToolButton(frame_3);
        toolButtonArea->setObjectName("toolButtonArea");
        toolButtonArea->setGeometry(QRect(0, 0, 19, 18));
        toolButtonArea->setCheckable(true);
        toolButtonArea->setChecked(true);
        toolButtonArea->setAutoExclusive(true);
        toolButtonInside = new QToolButton(frame_3);
        toolButtonInside->setObjectName("toolButtonInside");
        toolButtonInside->setGeometry(QRect(40, 0, 19, 18));
        toolButtonInside->setCheckable(true);
        toolButtonInside->setChecked(false);
        toolButtonInside->setAutoExclusive(true);
        frame_2 = new QFrame(PropertyTrueColorBlockFormClass);
        frame_2->setObjectName("frame_2");
        frame_2->setGeometry(QRect(10, 0, 291, 41));
        frame_2->setFrameShape(QFrame::NoFrame);
        frame_2->setFrameShadow(QFrame::Plain);
        toolButtonLibrary = new QToolButton(frame_2);
        toolButtonLibrary->setObjectName("toolButtonLibrary");
        toolButtonLibrary->setGeometry(QRect(0, 10, 111, 31));
        QFont font;
        font.setPointSize(12);
        toolButtonLibrary->setFont(font);
        toolButtonLibrary->setCheckable(true);
        toolButtonLibrary->setChecked(true);
        toolButtonLibrary->setAutoExclusive(true);
        toolButtonCreateBlock = new QToolButton(frame_2);
        toolButtonCreateBlock->setObjectName("toolButtonCreateBlock");
        toolButtonCreateBlock->setGeometry(QRect(170, 10, 111, 31));
        toolButtonCreateBlock->setFont(font);
        toolButtonCreateBlock->setCheckable(true);
        toolButtonCreateBlock->setAutoExclusive(true);
        stackedWidget = new QStackedWidget(PropertyTrueColorBlockFormClass);
        stackedWidget->setObjectName("stackedWidget");
        stackedWidget->setGeometry(QRect(0, 50, 396, 651));
        page = new QWidget();
        page->setObjectName("page");
        tableWidgetLibList = new QTableWidget(page);
        if (tableWidgetLibList->columnCount() < 2)
            tableWidgetLibList->setColumnCount(2);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        tableWidgetLibList->setHorizontalHeaderItem(0, __qtablewidgetitem);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        tableWidgetLibList->setHorizontalHeaderItem(1, __qtablewidgetitem1);
        tableWidgetLibList->setObjectName("tableWidgetLibList");
        tableWidgetLibList->setGeometry(QRect(10, 60, 161, 131));
        tableWidgetLibList->setSelectionMode(QAbstractItemView::SingleSelection);
        tableWidgetLibList->setSelectionBehavior(QAbstractItemView::SelectRows);
        tableWidgetGeneratedLibList = new QTableWidget(page);
        if (tableWidgetGeneratedLibList->columnCount() < 2)
            tableWidgetGeneratedLibList->setColumnCount(2);
        QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
        tableWidgetGeneratedLibList->setHorizontalHeaderItem(0, __qtablewidgetitem2);
        QTableWidgetItem *__qtablewidgetitem3 = new QTableWidgetItem();
        tableWidgetGeneratedLibList->setHorizontalHeaderItem(1, __qtablewidgetitem3);
        tableWidgetGeneratedLibList->setObjectName("tableWidgetGeneratedLibList");
        tableWidgetGeneratedLibList->setGeometry(QRect(230, 60, 161, 131));
        tableWidgetGeneratedLibList->setSelectionBehavior(QAbstractItemView::SelectRows);
        labelLibFolderName = new QLabel(page);
        labelLibFolderName->setObjectName("labelLibFolderName");
        labelLibFolderName->setGeometry(QRect(130, 0, 241, 31));
        QFont font1;
        font1.setPointSize(16);
        labelLibFolderName->setFont(font1);
        pushButtonEditLibFolder = new QPushButton(page);
        pushButtonEditLibFolder->setObjectName("pushButtonEditLibFolder");
        pushButtonEditLibFolder->setGeometry(QRect(20, 0, 101, 31));
        pushButtonEditLibFolder->setFont(font);
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/Qtres/Class.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        pushButtonEditLibFolder->setIcon(icon);
        pushButtonSetFrom = new QPushButton(page);
        pushButtonSetFrom->setObjectName("pushButtonSetFrom");
        pushButtonSetFrom->setGeometry(QRect(180, 60, 39, 23));
        pushButtonGetBack = new QPushButton(page);
        pushButtonGetBack->setObjectName("pushButtonGetBack");
        pushButtonGetBack->setGeometry(QRect(180, 90, 39, 23));
        pushButtonEditLibrary = new QPushButton(page);
        pushButtonEditLibrary->setObjectName("pushButtonEditLibrary");
        pushButtonEditLibrary->setGeometry(QRect(90, 200, 211, 31));
        pushButtonEditLibrary->setFont(font);
        QIcon icon1;
        icon1.addFile(QString::fromUtf8(":/Qtres/Edit.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        pushButtonEditLibrary->setIcon(icon1);
        ButtonPickupTest = new QPushButton(page);
        ButtonPickupTest->setObjectName("ButtonPickupTest");
        ButtonPickupTest->setGeometry(QRect(10, 240, 171, 31));
        ButtonPickupTest->setFont(font);
        QIcon icon2;
        icon2.addFile(QString::fromUtf8(":/Qtres/Extract.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        ButtonPickupTest->setIcon(icon2);
        ButtonPickupClearTest = new QPushButton(page);
        ButtonPickupClearTest->setObjectName("ButtonPickupClearTest");
        ButtonPickupClearTest->setGeometry(QRect(10, 280, 171, 31));
        ButtonPickupClearTest->setFont(font);
        QIcon icon3;
        icon3.addFile(QString::fromUtf8(":/Qtres/Clear.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        ButtonPickupClearTest->setIcon(icon3);
        ButtonGenerateLibs = new QPushButton(page);
        ButtonGenerateLibs->setObjectName("ButtonGenerateLibs");
        ButtonGenerateLibs->setGeometry(QRect(190, 240, 201, 71));
        ButtonGenerateLibs->setFont(font);
        QIcon icon4;
        icon4.addFile(QString::fromUtf8(":/Qtres/Add.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        ButtonGenerateLibs->setIcon(icon4);
        label_30 = new QLabel(page);
        label_30->setObjectName("label_30");
        label_30->setGeometry(QRect(10, 40, 161, 20));
        label_30->setFrameShape(QFrame::Panel);
        label_30->setFrameShadow(QFrame::Sunken);
        label_30->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_31 = new QLabel(page);
        label_31->setObjectName("label_31");
        label_31->setGeometry(QRect(230, 40, 161, 20));
        label_31->setFrameShape(QFrame::Panel);
        label_31->setFrameShadow(QFrame::Sunken);
        label_31->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        frame_4 = new QFrame(page);
        frame_4->setObjectName("frame_4");
        frame_4->setGeometry(QRect(0, 320, 391, 321));
        frame_4->setFrameShape(QFrame::StyledPanel);
        frame_4->setFrameShadow(QFrame::Sunken);
        EditLibName = new QLineEdit(frame_4);
        EditLibName->setObjectName("EditLibName");
        EditLibName->setGeometry(QRect(140, 10, 231, 31));
        EditLibName->setFont(font);
        label_18 = new QLabel(frame_4);
        label_18->setObjectName("label_18");
        label_18->setGeometry(QRect(20, 10, 61, 31));
        label_18->setFont(font);
        label_18->setFrameShape(QFrame::Panel);
        label_18->setFrameShadow(QFrame::Sunken);
        label_18->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditLibID = new QLineEdit(frame_4);
        EditLibID->setObjectName("EditLibID");
        EditLibID->setGeometry(QRect(80, 10, 61, 31));
        EditLibID->setFont(font);
        EditLibID->setReadOnly(true);
        ButtonLibSave = new QPushButton(frame_4);
        ButtonLibSave->setObjectName("ButtonLibSave");
        ButtonLibSave->setGeometry(QRect(10, 280, 371, 31));
        ButtonLibSave->setFont(font);
        QIcon icon5;
        icon5.addFile(QString::fromUtf8(":/Qtres/Update.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        ButtonLibSave->setIcon(icon5);
        tabWidget_2 = new QTabWidget(frame_4);
        tabWidget_2->setObjectName("tabWidget_2");
        tabWidget_2->setGeometry(QRect(10, 50, 371, 221));
        tab_3 = new QWidget();
        tab_3->setObjectName("tab_3");
        pushButtonGColor = new QPushButton(tab_3);
        pushButtonGColor->setObjectName("pushButtonGColor");
        pushButtonGColor->setGeometry(QRect(10, 70, 50, 40));
        frameGenerate = new QFrame(tab_3);
        frameGenerate->setObjectName("frameGenerate");
        frameGenerate->setGeometry(QRect(110, 20, 221, 151));
        frameGenerate->setFrameShape(QFrame::NoFrame);
        frameGenerate->setFrameShadow(QFrame::Raised);
        tabWidget_2->addTab(tab_3, QString());
        tab_4 = new QWidget();
        tab_4->setObjectName("tab_4");
        frame_6 = new QFrame(tab_4);
        frame_6->setObjectName("frame_6");
        frame_6->setGeometry(QRect(0, 0, 361, 111));
        frame_6->setFrameShape(QFrame::StyledPanel);
        frame_6->setFrameShadow(QFrame::Sunken);
        EditMinBlockSize = new QSpinBox(frame_6);
        EditMinBlockSize->setObjectName("EditMinBlockSize");
        EditMinBlockSize->setGeometry(QRect(160, 10, 81, 22));
        EditMinBlockSize->setMaximum(1000000);
        label_9 = new QLabel(frame_6);
        label_9->setObjectName("label_9");
        label_9->setGeometry(QRect(40, 30, 111, 21));
        label_9->setFrameShape(QFrame::Panel);
        label_9->setFrameShadow(QFrame::Sunken);
        label_9->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditMaxBlockSize = new QSpinBox(frame_6);
        EditMaxBlockSize->setObjectName("EditMaxBlockSize");
        EditMaxBlockSize->setGeometry(QRect(160, 30, 81, 22));
        EditMaxBlockSize->setMaximum(1000000);
        label_10 = new QLabel(frame_6);
        label_10->setObjectName("label_10");
        label_10->setGeometry(QRect(40, 10, 111, 21));
        label_10->setFrameShape(QFrame::Panel);
        label_10->setFrameShadow(QFrame::Sunken);
        label_10->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditMinBlockDots = new QSpinBox(frame_6);
        EditMinBlockDots->setObjectName("EditMinBlockDots");
        EditMinBlockDots->setGeometry(QRect(160, 60, 81, 22));
        EditMinBlockDots->setMaximum(2000000000);
        label_12 = new QLabel(frame_6);
        label_12->setObjectName("label_12");
        label_12->setGeometry(QRect(40, 60, 111, 21));
        label_12->setFrameShape(QFrame::Panel);
        label_12->setFrameShadow(QFrame::Sunken);
        label_12->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditMaxBlockDots = new QSpinBox(frame_6);
        EditMaxBlockDots->setObjectName("EditMaxBlockDots");
        EditMaxBlockDots->setGeometry(QRect(160, 80, 81, 22));
        EditMaxBlockDots->setMaximum(2000000000);
        EditMaxBlockDots->setValue(2000000000);
        label_11 = new QLabel(frame_6);
        label_11->setObjectName("label_11");
        label_11->setGeometry(QRect(40, 80, 111, 21));
        label_11->setFrameShape(QFrame::Panel);
        label_11->setFrameShadow(QFrame::Sunken);
        label_11->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_13 = new QLabel(frame_6);
        label_13->setObjectName("label_13");
        label_13->setGeometry(QRect(250, 60, 101, 21));
        label_13->setFrameShape(QFrame::Panel);
        label_13->setFrameShadow(QFrame::Sunken);
        label_13->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditLimitBlockSize = new QSpinBox(frame_6);
        EditLimitBlockSize->setObjectName("EditLimitBlockSize");
        EditLimitBlockSize->setGeometry(QRect(280, 80, 61, 22));
        EditLimitBlockSize->setMaximum(99999);
        label_57 = new QLabel(frame_6);
        label_57->setObjectName("label_57");
        label_57->setGeometry(QRect(0, 0, 31, 111));
        label_57->setFrameShape(QFrame::Panel);
        label_57->setFrameShadow(QFrame::Raised);
        label_57->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_57->setIndent(1);
        frame_5 = new QFrame(tab_4);
        frame_5->setObjectName("frame_5");
        frame_5->setGeometry(QRect(0, 110, 361, 81));
        frame_5->setFrameShape(QFrame::StyledPanel);
        frame_5->setFrameShadow(QFrame::Sunken);
        label_14 = new QLabel(frame_5);
        label_14->setObjectName("label_14");
        label_14->setGeometry(QRect(40, 10, 171, 21));
        label_14->setFrameShape(QFrame::Panel);
        label_14->setFrameShadow(QFrame::Sunken);
        label_14->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditSpaceToOutline = new QSpinBox(frame_5);
        EditSpaceToOutline->setObjectName("EditSpaceToOutline");
        EditSpaceToOutline->setGeometry(QRect(210, 10, 61, 23));
        label_15 = new QLabel(frame_5);
        label_15->setObjectName("label_15");
        label_15->setGeometry(QRect(40, 30, 171, 21));
        label_15->setFrameShape(QFrame::Panel);
        label_15->setFrameShadow(QFrame::Sunken);
        label_15->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditNoiseSize = new QSpinBox(frame_5);
        EditNoiseSize->setObjectName("EditNoiseSize");
        EditNoiseSize->setGeometry(QRect(210, 30, 61, 23));
        QFont font2;
        font2.setPointSize(9);
        EditNoiseSize->setFont(font2);
        label_16 = new QLabel(frame_5);
        label_16->setObjectName("label_16");
        label_16->setGeometry(QRect(280, 10, 71, 21));
        label_16->setFrameShape(QFrame::Panel);
        label_16->setFrameShadow(QFrame::Sunken);
        label_16->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditPriority = new QSpinBox(frame_5);
        EditPriority->setObjectName("EditPriority");
        EditPriority->setGeometry(QRect(280, 30, 61, 23));
        EditPriority->setFont(font2);
        label_56 = new QLabel(frame_5);
        label_56->setObjectName("label_56");
        label_56->setGeometry(QRect(0, 0, 31, 81));
        label_56->setFrameShape(QFrame::Panel);
        label_56->setFrameShadow(QFrame::Raised);
        label_56->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_56->setIndent(1);
        label_17 = new QLabel(frame_5);
        label_17->setObjectName("label_17");
        label_17->setGeometry(QRect(40, 50, 171, 21));
        label_17->setFrameShape(QFrame::Panel);
        label_17->setFrameShadow(QFrame::Sunken);
        label_17->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditNoiseSizePinHole = new QSpinBox(frame_5);
        EditNoiseSizePinHole->setObjectName("EditNoiseSizePinHole");
        EditNoiseSizePinHole->setGeometry(QRect(210, 50, 61, 23));
        EditNoiseSizePinHole->setFont(font2);
        tabWidget_2->addTab(tab_4, QString());
        pushButtonGetBackAll = new QPushButton(page);
        pushButtonGetBackAll->setObjectName("pushButtonGetBackAll");
        pushButtonGetBackAll->setGeometry(QRect(180, 160, 39, 23));
        pushButtonSetFromAll = new QPushButton(page);
        pushButtonSetFromAll->setObjectName("pushButtonSetFromAll");
        pushButtonSetFromAll->setGeometry(QRect(180, 130, 39, 23));
        stackedWidget->addWidget(page);
        page_2 = new QWidget();
        page_2->setObjectName("page_2");
        label_32 = new QLabel(page_2);
        label_32->setObjectName("label_32");
        label_32->setGeometry(QRect(10, 0, 381, 21));
        label_32->setFont(font);
        label_32->setFrameShape(QFrame::Panel);
        label_32->setFrameShadow(QFrame::Sunken);
        label_32->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        frameBlockInfoOnMouse = new QFrame(page_2);
        frameBlockInfoOnMouse->setObjectName("frameBlockInfoOnMouse");
        frameBlockInfoOnMouse->setGeometry(QRect(10, 190, 381, 451));
        frameBlockInfoOnMouse->setFrameShape(QFrame::StyledPanel);
        frameBlockInfoOnMouse->setFrameShadow(QFrame::Sunken);
        label_33 = new QLabel(frameBlockInfoOnMouse);
        label_33->setObjectName("label_33");
        label_33->setGeometry(QRect(0, 0, 381, 31));
        label_33->setFont(font);
        label_33->setFrameShape(QFrame::Panel);
        label_33->setFrameShadow(QFrame::Sunken);
        label_33->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        frame = new QFrame(frameBlockInfoOnMouse);
        frame->setObjectName("frame");
        frame->setGeometry(QRect(10, 70, 361, 371));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Raised);
        frame_15 = new QFrame(frame);
        frame_15->setObjectName("frame_15");
        frame_15->setGeometry(QRect(10, 250, 341, 81));
        frame_15->setFrameShape(QFrame::StyledPanel);
        frame_15->setFrameShadow(QFrame::Sunken);
        label_47 = new QLabel(frame_15);
        label_47->setObjectName("label_47");
        label_47->setGeometry(QRect(0, 0, 20, 81));
        label_47->setFrameShape(QFrame::Panel);
        label_47->setFrameShadow(QFrame::Raised);
        label_47->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_47->setIndent(1);
        frame_16 = new QFrame(frame_15);
        frame_16->setObjectName("frame_16");
        frame_16->setGeometry(QRect(10, 120, 371, 101));
        frame_16->setFrameShape(QFrame::StyledPanel);
        frame_16->setFrameShadow(QFrame::Sunken);
        label_48 = new QLabel(frame_16);
        label_48->setObjectName("label_48");
        label_48->setGeometry(QRect(0, 0, 20, 61));
        label_48->setFrameShape(QFrame::Panel);
        label_48->setFrameShadow(QFrame::Raised);
        label_48->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_48->setIndent(1);
        EditAdjustBlack = new QSpinBox(frame_15);
        EditAdjustBlack->setObjectName("EditAdjustBlack");
        EditAdjustBlack->setGeometry(QRect(230, 30, 81, 22));
        EditAdjustBlack->setMaximum(255);
        checkBModeAdjustable = new QCheckBox(frame_15);
        checkBModeAdjustable->setObjectName("checkBModeAdjustable");
        checkBModeAdjustable->setGeometry(QRect(30, 10, 241, 18));
        EditAdjustWhite = new QSpinBox(frame_15);
        EditAdjustWhite->setObjectName("EditAdjustWhite");
        EditAdjustWhite->setGeometry(QRect(230, 50, 81, 22));
        EditAdjustWhite->setMaximum(255);
        label_49 = new QLabel(frame_15);
        label_49->setObjectName("label_49");
        label_49->setGeometry(QRect(30, 50, 191, 21));
        label_49->setFrameShape(QFrame::Panel);
        label_49->setFrameShadow(QFrame::Sunken);
        label_49->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_50 = new QLabel(frame_15);
        label_50->setObjectName("label_50");
        label_50->setGeometry(QRect(30, 30, 191, 21));
        label_50->setFrameShape(QFrame::Panel);
        label_50->setFrameShadow(QFrame::Sunken);
        label_50->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditSelfSearch = new QSpinBox(frame);
        EditSelfSearch->setObjectName("EditSelfSearch");
        EditSelfSearch->setGeometry(QRect(230, 340, 81, 22));
        label_53 = new QLabel(frame);
        label_53->setObjectName("label_53");
        label_53->setGeometry(QRect(20, 340, 201, 21));
        label_53->setFrameShape(QFrame::Panel);
        label_53->setFrameShadow(QFrame::Sunken);
        label_53->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditLibNameInBlock = new QLineEdit(frame);
        EditLibNameInBlock->setObjectName("EditLibNameInBlock");
        EditLibNameInBlock->setGeometry(QRect(120, 10, 231, 31));
        EditLibNameInBlock->setFont(font);
        EditLibIDInBlock = new QLineEdit(frame);
        EditLibIDInBlock->setObjectName("EditLibIDInBlock");
        EditLibIDInBlock->setGeometry(QRect(60, 10, 61, 31));
        EditLibIDInBlock->setFont(font);
        EditLibIDInBlock->setReadOnly(true);
        label_34 = new QLabel(frame);
        label_34->setObjectName("label_34");
        label_34->setGeometry(QRect(10, 10, 51, 31));
        label_34->setFont(font);
        label_34->setFrameShape(QFrame::Panel);
        label_34->setFrameShadow(QFrame::Sunken);
        label_34->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        tabWidget = new QTabWidget(frame);
        tabWidget->setObjectName("tabWidget");
        tabWidget->setGeometry(QRect(10, 50, 341, 191));
        tab = new QWidget();
        tab->setObjectName("tab");
        label_51 = new QLabel(tab);
        label_51->setObjectName("label_51");
        label_51->setGeometry(QRect(10, 60, 71, 21));
        label_51->setFrameShape(QFrame::Panel);
        label_51->setFrameShadow(QFrame::Sunken);
        label_51->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_66 = new QLabel(tab);
        label_66->setObjectName("label_66");
        label_66->setGeometry(QRect(10, 10, 70, 21));
        label_66->setFrameShape(QFrame::Panel);
        label_66->setFrameShadow(QFrame::Sunken);
        label_66->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditNMergin = new QSpinBox(tab);
        EditNMergin->setObjectName("EditNMergin");
        EditNMergin->setGeometry(QRect(20, 30, 61, 22));
        EditNMergin->setMaximum(99999999);
        frameNarrowPanel = new QFrame(tab);
        frameNarrowPanel->setObjectName("frameNarrowPanel");
        frameNarrowPanel->setGeometry(QRect(90, 10, 231, 151));
        frameNarrowPanel->setFrameShape(QFrame::NoFrame);
        frameNarrowPanel->setFrameShadow(QFrame::Raised);
        EditNOKDot = new QSpinBox(tab);
        EditNOKDot->setObjectName("EditNOKDot");
        EditNOKDot->setGeometry(QRect(20, 80, 61, 22));
        EditNOKDot->setMaximum(99999999);
        label_36 = new QLabel(tab);
        label_36->setObjectName("label_36");
        label_36->setGeometry(QRect(10, 110, 81, 21));
        label_36->setFrameShape(QFrame::Panel);
        label_36->setFrameShadow(QFrame::Sunken);
        label_36->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditNMinNGCount = new QSpinBox(tab);
        EditNMinNGCount->setObjectName("EditNMinNGCount");
        EditNMinNGCount->setGeometry(QRect(10, 130, 81, 22));
        EditNMinNGCount->setMaximum(99999999);
        tabWidget->addTab(tab, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName("tab_2");
        label_54 = new QLabel(tab_2);
        label_54->setObjectName("label_54");
        label_54->setGeometry(QRect(10, 60, 71, 21));
        label_54->setFrameShape(QFrame::Panel);
        label_54->setFrameShadow(QFrame::Sunken);
        label_54->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        frameBroadPanel = new QFrame(tab_2);
        frameBroadPanel->setObjectName("frameBroadPanel");
        frameBroadPanel->setGeometry(QRect(90, 10, 231, 151));
        frameBroadPanel->setFrameShape(QFrame::NoFrame);
        frameBroadPanel->setFrameShadow(QFrame::Raised);
        label_55 = new QLabel(tab_2);
        label_55->setObjectName("label_55");
        label_55->setGeometry(QRect(10, 10, 70, 21));
        label_55->setFrameShape(QFrame::Panel);
        label_55->setFrameShadow(QFrame::Sunken);
        label_55->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditBOKDot = new QSpinBox(tab_2);
        EditBOKDot->setObjectName("EditBOKDot");
        EditBOKDot->setGeometry(QRect(20, 80, 61, 22));
        EditBOKDot->setMaximum(99999999);
        EditBMergin = new QSpinBox(tab_2);
        EditBMergin->setObjectName("EditBMergin");
        EditBMergin->setGeometry(QRect(20, 30, 61, 22));
        EditBMergin->setMaximum(99999999);
        EditBMinNGCount = new QSpinBox(tab_2);
        EditBMinNGCount->setObjectName("EditBMinNGCount");
        EditBMinNGCount->setGeometry(QRect(10, 130, 81, 22));
        EditBMinNGCount->setMaximum(99999999);
        label_37 = new QLabel(tab_2);
        label_37->setObjectName("label_37");
        label_37->setGeometry(QRect(10, 110, 81, 21));
        label_37->setFrameShape(QFrame::Panel);
        label_37->setFrameShadow(QFrame::Sunken);
        label_37->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        tabWidget->addTab(tab_2, QString());
        tableWidgetBlockInfo = new QTableWidget(page_2);
        if (tableWidgetBlockInfo->columnCount() < 4)
            tableWidgetBlockInfo->setColumnCount(4);
        QTableWidgetItem *__qtablewidgetitem4 = new QTableWidgetItem();
        tableWidgetBlockInfo->setHorizontalHeaderItem(0, __qtablewidgetitem4);
        QTableWidgetItem *__qtablewidgetitem5 = new QTableWidgetItem();
        tableWidgetBlockInfo->setHorizontalHeaderItem(1, __qtablewidgetitem5);
        QTableWidgetItem *__qtablewidgetitem6 = new QTableWidgetItem();
        tableWidgetBlockInfo->setHorizontalHeaderItem(2, __qtablewidgetitem6);
        QTableWidgetItem *__qtablewidgetitem7 = new QTableWidgetItem();
        tableWidgetBlockInfo->setHorizontalHeaderItem(3, __qtablewidgetitem7);
        tableWidgetBlockInfo->setObjectName("tableWidgetBlockInfo");
        tableWidgetBlockInfo->setGeometry(QRect(10, 20, 381, 161));
        tableWidgetBlockInfo->setSelectionMode(QAbstractItemView::MultiSelection);
        tableWidgetBlockInfo->setSelectionBehavior(QAbstractItemView::SelectRows);
        stackedWidget->addWidget(page_2);

        retranslateUi(PropertyTrueColorBlockFormClass);

        stackedWidget->setCurrentIndex(0);
        tabWidget_2->setCurrentIndex(0);
        tabWidget->setCurrentIndex(1);


        QMetaObject::connectSlotsByName(PropertyTrueColorBlockFormClass);
    } // setupUi

    void retranslateUi(GUIFormBase *PropertyTrueColorBlockFormClass)
    {
        PropertyTrueColorBlockFormClass->setWindowTitle(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "PropertyTrueColorBlockForm", nullptr));
        toolButtonEdge->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "E", nullptr));
        toolButtonArea->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "A", nullptr));
        toolButtonInside->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "I", nullptr));
        toolButtonLibrary->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "\346\212\275\345\207\272", nullptr));
        toolButtonCreateBlock->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "\343\203\226\343\203\255\343\203\203\343\202\257", nullptr));
        QTableWidgetItem *___qtablewidgetitem = tableWidgetLibList->horizontalHeaderItem(0);
        ___qtablewidgetitem->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "ID", nullptr));
        QTableWidgetItem *___qtablewidgetitem1 = tableWidgetLibList->horizontalHeaderItem(1);
        ___qtablewidgetitem1->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "Name", nullptr));
        QTableWidgetItem *___qtablewidgetitem2 = tableWidgetGeneratedLibList->horizontalHeaderItem(0);
        ___qtablewidgetitem2->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "ID", nullptr));
        QTableWidgetItem *___qtablewidgetitem3 = tableWidgetGeneratedLibList->horizontalHeaderItem(1);
        ___qtablewidgetitem3->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "Name", nullptr));
        labelLibFolderName->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "\357\274\270\357\274\270\357\274\270", nullptr));
        pushButtonEditLibFolder->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "\345\210\206\351\241\236\351\201\270\346\212\236", nullptr));
        pushButtonSetFrom->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "=>", nullptr));
        pushButtonGetBack->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "<=", nullptr));
        pushButtonEditLibrary->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "\343\203\251\343\202\244\343\203\226\343\203\251\343\203\252\347\267\250\351\233\206", nullptr));
        ButtonPickupTest->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "\345\215\230\344\270\200\343\203\251\343\202\244\343\203\226\343\203\251\343\203\252\343\201\247\343\201\256\346\212\275\345\207\272", nullptr));
        ButtonPickupClearTest->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "\346\212\275\345\207\272\343\201\256\343\202\257\343\203\252\343\202\242", nullptr));
        ButtonGenerateLibs->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "\345\217\263\343\201\256\345\205\250\343\201\246\343\201\256\343\203\251\343\202\244\343\203\226\343\203\251\343\203\252\343\201\247\347\224\237\346\210\220", nullptr));
        label_30->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "\347\231\273\351\214\262\343\201\225\343\202\214\343\201\246\343\201\204\343\202\213\343\203\251\343\202\244\343\203\226\343\203\251\343\203\252\343\203\252\343\202\271\343\203\210", nullptr));
        label_31->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "\344\273\212\345\233\236\344\275\277\347\224\250\343\201\231\343\202\213\350\250\255\345\256\232", nullptr));
        EditLibName->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "Library Name", nullptr));
        label_18->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "\345\220\215\347\247\260", nullptr));
        EditLibID->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "12345", nullptr));
        ButtonLibSave->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "\343\203\207\343\203\274\343\202\277\343\203\231\343\203\274\343\202\271\343\201\270\343\201\256\346\233\264\346\226\260", nullptr));
        pushButtonGColor->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "Color", nullptr));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_3), QCoreApplication::translate("PropertyTrueColorBlockFormClass", "Color", nullptr));
        label_9->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "\343\203\226\343\203\255\343\203\203\343\202\257\346\234\200\345\244\247\343\202\265\343\202\244\343\202\272", nullptr));
        label_10->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "\343\203\226\343\203\255\343\203\203\343\202\257\346\234\200\345\260\217\343\202\265\343\202\244\343\202\272", nullptr));
        label_12->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "\343\203\226\343\203\255\343\203\203\343\202\257\346\234\200\345\260\217\351\235\242\347\251\215", nullptr));
        label_11->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "\343\203\226\343\203\255\343\203\203\343\202\257\346\234\200\345\244\247\351\235\242\347\251\215", nullptr));
        label_13->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "\351\231\220\347\225\214\343\202\265\343\202\244\343\202\272", nullptr));
        label_57->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "\343\202\265\n"
"\343\202\244\n"
"\343\202\272", nullptr));
        label_14->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "\350\274\252\351\203\255\343\201\213\343\202\211\343\201\256\351\226\223\351\232\224", nullptr));
        label_15->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "\343\203\216\343\202\244\343\202\272\343\202\265\343\202\244\343\202\272 \345\255\244\347\253\213\347\202\271\345\211\212\351\231\244", nullptr));
        label_16->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "\345\204\252\345\205\210\345\272\246", nullptr));
        label_56->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "\347\224\237\n"
"\346\210\220", nullptr));
        label_17->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "\343\203\216\343\202\244\343\202\272\343\202\265\343\202\244\343\202\272\343\200\200\343\203\224\343\203\263\343\203\233\343\203\274\343\203\253\345\211\212\351\231\244", nullptr));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_4), QCoreApplication::translate("PropertyTrueColorBlockFormClass", "Generate", nullptr));
        pushButtonGetBackAll->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "<<=", nullptr));
        pushButtonSetFromAll->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "=>>", nullptr));
        label_32->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "\344\275\277\347\224\250\343\201\225\343\202\214\343\201\246\343\201\204\343\202\213\343\203\226\343\203\255\343\203\203\343\202\257\346\203\205\345\240\261", nullptr));
        label_33->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "\343\203\236\343\202\246\343\202\271\343\202\253\343\203\274\343\202\275\343\203\253\344\275\215\347\275\256\343\201\256\343\203\226\343\203\255\343\203\203\343\202\257\346\203\205\345\240\261", nullptr));
        label_47->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "\350\243\234\n"
"\346\255\243", nullptr));
        label_48->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "\350\274\235\n"
"\345\272\246", nullptr));
        checkBModeAdjustable->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "\344\270\255\345\277\203\350\274\235\345\272\246\350\243\234\346\255\243\343\202\222\346\234\211\345\212\271\343\201\253\343\201\231\343\202\213", nullptr));
        label_49->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "\346\230\216\345\201\264\343\200\200\346\234\200\345\244\247\350\243\234\346\255\243\350\274\235\345\272\246\351\207\217", nullptr));
        label_50->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "\346\232\227\345\201\264\343\200\200\346\234\200\345\244\247\350\243\234\346\255\243\350\274\235\345\272\246\351\207\217", nullptr));
        label_53->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "\343\203\226\343\203\255\343\203\203\343\202\257\345\215\230\344\275\223\343\201\247\343\201\256\346\216\242\347\264\242\343\203\211\343\203\203\343\203\210\346\225\260", nullptr));
        EditLibNameInBlock->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "Library Name", nullptr));
        EditLibIDInBlock->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "12345", nullptr));
        label_34->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "\345\220\215\347\247\260", nullptr));
        label_51->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "OK\343\203\211\343\203\203\343\203\210\346\225\260", nullptr));
        label_66->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "\350\274\235\345\272\246\343\203\236\343\203\274\343\202\270\343\203\263", nullptr));
        label_36->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "NG\345\241\212\345\200\213\346\225\260", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab), QCoreApplication::translate("PropertyTrueColorBlockFormClass", "\347\213\255\345\237\237", nullptr));
        label_54->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "OK\343\203\211\343\203\203\343\203\210\346\225\260", nullptr));
        label_55->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "\350\274\235\345\272\246\343\203\236\343\203\274\343\202\270\343\203\263", nullptr));
        label_37->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "NG\345\241\212\345\200\213\346\225\260", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QCoreApplication::translate("PropertyTrueColorBlockFormClass", "\345\272\203\345\237\237", nullptr));
        QTableWidgetItem *___qtablewidgetitem4 = tableWidgetBlockInfo->horizontalHeaderItem(0);
        ___qtablewidgetitem4->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "ID", nullptr));
        QTableWidgetItem *___qtablewidgetitem5 = tableWidgetBlockInfo->horizontalHeaderItem(1);
        ___qtablewidgetitem5->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "\343\203\251\343\202\244\343\203\226\343\203\251\343\203\252\345\220\215", nullptr));
        QTableWidgetItem *___qtablewidgetitem6 = tableWidgetBlockInfo->horizontalHeaderItem(2);
        ___qtablewidgetitem6->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "\343\203\226\343\203\255\343\203\203\343\202\257\347\267\217\346\225\260", nullptr));
        QTableWidgetItem *___qtablewidgetitem7 = tableWidgetBlockInfo->horizontalHeaderItem(3);
        ___qtablewidgetitem7->setText(QCoreApplication::translate("PropertyTrueColorBlockFormClass", "\343\203\254\343\202\244\343\203\244\343\203\274\357\274\221", nullptr));
    } // retranslateUi

};

namespace Ui {
    class PropertyTrueColorBlockFormClass: public Ui_PropertyTrueColorBlockFormClass {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_PROPERTYTRUECOLORBLOCKFORM_H
