/********************************************************************************
** Form generated from reading UI file 'TrueColorCreateManualBlockForm.ui'
**
** Created by: Qt User Interface Compiler version 6.10.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_TRUECOLORCREATEMANUALBLOCKFORM_H
#define UI_TRUECOLORCREATEMANUALBLOCKFORM_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDialog>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_TrueColorCreateManualBlockFormClass
{
public:
    QTableWidget *tableWidgetLibList;
    QFrame *frameLibFolder;
    QLineEdit *EditLibName;
    QLineEdit *EditLibID;
    QLabel *label_4;
    QStackedWidget *stackedWidget;
    QWidget *page;
    QFrame *frame_17;
    QTableWidget *tableWidgetSubtractLibList;
    QPushButton *ButtonDelSubtractLib_3;
    QPushButton *ButtonAddSubtractLib_3;
    QLabel *label_65;
    QFrame *frame_16;
    QLabel *label_64;
    QComboBox *comboBGenerationCategory;
    QCheckBox *checkBTransparent;
    QCheckBox *checkBLeftPickup;
    QCheckBox *checkBOverlappedGen;
    QFrame *frame_15;
    QSpinBox *EditMinBlockSize;
    QLabel *label_58;
    QSpinBox *EditMaxBlockSize;
    QLabel *label_59;
    QSpinBox *EditMinBlockDots;
    QLabel *label_60;
    QSpinBox *EditMaxBlockDots;
    QLabel *label_61;
    QLabel *label_62;
    QSpinBox *EditLimitBlockSize;
    QLabel *label_63;
    QFrame *frame_19;
    QLabel *label_69;
    QSpinBox *EditSpaceToOutline;
    QLabel *label_70;
    QSpinBox *EditNoiseSize;
    QLabel *label_71;
    QSpinBox *EditPriority;
    QLabel *label_72;
    QFrame *frame_18;
    QLabel *label_68;
    QFrame *frameGenerate;
    QPushButton *pushButtonGColor;
    QWidget *page_2;
    QFrame *frame_25;
    QLabel *label_86;
    QFrame *frame_26;
    QLabel *label_87;
    QSpinBox *EditAdjustBlack;
    QCheckBox *checkBModeAdjustable;
    QSpinBox *EditAdjustWhite;
    QLabel *label_88;
    QLabel *label_89;
    QFrame *frame_23;
    QLabel *label_84;
    QFrame *frame_24;
    QLabel *label_85;
    QCheckBox *checkBModeOnlyMatching;
    QCheckBox *checkBModeAbsoluteBright;
    QCheckBox *checkBModeDiffer;
    QCheckBox *checkBModeCenterBrightFromParts;
    QCheckBox *checkBModeNGCluster;
    QCheckBox *checkBModeEnabled;
    QCheckBox *checkBModeInvertLogic;
    QFrame *frame_21;
    QLabel *label_78;
    QFrame *frameBroadPanel;
    QSpinBox *EditBMergin;
    QLabel *label_53;
    QSpinBox *EditBOKDot;
    QLabel *label_54;
    QSpinBox *EditBMinNGCount;
    QLabel *label_31;
    QLabel *label_41;
    QSpinBox *EditBOKLength;
    QFrame *frame_27;
    QLabel *label_90;
    QFrame *frame_28;
    QLabel *label_91;
    QSpinBox *EditSelfSearch;
    QLabel *label_92;
    QLabel *label_93;
    QCheckBox *checkBModeCommonMovable;
    QSpinBox *EditCommonMoveDot;
    QFrame *frame_20;
    QLabel *label_73;
    QFrame *frameNarrowPanel;
    QLabel *label_66;
    QSpinBox *EditNMergin;
    QLabel *label_48;
    QSpinBox *EditNOKDot;
    QLabel *label_30;
    QSpinBox *EditNMinNGCount;
    QLabel *label_40;
    QSpinBox *EditNOKLength;
    QPushButton *pushButtonOK;
    QPushButton *pushButtonCancel;

    void setupUi(QDialog *TrueColorCreateManualBlockFormClass)
    {
        if (TrueColorCreateManualBlockFormClass->objectName().isEmpty())
            TrueColorCreateManualBlockFormClass->setObjectName("TrueColorCreateManualBlockFormClass");
        TrueColorCreateManualBlockFormClass->resize(604, 686);
        tableWidgetLibList = new QTableWidget(TrueColorCreateManualBlockFormClass);
        if (tableWidgetLibList->columnCount() < 2)
            tableWidgetLibList->setColumnCount(2);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        tableWidgetLibList->setHorizontalHeaderItem(0, __qtablewidgetitem);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        tableWidgetLibList->setHorizontalHeaderItem(1, __qtablewidgetitem1);
        tableWidgetLibList->setObjectName("tableWidgetLibList");
        tableWidgetLibList->setGeometry(QRect(10, 160, 201, 141));
        tableWidgetLibList->setSelectionBehavior(QAbstractItemView::SelectRows);
        frameLibFolder = new QFrame(TrueColorCreateManualBlockFormClass);
        frameLibFolder->setObjectName("frameLibFolder");
        frameLibFolder->setGeometry(QRect(10, 10, 201, 141));
        frameLibFolder->setFrameShape(QFrame::StyledPanel);
        frameLibFolder->setFrameShadow(QFrame::Sunken);
        EditLibName = new QLineEdit(TrueColorCreateManualBlockFormClass);
        EditLibName->setObjectName("EditLibName");
        EditLibName->setGeometry(QRect(10, 400, 201, 31));
        QFont font;
        font.setPointSize(12);
        EditLibName->setFont(font);
        EditLibID = new QLineEdit(TrueColorCreateManualBlockFormClass);
        EditLibID->setObjectName("EditLibID");
        EditLibID->setGeometry(QRect(10, 360, 81, 31));
        EditLibID->setFont(font);
        EditLibID->setReadOnly(true);
        label_4 = new QLabel(TrueColorCreateManualBlockFormClass);
        label_4->setObjectName("label_4");
        label_4->setGeometry(QRect(10, 320, 51, 31));
        label_4->setFont(font);
        label_4->setFrameShape(QFrame::Panel);
        label_4->setFrameShadow(QFrame::Sunken);
        label_4->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        stackedWidget = new QStackedWidget(TrueColorCreateManualBlockFormClass);
        stackedWidget->setObjectName("stackedWidget");
        stackedWidget->setGeometry(QRect(220, 20, 391, 621));
        page = new QWidget();
        page->setObjectName("page");
        frame_17 = new QFrame(page);
        frame_17->setObjectName("frame_17");
        frame_17->setGeometry(QRect(0, 0, 371, 121));
        frame_17->setFrameShape(QFrame::StyledPanel);
        frame_17->setFrameShadow(QFrame::Sunken);
        tableWidgetSubtractLibList = new QTableWidget(frame_17);
        if (tableWidgetSubtractLibList->columnCount() < 2)
            tableWidgetSubtractLibList->setColumnCount(2);
        QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
        tableWidgetSubtractLibList->setHorizontalHeaderItem(0, __qtablewidgetitem2);
        QTableWidgetItem *__qtablewidgetitem3 = new QTableWidgetItem();
        tableWidgetSubtractLibList->setHorizontalHeaderItem(1, __qtablewidgetitem3);
        tableWidgetSubtractLibList->setObjectName("tableWidgetSubtractLibList");
        tableWidgetSubtractLibList->setGeometry(QRect(60, 10, 191, 101));
        tableWidgetSubtractLibList->setSelectionMode(QAbstractItemView::SingleSelection);
        tableWidgetSubtractLibList->setSelectionBehavior(QAbstractItemView::SelectRows);
        ButtonDelSubtractLib_3 = new QPushButton(frame_17);
        ButtonDelSubtractLib_3->setObjectName("ButtonDelSubtractLib_3");
        ButtonDelSubtractLib_3->setGeometry(QRect(260, 60, 101, 31));
        ButtonAddSubtractLib_3 = new QPushButton(frame_17);
        ButtonAddSubtractLib_3->setObjectName("ButtonAddSubtractLib_3");
        ButtonAddSubtractLib_3->setGeometry(QRect(260, 20, 101, 31));
        label_65 = new QLabel(frame_17);
        label_65->setObjectName("label_65");
        label_65->setGeometry(QRect(0, 0, 20, 121));
        label_65->setFrameShape(QFrame::Panel);
        label_65->setFrameShadow(QFrame::Raised);
        label_65->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_65->setIndent(1);
        frame_16 = new QFrame(page);
        frame_16->setObjectName("frame_16");
        frame_16->setGeometry(QRect(0, 510, 371, 71));
        frame_16->setFrameShape(QFrame::StyledPanel);
        frame_16->setFrameShadow(QFrame::Sunken);
        label_64 = new QLabel(frame_16);
        label_64->setObjectName("label_64");
        label_64->setGeometry(QRect(0, 0, 20, 71));
        label_64->setFrameShape(QFrame::Panel);
        label_64->setFrameShadow(QFrame::Raised);
        label_64->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_64->setIndent(1);
        comboBGenerationCategory = new QComboBox(frame_16);
        comboBGenerationCategory->addItem(QString());
        comboBGenerationCategory->addItem(QString());
        comboBGenerationCategory->addItem(QString());
        comboBGenerationCategory->addItem(QString());
        comboBGenerationCategory->addItem(QString());
        comboBGenerationCategory->addItem(QString());
        comboBGenerationCategory->addItem(QString());
        comboBGenerationCategory->addItem(QString());
        comboBGenerationCategory->setObjectName("comboBGenerationCategory");
        comboBGenerationCategory->setGeometry(QRect(30, 10, 111, 22));
        checkBTransparent = new QCheckBox(frame_16);
        checkBTransparent->setObjectName("checkBTransparent");
        checkBTransparent->setGeometry(QRect(160, 10, 161, 18));
        checkBLeftPickup = new QCheckBox(frame_16);
        checkBLeftPickup->setObjectName("checkBLeftPickup");
        checkBLeftPickup->setGeometry(QRect(160, 30, 161, 18));
        checkBOverlappedGen = new QCheckBox(frame_16);
        checkBOverlappedGen->setObjectName("checkBOverlappedGen");
        checkBOverlappedGen->setGeometry(QRect(160, 50, 161, 18));
        frame_15 = new QFrame(page);
        frame_15->setObjectName("frame_15");
        frame_15->setGeometry(QRect(0, 270, 371, 141));
        frame_15->setFrameShape(QFrame::StyledPanel);
        frame_15->setFrameShadow(QFrame::Sunken);
        EditMinBlockSize = new QSpinBox(frame_15);
        EditMinBlockSize->setObjectName("EditMinBlockSize");
        EditMinBlockSize->setGeometry(QRect(160, 10, 81, 22));
        EditMinBlockSize->setMaximum(1000000);
        label_58 = new QLabel(frame_15);
        label_58->setObjectName("label_58");
        label_58->setGeometry(QRect(30, 30, 111, 21));
        label_58->setFrameShape(QFrame::Panel);
        label_58->setFrameShadow(QFrame::Sunken);
        label_58->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditMaxBlockSize = new QSpinBox(frame_15);
        EditMaxBlockSize->setObjectName("EditMaxBlockSize");
        EditMaxBlockSize->setGeometry(QRect(160, 30, 81, 22));
        EditMaxBlockSize->setMaximum(1000000);
        label_59 = new QLabel(frame_15);
        label_59->setObjectName("label_59");
        label_59->setGeometry(QRect(30, 10, 111, 21));
        label_59->setFrameShape(QFrame::Panel);
        label_59->setFrameShadow(QFrame::Sunken);
        label_59->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditMinBlockDots = new QSpinBox(frame_15);
        EditMinBlockDots->setObjectName("EditMinBlockDots");
        EditMinBlockDots->setGeometry(QRect(160, 60, 101, 22));
        EditMinBlockDots->setMaximum(2000000000);
        label_60 = new QLabel(frame_15);
        label_60->setObjectName("label_60");
        label_60->setGeometry(QRect(30, 60, 111, 21));
        label_60->setFrameShape(QFrame::Panel);
        label_60->setFrameShadow(QFrame::Sunken);
        label_60->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditMaxBlockDots = new QSpinBox(frame_15);
        EditMaxBlockDots->setObjectName("EditMaxBlockDots");
        EditMaxBlockDots->setGeometry(QRect(160, 80, 101, 22));
        EditMaxBlockDots->setMaximum(2000000000);
        EditMaxBlockDots->setValue(2000000000);
        label_61 = new QLabel(frame_15);
        label_61->setObjectName("label_61");
        label_61->setGeometry(QRect(30, 80, 111, 21));
        label_61->setFrameShape(QFrame::Panel);
        label_61->setFrameShadow(QFrame::Sunken);
        label_61->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_62 = new QLabel(frame_15);
        label_62->setObjectName("label_62");
        label_62->setGeometry(QRect(30, 110, 111, 21));
        label_62->setFrameShape(QFrame::Panel);
        label_62->setFrameShadow(QFrame::Sunken);
        label_62->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditLimitBlockSize = new QSpinBox(frame_15);
        EditLimitBlockSize->setObjectName("EditLimitBlockSize");
        EditLimitBlockSize->setGeometry(QRect(160, 110, 61, 22));
        EditLimitBlockSize->setMaximum(99999);
        label_63 = new QLabel(frame_15);
        label_63->setObjectName("label_63");
        label_63->setGeometry(QRect(0, 0, 20, 141));
        label_63->setFrameShape(QFrame::Panel);
        label_63->setFrameShadow(QFrame::Raised);
        label_63->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_63->setIndent(1);
        frame_19 = new QFrame(page);
        frame_19->setObjectName("frame_19");
        frame_19->setGeometry(QRect(0, 420, 371, 81));
        frame_19->setFrameShape(QFrame::StyledPanel);
        frame_19->setFrameShadow(QFrame::Sunken);
        label_69 = new QLabel(frame_19);
        label_69->setObjectName("label_69");
        label_69->setGeometry(QRect(30, 10, 111, 21));
        label_69->setFrameShape(QFrame::Panel);
        label_69->setFrameShadow(QFrame::Sunken);
        label_69->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditSpaceToOutline = new QSpinBox(frame_19);
        EditSpaceToOutline->setObjectName("EditSpaceToOutline");
        EditSpaceToOutline->setGeometry(QRect(160, 10, 61, 23));
        label_70 = new QLabel(frame_19);
        label_70->setObjectName("label_70");
        label_70->setGeometry(QRect(30, 30, 111, 21));
        label_70->setFrameShape(QFrame::Panel);
        label_70->setFrameShadow(QFrame::Sunken);
        label_70->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditNoiseSize = new QSpinBox(frame_19);
        EditNoiseSize->setObjectName("EditNoiseSize");
        EditNoiseSize->setGeometry(QRect(160, 30, 61, 23));
        QFont font1;
        font1.setPointSize(9);
        EditNoiseSize->setFont(font1);
        label_71 = new QLabel(frame_19);
        label_71->setObjectName("label_71");
        label_71->setGeometry(QRect(30, 50, 111, 21));
        label_71->setFrameShape(QFrame::Panel);
        label_71->setFrameShadow(QFrame::Sunken);
        label_71->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditPriority = new QSpinBox(frame_19);
        EditPriority->setObjectName("EditPriority");
        EditPriority->setGeometry(QRect(160, 50, 61, 23));
        EditPriority->setFont(font1);
        label_72 = new QLabel(frame_19);
        label_72->setObjectName("label_72");
        label_72->setGeometry(QRect(0, 0, 20, 81));
        label_72->setFrameShape(QFrame::Panel);
        label_72->setFrameShadow(QFrame::Raised);
        label_72->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_72->setIndent(1);
        frame_18 = new QFrame(page);
        frame_18->setObjectName("frame_18");
        frame_18->setGeometry(QRect(0, 130, 371, 131));
        frame_18->setFrameShape(QFrame::StyledPanel);
        frame_18->setFrameShadow(QFrame::Sunken);
        label_68 = new QLabel(frame_18);
        label_68->setObjectName("label_68");
        label_68->setGeometry(QRect(0, 0, 20, 131));
        label_68->setFrameShape(QFrame::Panel);
        label_68->setFrameShadow(QFrame::Raised);
        label_68->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_68->setIndent(1);
        frameGenerate = new QFrame(frame_18);
        frameGenerate->setObjectName("frameGenerate");
        frameGenerate->setGeometry(QRect(130, 0, 211, 131));
        frameGenerate->setFrameShape(QFrame::NoFrame);
        frameGenerate->setFrameShadow(QFrame::Raised);
        pushButtonGColor = new QPushButton(frame_18);
        pushButtonGColor->setObjectName("pushButtonGColor");
        pushButtonGColor->setGeometry(QRect(30, 80, 61, 40));
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/Qtres/Color.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        pushButtonGColor->setIcon(icon);
        stackedWidget->addWidget(page);
        page_2 = new QWidget();
        page_2->setObjectName("page_2");
        frame_25 = new QFrame(page_2);
        frame_25->setObjectName("frame_25");
        frame_25->setGeometry(QRect(0, 450, 371, 81));
        frame_25->setFrameShape(QFrame::StyledPanel);
        frame_25->setFrameShadow(QFrame::Sunken);
        label_86 = new QLabel(frame_25);
        label_86->setObjectName("label_86");
        label_86->setGeometry(QRect(0, 0, 20, 81));
        label_86->setFrameShape(QFrame::Panel);
        label_86->setFrameShadow(QFrame::Raised);
        label_86->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_86->setIndent(1);
        frame_26 = new QFrame(frame_25);
        frame_26->setObjectName("frame_26");
        frame_26->setGeometry(QRect(10, 120, 371, 101));
        frame_26->setFrameShape(QFrame::StyledPanel);
        frame_26->setFrameShadow(QFrame::Sunken);
        label_87 = new QLabel(frame_26);
        label_87->setObjectName("label_87");
        label_87->setGeometry(QRect(0, 0, 20, 61));
        label_87->setFrameShape(QFrame::Panel);
        label_87->setFrameShadow(QFrame::Raised);
        label_87->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_87->setIndent(1);
        EditAdjustBlack = new QSpinBox(frame_25);
        EditAdjustBlack->setObjectName("EditAdjustBlack");
        EditAdjustBlack->setGeometry(QRect(240, 30, 81, 22));
        EditAdjustBlack->setMaximum(255);
        checkBModeAdjustable = new QCheckBox(frame_25);
        checkBModeAdjustable->setObjectName("checkBModeAdjustable");
        checkBModeAdjustable->setGeometry(QRect(40, 10, 241, 18));
        EditAdjustWhite = new QSpinBox(frame_25);
        EditAdjustWhite->setObjectName("EditAdjustWhite");
        EditAdjustWhite->setGeometry(QRect(240, 50, 81, 22));
        EditAdjustWhite->setMaximum(255);
        label_88 = new QLabel(frame_25);
        label_88->setObjectName("label_88");
        label_88->setGeometry(QRect(30, 50, 201, 21));
        label_88->setFrameShape(QFrame::Panel);
        label_88->setFrameShadow(QFrame::Sunken);
        label_88->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_89 = new QLabel(frame_25);
        label_89->setObjectName("label_89");
        label_89->setGeometry(QRect(30, 30, 201, 21));
        label_89->setFrameShape(QFrame::Panel);
        label_89->setFrameShadow(QFrame::Sunken);
        label_89->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        frame_23 = new QFrame(page_2);
        frame_23->setObjectName("frame_23");
        frame_23->setGeometry(QRect(0, 350, 371, 91));
        frame_23->setFrameShape(QFrame::StyledPanel);
        frame_23->setFrameShadow(QFrame::Sunken);
        label_84 = new QLabel(frame_23);
        label_84->setObjectName("label_84");
        label_84->setGeometry(QRect(0, 0, 20, 91));
        label_84->setFrameShape(QFrame::Panel);
        label_84->setFrameShadow(QFrame::Raised);
        label_84->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_84->setIndent(1);
        frame_24 = new QFrame(frame_23);
        frame_24->setObjectName("frame_24");
        frame_24->setGeometry(QRect(10, 120, 371, 101));
        frame_24->setFrameShape(QFrame::StyledPanel);
        frame_24->setFrameShadow(QFrame::Sunken);
        label_85 = new QLabel(frame_24);
        label_85->setObjectName("label_85");
        label_85->setGeometry(QRect(0, 0, 20, 61));
        label_85->setFrameShape(QFrame::Panel);
        label_85->setFrameShadow(QFrame::Raised);
        label_85->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_85->setIndent(1);
        checkBModeOnlyMatching = new QCheckBox(frame_23);
        checkBModeOnlyMatching->setObjectName("checkBModeOnlyMatching");
        checkBModeOnlyMatching->setGeometry(QRect(190, 10, 141, 18));
        checkBModeAbsoluteBright = new QCheckBox(frame_23);
        checkBModeAbsoluteBright->setObjectName("checkBModeAbsoluteBright");
        checkBModeAbsoluteBright->setGeometry(QRect(40, 30, 141, 18));
        checkBModeDiffer = new QCheckBox(frame_23);
        checkBModeDiffer->setObjectName("checkBModeDiffer");
        checkBModeDiffer->setGeometry(QRect(40, 70, 141, 18));
        checkBModeCenterBrightFromParts = new QCheckBox(frame_23);
        checkBModeCenterBrightFromParts->setObjectName("checkBModeCenterBrightFromParts");
        checkBModeCenterBrightFromParts->setGeometry(QRect(190, 70, 141, 18));
        checkBModeNGCluster = new QCheckBox(frame_23);
        checkBModeNGCluster->setObjectName("checkBModeNGCluster");
        checkBModeNGCluster->setGeometry(QRect(40, 50, 141, 18));
        checkBModeEnabled = new QCheckBox(frame_23);
        checkBModeEnabled->setObjectName("checkBModeEnabled");
        checkBModeEnabled->setGeometry(QRect(40, 10, 141, 18));
        checkBModeInvertLogic = new QCheckBox(frame_23);
        checkBModeInvertLogic->setObjectName("checkBModeInvertLogic");
        checkBModeInvertLogic->setGeometry(QRect(190, 30, 141, 18));
        frame_21 = new QFrame(page_2);
        frame_21->setObjectName("frame_21");
        frame_21->setGeometry(QRect(0, 170, 371, 171));
        frame_21->setFrameShape(QFrame::StyledPanel);
        frame_21->setFrameShadow(QFrame::Sunken);
        label_78 = new QLabel(frame_21);
        label_78->setObjectName("label_78");
        label_78->setGeometry(QRect(0, 0, 20, 171));
        label_78->setFrameShape(QFrame::Panel);
        label_78->setFrameShadow(QFrame::Raised);
        label_78->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_78->setIndent(1);
        frameBroadPanel = new QFrame(frame_21);
        frameBroadPanel->setObjectName("frameBroadPanel");
        frameBroadPanel->setGeometry(QRect(150, 10, 211, 121));
        frameBroadPanel->setFrameShape(QFrame::NoFrame);
        frameBroadPanel->setFrameShadow(QFrame::Raised);
        EditBMergin = new QSpinBox(frame_21);
        EditBMergin->setObjectName("EditBMergin");
        EditBMergin->setGeometry(QRect(50, 20, 61, 22));
        EditBMergin->setMaximum(99999999);
        label_53 = new QLabel(frame_21);
        label_53->setObjectName("label_53");
        label_53->setGeometry(QRect(40, 50, 71, 21));
        label_53->setFrameShape(QFrame::Panel);
        label_53->setFrameShadow(QFrame::Sunken);
        label_53->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditBOKDot = new QSpinBox(frame_21);
        EditBOKDot->setObjectName("EditBOKDot");
        EditBOKDot->setGeometry(QRect(50, 70, 61, 22));
        EditBOKDot->setMaximum(99999999);
        label_54 = new QLabel(frame_21);
        label_54->setObjectName("label_54");
        label_54->setGeometry(QRect(40, 0, 70, 21));
        label_54->setFrameShape(QFrame::Panel);
        label_54->setFrameShadow(QFrame::Sunken);
        label_54->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditBMinNGCount = new QSpinBox(frame_21);
        EditBMinNGCount->setObjectName("EditBMinNGCount");
        EditBMinNGCount->setGeometry(QRect(40, 120, 81, 22));
        EditBMinNGCount->setMaximum(99999999);
        label_31 = new QLabel(frame_21);
        label_31->setObjectName("label_31");
        label_31->setGeometry(QRect(40, 100, 81, 21));
        label_31->setFrameShape(QFrame::Panel);
        label_31->setFrameShadow(QFrame::Sunken);
        label_31->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_41 = new QLabel(frame_21);
        label_41->setObjectName("label_41");
        label_41->setGeometry(QRect(150, 140, 121, 21));
        label_41->setFrameShape(QFrame::Panel);
        label_41->setFrameShadow(QFrame::Sunken);
        label_41->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditBOKLength = new QSpinBox(frame_21);
        EditBOKLength->setObjectName("EditBOKLength");
        EditBOKLength->setGeometry(QRect(270, 140, 81, 22));
        EditBOKLength->setMaximum(99999999);
        frame_27 = new QFrame(page_2);
        frame_27->setObjectName("frame_27");
        frame_27->setGeometry(QRect(0, 540, 371, 81));
        frame_27->setFrameShape(QFrame::StyledPanel);
        frame_27->setFrameShadow(QFrame::Sunken);
        label_90 = new QLabel(frame_27);
        label_90->setObjectName("label_90");
        label_90->setGeometry(QRect(0, 0, 20, 81));
        label_90->setFrameShape(QFrame::Panel);
        label_90->setFrameShadow(QFrame::Raised);
        label_90->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_90->setIndent(1);
        frame_28 = new QFrame(frame_27);
        frame_28->setObjectName("frame_28");
        frame_28->setGeometry(QRect(10, 120, 371, 101));
        frame_28->setFrameShape(QFrame::StyledPanel);
        frame_28->setFrameShadow(QFrame::Sunken);
        label_91 = new QLabel(frame_28);
        label_91->setObjectName("label_91");
        label_91->setGeometry(QRect(0, 0, 20, 61));
        label_91->setFrameShape(QFrame::Panel);
        label_91->setFrameShadow(QFrame::Raised);
        label_91->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_91->setIndent(1);
        EditSelfSearch = new QSpinBox(frame_27);
        EditSelfSearch->setObjectName("EditSelfSearch");
        EditSelfSearch->setGeometry(QRect(260, 30, 81, 22));
        label_92 = new QLabel(frame_27);
        label_92->setObjectName("label_92");
        label_92->setGeometry(QRect(50, 30, 201, 21));
        label_92->setFrameShape(QFrame::Panel);
        label_92->setFrameShadow(QFrame::Sunken);
        label_92->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_93 = new QLabel(frame_27);
        label_93->setObjectName("label_93");
        label_93->setGeometry(QRect(50, 50, 201, 21));
        label_93->setFrameShape(QFrame::Panel);
        label_93->setFrameShadow(QFrame::Sunken);
        label_93->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        checkBModeCommonMovable = new QCheckBox(frame_27);
        checkBModeCommonMovable->setObjectName("checkBModeCommonMovable");
        checkBModeCommonMovable->setGeometry(QRect(40, 10, 231, 18));
        EditCommonMoveDot = new QSpinBox(frame_27);
        EditCommonMoveDot->setObjectName("EditCommonMoveDot");
        EditCommonMoveDot->setGeometry(QRect(260, 50, 81, 22));
        frame_20 = new QFrame(page_2);
        frame_20->setObjectName("frame_20");
        frame_20->setGeometry(QRect(0, 0, 371, 171));
        frame_20->setFrameShape(QFrame::StyledPanel);
        frame_20->setFrameShadow(QFrame::Sunken);
        label_73 = new QLabel(frame_20);
        label_73->setObjectName("label_73");
        label_73->setGeometry(QRect(0, 0, 20, 171));
        label_73->setFrameShape(QFrame::Panel);
        label_73->setFrameShadow(QFrame::Raised);
        label_73->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_73->setIndent(1);
        frameNarrowPanel = new QFrame(frame_20);
        frameNarrowPanel->setObjectName("frameNarrowPanel");
        frameNarrowPanel->setGeometry(QRect(150, 10, 211, 121));
        frameNarrowPanel->setFrameShape(QFrame::NoFrame);
        frameNarrowPanel->setFrameShadow(QFrame::Raised);
        label_66 = new QLabel(frame_20);
        label_66->setObjectName("label_66");
        label_66->setGeometry(QRect(40, 0, 70, 21));
        label_66->setFrameShape(QFrame::Panel);
        label_66->setFrameShadow(QFrame::Sunken);
        label_66->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditNMergin = new QSpinBox(frame_20);
        EditNMergin->setObjectName("EditNMergin");
        EditNMergin->setGeometry(QRect(50, 20, 61, 22));
        EditNMergin->setMaximum(99999999);
        label_48 = new QLabel(frame_20);
        label_48->setObjectName("label_48");
        label_48->setGeometry(QRect(40, 50, 71, 21));
        label_48->setFrameShape(QFrame::Panel);
        label_48->setFrameShadow(QFrame::Sunken);
        label_48->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditNOKDot = new QSpinBox(frame_20);
        EditNOKDot->setObjectName("EditNOKDot");
        EditNOKDot->setGeometry(QRect(50, 70, 61, 22));
        EditNOKDot->setMaximum(99999999);
        label_30 = new QLabel(frame_20);
        label_30->setObjectName("label_30");
        label_30->setGeometry(QRect(40, 100, 81, 21));
        label_30->setFrameShape(QFrame::Panel);
        label_30->setFrameShadow(QFrame::Sunken);
        label_30->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditNMinNGCount = new QSpinBox(frame_20);
        EditNMinNGCount->setObjectName("EditNMinNGCount");
        EditNMinNGCount->setGeometry(QRect(40, 120, 81, 22));
        EditNMinNGCount->setMaximum(99999999);
        label_40 = new QLabel(frame_20);
        label_40->setObjectName("label_40");
        label_40->setGeometry(QRect(150, 140, 121, 21));
        label_40->setFrameShape(QFrame::Panel);
        label_40->setFrameShadow(QFrame::Sunken);
        label_40->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditNOKLength = new QSpinBox(frame_20);
        EditNOKLength->setObjectName("EditNOKLength");
        EditNOKLength->setGeometry(QRect(270, 140, 81, 22));
        EditNOKLength->setMaximum(99999999);
        stackedWidget->addWidget(page_2);
        pushButtonOK = new QPushButton(TrueColorCreateManualBlockFormClass);
        pushButtonOK->setObjectName("pushButtonOK");
        pushButtonOK->setGeometry(QRect(80, 650, 91, 31));
        QIcon icon1;
        icon1.addFile(QString::fromUtf8(":/Qtres/Make.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        pushButtonOK->setIcon(icon1);
        pushButtonCancel = new QPushButton(TrueColorCreateManualBlockFormClass);
        pushButtonCancel->setObjectName("pushButtonCancel");
        pushButtonCancel->setGeometry(QRect(420, 650, 91, 31));
        QIcon icon2;
        icon2.addFile(QString::fromUtf8(":/Qtres/Cancel.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        pushButtonCancel->setIcon(icon2);

        retranslateUi(TrueColorCreateManualBlockFormClass);

        stackedWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(TrueColorCreateManualBlockFormClass);
    } // setupUi

    void retranslateUi(QDialog *TrueColorCreateManualBlockFormClass)
    {
        TrueColorCreateManualBlockFormClass->setWindowTitle(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "TrueColorCreateManualBlockForm", nullptr));
        QTableWidgetItem *___qtablewidgetitem = tableWidgetLibList->horizontalHeaderItem(0);
        ___qtablewidgetitem->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "ID", nullptr));
        QTableWidgetItem *___qtablewidgetitem1 = tableWidgetLibList->horizontalHeaderItem(1);
        ___qtablewidgetitem1->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "Name", nullptr));
        EditLibName->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "Library Name", nullptr));
        EditLibID->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "12345", nullptr));
        label_4->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "\345\220\215\347\247\260", nullptr));
        QTableWidgetItem *___qtablewidgetitem2 = tableWidgetSubtractLibList->horizontalHeaderItem(0);
        ___qtablewidgetitem2->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "ID", nullptr));
        QTableWidgetItem *___qtablewidgetitem3 = tableWidgetSubtractLibList->horizontalHeaderItem(1);
        ___qtablewidgetitem3->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "Name", nullptr));
        ButtonDelSubtractLib_3->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "\345\211\212\351\231\244", nullptr));
        ButtonAddSubtractLib_3->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "\350\277\275\345\212\240", nullptr));
        label_65->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "\351\231\244\n"
"\345\216\273", nullptr));
        label_64->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "\343\201\235\n"
"\343\201\256\n"
"\344\273\226", nullptr));
        comboBGenerationCategory->setItemText(0, QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "Pad", nullptr));
        comboBGenerationCategory->setItemText(1, QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "Hole", nullptr));
        comboBGenerationCategory->setItemText(2, QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "Silk", nullptr));
        comboBGenerationCategory->setItemText(3, QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "Resist", nullptr));
        comboBGenerationCategory->setItemText(4, QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "OtherMask", nullptr));
        comboBGenerationCategory->setItemText(5, QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "FinePad", nullptr));
        comboBGenerationCategory->setItemText(6, QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "Surround", nullptr));
        comboBGenerationCategory->setItemText(7, QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "Any", nullptr));

        checkBTransparent->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "\346\216\222\344\273\226\347\224\237\346\210\220", nullptr));
        checkBLeftPickup->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "\346\256\213\343\202\250\343\203\252\343\202\242", nullptr));
        checkBOverlappedGen->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "\351\207\215\350\244\207\347\224\237\346\210\220", nullptr));
        label_58->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "\343\203\226\343\203\255\343\203\203\343\202\257\346\234\200\345\244\247\343\202\265\343\202\244\343\202\272", nullptr));
        label_59->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "\343\203\226\343\203\255\343\203\203\343\202\257\346\234\200\345\260\217\343\202\265\343\202\244\343\202\272", nullptr));
        label_60->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "\343\203\226\343\203\255\343\203\203\343\202\257\346\234\200\345\260\217\351\235\242\347\251\215", nullptr));
        label_61->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "\343\203\226\343\203\255\343\203\203\343\202\257\346\234\200\345\244\247\351\235\242\347\251\215", nullptr));
        label_62->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "\351\231\220\347\225\214\343\202\265\343\202\244\343\202\272", nullptr));
        label_63->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "\343\202\265\n"
"\343\202\244\n"
"\343\202\272", nullptr));
        label_69->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "\350\274\252\351\203\255\343\201\213\343\202\211\343\201\256\351\226\223\351\232\224", nullptr));
        label_70->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "\343\203\216\343\202\244\343\202\272\343\202\265\343\202\244\343\202\272", nullptr));
        label_71->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "\345\204\252\345\205\210\345\272\246", nullptr));
        label_72->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "\347\224\237\n"
"\346\210\220", nullptr));
        label_68->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "\350\274\235\n"
"\345\272\246", nullptr));
        pushButtonGColor->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "Color", nullptr));
        label_86->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "\350\243\234\n"
"\346\255\243", nullptr));
        label_87->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "\350\274\235\n"
"\345\272\246", nullptr));
        checkBModeAdjustable->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "\344\270\255\345\277\203\350\274\235\345\272\246\350\243\234\346\255\243\343\202\222\346\234\211\345\212\271\343\201\253\343\201\231\343\202\213", nullptr));
        label_88->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "\346\230\216\345\201\264\343\200\200\346\234\200\345\244\247\350\243\234\346\255\243\350\274\235\345\272\246\351\207\217", nullptr));
        label_89->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "\346\232\227\345\201\264\343\200\200\346\234\200\345\244\247\350\243\234\346\255\243\350\274\235\345\272\246\351\207\217", nullptr));
        label_84->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "\345\261\236\n"
"\346\200\247", nullptr));
        label_85->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "\350\274\235\n"
"\345\272\246", nullptr));
        checkBModeOnlyMatching->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "\347\265\220\346\236\234\345\207\272\345\212\233\343\201\227\343\201\252\343\201\204", nullptr));
        checkBModeAbsoluteBright->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "\347\265\266\345\257\276\350\274\235\345\272\246", nullptr));
        checkBModeDiffer->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "\345\267\256\345\210\206\346\244\234\346\237\273", nullptr));
        checkBModeCenterBrightFromParts->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "\351\203\250\345\223\201\343\201\213\343\202\211\350\274\235\345\272\246\343\202\222\346\212\275\345\207\272\343\201\231\343\202\213", nullptr));
        checkBModeNGCluster->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "\345\241\212\346\244\234\346\237\273", nullptr));
        checkBModeEnabled->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "\346\244\234\346\237\273\346\234\211\345\212\271", nullptr));
        checkBModeInvertLogic->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "\350\253\226\347\220\206\345\217\215\350\273\242", nullptr));
        label_78->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "\345\272\203\n"
"\345\237\237", nullptr));
        label_53->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "OK\343\203\211\343\203\203\343\203\210\346\225\260", nullptr));
        label_54->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "\350\274\235\345\272\246\343\203\236\343\203\274\343\202\270\343\203\263", nullptr));
        label_31->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "NG\345\241\212\345\200\213\346\225\260", nullptr));
        label_41->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "\343\201\223\343\202\214\344\273\245\344\270\212\343\201\256\351\225\267\343\201\225\343\201\247\357\274\256\357\274\247", nullptr));
        label_90->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "\346\216\242\n"
"\347\264\242", nullptr));
        label_91->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "\350\274\235\n"
"\345\272\246", nullptr));
        label_92->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "\343\203\226\343\203\255\343\203\203\343\202\257\345\215\230\344\275\223\343\201\247\343\201\256\346\216\242\347\264\242\343\203\211\343\203\203\343\203\210\346\225\260", nullptr));
        label_93->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "\345\205\250\344\275\223\343\201\247\343\201\256\346\216\242\347\264\242\343\203\211\343\203\203\343\203\210\346\225\260", nullptr));
        checkBModeCommonMovable->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "\345\205\250\344\275\223\343\201\247\343\201\256\346\216\242\347\264\242\343\202\222\346\234\211\345\212\271\343\201\253\343\201\231\343\202\213", nullptr));
        label_73->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "\347\213\255\n"
"\345\237\237", nullptr));
        label_66->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "\350\274\235\345\272\246\343\203\236\343\203\274\343\202\270\343\203\263", nullptr));
        label_48->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "OK\343\203\211\343\203\203\343\203\210\346\225\260", nullptr));
        label_30->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "NG\345\241\212\345\200\213\346\225\260", nullptr));
        label_40->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "\343\201\223\343\202\214\344\273\245\344\270\212\343\201\256\351\225\267\343\201\225\343\201\247\357\274\256\357\274\247", nullptr));
        pushButtonOK->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "\344\275\234\346\210\220", nullptr));
        pushButtonCancel->setText(QCoreApplication::translate("TrueColorCreateManualBlockFormClass", "\343\202\255\343\203\243\343\203\263\343\202\273\343\203\253", nullptr));
    } // retranslateUi

};

namespace Ui {
    class TrueColorCreateManualBlockFormClass: public Ui_TrueColorCreateManualBlockFormClass {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_TRUECOLORCREATEMANUALBLOCKFORM_H
