#ifndef BUTTONLOADMATRIXCELL_GLOBAL_H
#define BUTTONLOADMATRIXCELL_GLOBAL_H

#include <qglobal.h>

#ifdef BUTTONLOADMATRIXCELL_LIB
# define BUTTONLOADMATRIXCELL_EXPORT Q_DECL_EXPORT
#else
# define BUTTONLOADMATRIXCELL_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONLOADMATRIXCELL_GLOBAL_H
