#ifndef FILTERVERTICALREVERSE_GLOBAL_H
#define FILTERVERTICALREVERSE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef FILTERVERTICALREVERSE_LIB
# define FILTERVERTICALREVERSE_EXPORT Q_DECL_EXPORT
#else
# define FILTERVERTICALREVERSE_EXPORT Q_DECL_IMPORT
#endif

#endif // FILTERVERTICALREVERSE_GLOBAL_H
