/********************************************************************************
** Form generated from reading UI file 'GioTestModeDialog.ui'
**
** Created by: Qt User Interface Compiler version 5.15.13
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_GIOTESTMODEDIALOG_H
#define UI_GIOTESTMODEDIALOG_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QDialog>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QPushButton>

QT_BEGIN_NAMESPACE

class Ui_GioTestModeDialog
{
public:
    QGroupBox *groupBox_7;
    QCheckBox *checkBoxoGOUT0;
    QCheckBox *checkBoxoGOUT3;
    QCheckBox *checkBoxoGOUT2;
    QCheckBox *checkBoxoGOUT1;
    QCheckBox *checkBoxoGOUT7;
    QCheckBox *checkBoxoGOUT6;
    QCheckBox *checkBoxoGOUT4;
    QCheckBox *checkBoxoGOUT5;
    QGroupBox *groupBox_9;
    QCheckBox *checkBoxPIOBOUT0;
    QCheckBox *checkBoxPIOBOUT3;
    QCheckBox *checkBoxPIOBOUT2;
    QCheckBox *checkBoxPIOBOUT1;
    QGroupBox *groupBox_6;
    QCheckBox *checkBoxTRGIN0;
    QCheckBox *checkBoxTRGIN3;
    QCheckBox *checkBoxTRGIN2;
    QCheckBox *checkBoxTRGIN1;
    QGroupBox *groupBox;
    QCheckBox *checkBoxGIN0;
    QCheckBox *checkBoxGIN3;
    QCheckBox *checkBoxGIN2;
    QCheckBox *checkBoxGIN1;
    QGroupBox *groupBox_5;
    QCheckBox *checkBoxPIODIN0;
    QCheckBox *checkBoxPIODIN3;
    QCheckBox *checkBoxPIODIN2;
    QCheckBox *checkBoxPIODIN1;
    QGroupBox *groupBox_11;
    QCheckBox *checkBoxPIODOUT0;
    QCheckBox *checkBoxPIODOUT3;
    QCheckBox *checkBoxPIODOUT2;
    QCheckBox *checkBoxPIODOUT1;
    QGroupBox *groupBox_2;
    QCheckBox *checkBoxPIOAIN0;
    QCheckBox *checkBoxPIOAIN3;
    QCheckBox *checkBoxPIOAIN2;
    QCheckBox *checkBoxPIOAIN1;
    QGroupBox *groupBox_4;
    QCheckBox *checkBoxPIOCIN0;
    QCheckBox *checkBoxPIOCIN3;
    QCheckBox *checkBoxPIOCIN2;
    QCheckBox *checkBoxPIOCIN1;
    QGroupBox *groupBox_8;
    QCheckBox *checkBoxPIOAOUT0;
    QCheckBox *checkBoxPIOAOUT3;
    QCheckBox *checkBoxPIOAOUT2;
    QCheckBox *checkBoxPIOAOUT1;
    QGroupBox *groupBox_10;
    QCheckBox *checkBoxPIOCOUT0;
    QCheckBox *checkBoxPIOCOUT3;
    QCheckBox *checkBoxPIOCOUT2;
    QCheckBox *checkBoxPIOCOUT1;
    QGroupBox *groupBox_3;
    QCheckBox *checkBoxPIOBIN0;
    QCheckBox *checkBoxPIOBIN3;
    QCheckBox *checkBoxPIOBIN2;
    QCheckBox *checkBoxPIOBIN1;
    QGroupBox *groupBox_12;
    QCheckBox *checkBoxTRGCOUT0;
    QCheckBox *checkBoxTRGCOUT3;
    QCheckBox *checkBoxTRGCOUT2;
    QCheckBox *checkBoxTRGCOUT1;
    QGroupBox *groupBox_13;
    QCheckBox *checkBoxTRGDOUT0;
    QCheckBox *checkBoxTRGDOUT3;
    QCheckBox *checkBoxTRGDOUT2;
    QCheckBox *checkBoxTRGDOUT1;
    QGroupBox *groupBox_14;
    QCheckBox *checkBoxTRGBOUT0;
    QCheckBox *checkBoxTRGBOUT3;
    QCheckBox *checkBoxTRGBOUT2;
    QCheckBox *checkBoxTRGBOUT1;
    QGroupBox *groupBox_15;
    QCheckBox *checkBoxTRGAOUT0;
    QCheckBox *checkBoxTRGAOUT3;
    QCheckBox *checkBoxTRGAOUT2;
    QCheckBox *checkBoxTRGAOUT1;
    QPushButton *pushButtonClose;
    QCheckBox *checkBoxTestLEDReg;
    QCheckBox *checkBoxLEDOut0;
    QCheckBox *checkBoxLEDOut1;

    void setupUi(QDialog *GioTestModeDialog)
    {
        if (GioTestModeDialog->objectName().isEmpty())
            GioTestModeDialog->setObjectName(QString::fromUtf8("GioTestModeDialog"));
        GioTestModeDialog->resize(456, 591);
        groupBox_7 = new QGroupBox(GioTestModeDialog);
        groupBox_7->setObjectName(QString::fromUtf8("groupBox_7"));
        groupBox_7->setGeometry(QRect(0, 160, 151, 141));
        checkBoxoGOUT0 = new QCheckBox(groupBox_7);
        checkBoxoGOUT0->setObjectName(QString::fromUtf8("checkBoxoGOUT0"));
        checkBoxoGOUT0->setGeometry(QRect(10, 20, 61, 27));
        checkBoxoGOUT3 = new QCheckBox(groupBox_7);
        checkBoxoGOUT3->setObjectName(QString::fromUtf8("checkBoxoGOUT3"));
        checkBoxoGOUT3->setGeometry(QRect(10, 110, 61, 27));
        checkBoxoGOUT2 = new QCheckBox(groupBox_7);
        checkBoxoGOUT2->setObjectName(QString::fromUtf8("checkBoxoGOUT2"));
        checkBoxoGOUT2->setGeometry(QRect(10, 80, 61, 27));
        checkBoxoGOUT1 = new QCheckBox(groupBox_7);
        checkBoxoGOUT1->setObjectName(QString::fromUtf8("checkBoxoGOUT1"));
        checkBoxoGOUT1->setGeometry(QRect(10, 50, 61, 27));
        checkBoxoGOUT7 = new QCheckBox(groupBox_7);
        checkBoxoGOUT7->setObjectName(QString::fromUtf8("checkBoxoGOUT7"));
        checkBoxoGOUT7->setGeometry(QRect(80, 110, 61, 27));
        checkBoxoGOUT6 = new QCheckBox(groupBox_7);
        checkBoxoGOUT6->setObjectName(QString::fromUtf8("checkBoxoGOUT6"));
        checkBoxoGOUT6->setGeometry(QRect(80, 80, 61, 27));
        checkBoxoGOUT4 = new QCheckBox(groupBox_7);
        checkBoxoGOUT4->setObjectName(QString::fromUtf8("checkBoxoGOUT4"));
        checkBoxoGOUT4->setGeometry(QRect(80, 20, 61, 27));
        checkBoxoGOUT5 = new QCheckBox(groupBox_7);
        checkBoxoGOUT5->setObjectName(QString::fromUtf8("checkBoxoGOUT5"));
        checkBoxoGOUT5->setGeometry(QRect(80, 50, 61, 27));
        groupBox_9 = new QGroupBox(GioTestModeDialog);
        groupBox_9->setObjectName(QString::fromUtf8("groupBox_9"));
        groupBox_9->setGeometry(QRect(230, 160, 71, 141));
        checkBoxPIOBOUT0 = new QCheckBox(groupBox_9);
        checkBoxPIOBOUT0->setObjectName(QString::fromUtf8("checkBoxPIOBOUT0"));
        checkBoxPIOBOUT0->setGeometry(QRect(10, 20, 61, 27));
        checkBoxPIOBOUT3 = new QCheckBox(groupBox_9);
        checkBoxPIOBOUT3->setObjectName(QString::fromUtf8("checkBoxPIOBOUT3"));
        checkBoxPIOBOUT3->setGeometry(QRect(10, 110, 61, 27));
        checkBoxPIOBOUT2 = new QCheckBox(groupBox_9);
        checkBoxPIOBOUT2->setObjectName(QString::fromUtf8("checkBoxPIOBOUT2"));
        checkBoxPIOBOUT2->setGeometry(QRect(10, 80, 61, 27));
        checkBoxPIOBOUT1 = new QCheckBox(groupBox_9);
        checkBoxPIOBOUT1->setObjectName(QString::fromUtf8("checkBoxPIOBOUT1"));
        checkBoxPIOBOUT1->setGeometry(QRect(10, 50, 61, 27));
        groupBox_6 = new QGroupBox(GioTestModeDialog);
        groupBox_6->setObjectName(QString::fromUtf8("groupBox_6"));
        groupBox_6->setGeometry(QRect(80, 10, 71, 141));
        checkBoxTRGIN0 = new QCheckBox(groupBox_6);
        checkBoxTRGIN0->setObjectName(QString::fromUtf8("checkBoxTRGIN0"));
        checkBoxTRGIN0->setGeometry(QRect(10, 20, 61, 27));
        checkBoxTRGIN3 = new QCheckBox(groupBox_6);
        checkBoxTRGIN3->setObjectName(QString::fromUtf8("checkBoxTRGIN3"));
        checkBoxTRGIN3->setGeometry(QRect(10, 110, 61, 27));
        checkBoxTRGIN2 = new QCheckBox(groupBox_6);
        checkBoxTRGIN2->setObjectName(QString::fromUtf8("checkBoxTRGIN2"));
        checkBoxTRGIN2->setGeometry(QRect(10, 80, 61, 27));
        checkBoxTRGIN1 = new QCheckBox(groupBox_6);
        checkBoxTRGIN1->setObjectName(QString::fromUtf8("checkBoxTRGIN1"));
        checkBoxTRGIN1->setGeometry(QRect(10, 50, 61, 27));
        groupBox = new QGroupBox(GioTestModeDialog);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(0, 10, 71, 141));
        checkBoxGIN0 = new QCheckBox(groupBox);
        checkBoxGIN0->setObjectName(QString::fromUtf8("checkBoxGIN0"));
        checkBoxGIN0->setGeometry(QRect(10, 20, 61, 27));
        checkBoxGIN3 = new QCheckBox(groupBox);
        checkBoxGIN3->setObjectName(QString::fromUtf8("checkBoxGIN3"));
        checkBoxGIN3->setGeometry(QRect(10, 110, 61, 27));
        checkBoxGIN2 = new QCheckBox(groupBox);
        checkBoxGIN2->setObjectName(QString::fromUtf8("checkBoxGIN2"));
        checkBoxGIN2->setGeometry(QRect(10, 80, 61, 27));
        checkBoxGIN1 = new QCheckBox(groupBox);
        checkBoxGIN1->setObjectName(QString::fromUtf8("checkBoxGIN1"));
        checkBoxGIN1->setGeometry(QRect(10, 50, 61, 27));
        groupBox_5 = new QGroupBox(GioTestModeDialog);
        groupBox_5->setObjectName(QString::fromUtf8("groupBox_5"));
        groupBox_5->setGeometry(QRect(370, 10, 71, 141));
        checkBoxPIODIN0 = new QCheckBox(groupBox_5);
        checkBoxPIODIN0->setObjectName(QString::fromUtf8("checkBoxPIODIN0"));
        checkBoxPIODIN0->setGeometry(QRect(10, 20, 61, 27));
        checkBoxPIODIN3 = new QCheckBox(groupBox_5);
        checkBoxPIODIN3->setObjectName(QString::fromUtf8("checkBoxPIODIN3"));
        checkBoxPIODIN3->setGeometry(QRect(10, 110, 61, 27));
        checkBoxPIODIN2 = new QCheckBox(groupBox_5);
        checkBoxPIODIN2->setObjectName(QString::fromUtf8("checkBoxPIODIN2"));
        checkBoxPIODIN2->setGeometry(QRect(10, 80, 61, 27));
        checkBoxPIODIN1 = new QCheckBox(groupBox_5);
        checkBoxPIODIN1->setObjectName(QString::fromUtf8("checkBoxPIODIN1"));
        checkBoxPIODIN1->setGeometry(QRect(10, 50, 61, 27));
        groupBox_11 = new QGroupBox(GioTestModeDialog);
        groupBox_11->setObjectName(QString::fromUtf8("groupBox_11"));
        groupBox_11->setGeometry(QRect(370, 160, 71, 141));
        checkBoxPIODOUT0 = new QCheckBox(groupBox_11);
        checkBoxPIODOUT0->setObjectName(QString::fromUtf8("checkBoxPIODOUT0"));
        checkBoxPIODOUT0->setGeometry(QRect(10, 20, 61, 27));
        checkBoxPIODOUT3 = new QCheckBox(groupBox_11);
        checkBoxPIODOUT3->setObjectName(QString::fromUtf8("checkBoxPIODOUT3"));
        checkBoxPIODOUT3->setGeometry(QRect(10, 110, 61, 27));
        checkBoxPIODOUT2 = new QCheckBox(groupBox_11);
        checkBoxPIODOUT2->setObjectName(QString::fromUtf8("checkBoxPIODOUT2"));
        checkBoxPIODOUT2->setGeometry(QRect(10, 80, 61, 27));
        checkBoxPIODOUT1 = new QCheckBox(groupBox_11);
        checkBoxPIODOUT1->setObjectName(QString::fromUtf8("checkBoxPIODOUT1"));
        checkBoxPIODOUT1->setGeometry(QRect(10, 50, 61, 27));
        groupBox_2 = new QGroupBox(GioTestModeDialog);
        groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
        groupBox_2->setGeometry(QRect(160, 10, 71, 141));
        checkBoxPIOAIN0 = new QCheckBox(groupBox_2);
        checkBoxPIOAIN0->setObjectName(QString::fromUtf8("checkBoxPIOAIN0"));
        checkBoxPIOAIN0->setGeometry(QRect(10, 20, 61, 27));
        checkBoxPIOAIN3 = new QCheckBox(groupBox_2);
        checkBoxPIOAIN3->setObjectName(QString::fromUtf8("checkBoxPIOAIN3"));
        checkBoxPIOAIN3->setGeometry(QRect(10, 110, 61, 27));
        checkBoxPIOAIN2 = new QCheckBox(groupBox_2);
        checkBoxPIOAIN2->setObjectName(QString::fromUtf8("checkBoxPIOAIN2"));
        checkBoxPIOAIN2->setGeometry(QRect(10, 80, 61, 27));
        checkBoxPIOAIN1 = new QCheckBox(groupBox_2);
        checkBoxPIOAIN1->setObjectName(QString::fromUtf8("checkBoxPIOAIN1"));
        checkBoxPIOAIN1->setGeometry(QRect(10, 50, 61, 27));
        groupBox_4 = new QGroupBox(GioTestModeDialog);
        groupBox_4->setObjectName(QString::fromUtf8("groupBox_4"));
        groupBox_4->setGeometry(QRect(300, 10, 71, 141));
        checkBoxPIOCIN0 = new QCheckBox(groupBox_4);
        checkBoxPIOCIN0->setObjectName(QString::fromUtf8("checkBoxPIOCIN0"));
        checkBoxPIOCIN0->setGeometry(QRect(10, 20, 61, 27));
        checkBoxPIOCIN3 = new QCheckBox(groupBox_4);
        checkBoxPIOCIN3->setObjectName(QString::fromUtf8("checkBoxPIOCIN3"));
        checkBoxPIOCIN3->setGeometry(QRect(10, 110, 61, 27));
        checkBoxPIOCIN2 = new QCheckBox(groupBox_4);
        checkBoxPIOCIN2->setObjectName(QString::fromUtf8("checkBoxPIOCIN2"));
        checkBoxPIOCIN2->setGeometry(QRect(10, 80, 61, 27));
        checkBoxPIOCIN1 = new QCheckBox(groupBox_4);
        checkBoxPIOCIN1->setObjectName(QString::fromUtf8("checkBoxPIOCIN1"));
        checkBoxPIOCIN1->setGeometry(QRect(10, 50, 61, 27));
        groupBox_8 = new QGroupBox(GioTestModeDialog);
        groupBox_8->setObjectName(QString::fromUtf8("groupBox_8"));
        groupBox_8->setGeometry(QRect(160, 160, 71, 141));
        checkBoxPIOAOUT0 = new QCheckBox(groupBox_8);
        checkBoxPIOAOUT0->setObjectName(QString::fromUtf8("checkBoxPIOAOUT0"));
        checkBoxPIOAOUT0->setGeometry(QRect(10, 20, 61, 27));
        checkBoxPIOAOUT3 = new QCheckBox(groupBox_8);
        checkBoxPIOAOUT3->setObjectName(QString::fromUtf8("checkBoxPIOAOUT3"));
        checkBoxPIOAOUT3->setGeometry(QRect(10, 110, 61, 27));
        checkBoxPIOAOUT2 = new QCheckBox(groupBox_8);
        checkBoxPIOAOUT2->setObjectName(QString::fromUtf8("checkBoxPIOAOUT2"));
        checkBoxPIOAOUT2->setGeometry(QRect(10, 80, 61, 27));
        checkBoxPIOAOUT1 = new QCheckBox(groupBox_8);
        checkBoxPIOAOUT1->setObjectName(QString::fromUtf8("checkBoxPIOAOUT1"));
        checkBoxPIOAOUT1->setGeometry(QRect(10, 50, 61, 27));
        groupBox_10 = new QGroupBox(GioTestModeDialog);
        groupBox_10->setObjectName(QString::fromUtf8("groupBox_10"));
        groupBox_10->setGeometry(QRect(300, 160, 71, 141));
        checkBoxPIOCOUT0 = new QCheckBox(groupBox_10);
        checkBoxPIOCOUT0->setObjectName(QString::fromUtf8("checkBoxPIOCOUT0"));
        checkBoxPIOCOUT0->setGeometry(QRect(10, 20, 61, 27));
        checkBoxPIOCOUT3 = new QCheckBox(groupBox_10);
        checkBoxPIOCOUT3->setObjectName(QString::fromUtf8("checkBoxPIOCOUT3"));
        checkBoxPIOCOUT3->setGeometry(QRect(10, 110, 61, 27));
        checkBoxPIOCOUT2 = new QCheckBox(groupBox_10);
        checkBoxPIOCOUT2->setObjectName(QString::fromUtf8("checkBoxPIOCOUT2"));
        checkBoxPIOCOUT2->setGeometry(QRect(10, 80, 61, 27));
        checkBoxPIOCOUT1 = new QCheckBox(groupBox_10);
        checkBoxPIOCOUT1->setObjectName(QString::fromUtf8("checkBoxPIOCOUT1"));
        checkBoxPIOCOUT1->setGeometry(QRect(10, 50, 61, 27));
        groupBox_3 = new QGroupBox(GioTestModeDialog);
        groupBox_3->setObjectName(QString::fromUtf8("groupBox_3"));
        groupBox_3->setGeometry(QRect(230, 10, 71, 141));
        checkBoxPIOBIN0 = new QCheckBox(groupBox_3);
        checkBoxPIOBIN0->setObjectName(QString::fromUtf8("checkBoxPIOBIN0"));
        checkBoxPIOBIN0->setGeometry(QRect(10, 20, 61, 27));
        checkBoxPIOBIN3 = new QCheckBox(groupBox_3);
        checkBoxPIOBIN3->setObjectName(QString::fromUtf8("checkBoxPIOBIN3"));
        checkBoxPIOBIN3->setGeometry(QRect(10, 110, 61, 27));
        checkBoxPIOBIN2 = new QCheckBox(groupBox_3);
        checkBoxPIOBIN2->setObjectName(QString::fromUtf8("checkBoxPIOBIN2"));
        checkBoxPIOBIN2->setGeometry(QRect(10, 80, 61, 27));
        checkBoxPIOBIN1 = new QCheckBox(groupBox_3);
        checkBoxPIOBIN1->setObjectName(QString::fromUtf8("checkBoxPIOBIN1"));
        checkBoxPIOBIN1->setGeometry(QRect(10, 50, 61, 27));
        groupBox_12 = new QGroupBox(GioTestModeDialog);
        groupBox_12->setObjectName(QString::fromUtf8("groupBox_12"));
        groupBox_12->setGeometry(QRect(180, 320, 91, 141));
        checkBoxTRGCOUT0 = new QCheckBox(groupBox_12);
        checkBoxTRGCOUT0->setObjectName(QString::fromUtf8("checkBoxTRGCOUT0"));
        checkBoxTRGCOUT0->setGeometry(QRect(10, 20, 61, 27));
        checkBoxTRGCOUT3 = new QCheckBox(groupBox_12);
        checkBoxTRGCOUT3->setObjectName(QString::fromUtf8("checkBoxTRGCOUT3"));
        checkBoxTRGCOUT3->setGeometry(QRect(10, 110, 61, 27));
        checkBoxTRGCOUT2 = new QCheckBox(groupBox_12);
        checkBoxTRGCOUT2->setObjectName(QString::fromUtf8("checkBoxTRGCOUT2"));
        checkBoxTRGCOUT2->setGeometry(QRect(10, 80, 61, 27));
        checkBoxTRGCOUT1 = new QCheckBox(groupBox_12);
        checkBoxTRGCOUT1->setObjectName(QString::fromUtf8("checkBoxTRGCOUT1"));
        checkBoxTRGCOUT1->setGeometry(QRect(10, 50, 61, 27));
        groupBox_13 = new QGroupBox(GioTestModeDialog);
        groupBox_13->setObjectName(QString::fromUtf8("groupBox_13"));
        groupBox_13->setGeometry(QRect(270, 320, 91, 141));
        checkBoxTRGDOUT0 = new QCheckBox(groupBox_13);
        checkBoxTRGDOUT0->setObjectName(QString::fromUtf8("checkBoxTRGDOUT0"));
        checkBoxTRGDOUT0->setGeometry(QRect(10, 20, 61, 27));
        checkBoxTRGDOUT3 = new QCheckBox(groupBox_13);
        checkBoxTRGDOUT3->setObjectName(QString::fromUtf8("checkBoxTRGDOUT3"));
        checkBoxTRGDOUT3->setGeometry(QRect(10, 110, 61, 27));
        checkBoxTRGDOUT2 = new QCheckBox(groupBox_13);
        checkBoxTRGDOUT2->setObjectName(QString::fromUtf8("checkBoxTRGDOUT2"));
        checkBoxTRGDOUT2->setGeometry(QRect(10, 80, 61, 27));
        checkBoxTRGDOUT1 = new QCheckBox(groupBox_13);
        checkBoxTRGDOUT1->setObjectName(QString::fromUtf8("checkBoxTRGDOUT1"));
        checkBoxTRGDOUT1->setGeometry(QRect(10, 50, 61, 27));
        groupBox_14 = new QGroupBox(GioTestModeDialog);
        groupBox_14->setObjectName(QString::fromUtf8("groupBox_14"));
        groupBox_14->setGeometry(QRect(90, 320, 91, 141));
        checkBoxTRGBOUT0 = new QCheckBox(groupBox_14);
        checkBoxTRGBOUT0->setObjectName(QString::fromUtf8("checkBoxTRGBOUT0"));
        checkBoxTRGBOUT0->setGeometry(QRect(10, 20, 61, 27));
        checkBoxTRGBOUT3 = new QCheckBox(groupBox_14);
        checkBoxTRGBOUT3->setObjectName(QString::fromUtf8("checkBoxTRGBOUT3"));
        checkBoxTRGBOUT3->setGeometry(QRect(10, 110, 61, 27));
        checkBoxTRGBOUT2 = new QCheckBox(groupBox_14);
        checkBoxTRGBOUT2->setObjectName(QString::fromUtf8("checkBoxTRGBOUT2"));
        checkBoxTRGBOUT2->setGeometry(QRect(10, 80, 61, 27));
        checkBoxTRGBOUT1 = new QCheckBox(groupBox_14);
        checkBoxTRGBOUT1->setObjectName(QString::fromUtf8("checkBoxTRGBOUT1"));
        checkBoxTRGBOUT1->setGeometry(QRect(10, 50, 61, 27));
        groupBox_15 = new QGroupBox(GioTestModeDialog);
        groupBox_15->setObjectName(QString::fromUtf8("groupBox_15"));
        groupBox_15->setGeometry(QRect(0, 320, 91, 141));
        checkBoxTRGAOUT0 = new QCheckBox(groupBox_15);
        checkBoxTRGAOUT0->setObjectName(QString::fromUtf8("checkBoxTRGAOUT0"));
        checkBoxTRGAOUT0->setGeometry(QRect(10, 20, 61, 27));
        checkBoxTRGAOUT3 = new QCheckBox(groupBox_15);
        checkBoxTRGAOUT3->setObjectName(QString::fromUtf8("checkBoxTRGAOUT3"));
        checkBoxTRGAOUT3->setGeometry(QRect(10, 110, 61, 27));
        checkBoxTRGAOUT2 = new QCheckBox(groupBox_15);
        checkBoxTRGAOUT2->setObjectName(QString::fromUtf8("checkBoxTRGAOUT2"));
        checkBoxTRGAOUT2->setGeometry(QRect(10, 80, 61, 27));
        checkBoxTRGAOUT1 = new QCheckBox(groupBox_15);
        checkBoxTRGAOUT1->setObjectName(QString::fromUtf8("checkBoxTRGAOUT1"));
        checkBoxTRGAOUT1->setGeometry(QRect(10, 50, 61, 27));
        checkBoxTRGAOUT0->raise();
        checkBoxTRGAOUT3->raise();
        checkBoxTRGAOUT2->raise();
        checkBoxTRGAOUT1->raise();
        groupBox_14->raise();
        pushButtonClose = new QPushButton(GioTestModeDialog);
        pushButtonClose->setObjectName(QString::fromUtf8("pushButtonClose"));
        pushButtonClose->setGeometry(QRect(170, 540, 112, 34));
        checkBoxTestLEDReg = new QCheckBox(GioTestModeDialog);
        checkBoxTestLEDReg->setObjectName(QString::fromUtf8("checkBoxTestLEDReg"));
        checkBoxTestLEDReg->setGeometry(QRect(10, 470, 141, 27));
        checkBoxLEDOut0 = new QCheckBox(GioTestModeDialog);
        checkBoxLEDOut0->setObjectName(QString::fromUtf8("checkBoxLEDOut0"));
        checkBoxLEDOut0->setGeometry(QRect(240, 470, 141, 27));
        checkBoxLEDOut1 = new QCheckBox(GioTestModeDialog);
        checkBoxLEDOut1->setObjectName(QString::fromUtf8("checkBoxLEDOut1"));
        checkBoxLEDOut1->setGeometry(QRect(240, 500, 141, 27));

        retranslateUi(GioTestModeDialog);

        QMetaObject::connectSlotsByName(GioTestModeDialog);
    } // setupUi

    void retranslateUi(QDialog *GioTestModeDialog)
    {
        GioTestModeDialog->setWindowTitle(QCoreApplication::translate("GioTestModeDialog", "Dialog", nullptr));
        groupBox_7->setTitle(QCoreApplication::translate("GioTestModeDialog", "G-Out", nullptr));
        checkBoxoGOUT0->setText(QCoreApplication::translate("GioTestModeDialog", "P0", nullptr));
        checkBoxoGOUT3->setText(QCoreApplication::translate("GioTestModeDialog", "P3", nullptr));
        checkBoxoGOUT2->setText(QCoreApplication::translate("GioTestModeDialog", "P2", nullptr));
        checkBoxoGOUT1->setText(QCoreApplication::translate("GioTestModeDialog", "P1", nullptr));
        checkBoxoGOUT7->setText(QCoreApplication::translate("GioTestModeDialog", "P7", nullptr));
        checkBoxoGOUT6->setText(QCoreApplication::translate("GioTestModeDialog", "P6", nullptr));
        checkBoxoGOUT4->setText(QCoreApplication::translate("GioTestModeDialog", "P4", nullptr));
        checkBoxoGOUT5->setText(QCoreApplication::translate("GioTestModeDialog", "P5", nullptr));
        groupBox_9->setTitle(QCoreApplication::translate("GioTestModeDialog", "PIO-A", nullptr));
        checkBoxPIOBOUT0->setText(QCoreApplication::translate("GioTestModeDialog", "P0", nullptr));
        checkBoxPIOBOUT3->setText(QCoreApplication::translate("GioTestModeDialog", "P3", nullptr));
        checkBoxPIOBOUT2->setText(QCoreApplication::translate("GioTestModeDialog", "P2", nullptr));
        checkBoxPIOBOUT1->setText(QCoreApplication::translate("GioTestModeDialog", "P1", nullptr));
        groupBox_6->setTitle(QCoreApplication::translate("GioTestModeDialog", "Trigger", nullptr));
        checkBoxTRGIN0->setText(QCoreApplication::translate("GioTestModeDialog", "IN0", nullptr));
        checkBoxTRGIN3->setText(QCoreApplication::translate("GioTestModeDialog", "IN3", nullptr));
        checkBoxTRGIN2->setText(QCoreApplication::translate("GioTestModeDialog", "IN2", nullptr));
        checkBoxTRGIN1->setText(QCoreApplication::translate("GioTestModeDialog", "IN1", nullptr));
        groupBox->setTitle(QCoreApplication::translate("GioTestModeDialog", "G-IN", nullptr));
        checkBoxGIN0->setText(QCoreApplication::translate("GioTestModeDialog", "IN0", nullptr));
        checkBoxGIN3->setText(QCoreApplication::translate("GioTestModeDialog", "IN3", nullptr));
        checkBoxGIN2->setText(QCoreApplication::translate("GioTestModeDialog", "IN2", nullptr));
        checkBoxGIN1->setText(QCoreApplication::translate("GioTestModeDialog", "IN1", nullptr));
        groupBox_5->setTitle(QCoreApplication::translate("GioTestModeDialog", "PIO-D", nullptr));
        checkBoxPIODIN0->setText(QCoreApplication::translate("GioTestModeDialog", "IN0", nullptr));
        checkBoxPIODIN3->setText(QCoreApplication::translate("GioTestModeDialog", "IN3", nullptr));
        checkBoxPIODIN2->setText(QCoreApplication::translate("GioTestModeDialog", "IN2", nullptr));
        checkBoxPIODIN1->setText(QCoreApplication::translate("GioTestModeDialog", "IN1", nullptr));
        groupBox_11->setTitle(QCoreApplication::translate("GioTestModeDialog", "PIO-A", nullptr));
        checkBoxPIODOUT0->setText(QCoreApplication::translate("GioTestModeDialog", "P0", nullptr));
        checkBoxPIODOUT3->setText(QCoreApplication::translate("GioTestModeDialog", "P3", nullptr));
        checkBoxPIODOUT2->setText(QCoreApplication::translate("GioTestModeDialog", "P2", nullptr));
        checkBoxPIODOUT1->setText(QCoreApplication::translate("GioTestModeDialog", "P1", nullptr));
        groupBox_2->setTitle(QCoreApplication::translate("GioTestModeDialog", "PIO-A", nullptr));
        checkBoxPIOAIN0->setText(QCoreApplication::translate("GioTestModeDialog", "IN0", nullptr));
        checkBoxPIOAIN3->setText(QCoreApplication::translate("GioTestModeDialog", "IN3", nullptr));
        checkBoxPIOAIN2->setText(QCoreApplication::translate("GioTestModeDialog", "IN2", nullptr));
        checkBoxPIOAIN1->setText(QCoreApplication::translate("GioTestModeDialog", "IN1", nullptr));
        groupBox_4->setTitle(QCoreApplication::translate("GioTestModeDialog", "PIO-C", nullptr));
        checkBoxPIOCIN0->setText(QCoreApplication::translate("GioTestModeDialog", "IN0", nullptr));
        checkBoxPIOCIN3->setText(QCoreApplication::translate("GioTestModeDialog", "IN3", nullptr));
        checkBoxPIOCIN2->setText(QCoreApplication::translate("GioTestModeDialog", "IN2", nullptr));
        checkBoxPIOCIN1->setText(QCoreApplication::translate("GioTestModeDialog", "IN1", nullptr));
        groupBox_8->setTitle(QCoreApplication::translate("GioTestModeDialog", "PIO-A", nullptr));
        checkBoxPIOAOUT0->setText(QCoreApplication::translate("GioTestModeDialog", "P0", nullptr));
        checkBoxPIOAOUT3->setText(QCoreApplication::translate("GioTestModeDialog", "P3", nullptr));
        checkBoxPIOAOUT2->setText(QCoreApplication::translate("GioTestModeDialog", "P2", nullptr));
        checkBoxPIOAOUT1->setText(QCoreApplication::translate("GioTestModeDialog", "P1", nullptr));
        groupBox_10->setTitle(QCoreApplication::translate("GioTestModeDialog", "PIO-A", nullptr));
        checkBoxPIOCOUT0->setText(QCoreApplication::translate("GioTestModeDialog", "P0", nullptr));
        checkBoxPIOCOUT3->setText(QCoreApplication::translate("GioTestModeDialog", "P3", nullptr));
        checkBoxPIOCOUT2->setText(QCoreApplication::translate("GioTestModeDialog", "P2", nullptr));
        checkBoxPIOCOUT1->setText(QCoreApplication::translate("GioTestModeDialog", "P1", nullptr));
        groupBox_3->setTitle(QCoreApplication::translate("GioTestModeDialog", "PIO-B", nullptr));
        checkBoxPIOBIN0->setText(QCoreApplication::translate("GioTestModeDialog", "IN0", nullptr));
        checkBoxPIOBIN3->setText(QCoreApplication::translate("GioTestModeDialog", "IN3", nullptr));
        checkBoxPIOBIN2->setText(QCoreApplication::translate("GioTestModeDialog", "IN2", nullptr));
        checkBoxPIOBIN1->setText(QCoreApplication::translate("GioTestModeDialog", "IN1", nullptr));
        groupBox_12->setTitle(QCoreApplication::translate("GioTestModeDialog", "TrgOut-C", nullptr));
        checkBoxTRGCOUT0->setText(QCoreApplication::translate("GioTestModeDialog", "P0", nullptr));
        checkBoxTRGCOUT3->setText(QCoreApplication::translate("GioTestModeDialog", "P3", nullptr));
        checkBoxTRGCOUT2->setText(QCoreApplication::translate("GioTestModeDialog", "P2", nullptr));
        checkBoxTRGCOUT1->setText(QCoreApplication::translate("GioTestModeDialog", "P1", nullptr));
        groupBox_13->setTitle(QCoreApplication::translate("GioTestModeDialog", "TrgOut-D", nullptr));
        checkBoxTRGDOUT0->setText(QCoreApplication::translate("GioTestModeDialog", "P0", nullptr));
        checkBoxTRGDOUT3->setText(QCoreApplication::translate("GioTestModeDialog", "P3", nullptr));
        checkBoxTRGDOUT2->setText(QCoreApplication::translate("GioTestModeDialog", "P2", nullptr));
        checkBoxTRGDOUT1->setText(QCoreApplication::translate("GioTestModeDialog", "P1", nullptr));
        groupBox_14->setTitle(QCoreApplication::translate("GioTestModeDialog", "TrgOut-B", nullptr));
        checkBoxTRGBOUT0->setText(QCoreApplication::translate("GioTestModeDialog", "P0", nullptr));
        checkBoxTRGBOUT3->setText(QCoreApplication::translate("GioTestModeDialog", "P3", nullptr));
        checkBoxTRGBOUT2->setText(QCoreApplication::translate("GioTestModeDialog", "P2", nullptr));
        checkBoxTRGBOUT1->setText(QCoreApplication::translate("GioTestModeDialog", "P1", nullptr));
        groupBox_15->setTitle(QCoreApplication::translate("GioTestModeDialog", "TrgOut-A", nullptr));
        checkBoxTRGAOUT0->setText(QCoreApplication::translate("GioTestModeDialog", "P0", nullptr));
        checkBoxTRGAOUT3->setText(QCoreApplication::translate("GioTestModeDialog", "P3", nullptr));
        checkBoxTRGAOUT2->setText(QCoreApplication::translate("GioTestModeDialog", "P2", nullptr));
        checkBoxTRGAOUT1->setText(QCoreApplication::translate("GioTestModeDialog", "P1", nullptr));
        pushButtonClose->setText(QCoreApplication::translate("GioTestModeDialog", "Close", nullptr));
        checkBoxTestLEDReg->setText(QCoreApplication::translate("GioTestModeDialog", "TestLEDReg", nullptr));
        checkBoxLEDOut0->setText(QCoreApplication::translate("GioTestModeDialog", "LEDOut0", nullptr));
        checkBoxLEDOut1->setText(QCoreApplication::translate("GioTestModeDialog", "LEDOut1", nullptr));
    } // retranslateUi

};

namespace Ui {
    class GioTestModeDialog: public Ui_GioTestModeDialog {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_GIOTESTMODEDIALOG_H
