/********************************************************************************
** Form generated from reading UI file 'LEDControl16GPrnRasPi.ui'
**
** Created by: Qt User Interface Compiler version 5.15.13
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_LEDCONTROL16GPRNRASPI_H
#define UI_LEDCONTROL16GPRNRASPI_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QToolButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_LEDControl16GPrnRasPi
{
public:
    QWidget *centralWidget;
    QLabel *labelMotorPulseCounter;
    QLabel *label_2;
    QLabel *label_10;
    QFrame *frame;
    QLabel *label;
    QSpinBox *spinBoxMulInputA;
    QLabel *label_11;
    QSpinBox *spinBoxMulInputB;
    QDoubleSpinBox *doubleSpinBoxTriggerDelayParameter;
    QLabel *label_9;
    QPushButton *pushButtonSaveSetting;
    QPushButton *pushButtonSendFrameTrigger;
    QLabel *label_5;
    QFrame *frame_3;
    QLabel *label_14;
    QSpinBox *spinBoxMinOFF;
    QLabel *label_15;
    QSpinBox *spinBoxMinON;
    QGroupBox *groupBox;
    QCheckBox *checkBoxGIN0;
    QCheckBox *checkBoxGIN3;
    QCheckBox *checkBoxGIN2;
    QCheckBox *checkBoxGIN1;
    QGroupBox *groupBox_2;
    QCheckBox *checkBoxPIOAIN0;
    QCheckBox *checkBoxPIOAIN3;
    QCheckBox *checkBoxPIOAIN2;
    QCheckBox *checkBoxPIOAIN1;
    QGroupBox *groupBox_3;
    QCheckBox *checkBoxPIOBIN0;
    QCheckBox *checkBoxPIOBIN3;
    QCheckBox *checkBoxPIOBIN2;
    QCheckBox *checkBoxPIOBIN1;
    QGroupBox *groupBox_4;
    QCheckBox *checkBoxPIOCIN0;
    QCheckBox *checkBoxPIOCIN3;
    QCheckBox *checkBoxPIOCIN2;
    QCheckBox *checkBoxPIOCIN1;
    QGroupBox *groupBox_5;
    QCheckBox *checkBoxPIODIN0;
    QCheckBox *checkBoxPIODIN3;
    QCheckBox *checkBoxPIODIN2;
    QCheckBox *checkBoxPIODIN1;
    QGroupBox *groupBox_6;
    QCheckBox *checkBoxTRGIN0;
    QCheckBox *checkBoxTRGIN3;
    QCheckBox *checkBoxTRGIN2;
    QCheckBox *checkBoxTRGIN1;
    QFrame *frame_4;
    QLabel *label_6;
    QSpinBox *spinBoxResultAAcceptStart;
    QLabel *label_Unit1_2;
    QLabel *label_16;
    QLabel *label_Unit1_3;
    QLabel *label_18;
    QSpinBox *spinBoxResultACloseAccept;
    QLabel *label_17;
    QLabel *label_Unit1_4;
    QSpinBox *spinBoxResultBCloseAccept;
    QSpinBox *spinBoxResultBAcceptStart;
    QLabel *label_Unit1_5;
    QLabel *label_19;
    QLabel *label_Unit1_6;
    QSpinBox *spinBoxResultCCloseAccept;
    QSpinBox *spinBoxResultCAcceptStart;
    QLabel *label_Unit1_7;
    QLabel *label_20;
    QLabel *label_Unit1_8;
    QSpinBox *spinBoxResultDCloseAccept;
    QSpinBox *spinBoxResultDAcceptStart;
    QLabel *label_Unit1_9;
    QLabel *label_Unit1;
    QSpinBox *spinBoxDelayFrameTriggerA;
    QLabel *label_Unit2;
    QSpinBox *spinBoxDelayFrameTriggerB;
    QLabel *label_Unit2_2;
    QSpinBox *spinBoxDelayFrameTriggerC;
    QLabel *label_Unit2_3;
    QSpinBox *spinBoxDelayFrameTriggerD;
    QLabel *label_4;
    QLabel *label_23;
    QCheckBox *checkBoxFlipFrameTriggerA;
    QCheckBox *checkBoxFlipFrameTriggerB;
    QCheckBox *checkBoxFlipFrameTriggerC;
    QCheckBox *checkBoxFlipFrameTriggerD;
    QFrame *frame_5;
    QLabel *label_21;
    QSpinBox *spinBoxConveyerLength;
    QLabel *label_22;
    QSpinBox *spinBoxGateOpenTerm;
    QLabel *label_7;
    QCheckBox *checkBox;
    QLabel *label_8;
    QWidget *widgetTestMode;
    QGroupBox *groupBox_8;
    QCheckBox *checkBoxPIOAOUT0;
    QCheckBox *checkBoxPIOAOUT3;
    QCheckBox *checkBoxPIOAOUT2;
    QCheckBox *checkBoxPIOAOUT1;
    QGroupBox *groupBox_10;
    QCheckBox *checkBoxPIOCOUT0;
    QCheckBox *checkBoxPIOCOUT3;
    QCheckBox *checkBoxPIOCOUT2;
    QCheckBox *checkBoxPIOCOUT1;
    QGroupBox *groupBox_11;
    QCheckBox *checkBoxPIODOUT0;
    QCheckBox *checkBoxPIODOUT3;
    QCheckBox *checkBoxPIODOUT2;
    QCheckBox *checkBoxPIODOUT1;
    QGroupBox *groupBox_9;
    QCheckBox *checkBoxPIOBOUT0;
    QCheckBox *checkBoxPIOBOUT3;
    QCheckBox *checkBoxPIOBOUT2;
    QCheckBox *checkBoxPIOBOUT1;
    QGroupBox *groupBox_7;
    QCheckBox *checkBoxoGOUT0;
    QCheckBox *checkBoxoGOUT3;
    QCheckBox *checkBoxoGOUT2;
    QCheckBox *checkBoxoGOUT1;
    QCheckBox *checkBoxoGOUT7;
    QCheckBox *checkBoxoGOUT6;
    QCheckBox *checkBoxoGOUT4;
    QCheckBox *checkBoxoGOUT5;
    QGroupBox *groupBox_12;
    QCheckBox *checkBoxTRGAOUT0;
    QCheckBox *checkBoxTRGAOUT3;
    QCheckBox *checkBoxTRGAOUT2;
    QCheckBox *checkBoxTRGAOUT1;
    QGroupBox *groupBox_13;
    QCheckBox *checkBoxTRGBOUT0;
    QCheckBox *checkBoxTRGBOUT3;
    QCheckBox *checkBoxTRGBOUT2;
    QCheckBox *checkBoxTRGBOUT1;
    QGroupBox *groupBox_14;
    QCheckBox *checkBoxTRGCOUT0;
    QCheckBox *checkBoxTRGCOUT3;
    QCheckBox *checkBoxTRGCOUT2;
    QCheckBox *checkBoxTRGCOUT1;
    QGroupBox *groupBox_15;
    QCheckBox *checkBoxTRGDOUT0;
    QCheckBox *checkBoxTRGDOUT3;
    QCheckBox *checkBoxTRGDOUT2;
    QCheckBox *checkBoxTRGDOUT1;
    QToolButton *toolButtonTestMode;
    QLabel *labelMotorPulseCounter2;
    QLabel *label_12;

    void setupUi(QMainWindow *LEDControl16GPrnRasPi)
    {
        if (LEDControl16GPrnRasPi->objectName().isEmpty())
            LEDControl16GPrnRasPi->setObjectName(QString::fromUtf8("LEDControl16GPrnRasPi"));
        LEDControl16GPrnRasPi->resize(1133, 572);
        centralWidget = new QWidget(LEDControl16GPrnRasPi);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        labelMotorPulseCounter = new QLabel(centralWidget);
        labelMotorPulseCounter->setObjectName(QString::fromUtf8("labelMotorPulseCounter"));
        labelMotorPulseCounter->setGeometry(QRect(10, 200, 131, 22));
        QPalette palette;
        QBrush brush(QColor(255, 255, 255, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Base, brush);
        palette.setBrush(QPalette::Active, QPalette::Window, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush);
        labelMotorPulseCounter->setPalette(palette);
        labelMotorPulseCounter->setAutoFillBackground(true);
        labelMotorPulseCounter->setFrameShape(QFrame::Panel);
        labelMotorPulseCounter->setFrameShadow(QFrame::Sunken);
        labelMotorPulseCounter->setAlignment(Qt::AlignCenter);
        label_2 = new QLabel(centralWidget);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(20, 10, 101, 21));
        label_10 = new QLabel(centralWidget);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(10, 230, 181, 22));
        frame = new QFrame(centralWidget);
        frame->setObjectName(QString::fromUtf8("frame"));
        frame->setGeometry(QRect(10, 30, 111, 141));
        frame->setFrameShape(QFrame::Panel);
        frame->setFrameShadow(QFrame::Sunken);
        label = new QLabel(frame);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(10, 10, 91, 21));
        spinBoxMulInputA = new QSpinBox(frame);
        spinBoxMulInputA->setObjectName(QString::fromUtf8("spinBoxMulInputA"));
        spinBoxMulInputA->setGeometry(QRect(10, 30, 91, 31));
        spinBoxMulInputA->setMaximum(16777215);
        label_11 = new QLabel(frame);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(10, 70, 91, 21));
        spinBoxMulInputB = new QSpinBox(frame);
        spinBoxMulInputB->setObjectName(QString::fromUtf8("spinBoxMulInputB"));
        spinBoxMulInputB->setGeometry(QRect(10, 90, 91, 31));
        spinBoxMulInputB->setMaximum(16777215);
        doubleSpinBoxTriggerDelayParameter = new QDoubleSpinBox(centralWidget);
        doubleSpinBoxTriggerDelayParameter->setObjectName(QString::fromUtf8("doubleSpinBoxTriggerDelayParameter"));
        doubleSpinBoxTriggerDelayParameter->setGeometry(QRect(10, 250, 141, 32));
        doubleSpinBoxTriggerDelayParameter->setMaximum(99999999.000000000000000);
        doubleSpinBoxTriggerDelayParameter->setValue(200000.000000000000000);
        label_9 = new QLabel(centralWidget);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(10, 180, 141, 22));
        pushButtonSaveSetting = new QPushButton(centralWidget);
        pushButtonSaveSetting->setObjectName(QString::fromUtf8("pushButtonSaveSetting"));
        pushButtonSaveSetting->setGeometry(QRect(190, 530, 111, 31));
        pushButtonSendFrameTrigger = new QPushButton(centralWidget);
        pushButtonSendFrameTrigger->setObjectName(QString::fromUtf8("pushButtonSendFrameTrigger"));
        pushButtonSendFrameTrigger->setGeometry(QRect(80, 530, 101, 31));
        label_5 = new QLabel(centralWidget);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(130, 10, 111, 21));
        frame_3 = new QFrame(centralWidget);
        frame_3->setObjectName(QString::fromUtf8("frame_3"));
        frame_3->setGeometry(QRect(130, 30, 111, 141));
        frame_3->setFrameShape(QFrame::Panel);
        frame_3->setFrameShadow(QFrame::Sunken);
        label_14 = new QLabel(frame_3);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(0, 10, 111, 21));
        spinBoxMinOFF = new QSpinBox(frame_3);
        spinBoxMinOFF->setObjectName(QString::fromUtf8("spinBoxMinOFF"));
        spinBoxMinOFF->setGeometry(QRect(10, 30, 91, 31));
        spinBoxMinOFF->setMaximum(16777215);
        label_15 = new QLabel(frame_3);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(0, 70, 111, 21));
        spinBoxMinON = new QSpinBox(frame_3);
        spinBoxMinON->setObjectName(QString::fromUtf8("spinBoxMinON"));
        spinBoxMinON->setGeometry(QRect(10, 90, 91, 31));
        spinBoxMinON->setMaximum(16777215);
        groupBox = new QGroupBox(centralWidget);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(450, 10, 71, 141));
        checkBoxGIN0 = new QCheckBox(groupBox);
        checkBoxGIN0->setObjectName(QString::fromUtf8("checkBoxGIN0"));
        checkBoxGIN0->setGeometry(QRect(10, 20, 61, 27));
        checkBoxGIN3 = new QCheckBox(groupBox);
        checkBoxGIN3->setObjectName(QString::fromUtf8("checkBoxGIN3"));
        checkBoxGIN3->setGeometry(QRect(10, 110, 61, 27));
        checkBoxGIN2 = new QCheckBox(groupBox);
        checkBoxGIN2->setObjectName(QString::fromUtf8("checkBoxGIN2"));
        checkBoxGIN2->setGeometry(QRect(10, 80, 61, 27));
        checkBoxGIN1 = new QCheckBox(groupBox);
        checkBoxGIN1->setObjectName(QString::fromUtf8("checkBoxGIN1"));
        checkBoxGIN1->setGeometry(QRect(10, 50, 61, 27));
        groupBox_2 = new QGroupBox(centralWidget);
        groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
        groupBox_2->setGeometry(QRect(610, 10, 61, 141));
        checkBoxPIOAIN0 = new QCheckBox(groupBox_2);
        checkBoxPIOAIN0->setObjectName(QString::fromUtf8("checkBoxPIOAIN0"));
        checkBoxPIOAIN0->setGeometry(QRect(0, 20, 61, 27));
        checkBoxPIOAIN3 = new QCheckBox(groupBox_2);
        checkBoxPIOAIN3->setObjectName(QString::fromUtf8("checkBoxPIOAIN3"));
        checkBoxPIOAIN3->setGeometry(QRect(0, 110, 61, 27));
        checkBoxPIOAIN2 = new QCheckBox(groupBox_2);
        checkBoxPIOAIN2->setObjectName(QString::fromUtf8("checkBoxPIOAIN2"));
        checkBoxPIOAIN2->setGeometry(QRect(0, 80, 61, 27));
        checkBoxPIOAIN1 = new QCheckBox(groupBox_2);
        checkBoxPIOAIN1->setObjectName(QString::fromUtf8("checkBoxPIOAIN1"));
        checkBoxPIOAIN1->setGeometry(QRect(0, 50, 61, 27));
        groupBox_3 = new QGroupBox(centralWidget);
        groupBox_3->setObjectName(QString::fromUtf8("groupBox_3"));
        groupBox_3->setGeometry(QRect(670, 10, 61, 141));
        checkBoxPIOBIN0 = new QCheckBox(groupBox_3);
        checkBoxPIOBIN0->setObjectName(QString::fromUtf8("checkBoxPIOBIN0"));
        checkBoxPIOBIN0->setGeometry(QRect(0, 20, 61, 27));
        checkBoxPIOBIN3 = new QCheckBox(groupBox_3);
        checkBoxPIOBIN3->setObjectName(QString::fromUtf8("checkBoxPIOBIN3"));
        checkBoxPIOBIN3->setGeometry(QRect(0, 110, 61, 27));
        checkBoxPIOBIN2 = new QCheckBox(groupBox_3);
        checkBoxPIOBIN2->setObjectName(QString::fromUtf8("checkBoxPIOBIN2"));
        checkBoxPIOBIN2->setGeometry(QRect(0, 80, 61, 27));
        checkBoxPIOBIN1 = new QCheckBox(groupBox_3);
        checkBoxPIOBIN1->setObjectName(QString::fromUtf8("checkBoxPIOBIN1"));
        checkBoxPIOBIN1->setGeometry(QRect(0, 50, 61, 27));
        groupBox_4 = new QGroupBox(centralWidget);
        groupBox_4->setObjectName(QString::fromUtf8("groupBox_4"));
        groupBox_4->setGeometry(QRect(730, 10, 61, 141));
        checkBoxPIOCIN0 = new QCheckBox(groupBox_4);
        checkBoxPIOCIN0->setObjectName(QString::fromUtf8("checkBoxPIOCIN0"));
        checkBoxPIOCIN0->setGeometry(QRect(0, 20, 61, 27));
        checkBoxPIOCIN3 = new QCheckBox(groupBox_4);
        checkBoxPIOCIN3->setObjectName(QString::fromUtf8("checkBoxPIOCIN3"));
        checkBoxPIOCIN3->setGeometry(QRect(0, 110, 61, 27));
        checkBoxPIOCIN2 = new QCheckBox(groupBox_4);
        checkBoxPIOCIN2->setObjectName(QString::fromUtf8("checkBoxPIOCIN2"));
        checkBoxPIOCIN2->setGeometry(QRect(0, 80, 61, 27));
        checkBoxPIOCIN1 = new QCheckBox(groupBox_4);
        checkBoxPIOCIN1->setObjectName(QString::fromUtf8("checkBoxPIOCIN1"));
        checkBoxPIOCIN1->setGeometry(QRect(0, 50, 61, 27));
        groupBox_5 = new QGroupBox(centralWidget);
        groupBox_5->setObjectName(QString::fromUtf8("groupBox_5"));
        groupBox_5->setGeometry(QRect(790, 10, 61, 141));
        checkBoxPIODIN0 = new QCheckBox(groupBox_5);
        checkBoxPIODIN0->setObjectName(QString::fromUtf8("checkBoxPIODIN0"));
        checkBoxPIODIN0->setGeometry(QRect(0, 20, 61, 27));
        checkBoxPIODIN3 = new QCheckBox(groupBox_5);
        checkBoxPIODIN3->setObjectName(QString::fromUtf8("checkBoxPIODIN3"));
        checkBoxPIODIN3->setGeometry(QRect(0, 110, 61, 27));
        checkBoxPIODIN2 = new QCheckBox(groupBox_5);
        checkBoxPIODIN2->setObjectName(QString::fromUtf8("checkBoxPIODIN2"));
        checkBoxPIODIN2->setGeometry(QRect(0, 80, 61, 27));
        checkBoxPIODIN1 = new QCheckBox(groupBox_5);
        checkBoxPIODIN1->setObjectName(QString::fromUtf8("checkBoxPIODIN1"));
        checkBoxPIODIN1->setGeometry(QRect(0, 50, 61, 27));
        groupBox_6 = new QGroupBox(centralWidget);
        groupBox_6->setObjectName(QString::fromUtf8("groupBox_6"));
        groupBox_6->setGeometry(QRect(530, 10, 71, 141));
        checkBoxTRGIN0 = new QCheckBox(groupBox_6);
        checkBoxTRGIN0->setObjectName(QString::fromUtf8("checkBoxTRGIN0"));
        checkBoxTRGIN0->setGeometry(QRect(10, 20, 61, 27));
        checkBoxTRGIN3 = new QCheckBox(groupBox_6);
        checkBoxTRGIN3->setObjectName(QString::fromUtf8("checkBoxTRGIN3"));
        checkBoxTRGIN3->setGeometry(QRect(10, 110, 61, 27));
        checkBoxTRGIN2 = new QCheckBox(groupBox_6);
        checkBoxTRGIN2->setObjectName(QString::fromUtf8("checkBoxTRGIN2"));
        checkBoxTRGIN2->setGeometry(QRect(10, 80, 61, 27));
        checkBoxTRGIN1 = new QCheckBox(groupBox_6);
        checkBoxTRGIN1->setObjectName(QString::fromUtf8("checkBoxTRGIN1"));
        checkBoxTRGIN1->setGeometry(QRect(10, 50, 61, 27));
        frame_4 = new QFrame(centralWidget);
        frame_4->setObjectName(QString::fromUtf8("frame_4"));
        frame_4->setGeometry(QRect(10, 320, 671, 201));
        frame_4->setFrameShape(QFrame::Panel);
        frame_4->setFrameShadow(QFrame::Sunken);
        label_6 = new QLabel(frame_4);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(240, 10, 101, 21));
        spinBoxResultAAcceptStart = new QSpinBox(frame_4);
        spinBoxResultAAcceptStart->setObjectName(QString::fromUtf8("spinBoxResultAAcceptStart"));
        spinBoxResultAAcceptStart->setGeometry(QRect(240, 30, 111, 31));
        QPalette palette1;
        QBrush brush1(QColor(255, 255, 0, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        QBrush brush2(QColor(240, 240, 240, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush2);
        spinBoxResultAAcceptStart->setPalette(palette1);
        spinBoxResultAAcceptStart->setAutoFillBackground(true);
        spinBoxResultAAcceptStart->setMaximum(16777215);
        label_Unit1_2 = new QLabel(frame_4);
        label_Unit1_2->setObjectName(QString::fromUtf8("label_Unit1_2"));
        label_Unit1_2->setGeometry(QRect(360, 40, 41, 21));
        label_16 = new QLabel(frame_4);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(0, 30, 61, 31));
        label_Unit1_3 = new QLabel(frame_4);
        label_Unit1_3->setObjectName(QString::fromUtf8("label_Unit1_3"));
        label_Unit1_3->setGeometry(QRect(530, 40, 41, 21));
        label_18 = new QLabel(frame_4);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(410, 10, 101, 21));
        spinBoxResultACloseAccept = new QSpinBox(frame_4);
        spinBoxResultACloseAccept->setObjectName(QString::fromUtf8("spinBoxResultACloseAccept"));
        spinBoxResultACloseAccept->setGeometry(QRect(410, 30, 111, 31));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush2);
        spinBoxResultACloseAccept->setPalette(palette2);
        spinBoxResultACloseAccept->setAutoFillBackground(true);
        spinBoxResultACloseAccept->setMaximum(16777215);
        label_17 = new QLabel(frame_4);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(0, 70, 61, 31));
        label_Unit1_4 = new QLabel(frame_4);
        label_Unit1_4->setObjectName(QString::fromUtf8("label_Unit1_4"));
        label_Unit1_4->setGeometry(QRect(360, 80, 41, 21));
        spinBoxResultBCloseAccept = new QSpinBox(frame_4);
        spinBoxResultBCloseAccept->setObjectName(QString::fromUtf8("spinBoxResultBCloseAccept"));
        spinBoxResultBCloseAccept->setGeometry(QRect(410, 70, 111, 31));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush2);
        spinBoxResultBCloseAccept->setPalette(palette3);
        spinBoxResultBCloseAccept->setAutoFillBackground(true);
        spinBoxResultBCloseAccept->setMaximum(16777215);
        spinBoxResultBAcceptStart = new QSpinBox(frame_4);
        spinBoxResultBAcceptStart->setObjectName(QString::fromUtf8("spinBoxResultBAcceptStart"));
        spinBoxResultBAcceptStart->setGeometry(QRect(240, 70, 111, 31));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::Base, brush2);
        spinBoxResultBAcceptStart->setPalette(palette4);
        spinBoxResultBAcceptStart->setAutoFillBackground(true);
        spinBoxResultBAcceptStart->setMaximum(16777215);
        label_Unit1_5 = new QLabel(frame_4);
        label_Unit1_5->setObjectName(QString::fromUtf8("label_Unit1_5"));
        label_Unit1_5->setGeometry(QRect(530, 80, 41, 21));
        label_19 = new QLabel(frame_4);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(0, 110, 61, 31));
        label_Unit1_6 = new QLabel(frame_4);
        label_Unit1_6->setObjectName(QString::fromUtf8("label_Unit1_6"));
        label_Unit1_6->setGeometry(QRect(360, 120, 41, 21));
        spinBoxResultCCloseAccept = new QSpinBox(frame_4);
        spinBoxResultCCloseAccept->setObjectName(QString::fromUtf8("spinBoxResultCCloseAccept"));
        spinBoxResultCCloseAccept->setGeometry(QRect(410, 110, 111, 31));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Base, brush2);
        spinBoxResultCCloseAccept->setPalette(palette5);
        spinBoxResultCCloseAccept->setAutoFillBackground(true);
        spinBoxResultCCloseAccept->setMaximum(16777215);
        spinBoxResultCAcceptStart = new QSpinBox(frame_4);
        spinBoxResultCAcceptStart->setObjectName(QString::fromUtf8("spinBoxResultCAcceptStart"));
        spinBoxResultCAcceptStart->setGeometry(QRect(240, 110, 111, 31));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette6.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::Base, brush2);
        spinBoxResultCAcceptStart->setPalette(palette6);
        spinBoxResultCAcceptStart->setAutoFillBackground(true);
        spinBoxResultCAcceptStart->setMaximum(16777215);
        label_Unit1_7 = new QLabel(frame_4);
        label_Unit1_7->setObjectName(QString::fromUtf8("label_Unit1_7"));
        label_Unit1_7->setGeometry(QRect(530, 120, 41, 21));
        label_20 = new QLabel(frame_4);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(0, 150, 61, 31));
        label_Unit1_8 = new QLabel(frame_4);
        label_Unit1_8->setObjectName(QString::fromUtf8("label_Unit1_8"));
        label_Unit1_8->setGeometry(QRect(360, 160, 41, 21));
        spinBoxResultDCloseAccept = new QSpinBox(frame_4);
        spinBoxResultDCloseAccept->setObjectName(QString::fromUtf8("spinBoxResultDCloseAccept"));
        spinBoxResultDCloseAccept->setGeometry(QRect(410, 150, 111, 31));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette7.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette7.setBrush(QPalette::Disabled, QPalette::Base, brush2);
        spinBoxResultDCloseAccept->setPalette(palette7);
        spinBoxResultDCloseAccept->setAutoFillBackground(true);
        spinBoxResultDCloseAccept->setMaximum(16777215);
        spinBoxResultDAcceptStart = new QSpinBox(frame_4);
        spinBoxResultDAcceptStart->setObjectName(QString::fromUtf8("spinBoxResultDAcceptStart"));
        spinBoxResultDAcceptStart->setGeometry(QRect(240, 150, 111, 31));
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette8.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette8.setBrush(QPalette::Disabled, QPalette::Base, brush2);
        spinBoxResultDAcceptStart->setPalette(palette8);
        spinBoxResultDAcceptStart->setAutoFillBackground(true);
        spinBoxResultDAcceptStart->setMaximum(16777215);
        label_Unit1_9 = new QLabel(frame_4);
        label_Unit1_9->setObjectName(QString::fromUtf8("label_Unit1_9"));
        label_Unit1_9->setGeometry(QRect(530, 160, 41, 21));
        label_Unit1 = new QLabel(frame_4);
        label_Unit1->setObjectName(QString::fromUtf8("label_Unit1"));
        label_Unit1->setGeometry(QRect(180, 40, 41, 21));
        spinBoxDelayFrameTriggerA = new QSpinBox(frame_4);
        spinBoxDelayFrameTriggerA->setObjectName(QString::fromUtf8("spinBoxDelayFrameTriggerA"));
        spinBoxDelayFrameTriggerA->setGeometry(QRect(60, 30, 111, 31));
        spinBoxDelayFrameTriggerA->setMaximum(16777215);
        label_Unit2 = new QLabel(frame_4);
        label_Unit2->setObjectName(QString::fromUtf8("label_Unit2"));
        label_Unit2->setGeometry(QRect(180, 80, 41, 21));
        spinBoxDelayFrameTriggerB = new QSpinBox(frame_4);
        spinBoxDelayFrameTriggerB->setObjectName(QString::fromUtf8("spinBoxDelayFrameTriggerB"));
        spinBoxDelayFrameTriggerB->setGeometry(QRect(60, 70, 111, 31));
        spinBoxDelayFrameTriggerB->setMaximum(16777215);
        label_Unit2_2 = new QLabel(frame_4);
        label_Unit2_2->setObjectName(QString::fromUtf8("label_Unit2_2"));
        label_Unit2_2->setGeometry(QRect(180, 120, 41, 21));
        spinBoxDelayFrameTriggerC = new QSpinBox(frame_4);
        spinBoxDelayFrameTriggerC->setObjectName(QString::fromUtf8("spinBoxDelayFrameTriggerC"));
        spinBoxDelayFrameTriggerC->setGeometry(QRect(60, 110, 111, 31));
        spinBoxDelayFrameTriggerC->setMaximum(16777215);
        label_Unit2_3 = new QLabel(frame_4);
        label_Unit2_3->setObjectName(QString::fromUtf8("label_Unit2_3"));
        label_Unit2_3->setGeometry(QRect(180, 160, 41, 21));
        spinBoxDelayFrameTriggerD = new QSpinBox(frame_4);
        spinBoxDelayFrameTriggerD->setObjectName(QString::fromUtf8("spinBoxDelayFrameTriggerD"));
        spinBoxDelayFrameTriggerD->setGeometry(QRect(60, 150, 111, 31));
        spinBoxDelayFrameTriggerD->setMaximum(16777215);
        label_4 = new QLabel(frame_4);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(60, 10, 101, 21));
        label_23 = new QLabel(frame_4);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(580, 10, 81, 21));
        checkBoxFlipFrameTriggerA = new QCheckBox(frame_4);
        checkBoxFlipFrameTriggerA->setObjectName(QString::fromUtf8("checkBoxFlipFrameTriggerA"));
        checkBoxFlipFrameTriggerA->setGeometry(QRect(600, 30, 51, 27));
        checkBoxFlipFrameTriggerB = new QCheckBox(frame_4);
        checkBoxFlipFrameTriggerB->setObjectName(QString::fromUtf8("checkBoxFlipFrameTriggerB"));
        checkBoxFlipFrameTriggerB->setGeometry(QRect(600, 70, 51, 27));
        checkBoxFlipFrameTriggerC = new QCheckBox(frame_4);
        checkBoxFlipFrameTriggerC->setObjectName(QString::fromUtf8("checkBoxFlipFrameTriggerC"));
        checkBoxFlipFrameTriggerC->setGeometry(QRect(600, 110, 51, 27));
        checkBoxFlipFrameTriggerD = new QCheckBox(frame_4);
        checkBoxFlipFrameTriggerD->setObjectName(QString::fromUtf8("checkBoxFlipFrameTriggerD"));
        checkBoxFlipFrameTriggerD->setGeometry(QRect(600, 150, 51, 27));
        frame_5 = new QFrame(centralWidget);
        frame_5->setObjectName(QString::fromUtf8("frame_5"));
        frame_5->setGeometry(QRect(250, 30, 131, 141));
        frame_5->setFrameShape(QFrame::Panel);
        frame_5->setFrameShadow(QFrame::Sunken);
        label_21 = new QLabel(frame_5);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(0, 10, 131, 21));
        spinBoxConveyerLength = new QSpinBox(frame_5);
        spinBoxConveyerLength->setObjectName(QString::fromUtf8("spinBoxConveyerLength"));
        spinBoxConveyerLength->setGeometry(QRect(10, 30, 111, 31));
        QPalette palette9;
        palette9.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette9.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette9.setBrush(QPalette::Disabled, QPalette::Base, brush2);
        spinBoxConveyerLength->setPalette(palette9);
        spinBoxConveyerLength->setAutoFillBackground(true);
        spinBoxConveyerLength->setMaximum(65535);
        label_22 = new QLabel(frame_5);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(10, 70, 121, 21));
        spinBoxGateOpenTerm = new QSpinBox(frame_5);
        spinBoxGateOpenTerm->setObjectName(QString::fromUtf8("spinBoxGateOpenTerm"));
        spinBoxGateOpenTerm->setGeometry(QRect(20, 90, 91, 31));
        QPalette palette10;
        palette10.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette10.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette10.setBrush(QPalette::Disabled, QPalette::Base, brush2);
        spinBoxGateOpenTerm->setPalette(palette10);
        spinBoxGateOpenTerm->setAutoFillBackground(true);
        spinBoxGateOpenTerm->setMaximum(1023);
        label_7 = new QLabel(centralWidget);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(250, 10, 111, 21));
        checkBox = new QCheckBox(centralWidget);
        checkBox->setObjectName(QString::fromUtf8("checkBox"));
        checkBox->setGeometry(QRect(770, 540, 131, 22));
        label_8 = new QLabel(centralWidget);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(700, 330, 261, 21));
        widgetTestMode = new QWidget(centralWidget);
        widgetTestMode->setObjectName(QString::fromUtf8("widgetTestMode"));
        widgetTestMode->setGeometry(QRect(450, 150, 671, 161));
        groupBox_8 = new QGroupBox(widgetTestMode);
        groupBox_8->setObjectName(QString::fromUtf8("groupBox_8"));
        groupBox_8->setGeometry(QRect(160, 0, 61, 141));
        checkBoxPIOAOUT0 = new QCheckBox(groupBox_8);
        checkBoxPIOAOUT0->setObjectName(QString::fromUtf8("checkBoxPIOAOUT0"));
        checkBoxPIOAOUT0->setGeometry(QRect(0, 20, 61, 27));
        checkBoxPIOAOUT3 = new QCheckBox(groupBox_8);
        checkBoxPIOAOUT3->setObjectName(QString::fromUtf8("checkBoxPIOAOUT3"));
        checkBoxPIOAOUT3->setGeometry(QRect(0, 110, 61, 27));
        checkBoxPIOAOUT2 = new QCheckBox(groupBox_8);
        checkBoxPIOAOUT2->setObjectName(QString::fromUtf8("checkBoxPIOAOUT2"));
        checkBoxPIOAOUT2->setGeometry(QRect(0, 80, 61, 27));
        checkBoxPIOAOUT1 = new QCheckBox(groupBox_8);
        checkBoxPIOAOUT1->setObjectName(QString::fromUtf8("checkBoxPIOAOUT1"));
        checkBoxPIOAOUT1->setGeometry(QRect(0, 50, 61, 27));
        groupBox_10 = new QGroupBox(widgetTestMode);
        groupBox_10->setObjectName(QString::fromUtf8("groupBox_10"));
        groupBox_10->setGeometry(QRect(280, 0, 61, 141));
        checkBoxPIOCOUT0 = new QCheckBox(groupBox_10);
        checkBoxPIOCOUT0->setObjectName(QString::fromUtf8("checkBoxPIOCOUT0"));
        checkBoxPIOCOUT0->setGeometry(QRect(0, 20, 61, 27));
        checkBoxPIOCOUT3 = new QCheckBox(groupBox_10);
        checkBoxPIOCOUT3->setObjectName(QString::fromUtf8("checkBoxPIOCOUT3"));
        checkBoxPIOCOUT3->setGeometry(QRect(0, 110, 61, 27));
        checkBoxPIOCOUT2 = new QCheckBox(groupBox_10);
        checkBoxPIOCOUT2->setObjectName(QString::fromUtf8("checkBoxPIOCOUT2"));
        checkBoxPIOCOUT2->setGeometry(QRect(0, 80, 61, 27));
        checkBoxPIOCOUT1 = new QCheckBox(groupBox_10);
        checkBoxPIOCOUT1->setObjectName(QString::fromUtf8("checkBoxPIOCOUT1"));
        checkBoxPIOCOUT1->setGeometry(QRect(0, 50, 61, 27));
        groupBox_11 = new QGroupBox(widgetTestMode);
        groupBox_11->setObjectName(QString::fromUtf8("groupBox_11"));
        groupBox_11->setGeometry(QRect(340, 0, 61, 141));
        checkBoxPIODOUT0 = new QCheckBox(groupBox_11);
        checkBoxPIODOUT0->setObjectName(QString::fromUtf8("checkBoxPIODOUT0"));
        checkBoxPIODOUT0->setGeometry(QRect(0, 20, 61, 27));
        checkBoxPIODOUT3 = new QCheckBox(groupBox_11);
        checkBoxPIODOUT3->setObjectName(QString::fromUtf8("checkBoxPIODOUT3"));
        checkBoxPIODOUT3->setGeometry(QRect(0, 110, 61, 27));
        checkBoxPIODOUT2 = new QCheckBox(groupBox_11);
        checkBoxPIODOUT2->setObjectName(QString::fromUtf8("checkBoxPIODOUT2"));
        checkBoxPIODOUT2->setGeometry(QRect(0, 80, 61, 27));
        checkBoxPIODOUT1 = new QCheckBox(groupBox_11);
        checkBoxPIODOUT1->setObjectName(QString::fromUtf8("checkBoxPIODOUT1"));
        checkBoxPIODOUT1->setGeometry(QRect(0, 50, 61, 27));
        groupBox_9 = new QGroupBox(widgetTestMode);
        groupBox_9->setObjectName(QString::fromUtf8("groupBox_9"));
        groupBox_9->setGeometry(QRect(220, 0, 61, 141));
        checkBoxPIOBOUT0 = new QCheckBox(groupBox_9);
        checkBoxPIOBOUT0->setObjectName(QString::fromUtf8("checkBoxPIOBOUT0"));
        checkBoxPIOBOUT0->setGeometry(QRect(0, 20, 61, 27));
        checkBoxPIOBOUT3 = new QCheckBox(groupBox_9);
        checkBoxPIOBOUT3->setObjectName(QString::fromUtf8("checkBoxPIOBOUT3"));
        checkBoxPIOBOUT3->setGeometry(QRect(0, 110, 61, 27));
        checkBoxPIOBOUT2 = new QCheckBox(groupBox_9);
        checkBoxPIOBOUT2->setObjectName(QString::fromUtf8("checkBoxPIOBOUT2"));
        checkBoxPIOBOUT2->setGeometry(QRect(0, 80, 61, 27));
        checkBoxPIOBOUT1 = new QCheckBox(groupBox_9);
        checkBoxPIOBOUT1->setObjectName(QString::fromUtf8("checkBoxPIOBOUT1"));
        checkBoxPIOBOUT1->setGeometry(QRect(0, 50, 61, 27));
        groupBox_7 = new QGroupBox(widgetTestMode);
        groupBox_7->setObjectName(QString::fromUtf8("groupBox_7"));
        groupBox_7->setGeometry(QRect(0, 0, 151, 141));
        checkBoxoGOUT0 = new QCheckBox(groupBox_7);
        checkBoxoGOUT0->setObjectName(QString::fromUtf8("checkBoxoGOUT0"));
        checkBoxoGOUT0->setGeometry(QRect(10, 20, 61, 27));
        checkBoxoGOUT3 = new QCheckBox(groupBox_7);
        checkBoxoGOUT3->setObjectName(QString::fromUtf8("checkBoxoGOUT3"));
        checkBoxoGOUT3->setGeometry(QRect(10, 110, 61, 27));
        checkBoxoGOUT2 = new QCheckBox(groupBox_7);
        checkBoxoGOUT2->setObjectName(QString::fromUtf8("checkBoxoGOUT2"));
        checkBoxoGOUT2->setGeometry(QRect(10, 80, 61, 27));
        checkBoxoGOUT1 = new QCheckBox(groupBox_7);
        checkBoxoGOUT1->setObjectName(QString::fromUtf8("checkBoxoGOUT1"));
        checkBoxoGOUT1->setGeometry(QRect(10, 50, 61, 27));
        checkBoxoGOUT7 = new QCheckBox(groupBox_7);
        checkBoxoGOUT7->setObjectName(QString::fromUtf8("checkBoxoGOUT7"));
        checkBoxoGOUT7->setGeometry(QRect(80, 110, 61, 27));
        checkBoxoGOUT6 = new QCheckBox(groupBox_7);
        checkBoxoGOUT6->setObjectName(QString::fromUtf8("checkBoxoGOUT6"));
        checkBoxoGOUT6->setGeometry(QRect(80, 80, 61, 27));
        checkBoxoGOUT4 = new QCheckBox(groupBox_7);
        checkBoxoGOUT4->setObjectName(QString::fromUtf8("checkBoxoGOUT4"));
        checkBoxoGOUT4->setGeometry(QRect(80, 20, 61, 27));
        checkBoxoGOUT5 = new QCheckBox(groupBox_7);
        checkBoxoGOUT5->setObjectName(QString::fromUtf8("checkBoxoGOUT5"));
        checkBoxoGOUT5->setGeometry(QRect(80, 50, 61, 27));
        groupBox_12 = new QGroupBox(widgetTestMode);
        groupBox_12->setObjectName(QString::fromUtf8("groupBox_12"));
        groupBox_12->setGeometry(QRect(420, 0, 61, 141));
        checkBoxTRGAOUT0 = new QCheckBox(groupBox_12);
        checkBoxTRGAOUT0->setObjectName(QString::fromUtf8("checkBoxTRGAOUT0"));
        checkBoxTRGAOUT0->setGeometry(QRect(0, 20, 61, 27));
        checkBoxTRGAOUT3 = new QCheckBox(groupBox_12);
        checkBoxTRGAOUT3->setObjectName(QString::fromUtf8("checkBoxTRGAOUT3"));
        checkBoxTRGAOUT3->setGeometry(QRect(0, 110, 61, 27));
        checkBoxTRGAOUT2 = new QCheckBox(groupBox_12);
        checkBoxTRGAOUT2->setObjectName(QString::fromUtf8("checkBoxTRGAOUT2"));
        checkBoxTRGAOUT2->setGeometry(QRect(0, 80, 61, 27));
        checkBoxTRGAOUT1 = new QCheckBox(groupBox_12);
        checkBoxTRGAOUT1->setObjectName(QString::fromUtf8("checkBoxTRGAOUT1"));
        checkBoxTRGAOUT1->setGeometry(QRect(0, 50, 61, 27));
        groupBox_13 = new QGroupBox(widgetTestMode);
        groupBox_13->setObjectName(QString::fromUtf8("groupBox_13"));
        groupBox_13->setGeometry(QRect(480, 0, 61, 141));
        checkBoxTRGBOUT0 = new QCheckBox(groupBox_13);
        checkBoxTRGBOUT0->setObjectName(QString::fromUtf8("checkBoxTRGBOUT0"));
        checkBoxTRGBOUT0->setGeometry(QRect(0, 20, 61, 27));
        checkBoxTRGBOUT3 = new QCheckBox(groupBox_13);
        checkBoxTRGBOUT3->setObjectName(QString::fromUtf8("checkBoxTRGBOUT3"));
        checkBoxTRGBOUT3->setGeometry(QRect(0, 110, 61, 27));
        checkBoxTRGBOUT2 = new QCheckBox(groupBox_13);
        checkBoxTRGBOUT2->setObjectName(QString::fromUtf8("checkBoxTRGBOUT2"));
        checkBoxTRGBOUT2->setGeometry(QRect(0, 80, 61, 27));
        checkBoxTRGBOUT1 = new QCheckBox(groupBox_13);
        checkBoxTRGBOUT1->setObjectName(QString::fromUtf8("checkBoxTRGBOUT1"));
        checkBoxTRGBOUT1->setGeometry(QRect(0, 50, 61, 27));
        groupBox_14 = new QGroupBox(widgetTestMode);
        groupBox_14->setObjectName(QString::fromUtf8("groupBox_14"));
        groupBox_14->setGeometry(QRect(540, 0, 61, 141));
        checkBoxTRGCOUT0 = new QCheckBox(groupBox_14);
        checkBoxTRGCOUT0->setObjectName(QString::fromUtf8("checkBoxTRGCOUT0"));
        checkBoxTRGCOUT0->setGeometry(QRect(0, 20, 61, 27));
        checkBoxTRGCOUT3 = new QCheckBox(groupBox_14);
        checkBoxTRGCOUT3->setObjectName(QString::fromUtf8("checkBoxTRGCOUT3"));
        checkBoxTRGCOUT3->setGeometry(QRect(0, 110, 61, 27));
        checkBoxTRGCOUT2 = new QCheckBox(groupBox_14);
        checkBoxTRGCOUT2->setObjectName(QString::fromUtf8("checkBoxTRGCOUT2"));
        checkBoxTRGCOUT2->setGeometry(QRect(0, 80, 61, 27));
        checkBoxTRGCOUT1 = new QCheckBox(groupBox_14);
        checkBoxTRGCOUT1->setObjectName(QString::fromUtf8("checkBoxTRGCOUT1"));
        checkBoxTRGCOUT1->setGeometry(QRect(0, 50, 61, 27));
        groupBox_15 = new QGroupBox(widgetTestMode);
        groupBox_15->setObjectName(QString::fromUtf8("groupBox_15"));
        groupBox_15->setGeometry(QRect(600, 0, 61, 141));
        checkBoxTRGDOUT0 = new QCheckBox(groupBox_15);
        checkBoxTRGDOUT0->setObjectName(QString::fromUtf8("checkBoxTRGDOUT0"));
        checkBoxTRGDOUT0->setGeometry(QRect(0, 20, 61, 27));
        checkBoxTRGDOUT3 = new QCheckBox(groupBox_15);
        checkBoxTRGDOUT3->setObjectName(QString::fromUtf8("checkBoxTRGDOUT3"));
        checkBoxTRGDOUT3->setGeometry(QRect(0, 110, 61, 27));
        checkBoxTRGDOUT2 = new QCheckBox(groupBox_15);
        checkBoxTRGDOUT2->setObjectName(QString::fromUtf8("checkBoxTRGDOUT2"));
        checkBoxTRGDOUT2->setGeometry(QRect(0, 80, 61, 27));
        checkBoxTRGDOUT1 = new QCheckBox(groupBox_15);
        checkBoxTRGDOUT1->setObjectName(QString::fromUtf8("checkBoxTRGDOUT1"));
        checkBoxTRGDOUT1->setGeometry(QRect(0, 50, 61, 27));
        toolButtonTestMode = new QToolButton(centralWidget);
        toolButtonTestMode->setObjectName(QString::fromUtf8("toolButtonTestMode"));
        toolButtonTestMode->setGeometry(QRect(320, 230, 101, 28));
        toolButtonTestMode->setCheckable(true);
        labelMotorPulseCounter2 = new QLabel(centralWidget);
        labelMotorPulseCounter2->setObjectName(QString::fromUtf8("labelMotorPulseCounter2"));
        labelMotorPulseCounter2->setGeometry(QRect(160, 200, 131, 22));
        QPalette palette11;
        palette11.setBrush(QPalette::Active, QPalette::Base, brush);
        palette11.setBrush(QPalette::Active, QPalette::Window, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette11.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette11.setBrush(QPalette::Disabled, QPalette::Window, brush);
        labelMotorPulseCounter2->setPalette(palette11);
        labelMotorPulseCounter2->setAutoFillBackground(true);
        labelMotorPulseCounter2->setFrameShape(QFrame::Panel);
        labelMotorPulseCounter2->setFrameShadow(QFrame::Sunken);
        labelMotorPulseCounter2->setAlignment(Qt::AlignCenter);
        label_12 = new QLabel(centralWidget);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(160, 180, 151, 22));
        LEDControl16GPrnRasPi->setCentralWidget(centralWidget);

        retranslateUi(LEDControl16GPrnRasPi);

        QMetaObject::connectSlotsByName(LEDControl16GPrnRasPi);
    } // setupUi

    void retranslateUi(QMainWindow *LEDControl16GPrnRasPi)
    {
        LEDControl16GPrnRasPi->setWindowTitle(QCoreApplication::translate("LEDControl16GPrnRasPi", "LEDControl16GPrnRasPi", nullptr));
        labelMotorPulseCounter->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "XXXX", nullptr));
        label_2->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "LintTrigger", nullptr));
        label_10->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "Trigger delay parameter", nullptr));
        label->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "MulInput-A", nullptr));
        label_11->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "MulInput-B", nullptr));
        label_9->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "Motor pulse length", nullptr));
        pushButtonSaveSetting->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "Save setting", nullptr));
        pushButtonSendFrameTrigger->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "Send", nullptr));
        label_5->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "Trigger filter", nullptr));
        label_14->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "Minimum OFF", nullptr));
        label_15->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "Minimum ON", nullptr));
        groupBox->setTitle(QCoreApplication::translate("LEDControl16GPrnRasPi", "G-IN", nullptr));
        checkBoxGIN0->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "IN0", nullptr));
        checkBoxGIN3->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "IN3", nullptr));
        checkBoxGIN2->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "IN2", nullptr));
        checkBoxGIN1->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "IN1", nullptr));
        groupBox_2->setTitle(QCoreApplication::translate("LEDControl16GPrnRasPi", "PIO-A", nullptr));
        checkBoxPIOAIN0->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "IN0", nullptr));
        checkBoxPIOAIN3->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "IN3", nullptr));
        checkBoxPIOAIN2->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "IN2", nullptr));
        checkBoxPIOAIN1->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "IN1", nullptr));
        groupBox_3->setTitle(QCoreApplication::translate("LEDControl16GPrnRasPi", "PIO-B", nullptr));
        checkBoxPIOBIN0->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "IN0", nullptr));
        checkBoxPIOBIN3->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "IN3", nullptr));
        checkBoxPIOBIN2->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "IN2", nullptr));
        checkBoxPIOBIN1->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "IN1", nullptr));
        groupBox_4->setTitle(QCoreApplication::translate("LEDControl16GPrnRasPi", "PIO-C", nullptr));
        checkBoxPIOCIN0->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "IN0", nullptr));
        checkBoxPIOCIN3->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "IN3", nullptr));
        checkBoxPIOCIN2->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "IN2", nullptr));
        checkBoxPIOCIN1->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "IN1", nullptr));
        groupBox_5->setTitle(QCoreApplication::translate("LEDControl16GPrnRasPi", "PIO-D", nullptr));
        checkBoxPIODIN0->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "IN0", nullptr));
        checkBoxPIODIN3->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "IN3", nullptr));
        checkBoxPIODIN2->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "IN2", nullptr));
        checkBoxPIODIN1->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "IN1", nullptr));
        groupBox_6->setTitle(QCoreApplication::translate("LEDControl16GPrnRasPi", "Trigger", nullptr));
        checkBoxTRGIN0->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "IN0", nullptr));
        checkBoxTRGIN3->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "IN3", nullptr));
        checkBoxTRGIN2->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "IN2", nullptr));
        checkBoxTRGIN1->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "IN1", nullptr));
        label_6->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "Accept Start", nullptr));
        label_Unit1_2->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "Pulse", nullptr));
        label_16->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "Port A", nullptr));
        label_Unit1_3->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "Pulse", nullptr));
        label_18->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "Accept End", nullptr));
        label_17->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "Port B", nullptr));
        label_Unit1_4->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "Pulse", nullptr));
        label_Unit1_5->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "Pulse", nullptr));
        label_19->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "Port C", nullptr));
        label_Unit1_6->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "Pulse", nullptr));
        label_Unit1_7->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "Pulse", nullptr));
        label_20->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "Port D", nullptr));
        label_Unit1_8->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "Pulse", nullptr));
        label_Unit1_9->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "Pulse", nullptr));
        label_Unit1->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "Pulse", nullptr));
        label_Unit2->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "Pulse", nullptr));
        label_Unit2_2->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "Pulse", nullptr));
        label_Unit2_3->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "Pulse", nullptr));
        label_4->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "Frame trigger", nullptr));
        label_23->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "Flip trigger", nullptr));
        checkBoxFlipFrameTriggerA->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "A", nullptr));
        checkBoxFlipFrameTriggerB->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "B", nullptr));
        checkBoxFlipFrameTriggerC->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "C", nullptr));
        checkBoxFlipFrameTriggerD->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "D", nullptr));
        label_21->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "Convayer length", nullptr));
        label_22->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "Open flat term", nullptr));
        label_7->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "Conveyer", nullptr));
        checkBox->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "Connected", nullptr));
        label_8->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "Yellow : 1/16 motor pulse", nullptr));
        groupBox_8->setTitle(QCoreApplication::translate("LEDControl16GPrnRasPi", "PIO-A", nullptr));
        checkBoxPIOAOUT0->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "P0", nullptr));
        checkBoxPIOAOUT3->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "P3", nullptr));
        checkBoxPIOAOUT2->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "P2", nullptr));
        checkBoxPIOAOUT1->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "P1", nullptr));
        groupBox_10->setTitle(QCoreApplication::translate("LEDControl16GPrnRasPi", "PIO-C", nullptr));
        checkBoxPIOCOUT0->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "P0", nullptr));
        checkBoxPIOCOUT3->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "P3", nullptr));
        checkBoxPIOCOUT2->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "P2", nullptr));
        checkBoxPIOCOUT1->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "P1", nullptr));
        groupBox_11->setTitle(QCoreApplication::translate("LEDControl16GPrnRasPi", "PIO-D", nullptr));
        checkBoxPIODOUT0->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "P0", nullptr));
        checkBoxPIODOUT3->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "P3", nullptr));
        checkBoxPIODOUT2->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "P2", nullptr));
        checkBoxPIODOUT1->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "P1", nullptr));
        groupBox_9->setTitle(QCoreApplication::translate("LEDControl16GPrnRasPi", "PIO-B", nullptr));
        checkBoxPIOBOUT0->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "P0", nullptr));
        checkBoxPIOBOUT3->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "P3", nullptr));
        checkBoxPIOBOUT2->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "P2", nullptr));
        checkBoxPIOBOUT1->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "P1", nullptr));
        groupBox_7->setTitle(QCoreApplication::translate("LEDControl16GPrnRasPi", "G-Out", nullptr));
        checkBoxoGOUT0->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "P0", nullptr));
        checkBoxoGOUT3->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "P3", nullptr));
        checkBoxoGOUT2->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "P2", nullptr));
        checkBoxoGOUT1->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "P1", nullptr));
        checkBoxoGOUT7->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "P7", nullptr));
        checkBoxoGOUT6->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "P6", nullptr));
        checkBoxoGOUT4->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "P4", nullptr));
        checkBoxoGOUT5->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "P5", nullptr));
        groupBox_12->setTitle(QCoreApplication::translate("LEDControl16GPrnRasPi", "TRG-A", nullptr));
        checkBoxTRGAOUT0->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "P0", nullptr));
        checkBoxTRGAOUT3->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "P3", nullptr));
        checkBoxTRGAOUT2->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "P2", nullptr));
        checkBoxTRGAOUT1->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "P1", nullptr));
        groupBox_13->setTitle(QCoreApplication::translate("LEDControl16GPrnRasPi", "TRG-B", nullptr));
        checkBoxTRGBOUT0->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "P0", nullptr));
        checkBoxTRGBOUT3->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "P3", nullptr));
        checkBoxTRGBOUT2->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "P2", nullptr));
        checkBoxTRGBOUT1->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "P1", nullptr));
        groupBox_14->setTitle(QCoreApplication::translate("LEDControl16GPrnRasPi", "TRG-C", nullptr));
        checkBoxTRGCOUT0->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "P0", nullptr));
        checkBoxTRGCOUT3->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "P3", nullptr));
        checkBoxTRGCOUT2->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "P2", nullptr));
        checkBoxTRGCOUT1->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "P1", nullptr));
        groupBox_15->setTitle(QCoreApplication::translate("LEDControl16GPrnRasPi", "TRG-D", nullptr));
        checkBoxTRGDOUT0->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "P0", nullptr));
        checkBoxTRGDOUT3->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "P3", nullptr));
        checkBoxTRGDOUT2->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "P2", nullptr));
        checkBoxTRGDOUT1->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "P1", nullptr));
        toolButtonTestMode->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "TestMode", nullptr));
        labelMotorPulseCounter2->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "XXXX", nullptr));
        label_12->setText(QCoreApplication::translate("LEDControl16GPrnRasPi", "Motor pulse length B", nullptr));
    } // retranslateUi

};

namespace Ui {
    class LEDControl16GPrnRasPi: public Ui_LEDControl16GPrnRasPi {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_LEDCONTROL16GPRNRASPI_H
