#ifndef MAKEDIFFERENCIALIMAGE_GLOBAL_H
#define MAKEDIFFERENCIALIMAGE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef MAKEDIFFERENCIALIMAGE_LIB
# define MAKEDIFFERENCIALIMAGE_EXPORT Q_DECL_EXPORT
#else
# define MAKEDIFFERENCIALIMAGE_EXPORT Q_DECL_IMPORT
#endif

#endif // MAKEDIFFERENCIALIMAGE_GLOBAL_H
