#ifndef SHOWTHRESHOLDFILENAME_GLOBAL_H
#define SHOWTHRESHOLDFILENAME_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SHOWTHRESHOLDFILENAME_LIB
# define SHOWTHRESHOLDFILENAME_EXPORT Q_DECL_EXPORT
#else
# define SHOWTHRESHOLDFILENAME_EXPORT Q_DECL_IMPORT
#endif

#endif // SHOWTHRESHOLDFILENAME_GLOBAL_H
