#ifndef DISTINGUISHPIX_GLOBAL_H
#define DISTINGUISHPIX_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef DISTINGUISHPIX_LIB
# define DISTINGUISHPIX_EXPORT Q_DECL_EXPORT
#else
# define DISTINGUISHPIX_EXPORT Q_DECL_IMPORT
#endif

#endif // DISTINGUISHPIX_GLOBAL_H
