#ifndef DISPLAYSERVER_GLOBAL_H
#define DISPLAYSERVER_GLOBAL_H

#include <qglobal.h>

#ifdef DISPLAYSERVER_LIB
# define DISPLAYSERVER_EXPORT Q_DECL_EXPORT
#else
# define DISPLAYSERVER_EXPORT Q_DECL_IMPORT
#endif

#endif // DISPLAYSERVER_GLOBAL_H
