# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = DFSExplorer
DESTDIR = ../../
CONFIG += debug
DEFINES += QT_LARGEFILE_SUPPORT
LIBS += -L"./../../Lib/Release" \
    -lServiceLib \
    -lDisplayImage \
    -lComponent
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += .
RCC_DIR += .
include(DFSExplorer.pri)
win32:RC_FILE = DFSExplorer.rc
