/********************************************************************************
** Form generated from reading UI file 'PropertyBlockForm.ui'
**
** Created by: Qt User Interface Compiler version 6.10.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_PROPERTYBLOCKFORM_H
#define UI_PROPERTYBLOCKFORM_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QToolButton>
#include <QtWidgets/QWidget>
#include "guiformbase.h"

QT_BEGIN_NAMESPACE

class Ui_PropertyBlockFormClass
{
public:
    QFrame *frame_3;
    QToolButton *toolButtonEdge;
    QToolButton *toolButtonArea;
    QToolButton *toolButtonInside;
    QToolButton *toolButtonBeforeShrink;
    QToolButton *toolButtonOmitMatchLineArea;
    QStackedWidget *stackedWidget;
    QWidget *page;
    QPushButton *pushButtonEditLibFolder;
    QLabel *labelLibFolderName;
    QTableWidget *tableWidgetLibList;
    QTableWidget *tableWidgetGeneratedLibList;
    QPushButton *pushButtonSetFrom;
    QPushButton *pushButtonGetBack;
    QPushButton *pushButtonEditLibrary;
    QPushButton *ButtonPickupClearTest;
    QPushButton *ButtonPickupTest;
    QPushButton *ButtonGenerateLibs;
    QFrame *frame_4;
    QLineEdit *EditLibName;
    QLabel *label_3;
    QLineEdit *EditLibID;
    QLabel *label_4;
    QPushButton *ButtonLibSave;
    QFrame *frame_5;
    QLabel *label_14;
    QSpinBox *EditSpaceToOutline;
    QLabel *label_15;
    QSpinBox *EditNoiseSize;
    QLabel *label_16;
    QSpinBox *EditPriority;
    QLabel *label_53;
    QLabel *label_17;
    QSpinBox *EditNoiseSizePinHole;
    QSpinBox *EditOutlineGeneration;
    QLabel *label_55;
    QCheckBox *checkBPlusHalfDotIsolation;
    QFrame *frame_6;
    QSpinBox *EditMinBlockSize;
    QLabel *label_9;
    QSpinBox *EditMaxBlockSize;
    QLabel *label_10;
    QSpinBox *EditMinBlockDots;
    QLabel *label_12;
    QSpinBox *EditMaxBlockDots;
    QLabel *label_11;
    QLabel *label_13;
    QSpinBox *EditLimitBlockSize;
    QLabel *label_54;
    QLabel *label_30;
    QLabel *label_31;
    QPushButton *pushButtonGetBackAll;
    QPushButton *pushButtonSetFromAll;
    QWidget *page_2;
    QTableWidget *tableWidgetBlockInfo;
    QLabel *label_32;
    QTabWidget *tabWidget;
    QWidget *tab;
    QFrame *frameBlockInfoOnMouse;
    QLabel *label_33;
    QFrame *frame;
    QFrame *frame_15;
    QLabel *label_46;
    QFrame *frame_16;
    QLabel *label_47;
    QSpinBox *EditAdjustBlack;
    QCheckBox *checkBModeAdjustable;
    QSpinBox *EditAdjustWhite;
    QLabel *label_48;
    QLabel *label_49;
    QCheckBox *checkBModeWhiteMask;
    QFrame *frame_8;
    QLabel *label_40;
    QFrame *frame_9;
    QLabel *label_41;
    QLabel *label_42;
    QSpinBox *EditBOKDotH;
    QLabel *label_43;
    QSpinBox *EditBOKDotL;
    QSpinBox *EditBBrightWidthL;
    QLabel *label_44;
    QLabel *label_45;
    QSpinBox *EditBBrightWidthH;
    QSpinBox *EditBMinNGCountL;
    QLabel *label_52;
    QSpinBox *EditBMinNGCountH;
    QSpinBox *EditSelfSearch;
    QLabel *label_50;
    QFrame *frame_7;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *label_37;
    QSpinBox *EditNOKDotH;
    QLabel *label_38;
    QSpinBox *EditNBrightWidthL;
    QSpinBox *EditNOKDotL;
    QSpinBox *EditNBrightWidthH;
    QLabel *label_39;
    QSpinBox *EditNMinNGCountH;
    QLabel *label_51;
    QSpinBox *EditNMinNGCountL;
    QCheckBox *checkBModeBlackMask;
    QLineEdit *EditLibNameInBlock;
    QLineEdit *EditLibIDnBlock;
    QLabel *label_34;
    QWidget *tab_2;
    QPushButton *pushButtonShrink;
    QSpinBox *spinBoxShrink;
    QLabel *label;
    QPushButton *pushButtonShrinkHalf;
    QPushButton *pushButtonExpandHalf;
    QWidget *widget;
    QToolButton *toolButtonCreateBlock;
    QToolButton *toolButtonLibrary;
    QFrame *frame_2;
    QToolButton *toolButtonDirBottom;
    QToolButton *toolButtonDirRight;
    QToolButton *toolButtonDirLeft;
    QToolButton *toolButtonDirUp;
    QToolButton *toolButtonSkipSearch;

    void setupUi(GUIFormBase *PropertyBlockFormClass)
    {
        if (PropertyBlockFormClass->objectName().isEmpty())
            PropertyBlockFormClass->setObjectName("PropertyBlockFormClass");
        PropertyBlockFormClass->resize(400, 700);
        frame_3 = new QFrame(PropertyBlockFormClass);
        frame_3->setObjectName("frame_3");
        frame_3->setGeometry(QRect(244, 4, 61, 40));
        frame_3->setFrameShape(QFrame::NoFrame);
        frame_3->setFrameShadow(QFrame::Plain);
        toolButtonEdge = new QToolButton(frame_3);
        toolButtonEdge->setObjectName("toolButtonEdge");
        toolButtonEdge->setGeometry(QRect(0, 18, 19, 18));
        toolButtonEdge->setCheckable(true);
        toolButtonEdge->setChecked(false);
        toolButtonEdge->setAutoExclusive(true);
        toolButtonArea = new QToolButton(frame_3);
        toolButtonArea->setObjectName("toolButtonArea");
        toolButtonArea->setGeometry(QRect(0, 0, 19, 18));
        toolButtonArea->setCheckable(true);
        toolButtonArea->setChecked(true);
        toolButtonArea->setAutoExclusive(true);
        toolButtonInside = new QToolButton(frame_3);
        toolButtonInside->setObjectName("toolButtonInside");
        toolButtonInside->setGeometry(QRect(20, 18, 19, 18));
        toolButtonInside->setCheckable(true);
        toolButtonInside->setChecked(false);
        toolButtonInside->setAutoExclusive(true);
        toolButtonBeforeShrink = new QToolButton(frame_3);
        toolButtonBeforeShrink->setObjectName("toolButtonBeforeShrink");
        toolButtonBeforeShrink->setGeometry(QRect(20, 0, 19, 18));
        toolButtonBeforeShrink->setCheckable(true);
        toolButtonBeforeShrink->setChecked(false);
        toolButtonBeforeShrink->setAutoExclusive(true);
        toolButtonOmitMatchLineArea = new QToolButton(frame_3);
        toolButtonOmitMatchLineArea->setObjectName("toolButtonOmitMatchLineArea");
        toolButtonOmitMatchLineArea->setGeometry(QRect(40, 0, 19, 18));
        toolButtonOmitMatchLineArea->setCheckable(true);
        toolButtonOmitMatchLineArea->setChecked(false);
        toolButtonOmitMatchLineArea->setAutoExclusive(false);
        stackedWidget = new QStackedWidget(PropertyBlockFormClass);
        stackedWidget->setObjectName("stackedWidget");
        stackedWidget->setGeometry(QRect(0, 40, 401, 671));
        page = new QWidget();
        page->setObjectName("page");
        pushButtonEditLibFolder = new QPushButton(page);
        pushButtonEditLibFolder->setObjectName("pushButtonEditLibFolder");
        pushButtonEditLibFolder->setGeometry(QRect(20, 0, 101, 31));
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/Qtres/Class.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        pushButtonEditLibFolder->setIcon(icon);
        labelLibFolderName = new QLabel(page);
        labelLibFolderName->setObjectName("labelLibFolderName");
        labelLibFolderName->setGeometry(QRect(140, 0, 241, 31));
        QFont font;
        font.setPointSize(16);
        labelLibFolderName->setFont(font);
        tableWidgetLibList = new QTableWidget(page);
        if (tableWidgetLibList->columnCount() < 2)
            tableWidgetLibList->setColumnCount(2);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        tableWidgetLibList->setHorizontalHeaderItem(0, __qtablewidgetitem);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        tableWidgetLibList->setHorizontalHeaderItem(1, __qtablewidgetitem1);
        tableWidgetLibList->setObjectName("tableWidgetLibList");
        tableWidgetLibList->setGeometry(QRect(10, 60, 161, 161));
        tableWidgetLibList->setSelectionMode(QAbstractItemView::SingleSelection);
        tableWidgetLibList->setSelectionBehavior(QAbstractItemView::SelectRows);
        tableWidgetGeneratedLibList = new QTableWidget(page);
        if (tableWidgetGeneratedLibList->columnCount() < 2)
            tableWidgetGeneratedLibList->setColumnCount(2);
        QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
        tableWidgetGeneratedLibList->setHorizontalHeaderItem(0, __qtablewidgetitem2);
        QTableWidgetItem *__qtablewidgetitem3 = new QTableWidgetItem();
        tableWidgetGeneratedLibList->setHorizontalHeaderItem(1, __qtablewidgetitem3);
        tableWidgetGeneratedLibList->setObjectName("tableWidgetGeneratedLibList");
        tableWidgetGeneratedLibList->setGeometry(QRect(230, 60, 161, 161));
        tableWidgetGeneratedLibList->setSelectionBehavior(QAbstractItemView::SelectRows);
        pushButtonSetFrom = new QPushButton(page);
        pushButtonSetFrom->setObjectName("pushButtonSetFrom");
        pushButtonSetFrom->setGeometry(QRect(180, 90, 39, 23));
        pushButtonGetBack = new QPushButton(page);
        pushButtonGetBack->setObjectName("pushButtonGetBack");
        pushButtonGetBack->setGeometry(QRect(180, 120, 39, 23));
        pushButtonEditLibrary = new QPushButton(page);
        pushButtonEditLibrary->setObjectName("pushButtonEditLibrary");
        pushButtonEditLibrary->setGeometry(QRect(200, 230, 191, 31));
        QFont font1;
        font1.setPointSize(12);
        pushButtonEditLibrary->setFont(font1);
        QIcon icon1;
        icon1.addFile(QString::fromUtf8(":/Qtres/Edit.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        pushButtonEditLibrary->setIcon(icon1);
        ButtonPickupClearTest = new QPushButton(page);
        ButtonPickupClearTest->setObjectName("ButtonPickupClearTest");
        ButtonPickupClearTest->setGeometry(QRect(6, 310, 189, 31));
        QFont font2;
        font2.setPointSize(11);
        ButtonPickupClearTest->setFont(font2);
        QIcon icon2;
        icon2.addFile(QString::fromUtf8(":/Qtres/Clear.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        ButtonPickupClearTest->setIcon(icon2);
        ButtonPickupTest = new QPushButton(page);
        ButtonPickupTest->setObjectName("ButtonPickupTest");
        ButtonPickupTest->setGeometry(QRect(6, 254, 189, 51));
        ButtonPickupTest->setFont(font2);
        QIcon icon3;
        icon3.addFile(QString::fromUtf8(":/Qtres/Extract.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        ButtonPickupTest->setIcon(icon3);
        ButtonGenerateLibs = new QPushButton(page);
        ButtonGenerateLibs->setObjectName("ButtonGenerateLibs");
        ButtonGenerateLibs->setGeometry(QRect(196, 270, 199, 71));
        ButtonGenerateLibs->setFont(font2);
        QIcon icon4;
        icon4.addFile(QString::fromUtf8(":/Qtres/Add.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        ButtonGenerateLibs->setIcon(icon4);
        frame_4 = new QFrame(page);
        frame_4->setObjectName("frame_4");
        frame_4->setGeometry(QRect(10, 350, 381, 311));
        frame_4->setFrameShape(QFrame::StyledPanel);
        frame_4->setFrameShadow(QFrame::Sunken);
        EditLibName = new QLineEdit(frame_4);
        EditLibName->setObjectName("EditLibName");
        EditLibName->setGeometry(QRect(140, 20, 231, 21));
        EditLibName->setFont(font1);
        label_3 = new QLabel(frame_4);
        label_3->setObjectName("label_3");
        label_3->setGeometry(QRect(0, 0, 381, 21));
        label_3->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditLibID = new QLineEdit(frame_4);
        EditLibID->setObjectName("EditLibID");
        EditLibID->setGeometry(QRect(60, 20, 81, 21));
        EditLibID->setFont(font1);
        EditLibID->setReadOnly(true);
        label_4 = new QLabel(frame_4);
        label_4->setObjectName("label_4");
        label_4->setGeometry(QRect(10, 20, 51, 21));
        label_4->setFont(font1);
        label_4->setFrameShape(QFrame::Panel);
        label_4->setFrameShadow(QFrame::Sunken);
        label_4->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        ButtonLibSave = new QPushButton(frame_4);
        ButtonLibSave->setObjectName("ButtonLibSave");
        ButtonLibSave->setGeometry(QRect(10, 270, 361, 31));
        QIcon icon5;
        icon5.addFile(QString::fromUtf8(":/Qtres/Update.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        ButtonLibSave->setIcon(icon5);
        frame_5 = new QFrame(frame_4);
        frame_5->setObjectName("frame_5");
        frame_5->setGeometry(QRect(6, 160, 369, 101));
        frame_5->setFrameShape(QFrame::StyledPanel);
        frame_5->setFrameShadow(QFrame::Sunken);
        label_14 = new QLabel(frame_5);
        label_14->setObjectName("label_14");
        label_14->setGeometry(QRect(32, 10, 188, 21));
        label_14->setFrameShape(QFrame::Panel);
        label_14->setFrameShadow(QFrame::Sunken);
        label_14->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditSpaceToOutline = new QSpinBox(frame_5);
        EditSpaceToOutline->setObjectName("EditSpaceToOutline");
        EditSpaceToOutline->setGeometry(QRect(222, 10, 61, 23));
        label_15 = new QLabel(frame_5);
        label_15->setObjectName("label_15");
        label_15->setGeometry(QRect(32, 30, 188, 21));
        label_15->setFrameShape(QFrame::Panel);
        label_15->setFrameShadow(QFrame::Sunken);
        label_15->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditNoiseSize = new QSpinBox(frame_5);
        EditNoiseSize->setObjectName("EditNoiseSize");
        EditNoiseSize->setGeometry(QRect(222, 30, 61, 23));
        QFont font3;
        font3.setPointSize(9);
        EditNoiseSize->setFont(font3);
        label_16 = new QLabel(frame_5);
        label_16->setObjectName("label_16");
        label_16->setGeometry(QRect(290, 50, 71, 21));
        label_16->setFrameShape(QFrame::Panel);
        label_16->setFrameShadow(QFrame::Sunken);
        label_16->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditPriority = new QSpinBox(frame_5);
        EditPriority->setObjectName("EditPriority");
        EditPriority->setGeometry(QRect(290, 70, 61, 23));
        EditPriority->setFont(font3);
        label_53 = new QLabel(frame_5);
        label_53->setObjectName("label_53");
        label_53->setGeometry(QRect(0, 0, 26, 101));
        label_53->setFrameShape(QFrame::Panel);
        label_53->setFrameShadow(QFrame::Raised);
        label_53->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_53->setIndent(1);
        label_17 = new QLabel(frame_5);
        label_17->setObjectName("label_17");
        label_17->setGeometry(QRect(32, 50, 188, 21));
        label_17->setFrameShape(QFrame::Panel);
        label_17->setFrameShadow(QFrame::Sunken);
        label_17->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditNoiseSizePinHole = new QSpinBox(frame_5);
        EditNoiseSizePinHole->setObjectName("EditNoiseSizePinHole");
        EditNoiseSizePinHole->setGeometry(QRect(222, 50, 61, 23));
        EditNoiseSizePinHole->setFont(font3);
        EditOutlineGeneration = new QSpinBox(frame_5);
        EditOutlineGeneration->setObjectName("EditOutlineGeneration");
        EditOutlineGeneration->setGeometry(QRect(222, 70, 61, 23));
        EditOutlineGeneration->setFont(font3);
        EditOutlineGeneration->setMaximum(1000);
        label_55 = new QLabel(frame_5);
        label_55->setObjectName("label_55");
        label_55->setGeometry(QRect(32, 70, 188, 21));
        label_55->setFrameShape(QFrame::Panel);
        label_55->setFrameShadow(QFrame::Sunken);
        label_55->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        checkBPlusHalfDotIsolation = new QCheckBox(frame_5);
        checkBPlusHalfDotIsolation->setObjectName("checkBPlusHalfDotIsolation");
        checkBPlusHalfDotIsolation->setGeometry(QRect(290, 10, 71, 20));
        frame_6 = new QFrame(frame_4);
        frame_6->setObjectName("frame_6");
        frame_6->setGeometry(QRect(6, 50, 369, 111));
        frame_6->setFrameShape(QFrame::StyledPanel);
        frame_6->setFrameShadow(QFrame::Sunken);
        EditMinBlockSize = new QSpinBox(frame_6);
        EditMinBlockSize->setObjectName("EditMinBlockSize");
        EditMinBlockSize->setGeometry(QRect(172, 10, 81, 22));
        EditMinBlockSize->setMaximum(1000000);
        label_9 = new QLabel(frame_6);
        label_9->setObjectName("label_9");
        label_9->setGeometry(QRect(32, 30, 136, 21));
        label_9->setFrameShape(QFrame::Panel);
        label_9->setFrameShadow(QFrame::Sunken);
        label_9->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditMaxBlockSize = new QSpinBox(frame_6);
        EditMaxBlockSize->setObjectName("EditMaxBlockSize");
        EditMaxBlockSize->setGeometry(QRect(172, 30, 81, 22));
        EditMaxBlockSize->setMaximum(1000000);
        label_10 = new QLabel(frame_6);
        label_10->setObjectName("label_10");
        label_10->setGeometry(QRect(32, 10, 136, 21));
        label_10->setFrameShape(QFrame::Panel);
        label_10->setFrameShadow(QFrame::Sunken);
        label_10->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditMinBlockDots = new QSpinBox(frame_6);
        EditMinBlockDots->setObjectName("EditMinBlockDots");
        EditMinBlockDots->setGeometry(QRect(172, 60, 81, 22));
        EditMinBlockDots->setMaximum(2000000000);
        label_12 = new QLabel(frame_6);
        label_12->setObjectName("label_12");
        label_12->setGeometry(QRect(32, 60, 136, 21));
        label_12->setFrameShape(QFrame::Panel);
        label_12->setFrameShadow(QFrame::Sunken);
        label_12->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditMaxBlockDots = new QSpinBox(frame_6);
        EditMaxBlockDots->setObjectName("EditMaxBlockDots");
        EditMaxBlockDots->setGeometry(QRect(172, 80, 91, 22));
        EditMaxBlockDots->setMinimum(-1);
        EditMaxBlockDots->setMaximum(2000000000);
        EditMaxBlockDots->setValue(2000000000);
        label_11 = new QLabel(frame_6);
        label_11->setObjectName("label_11");
        label_11->setGeometry(QRect(32, 80, 136, 21));
        label_11->setFrameShape(QFrame::Panel);
        label_11->setFrameShadow(QFrame::Sunken);
        label_11->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_13 = new QLabel(frame_6);
        label_13->setObjectName("label_13");
        label_13->setGeometry(QRect(270, 60, 91, 21));
        label_13->setFrameShape(QFrame::Panel);
        label_13->setFrameShadow(QFrame::Sunken);
        label_13->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditLimitBlockSize = new QSpinBox(frame_6);
        EditLimitBlockSize->setObjectName("EditLimitBlockSize");
        EditLimitBlockSize->setGeometry(QRect(290, 80, 61, 22));
        EditLimitBlockSize->setMaximum(99999);
        label_54 = new QLabel(frame_6);
        label_54->setObjectName("label_54");
        label_54->setGeometry(QRect(0, 0, 26, 111));
        label_54->setFrameShape(QFrame::Panel);
        label_54->setFrameShadow(QFrame::Raised);
        label_54->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_54->setIndent(1);
        label_30 = new QLabel(page);
        label_30->setObjectName("label_30");
        label_30->setGeometry(QRect(10, 40, 161, 20));
        label_30->setFrameShape(QFrame::Panel);
        label_30->setFrameShadow(QFrame::Sunken);
        label_30->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_31 = new QLabel(page);
        label_31->setObjectName("label_31");
        label_31->setGeometry(QRect(230, 40, 161, 20));
        label_31->setFrameShape(QFrame::Panel);
        label_31->setFrameShadow(QFrame::Sunken);
        label_31->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        pushButtonGetBackAll = new QPushButton(page);
        pushButtonGetBackAll->setObjectName("pushButtonGetBackAll");
        pushButtonGetBackAll->setGeometry(QRect(180, 200, 39, 23));
        pushButtonSetFromAll = new QPushButton(page);
        pushButtonSetFromAll->setObjectName("pushButtonSetFromAll");
        pushButtonSetFromAll->setGeometry(QRect(180, 170, 39, 23));
        stackedWidget->addWidget(page);
        page_2 = new QWidget();
        page_2->setObjectName("page_2");
        tableWidgetBlockInfo = new QTableWidget(page_2);
        if (tableWidgetBlockInfo->columnCount() < 4)
            tableWidgetBlockInfo->setColumnCount(4);
        QTableWidgetItem *__qtablewidgetitem4 = new QTableWidgetItem();
        tableWidgetBlockInfo->setHorizontalHeaderItem(0, __qtablewidgetitem4);
        QTableWidgetItem *__qtablewidgetitem5 = new QTableWidgetItem();
        tableWidgetBlockInfo->setHorizontalHeaderItem(1, __qtablewidgetitem5);
        QTableWidgetItem *__qtablewidgetitem6 = new QTableWidgetItem();
        tableWidgetBlockInfo->setHorizontalHeaderItem(2, __qtablewidgetitem6);
        QTableWidgetItem *__qtablewidgetitem7 = new QTableWidgetItem();
        tableWidgetBlockInfo->setHorizontalHeaderItem(3, __qtablewidgetitem7);
        tableWidgetBlockInfo->setObjectName("tableWidgetBlockInfo");
        tableWidgetBlockInfo->setGeometry(QRect(10, 20, 381, 131));
        tableWidgetBlockInfo->setSelectionMode(QAbstractItemView::MultiSelection);
        label_32 = new QLabel(page_2);
        label_32->setObjectName("label_32");
        label_32->setGeometry(QRect(10, 0, 381, 21));
        label_32->setFont(font1);
        label_32->setFrameShape(QFrame::Panel);
        label_32->setFrameShadow(QFrame::Sunken);
        label_32->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        tabWidget = new QTabWidget(page_2);
        tabWidget->setObjectName("tabWidget");
        tabWidget->setGeometry(QRect(0, 155, 391, 516));
        tab = new QWidget();
        tab->setObjectName("tab");
        frameBlockInfoOnMouse = new QFrame(tab);
        frameBlockInfoOnMouse->setObjectName("frameBlockInfoOnMouse");
        frameBlockInfoOnMouse->setGeometry(QRect(10, 10, 371, 471));
        frameBlockInfoOnMouse->setFrameShape(QFrame::StyledPanel);
        frameBlockInfoOnMouse->setFrameShadow(QFrame::Sunken);
        label_33 = new QLabel(frameBlockInfoOnMouse);
        label_33->setObjectName("label_33");
        label_33->setGeometry(QRect(0, 0, 371, 31));
        label_33->setFont(font1);
        label_33->setFrameShape(QFrame::Panel);
        label_33->setFrameShadow(QFrame::Sunken);
        label_33->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        frame = new QFrame(frameBlockInfoOnMouse);
        frame->setObjectName("frame");
        frame->setGeometry(QRect(10, 70, 351, 401));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Raised);
        frame_15 = new QFrame(frame);
        frame_15->setObjectName("frame_15");
        frame_15->setGeometry(QRect(10, 260, 331, 81));
        frame_15->setFrameShape(QFrame::StyledPanel);
        frame_15->setFrameShadow(QFrame::Sunken);
        label_46 = new QLabel(frame_15);
        label_46->setObjectName("label_46");
        label_46->setGeometry(QRect(0, 0, 20, 81));
        label_46->setFrameShape(QFrame::Panel);
        label_46->setFrameShadow(QFrame::Raised);
        label_46->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_46->setIndent(1);
        frame_16 = new QFrame(frame_15);
        frame_16->setObjectName("frame_16");
        frame_16->setGeometry(QRect(10, 120, 371, 101));
        frame_16->setFrameShape(QFrame::StyledPanel);
        frame_16->setFrameShadow(QFrame::Sunken);
        label_47 = new QLabel(frame_16);
        label_47->setObjectName("label_47");
        label_47->setGeometry(QRect(0, 0, 20, 61));
        label_47->setFrameShape(QFrame::Panel);
        label_47->setFrameShadow(QFrame::Raised);
        label_47->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_47->setIndent(1);
        EditAdjustBlack = new QSpinBox(frame_15);
        EditAdjustBlack->setObjectName("EditAdjustBlack");
        EditAdjustBlack->setGeometry(QRect(230, 30, 81, 22));
        EditAdjustBlack->setMaximum(255);
        checkBModeAdjustable = new QCheckBox(frame_15);
        checkBModeAdjustable->setObjectName("checkBModeAdjustable");
        checkBModeAdjustable->setGeometry(QRect(30, 10, 241, 18));
        EditAdjustWhite = new QSpinBox(frame_15);
        EditAdjustWhite->setObjectName("EditAdjustWhite");
        EditAdjustWhite->setGeometry(QRect(230, 50, 81, 22));
        EditAdjustWhite->setMaximum(255);
        label_48 = new QLabel(frame_15);
        label_48->setObjectName("label_48");
        label_48->setGeometry(QRect(30, 50, 191, 21));
        label_48->setFrameShape(QFrame::Panel);
        label_48->setFrameShadow(QFrame::Sunken);
        label_48->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_49 = new QLabel(frame_15);
        label_49->setObjectName("label_49");
        label_49->setGeometry(QRect(30, 30, 191, 21));
        label_49->setFrameShape(QFrame::Panel);
        label_49->setFrameShadow(QFrame::Sunken);
        label_49->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        checkBModeWhiteMask = new QCheckBox(frame);
        checkBModeWhiteMask->setObjectName("checkBModeWhiteMask");
        checkBModeWhiteMask->setGeometry(QRect(30, 350, 141, 18));
        frame_8 = new QFrame(frame);
        frame_8->setObjectName("frame_8");
        frame_8->setGeometry(QRect(10, 150, 331, 101));
        frame_8->setFrameShape(QFrame::StyledPanel);
        frame_8->setFrameShadow(QFrame::Sunken);
        label_40 = new QLabel(frame_8);
        label_40->setObjectName("label_40");
        label_40->setGeometry(QRect(0, 0, 20, 101));
        label_40->setFrameShape(QFrame::Panel);
        label_40->setFrameShadow(QFrame::Raised);
        label_40->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_40->setIndent(1);
        frame_9 = new QFrame(frame_8);
        frame_9->setObjectName("frame_9");
        frame_9->setGeometry(QRect(10, 120, 371, 101));
        frame_9->setFrameShape(QFrame::StyledPanel);
        frame_9->setFrameShadow(QFrame::Sunken);
        label_41 = new QLabel(frame_9);
        label_41->setObjectName("label_41");
        label_41->setGeometry(QRect(0, 0, 20, 61));
        label_41->setFrameShape(QFrame::Panel);
        label_41->setFrameShadow(QFrame::Raised);
        label_41->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_41->setIndent(1);
        label_42 = new QLabel(frame_8);
        label_42->setObjectName("label_42");
        label_42->setGeometry(QRect(30, 30, 101, 21));
        label_42->setFrameShape(QFrame::Panel);
        label_42->setFrameShadow(QFrame::Sunken);
        label_42->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditBOKDotH = new QSpinBox(frame_8);
        EditBOKDotH->setObjectName("EditBOKDotH");
        EditBOKDotH->setGeometry(QRect(230, 50, 81, 22));
        EditBOKDotH->setMaximum(99999999);
        label_43 = new QLabel(frame_8);
        label_43->setObjectName("label_43");
        label_43->setGeometry(QRect(230, 10, 81, 21));
        label_43->setFrameShape(QFrame::Panel);
        label_43->setFrameShadow(QFrame::Sunken);
        label_43->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditBOKDotL = new QSpinBox(frame_8);
        EditBOKDotL->setObjectName("EditBOKDotL");
        EditBOKDotL->setGeometry(QRect(140, 50, 81, 22));
        EditBOKDotL->setMaximum(99999999);
        EditBBrightWidthL = new QSpinBox(frame_8);
        EditBBrightWidthL->setObjectName("EditBBrightWidthL");
        EditBBrightWidthL->setGeometry(QRect(140, 30, 81, 22));
        EditBBrightWidthL->setMaximum(255);
        label_44 = new QLabel(frame_8);
        label_44->setObjectName("label_44");
        label_44->setGeometry(QRect(30, 50, 101, 21));
        label_44->setFrameShape(QFrame::Panel);
        label_44->setFrameShadow(QFrame::Sunken);
        label_44->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_45 = new QLabel(frame_8);
        label_45->setObjectName("label_45");
        label_45->setGeometry(QRect(140, 10, 81, 21));
        label_45->setFrameShape(QFrame::Panel);
        label_45->setFrameShadow(QFrame::Sunken);
        label_45->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditBBrightWidthH = new QSpinBox(frame_8);
        EditBBrightWidthH->setObjectName("EditBBrightWidthH");
        EditBBrightWidthH->setGeometry(QRect(230, 30, 81, 22));
        EditBBrightWidthH->setMaximum(255);
        EditBMinNGCountL = new QSpinBox(frame_8);
        EditBMinNGCountL->setObjectName("EditBMinNGCountL");
        EditBMinNGCountL->setGeometry(QRect(140, 70, 81, 22));
        EditBMinNGCountL->setMaximum(99999999);
        label_52 = new QLabel(frame_8);
        label_52->setObjectName("label_52");
        label_52->setGeometry(QRect(30, 70, 101, 21));
        label_52->setFrameShape(QFrame::Panel);
        label_52->setFrameShadow(QFrame::Sunken);
        label_52->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditBMinNGCountH = new QSpinBox(frame_8);
        EditBMinNGCountH->setObjectName("EditBMinNGCountH");
        EditBMinNGCountH->setGeometry(QRect(230, 70, 81, 22));
        EditBMinNGCountH->setMaximum(99999999);
        EditSelfSearch = new QSpinBox(frame);
        EditSelfSearch->setObjectName("EditSelfSearch");
        EditSelfSearch->setGeometry(QRect(240, 370, 81, 22));
        label_50 = new QLabel(frame);
        label_50->setObjectName("label_50");
        label_50->setGeometry(QRect(30, 370, 201, 21));
        label_50->setFrameShape(QFrame::Panel);
        label_50->setFrameShadow(QFrame::Sunken);
        label_50->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        frame_7 = new QFrame(frame);
        frame_7->setObjectName("frame_7");
        frame_7->setGeometry(QRect(10, 50, 331, 101));
        frame_7->setFrameShape(QFrame::StyledPanel);
        frame_7->setFrameShadow(QFrame::Sunken);
        label_35 = new QLabel(frame_7);
        label_35->setObjectName("label_35");
        label_35->setGeometry(QRect(0, 0, 20, 101));
        label_35->setFrameShape(QFrame::Panel);
        label_35->setFrameShadow(QFrame::Raised);
        label_35->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_35->setIndent(1);
        label_36 = new QLabel(frame_7);
        label_36->setObjectName("label_36");
        label_36->setGeometry(QRect(230, 10, 81, 21));
        label_36->setFrameShape(QFrame::Panel);
        label_36->setFrameShadow(QFrame::Sunken);
        label_36->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_37 = new QLabel(frame_7);
        label_37->setObjectName("label_37");
        label_37->setGeometry(QRect(30, 30, 101, 21));
        label_37->setFrameShape(QFrame::Panel);
        label_37->setFrameShadow(QFrame::Sunken);
        label_37->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditNOKDotH = new QSpinBox(frame_7);
        EditNOKDotH->setObjectName("EditNOKDotH");
        EditNOKDotH->setGeometry(QRect(230, 50, 81, 22));
        EditNOKDotH->setMaximum(99999999);
        label_38 = new QLabel(frame_7);
        label_38->setObjectName("label_38");
        label_38->setGeometry(QRect(30, 50, 101, 21));
        label_38->setFrameShape(QFrame::Panel);
        label_38->setFrameShadow(QFrame::Sunken);
        label_38->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditNBrightWidthL = new QSpinBox(frame_7);
        EditNBrightWidthL->setObjectName("EditNBrightWidthL");
        EditNBrightWidthL->setGeometry(QRect(140, 30, 81, 22));
        EditNBrightWidthL->setMaximum(255);
        EditNOKDotL = new QSpinBox(frame_7);
        EditNOKDotL->setObjectName("EditNOKDotL");
        EditNOKDotL->setGeometry(QRect(140, 50, 81, 22));
        EditNOKDotL->setMaximum(99999999);
        EditNBrightWidthH = new QSpinBox(frame_7);
        EditNBrightWidthH->setObjectName("EditNBrightWidthH");
        EditNBrightWidthH->setGeometry(QRect(230, 30, 81, 22));
        EditNBrightWidthH->setMaximum(255);
        label_39 = new QLabel(frame_7);
        label_39->setObjectName("label_39");
        label_39->setGeometry(QRect(140, 10, 81, 21));
        label_39->setFrameShape(QFrame::Panel);
        label_39->setFrameShadow(QFrame::Sunken);
        label_39->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditNMinNGCountH = new QSpinBox(frame_7);
        EditNMinNGCountH->setObjectName("EditNMinNGCountH");
        EditNMinNGCountH->setGeometry(QRect(230, 70, 81, 22));
        EditNMinNGCountH->setMaximum(99999999);
        label_51 = new QLabel(frame_7);
        label_51->setObjectName("label_51");
        label_51->setGeometry(QRect(30, 70, 101, 21));
        label_51->setFrameShape(QFrame::Panel);
        label_51->setFrameShadow(QFrame::Sunken);
        label_51->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditNMinNGCountL = new QSpinBox(frame_7);
        EditNMinNGCountL->setObjectName("EditNMinNGCountL");
        EditNMinNGCountL->setGeometry(QRect(140, 70, 81, 22));
        EditNMinNGCountL->setMaximum(99999999);
        checkBModeBlackMask = new QCheckBox(frame);
        checkBModeBlackMask->setObjectName("checkBModeBlackMask");
        checkBModeBlackMask->setGeometry(QRect(190, 350, 141, 18));
        EditLibNameInBlock = new QLineEdit(frame);
        EditLibNameInBlock->setObjectName("EditLibNameInBlock");
        EditLibNameInBlock->setGeometry(QRect(120, 10, 231, 31));
        EditLibNameInBlock->setFont(font1);
        EditLibIDnBlock = new QLineEdit(frame);
        EditLibIDnBlock->setObjectName("EditLibIDnBlock");
        EditLibIDnBlock->setGeometry(QRect(60, 10, 61, 31));
        EditLibIDnBlock->setFont(font1);
        EditLibIDnBlock->setReadOnly(true);
        label_34 = new QLabel(frame);
        label_34->setObjectName("label_34");
        label_34->setGeometry(QRect(10, 10, 51, 31));
        label_34->setFont(font1);
        label_34->setFrameShape(QFrame::Panel);
        label_34->setFrameShadow(QFrame::Sunken);
        label_34->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        tabWidget->addTab(tab, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName("tab_2");
        pushButtonShrink = new QPushButton(tab_2);
        pushButtonShrink->setObjectName("pushButtonShrink");
        pushButtonShrink->setGeometry(QRect(140, 20, 181, 31));
        QIcon icon6;
        icon6.addFile(QString::fromUtf8(":/Qtres/Select.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        pushButtonShrink->setIcon(icon6);
        spinBoxShrink = new QSpinBox(tab_2);
        spinBoxShrink->setObjectName("spinBoxShrink");
        spinBoxShrink->setGeometry(QRect(20, 20, 101, 31));
        spinBoxShrink->setMinimum(-99);
        label = new QLabel(tab_2);
        label->setObjectName("label");
        label->setGeometry(QRect(30, 50, 331, 21));
        pushButtonShrinkHalf = new QPushButton(tab_2);
        pushButtonShrinkHalf->setObjectName("pushButtonShrinkHalf");
        pushButtonShrinkHalf->setGeometry(QRect(140, 90, 221, 31));
        pushButtonShrinkHalf->setIcon(icon6);
        pushButtonExpandHalf = new QPushButton(tab_2);
        pushButtonExpandHalf->setObjectName("pushButtonExpandHalf");
        pushButtonExpandHalf->setGeometry(QRect(140, 130, 221, 31));
        pushButtonExpandHalf->setIcon(icon6);
        tabWidget->addTab(tab_2, QString());
        stackedWidget->addWidget(page_2);
        widget = new QWidget(PropertyBlockFormClass);
        widget->setObjectName("widget");
        widget->setGeometry(QRect(4, 4, 231, 31));
        toolButtonCreateBlock = new QToolButton(widget);
        toolButtonCreateBlock->setObjectName("toolButtonCreateBlock");
        toolButtonCreateBlock->setGeometry(QRect(120, 0, 111, 31));
        toolButtonCreateBlock->setCheckable(true);
        toolButtonCreateBlock->setAutoExclusive(true);
        toolButtonLibrary = new QToolButton(widget);
        toolButtonLibrary->setObjectName("toolButtonLibrary");
        toolButtonLibrary->setGeometry(QRect(3, 0, 111, 31));
        toolButtonLibrary->setCheckable(true);
        toolButtonLibrary->setChecked(true);
        toolButtonLibrary->setAutoExclusive(true);
        toolButtonLibrary->setToolButtonStyle(Qt::ToolButtonTextBesideIcon);
        frame_2 = new QFrame(PropertyBlockFormClass);
        frame_2->setObjectName("frame_2");
        frame_2->setGeometry(QRect(310, 0, 91, 41));
        frame_2->setFrameShape(QFrame::StyledPanel);
        frame_2->setFrameShadow(QFrame::Raised);
        toolButtonDirBottom = new QToolButton(frame_2);
        toolButtonDirBottom->setObjectName("toolButtonDirBottom");
        toolButtonDirBottom->setGeometry(QRect(20, 20, 19, 18));
        toolButtonDirBottom->setCheckable(true);
        toolButtonDirBottom->setChecked(true);
        toolButtonDirBottom->setAutoExclusive(true);
        toolButtonDirRight = new QToolButton(frame_2);
        toolButtonDirRight->setObjectName("toolButtonDirRight");
        toolButtonDirRight->setGeometry(QRect(40, 10, 19, 18));
        toolButtonDirRight->setCheckable(true);
        toolButtonDirRight->setChecked(true);
        toolButtonDirRight->setAutoExclusive(true);
        toolButtonDirLeft = new QToolButton(frame_2);
        toolButtonDirLeft->setObjectName("toolButtonDirLeft");
        toolButtonDirLeft->setGeometry(QRect(0, 10, 19, 18));
        toolButtonDirLeft->setCheckable(true);
        toolButtonDirLeft->setChecked(true);
        toolButtonDirLeft->setAutoExclusive(true);
        toolButtonDirUp = new QToolButton(frame_2);
        toolButtonDirUp->setObjectName("toolButtonDirUp");
        toolButtonDirUp->setGeometry(QRect(20, 0, 19, 18));
        toolButtonDirUp->setCheckable(true);
        toolButtonDirUp->setChecked(true);
        toolButtonDirUp->setAutoExclusive(true);
        toolButtonSkipSearch = new QToolButton(frame_2);
        toolButtonSkipSearch->setObjectName("toolButtonSkipSearch");
        toolButtonSkipSearch->setGeometry(QRect(60, 3, 26, 34));
        toolButtonSkipSearch->setCheckable(true);

        retranslateUi(PropertyBlockFormClass);

        stackedWidget->setCurrentIndex(0);
        tabWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(PropertyBlockFormClass);
    } // setupUi

    void retranslateUi(GUIFormBase *PropertyBlockFormClass)
    {
        PropertyBlockFormClass->setWindowTitle(QCoreApplication::translate("PropertyBlockFormClass", "PropertyBlockForm", nullptr));
        toolButtonEdge->setText(QCoreApplication::translate("PropertyBlockFormClass", "E", nullptr));
        toolButtonArea->setText(QCoreApplication::translate("PropertyBlockFormClass", "A", nullptr));
        toolButtonInside->setText(QCoreApplication::translate("PropertyBlockFormClass", "I", nullptr));
        toolButtonBeforeShrink->setText(QCoreApplication::translate("PropertyBlockFormClass", "B", nullptr));
        toolButtonOmitMatchLineArea->setText(QCoreApplication::translate("PropertyBlockFormClass", "O", nullptr));
        pushButtonEditLibFolder->setText(QCoreApplication::translate("PropertyBlockFormClass", "\345\210\206\351\241\236\351\201\270\346\212\236", nullptr));
        labelLibFolderName->setText(QCoreApplication::translate("PropertyBlockFormClass", "\357\274\270\357\274\270\357\274\270", nullptr));
        QTableWidgetItem *___qtablewidgetitem = tableWidgetLibList->horizontalHeaderItem(0);
        ___qtablewidgetitem->setText(QCoreApplication::translate("PropertyBlockFormClass", "ID", nullptr));
        QTableWidgetItem *___qtablewidgetitem1 = tableWidgetLibList->horizontalHeaderItem(1);
        ___qtablewidgetitem1->setText(QCoreApplication::translate("PropertyBlockFormClass", "Name", nullptr));
        QTableWidgetItem *___qtablewidgetitem2 = tableWidgetGeneratedLibList->horizontalHeaderItem(0);
        ___qtablewidgetitem2->setText(QCoreApplication::translate("PropertyBlockFormClass", "ID", nullptr));
        QTableWidgetItem *___qtablewidgetitem3 = tableWidgetGeneratedLibList->horizontalHeaderItem(1);
        ___qtablewidgetitem3->setText(QCoreApplication::translate("PropertyBlockFormClass", "Name", nullptr));
        pushButtonSetFrom->setText(QCoreApplication::translate("PropertyBlockFormClass", "=>", nullptr));
        pushButtonGetBack->setText(QCoreApplication::translate("PropertyBlockFormClass", "<=", nullptr));
        pushButtonEditLibrary->setText(QCoreApplication::translate("PropertyBlockFormClass", "\343\203\251\343\202\244\343\203\226\343\203\251\343\203\252\347\267\250\351\233\206", nullptr));
        ButtonPickupClearTest->setText(QCoreApplication::translate("PropertyBlockFormClass", "\346\212\275\345\207\272\343\201\256\343\202\257\343\203\252\343\202\242", nullptr));
        ButtonPickupTest->setText(QCoreApplication::translate("PropertyBlockFormClass", "\345\215\230\344\270\200\343\203\251\343\202\244\343\203\226\343\203\251\343\203\252\343\201\247\343\201\256\346\212\275\345\207\272", nullptr));
        ButtonGenerateLibs->setText(QCoreApplication::translate("PropertyBlockFormClass", "\344\270\212\343\201\256\345\205\250\343\201\246\343\201\256\343\203\251\343\202\244\343\203\226\343\203\251\343\203\252\343\201\247\347\224\237\346\210\220", nullptr));
        EditLibName->setText(QCoreApplication::translate("PropertyBlockFormClass", "Library Name", nullptr));
        label_3->setText(QCoreApplication::translate("PropertyBlockFormClass", "\343\203\251\343\202\244\343\203\226\343\203\251\343\203\252\343\203\227\343\203\255\343\203\221\343\203\206\343\202\243", nullptr));
        EditLibID->setText(QCoreApplication::translate("PropertyBlockFormClass", "12345", nullptr));
        label_4->setText(QCoreApplication::translate("PropertyBlockFormClass", "\345\220\215\347\247\260", nullptr));
        ButtonLibSave->setText(QCoreApplication::translate("PropertyBlockFormClass", "\343\203\207\343\203\274\343\202\277\343\203\231\343\203\274\343\202\271\343\201\270\343\201\256\346\233\264\346\226\260", nullptr));
        label_14->setText(QCoreApplication::translate("PropertyBlockFormClass", "\350\274\252\351\203\255\343\201\213\343\202\211\343\201\256\351\226\223\351\232\224", nullptr));
        label_15->setText(QCoreApplication::translate("PropertyBlockFormClass", "\343\203\216\343\202\244\343\202\272\343\202\265\343\202\244\343\202\272 \345\255\244\347\253\213\347\202\271\345\211\212\351\231\244", nullptr));
        label_16->setText(QCoreApplication::translate("PropertyBlockFormClass", "\345\204\252\345\205\210\345\272\246", nullptr));
        label_53->setText(QCoreApplication::translate("PropertyBlockFormClass", "\347\224\237\n"
"\346\210\220", nullptr));
        label_17->setText(QCoreApplication::translate("PropertyBlockFormClass", "\343\203\216\343\202\244\343\202\272\343\202\265\343\202\244\343\202\272\343\200\200\343\203\224\343\203\263\343\203\233\343\203\274\343\203\253\345\211\212\351\231\244", nullptr));
        label_55->setText(QCoreApplication::translate("PropertyBlockFormClass", "\350\274\252\351\203\255\344\273\230\350\277\221\343\201\253\347\224\237\346\210\220(Max1000)", nullptr));
        checkBPlusHalfDotIsolation->setText(QCoreApplication::translate("PropertyBlockFormClass", "\357\274\213\345\215\212\343\203\211\343\203\203\343\203\210", nullptr));
        label_9->setText(QCoreApplication::translate("PropertyBlockFormClass", "\343\203\226\343\203\255\343\203\203\343\202\257\346\234\200\345\244\247\343\202\265\343\202\244\343\202\272", nullptr));
        label_10->setText(QCoreApplication::translate("PropertyBlockFormClass", "\343\203\226\343\203\255\343\203\203\343\202\257\346\234\200\345\260\217\343\202\265\343\202\244\343\202\272", nullptr));
        label_12->setText(QCoreApplication::translate("PropertyBlockFormClass", "\343\203\226\343\203\255\343\203\203\343\202\257\346\234\200\345\260\217\351\235\242\347\251\215", nullptr));
        label_11->setText(QCoreApplication::translate("PropertyBlockFormClass", "\343\203\226\343\203\255\343\203\203\343\202\257\346\234\200\345\244\247\351\235\242\347\251\215", nullptr));
        label_13->setText(QCoreApplication::translate("PropertyBlockFormClass", "\351\231\220\347\225\214\343\202\265\343\202\244\343\202\272", nullptr));
        label_54->setText(QCoreApplication::translate("PropertyBlockFormClass", "\343\202\265\n"
"\343\202\244\n"
"\343\202\272", nullptr));
        label_30->setText(QCoreApplication::translate("PropertyBlockFormClass", "\347\231\273\351\214\262\343\201\225\343\202\214\343\201\246\343\201\204\343\202\213\343\203\251\343\202\244\343\203\226\343\203\251\343\203\252\343\203\252\343\202\271\343\203\210", nullptr));
        label_31->setText(QCoreApplication::translate("PropertyBlockFormClass", "\344\273\212\345\233\236\344\275\277\347\224\250\343\201\231\343\202\213\350\250\255\345\256\232", nullptr));
        pushButtonGetBackAll->setText(QCoreApplication::translate("PropertyBlockFormClass", "<<=", nullptr));
        pushButtonSetFromAll->setText(QCoreApplication::translate("PropertyBlockFormClass", "=>>", nullptr));
        QTableWidgetItem *___qtablewidgetitem4 = tableWidgetBlockInfo->horizontalHeaderItem(0);
        ___qtablewidgetitem4->setText(QCoreApplication::translate("PropertyBlockFormClass", "ID", nullptr));
        QTableWidgetItem *___qtablewidgetitem5 = tableWidgetBlockInfo->horizontalHeaderItem(1);
        ___qtablewidgetitem5->setText(QCoreApplication::translate("PropertyBlockFormClass", "\343\203\251\343\202\244\343\203\226\343\203\251\343\203\252\345\220\215", nullptr));
        QTableWidgetItem *___qtablewidgetitem6 = tableWidgetBlockInfo->horizontalHeaderItem(2);
        ___qtablewidgetitem6->setText(QCoreApplication::translate("PropertyBlockFormClass", "\343\203\226\343\203\255\343\203\203\343\202\257\347\267\217\346\225\260", nullptr));
        QTableWidgetItem *___qtablewidgetitem7 = tableWidgetBlockInfo->horizontalHeaderItem(3);
        ___qtablewidgetitem7->setText(QCoreApplication::translate("PropertyBlockFormClass", "\343\203\254\343\202\244\343\203\244\343\203\274\357\274\221", nullptr));
        label_32->setText(QCoreApplication::translate("PropertyBlockFormClass", "\344\275\277\347\224\250\343\201\225\343\202\214\343\201\246\343\201\204\343\202\213\343\203\226\343\203\255\343\203\203\343\202\257\346\203\205\345\240\261", nullptr));
        label_33->setText(QCoreApplication::translate("PropertyBlockFormClass", "\343\203\236\343\202\246\343\202\271\343\202\253\343\203\274\343\202\275\343\203\253\344\275\215\347\275\256\343\201\256\343\203\226\343\203\255\343\203\203\343\202\257\346\203\205\345\240\261", nullptr));
        label_46->setText(QCoreApplication::translate("PropertyBlockFormClass", "\350\243\234\n"
"\346\255\243", nullptr));
        label_47->setText(QCoreApplication::translate("PropertyBlockFormClass", "\350\274\235\n"
"\345\272\246", nullptr));
        checkBModeAdjustable->setText(QCoreApplication::translate("PropertyBlockFormClass", "\344\270\255\345\277\203\350\274\235\345\272\246\350\243\234\346\255\243\343\202\222\346\234\211\345\212\271\343\201\253\343\201\231\343\202\213", nullptr));
        label_48->setText(QCoreApplication::translate("PropertyBlockFormClass", "\346\230\216\345\201\264\343\200\200\346\234\200\345\244\247\350\243\234\346\255\243\350\274\235\345\272\246\351\207\217", nullptr));
        label_49->setText(QCoreApplication::translate("PropertyBlockFormClass", "\346\232\227\345\201\264\343\200\200\346\234\200\345\244\247\350\243\234\346\255\243\350\274\235\345\272\246\351\207\217", nullptr));
        checkBModeWhiteMask->setText(QCoreApplication::translate("PropertyBlockFormClass", "\347\231\275\343\203\236\343\202\271\343\202\257", nullptr));
        label_40->setText(QCoreApplication::translate("PropertyBlockFormClass", "\345\272\203\n"
"\345\237\237", nullptr));
        label_41->setText(QCoreApplication::translate("PropertyBlockFormClass", "\350\274\235\n"
"\345\272\246", nullptr));
        label_42->setText(QCoreApplication::translate("PropertyBlockFormClass", "OK\350\274\235\345\272\246\347\257\204\345\233\262", nullptr));
        label_43->setText(QCoreApplication::translate("PropertyBlockFormClass", "\346\230\216\345\201\264", nullptr));
        label_44->setText(QCoreApplication::translate("PropertyBlockFormClass", "OK\343\203\211\343\203\203\343\203\210\346\225\260", nullptr));
        label_45->setText(QCoreApplication::translate("PropertyBlockFormClass", "\346\232\227\345\201\264", nullptr));
        label_52->setText(QCoreApplication::translate("PropertyBlockFormClass", "\357\274\256\357\274\247\345\241\212\345\200\213\346\225\260", nullptr));
        label_50->setText(QCoreApplication::translate("PropertyBlockFormClass", "\343\203\226\343\203\255\343\203\203\343\202\257\345\215\230\344\275\223\343\201\247\343\201\256\346\216\242\347\264\242\343\203\211\343\203\203\343\203\210\346\225\260", nullptr));
        label_35->setText(QCoreApplication::translate("PropertyBlockFormClass", "\347\213\255\n"
"\345\237\237", nullptr));
        label_36->setText(QCoreApplication::translate("PropertyBlockFormClass", "\346\230\216\345\201\264", nullptr));
        label_37->setText(QCoreApplication::translate("PropertyBlockFormClass", "OK\350\274\235\345\272\246\347\257\204\345\233\262", nullptr));
        label_38->setText(QCoreApplication::translate("PropertyBlockFormClass", "OK\343\203\211\343\203\203\343\203\210\346\225\260", nullptr));
        label_39->setText(QCoreApplication::translate("PropertyBlockFormClass", "\346\232\227\345\201\264", nullptr));
        label_51->setText(QCoreApplication::translate("PropertyBlockFormClass", "NG\345\241\212\345\200\213\346\225\260", nullptr));
        checkBModeBlackMask->setText(QCoreApplication::translate("PropertyBlockFormClass", "\351\273\222\343\203\236\343\202\271\343\202\257", nullptr));
        EditLibNameInBlock->setText(QCoreApplication::translate("PropertyBlockFormClass", "Library Name", nullptr));
        EditLibIDnBlock->setText(QCoreApplication::translate("PropertyBlockFormClass", "12345", nullptr));
        label_34->setText(QCoreApplication::translate("PropertyBlockFormClass", "\345\220\215\347\247\260", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab), QCoreApplication::translate("PropertyBlockFormClass", "Information", nullptr));
        pushButtonShrink->setText(QCoreApplication::translate("PropertyBlockFormClass", "Shrink selected block", nullptr));
        label->setText(QCoreApplication::translate("PropertyBlockFormClass", "Plus: Shrink    Minus:Expansion", nullptr));
        pushButtonShrinkHalf->setText(QCoreApplication::translate("PropertyBlockFormClass", "Shrink-half selected block", nullptr));
        pushButtonExpandHalf->setText(QCoreApplication::translate("PropertyBlockFormClass", "Expand-half selected block", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QCoreApplication::translate("PropertyBlockFormClass", "Operation", nullptr));
        toolButtonCreateBlock->setText(QCoreApplication::translate("PropertyBlockFormClass", "Create Block", nullptr));
        toolButtonLibrary->setText(QCoreApplication::translate("PropertyBlockFormClass", "Library Test", nullptr));
        toolButtonDirBottom->setText(QCoreApplication::translate("PropertyBlockFormClass", "4", nullptr));
        toolButtonDirRight->setText(QCoreApplication::translate("PropertyBlockFormClass", "4", nullptr));
        toolButtonDirLeft->setText(QCoreApplication::translate("PropertyBlockFormClass", "4", nullptr));
        toolButtonDirUp->setText(QCoreApplication::translate("PropertyBlockFormClass", "4", nullptr));
        toolButtonSkipSearch->setText(QCoreApplication::translate("PropertyBlockFormClass", "S", nullptr));
    } // retranslateUi

};

namespace Ui {
    class PropertyBlockFormClass: public Ui_PropertyBlockFormClass {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_PROPERTYBLOCKFORM_H
