#ifndef LISTHISTORYSYNC_GLOBAL_H
#define LISTHISTORYSYNC_GLOBAL_H

#include <qglobal.h>

#ifdef LISTHISTORYSYNC_LIB
# define LISTHISTORYSYNC_EXPORT Q_DECL_EXPORT
#else
# define LISTHISTORYSYNC_EXPORT Q_DECL_IMPORT
#endif

#endif // LISTHISTORYSYNC_GLOBAL_H
