#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(SERVICEEXECUTIONEDITOR_LIB)
#  define SERVICEEXECUTIONEDITOR_EXPORT Q_DECL_EXPORT
# else
#  define SERVICEEXECUTIONEDITOR_EXPORT Q_DECL_IMPORT
# endif
#else
# define SERVICEEXECUTIONEDITOR_EXPORT
#endif
