#ifndef EVOBJCURRENTPHASE_GLOBAL_H
#define EVOBJCURRENTPHASE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef EVOBJCURRENTPHASE_LIB
# define EVOBJCURRENTPHASE_EXPORT Q_DECL_EXPORT
#else
# define EVOBJCURRENTPHASE_EXPORT Q_DECL_IMPORT
#endif

#endif // EVOBJCURRENTPHASE_GLOBAL_H
