#ifndef PROPERTYPARTIALIMAGING_GLOBAL_H
#define PROPERTYPARTIALIMAGING_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PROPERTYPARTIALIMAGING_LIB
# define PROPERTYPARTIALIMAGING_EXPORT Q_DECL_EXPORT
#else
# define PROPERTYPARTIALIMAGING_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTYPARTIALIMAGING_GLOBAL_H
