#ifndef INTEGRATIONSHOWRELATIONINFO_GLOBAL_H
#define INTEGRATIONSHOWRELATIONINFO_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef INTEGRATIONSHOWRELATIONINFO_LIB
# define INTEGRATIONSHOWRELATIONINFO_EXPORT Q_DECL_EXPORT
#else
# define INTEGRATIONSHOWRELATIONINFO_EXPORT Q_DECL_IMPORT
#endif

#endif // INTEGRATIONSHOWRELATIONINFO_GLOBAL_H
