#ifndef FILTERMOVEIMAGE_GLOBAL_H
#define FILTERMOVEIMAGE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef FILTERMOVEIMAGE_LIB
# define FILTERMOVEIMAGE_EXPORT Q_DECL_EXPORT
#else
# define FILTERMOVEIMAGE_EXPORT Q_DECL_IMPORT
#endif

#endif // FILTERMOVEIMAGE_GLOBAL_H
