#ifndef MATCHINGALIGNMENTIMAGEPANEL_GLOBAL_H
#define MATCHINGALIGNMENTIMAGEPANEL_GLOBAL_H

#include <qglobal.h>

#ifdef MATCHINGALIGNMENTIMAGEPANEL_LIB
# define MATCHINGALIGNMENTIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define MATCHINGALIGNMENTIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // MATCHINGALIGNMENTIMAGEPANEL_GLOBAL_H
