#ifndef LIGHTUSB8PORTARM_GLOBAL_H
#define LIGHTUSB8PORTARM_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef LIGHTUSB8PORTARM_LIB
# define LIGHTUSB8PORTARM_EXPORT Q_DECL_EXPORT
#else
# define LIGHTUSB8PORTARM_EXPORT Q_DECL_IMPORT
#endif

#endif // LIGHTUSB8PORTARM_GLOBAL_H
