#ifndef PROPERTYAUTOPCBHOLEALIGNER_GLOBAL_H
#define PROPERTYAUTOPCBHOLEALIGNER_GLOBAL_H

#include <qglobal.h>

#ifdef PROPERTYAUTOPCBHOLEALIGNER_LIB
# define PROPERTYAUTOPCBHOLEALIGNER_EXPORT Q_DECL_EXPORT
#else
# define PROPERTYAUTOPCBHOLEALIGNER_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTYAUTOPCBHOLEALIGNER_GLOBAL_H
