#ifndef BCRINSPECTION_GLOBAL_H
#define BCRINSPECTION_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BCRINSPECTION_LIB
# define BCRINSPECTION_EXPORT Q_DECL_EXPORT
#else
# define BCRINSPECTION_EXPORT Q_DECL_IMPORT
#endif

#endif // BCRINSPECTION_GLOBAL_H
