#ifndef RESULTKIDAOUTPUT_GLOBAL_H
#define RESULTKIDAOUTPUT_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef RESULTKIDAOUTPUT_LIB
# define RESULTKIDAOUTPUT_EXPORT Q_DECL_EXPORT
#else
# define RESULTKIDAOUTPUT_EXPORT Q_DECL_IMPORT
#endif

#endif // RESULTKIDAOUTPUT_GLOBAL_H
