#ifndef SHOWPARTIALIMAGINGPANEL_GLOBAL_H
#define SHOWPARTIALIMAGINGPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SHOWPARTIALIMAGINGPANEL_LIB
# define SHOWPARTIALIMAGINGPANEL_EXPORT Q_DECL_EXPORT
#else
# define SHOWPARTIALIMAGINGPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // SHOWPARTIALIMAGINGPANEL_GLOBAL_H
