#ifndef OLSCCONTROLLPANEL_GLOBAL_H
#define OLSCCONTROLLPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef OLSCCONTROLLPANEL_LIB
# define OLSCCONTROLLPANEL_EXPORT Q_DECL_EXPORT
#else
# define OLSCCONTROLLPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONTOSHOWTOTALNGMAP_GLOBAL_H
