#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(BUTTONUPDATEALLBYHISTOGRAM_LIB)
#  define BUTTONUPDATEALLBYHISTOGRAM_EXPORT Q_DECL_EXPORT
# else
#  define BUTTONUPDATEALLBYHISTOGRAM_EXPORT Q_DECL_IMPORT
# endif
#else
# define BUTTONUPDATEALLBYHISTOGRAM_EXPORT
#endif
