# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./GeneralDisplayWholeImageResource.h \
    ./generaldisplaywholeimage_global.h \
    ../../Open/XDLLOnly.h \
    ../../Open/XDLLType.h \
    ./GeneralDisplayWholeImage.h
SOURCES += ./GeneralDisplayWholeImage.cpp \
    ../../Open/GUIDllCommon.cpp \
    ../../Open/SystemVersion.cpp \
    ./GeneralDisplayWholeImageResource.cpp \
    ./XGeneralDisplayWholeImageOptimized.cpp \
    ./XGeneralDisplayWholeImagePacket.cpp
RESOURCES += GeneralDisplayWholeImage.qrc
