#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(BUTTONSWITCHPHASESYNCHRONIZE_LIB)
#  define BUTTONSWITCHPHASESYNCHRONIZE_EXPORT Q_DECL_EXPORT
# else
#  define BUTTONSWITCHPHASESYNCHRONIZE_EXPORT Q_DECL_IMPORT
# endif
#else
# define BUTTONSWITCHPHASESYNCHRONIZE_EXPORT
#endif
