#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(SERVICEEXECUTIONEDITORWITHSEQUENCE_LIB)
#  define SERVICEEXECUTIONEDITORWITHSEQUENCE_EXPORT Q_DECL_EXPORT
# else
#  define SERVICEEXECUTIONEDITORWITHSEQUENCE_EXPORT Q_DECL_IMPORT
# endif
#else
# define SERVICEEXECUTIONEDITORWITHSEQUENCE_EXPORT
#endif
