#ifndef PROPERTYRESULTBINDER_GLOBAL_H
#define PROPERTYRESULTBINDER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PROPERTYRESULTBINDER_LIB
# define PROPERTYRESULTBINDER_EXPORT Q_DECL_EXPORT
#else
# define PROPERTYRESULTBINDER_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTYRESULTBINDER_GLOBAL_H
