#ifndef LIVECAMERADFK31AF03_GLOBAL_H
#define LIVECAMERADFK31AF03_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef LIVECAMERADFK31AF03_LIB
# define LIVECAMERADFK31AF03_EXPORT Q_DECL_EXPORT
#else
# define LIVECAMERADFK31AF03_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONTOSHOWTOTALNGMAP_GLOBAL_H
