#ifndef AUTOSAVEIMAGEBUTTONAUTO_GLOBAL_H
#define AUTOSAVEIMAGEBUTTONAUTO_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef AUTOSAVEIMAGEBUTTONAUTO_LIB
# define AUTOSAVEIMAGEBUTTONAUTO_EXPORT Q_DECL_EXPORT
#else
# define AUTOSAVEIMAGEBUTTONAUTO_EXPORT Q_DECL_IMPORT
#endif

#endif // AUTOSAVEIMAGEBUTTONAUTO_GLOBAL_H
