#ifndef FILTERSMOOTHLARGE_GLOBAL_H
#define FILTERSMOOTHLARGE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef FILTERSMOOTHLARGE_LIB
# define FILTERSMOOTHLARGE_EXPORT Q_DECL_EXPORT
#else
# define FILTERSMOOTHLARGE_EXPORT Q_DECL_IMPORT
#endif

#endif // FILTERSMOOTHLARGE_GLOBAL_H
