#ifndef BUTTONLOADPWAFILE_GLOBAL_H
#define BUTTONLOADPWAFILE_GLOBAL_H

#include <qglobal.h>

#ifdef BUTTONLOADPWAFILE_LIB
# define BUTTONLOADPWAFILE_EXPORT Q_DECL_EXPORT
#else
# define BUTTONLOADPWAFILE_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONLOADPWAFILE_GLOBAL_H
