#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(BUTTONGENERATEMASKFROMBACKGROUND_LIB)
#  define BUTTONGENERATEMASKFROMBACKGROUND_EXPORT Q_DECL_EXPORT
# else
#  define BUTTONGENERATEMASKFROMBACKGROUND_EXPORT Q_DECL_IMPORT
# endif
#else
# define BUTTONGENERATEMASKFROMBACKGROUND_EXPORT
#endif
