#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(BUTTONCREATETHRESHOLDLEVEL_LIB)
#  define BUTTONCREATETHRESHOLDLEVEL_EXPORT Q_DECL_EXPORT
# else
#  define BUTTONCREATETHRESHOLDLEVEL_EXPORT Q_DECL_IMPORT
# endif
#else
# define BUTTONCREATETHRESHOLDLEVEL_EXPORT
#endif
