#ifndef LIGHTDLL8PORT_GLOBAL_H
#define LIGHTDLL8PORT_GLOBAL_H

#include <qglobal.h>

#ifdef LIGHTDLL8PORT_LIB
# define LIGHTDLL8PORT_EXPORT Q_DECL_EXPORT
#else
# define LIGHTDLL8PORT_EXPORT Q_DECL_IMPORT
#endif

#endif // LIGHTDLL8PORT_GLOBAL_H
