#ifndef BUTTONLIGHTON_GLOBAL_H
#define BUTTONLIGHTON_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONLIGHTON_LIB
# define BUTTONLIGHTON_EXPORT Q_DECL_EXPORT
#else
# define BUTTONLIGHTON_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONLIGHTON_GLOBAL_H
