#ifndef CAMERAXTIUMMITSUBISHICIS_GLOBAL_H
#define CAMERAXTIUMMITSUBISHICIS_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef CAMERAXTIUMMITSUBISHICIS_LIB
# define CAMERAXTIUMMITSUBISHICIS_EXPORT Q_DECL_EXPORT
#else
# define CAMERAXTIUMMITSUBISHICIS_EXPORT Q_DECL_IMPORT
#endif

#endif // CAMERAXTIUMMITSUBISHICIS_GLOBAL_H
