#ifndef RESULTXMLSMALLLOT_GLOBAL_H
#define RESULTXMLSMALLLOT_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef RESULTXMLSMALLLOT_LIB
# define RESULTXMLSMALLLOT_EXPORT Q_DECL_EXPORT
#else
# define RESULTXMLSMALLLOT_EXPORT Q_DECL_IMPORT
#endif

#endif // RESULTXMLSMALLLOT_GLOBAL_H
