#ifndef IMAGECHECKERPANEL_GLOBAL_H
#define IMAGECHECKERPANEL_GLOBAL_H

#include <qglobal.h>

#ifdef IMAGECHECKERPANEL_LIB
# define IMAGECHECKERPANEL_EXPORT Q_DECL_EXPORT
#else
# define IMAGECHECKERPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // IMAGECHECKERPANEL_GLOBAL_H
