#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(TEMPLATERULEIMAGEPANEL_LIB)
#  define TEMPLATERULEIMAGEPANEL_EXPORT Q_DECL_EXPORT
# else
#  define TEMPLATERULEIMAGEPANEL_EXPORT Q_DECL_IMPORT
# endif
#else
# define TEMPLATERULEIMAGEPANEL_EXPORT
#endif
