#ifndef NICKINSPECTION_GLOBAL_H
#define NICKINSPECTION_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef NICKINSPECTION_LIB
# define NICKINSPECTION_EXPORT Q_DECL_EXPORT
#else
# define NICKINSPECTION_EXPORT Q_DECL_IMPORT
#endif

#endif // NICKINSPECTION_GLOBAL_H
