#ifndef BUTTONLOADHISTOGRAMDATA_GLOBAL_H
#define BUTTONLOADHISTOGRAMDATA_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONLOADHISTOGRAMDATA_LIB
# define BUTTONLOADHISTOGRAMDATA_EXPORT Q_DECL_EXPORT
#else
# define BUTTONLOADHISTOGRAMDATA_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONLOADHISTOGRAMDATA_GLOBAL_H
