# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./DynamicMaskingPIImagePanelResource.h \
    ./dynamicmaskingpiimagepanel_global.h \
    ../../Open/XDLLOnly.h \
    ../../Open/XDLLType.h \
    ../PropertyDynamicMaskingPI/XPropertyDynamicMaskingPIPacket.h \
    ./DynamicMaskingPIImagePanel.h
SOURCES += ./DynamicMaskingPIImagePanel.cpp \
    ../../Open/GUIDllCommon.cpp \
    ../../Open/SystemVersion.cpp \
    ../../Algorithm/DynamicMaskingPI/XDynamicMaskingPICommon.cpp \
    ../PropertyDynamicMaskingPI/XPropertyDynamicMaskingPIPacket.cpp \
    ./DynamicMaskingPIImagePanelResource.cpp
RESOURCES += DynamicMaskingPIImagePanel.qrc
