#ifndef SHOWMATRIXIMAGECENTER_GLOBAL_H
#define SHOWMATRIXIMAGECENTER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SHOWMATRIXIMAGECENTER_LIB
# define SHOWMATRIXIMAGECENTER_EXPORT Q_DECL_EXPORT
#else
# define SHOWMATRIXIMAGECENTER_EXPORT Q_DECL_IMPORT
#endif

#endif // SHOWMATRIXIMAGECENTER_GLOBAL_H
