#ifndef BUTTONSAVEALLOPINIONS_GLOBAL_H
#define BUTTONSAVEALLOPINIONS_GLOBAL_H

#include <qglobal.h>

#ifdef BUTTONSAVEALLOPINIONS_LIB
# define BUTTONSAVEALLOPINIONS_EXPORT Q_DECL_EXPORT
#else
# define BUTTONSAVEALLOPINIONS_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONSAVEALLOPINIONS_GLOBAL_H
