#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(CAMERAXTIUMFX8COLORMONOLINETRIGGER_LIB)
#  define CAMERAXTIUMFX8COLORMONOLINETRIGGER_EXPORT Q_DECL_EXPORT
# else
#  define CAMERAXTIUMFX8COLORMONOLINETRIGGER_EXPORT Q_DECL_IMPORT
# endif
#else
# define CAMERAXTIUMFX8COLORMONOLINETRIGGER_EXPORT
#endif
