#ifndef LINEENHANCER1L_GLOBAL_H
#define LINEENHANCER1L_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef LINEENHANCER1L_LIB
# define LINEENHANCER1L_EXPORT Q_DECL_EXPORT
#else
# define LINEENHANCER1L_EXPORT Q_DECL_IMPORT
#endif

#endif // LINEENHANCER1L_GLOBAL_H
