# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = MakeShrinkingTable
DESTDIR = ../../
CONFIG += debug
DEFINES += QT_LARGEFILE_SUPPORT
LIBS += -L"./../../Lib/Release" \
    -lComponent \
    -lServiceLib
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += .
RCC_DIR += .
include(MakeShrinkingTable.pri)
win32:RC_FILE = MakeShrinkingTable.rc
