#ifndef SHOWITEMNAMERESULTSEQ_GLOBAL_H
#define SHOWITEMNAMERESULTSEQ_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SHOWITEMNAMERESULTSEQ_LIB
# define SHOWITEMNAMERESULTSEQ_EXPORT Q_DECL_EXPORT
#else
# define SHOWITEMNAMERESULTSEQ_EXPORT Q_DECL_IMPORT
#endif

#endif // SHOWITEMNAMERESULTSEQ_GLOBAL_H
