#ifndef PROPERTYNICKINSPECTION_GLOBAL_H
#define PROPERTYNICKINSPECTION_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PROPERTYNICKINSPECTION_LIB
# define PROPERTYNICKINSPECTION_EXPORT Q_DECL_EXPORT
#else
# define PROPERTYNICKINSPECTION_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTYNICKINSPECTION_GLOBAL_H
