#ifndef SHOWTOTALNGNAMING_GLOBAL_H
#define SHOWTOTALNGNAMING_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SHOWTOTALNGNAMING_LIB
# define SHOWTOTALNGNAMING_EXPORT Q_DECL_EXPORT
#else
# define SHOWTOTALNGNAMING_EXPORT Q_DECL_IMPORT
#endif

#endif // SHOWTOTALNGNAMING_GLOBAL_H
