#ifndef EXECUTOROFPIXLIST_GLOBAL_H
#define EXECUTOROFPIXLIST_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef EXECUTOROFPIXLIST_LIB
# define EXECUTOROFPIXLIST_EXPORT Q_DECL_EXPORT
#else
# define EXECUTOROFPIXLIST_EXPORT Q_DECL_IMPORT
#endif

#endif // EXECUTOROFPIXLIST_GLOBAL_H
