#ifndef FILTERONELAYER_GLOBAL_H
#define FILTERONELAYER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef FILTERONELAYER_LIB
# define FILTERONELAYER_EXPORT Q_DECL_EXPORT
#else
# define FILTERONELAYER_EXPORT Q_DECL_IMPORT
#endif

#endif // FILTERONELAYER_GLOBAL_H
