#ifndef SELECTMACHINEFORREVIEW_GLOBAL_H
#define SELECTMACHINEFORREVIEW_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SELECTMACHINEFORREVIEW_LIB
# define SELECTMACHINEFORREVIEW_EXPORT Q_DECL_EXPORT
#else
# define SELECTMACHINEFORREVIEW_EXPORT Q_DECL_IMPORT
#endif

#endif // SELECTMACHINEFORREVIEW_GLOBAL_H
