#ifndef LOADOUTLINEOFFSETINMASTER_GLOBAL_H
#define LOADOUTLINEOFFSETINMASTER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef LOADOUTLINEOFFSETINMASTER_LIB
# define LOADOUTLINEOFFSETINMASTER_EXPORT Q_DECL_EXPORT
#else
# define LOADOUTLINEOFFSETINMASTER_EXPORT Q_DECL_IMPORT
#endif

#endif // LOADOUTLINEOFFSETINMASTER_GLOBAL_H
