# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = World3DImagePanel
DESTDIR = ../
CONFIG += debug
DEFINES += WORLD3DIMAGEPANEL_LIB
LIBS += -L"./../../Lib/Release" \
    -lComponent \
    -lDisplayImage \
    -lServiceLib
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += GeneratedFiles
RCC_DIR += GeneratedFiles
include(World3DImagePanel.pri)
