#ifndef EASYGENERATEALIGNMENT_GLOBAL_H
#define EASYGENERATEALIGNMENT_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef EASYGENERATEALIGNMENT_LIB
# define EASYGENERATEALIGNMENT_EXPORT Q_DECL_EXPORT
#else
# define EASYGENERATEALIGNMENT_EXPORT Q_DECL_IMPORT
#endif

#endif // EASYGENERATEALIGNMENT_GLOBAL_H
