# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = Delete
DESTDIR = ../../
CONFIG += release
LIBS += -L"." \
    -lopengl32 \
    -lglu32
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += .
RCC_DIR += ./GeneratedFiles
include(Delete.pri)
win32:RC_FILE = Delete.rc
