#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(INTEGRATIONNGCATEGORIZEDLIST_LIB)
#  define INTEGRATIONNGCATEGORIZEDLIST_EXPORT Q_DECL_EXPORT
# else
#  define INTEGRATIONNGCATEGORIZEDLIST_EXPORT Q_DECL_IMPORT
# endif
#else
# define INTEGRATIONNGCATEGORIZEDLIST_EXPORT
#endif
