#ifndef RESULTIMPORTANCE_GLOBAL_H
#define RESULTIMPORTANCE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef RESULTIMPORTANCE_LIB
# define RESULTIMPORTANCE_EXPORT Q_DECL_EXPORT
#else
# define RESULTIMPORTANCE_EXPORT Q_DECL_IMPORT
#endif

#endif // RESULTIMPORTANCE_GLOBAL_H
