#ifndef SELECTLOTFORREVIEW_GLOBAL_H
#define SELECTLOTFORREVIEW_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SELECTLOTFORREVIEW_LIB
# define SELECTLOTFORREVIEW_EXPORT Q_DECL_EXPORT
#else
# define SELECTLOTFORREVIEW_EXPORT Q_DECL_IMPORT
#endif

#endif // SELECTLOTFORREVIEW_GLOBAL_H
