#ifndef GENERALPANELFROMSEQ_GLOBAL_H
#define GENERALPANELFROMSEQ_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef GENERALPANELFROMSEQ_LIB
# define GENERALPANELFROMSEQ_EXPORT Q_DECL_EXPORT
#else
# define GENERALPANELFROMSEQ_EXPORT Q_DECL_IMPORT
#endif

#endif // GENERALPANELFROMSEQ_GLOBAL_H
