#ifndef LOADIMAGEINANYPAGE_GLOBAL_H
#define LOADIMAGEINANYPAGE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef LOADIMAGEINANYPAGE_LIB
# define LOADIMAGEINANYPAGE_EXPORT Q_DECL_EXPORT
#else
# define LOADIMAGEINANYPAGE_EXPORT Q_DECL_IMPORT
#endif

#endif // LOADIMAGEINANYPAGE_GLOBAL_H
