#ifndef BUTTONSELECTMULTIDELIVERY_GLOBAL_H
#define BUTTONSELECTMULTIDELIVERY_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONSELECTMULTIDELIVERY_LIB
# define BUTTONSELECTMULTIDELIVERY_EXPORT Q_DECL_EXPORT
#else
# define BUTTONSELECTMULTIDELIVERY_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONSELECTMULTIDELIVERY_GLOBAL_H
