#ifndef CHANGETURNTOP_GLOBAL_H
#define CHANGETURNTOP_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef CHANGETURNTOP_LIB
# define CHANGETURNTOP_EXPORT Q_DECL_EXPORT
#else
# define CHANGETURNTOP_EXPORT Q_DECL_IMPORT
#endif

#endif // CHANGETURNTOP_GLOBAL_H
