#ifndef BUTTONSWITCHDELAYEDVIEW_GLOBAL_H
#define BUTTONSWITCHDELAYEDVIEW_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONSWITCHDELAYEDVIEW_LIB
# define BUTTONSWITCHDELAYEDVIEW_EXPORT Q_DECL_EXPORT
#else
# define BUTTONSWITCHDELAYEDVIEW_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONSWITCHDELAYEDVIEW_GLOBAL_H
