#ifndef SHOWVRSOPERATION_GLOBAL_H
#define SHOWVRSOPERATION_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SHOWVRSOPERATION_LIB
# define SHOWVRSOPERATION_EXPORT Q_DECL_EXPORT
#else
# define SHOWVRSOPERATION_EXPORT Q_DECL_IMPORT
#endif

#endif // SHOWVRSOPERATION_GLOBAL_H
