#ifndef BUTTONTOSETFILTER_GLOBAL_H
#define BUTTONTOSETFILTER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONTOSETFILTER_LIB
# define BUTTONTOSETFILTER_EXPORT Q_DECL_EXPORT
#else
# define BUTTONTOSETFILTER_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONTOSETFILTER_GLOBAL_H
