#ifndef CONTECNC4DSEQ_GLOBAL_H
#define CONTECNC4DSEQ_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef CONTECNC4DSEQ_LIB
# define CONTECNC4DSEQ_EXPORT Q_DECL_EXPORT
#else
# define CONTECNC4DSEQ_EXPORT Q_DECL_IMPORT
#endif

#endif // CONTECNC4DSEQ_GLOBAL_H
