# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


TEMPLATE = subdirs
SUBDIRS += RegulusWorld/WorldServer/WorldServer.pro \
    RegulusWorld/EditRegulusWorld/EditRegulusWorld.pro \
    RegulusWorld/RobotRegulusWorld/RobotRegulusWorld.pro \
    RegulusWorld/RegulusWorldLibrary/RegulusWorldLibrary.pro \
    PluginDLL/Camera/CameraBaslerGigE/CameraBaslerGigE.pro \
    RegulusWorld/RWCamera/RWCamera.pro \
    RegulusWorld/GUI/RWView3D/RWView3D.pro \
    RegulusWorld/GUI/RWView5Panels/RWView5Panels.pro \
    RegulusWorld/GUI/RWShowObjectProperty/RWShowObjectProperty.pro \
    RegulusWorld/GUI/RWEditObjectImagePanel/RWEditObjectImagePanel.pro \
    RegulusWorld/GUI/RWEditObjectProperty/RWEditObjectProperty.pro \
    RegulusWorld/GUI/RWRobotRun/RWRobotRun.pro \
    RegulusWorld/GUI/RWButtonDeviceShowSetting/RWButtonDeviceShowSetting.pro \
    RegulusWorld/GUI/RWCamRecognitionImagePanel/RWCamRecognitionImagePanel.pro \
    RegulusWorld/GUI/RWPropertyCamRecognition/RWPropertyCamRecognition.pro \
    RegulusWorld/Algorithm/RWCamRecognition/RWCamRecognition.pro \
    RegulusWorld/Algorithm/RWAlgorithm3D/RWAlgorithm3D.pro \
    RegulusWorld/RWDevice/RWDevYRC1000/RWDevYRC1000.pro \
    RegulusWorld/RWDevice/RWDev3DMouse/RWDev3DMouse.pro \
    RegulusWorld/EditRWParameter/EditRWParameter.pro
