#ifndef EASYPROPERTYALIGNMENT_GLOBAL_H
#define EASYPROPERTYALIGNMENT_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef EASYPROPERTYALIGNMENT_LIB
# define EASYPROPERTYALIGNMENT_EXPORT Q_DECL_EXPORT
#else
# define EASYPROPERTYALIGNMENT_EXPORT Q_DECL_IMPORT
#endif

#endif // EASYPROPERTYALIGNMENT_GLOBAL_H
