#ifndef MEASUREHOLEPOSIMAGEPANEL_GLOBAL_H
#define MEASUREHOLEPOSIMAGEPANEL_GLOBAL_H

#include <qglobal.h>

#ifdef MEASUREHOLEPOSIMAGEPANEL_LIB
# define MEASUREHOLEPOSIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define MEASUREHOLEPOSIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // MEASUREHOLEPOSIMAGEPANEL_GLOBAL_H
