#ifndef BUTTONLOADMASTERDATAINPHASE_GLOBAL_H
#define BUTTONLOADMASTERDATAINPHASE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONLOADMASTERDATAINPHASE_LIB
# define BUTTONLOADMASTERDATAINPHASE_EXPORT Q_DECL_EXPORT
#else
# define BUTTONLOADMASTERDATAINPHASE_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONLOADMASTERDATAINPHASE_GLOBAL_H
