#ifndef BUTTONCALCALIGNMENT_GLOBAL_H
#define BUTTONCALCALIGNMENT_GLOBAL_H

#include <qglobal.h>

#ifdef BUTTONCALCALIGNMENT_LIB
# define BUTTONCALCALIGNMENT_EXPORT Q_DECL_EXPORT
#else
# define BUTTONCALCALIGNMENT_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONCALCALIGNMENT_GLOBAL_H
