#ifndef PROPERTYIMAGECHECKER_GLOBAL_H
#define PROPERTYIMAGECHECKER_GLOBAL_H

#include <qglobal.h>

#ifdef PROPERTYIMAGECHECKER_LIB
# define PROPERTYIMAGECHECKER_EXPORT Q_DECL_EXPORT
#else
# define PROPERTYIMAGECHECKER_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTYIMAGECHECKER_GLOBAL_H
