#ifndef BUTTONSHOWSTOCKEDIMAGE_GLOBAL_H
#define BUTTONSHOWSTOCKEDIMAGE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONSHOWSTOCKEDIMAGE_LIB
# define BUTTONSHOWSTOCKEDIMAGE_EXPORT Q_DECL_EXPORT
#else
# define BUTTONSHOWSTOCKEDIMAGE_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONSHOWSTOCKEDIMAGE_GLOBAL_H
