#ifndef CCSCONTROL2GUI_GLOBAL_H
#define CCSCONTROL2GUI_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef CCSCONTROL2GUI_LIB
# define CCSCONTROL2GUI_EXPORT Q_DECL_EXPORT
#else
# define CCSCONTROL2GUI_EXPORT Q_DECL_IMPORT
#endif

#endif // CCSCONTROL2GUI_GLOBAL_H
