#ifndef RESETCAMERASEQ_GLOBAL_H
#define RESETCAMERASEQ_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef RESETCAMERASEQ_LIB
# define RESETCAMERASEQ_EXPORT Q_DECL_EXPORT
#else
# define RESETCAMERASEQ_EXPORT Q_DECL_IMPORT
#endif

#endif // RESETCAMERASEQ_GLOBAL_H
