#ifndef SHOWCHECKBRIGHTNESSPANEL_GLOBAL_H
#define SHOWCHECKBRIGHTNESSPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SHOWCHECKBRIGHTNESSPANEL_LIB
# define SHOWCHECKBRIGHTNESSPANEL_EXPORT Q_DECL_EXPORT
#else
# define SHOWCHECKBRIGHTNESSPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // SHOWCHECKBRIGHTNESSPANEL_GLOBAL_H
