#ifndef EASYALIGNMENTIMAGEPANEL_GLOBAL_H
#define EASYALIGNMENTIMAGEPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef EASYALIGNMENTIMAGEPANEL_LIB
# define EASYALIGNMENTIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define EASYALIGNMENTIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // EASYALIGNMENTIMAGEPANEL_GLOBAL_H
