/********************************************************************************
** Form generated from reading UI file 'SettingDialog.ui'
**
** Created by: Qt User Interface Compiler version 6.10.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_SETTINGDIALOG_H
#define UI_SETTINGDIALOG_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDialog>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QProgressBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QToolButton>

QT_BEGIN_NAMESPACE

class Ui_SettingDialog
{
public:
    QFrame *frame;
    QLineEdit *lineEditText0;
    QSpinBox *spinBoxBrightness0;
    QLabel *label_2;
    QLineEdit *lineEditText1;
    QSpinBox *spinBoxBrightness1;
    QLabel *label_3;
    QLineEdit *lineEditText2;
    QSpinBox *spinBoxBrightness2;
    QLabel *label_4;
    QLineEdit *lineEditText3;
    QSpinBox *spinBoxBrightness3;
    QLabel *label_5;
    QLineEdit *lineEditText4;
    QSpinBox *spinBoxBrightness4;
    QLabel *label_6;
    QLineEdit *lineEditText5;
    QSpinBox *spinBoxBrightness5;
    QLabel *label_7;
    QLineEdit *lineEditText6;
    QSpinBox *spinBoxBrightness6;
    QLabel *label_8;
    QLineEdit *lineEditText7;
    QSpinBox *spinBoxBrightness7;
    QLabel *label_9;
    QFrame *frame_2;
    QLineEdit *lineEditText8;
    QSpinBox *spinBoxBrightness8;
    QLabel *label_10;
    QLineEdit *lineEditText9;
    QSpinBox *spinBoxBrightness9;
    QLabel *label_11;
    QLineEdit *lineEditText10;
    QSpinBox *spinBoxBrightness10;
    QLabel *label_12;
    QLineEdit *lineEditText11;
    QSpinBox *spinBoxBrightness11;
    QLabel *label_13;
    QLineEdit *lineEditText12;
    QSpinBox *spinBoxBrightness12;
    QLabel *label_14;
    QLineEdit *lineEditText13;
    QSpinBox *spinBoxBrightness13;
    QLabel *label_15;
    QLineEdit *lineEditText14;
    QSpinBox *spinBoxBrightness14;
    QLabel *label_16;
    QLineEdit *lineEditText15;
    QSpinBox *spinBoxBrightness15;
    QLabel *label_17;
    QFrame *frame_3;
    QLineEdit *lineEditText16;
    QSpinBox *spinBoxBrightness16;
    QLabel *label_18;
    QLineEdit *lineEditText17;
    QSpinBox *spinBoxBrightness17;
    QLabel *label_19;
    QLineEdit *lineEditText18;
    QSpinBox *spinBoxBrightness18;
    QLabel *label_20;
    QLineEdit *lineEditText19;
    QSpinBox *spinBoxBrightness19;
    QLabel *label_21;
    QLineEdit *lineEditText20;
    QSpinBox *spinBoxBrightness20;
    QLabel *label_22;
    QLineEdit *lineEditText21;
    QSpinBox *spinBoxBrightness21;
    QLabel *label_23;
    QLineEdit *lineEditText22;
    QSpinBox *spinBoxBrightness22;
    QLabel *label_24;
    QLineEdit *lineEditText23;
    QSpinBox *spinBoxBrightness23;
    QLabel *label_25;
    QFrame *frame_4;
    QLineEdit *lineEditText24;
    QSpinBox *spinBoxBrightness24;
    QLabel *label_26;
    QLineEdit *lineEditText25;
    QSpinBox *spinBoxBrightness25;
    QLabel *label_27;
    QLineEdit *lineEditText26;
    QSpinBox *spinBoxBrightness26;
    QLabel *label_28;
    QLineEdit *lineEditText27;
    QSpinBox *spinBoxBrightness27;
    QLabel *label_29;
    QLineEdit *lineEditText28;
    QSpinBox *spinBoxBrightness28;
    QLabel *label_30;
    QLineEdit *lineEditText29;
    QSpinBox *spinBoxBrightness29;
    QLabel *label_31;
    QLineEdit *lineEditText30;
    QSpinBox *spinBoxBrightness30;
    QLabel *label_32;
    QLineEdit *lineEditText31;
    QSpinBox *spinBoxBrightness31;
    QLabel *label_33;
    QComboBox *comboBoxBoard;
    QLabel *label_34;
    QComboBox *comboBoxPattern;
    QLabel *label_35;
    QLineEdit *lineEditBoard;
    QLineEdit *lineEditPattern;
    QFrame *frame_5;
    QToolButton *toolButtonSelectAllBoard;
    QToolButton *toolButtonSelectAll;
    QPushButton *pushButtonTransfer;
    QSlider *verticalSliderBrightnrss;
    QSpinBox *spinBoxBrightness;
    QProgressBar *progressBar;
    QToolButton *toolButtonLightON;
    QGroupBox *groupBox;
    QComboBox *comboBoxPatternBuffA;
    QLabel *label_36;
    QComboBox *comboBoxPatternBuffB;
    QLabel *label_37;
    QFrame *frame_6;
    QRadioButton *radioButtonOutputA;
    QRadioButton *radioButtonOutputB;
    QLabel *label_38;
    QPushButton *pushButtonOK;
    QPushButton *pushButtonCancel;
    QLineEdit *lineEditVersionStr;

    void setupUi(QDialog *SettingDialog)
    {
        if (SettingDialog->objectName().isEmpty())
            SettingDialog->setObjectName("SettingDialog");
        SettingDialog->resize(886, 684);
        frame = new QFrame(SettingDialog);
        frame->setObjectName("frame");
        frame->setGeometry(QRect(10, 90, 271, 251));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Raised);
        lineEditText0 = new QLineEdit(frame);
        lineEditText0->setObjectName("lineEditText0");
        lineEditText0->setGeometry(QRect(130, 10, 131, 20));
        spinBoxBrightness0 = new QSpinBox(frame);
        spinBoxBrightness0->setObjectName("spinBoxBrightness0");
        spinBoxBrightness0->setGeometry(QRect(50, 10, 71, 22));
        label_2 = new QLabel(frame);
        label_2->setObjectName("label_2");
        label_2->setGeometry(QRect(10, 10, 31, 21));
        label_2->setFrameShape(QFrame::Panel);
        label_2->setFrameShadow(QFrame::Sunken);
        label_2->setAlignment(Qt::AlignCenter);
        lineEditText1 = new QLineEdit(frame);
        lineEditText1->setObjectName("lineEditText1");
        lineEditText1->setGeometry(QRect(130, 40, 131, 20));
        spinBoxBrightness1 = new QSpinBox(frame);
        spinBoxBrightness1->setObjectName("spinBoxBrightness1");
        spinBoxBrightness1->setGeometry(QRect(50, 40, 71, 22));
        label_3 = new QLabel(frame);
        label_3->setObjectName("label_3");
        label_3->setGeometry(QRect(10, 40, 31, 21));
        label_3->setFrameShape(QFrame::Panel);
        label_3->setFrameShadow(QFrame::Sunken);
        label_3->setAlignment(Qt::AlignCenter);
        lineEditText2 = new QLineEdit(frame);
        lineEditText2->setObjectName("lineEditText2");
        lineEditText2->setGeometry(QRect(130, 70, 131, 20));
        spinBoxBrightness2 = new QSpinBox(frame);
        spinBoxBrightness2->setObjectName("spinBoxBrightness2");
        spinBoxBrightness2->setGeometry(QRect(50, 70, 71, 22));
        label_4 = new QLabel(frame);
        label_4->setObjectName("label_4");
        label_4->setGeometry(QRect(10, 70, 31, 21));
        label_4->setFrameShape(QFrame::Panel);
        label_4->setFrameShadow(QFrame::Sunken);
        label_4->setAlignment(Qt::AlignCenter);
        lineEditText3 = new QLineEdit(frame);
        lineEditText3->setObjectName("lineEditText3");
        lineEditText3->setGeometry(QRect(130, 100, 131, 20));
        spinBoxBrightness3 = new QSpinBox(frame);
        spinBoxBrightness3->setObjectName("spinBoxBrightness3");
        spinBoxBrightness3->setGeometry(QRect(50, 100, 71, 22));
        label_5 = new QLabel(frame);
        label_5->setObjectName("label_5");
        label_5->setGeometry(QRect(10, 100, 31, 21));
        label_5->setFrameShape(QFrame::Panel);
        label_5->setFrameShadow(QFrame::Sunken);
        label_5->setAlignment(Qt::AlignCenter);
        lineEditText4 = new QLineEdit(frame);
        lineEditText4->setObjectName("lineEditText4");
        lineEditText4->setGeometry(QRect(130, 130, 131, 20));
        spinBoxBrightness4 = new QSpinBox(frame);
        spinBoxBrightness4->setObjectName("spinBoxBrightness4");
        spinBoxBrightness4->setGeometry(QRect(50, 130, 71, 22));
        label_6 = new QLabel(frame);
        label_6->setObjectName("label_6");
        label_6->setGeometry(QRect(10, 130, 31, 21));
        label_6->setFrameShape(QFrame::Panel);
        label_6->setFrameShadow(QFrame::Sunken);
        label_6->setAlignment(Qt::AlignCenter);
        lineEditText5 = new QLineEdit(frame);
        lineEditText5->setObjectName("lineEditText5");
        lineEditText5->setGeometry(QRect(130, 160, 131, 20));
        spinBoxBrightness5 = new QSpinBox(frame);
        spinBoxBrightness5->setObjectName("spinBoxBrightness5");
        spinBoxBrightness5->setGeometry(QRect(50, 160, 71, 22));
        label_7 = new QLabel(frame);
        label_7->setObjectName("label_7");
        label_7->setGeometry(QRect(10, 160, 31, 21));
        label_7->setFrameShape(QFrame::Panel);
        label_7->setFrameShadow(QFrame::Sunken);
        label_7->setAlignment(Qt::AlignCenter);
        lineEditText6 = new QLineEdit(frame);
        lineEditText6->setObjectName("lineEditText6");
        lineEditText6->setGeometry(QRect(130, 190, 131, 20));
        spinBoxBrightness6 = new QSpinBox(frame);
        spinBoxBrightness6->setObjectName("spinBoxBrightness6");
        spinBoxBrightness6->setGeometry(QRect(50, 190, 71, 22));
        label_8 = new QLabel(frame);
        label_8->setObjectName("label_8");
        label_8->setGeometry(QRect(10, 190, 31, 21));
        label_8->setFrameShape(QFrame::Panel);
        label_8->setFrameShadow(QFrame::Sunken);
        label_8->setAlignment(Qt::AlignCenter);
        lineEditText7 = new QLineEdit(frame);
        lineEditText7->setObjectName("lineEditText7");
        lineEditText7->setGeometry(QRect(130, 220, 131, 20));
        spinBoxBrightness7 = new QSpinBox(frame);
        spinBoxBrightness7->setObjectName("spinBoxBrightness7");
        spinBoxBrightness7->setGeometry(QRect(50, 220, 71, 22));
        label_9 = new QLabel(frame);
        label_9->setObjectName("label_9");
        label_9->setGeometry(QRect(10, 220, 31, 21));
        label_9->setFrameShape(QFrame::Panel);
        label_9->setFrameShadow(QFrame::Sunken);
        label_9->setAlignment(Qt::AlignCenter);
        frame_2 = new QFrame(SettingDialog);
        frame_2->setObjectName("frame_2");
        frame_2->setGeometry(QRect(10, 350, 271, 251));
        frame_2->setFrameShape(QFrame::StyledPanel);
        frame_2->setFrameShadow(QFrame::Raised);
        lineEditText8 = new QLineEdit(frame_2);
        lineEditText8->setObjectName("lineEditText8");
        lineEditText8->setGeometry(QRect(130, 10, 131, 20));
        spinBoxBrightness8 = new QSpinBox(frame_2);
        spinBoxBrightness8->setObjectName("spinBoxBrightness8");
        spinBoxBrightness8->setGeometry(QRect(50, 10, 71, 22));
        label_10 = new QLabel(frame_2);
        label_10->setObjectName("label_10");
        label_10->setGeometry(QRect(10, 10, 31, 21));
        label_10->setFrameShape(QFrame::Panel);
        label_10->setFrameShadow(QFrame::Sunken);
        label_10->setAlignment(Qt::AlignCenter);
        lineEditText9 = new QLineEdit(frame_2);
        lineEditText9->setObjectName("lineEditText9");
        lineEditText9->setGeometry(QRect(130, 40, 131, 20));
        spinBoxBrightness9 = new QSpinBox(frame_2);
        spinBoxBrightness9->setObjectName("spinBoxBrightness9");
        spinBoxBrightness9->setGeometry(QRect(50, 40, 71, 22));
        label_11 = new QLabel(frame_2);
        label_11->setObjectName("label_11");
        label_11->setGeometry(QRect(10, 40, 31, 21));
        label_11->setFrameShape(QFrame::Panel);
        label_11->setFrameShadow(QFrame::Sunken);
        label_11->setAlignment(Qt::AlignCenter);
        lineEditText10 = new QLineEdit(frame_2);
        lineEditText10->setObjectName("lineEditText10");
        lineEditText10->setGeometry(QRect(130, 70, 131, 20));
        spinBoxBrightness10 = new QSpinBox(frame_2);
        spinBoxBrightness10->setObjectName("spinBoxBrightness10");
        spinBoxBrightness10->setGeometry(QRect(50, 70, 71, 22));
        label_12 = new QLabel(frame_2);
        label_12->setObjectName("label_12");
        label_12->setGeometry(QRect(10, 70, 31, 21));
        label_12->setFrameShape(QFrame::Panel);
        label_12->setFrameShadow(QFrame::Sunken);
        label_12->setAlignment(Qt::AlignCenter);
        lineEditText11 = new QLineEdit(frame_2);
        lineEditText11->setObjectName("lineEditText11");
        lineEditText11->setGeometry(QRect(130, 100, 131, 20));
        spinBoxBrightness11 = new QSpinBox(frame_2);
        spinBoxBrightness11->setObjectName("spinBoxBrightness11");
        spinBoxBrightness11->setGeometry(QRect(50, 100, 71, 22));
        label_13 = new QLabel(frame_2);
        label_13->setObjectName("label_13");
        label_13->setGeometry(QRect(10, 100, 31, 21));
        label_13->setFrameShape(QFrame::Panel);
        label_13->setFrameShadow(QFrame::Sunken);
        label_13->setAlignment(Qt::AlignCenter);
        lineEditText12 = new QLineEdit(frame_2);
        lineEditText12->setObjectName("lineEditText12");
        lineEditText12->setGeometry(QRect(130, 130, 131, 20));
        spinBoxBrightness12 = new QSpinBox(frame_2);
        spinBoxBrightness12->setObjectName("spinBoxBrightness12");
        spinBoxBrightness12->setGeometry(QRect(50, 130, 71, 22));
        label_14 = new QLabel(frame_2);
        label_14->setObjectName("label_14");
        label_14->setGeometry(QRect(10, 130, 31, 21));
        label_14->setFrameShape(QFrame::Panel);
        label_14->setFrameShadow(QFrame::Sunken);
        label_14->setAlignment(Qt::AlignCenter);
        lineEditText13 = new QLineEdit(frame_2);
        lineEditText13->setObjectName("lineEditText13");
        lineEditText13->setGeometry(QRect(130, 160, 131, 20));
        spinBoxBrightness13 = new QSpinBox(frame_2);
        spinBoxBrightness13->setObjectName("spinBoxBrightness13");
        spinBoxBrightness13->setGeometry(QRect(50, 160, 71, 22));
        label_15 = new QLabel(frame_2);
        label_15->setObjectName("label_15");
        label_15->setGeometry(QRect(10, 160, 31, 21));
        label_15->setFrameShape(QFrame::Panel);
        label_15->setFrameShadow(QFrame::Sunken);
        label_15->setAlignment(Qt::AlignCenter);
        lineEditText14 = new QLineEdit(frame_2);
        lineEditText14->setObjectName("lineEditText14");
        lineEditText14->setGeometry(QRect(130, 190, 131, 20));
        spinBoxBrightness14 = new QSpinBox(frame_2);
        spinBoxBrightness14->setObjectName("spinBoxBrightness14");
        spinBoxBrightness14->setGeometry(QRect(50, 190, 71, 22));
        label_16 = new QLabel(frame_2);
        label_16->setObjectName("label_16");
        label_16->setGeometry(QRect(10, 190, 31, 21));
        label_16->setFrameShape(QFrame::Panel);
        label_16->setFrameShadow(QFrame::Sunken);
        label_16->setAlignment(Qt::AlignCenter);
        lineEditText15 = new QLineEdit(frame_2);
        lineEditText15->setObjectName("lineEditText15");
        lineEditText15->setGeometry(QRect(130, 220, 131, 20));
        spinBoxBrightness15 = new QSpinBox(frame_2);
        spinBoxBrightness15->setObjectName("spinBoxBrightness15");
        spinBoxBrightness15->setGeometry(QRect(50, 220, 71, 22));
        label_17 = new QLabel(frame_2);
        label_17->setObjectName("label_17");
        label_17->setGeometry(QRect(10, 220, 31, 21));
        label_17->setFrameShape(QFrame::Panel);
        label_17->setFrameShadow(QFrame::Sunken);
        label_17->setAlignment(Qt::AlignCenter);
        frame_3 = new QFrame(SettingDialog);
        frame_3->setObjectName("frame_3");
        frame_3->setGeometry(QRect(300, 90, 271, 251));
        frame_3->setFrameShape(QFrame::StyledPanel);
        frame_3->setFrameShadow(QFrame::Raised);
        lineEditText16 = new QLineEdit(frame_3);
        lineEditText16->setObjectName("lineEditText16");
        lineEditText16->setGeometry(QRect(130, 10, 131, 20));
        spinBoxBrightness16 = new QSpinBox(frame_3);
        spinBoxBrightness16->setObjectName("spinBoxBrightness16");
        spinBoxBrightness16->setGeometry(QRect(50, 10, 71, 22));
        label_18 = new QLabel(frame_3);
        label_18->setObjectName("label_18");
        label_18->setGeometry(QRect(10, 10, 31, 21));
        label_18->setFrameShape(QFrame::Panel);
        label_18->setFrameShadow(QFrame::Sunken);
        label_18->setAlignment(Qt::AlignCenter);
        lineEditText17 = new QLineEdit(frame_3);
        lineEditText17->setObjectName("lineEditText17");
        lineEditText17->setGeometry(QRect(130, 40, 131, 20));
        spinBoxBrightness17 = new QSpinBox(frame_3);
        spinBoxBrightness17->setObjectName("spinBoxBrightness17");
        spinBoxBrightness17->setGeometry(QRect(50, 40, 71, 22));
        label_19 = new QLabel(frame_3);
        label_19->setObjectName("label_19");
        label_19->setGeometry(QRect(10, 40, 31, 21));
        label_19->setFrameShape(QFrame::Panel);
        label_19->setFrameShadow(QFrame::Sunken);
        label_19->setAlignment(Qt::AlignCenter);
        lineEditText18 = new QLineEdit(frame_3);
        lineEditText18->setObjectName("lineEditText18");
        lineEditText18->setGeometry(QRect(130, 70, 131, 20));
        spinBoxBrightness18 = new QSpinBox(frame_3);
        spinBoxBrightness18->setObjectName("spinBoxBrightness18");
        spinBoxBrightness18->setGeometry(QRect(50, 70, 71, 22));
        label_20 = new QLabel(frame_3);
        label_20->setObjectName("label_20");
        label_20->setGeometry(QRect(10, 70, 31, 21));
        label_20->setFrameShape(QFrame::Panel);
        label_20->setFrameShadow(QFrame::Sunken);
        label_20->setAlignment(Qt::AlignCenter);
        lineEditText19 = new QLineEdit(frame_3);
        lineEditText19->setObjectName("lineEditText19");
        lineEditText19->setGeometry(QRect(130, 100, 131, 20));
        spinBoxBrightness19 = new QSpinBox(frame_3);
        spinBoxBrightness19->setObjectName("spinBoxBrightness19");
        spinBoxBrightness19->setGeometry(QRect(50, 100, 71, 22));
        label_21 = new QLabel(frame_3);
        label_21->setObjectName("label_21");
        label_21->setGeometry(QRect(10, 100, 31, 21));
        label_21->setFrameShape(QFrame::Panel);
        label_21->setFrameShadow(QFrame::Sunken);
        label_21->setAlignment(Qt::AlignCenter);
        lineEditText20 = new QLineEdit(frame_3);
        lineEditText20->setObjectName("lineEditText20");
        lineEditText20->setGeometry(QRect(130, 130, 131, 20));
        spinBoxBrightness20 = new QSpinBox(frame_3);
        spinBoxBrightness20->setObjectName("spinBoxBrightness20");
        spinBoxBrightness20->setGeometry(QRect(50, 130, 71, 22));
        label_22 = new QLabel(frame_3);
        label_22->setObjectName("label_22");
        label_22->setGeometry(QRect(10, 130, 31, 21));
        label_22->setFrameShape(QFrame::Panel);
        label_22->setFrameShadow(QFrame::Sunken);
        label_22->setAlignment(Qt::AlignCenter);
        lineEditText21 = new QLineEdit(frame_3);
        lineEditText21->setObjectName("lineEditText21");
        lineEditText21->setGeometry(QRect(130, 160, 131, 20));
        spinBoxBrightness21 = new QSpinBox(frame_3);
        spinBoxBrightness21->setObjectName("spinBoxBrightness21");
        spinBoxBrightness21->setGeometry(QRect(50, 160, 71, 22));
        label_23 = new QLabel(frame_3);
        label_23->setObjectName("label_23");
        label_23->setGeometry(QRect(10, 160, 31, 21));
        label_23->setFrameShape(QFrame::Panel);
        label_23->setFrameShadow(QFrame::Sunken);
        label_23->setAlignment(Qt::AlignCenter);
        lineEditText22 = new QLineEdit(frame_3);
        lineEditText22->setObjectName("lineEditText22");
        lineEditText22->setGeometry(QRect(130, 190, 131, 20));
        spinBoxBrightness22 = new QSpinBox(frame_3);
        spinBoxBrightness22->setObjectName("spinBoxBrightness22");
        spinBoxBrightness22->setGeometry(QRect(50, 190, 71, 22));
        label_24 = new QLabel(frame_3);
        label_24->setObjectName("label_24");
        label_24->setGeometry(QRect(10, 190, 31, 21));
        label_24->setFrameShape(QFrame::Panel);
        label_24->setFrameShadow(QFrame::Sunken);
        label_24->setAlignment(Qt::AlignCenter);
        lineEditText23 = new QLineEdit(frame_3);
        lineEditText23->setObjectName("lineEditText23");
        lineEditText23->setGeometry(QRect(130, 220, 131, 20));
        spinBoxBrightness23 = new QSpinBox(frame_3);
        spinBoxBrightness23->setObjectName("spinBoxBrightness23");
        spinBoxBrightness23->setGeometry(QRect(50, 220, 71, 22));
        label_25 = new QLabel(frame_3);
        label_25->setObjectName("label_25");
        label_25->setGeometry(QRect(10, 220, 31, 21));
        label_25->setFrameShape(QFrame::Panel);
        label_25->setFrameShadow(QFrame::Sunken);
        label_25->setAlignment(Qt::AlignCenter);
        frame_4 = new QFrame(SettingDialog);
        frame_4->setObjectName("frame_4");
        frame_4->setGeometry(QRect(300, 350, 271, 251));
        frame_4->setFrameShape(QFrame::StyledPanel);
        frame_4->setFrameShadow(QFrame::Raised);
        lineEditText24 = new QLineEdit(frame_4);
        lineEditText24->setObjectName("lineEditText24");
        lineEditText24->setGeometry(QRect(130, 10, 131, 20));
        spinBoxBrightness24 = new QSpinBox(frame_4);
        spinBoxBrightness24->setObjectName("spinBoxBrightness24");
        spinBoxBrightness24->setGeometry(QRect(50, 10, 71, 22));
        label_26 = new QLabel(frame_4);
        label_26->setObjectName("label_26");
        label_26->setGeometry(QRect(10, 10, 31, 21));
        label_26->setFrameShape(QFrame::Panel);
        label_26->setFrameShadow(QFrame::Sunken);
        label_26->setAlignment(Qt::AlignCenter);
        lineEditText25 = new QLineEdit(frame_4);
        lineEditText25->setObjectName("lineEditText25");
        lineEditText25->setGeometry(QRect(130, 40, 131, 20));
        spinBoxBrightness25 = new QSpinBox(frame_4);
        spinBoxBrightness25->setObjectName("spinBoxBrightness25");
        spinBoxBrightness25->setGeometry(QRect(50, 40, 71, 22));
        label_27 = new QLabel(frame_4);
        label_27->setObjectName("label_27");
        label_27->setGeometry(QRect(10, 40, 31, 21));
        label_27->setFrameShape(QFrame::Panel);
        label_27->setFrameShadow(QFrame::Sunken);
        label_27->setAlignment(Qt::AlignCenter);
        lineEditText26 = new QLineEdit(frame_4);
        lineEditText26->setObjectName("lineEditText26");
        lineEditText26->setGeometry(QRect(130, 70, 131, 20));
        spinBoxBrightness26 = new QSpinBox(frame_4);
        spinBoxBrightness26->setObjectName("spinBoxBrightness26");
        spinBoxBrightness26->setGeometry(QRect(50, 70, 71, 22));
        label_28 = new QLabel(frame_4);
        label_28->setObjectName("label_28");
        label_28->setGeometry(QRect(10, 70, 31, 21));
        label_28->setFrameShape(QFrame::Panel);
        label_28->setFrameShadow(QFrame::Sunken);
        label_28->setAlignment(Qt::AlignCenter);
        lineEditText27 = new QLineEdit(frame_4);
        lineEditText27->setObjectName("lineEditText27");
        lineEditText27->setGeometry(QRect(130, 100, 131, 20));
        spinBoxBrightness27 = new QSpinBox(frame_4);
        spinBoxBrightness27->setObjectName("spinBoxBrightness27");
        spinBoxBrightness27->setGeometry(QRect(50, 100, 71, 22));
        label_29 = new QLabel(frame_4);
        label_29->setObjectName("label_29");
        label_29->setGeometry(QRect(10, 100, 31, 21));
        label_29->setFrameShape(QFrame::Panel);
        label_29->setFrameShadow(QFrame::Sunken);
        label_29->setAlignment(Qt::AlignCenter);
        lineEditText28 = new QLineEdit(frame_4);
        lineEditText28->setObjectName("lineEditText28");
        lineEditText28->setGeometry(QRect(130, 130, 131, 20));
        spinBoxBrightness28 = new QSpinBox(frame_4);
        spinBoxBrightness28->setObjectName("spinBoxBrightness28");
        spinBoxBrightness28->setGeometry(QRect(50, 130, 71, 22));
        label_30 = new QLabel(frame_4);
        label_30->setObjectName("label_30");
        label_30->setGeometry(QRect(10, 130, 31, 21));
        label_30->setFrameShape(QFrame::Panel);
        label_30->setFrameShadow(QFrame::Sunken);
        label_30->setAlignment(Qt::AlignCenter);
        lineEditText29 = new QLineEdit(frame_4);
        lineEditText29->setObjectName("lineEditText29");
        lineEditText29->setGeometry(QRect(130, 160, 131, 20));
        spinBoxBrightness29 = new QSpinBox(frame_4);
        spinBoxBrightness29->setObjectName("spinBoxBrightness29");
        spinBoxBrightness29->setGeometry(QRect(50, 160, 71, 22));
        label_31 = new QLabel(frame_4);
        label_31->setObjectName("label_31");
        label_31->setGeometry(QRect(10, 160, 31, 21));
        label_31->setFrameShape(QFrame::Panel);
        label_31->setFrameShadow(QFrame::Sunken);
        label_31->setAlignment(Qt::AlignCenter);
        lineEditText30 = new QLineEdit(frame_4);
        lineEditText30->setObjectName("lineEditText30");
        lineEditText30->setGeometry(QRect(130, 190, 131, 20));
        spinBoxBrightness30 = new QSpinBox(frame_4);
        spinBoxBrightness30->setObjectName("spinBoxBrightness30");
        spinBoxBrightness30->setGeometry(QRect(50, 190, 71, 22));
        label_32 = new QLabel(frame_4);
        label_32->setObjectName("label_32");
        label_32->setGeometry(QRect(10, 190, 31, 21));
        label_32->setFrameShape(QFrame::Panel);
        label_32->setFrameShadow(QFrame::Sunken);
        label_32->setAlignment(Qt::AlignCenter);
        lineEditText31 = new QLineEdit(frame_4);
        lineEditText31->setObjectName("lineEditText31");
        lineEditText31->setGeometry(QRect(130, 220, 131, 20));
        spinBoxBrightness31 = new QSpinBox(frame_4);
        spinBoxBrightness31->setObjectName("spinBoxBrightness31");
        spinBoxBrightness31->setGeometry(QRect(50, 220, 71, 22));
        label_33 = new QLabel(frame_4);
        label_33->setObjectName("label_33");
        label_33->setGeometry(QRect(10, 220, 31, 21));
        label_33->setFrameShape(QFrame::Panel);
        label_33->setFrameShadow(QFrame::Sunken);
        label_33->setAlignment(Qt::AlignCenter);
        comboBoxBoard = new QComboBox(SettingDialog);
        comboBoxBoard->setObjectName("comboBoxBoard");
        comboBoxBoard->setGeometry(QRect(100, 40, 81, 22));
        label_34 = new QLabel(SettingDialog);
        label_34->setObjectName("label_34");
        label_34->setGeometry(QRect(10, 40, 81, 21));
        label_34->setFrameShape(QFrame::Panel);
        label_34->setFrameShadow(QFrame::Sunken);
        label_34->setAlignment(Qt::AlignCenter);
        comboBoxPattern = new QComboBox(SettingDialog);
        comboBoxPattern->setObjectName("comboBoxPattern");
        comboBoxPattern->setGeometry(QRect(100, 10, 81, 22));
        label_35 = new QLabel(SettingDialog);
        label_35->setObjectName("label_35");
        label_35->setGeometry(QRect(10, 10, 81, 21));
        label_35->setFrameShape(QFrame::Panel);
        label_35->setFrameShadow(QFrame::Sunken);
        label_35->setAlignment(Qt::AlignCenter);
        lineEditBoard = new QLineEdit(SettingDialog);
        lineEditBoard->setObjectName("lineEditBoard");
        lineEditBoard->setGeometry(QRect(190, 40, 381, 20));
        lineEditPattern = new QLineEdit(SettingDialog);
        lineEditPattern->setObjectName("lineEditPattern");
        lineEditPattern->setGeometry(QRect(190, 10, 381, 20));
        frame_5 = new QFrame(SettingDialog);
        frame_5->setObjectName("frame_5");
        frame_5->setGeometry(QRect(590, 90, 281, 511));
        frame_5->setFrameShape(QFrame::StyledPanel);
        frame_5->setFrameShadow(QFrame::Raised);
        toolButtonSelectAllBoard = new QToolButton(frame_5);
        toolButtonSelectAllBoard->setObjectName("toolButtonSelectAllBoard");
        toolButtonSelectAllBoard->setGeometry(QRect(130, 130, 121, 41));
        toolButtonSelectAllBoard->setCheckable(true);
        toolButtonSelectAll = new QToolButton(frame_5);
        toolButtonSelectAll->setObjectName("toolButtonSelectAll");
        toolButtonSelectAll->setGeometry(QRect(130, 180, 121, 41));
        toolButtonSelectAll->setCheckable(true);
        pushButtonTransfer = new QPushButton(frame_5);
        pushButtonTransfer->setObjectName("pushButtonTransfer");
        pushButtonTransfer->setGeometry(QRect(130, 230, 121, 41));
        verticalSliderBrightnrss = new QSlider(frame_5);
        verticalSliderBrightnrss->setObjectName("verticalSliderBrightnrss");
        verticalSliderBrightnrss->setGeometry(QRect(40, 10, 21, 256));
        verticalSliderBrightnrss->setOrientation(Qt::Vertical);
        spinBoxBrightness = new QSpinBox(frame_5);
        spinBoxBrightness->setObjectName("spinBoxBrightness");
        spinBoxBrightness->setGeometry(QRect(20, 280, 71, 22));
        progressBar = new QProgressBar(frame_5);
        progressBar->setObjectName("progressBar");
        progressBar->setGeometry(QRect(130, 280, 131, 23));
        progressBar->setValue(24);
        toolButtonLightON = new QToolButton(frame_5);
        toolButtonLightON->setObjectName("toolButtonLightON");
        toolButtonLightON->setGeometry(QRect(30, 450, 211, 41));
        toolButtonLightON->setCheckable(true);
        groupBox = new QGroupBox(frame_5);
        groupBox->setObjectName("groupBox");
        groupBox->setGeometry(QRect(10, 320, 261, 121));
        comboBoxPatternBuffA = new QComboBox(groupBox);
        comboBoxPatternBuffA->setObjectName("comboBoxPatternBuffA");
        comboBoxPatternBuffA->setGeometry(QRect(100, 50, 81, 22));
        label_36 = new QLabel(groupBox);
        label_36->setObjectName("label_36");
        label_36->setGeometry(QRect(10, 50, 81, 21));
        label_36->setFrameShape(QFrame::Panel);
        label_36->setFrameShadow(QFrame::Sunken);
        label_36->setAlignment(Qt::AlignCenter);
        comboBoxPatternBuffB = new QComboBox(groupBox);
        comboBoxPatternBuffB->setObjectName("comboBoxPatternBuffB");
        comboBoxPatternBuffB->setGeometry(QRect(100, 80, 81, 22));
        label_37 = new QLabel(groupBox);
        label_37->setObjectName("label_37");
        label_37->setGeometry(QRect(10, 80, 81, 21));
        label_37->setFrameShape(QFrame::Panel);
        label_37->setFrameShadow(QFrame::Sunken);
        label_37->setAlignment(Qt::AlignCenter);
        frame_6 = new QFrame(groupBox);
        frame_6->setObjectName("frame_6");
        frame_6->setGeometry(QRect(190, 40, 61, 71));
        frame_6->setFrameShape(QFrame::NoFrame);
        frame_6->setFrameShadow(QFrame::Raised);
        radioButtonOutputA = new QRadioButton(frame_6);
        radioButtonOutputA->setObjectName("radioButtonOutputA");
        radioButtonOutputA->setGeometry(QRect(10, 10, 41, 17));
        radioButtonOutputA->setChecked(true);
        radioButtonOutputB = new QRadioButton(frame_6);
        radioButtonOutputB->setObjectName("radioButtonOutputB");
        radioButtonOutputB->setGeometry(QRect(10, 40, 41, 17));
        label_38 = new QLabel(groupBox);
        label_38->setObjectName("label_38");
        label_38->setGeometry(QRect(180, 20, 71, 21));
        label_38->setFrameShape(QFrame::Panel);
        label_38->setFrameShadow(QFrame::Sunken);
        label_38->setAlignment(Qt::AlignCenter);
        pushButtonOK = new QPushButton(SettingDialog);
        pushButtonOK->setObjectName("pushButtonOK");
        pushButtonOK->setGeometry(QRect(230, 620, 131, 41));
        pushButtonCancel = new QPushButton(SettingDialog);
        pushButtonCancel->setObjectName("pushButtonCancel");
        pushButtonCancel->setGeometry(QRect(380, 620, 131, 41));
        lineEditVersionStr = new QLineEdit(SettingDialog);
        lineEditVersionStr->setObjectName("lineEditVersionStr");
        lineEditVersionStr->setGeometry(QRect(540, 660, 221, 20));

        retranslateUi(SettingDialog);

        pushButtonOK->setDefault(true);


        QMetaObject::connectSlotsByName(SettingDialog);
    } // setupUi

    void retranslateUi(QDialog *SettingDialog)
    {
        SettingDialog->setWindowTitle(QCoreApplication::translate("SettingDialog", "Dialog", nullptr));
        label_2->setText(QCoreApplication::translate("SettingDialog", "1", nullptr));
        label_3->setText(QCoreApplication::translate("SettingDialog", "2", nullptr));
        label_4->setText(QCoreApplication::translate("SettingDialog", "3", nullptr));
        label_5->setText(QCoreApplication::translate("SettingDialog", "4", nullptr));
        label_6->setText(QCoreApplication::translate("SettingDialog", "5", nullptr));
        label_7->setText(QCoreApplication::translate("SettingDialog", "6", nullptr));
        label_8->setText(QCoreApplication::translate("SettingDialog", "7", nullptr));
        label_9->setText(QCoreApplication::translate("SettingDialog", "8", nullptr));
        label_10->setText(QCoreApplication::translate("SettingDialog", "9", nullptr));
        label_11->setText(QCoreApplication::translate("SettingDialog", "10", nullptr));
        label_12->setText(QCoreApplication::translate("SettingDialog", "11", nullptr));
        label_13->setText(QCoreApplication::translate("SettingDialog", "12", nullptr));
        label_14->setText(QCoreApplication::translate("SettingDialog", "13", nullptr));
        label_15->setText(QCoreApplication::translate("SettingDialog", "14", nullptr));
        label_16->setText(QCoreApplication::translate("SettingDialog", "15", nullptr));
        label_17->setText(QCoreApplication::translate("SettingDialog", "16", nullptr));
        label_18->setText(QCoreApplication::translate("SettingDialog", "17", nullptr));
        label_19->setText(QCoreApplication::translate("SettingDialog", "18", nullptr));
        label_20->setText(QCoreApplication::translate("SettingDialog", "19", nullptr));
        label_21->setText(QCoreApplication::translate("SettingDialog", "20", nullptr));
        label_22->setText(QCoreApplication::translate("SettingDialog", "21", nullptr));
        label_23->setText(QCoreApplication::translate("SettingDialog", "22", nullptr));
        label_24->setText(QCoreApplication::translate("SettingDialog", "23", nullptr));
        label_25->setText(QCoreApplication::translate("SettingDialog", "24", nullptr));
        label_26->setText(QCoreApplication::translate("SettingDialog", "25", nullptr));
        label_27->setText(QCoreApplication::translate("SettingDialog", "26", nullptr));
        label_28->setText(QCoreApplication::translate("SettingDialog", "27", nullptr));
        label_29->setText(QCoreApplication::translate("SettingDialog", "28", nullptr));
        label_30->setText(QCoreApplication::translate("SettingDialog", "29", nullptr));
        label_31->setText(QCoreApplication::translate("SettingDialog", "30", nullptr));
        label_32->setText(QCoreApplication::translate("SettingDialog", "31", nullptr));
        label_33->setText(QCoreApplication::translate("SettingDialog", "32", nullptr));
        label_34->setText(QCoreApplication::translate("SettingDialog", "Board", nullptr));
        label_35->setText(QCoreApplication::translate("SettingDialog", "Pattern", nullptr));
        toolButtonSelectAllBoard->setText(QCoreApplication::translate("SettingDialog", "All board", nullptr));
        toolButtonSelectAll->setText(QCoreApplication::translate("SettingDialog", "Select all in current", nullptr));
        pushButtonTransfer->setText(QCoreApplication::translate("SettingDialog", "Transfer", nullptr));
        toolButtonLightON->setText(QCoreApplication::translate("SettingDialog", "ON", nullptr));
        groupBox->setTitle(QString());
        label_36->setText(QCoreApplication::translate("SettingDialog", "Buffer1", nullptr));
        label_37->setText(QCoreApplication::translate("SettingDialog", "Buffer2", nullptr));
        radioButtonOutputA->setText(QString());
        radioButtonOutputB->setText(QString());
        label_38->setText(QCoreApplication::translate("SettingDialog", "Output", nullptr));
        pushButtonOK->setText(QCoreApplication::translate("SettingDialog", "OK", nullptr));
        pushButtonCancel->setText(QCoreApplication::translate("SettingDialog", "Cancel", nullptr));
    } // retranslateUi

};

namespace Ui {
    class SettingDialog: public Ui_SettingDialog {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_SETTINGDIALOG_H
