#ifndef BUTTONGENERATEFROMGERBER_GLOBAL_H
#define BUTTONGENERATEFROMGERBER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONGENERATEFROMGERBER_LIB
# define BUTTONGENERATEFROMGERBER_EXPORT Q_DECL_EXPORT
#else
# define BUTTONGENERATEFROMGERBER_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONGENERATEFROMGERBER_GLOBAL_H
