#ifndef FILTERSHRINKIMAGE_GLOBAL_H
#define FILTERSHRINKIMAGE_GLOBAL_H

#include <qglobal.h>

#ifdef FILTERSHRINKIMAGE_LIB
# define FILTERSHRINKIMAGE_EXPORT Q_DECL_EXPORT
#else
# define FILTERSHRINKIMAGE_EXPORT Q_DECL_IMPORT
#endif

#endif // FILTERSHRINKIMAGE_GLOBAL_H
