#ifndef CHECKCYCLETIME_GLOBAL_H
#define CHECKCYCLETIME_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef CHECKCYCLETIME_LIB
# define CHECKCYCLETIME_EXPORT Q_DECL_EXPORT
#else
# define CHECKCYCLETIME_EXPORT Q_DECL_IMPORT
#endif

#endif // CHECKCYCLETIME_GLOBAL_H
