#ifndef PANELRUNNINGVRS_GLOBAL_H
#define PANELRUNNINGVRS_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PANELRUNNINGVRS_LIB
# define PANELRUNNINGVRS_EXPORT Q_DECL_EXPORT
#else
# define PANELRUNNINGVRS_EXPORT Q_DECL_IMPORT
#endif

#endif // PANELRUNNINGVRS_GLOBAL_H
