#ifndef BUTTONLOADOUTLINEOFFSET_GLOBAL_H
#define BUTTONLOADOUTLINEOFFSET_GLOBAL_H

#include <qglobal.h>

#ifdef BUTTONLOADOUTLINEOFFSET_LIB
# define BUTTONLOADOUTLINEOFFSET_EXPORT Q_DECL_EXPORT
#else
# define BUTTONLOADOUTLINEOFFSET_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONLOADOUTLINEOFFSET_GLOBAL_H
