#ifndef SAVETARGETINNG_GLOBAL_H
#define SAVETARGETINNG_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SAVETARGETINNG_LIB
# define SAVETARGETINNG_EXPORT Q_DECL_EXPORT
#else
# define SAVETARGETINNG_EXPORT Q_DECL_IMPORT
#endif

#endif // SAVETARGETINNG_GLOBAL_H
