#ifndef BCRIMAGEPANEL_GLOBAL_H
#define BCRIMAGEPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BCRIMAGEPANEL_LIB
# define BCRIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define BCRIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // BCRIMAGEPANEL_GLOBAL_H
