#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(FILTERMATCHCOLORBANDDYNAMICALLY_LIB)
#  define FILTERMATCHCOLORBANDDYNAMICALLY_EXPORT Q_DECL_EXPORT
# else
#  define FILTERMATCHCOLORBANDDYNAMICALLY_EXPORT Q_DECL_IMPORT
# endif
#else
# define FILTERMATCHCOLORBANDDYNAMICALLY_EXPORT
#endif
