#ifndef PROPERTYDXFOPERATION_GLOBAL_H
#define PROPERTYDXFOPERATION_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PROPERTYDXFOPERATION_LIB
# define PROPERTYDXFOPERATION_EXPORT Q_DECL_EXPORT
#else
# define PROPERTYDXFOPERATION_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTYDXFOPERATION_GLOBAL_H
