#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(PROPERTYRASTERINSPECTION_LIB)
#  define PROPERTYRASTERINSPECTION_EXPORT Q_DECL_EXPORT
# else
#  define PROPERTYRASTERINSPECTION_EXPORT Q_DECL_IMPORT
# endif
#else
# define PROPERTYRASTERINSPECTION_EXPORT
#endif
