#ifndef DOTMATCHINGIMAGEPANEL_GLOBAL_H
#define DOTMATCHINGIMAGEPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef DOTMATCHINGIMAGEPANEL_LIB
# define DOTMATCHINGIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define DOTMATCHINGIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // DOTMATCHINGIMAGEPANEL_GLOBAL_H
