#ifndef INTEGRATIONSHOWMEMORY_GLOBAL_H
#define INTEGRATIONSHOWMEMORY_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef INTEGRATIONSHOWMEMORY_LIB
# define INTEGRATIONSHOWMEMORY_EXPORT Q_DECL_EXPORT
#else
# define INTEGRATIONSHOWMEMORY_EXPORT Q_DECL_IMPORT
#endif

#endif // INTEGRATIONSHOWMEMORY_GLOBAL_H
