#ifndef SAVEPARTIALIMAGEPANEL_GLOBAL_H
#define SAVEPARTIALIMAGEPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SAVEPARTIALIMAGEPANEL_LIB
# define SAVEPARTIALIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define SAVEPARTIALIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // SAVEPARTIALIMAGEPANEL_GLOBAL_H
