#ifndef LISTRESULTFRAME_GLOBAL_H
#define LISTRESULTFRAME_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef LISTRESULTFRAME_LIB
# define LISTRESULTFRAME_EXPORT Q_DECL_EXPORT
#else
# define LISTRESULTFRAME_EXPORT Q_DECL_IMPORT
#endif

#endif // LISTRESULTFRAME_GLOBAL_H
