#ifndef PROPERTYCOLORDIFFERENCE_GLOBAL_H
#define PROPERTYCOLORDIFFERENCE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PROPERTYCOLORDIFFERENCE_LIB
# define PROPERTYCOLORDIFFERENCE_EXPORT Q_DECL_EXPORT
#else
# define PROPERTYCOLORDIFFERENCE_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTYCOLORDIFFERENCE_GLOBAL_H
