#ifndef SETMECHANICALOFFSET_GLOBAL_H
#define SETMECHANICALOFFSET_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SETMECHANICALOFFSET_LIB
# define SETMECHANICALOFFSET_EXPORT Q_DECL_EXPORT
#else
# define SETMECHANICALOFFSET_EXPORT Q_DECL_IMPORT
#endif

#endif // SETMECHANICALOFFSET_GLOBAL_H
