#ifndef TREEMASTERIMAGEPANEL_GLOBAL_H
#define TREEMASTERIMAGEPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef TREEMASTERIMAGEPANEL_LIB
# define TREEMASTERIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define TREEMASTERIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // TREEMASTERIMAGEPANEL_GLOBAL_H
