#ifndef INTEGRATIONSHOWHISTORYLOADIMAGE_GLOBAL_H
#define INTEGRATIONSHOWHISTORYLOADIMAGE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef INTEGRATIONSHOWHISTORYLOADIMAGE_LIB
# define INTEGRATIONSHOWHISTORYLOADIMAGE_EXPORT Q_DECL_EXPORT
#else
# define INTEGRATIONSHOWHISTORYLOADIMAGE_EXPORT Q_DECL_IMPORT
#endif

#endif // INTEGRATIONSHOWHISTORYLOADIMAGE_GLOBAL_H
