#ifndef SHOWRESULTFRAME_GLOBAL_H
#define SHOWRESULTFRAME_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SHOWRESULTFRAME_LIB
# define SHOWRESULTFRAME_EXPORT Q_DECL_EXPORT
#else
# define SHOWRESULTFRAME_EXPORT Q_DECL_IMPORT
#endif

#endif // SHOWRESULTFRAME_GLOBAL_H
