#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(RESULTXMLBARCODEAPPENDER_LIB)
#  define RESULTXMLBARCODEAPPENDER_EXPORT Q_DECL_EXPORT
# else
#  define RESULTXMLBARCODEAPPENDER_EXPORT Q_DECL_IMPORT
# endif
#else
# define RESULTXMLBARCODEAPPENDER_EXPORT
#endif
