#ifndef AUTOFOCUSCONTROL_GLOBAL_H
#define AUTOFOCUSCONTROL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef AUTOFOCUSCONTROL_LIB
# define AUTOFOCUSCONTROL_EXPORT Q_DECL_EXPORT
#else
# define AUTOFOCUSCONTROL_EXPORT Q_DECL_IMPORT
#endif

#endif // AUTOFOCUSCONTROL_GLOBAL_H
