#ifndef STARTPROCESSAGAINBUTTONFORDESKTOP_GLOBAL_H
#define STARTPROCESSAGAINBUTTONFORDESKTOP_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef STARTPROCESSAGAINBUTTONFORDESKTOP_LIB
# define STARTPROCESSAGAINBUTTONFORDESKTOP_EXPORT Q_DECL_EXPORT
#else
# define STARTPROCESSAGAINBUTTONFORDESKTOP_EXPORT Q_DECL_IMPORT
#endif

#endif // STARTPROCESSAGAINBUTTONFORDESKTOP_GLOBAL_H
