#ifndef FIXEDWINDOWSIZE_GLOBAL_H
#define FIXEDWINDOWSIZE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef FIXEDWINDOWSIZE_LIB
# define FIXEDWINDOWSIZE_EXPORT Q_DECL_EXPORT
#else
# define FIXEDWINDOWSIZE_EXPORT Q_DECL_IMPORT
#endif

#endif // FIXEDWINDOWSIZE_GLOBAL_H
