#ifndef INTEGRATIONSHOWOKNG_GLOBAL_H
#define INTEGRATIONSHOWOKNG_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef INTEGRATIONSHOWOKNG_LIB
# define INTEGRATIONSHOWOKNG_EXPORT Q_DECL_EXPORT
#else
# define INTEGRATIONSHOWOKNG_EXPORT Q_DECL_IMPORT
#endif

#endif // INTEGRATIONSHOWOKNG_GLOBAL_H
