#ifndef BUTTONLEARNINGNG_GLOBAL_H
#define BUTTONLEARNINGNG_GLOBAL_H

#include <qglobal.h>

#ifdef BUTTONLEARNINGNG_LIB
# define BUTTONLEARNINGNG_EXPORT Q_DECL_EXPORT
#else
# define BUTTONLEARNINGNG_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONLEARNINGNG_GLOBAL_H
