#ifndef PIOFORCAMERAEXECUTER_GLOBAL_H
#define PIOFORCAMERAEXECUTER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PIOFORCAMERAEXECUTER_LIB
# define PIOFORCAMERAEXECUTER_EXPORT Q_DECL_EXPORT
#else
# define PIOFORCAMERAEXECUTER_EXPORT Q_DECL_IMPORT
#endif

#endif // PIOFORCAMERAEXECUTER_GLOBAL_H
