#ifndef SHOWRESULTIMAGECHECKER_GLOBAL_H
#define SHOWRESULTIMAGECHECKER_GLOBAL_H

#include <qglobal.h>

#ifdef SHOWRESULTIMAGECHECKER_LIB
# define SHOWRESULTIMAGECHECKER_EXPORT Q_DECL_EXPORT
#else
# define SHOWRESULTIMAGECHECKER_EXPORT Q_DECL_IMPORT
#endif

#endif // SHOWRESULTIMAGECHECKER_GLOBAL_H
