#ifndef BUTTONFILTERUDCOLORSHIFT_GLOBAL_H
#define BUTTONFILTERUDCOLORSHIFT_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONFILTERUDCOLORSHIFT_LIB
# define BUTTONFILTERUDCOLORSHIFT_EXPORT Q_DECL_EXPORT
#else
# define BUTTONFILTERUDCOLORSHIFT_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONFILTERUDCOLORSHIFT_GLOBAL_H
