#ifndef ALIGNMENTFLEXAREA_GLOBAL_H
#define ALIGNMENTFLEXAREA_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef ALIGNMENTFLEXAREA_LIB
# define ALIGNMENTFLEXAREA_EXPORT Q_DECL_EXPORT
#else
# define ALIGNMENTFLEXAREA_EXPORT Q_DECL_IMPORT
#endif

#endif // ALIGNMENTFLEXAREA_GLOBAL_H
