#ifndef INTEGRATIONCOPYIMAGE_GLOBAL_H
#define INTEGRATIONCOPYIMAGE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef INTEGRATIONCOPYIMAGE_LIB
# define INTEGRATIONCOPYIMAGE_EXPORT Q_DECL_EXPORT
#else
# define INTEGRATIONCOPYIMAGE_EXPORT Q_DECL_IMPORT
#endif

#endif // INTEGRATIONCOPYIMAGE_GLOBAL_H
