#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(SHOWTHRESHOLDSLIDEBAR_LIB)
#  define SHOWTHRESHOLDSLIDEBAR_EXPORT Q_DECL_EXPORT
# else
#  define SHOWTHRESHOLDSLIDEBAR_EXPORT Q_DECL_IMPORT
# endif
#else
# define SHOWTHRESHOLDSLIDEBAR_EXPORT
#endif
