#ifndef LOGINTEGRATORLIB_GLOBAL_H
#define LOGINTEGRATORLIB_GLOBAL_H

#include <qglobal.h>

#ifdef LOGINTEGRATORLIB_LIB
# define LOGINTEGRATORLIB_EXPORT Q_DECL_EXPORT
#else
# define LOGINTEGRATORLIB_EXPORT Q_DECL_IMPORT
#endif

#endif // LOGINTEGRATORLIB_GLOBAL_H
