#ifndef INTEGRATIONSHOWRUNNINGTREND_GLOBAL_H
#define INTEGRATIONSHOWRUNNINGTREND_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef INTEGRATIONSHOWRUNNINGTREND_LIB
# define INTEGRATIONSHOWRUNNINGTREND_EXPORT Q_DECL_EXPORT
#else
# define INTEGRATIONSHOWRUNNINGTREND_EXPORT Q_DECL_IMPORT
#endif

#endif // INTEGRATIONSHOWRUNNINGTREND_GLOBAL_H
