#ifndef PANELDOCKINGFLOAT_GLOBAL_H
#define PANELDOCKINGFLOAT_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PANELDOCKINGFLOAT_LIB
# define PANELDOCKINGFLOAT_EXPORT Q_DECL_EXPORT
#else
# define PANELDOCKINGFLOAT_EXPORT Q_DECL_IMPORT
#endif

#endif // PANELDOCKINGFLOAT_GLOBAL_H
