#ifndef AUTOPCBHOLEALIGNERIMAGEPANEL_GLOBAL_H
#define AUTOPCBHOLEALIGNERIMAGEPANEL_GLOBAL_H

#include <qglobal.h>

#ifdef AUTOPCBHOLEALIGNERIMAGEPANEL_LIB
# define AUTOPCBHOLEALIGNERIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define AUTOPCBHOLEALIGNERIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // AUTOPCBHOLEALIGNERIMAGEPANEL_GLOBAL_H
