#ifndef AUTOFOCUSWITHCAMERA_GLOBAL_H
#define AUTOFOCUSWITHCAMERA_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef AUTOFOCUSWITHCAMERA_LIB
# define AUTOFOCUSWITHCAMERA_EXPORT Q_DECL_EXPORT
#else
# define AUTOFOCUSWITHCAMERA_EXPORT Q_DECL_IMPORT
#endif

#endif // AUTOFOCUSWITHCAMERA_GLOBAL_H
