#ifndef SEQRELAYLCUS2_GLOBAL_H
#define SEQRELAYLCUS2_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SEQRELAYLCUS2_LIB
# define SEQRELAYLCUS2_EXPORT Q_DECL_EXPORT
#else
# define SEQRELAYLCUS2_EXPORT Q_DECL_IMPORT
#endif

#endif // SEQRELAYLCUS2_GLOBAL_H
