# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./SeqRelayLCUS2.h \
    ./seqrelaylcus2_global.h
SOURCES += ../../../GeneralSource/Sequence/qextserialbase.cpp \
    ../../../GeneralSource/Sequence/qextserialport.cpp \
    ../../../GeneralSource/Sequence/win_qextserialport.cpp \
    ../../../Open/SystemVersion.cpp \
    ./SeqRelayLCUS2.cpp
