#ifndef DISPLAYPOINTINGMESSAGE_GLOBAL_H
#define DISPLAYPOINTINGMESSAGE_GLOBAL_H

#include <qglobal.h>

#ifdef DISPLAYPOINTINGMESSAGE_LIB
# define DISPLAYPOINTINGMESSAGE_EXPORT Q_DECL_EXPORT
#else
# define DISPLAYPOINTINGMESSAGE_EXPORT Q_DECL_IMPORT
#endif

#endif // DISPLAYPOINTINGMESSAGE_GLOBAL_H
