#ifndef CONTEC64MULTI_GLOBAL_H
#define CONTEC64MULTI_GLOBAL_H

#include <qglobal.h>

#ifdef CONTEC64MULTI_LIB
# define CONTEC64MULTI_EXPORT Q_DECL_EXPORT
#else
# define CONTEC64MULTI_EXPORT Q_DECL_IMPORT
#endif

#endif // CONTEC64MULTI_GLOBAL_H
