# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = Contec64Multi
DESTDIR = ../../
CONFIG += release
DEFINES += CONTEC64MULTI_LIB
LIBS += -L"./../../../Lib/Release" \
    -lServiceLib
DEPENDPATH += .
MOC_DIR += ./GeneratedFiles/$(ConfigurationName)
OBJECTS_DIR += release
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles
include(Contec64Multi.pri)
