#ifndef BUTTONSTARTLEARNING_GLOBAL_H
#define BUTTONSTARTLEARNING_GLOBAL_H

#include <qglobal.h>

#ifdef BUTTONSTARTLEARNING_LIB
# define BUTTONSTARTLEARNING_EXPORT Q_DECL_EXPORT
#else
# define BUTTONSTARTLEARNING_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONSTARTLEARNING_GLOBAL_H
