#ifndef CONTROLHAYASHITOKEI_GLOBAL_H
#define CONTROLHAYASHITOKEI_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef CONTROLHAYASHITOKEI_LIB
# define CONTROLHAYASHITOKEI_EXPORT Q_DECL_EXPORT
#else
# define CONTROLHAYASHITOKEI_EXPORT Q_DECL_IMPORT
#endif

#endif // CONTROLHAYASHITOKEI_GLOBAL_H
