#ifndef PROPERTYSTEPLINEENHANCERL_GLOBAL_H
#define PROPERTYSTEPLINEENHANCERL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PROPERTYSTEPLINEENHANCERL_LIB
# define PROPERTYSTEPLINEENHANCERL_EXPORT Q_DECL_EXPORT
#else
# define PROPERTYSTEPLINEENHANCERL_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTYSTEPLINEENHANCERL_GLOBAL_H
