#ifndef GENERALSTACKFORM_GLOBAL_H
#define GENERALSTACKFORM_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef GENERALSTACKFORM_LIB
# define GENERALSTACKFORM_EXPORT Q_DECL_EXPORT
#else
# define GENERALSTACKFORM_EXPORT Q_DECL_IMPORT
#endif

#endif // GENERALSTACKFORM_GLOBAL_H
