#ifndef CAMERAFROMPROVIDER_GLOBAL_H
#define CAMERAFROMPROVIDER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef CAMERAFROMPROVIDER_LIB
# define CAMERAFROMPROVIDER_EXPORT Q_DECL_EXPORT
#else
# define CAMERAFROMPROVIDER_EXPORT Q_DECL_IMPORT
#endif

#endif // CAMERAFROMPROVIDER_GLOBAL_H
