# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


TEMPLATE = subdirs
SUBDIRS += Contec64DLL/Contec64DLL/Contec64DLL.pro \
    Contec64DLL-2/Contec64DLL/Contec64DLL2.pro \
    Contec64Multi/Contec64Multi.pro \
    NetworkContec64/PIODevicer/PIODevicer.pro \
    NetworkContec64/PIOClient/PIOClient.pro \
    DummyPIO/DummyPIO.pro \
    TestPIODLL/TestPIODLL.pro \
    ContecBitAccess/ContecBitAccess.pro \
    USB_Control8PIO/USB_Control8PIO.pro \
    StmArm_ControlPIO_A/StmArm_ControlPIO_A.pro \
    USB_Control8ARMV2PIO/USB_Control8ARMV2PIO.pro \
    VirtualPIOServer/VirtualPIOServer.pro \
    VirtualPIOAdapter/VirtualPIOAdapter.pro \
    VirtualPIOClient/VirtualPIOClient.pro \
    NetworkSIOServer/NetworkSIOServer.pro \
    NetworkSIOClientLib/NetworkSIOClientLib.pro \
    NetworkSIOTestClient/NetworkSIOTestClient.pro \
    ADLinkPIO/ADLinkPIO.pro \
    PIOForCameraExecuter/PIOForCameraExecuter.pro \
    NetworkPIOClient/NetworkPIOClient.pro \
    NetworkPIOLib/NetworkPIOLib.pro \
    NetworkPIOVirtual/NetworkPIOVirtual.pro \
    NetworkPIOVirtualCommunicator/NetworkPIOVirtualCommunicator.pro \
    Relay4ByFTDI/Relay4ByFTDI.pro \
    RelayLCUS2/RelayLCUS2.pro \
    SharedPIOLib/SharedPIOLib.pro \
    SharedPIO/SharedPIO.pro
