#ifndef BUTTONSAVEBMPJPG_GLOBAL_H
#define BUTTONSAVEBMPJPG_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONSAVEBMPJPG_LIB
# define BUTTONSAVEBMPJPG_EXPORT Q_DECL_EXPORT
#else
# define BUTTONSAVEBMPJPG_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONSAVEBMPJPG_GLOBAL_H
