#ifndef NETWORKPIOVIRTUAL_GLOBAL_H
#define NETWORKPIOVIRTUAL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef NETWORKPIOVIRTUAL_LIB
# define NETWORKPIOVIRTUAL_EXPORT Q_DECL_EXPORT
#else
# define NETWORKPIOVIRTUAL_EXPORT Q_DECL_IMPORT
#endif

#endif // NETWORKPIOVIRTUAL_GLOBAL_H
