#ifndef RESULTKIDAINSPECTION_GLOBAL_H
#define RESULTKIDAINSPECTION_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef RESULTKIDAINSPECTION_LIB
# define RESULTKIDAINSPECTION_EXPORT Q_DECL_EXPORT
#else
# define RESULTKIDAINSPECTION_EXPORT Q_DECL_IMPORT
#endif

#endif // RESULTKIDAINSPECTION_GLOBAL_H
