/********************************************************************************
** Form generated from reading UI file 'CameraSetting.ui'
**
** Created by: Qt User Interface Compiler version 6.10.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_CAMERASETTING_H
#define UI_CAMERASETTING_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDialog>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QLCDNumber>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QWidget>
#include "mtMeter.h"
#include "mtTBarGraph.h"

QT_BEGIN_NAMESPACE

class Ui_CameraSettingClass
{
public:
    QPushButton *pbCancel;
    QLabel *label_43;
    QLabel *label;
    QLabel *label_45;
    QPushButton *pbOK;
    QLineEdit *leProofFile;
    QTextEdit *teCameraData;
    QCheckBox *checkBoxDirection;
    QPushButton *pbProof;
    QPushButton *pbProofCancel;
    QLineEdit *leCameraType;
    QSpinBox *spinBoxLineRate;
    QGroupBox *groupBox;
    QTabWidget *tabRGB;
    QWidget *tabRed;
    QPushButton *pbRedApply;
    QLabel *label_31;
    QLabel *label_32;
    QLabel *label_33;
    QLabel *label_34;
    QLabel *label_2;
    QSpinBox *sbRedFloor;
    QSpinBox *sbRedCeiling;
    QSlider *hsRedBrightness;
    QSlider *hsRedContrast;
    QSlider *hsRedGamma;
    QLCDNumber *lnRedGamma;
    QLCDNumber *lnRedContrast;
    QLCDNumber *lnRedBrightness;
    QFrame *frame;
    QPushButton *pbRedUpdate;
    QLabel *label_10;
    QLabel *label_7;
    QLabel *label_9;
    QSpinBox *sbRedFirstPoint;
    QLabel *label_5;
    QSpinBox *sbRedSecondPoint;
    QLabel *label_51;
    QLabel *label_52;
    QSpinBox *sbRedFirstXCoordinates;
    QSpinBox *sbRedSecondXCoordinates;
    QLabel *label_53;
    QLabel *label_54;
    QSpinBox *sbRedFirstYCoordinates;
    QLabel *label_6;
    QLabel *label_8;
    QSpinBox *sbRedSecondYCoordinates;
    mtMeter *mRedHU;
    mtTBarGraph *bgRedBrightnessGraph;
    mtMeter *mRedVRR;
    QComboBox *cbRedGraphType;
    QWidget *tabGreen;
    QPushButton *pbGreenApply;
    QLabel *label_3;
    QLabel *label_35;
    QLabel *label_38;
    QLabel *label_36;
    QLabel *label_37;
    QSpinBox *sbGreenFloor;
    QSpinBox *sbGreenCeiling;
    QSlider *hsGreenBrightness;
    QSlider *hsGreenContrast;
    QSlider *hsGreenGamma;
    QLCDNumber *lnGreenBrightness;
    QLCDNumber *lnGreenContrast;
    QLCDNumber *lnGreenGamma;
    QFrame *frame_2;
    QLabel *label_20;
    QLabel *label_12;
    QSpinBox *sbGreenFirstXCoordinates;
    QLabel *label_19;
    QLabel *label_15;
    QSpinBox *sbGreenSecondXCoordinates;
    QPushButton *pbGreenUpdate;
    QSpinBox *sbGreenFirstPoint;
    QLabel *label_16;
    QSpinBox *sbGreenSecondPoint;
    QLabel *label_14;
    QSpinBox *sbGreenSecondYCoordinates;
    QLabel *label_18;
    QLabel *label_11;
    QLabel *label_13;
    QSpinBox *sbGreenFirstYCoordinates;
    QLabel *label_17;
    mtMeter *mGreenVRR;
    mtMeter *mGreenHU;
    mtTBarGraph *bgGreenBrightnessGraph;
    QComboBox *cbGreenGraphType;
    QWidget *tabBlue;
    QPushButton *pbBlueApply;
    QLabel *label_39;
    QLabel *label_40;
    QLabel *label_41;
    QLabel *label_42;
    QLabel *label_4;
    QSpinBox *sbBlueFloor;
    QSpinBox *sbBlueCeiling;
    QSlider *hsBlueBrightness;
    QSlider *hsBlueContrast;
    QSlider *hsBlueGamma;
    QLCDNumber *lnBlueBrightness;
    QLCDNumber *lnBlueContrast;
    QLCDNumber *lnBlueGamma;
    QFrame *frame_3;
    QLabel *label_25;
    QLabel *label_21;
    QLabel *label_28;
    QSpinBox *sbBlueFirstXCoordinates;
    QLabel *label_29;
    QLabel *label_27;
    QSpinBox *sbBlueSecondXCoordinates;
    QPushButton *pbBlueUpdate;
    QLabel *label_23;
    QSpinBox *sbBlueFirstPoint;
    QSpinBox *sbBlueSecondPoint;
    QLabel *label_22;
    QSpinBox *sbBlueFirstYCoordinates;
    QLabel *label_26;
    QLabel *label_24;
    QSpinBox *sbBlueSecondYCoordinates;
    QLabel *label_30;
    mtMeter *mBlueHU;
    mtTBarGraph *bgBlueBrightnessGraph;
    mtMeter *mBlueVRR;
    QComboBox *cbBlueGraphType;
    QLabel *label_46;
    QDoubleSpinBox *doubleSpinBoxExposureTime;
    QLabel *label_47;
    QLabel *label_48;
    QLabel *label_49;
    QLabel *label_50;
    QLabel *label_511;
    QDoubleSpinBox *doubleSpinBoxGainRed;
    QSpinBox *spinBoxOffsetRed;
    QSpinBox *spinBoxOffsetGreen;
    QDoubleSpinBox *doubleSpinBoxGainGreen;
    QSpinBox *spinBoxOffsetBlue;
    QDoubleSpinBox *doubleSpinBoxGainBlue;
    QSpinBox *spinBoxRedOffsetX;
    QSpinBox *spinBoxBlueOffsetX;
    QLabel *label_521;
    QDoubleSpinBox *doubleSpinBoxBlueMultipleX;
    QLabel *label_531;
    QLabel *label_541;
    QDoubleSpinBox *doubleSpinBoxGreenMultipleX;
    QLabel *label_55;
    QLabel *label_56;
    QDoubleSpinBox *doubleSpinBoxRedMultipleX;
    QSpinBox *spinBoxGreenOffsetX;
    QSpinBox *spinBoxRedOffsetY;
    QSpinBox *spinBoxGreenOffsetY;
    QSpinBox *spinBoxBlueOffsetY;
    QLabel *label_57;
    QLabel *label_58;
    QDoubleSpinBox *doubleSpinBoxGainGreenL;
    QDoubleSpinBox *doubleSpinBoxGainRedL;
    QDoubleSpinBox *doubleSpinBoxGainBlueL;
    QLabel *label_59;
    QDoubleSpinBox *doubleSpinBoxGainBlueR;
    QDoubleSpinBox *doubleSpinBoxGainRedR;
    QDoubleSpinBox *doubleSpinBoxGainGreenR;
    QLabel *label_60;
    QLabel *label_61;
    QSpinBox *spinBoxOffsetBlueL;
    QSpinBox *spinBoxOffsetGreenL;
    QSpinBox *spinBoxOffsetRedL;
    QSpinBox *spinBoxOffsetBlueR;
    QSpinBox *spinBoxOffsetGreenR;
    QSpinBox *spinBoxOffsetRedR;
    QLabel *label_62;
    QSpinBox *spinBoxHorizontalBinning;
    QSpinBox *spinBoxVerticalBinning;
    QLabel *label_63;
    QCheckBox *checkBoxLeftRight;
    QCheckBox *checkBoxExternalTrigger;
    QCheckBox *checkBoxCameraControl;
    QCheckBox *checkBoxAutoBlackLevel;
    QCheckBox *checkBoxCalibrateFPN;
    QLabel *label_64;
    QSpinBox *spinBoxROIOffset;
    QLabel *label_65;
    QLabel *label_66;
    QSpinBox *spinBoxLightOffMilisec;
    QSpinBox *spinBoxLightOnMilisec;

    void setupUi(QDialog *CameraSettingClass)
    {
        if (CameraSettingClass->objectName().isEmpty())
            CameraSettingClass->setObjectName("CameraSettingClass");
        CameraSettingClass->resize(870, 796);
        pbCancel = new QPushButton(CameraSettingClass);
        pbCancel->setObjectName("pbCancel");
        pbCancel->setGeometry(QRect(680, 660, 75, 31));
        label_43 = new QLabel(CameraSettingClass);
        label_43->setObjectName("label_43");
        label_43->setGeometry(QRect(18, 32, 68, 16));
        label = new QLabel(CameraSettingClass);
        label->setObjectName("label");
        label->setGeometry(QRect(25, 120, 101, 21));
        label_45 = new QLabel(CameraSettingClass);
        label_45->setObjectName("label_45");
        label_45->setGeometry(QRect(310, 27, 51, 16));
        pbOK = new QPushButton(CameraSettingClass);
        pbOK->setObjectName("pbOK");
        pbOK->setGeometry(QRect(780, 660, 75, 31));
        leProofFile = new QLineEdit(CameraSettingClass);
        leProofFile->setObjectName("leProofFile");
        leProofFile->setGeometry(QRect(370, 24, 341, 21));
        leProofFile->setReadOnly(true);
        teCameraData = new QTextEdit(CameraSettingClass);
        teCameraData->setObjectName("teCameraData");
        teCameraData->setGeometry(QRect(480, 650, 181, 71));
        teCameraData->setReadOnly(true);
        checkBoxDirection = new QCheckBox(CameraSettingClass);
        checkBoxDirection->setObjectName("checkBoxDirection");
        checkBoxDirection->setGeometry(QRect(20, 200, 211, 21));
        pbProof = new QPushButton(CameraSettingClass);
        pbProof->setObjectName("pbProof");
        pbProof->setGeometry(QRect(710, 20, 31, 31));
        pbProofCancel = new QPushButton(CameraSettingClass);
        pbProofCancel->setObjectName("pbProofCancel");
        pbProofCancel->setGeometry(QRect(750, 20, 61, 31));
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/Qtres/flash_64.PNG"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        pbProofCancel->setIcon(icon);
        leCameraType = new QLineEdit(CameraSettingClass);
        leCameraType->setObjectName("leCameraType");
        leCameraType->setGeometry(QRect(100, 30, 101, 20));
        leCameraType->setReadOnly(true);
        spinBoxLineRate = new QSpinBox(CameraSettingClass);
        spinBoxLineRate->setObjectName("spinBoxLineRate");
        spinBoxLineRate->setGeometry(QRect(130, 118, 81, 22));
        spinBoxLineRate->setMaximum(70000);
        groupBox = new QGroupBox(CameraSettingClass);
        groupBox->setObjectName("groupBox");
        groupBox->setGeometry(QRect(340, 63, 511, 581));
        tabRGB = new QTabWidget(groupBox);
        tabRGB->setObjectName("tabRGB");
        tabRGB->setGeometry(QRect(10, 20, 491, 551));
        tabRed = new QWidget();
        tabRed->setObjectName("tabRed");
        pbRedApply = new QPushButton(tabRed);
        pbRedApply->setObjectName("pbRedApply");
        pbRedApply->setGeometry(QRect(390, 480, 75, 31));
        label_31 = new QLabel(tabRed);
        label_31->setObjectName("label_31");
        label_31->setGeometry(QRect(20, 50, 61, 16));
        label_32 = new QLabel(tabRed);
        label_32->setObjectName("label_32");
        label_32->setGeometry(QRect(20, 80, 61, 16));
        label_33 = new QLabel(tabRed);
        label_33->setObjectName("label_33");
        label_33->setGeometry(QRect(310, 20, 51, 16));
        label_34 = new QLabel(tabRed);
        label_34->setObjectName("label_34");
        label_34->setGeometry(QRect(310, 50, 51, 16));
        label_2 = new QLabel(tabRed);
        label_2->setObjectName("label_2");
        label_2->setGeometry(QRect(20, 20, 61, 16));
        sbRedFloor = new QSpinBox(tabRed);
        sbRedFloor->setObjectName("sbRedFloor");
        sbRedFloor->setGeometry(QRect(360, 17, 51, 22));
        sbRedFloor->setMaximum(255);
        sbRedCeiling = new QSpinBox(tabRed);
        sbRedCeiling->setObjectName("sbRedCeiling");
        sbRedCeiling->setGeometry(QRect(360, 47, 51, 22));
        sbRedCeiling->setMaximum(255);
        sbRedCeiling->setValue(255);
        hsRedBrightness = new QSlider(tabRed);
        hsRedBrightness->setObjectName("hsRedBrightness");
        hsRedBrightness->setGeometry(QRect(90, 17, 121, 21));
        hsRedBrightness->setMaximum(200);
        hsRedBrightness->setOrientation(Qt::Horizontal);
        hsRedContrast = new QSlider(tabRed);
        hsRedContrast->setObjectName("hsRedContrast");
        hsRedContrast->setGeometry(QRect(90, 47, 121, 21));
        hsRedContrast->setMaximum(200);
        hsRedContrast->setOrientation(Qt::Horizontal);
        hsRedGamma = new QSlider(tabRed);
        hsRedGamma->setObjectName("hsRedGamma");
        hsRedGamma->setGeometry(QRect(90, 77, 121, 21));
        hsRedGamma->setMaximum(400);
        hsRedGamma->setOrientation(Qt::Horizontal);
        lnRedGamma = new QLCDNumber(tabRed);
        lnRedGamma->setObjectName("lnRedGamma");
        lnRedGamma->setGeometry(QRect(220, 76, 41, 23));
        lnRedGamma->setDigitCount(4);
        lnRedGamma->setSegmentStyle(QLCDNumber::Flat);
        lnRedContrast = new QLCDNumber(tabRed);
        lnRedContrast->setObjectName("lnRedContrast");
        lnRedContrast->setGeometry(QRect(220, 46, 41, 23));
        lnRedContrast->setDigitCount(4);
        lnRedContrast->setSegmentStyle(QLCDNumber::Flat);
        lnRedBrightness = new QLCDNumber(tabRed);
        lnRedBrightness->setObjectName("lnRedBrightness");
        lnRedBrightness->setGeometry(QRect(220, 16, 41, 23));
        lnRedBrightness->setDigitCount(4);
        lnRedBrightness->setSegmentStyle(QLCDNumber::Flat);
        frame = new QFrame(tabRed);
        frame->setObjectName("frame");
        frame->setGeometry(QRect(10, 130, 461, 331));
        frame->setFrameShape(QFrame::Panel);
        frame->setFrameShadow(QFrame::Plain);
        pbRedUpdate = new QPushButton(frame);
        pbRedUpdate->setObjectName("pbRedUpdate");
        pbRedUpdate->setGeometry(QRect(50, 280, 75, 31));
        label_10 = new QLabel(frame);
        label_10->setObjectName("label_10");
        label_10->setGeometry(QRect(15, 150, 102, 16));
        label_7 = new QLabel(frame);
        label_7->setObjectName("label_7");
        label_7->setGeometry(QRect(15, 170, 16, 22));
        QFont font;
        font.setFamilies({QString::fromUtf8("MS UI Gothic")});
        font.setPointSize(16);
        font.setBold(false);
        font.setItalic(false);
        font.setUnderline(false);
        font.setStrikeOut(false);
        label_7->setFont(font);
        label_9 = new QLabel(frame);
        label_9->setObjectName("label_9");
        label_9->setGeometry(QRect(147, 170, 16, 22));
        label_9->setFont(font);
        sbRedFirstPoint = new QSpinBox(frame);
        sbRedFirstPoint->setObjectName("sbRedFirstPoint");
        sbRedFirstPoint->setGeometry(QRect(95, 37, 51, 22));
        sbRedFirstPoint->setMaximum(255);
        label_5 = new QLabel(frame);
        label_5->setObjectName("label_5");
        label_5->setGeometry(QRect(25, 70, 66, 16));
        sbRedSecondPoint = new QSpinBox(frame);
        sbRedSecondPoint->setObjectName("sbRedSecondPoint");
        sbRedSecondPoint->setGeometry(QRect(95, 67, 51, 22));
        sbRedSecondPoint->setMaximum(255);
        label_51 = new QLabel(frame);
        label_51->setObjectName("label_51");
        label_51->setGeometry(QRect(15, 100, 89, 16));
        label_52 = new QLabel(frame);
        label_52->setObjectName("label_52");
        label_52->setGeometry(QRect(15, 120, 16, 22));
        label_52->setFont(font);
        sbRedFirstXCoordinates = new QSpinBox(frame);
        sbRedFirstXCoordinates->setObjectName("sbRedFirstXCoordinates");
        sbRedFirstXCoordinates->setGeometry(QRect(25, 120, 51, 22));
        sbRedFirstXCoordinates->setMaximum(255);
        sbRedSecondXCoordinates = new QSpinBox(frame);
        sbRedSecondXCoordinates->setObjectName("sbRedSecondXCoordinates");
        sbRedSecondXCoordinates->setGeometry(QRect(25, 170, 51, 22));
        sbRedSecondXCoordinates->setMaximum(255);
        sbRedSecondXCoordinates->setValue(255);
        label_53 = new QLabel(frame);
        label_53->setObjectName("label_53");
        label_53->setGeometry(QRect(25, 40, 53, 16));
        label_54 = new QLabel(frame);
        label_54->setObjectName("label_54");
        label_54->setGeometry(QRect(83, 120, 16, 22));
        label_54->setFont(font);
        sbRedFirstYCoordinates = new QSpinBox(frame);
        sbRedFirstYCoordinates->setObjectName("sbRedFirstYCoordinates");
        sbRedFirstYCoordinates->setGeometry(QRect(92, 120, 51, 22));
        sbRedFirstYCoordinates->setMaximum(255);
        label_6 = new QLabel(frame);
        label_6->setObjectName("label_6");
        label_6->setGeometry(QRect(147, 120, 16, 22));
        label_6->setFont(font);
        label_8 = new QLabel(frame);
        label_8->setObjectName("label_8");
        label_8->setGeometry(QRect(83, 170, 16, 22));
        label_8->setFont(font);
        sbRedSecondYCoordinates = new QSpinBox(frame);
        sbRedSecondYCoordinates->setObjectName("sbRedSecondYCoordinates");
        sbRedSecondYCoordinates->setGeometry(QRect(92, 170, 51, 22));
        sbRedSecondYCoordinates->setMaximum(255);
        sbRedSecondYCoordinates->setValue(255);
        mRedHU = new mtMeter(frame);
        mRedHU->setObjectName("mRedHU");
        mRedHU->setGeometry(QRect(190, 295, 256, 20));
        bgRedBrightnessGraph = new mtTBarGraph(frame);
        bgRedBrightnessGraph->setObjectName("bgRedBrightnessGraph");
        bgRedBrightnessGraph->setGeometry(QRect(190, 40, 256, 256));
        mRedVRR = new mtMeter(frame);
        mRedVRR->setObjectName("mRedVRR");
        mRedVRR->setGeometry(QRect(170, 40, 21, 256));
        cbRedGraphType = new QComboBox(tabRed);
        cbRedGraphType->addItem(QString());
        cbRedGraphType->addItem(QString());
        cbRedGraphType->addItem(QString());
        cbRedGraphType->addItem(QString());
        cbRedGraphType->addItem(QString());
        cbRedGraphType->addItem(QString());
        cbRedGraphType->addItem(QString());
        cbRedGraphType->addItem(QString());
        cbRedGraphType->setObjectName("cbRedGraphType");
        cbRedGraphType->setGeometry(QRect(30, 120, 111, 22));
        tabRGB->addTab(tabRed, QString());
        tabGreen = new QWidget();
        tabGreen->setObjectName("tabGreen");
        pbGreenApply = new QPushButton(tabGreen);
        pbGreenApply->setObjectName("pbGreenApply");
        pbGreenApply->setGeometry(QRect(390, 480, 75, 31));
        label_3 = new QLabel(tabGreen);
        label_3->setObjectName("label_3");
        label_3->setGeometry(QRect(20, 20, 61, 16));
        label_35 = new QLabel(tabGreen);
        label_35->setObjectName("label_35");
        label_35->setGeometry(QRect(20, 50, 61, 16));
        label_38 = new QLabel(tabGreen);
        label_38->setObjectName("label_38");
        label_38->setGeometry(QRect(20, 80, 61, 16));
        label_36 = new QLabel(tabGreen);
        label_36->setObjectName("label_36");
        label_36->setGeometry(QRect(310, 20, 51, 16));
        label_37 = new QLabel(tabGreen);
        label_37->setObjectName("label_37");
        label_37->setGeometry(QRect(310, 50, 51, 16));
        sbGreenFloor = new QSpinBox(tabGreen);
        sbGreenFloor->setObjectName("sbGreenFloor");
        sbGreenFloor->setGeometry(QRect(360, 17, 51, 22));
        sbGreenFloor->setMaximum(255);
        sbGreenCeiling = new QSpinBox(tabGreen);
        sbGreenCeiling->setObjectName("sbGreenCeiling");
        sbGreenCeiling->setGeometry(QRect(360, 47, 51, 22));
        sbGreenCeiling->setMaximum(255);
        sbGreenCeiling->setValue(255);
        hsGreenBrightness = new QSlider(tabGreen);
        hsGreenBrightness->setObjectName("hsGreenBrightness");
        hsGreenBrightness->setGeometry(QRect(90, 17, 121, 21));
        hsGreenBrightness->setMaximum(200);
        hsGreenBrightness->setOrientation(Qt::Horizontal);
        hsGreenContrast = new QSlider(tabGreen);
        hsGreenContrast->setObjectName("hsGreenContrast");
        hsGreenContrast->setGeometry(QRect(90, 47, 121, 21));
        hsGreenContrast->setMaximum(200);
        hsGreenContrast->setOrientation(Qt::Horizontal);
        hsGreenGamma = new QSlider(tabGreen);
        hsGreenGamma->setObjectName("hsGreenGamma");
        hsGreenGamma->setGeometry(QRect(90, 77, 121, 21));
        hsGreenGamma->setMaximum(400);
        hsGreenGamma->setOrientation(Qt::Horizontal);
        lnGreenBrightness = new QLCDNumber(tabGreen);
        lnGreenBrightness->setObjectName("lnGreenBrightness");
        lnGreenBrightness->setGeometry(QRect(220, 16, 41, 23));
        lnGreenBrightness->setDigitCount(4);
        lnGreenBrightness->setSegmentStyle(QLCDNumber::Flat);
        lnGreenContrast = new QLCDNumber(tabGreen);
        lnGreenContrast->setObjectName("lnGreenContrast");
        lnGreenContrast->setGeometry(QRect(220, 46, 41, 23));
        lnGreenContrast->setDigitCount(4);
        lnGreenContrast->setSegmentStyle(QLCDNumber::Flat);
        lnGreenGamma = new QLCDNumber(tabGreen);
        lnGreenGamma->setObjectName("lnGreenGamma");
        lnGreenGamma->setGeometry(QRect(220, 76, 41, 23));
        lnGreenGamma->setDigitCount(4);
        lnGreenGamma->setSegmentStyle(QLCDNumber::Flat);
        frame_2 = new QFrame(tabGreen);
        frame_2->setObjectName("frame_2");
        frame_2->setGeometry(QRect(10, 130, 461, 331));
        frame_2->setFrameShape(QFrame::Panel);
        frame_2->setFrameShadow(QFrame::Plain);
        label_20 = new QLabel(frame_2);
        label_20->setObjectName("label_20");
        label_20->setGeometry(QRect(15, 100, 89, 16));
        label_12 = new QLabel(frame_2);
        label_12->setObjectName("label_12");
        label_12->setGeometry(QRect(15, 120, 16, 22));
        label_12->setFont(font);
        sbGreenFirstXCoordinates = new QSpinBox(frame_2);
        sbGreenFirstXCoordinates->setObjectName("sbGreenFirstXCoordinates");
        sbGreenFirstXCoordinates->setGeometry(QRect(25, 120, 51, 22));
        sbGreenFirstXCoordinates->setMaximum(255);
        label_19 = new QLabel(frame_2);
        label_19->setObjectName("label_19");
        label_19->setGeometry(QRect(15, 150, 102, 16));
        label_15 = new QLabel(frame_2);
        label_15->setObjectName("label_15");
        label_15->setGeometry(QRect(15, 170, 16, 22));
        label_15->setFont(font);
        sbGreenSecondXCoordinates = new QSpinBox(frame_2);
        sbGreenSecondXCoordinates->setObjectName("sbGreenSecondXCoordinates");
        sbGreenSecondXCoordinates->setGeometry(QRect(25, 170, 51, 22));
        sbGreenSecondXCoordinates->setMaximum(255);
        sbGreenSecondXCoordinates->setValue(255);
        pbGreenUpdate = new QPushButton(frame_2);
        pbGreenUpdate->setObjectName("pbGreenUpdate");
        pbGreenUpdate->setGeometry(QRect(50, 280, 75, 31));
        sbGreenFirstPoint = new QSpinBox(frame_2);
        sbGreenFirstPoint->setObjectName("sbGreenFirstPoint");
        sbGreenFirstPoint->setGeometry(QRect(95, 37, 51, 22));
        sbGreenFirstPoint->setMaximum(255);
        label_16 = new QLabel(frame_2);
        label_16->setObjectName("label_16");
        label_16->setGeometry(QRect(25, 70, 66, 16));
        sbGreenSecondPoint = new QSpinBox(frame_2);
        sbGreenSecondPoint->setObjectName("sbGreenSecondPoint");
        sbGreenSecondPoint->setGeometry(QRect(95, 67, 51, 22));
        sbGreenSecondPoint->setMaximum(255);
        label_14 = new QLabel(frame_2);
        label_14->setObjectName("label_14");
        label_14->setGeometry(QRect(83, 170, 16, 22));
        label_14->setFont(font);
        sbGreenSecondYCoordinates = new QSpinBox(frame_2);
        sbGreenSecondYCoordinates->setObjectName("sbGreenSecondYCoordinates");
        sbGreenSecondYCoordinates->setGeometry(QRect(92, 170, 51, 22));
        sbGreenSecondYCoordinates->setMaximum(255);
        sbGreenSecondYCoordinates->setValue(255);
        label_18 = new QLabel(frame_2);
        label_18->setObjectName("label_18");
        label_18->setGeometry(QRect(147, 170, 16, 22));
        label_18->setFont(font);
        label_11 = new QLabel(frame_2);
        label_11->setObjectName("label_11");
        label_11->setGeometry(QRect(25, 40, 53, 16));
        label_13 = new QLabel(frame_2);
        label_13->setObjectName("label_13");
        label_13->setGeometry(QRect(83, 120, 16, 22));
        label_13->setFont(font);
        sbGreenFirstYCoordinates = new QSpinBox(frame_2);
        sbGreenFirstYCoordinates->setObjectName("sbGreenFirstYCoordinates");
        sbGreenFirstYCoordinates->setGeometry(QRect(92, 120, 51, 22));
        sbGreenFirstYCoordinates->setMaximum(255);
        label_17 = new QLabel(frame_2);
        label_17->setObjectName("label_17");
        label_17->setGeometry(QRect(147, 120, 16, 22));
        label_17->setFont(font);
        mGreenVRR = new mtMeter(frame_2);
        mGreenVRR->setObjectName("mGreenVRR");
        mGreenVRR->setGeometry(QRect(170, 40, 21, 256));
        mGreenHU = new mtMeter(frame_2);
        mGreenHU->setObjectName("mGreenHU");
        mGreenHU->setGeometry(QRect(190, 295, 256, 20));
        bgGreenBrightnessGraph = new mtTBarGraph(frame_2);
        bgGreenBrightnessGraph->setObjectName("bgGreenBrightnessGraph");
        bgGreenBrightnessGraph->setGeometry(QRect(190, 40, 256, 256));
        cbGreenGraphType = new QComboBox(tabGreen);
        cbGreenGraphType->addItem(QString());
        cbGreenGraphType->addItem(QString());
        cbGreenGraphType->addItem(QString());
        cbGreenGraphType->addItem(QString());
        cbGreenGraphType->addItem(QString());
        cbGreenGraphType->addItem(QString());
        cbGreenGraphType->addItem(QString());
        cbGreenGraphType->addItem(QString());
        cbGreenGraphType->setObjectName("cbGreenGraphType");
        cbGreenGraphType->setGeometry(QRect(30, 120, 111, 22));
        tabRGB->addTab(tabGreen, QString());
        tabBlue = new QWidget();
        tabBlue->setObjectName("tabBlue");
        pbBlueApply = new QPushButton(tabBlue);
        pbBlueApply->setObjectName("pbBlueApply");
        pbBlueApply->setGeometry(QRect(390, 480, 75, 31));
        label_39 = new QLabel(tabBlue);
        label_39->setObjectName("label_39");
        label_39->setGeometry(QRect(310, 50, 51, 16));
        label_40 = new QLabel(tabBlue);
        label_40->setObjectName("label_40");
        label_40->setGeometry(QRect(20, 80, 61, 16));
        label_41 = new QLabel(tabBlue);
        label_41->setObjectName("label_41");
        label_41->setGeometry(QRect(20, 50, 61, 16));
        label_42 = new QLabel(tabBlue);
        label_42->setObjectName("label_42");
        label_42->setGeometry(QRect(310, 20, 51, 16));
        label_4 = new QLabel(tabBlue);
        label_4->setObjectName("label_4");
        label_4->setGeometry(QRect(20, 20, 61, 16));
        sbBlueFloor = new QSpinBox(tabBlue);
        sbBlueFloor->setObjectName("sbBlueFloor");
        sbBlueFloor->setGeometry(QRect(360, 17, 51, 22));
        sbBlueFloor->setMaximum(255);
        sbBlueCeiling = new QSpinBox(tabBlue);
        sbBlueCeiling->setObjectName("sbBlueCeiling");
        sbBlueCeiling->setGeometry(QRect(360, 47, 51, 22));
        sbBlueCeiling->setMaximum(255);
        sbBlueCeiling->setValue(255);
        hsBlueBrightness = new QSlider(tabBlue);
        hsBlueBrightness->setObjectName("hsBlueBrightness");
        hsBlueBrightness->setGeometry(QRect(90, 17, 121, 21));
        hsBlueBrightness->setMaximum(200);
        hsBlueBrightness->setOrientation(Qt::Horizontal);
        hsBlueContrast = new QSlider(tabBlue);
        hsBlueContrast->setObjectName("hsBlueContrast");
        hsBlueContrast->setGeometry(QRect(90, 47, 121, 21));
        hsBlueContrast->setMaximum(200);
        hsBlueContrast->setOrientation(Qt::Horizontal);
        hsBlueGamma = new QSlider(tabBlue);
        hsBlueGamma->setObjectName("hsBlueGamma");
        hsBlueGamma->setGeometry(QRect(90, 77, 121, 21));
        hsBlueGamma->setMaximum(400);
        hsBlueGamma->setOrientation(Qt::Horizontal);
        lnBlueBrightness = new QLCDNumber(tabBlue);
        lnBlueBrightness->setObjectName("lnBlueBrightness");
        lnBlueBrightness->setGeometry(QRect(220, 16, 41, 23));
        lnBlueBrightness->setDigitCount(4);
        lnBlueBrightness->setSegmentStyle(QLCDNumber::Flat);
        lnBlueContrast = new QLCDNumber(tabBlue);
        lnBlueContrast->setObjectName("lnBlueContrast");
        lnBlueContrast->setGeometry(QRect(220, 46, 41, 23));
        lnBlueContrast->setDigitCount(4);
        lnBlueContrast->setSegmentStyle(QLCDNumber::Flat);
        lnBlueGamma = new QLCDNumber(tabBlue);
        lnBlueGamma->setObjectName("lnBlueGamma");
        lnBlueGamma->setGeometry(QRect(220, 76, 41, 23));
        lnBlueGamma->setDigitCount(4);
        lnBlueGamma->setSegmentStyle(QLCDNumber::Flat);
        frame_3 = new QFrame(tabBlue);
        frame_3->setObjectName("frame_3");
        frame_3->setGeometry(QRect(10, 130, 461, 331));
        frame_3->setFrameShape(QFrame::Panel);
        frame_3->setFrameShadow(QFrame::Plain);
        label_25 = new QLabel(frame_3);
        label_25->setObjectName("label_25");
        label_25->setGeometry(QRect(25, 70, 66, 16));
        label_21 = new QLabel(frame_3);
        label_21->setObjectName("label_21");
        label_21->setGeometry(QRect(15, 100, 89, 16));
        label_28 = new QLabel(frame_3);
        label_28->setObjectName("label_28");
        label_28->setGeometry(QRect(15, 120, 16, 22));
        label_28->setFont(font);
        sbBlueFirstXCoordinates = new QSpinBox(frame_3);
        sbBlueFirstXCoordinates->setObjectName("sbBlueFirstXCoordinates");
        sbBlueFirstXCoordinates->setGeometry(QRect(25, 120, 51, 22));
        sbBlueFirstXCoordinates->setMaximum(255);
        label_29 = new QLabel(frame_3);
        label_29->setObjectName("label_29");
        label_29->setGeometry(QRect(15, 150, 102, 16));
        label_27 = new QLabel(frame_3);
        label_27->setObjectName("label_27");
        label_27->setGeometry(QRect(15, 170, 16, 22));
        label_27->setFont(font);
        sbBlueSecondXCoordinates = new QSpinBox(frame_3);
        sbBlueSecondXCoordinates->setObjectName("sbBlueSecondXCoordinates");
        sbBlueSecondXCoordinates->setGeometry(QRect(25, 170, 51, 22));
        sbBlueSecondXCoordinates->setMaximum(255);
        sbBlueSecondXCoordinates->setValue(255);
        pbBlueUpdate = new QPushButton(frame_3);
        pbBlueUpdate->setObjectName("pbBlueUpdate");
        pbBlueUpdate->setGeometry(QRect(50, 280, 75, 31));
        label_23 = new QLabel(frame_3);
        label_23->setObjectName("label_23");
        label_23->setGeometry(QRect(25, 40, 53, 16));
        sbBlueFirstPoint = new QSpinBox(frame_3);
        sbBlueFirstPoint->setObjectName("sbBlueFirstPoint");
        sbBlueFirstPoint->setGeometry(QRect(95, 37, 51, 22));
        sbBlueFirstPoint->setMaximum(255);
        sbBlueSecondPoint = new QSpinBox(frame_3);
        sbBlueSecondPoint->setObjectName("sbBlueSecondPoint");
        sbBlueSecondPoint->setGeometry(QRect(95, 67, 51, 22));
        sbBlueSecondPoint->setMaximum(255);
        label_22 = new QLabel(frame_3);
        label_22->setObjectName("label_22");
        label_22->setGeometry(QRect(83, 120, 16, 22));
        label_22->setFont(font);
        sbBlueFirstYCoordinates = new QSpinBox(frame_3);
        sbBlueFirstYCoordinates->setObjectName("sbBlueFirstYCoordinates");
        sbBlueFirstYCoordinates->setGeometry(QRect(92, 120, 51, 22));
        sbBlueFirstYCoordinates->setMaximum(255);
        label_26 = new QLabel(frame_3);
        label_26->setObjectName("label_26");
        label_26->setGeometry(QRect(147, 120, 16, 22));
        label_26->setFont(font);
        label_24 = new QLabel(frame_3);
        label_24->setObjectName("label_24");
        label_24->setGeometry(QRect(83, 170, 16, 22));
        label_24->setFont(font);
        sbBlueSecondYCoordinates = new QSpinBox(frame_3);
        sbBlueSecondYCoordinates->setObjectName("sbBlueSecondYCoordinates");
        sbBlueSecondYCoordinates->setGeometry(QRect(92, 170, 51, 22));
        sbBlueSecondYCoordinates->setMaximum(255);
        sbBlueSecondYCoordinates->setValue(255);
        label_30 = new QLabel(frame_3);
        label_30->setObjectName("label_30");
        label_30->setGeometry(QRect(147, 170, 16, 22));
        label_30->setFont(font);
        mBlueHU = new mtMeter(frame_3);
        mBlueHU->setObjectName("mBlueHU");
        mBlueHU->setGeometry(QRect(190, 295, 256, 20));
        bgBlueBrightnessGraph = new mtTBarGraph(frame_3);
        bgBlueBrightnessGraph->setObjectName("bgBlueBrightnessGraph");
        bgBlueBrightnessGraph->setGeometry(QRect(190, 40, 256, 256));
        mBlueVRR = new mtMeter(frame_3);
        mBlueVRR->setObjectName("mBlueVRR");
        mBlueVRR->setGeometry(QRect(170, 40, 21, 256));
        cbBlueGraphType = new QComboBox(tabBlue);
        cbBlueGraphType->addItem(QString());
        cbBlueGraphType->addItem(QString());
        cbBlueGraphType->addItem(QString());
        cbBlueGraphType->addItem(QString());
        cbBlueGraphType->addItem(QString());
        cbBlueGraphType->addItem(QString());
        cbBlueGraphType->addItem(QString());
        cbBlueGraphType->addItem(QString());
        cbBlueGraphType->setObjectName("cbBlueGraphType");
        cbBlueGraphType->setGeometry(QRect(30, 120, 111, 22));
        tabRGB->addTab(tabBlue, QString());
        label_46 = new QLabel(CameraSettingClass);
        label_46->setObjectName("label_46");
        label_46->setGeometry(QRect(20, 150, 201, 20));
        doubleSpinBoxExposureTime = new QDoubleSpinBox(CameraSettingClass);
        doubleSpinBoxExposureTime->setObjectName("doubleSpinBoxExposureTime");
        doubleSpinBoxExposureTime->setGeometry(QRect(110, 170, 101, 24));
        doubleSpinBoxExposureTime->setDecimals(5);
        doubleSpinBoxExposureTime->setMinimum(0.960000000000000);
        doubleSpinBoxExposureTime->setMaximum(3000.000000000000000);
        label_47 = new QLabel(CameraSettingClass);
        label_47->setObjectName("label_47");
        label_47->setGeometry(QRect(90, 250, 61, 20));
        label_48 = new QLabel(CameraSettingClass);
        label_48->setObjectName("label_48");
        label_48->setGeometry(QRect(30, 300, 61, 20));
        label_49 = new QLabel(CameraSettingClass);
        label_49->setObjectName("label_49");
        label_49->setGeometry(QRect(20, 270, 51, 20));
        label_50 = new QLabel(CameraSettingClass);
        label_50->setObjectName("label_50");
        label_50->setGeometry(QRect(20, 330, 51, 20));
        label_511 = new QLabel(CameraSettingClass);
        label_511->setObjectName("label_511");
        label_511->setGeometry(QRect(20, 390, 51, 20));
        doubleSpinBoxGainRed = new QDoubleSpinBox(CameraSettingClass);
        doubleSpinBoxGainRed->setObjectName("doubleSpinBoxGainRed");
        doubleSpinBoxGainRed->setGeometry(QRect(80, 270, 81, 24));
        doubleSpinBoxGainRed->setDecimals(5);
        doubleSpinBoxGainRed->setMinimum(0.000240000000000);
        doubleSpinBoxGainRed->setMaximum(5.516850000000000);
        spinBoxOffsetRed = new QSpinBox(CameraSettingClass);
        spinBoxOffsetRed->setObjectName("spinBoxOffsetRed");
        spinBoxOffsetRed->setGeometry(QRect(100, 300, 61, 24));
        spinBoxOffsetRed->setMinimum(-255);
        spinBoxOffsetRed->setMaximum(255);
        spinBoxOffsetGreen = new QSpinBox(CameraSettingClass);
        spinBoxOffsetGreen->setObjectName("spinBoxOffsetGreen");
        spinBoxOffsetGreen->setGeometry(QRect(100, 360, 61, 24));
        spinBoxOffsetGreen->setMinimum(-255);
        spinBoxOffsetGreen->setMaximum(255);
        doubleSpinBoxGainGreen = new QDoubleSpinBox(CameraSettingClass);
        doubleSpinBoxGainGreen->setObjectName("doubleSpinBoxGainGreen");
        doubleSpinBoxGainGreen->setGeometry(QRect(80, 330, 81, 24));
        doubleSpinBoxGainGreen->setDecimals(5);
        doubleSpinBoxGainGreen->setMinimum(0.000240000000000);
        doubleSpinBoxGainGreen->setMaximum(5.516850000000000);
        spinBoxOffsetBlue = new QSpinBox(CameraSettingClass);
        spinBoxOffsetBlue->setObjectName("spinBoxOffsetBlue");
        spinBoxOffsetBlue->setGeometry(QRect(100, 420, 61, 24));
        spinBoxOffsetBlue->setMinimum(-255);
        spinBoxOffsetBlue->setMaximum(255);
        doubleSpinBoxGainBlue = new QDoubleSpinBox(CameraSettingClass);
        doubleSpinBoxGainBlue->setObjectName("doubleSpinBoxGainBlue");
        doubleSpinBoxGainBlue->setGeometry(QRect(80, 390, 81, 24));
        doubleSpinBoxGainBlue->setDecimals(5);
        doubleSpinBoxGainBlue->setMinimum(0.000240000000000);
        doubleSpinBoxGainBlue->setMaximum(5.516850000000000);
        spinBoxRedOffsetX = new QSpinBox(CameraSettingClass);
        spinBoxRedOffsetX->setObjectName("spinBoxRedOffsetX");
        spinBoxRedOffsetX->setGeometry(QRect(120, 490, 61, 24));
        spinBoxRedOffsetX->setMinimum(-100000);
        spinBoxRedOffsetX->setMaximum(100000);
        spinBoxBlueOffsetX = new QSpinBox(CameraSettingClass);
        spinBoxBlueOffsetX->setObjectName("spinBoxBlueOffsetX");
        spinBoxBlueOffsetX->setGeometry(QRect(120, 550, 61, 24));
        spinBoxBlueOffsetX->setMinimum(-100000);
        spinBoxBlueOffsetX->setMaximum(100000);
        label_521 = new QLabel(CameraSettingClass);
        label_521->setObjectName("label_521");
        label_521->setGeometry(QRect(20, 520, 41, 20));
        doubleSpinBoxBlueMultipleX = new QDoubleSpinBox(CameraSettingClass);
        doubleSpinBoxBlueMultipleX->setObjectName("doubleSpinBoxBlueMultipleX");
        doubleSpinBoxBlueMultipleX->setGeometry(QRect(60, 550, 61, 24));
        doubleSpinBoxBlueMultipleX->setDecimals(5);
        doubleSpinBoxBlueMultipleX->setMinimum(0.000240000000000);
        doubleSpinBoxBlueMultipleX->setMaximum(5.516850000000000);
        doubleSpinBoxBlueMultipleX->setValue(1.000000000000000);
        label_531 = new QLabel(CameraSettingClass);
        label_531->setObjectName("label_531");
        label_531->setGeometry(QRect(20, 490, 41, 20));
        label_541 = new QLabel(CameraSettingClass);
        label_541->setObjectName("label_541");
        label_541->setGeometry(QRect(120, 470, 51, 20));
        doubleSpinBoxGreenMultipleX = new QDoubleSpinBox(CameraSettingClass);
        doubleSpinBoxGreenMultipleX->setObjectName("doubleSpinBoxGreenMultipleX");
        doubleSpinBoxGreenMultipleX->setGeometry(QRect(60, 520, 61, 24));
        doubleSpinBoxGreenMultipleX->setDecimals(5);
        doubleSpinBoxGreenMultipleX->setMinimum(0.000240000000000);
        doubleSpinBoxGreenMultipleX->setMaximum(5.516850000000000);
        doubleSpinBoxGreenMultipleX->setValue(1.000000000000000);
        label_55 = new QLabel(CameraSettingClass);
        label_55->setObjectName("label_55");
        label_55->setGeometry(QRect(20, 550, 41, 20));
        label_56 = new QLabel(CameraSettingClass);
        label_56->setObjectName("label_56");
        label_56->setGeometry(QRect(60, 470, 61, 20));
        doubleSpinBoxRedMultipleX = new QDoubleSpinBox(CameraSettingClass);
        doubleSpinBoxRedMultipleX->setObjectName("doubleSpinBoxRedMultipleX");
        doubleSpinBoxRedMultipleX->setGeometry(QRect(60, 490, 61, 24));
        doubleSpinBoxRedMultipleX->setDecimals(5);
        doubleSpinBoxRedMultipleX->setMinimum(0.000240000000000);
        doubleSpinBoxRedMultipleX->setMaximum(5.516850000000000);
        doubleSpinBoxRedMultipleX->setValue(1.000000000000000);
        spinBoxGreenOffsetX = new QSpinBox(CameraSettingClass);
        spinBoxGreenOffsetX->setObjectName("spinBoxGreenOffsetX");
        spinBoxGreenOffsetX->setGeometry(QRect(120, 520, 61, 24));
        spinBoxGreenOffsetX->setMinimum(-100000);
        spinBoxGreenOffsetX->setMaximum(100000);
        spinBoxRedOffsetY = new QSpinBox(CameraSettingClass);
        spinBoxRedOffsetY->setObjectName("spinBoxRedOffsetY");
        spinBoxRedOffsetY->setGeometry(QRect(190, 490, 61, 24));
        spinBoxRedOffsetY->setMinimum(-100000);
        spinBoxRedOffsetY->setMaximum(100000);
        spinBoxGreenOffsetY = new QSpinBox(CameraSettingClass);
        spinBoxGreenOffsetY->setObjectName("spinBoxGreenOffsetY");
        spinBoxGreenOffsetY->setGeometry(QRect(190, 520, 61, 24));
        spinBoxGreenOffsetY->setMinimum(-100000);
        spinBoxGreenOffsetY->setMaximum(100000);
        spinBoxBlueOffsetY = new QSpinBox(CameraSettingClass);
        spinBoxBlueOffsetY->setObjectName("spinBoxBlueOffsetY");
        spinBoxBlueOffsetY->setGeometry(QRect(190, 550, 61, 24));
        spinBoxBlueOffsetY->setMinimum(-100000);
        spinBoxBlueOffsetY->setMaximum(100000);
        label_57 = new QLabel(CameraSettingClass);
        label_57->setObjectName("label_57");
        label_57->setGeometry(QRect(190, 470, 51, 20));
        label_58 = new QLabel(CameraSettingClass);
        label_58->setObjectName("label_58");
        label_58->setGeometry(QRect(180, 250, 61, 20));
        doubleSpinBoxGainGreenL = new QDoubleSpinBox(CameraSettingClass);
        doubleSpinBoxGainGreenL->setObjectName("doubleSpinBoxGainGreenL");
        doubleSpinBoxGainGreenL->setGeometry(QRect(170, 330, 81, 24));
        doubleSpinBoxGainGreenL->setDecimals(5);
        doubleSpinBoxGainGreenL->setMinimum(0.000240000000000);
        doubleSpinBoxGainGreenL->setMaximum(5.516850000000000);
        doubleSpinBoxGainRedL = new QDoubleSpinBox(CameraSettingClass);
        doubleSpinBoxGainRedL->setObjectName("doubleSpinBoxGainRedL");
        doubleSpinBoxGainRedL->setGeometry(QRect(170, 270, 81, 24));
        doubleSpinBoxGainRedL->setDecimals(5);
        doubleSpinBoxGainRedL->setMinimum(0.000240000000000);
        doubleSpinBoxGainRedL->setMaximum(5.516850000000000);
        doubleSpinBoxGainBlueL = new QDoubleSpinBox(CameraSettingClass);
        doubleSpinBoxGainBlueL->setObjectName("doubleSpinBoxGainBlueL");
        doubleSpinBoxGainBlueL->setGeometry(QRect(170, 390, 81, 24));
        doubleSpinBoxGainBlueL->setDecimals(5);
        doubleSpinBoxGainBlueL->setMinimum(0.000240000000000);
        doubleSpinBoxGainBlueL->setMaximum(5.516850000000000);
        label_59 = new QLabel(CameraSettingClass);
        label_59->setObjectName("label_59");
        label_59->setGeometry(QRect(270, 250, 61, 20));
        doubleSpinBoxGainBlueR = new QDoubleSpinBox(CameraSettingClass);
        doubleSpinBoxGainBlueR->setObjectName("doubleSpinBoxGainBlueR");
        doubleSpinBoxGainBlueR->setGeometry(QRect(260, 390, 81, 24));
        doubleSpinBoxGainBlueR->setDecimals(5);
        doubleSpinBoxGainBlueR->setMinimum(0.000240000000000);
        doubleSpinBoxGainBlueR->setMaximum(5.516850000000000);
        doubleSpinBoxGainRedR = new QDoubleSpinBox(CameraSettingClass);
        doubleSpinBoxGainRedR->setObjectName("doubleSpinBoxGainRedR");
        doubleSpinBoxGainRedR->setGeometry(QRect(260, 270, 81, 24));
        doubleSpinBoxGainRedR->setDecimals(5);
        doubleSpinBoxGainRedR->setMinimum(0.000240000000000);
        doubleSpinBoxGainRedR->setMaximum(5.516850000000000);
        doubleSpinBoxGainGreenR = new QDoubleSpinBox(CameraSettingClass);
        doubleSpinBoxGainGreenR->setObjectName("doubleSpinBoxGainGreenR");
        doubleSpinBoxGainGreenR->setGeometry(QRect(260, 330, 81, 24));
        doubleSpinBoxGainGreenR->setDecimals(5);
        doubleSpinBoxGainGreenR->setMinimum(0.000240000000000);
        doubleSpinBoxGainGreenR->setMaximum(5.516850000000000);
        label_60 = new QLabel(CameraSettingClass);
        label_60->setObjectName("label_60");
        label_60->setGeometry(QRect(30, 360, 61, 20));
        label_61 = new QLabel(CameraSettingClass);
        label_61->setObjectName("label_61");
        label_61->setGeometry(QRect(30, 420, 61, 20));
        spinBoxOffsetBlueL = new QSpinBox(CameraSettingClass);
        spinBoxOffsetBlueL->setObjectName("spinBoxOffsetBlueL");
        spinBoxOffsetBlueL->setGeometry(QRect(190, 420, 61, 24));
        spinBoxOffsetBlueL->setMinimum(-255);
        spinBoxOffsetBlueL->setMaximum(255);
        spinBoxOffsetGreenL = new QSpinBox(CameraSettingClass);
        spinBoxOffsetGreenL->setObjectName("spinBoxOffsetGreenL");
        spinBoxOffsetGreenL->setGeometry(QRect(190, 360, 61, 24));
        spinBoxOffsetGreenL->setMinimum(-255);
        spinBoxOffsetGreenL->setMaximum(255);
        spinBoxOffsetRedL = new QSpinBox(CameraSettingClass);
        spinBoxOffsetRedL->setObjectName("spinBoxOffsetRedL");
        spinBoxOffsetRedL->setGeometry(QRect(190, 300, 61, 24));
        spinBoxOffsetRedL->setMinimum(-255);
        spinBoxOffsetRedL->setMaximum(255);
        spinBoxOffsetBlueR = new QSpinBox(CameraSettingClass);
        spinBoxOffsetBlueR->setObjectName("spinBoxOffsetBlueR");
        spinBoxOffsetBlueR->setGeometry(QRect(280, 420, 61, 24));
        spinBoxOffsetBlueR->setMinimum(-255);
        spinBoxOffsetBlueR->setMaximum(255);
        spinBoxOffsetGreenR = new QSpinBox(CameraSettingClass);
        spinBoxOffsetGreenR->setObjectName("spinBoxOffsetGreenR");
        spinBoxOffsetGreenR->setGeometry(QRect(280, 360, 61, 24));
        spinBoxOffsetGreenR->setMinimum(-255);
        spinBoxOffsetGreenR->setMaximum(255);
        spinBoxOffsetRedR = new QSpinBox(CameraSettingClass);
        spinBoxOffsetRedR->setObjectName("spinBoxOffsetRedR");
        spinBoxOffsetRedR->setGeometry(QRect(280, 300, 61, 24));
        spinBoxOffsetRedR->setMinimum(-255);
        spinBoxOffsetRedR->setMaximum(255);
        label_62 = new QLabel(CameraSettingClass);
        label_62->setObjectName("label_62");
        label_62->setGeometry(QRect(20, 590, 161, 20));
        spinBoxHorizontalBinning = new QSpinBox(CameraSettingClass);
        spinBoxHorizontalBinning->setObjectName("spinBoxHorizontalBinning");
        spinBoxHorizontalBinning->setGeometry(QRect(180, 590, 61, 24));
        spinBoxHorizontalBinning->setMinimum(-255);
        spinBoxHorizontalBinning->setMaximum(255);
        spinBoxVerticalBinning = new QSpinBox(CameraSettingClass);
        spinBoxVerticalBinning->setObjectName("spinBoxVerticalBinning");
        spinBoxVerticalBinning->setGeometry(QRect(180, 620, 61, 24));
        spinBoxVerticalBinning->setMinimum(-255);
        spinBoxVerticalBinning->setMaximum(255);
        label_63 = new QLabel(CameraSettingClass);
        label_63->setObjectName("label_63");
        label_63->setGeometry(QRect(20, 620, 161, 20));
        checkBoxLeftRight = new QCheckBox(CameraSettingClass);
        checkBoxLeftRight->setObjectName("checkBoxLeftRight");
        checkBoxLeftRight->setGeometry(QRect(20, 220, 211, 21));
        checkBoxExternalTrigger = new QCheckBox(CameraSettingClass);
        checkBoxExternalTrigger->setObjectName("checkBoxExternalTrigger");
        checkBoxExternalTrigger->setGeometry(QRect(20, 700, 181, 21));
        checkBoxCameraControl = new QCheckBox(CameraSettingClass);
        checkBoxCameraControl->setObjectName("checkBoxCameraControl");
        checkBoxCameraControl->setGeometry(QRect(20, 70, 301, 22));
        checkBoxAutoBlackLevel = new QCheckBox(CameraSettingClass);
        checkBoxAutoBlackLevel->setObjectName("checkBoxAutoBlackLevel");
        checkBoxAutoBlackLevel->setGeometry(QRect(20, 730, 211, 21));
        checkBoxCalibrateFPN = new QCheckBox(CameraSettingClass);
        checkBoxCalibrateFPN->setObjectName("checkBoxCalibrateFPN");
        checkBoxCalibrateFPN->setGeometry(QRect(20, 760, 211, 21));
        label_64 = new QLabel(CameraSettingClass);
        label_64->setObjectName("label_64");
        label_64->setGeometry(QRect(20, 650, 161, 20));
        spinBoxROIOffset = new QSpinBox(CameraSettingClass);
        spinBoxROIOffset->setObjectName("spinBoxROIOffset");
        spinBoxROIOffset->setGeometry(QRect(180, 650, 61, 24));
        spinBoxROIOffset->setMinimum(0);
        spinBoxROIOffset->setMaximum(16384);
        label_65 = new QLabel(CameraSettingClass);
        label_65->setObjectName("label_65");
        label_65->setGeometry(QRect(250, 690, 151, 20));
        label_66 = new QLabel(CameraSettingClass);
        label_66->setObjectName("label_66");
        label_66->setGeometry(QRect(250, 730, 151, 20));
        spinBoxLightOffMilisec = new QSpinBox(CameraSettingClass);
        spinBoxLightOffMilisec->setObjectName("spinBoxLightOffMilisec");
        spinBoxLightOffMilisec->setGeometry(QRect(400, 690, 61, 24));
        spinBoxLightOffMilisec->setMinimum(0);
        spinBoxLightOffMilisec->setMaximum(1000000);
        spinBoxLightOnMilisec = new QSpinBox(CameraSettingClass);
        spinBoxLightOnMilisec->setObjectName("spinBoxLightOnMilisec");
        spinBoxLightOnMilisec->setGeometry(QRect(400, 730, 61, 24));
        spinBoxLightOnMilisec->setMinimum(0);
        spinBoxLightOnMilisec->setMaximum(1000000);

        retranslateUi(CameraSettingClass);
        QObject::connect(hsRedBrightness, &QSlider::valueChanged, lnRedBrightness, qOverload<int>(&QLCDNumber::display));
        QObject::connect(hsRedContrast, &QSlider::valueChanged, lnRedContrast, qOverload<int>(&QLCDNumber::display));
        QObject::connect(hsRedGamma, &QSlider::valueChanged, lnRedGamma, qOverload<int>(&QLCDNumber::display));
        QObject::connect(hsGreenBrightness, &QSlider::valueChanged, lnGreenBrightness, qOverload<int>(&QLCDNumber::display));
        QObject::connect(hsGreenContrast, &QSlider::valueChanged, lnGreenContrast, qOverload<int>(&QLCDNumber::display));
        QObject::connect(hsGreenGamma, &QSlider::valueChanged, lnGreenGamma, qOverload<int>(&QLCDNumber::display));
        QObject::connect(hsBlueBrightness, &QSlider::valueChanged, lnBlueBrightness, qOverload<int>(&QLCDNumber::display));
        QObject::connect(hsBlueContrast, &QSlider::valueChanged, lnBlueContrast, qOverload<int>(&QLCDNumber::display));
        QObject::connect(hsBlueGamma, &QSlider::valueChanged, lnBlueGamma, qOverload<int>(&QLCDNumber::display));

        tabRGB->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(CameraSettingClass);
    } // setupUi

    void retranslateUi(QDialog *CameraSettingClass)
    {
        CameraSettingClass->setWindowTitle(QCoreApplication::translate("CameraSettingClass", "Camera Setting", nullptr));
        pbCancel->setText(QCoreApplication::translate("CameraSettingClass", "Cancel", nullptr));
        label_43->setText(QCoreApplication::translate("CameraSettingClass", "Camera Type", nullptr));
        label->setText(QCoreApplication::translate("CameraSettingClass", "Line rate (Hz)", nullptr));
        label_45->setText(QCoreApplication::translate("CameraSettingClass", "Proof file", nullptr));
        pbOK->setText(QCoreApplication::translate("CameraSettingClass", "OK", nullptr));
        checkBoxDirection->setText(QCoreApplication::translate("CameraSettingClass", "TDI direction", nullptr));
        pbProof->setText(QCoreApplication::translate("CameraSettingClass", "...", nullptr));
        pbProofCancel->setText(QCoreApplication::translate("CameraSettingClass", "Cancel", nullptr));
        groupBox->setTitle(QCoreApplication::translate("CameraSettingClass", "LUT", nullptr));
        pbRedApply->setText(QCoreApplication::translate("CameraSettingClass", "Apply", nullptr));
        label_31->setText(QCoreApplication::translate("CameraSettingClass", "Contrast", nullptr));
        label_32->setText(QCoreApplication::translate("CameraSettingClass", "Gamma", nullptr));
        label_33->setText(QCoreApplication::translate("CameraSettingClass", "Floor", nullptr));
        label_34->setText(QCoreApplication::translate("CameraSettingClass", "Ceiling", nullptr));
        label_2->setText(QCoreApplication::translate("CameraSettingClass", "Brightness", nullptr));
        pbRedUpdate->setText(QCoreApplication::translate("CameraSettingClass", "Update", nullptr));
        label_10->setText(QCoreApplication::translate("CameraSettingClass", "Second Coordinates", nullptr));
        label_7->setText(QCoreApplication::translate("CameraSettingClass", "(", nullptr));
        label_9->setText(QCoreApplication::translate("CameraSettingClass", ")", nullptr));
        label_5->setText(QCoreApplication::translate("CameraSettingClass", "Second point", nullptr));
        label_51->setText(QCoreApplication::translate("CameraSettingClass", "First Coordinates", nullptr));
        label_52->setText(QCoreApplication::translate("CameraSettingClass", "(", nullptr));
        label_53->setText(QCoreApplication::translate("CameraSettingClass", "First point", nullptr));
        label_54->setText(QCoreApplication::translate("CameraSettingClass", ",", nullptr));
        label_6->setText(QCoreApplication::translate("CameraSettingClass", ")", nullptr));
        label_8->setText(QCoreApplication::translate("CameraSettingClass", ",", nullptr));
        cbRedGraphType->setItemText(0, QCoreApplication::translate("CameraSettingClass", "Default", nullptr));
        cbRedGraphType->setItemText(1, QCoreApplication::translate("CameraSettingClass", "Straight Line", nullptr));
        cbRedGraphType->setItemText(2, QCoreApplication::translate("CameraSettingClass", "Hight Pass", nullptr));
        cbRedGraphType->setItemText(3, QCoreApplication::translate("CameraSettingClass", "Low Pass", nullptr));
        cbRedGraphType->setItemText(4, QCoreApplication::translate("CameraSettingClass", "UpDown Pass", nullptr));
        cbRedGraphType->setItemText(5, QCoreApplication::translate("CameraSettingClass", "DownUp Pass", nullptr));
        cbRedGraphType->setItemText(6, QCoreApplication::translate("CameraSettingClass", "Shigmoid Curve", nullptr));
        cbRedGraphType->setItemText(7, QCoreApplication::translate("CameraSettingClass", "Logarithm", nullptr));

        tabRGB->setTabText(tabRGB->indexOf(tabRed), QCoreApplication::translate("CameraSettingClass", "Red", nullptr));
        pbGreenApply->setText(QCoreApplication::translate("CameraSettingClass", "Apply", nullptr));
        label_3->setText(QCoreApplication::translate("CameraSettingClass", "Brightness", nullptr));
        label_35->setText(QCoreApplication::translate("CameraSettingClass", "Contrast", nullptr));
        label_38->setText(QCoreApplication::translate("CameraSettingClass", "Gamma", nullptr));
        label_36->setText(QCoreApplication::translate("CameraSettingClass", "Floor", nullptr));
        label_37->setText(QCoreApplication::translate("CameraSettingClass", "Ceiling", nullptr));
        label_20->setText(QCoreApplication::translate("CameraSettingClass", "First Coordinates", nullptr));
        label_12->setText(QCoreApplication::translate("CameraSettingClass", "(", nullptr));
        label_19->setText(QCoreApplication::translate("CameraSettingClass", "Second Coordinates", nullptr));
        label_15->setText(QCoreApplication::translate("CameraSettingClass", "(", nullptr));
        pbGreenUpdate->setText(QCoreApplication::translate("CameraSettingClass", "Update", nullptr));
        label_16->setText(QCoreApplication::translate("CameraSettingClass", "Second point", nullptr));
        label_14->setText(QCoreApplication::translate("CameraSettingClass", ",", nullptr));
        label_18->setText(QCoreApplication::translate("CameraSettingClass", ")", nullptr));
        label_11->setText(QCoreApplication::translate("CameraSettingClass", "First point", nullptr));
        label_13->setText(QCoreApplication::translate("CameraSettingClass", ",", nullptr));
        label_17->setText(QCoreApplication::translate("CameraSettingClass", ")", nullptr));
        cbGreenGraphType->setItemText(0, QCoreApplication::translate("CameraSettingClass", "Default", nullptr));
        cbGreenGraphType->setItemText(1, QCoreApplication::translate("CameraSettingClass", "Straight Line", nullptr));
        cbGreenGraphType->setItemText(2, QCoreApplication::translate("CameraSettingClass", "Hight Pass", nullptr));
        cbGreenGraphType->setItemText(3, QCoreApplication::translate("CameraSettingClass", "Low Pass", nullptr));
        cbGreenGraphType->setItemText(4, QCoreApplication::translate("CameraSettingClass", "UpDown Pass", nullptr));
        cbGreenGraphType->setItemText(5, QCoreApplication::translate("CameraSettingClass", "DownUp Pass", nullptr));
        cbGreenGraphType->setItemText(6, QCoreApplication::translate("CameraSettingClass", "Shigmoid Curve", nullptr));
        cbGreenGraphType->setItemText(7, QCoreApplication::translate("CameraSettingClass", "Logarithm", nullptr));

        tabRGB->setTabText(tabRGB->indexOf(tabGreen), QCoreApplication::translate("CameraSettingClass", "Green", nullptr));
        pbBlueApply->setText(QCoreApplication::translate("CameraSettingClass", "Apply", nullptr));
        label_39->setText(QCoreApplication::translate("CameraSettingClass", "Ceiling", nullptr));
        label_40->setText(QCoreApplication::translate("CameraSettingClass", "Gamma", nullptr));
        label_41->setText(QCoreApplication::translate("CameraSettingClass", "Contrast", nullptr));
        label_42->setText(QCoreApplication::translate("CameraSettingClass", "Floor", nullptr));
        label_4->setText(QCoreApplication::translate("CameraSettingClass", "Brightness", nullptr));
        label_25->setText(QCoreApplication::translate("CameraSettingClass", "Second point", nullptr));
        label_21->setText(QCoreApplication::translate("CameraSettingClass", "First Coordinates", nullptr));
        label_28->setText(QCoreApplication::translate("CameraSettingClass", "(", nullptr));
        label_29->setText(QCoreApplication::translate("CameraSettingClass", "Second Coordinates", nullptr));
        label_27->setText(QCoreApplication::translate("CameraSettingClass", "(", nullptr));
        pbBlueUpdate->setText(QCoreApplication::translate("CameraSettingClass", "Update", nullptr));
        label_23->setText(QCoreApplication::translate("CameraSettingClass", "First point", nullptr));
        label_22->setText(QCoreApplication::translate("CameraSettingClass", ",", nullptr));
        label_26->setText(QCoreApplication::translate("CameraSettingClass", ")", nullptr));
        label_24->setText(QCoreApplication::translate("CameraSettingClass", ",", nullptr));
        label_30->setText(QCoreApplication::translate("CameraSettingClass", ")", nullptr));
        cbBlueGraphType->setItemText(0, QCoreApplication::translate("CameraSettingClass", "Default", nullptr));
        cbBlueGraphType->setItemText(1, QCoreApplication::translate("CameraSettingClass", "Straight Line", nullptr));
        cbBlueGraphType->setItemText(2, QCoreApplication::translate("CameraSettingClass", "Hight Pass", nullptr));
        cbBlueGraphType->setItemText(3, QCoreApplication::translate("CameraSettingClass", "Low Pass", nullptr));
        cbBlueGraphType->setItemText(4, QCoreApplication::translate("CameraSettingClass", "UpDown Pass", nullptr));
        cbBlueGraphType->setItemText(5, QCoreApplication::translate("CameraSettingClass", "DownUp Pass", nullptr));
        cbBlueGraphType->setItemText(6, QCoreApplication::translate("CameraSettingClass", "Shigmoid Curve", nullptr));
        cbBlueGraphType->setItemText(7, QCoreApplication::translate("CameraSettingClass", "Logarithm", nullptr));

        tabRGB->setTabText(tabRGB->indexOf(tabBlue), QCoreApplication::translate("CameraSettingClass", "Blue", nullptr));
        label_46->setText(QCoreApplication::translate("CameraSettingClass", "Exposure time(micro sec)", nullptr));
        label_47->setText(QCoreApplication::translate("CameraSettingClass", "Gain", nullptr));
        label_48->setText(QCoreApplication::translate("CameraSettingClass", "Offset", nullptr));
        label_49->setText(QCoreApplication::translate("CameraSettingClass", "Red", nullptr));
        label_50->setText(QCoreApplication::translate("CameraSettingClass", "Green", nullptr));
        label_511->setText(QCoreApplication::translate("CameraSettingClass", "Blue", nullptr));
        label_521->setText(QCoreApplication::translate("CameraSettingClass", "Green", nullptr));
        label_531->setText(QCoreApplication::translate("CameraSettingClass", "Red", nullptr));
        label_541->setText(QCoreApplication::translate("CameraSettingClass", "X offset", nullptr));
        label_55->setText(QCoreApplication::translate("CameraSettingClass", "Blue", nullptr));
        label_56->setText(QCoreApplication::translate("CameraSettingClass", "X multiple", nullptr));
        label_57->setText(QCoreApplication::translate("CameraSettingClass", "Y offset", nullptr));
        label_58->setText(QCoreApplication::translate("CameraSettingClass", "LGain", nullptr));
        label_59->setText(QCoreApplication::translate("CameraSettingClass", "RGain", nullptr));
        label_60->setText(QCoreApplication::translate("CameraSettingClass", "Offset", nullptr));
        label_61->setText(QCoreApplication::translate("CameraSettingClass", "Offset", nullptr));
        label_62->setText(QCoreApplication::translate("CameraSettingClass", "Binning Horizontal", nullptr));
        label_63->setText(QCoreApplication::translate("CameraSettingClass", "Binning Vertical", nullptr));
        checkBoxLeftRight->setText(QCoreApplication::translate("CameraSettingClass", "Reverse lefr-right", nullptr));
        checkBoxExternalTrigger->setText(QCoreApplication::translate("CameraSettingClass", "External Trigger", nullptr));
        checkBoxCameraControl->setText(QCoreApplication::translate("CameraSettingClass", "Camera control", nullptr));
        checkBoxAutoBlackLevel->setText(QCoreApplication::translate("CameraSettingClass", "Auto BlackLevel", nullptr));
        checkBoxCalibrateFPN->setText(QCoreApplication::translate("CameraSettingClass", "Calibrate FPN at start", nullptr));
        label_64->setText(QCoreApplication::translate("CameraSettingClass", "ROI Offset", nullptr));
        label_65->setText(QCoreApplication::translate("CameraSettingClass", "\347\205\247\346\230\216OFF\344\277\241\345\217\267\345\276\205\346\251\237\346\231\202\351\226\223(\343\203\237\343\203\252\347\247\222\357\274\211", nullptr));
        label_66->setText(QCoreApplication::translate("CameraSettingClass", "\347\205\247\346\230\216ON\344\277\241\345\217\267\345\276\205\346\251\237\346\231\202\351\226\223\357\274\210\343\203\237\343\203\252\347\247\222)", nullptr));
    } // retranslateUi

};

namespace Ui {
    class CameraSettingClass: public Ui_CameraSettingClass {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_CAMERASETTING_H
