#ifndef CATEGORIZEDSHADERIMAGEPANEL_GLOBAL_H
#define CATEGORIZEDSHADERIMAGEPANEL_GLOBAL_H

#include <qglobal.h>

#ifdef CATEGORIZEDSHADERIMAGEPANEL_LIB
# define CATEGORIZEDSHADERIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define CATEGORIZEDSHADERIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // CATEGORIZEDSHADERIMAGEPANEL_GLOBAL_H
