#ifndef LISTSTATISTICNG_GLOBAL_H
#define LISTSTATISTICNG_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef LISTSTATISTICNG_LIB
# define LISTSTATISTICNG_EXPORT Q_DECL_EXPORT
#else
# define LISTSTATISTICNG_EXPORT Q_DECL_IMPORT
#endif

#endif // LISTSTATISTICNG_GLOBAL_H
