#ifndef MATCHSHIFTROTATIONIMAGEPANEL_GLOBAL_H
#define MATCHSHIFTROTATIONIMAGEPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef MATCHSHIFTROTATIONIMAGEPANEL_LIB
# define MATCHSHIFTROTATIONIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define MATCHSHIFTROTATIONIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // MATCHSHIFTROTATIONIMAGEPANEL_GLOBAL_H
