#ifndef VCUTINSPECTION_GLOBAL_H
#define VCUTINSPECTION_GLOBAL_H

#include <qglobal.h>

#ifdef VCUTINSPECTION_LIB
# define VCUTINSPECTION_EXPORT Q_DECL_EXPORT
#else
# define VCUTINSPECTION_EXPORT Q_DECL_IMPORT
#endif

#endif // VCUTINSPECTION_GLOBAL_H
