/********************************************************************************
** Form generated from reading UI file 'ShowOperationalPanel.ui'
**
** Created by: Qt User Interface Compiler version 6.10.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_SHOWOPERATIONALPANEL_H
#define UI_SHOWOPERATIONALPANEL_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QListWidget>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QToolButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_ShowOperationalPanel
{
public:
    QToolButton *toolButtonSimShowNGMark;
    QToolButton *toolButtonSimShowOutside;
    QLineEdit *EditItemName;
    QLabel *label_3;
    QTabWidget *tabWidgetInspect;
    QWidget *tab_6;
    QLabel *labelUnitName_8;
    QFrame *frame_6;
    QLabel *label_35;
    QLabel *label_20;
    QLabel *label_21;
    QSpinBox *EditNGSizeIH;
    QLabel *label_22;
    QSpinBox *EditBrightWidthIL;
    QSpinBox *EditNGSizeIL;
    QSpinBox *EditBrightWidthIH;
    QLabel *label_23;
    QFrame *frame_7;
    QLabel *label_37;
    QLabel *label_24;
    QSpinBox *EditNGSizeOH;
    QLabel *label_28;
    QSpinBox *EditNGSizeOL;
    QSpinBox *EditBrightWidthOL;
    QLabel *label_29;
    QLabel *label_30;
    QSpinBox *EditBrightWidthOH;
    QWidget *tab_7;
    QCheckBox *checkBModeAbsoluteBright;
    QCheckBox *checkBModeDynamicMask;
    QCheckBox *checkBModeEnabled;
    QCheckBox *checkBModeCenterBrightFromParts;
    QWidget *tab_8;
    QLabel *label_26;
    QSpinBox *EditAdjustBrightIH;
    QSpinBox *EditAdjustBrightOH;
    QLabel *label_25;
    QSpinBox *EditAdjustBrightOL;
    QLabel *label_34;
    QSpinBox *EditAdjustBrightIL;
    QLabel *label_33;
    QWidget *tab;
    QSpinBox *EditRegulatedColO;
    QLabel *label_38;
    QSpinBox *EditRegulatedColI;
    QLabel *label_39;
    QCheckBox *checkBModeUseRegularBrightness;
    QWidget *Search;
    QLabel *label_27;
    QLabel *label_36;
    QSpinBox *EditSearchDot;
    QSpinBox *EditGlobalSearchDot;
    QWidget *tab_2;
    QLabel *label_32;
    QSpinBox *EditTransitDot;
    QLabel *label_45;
    QSpinBox *EditAngleNumb;
    QLabel *label;
    QLineEdit *EditLibID;
    QFrame *frame_SimImage;
    QLabel *label_7;
    QFrame *frame;
    QLabel *label_31;
    QPushButton *ButtonCalc;
    QLabel *labelUnitName_11;
    QLabel *labelResultIL;
    QLabel *label_11;
    QLabel *labelResultILUnit;
    QLabel *labelUnitName_12;
    QLabel *labelResultIH;
    QLabel *labelResultIHUnit;
    QLabel *label_14;
    QLabel *labelUnitName_13;
    QLabel *labelResultOL;
    QLabel *labelResultOLUnit;
    QLabel *label_15;
    QLabel *labelUnitName_14;
    QLabel *labelResultOH;
    QLabel *labelResultOHUnit;
    QLabel *label_16;
    QLabel *label_17;
    QComboBox *comboBoxAngleNumber;
    QLabel *labelResultAngleNumber;
    QLabel *label_6;
    QFrame *frameMaster;
    QLabel *label_8;
    QFrame *frameLayer;
    QListWidget *listWidgetHistList;
    QLabel *label_9;
    QToolButton *toolButtonSimShowArea;
    QPushButton *ButtonSaveToLibrary;
    QPushButton *pushButtonTransmitItemNameAll;
    QGroupBox *groupBox;
    QRadioButton *radioButtonLightSide1;
    QRadioButton *radioButtonDarkSide1;
    QLabel *label_40;
    QPushButton *ButtonLoadFromLibrary;
    QFrame *frameThreshold;
    QLabel *label_4;
    QPushButton *ButtonRelrectOnlyBlock;
    QPushButton *ButtonReflectAllBlocks;
    QLabel *label_5;
    QPushButton *pushButtonChangeLib;
    QToolButton *toolButtonSimShowInside;
    QLineEdit *EditLibName;
    QPushButton *ButtonClose;
    QFrame *frameLineGraphI;
    QPushButton *pushButtonSimShowCenterPos;
    QFrame *frameTarget;
    QFrame *frameLineGraphO;
    QLabel *label_12;
    QLabel *label_13;
    QLineEdit *EditMasterColI;
    QLabel *label_41;
    QLabel *label_42;
    QLineEdit *EditTargetColI;
    QLabel *label_43;
    QLineEdit *EditMasterColO;
    QLabel *label_44;
    QLineEdit *EditTargetColO;
    QTableWidget *tableWidgetShift;

    void setupUi(QWidget *ShowOperationalPanel)
    {
        if (ShowOperationalPanel->objectName().isEmpty())
            ShowOperationalPanel->setObjectName("ShowOperationalPanel");
        ShowOperationalPanel->resize(1293, 730);
        toolButtonSimShowNGMark = new QToolButton(ShowOperationalPanel);
        toolButtonSimShowNGMark->setObjectName("toolButtonSimShowNGMark");
        toolButtonSimShowNGMark->setGeometry(QRect(970, 20, 141, 41));
        toolButtonSimShowNGMark->setCheckable(true);
        toolButtonSimShowNGMark->setChecked(true);
        toolButtonSimShowOutside = new QToolButton(ShowOperationalPanel);
        toolButtonSimShowOutside->setObjectName("toolButtonSimShowOutside");
        toolButtonSimShowOutside->setGeometry(QRect(970, 60, 141, 41));
        toolButtonSimShowOutside->setCheckable(true);
        toolButtonSimShowOutside->setChecked(true);
        EditItemName = new QLineEdit(ShowOperationalPanel);
        EditItemName->setObjectName("EditItemName");
        EditItemName->setGeometry(QRect(20, 460, 141, 21));
        EditItemName->setReadOnly(false);
        label_3 = new QLabel(ShowOperationalPanel);
        label_3->setObjectName("label_3");
        label_3->setGeometry(QRect(190, 5, 131, 21));
        tabWidgetInspect = new QTabWidget(ShowOperationalPanel);
        tabWidgetInspect->setObjectName("tabWidgetInspect");
        tabWidgetInspect->setGeometry(QRect(240, 410, 331, 201));
        tab_6 = new QWidget();
        tab_6->setObjectName("tab_6");
        labelUnitName_8 = new QLabel(tab_6);
        labelUnitName_8->setObjectName("labelUnitName_8");
        labelUnitName_8->setGeometry(QRect(320, 60, 61, 20));
        labelUnitName_8->setFrameShape(QFrame::NoFrame);
        labelUnitName_8->setFrameShadow(QFrame::Sunken);
        labelUnitName_8->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        frame_6 = new QFrame(tab_6);
        frame_6->setObjectName("frame_6");
        frame_6->setGeometry(QRect(10, 4, 311, 81));
        frame_6->setFrameShape(QFrame::StyledPanel);
        frame_6->setFrameShadow(QFrame::Sunken);
        label_35 = new QLabel(frame_6);
        label_35->setObjectName("label_35");
        label_35->setGeometry(QRect(0, 0, 31, 81));
        label_35->setFrameShape(QFrame::Panel);
        label_35->setFrameShadow(QFrame::Raised);
        label_35->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_35->setIndent(1);
        label_20 = new QLabel(frame_6);
        label_20->setObjectName("label_20");
        label_20->setGeometry(QRect(230, 10, 72, 21));
        label_20->setFrameShape(QFrame::Panel);
        label_20->setFrameShadow(QFrame::Sunken);
        label_20->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_21 = new QLabel(frame_6);
        label_21->setObjectName("label_21");
        label_21->setGeometry(QRect(36, 28, 121, 21));
        label_21->setFrameShape(QFrame::Panel);
        label_21->setFrameShadow(QFrame::Sunken);
        label_21->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditNGSizeIH = new QSpinBox(frame_6);
        EditNGSizeIH->setObjectName("EditNGSizeIH");
        EditNGSizeIH->setGeometry(QRect(230, 50, 72, 22));
        EditNGSizeIH->setMaximum(99999999);
        label_22 = new QLabel(frame_6);
        label_22->setObjectName("label_22");
        label_22->setGeometry(QRect(36, 48, 121, 21));
        label_22->setFrameShape(QFrame::Panel);
        label_22->setFrameShadow(QFrame::Sunken);
        label_22->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditBrightWidthIL = new QSpinBox(frame_6);
        EditBrightWidthIL->setObjectName("EditBrightWidthIL");
        EditBrightWidthIL->setGeometry(QRect(162, 30, 72, 22));
        EditBrightWidthIL->setMaximum(255);
        EditNGSizeIL = new QSpinBox(frame_6);
        EditNGSizeIL->setObjectName("EditNGSizeIL");
        EditNGSizeIL->setGeometry(QRect(162, 50, 72, 22));
        EditNGSizeIL->setMaximum(99999999);
        EditBrightWidthIH = new QSpinBox(frame_6);
        EditBrightWidthIH->setObjectName("EditBrightWidthIH");
        EditBrightWidthIH->setGeometry(QRect(230, 30, 72, 22));
        EditBrightWidthIH->setMaximum(255);
        label_23 = new QLabel(frame_6);
        label_23->setObjectName("label_23");
        label_23->setGeometry(QRect(162, 10, 72, 21));
        label_23->setFrameShape(QFrame::Panel);
        label_23->setFrameShadow(QFrame::Sunken);
        label_23->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        frame_7 = new QFrame(tab_6);
        frame_7->setObjectName("frame_7");
        frame_7->setGeometry(QRect(10, 90, 311, 81));
        frame_7->setFrameShape(QFrame::StyledPanel);
        frame_7->setFrameShadow(QFrame::Sunken);
        label_37 = new QLabel(frame_7);
        label_37->setObjectName("label_37");
        label_37->setGeometry(QRect(0, 0, 31, 81));
        label_37->setFrameShape(QFrame::Panel);
        label_37->setFrameShadow(QFrame::Raised);
        label_37->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_37->setIndent(1);
        label_24 = new QLabel(frame_7);
        label_24->setObjectName("label_24");
        label_24->setGeometry(QRect(36, 30, 121, 21));
        label_24->setFrameShape(QFrame::Panel);
        label_24->setFrameShadow(QFrame::Sunken);
        label_24->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditNGSizeOH = new QSpinBox(frame_7);
        EditNGSizeOH->setObjectName("EditNGSizeOH");
        EditNGSizeOH->setGeometry(QRect(230, 50, 72, 22));
        EditNGSizeOH->setMaximum(99999999);
        label_28 = new QLabel(frame_7);
        label_28->setObjectName("label_28");
        label_28->setGeometry(QRect(230, 10, 72, 21));
        label_28->setFrameShape(QFrame::Panel);
        label_28->setFrameShadow(QFrame::Sunken);
        label_28->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditNGSizeOL = new QSpinBox(frame_7);
        EditNGSizeOL->setObjectName("EditNGSizeOL");
        EditNGSizeOL->setGeometry(QRect(160, 50, 72, 22));
        EditNGSizeOL->setMaximum(99999999);
        EditBrightWidthOL = new QSpinBox(frame_7);
        EditBrightWidthOL->setObjectName("EditBrightWidthOL");
        EditBrightWidthOL->setGeometry(QRect(160, 30, 72, 22));
        EditBrightWidthOL->setMaximum(255);
        label_29 = new QLabel(frame_7);
        label_29->setObjectName("label_29");
        label_29->setGeometry(QRect(36, 50, 121, 21));
        label_29->setFrameShape(QFrame::Panel);
        label_29->setFrameShadow(QFrame::Sunken);
        label_29->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_30 = new QLabel(frame_7);
        label_30->setObjectName("label_30");
        label_30->setGeometry(QRect(160, 10, 72, 21));
        label_30->setFrameShape(QFrame::Panel);
        label_30->setFrameShadow(QFrame::Sunken);
        label_30->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditBrightWidthOH = new QSpinBox(frame_7);
        EditBrightWidthOH->setObjectName("EditBrightWidthOH");
        EditBrightWidthOH->setGeometry(QRect(230, 30, 72, 22));
        EditBrightWidthOH->setMaximum(255);
        tabWidgetInspect->addTab(tab_6, QString());
        tab_7 = new QWidget();
        tab_7->setObjectName("tab_7");
        checkBModeAbsoluteBright = new QCheckBox(tab_7);
        checkBModeAbsoluteBright->setObjectName("checkBModeAbsoluteBright");
        checkBModeAbsoluteBright->setGeometry(QRect(10, 40, 161, 18));
        checkBModeDynamicMask = new QCheckBox(tab_7);
        checkBModeDynamicMask->setObjectName("checkBModeDynamicMask");
        checkBModeDynamicMask->setGeometry(QRect(10, 80, 191, 18));
        checkBModeEnabled = new QCheckBox(tab_7);
        checkBModeEnabled->setObjectName("checkBModeEnabled");
        checkBModeEnabled->setGeometry(QRect(10, 20, 161, 18));
        checkBModeCenterBrightFromParts = new QCheckBox(tab_7);
        checkBModeCenterBrightFromParts->setObjectName("checkBModeCenterBrightFromParts");
        checkBModeCenterBrightFromParts->setGeometry(QRect(10, 60, 191, 18));
        tabWidgetInspect->addTab(tab_7, QString());
        tab_8 = new QWidget();
        tab_8->setObjectName("tab_8");
        label_26 = new QLabel(tab_8);
        label_26->setObjectName("label_26");
        label_26->setGeometry(QRect(10, 30, 250, 21));
        label_26->setFrameShape(QFrame::Panel);
        label_26->setFrameShadow(QFrame::Sunken);
        label_26->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditAdjustBrightIH = new QSpinBox(tab_8);
        EditAdjustBrightIH->setObjectName("EditAdjustBrightIH");
        EditAdjustBrightIH->setGeometry(QRect(260, 30, 64, 22));
        EditAdjustBrightIH->setMaximum(255);
        EditAdjustBrightOH = new QSpinBox(tab_8);
        EditAdjustBrightOH->setObjectName("EditAdjustBrightOH");
        EditAdjustBrightOH->setGeometry(QRect(260, 80, 64, 22));
        EditAdjustBrightOH->setMaximum(255);
        label_25 = new QLabel(tab_8);
        label_25->setObjectName("label_25");
        label_25->setGeometry(QRect(10, 10, 250, 21));
        label_25->setFrameShape(QFrame::Panel);
        label_25->setFrameShadow(QFrame::Sunken);
        label_25->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditAdjustBrightOL = new QSpinBox(tab_8);
        EditAdjustBrightOL->setObjectName("EditAdjustBrightOL");
        EditAdjustBrightOL->setGeometry(QRect(260, 60, 64, 22));
        EditAdjustBrightOL->setMaximum(255);
        label_34 = new QLabel(tab_8);
        label_34->setObjectName("label_34");
        label_34->setGeometry(QRect(10, 80, 250, 21));
        label_34->setFrameShape(QFrame::Panel);
        label_34->setFrameShadow(QFrame::Sunken);
        label_34->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditAdjustBrightIL = new QSpinBox(tab_8);
        EditAdjustBrightIL->setObjectName("EditAdjustBrightIL");
        EditAdjustBrightIL->setGeometry(QRect(260, 10, 64, 22));
        EditAdjustBrightIL->setMaximum(255);
        label_33 = new QLabel(tab_8);
        label_33->setObjectName("label_33");
        label_33->setGeometry(QRect(10, 60, 250, 21));
        label_33->setFrameShape(QFrame::Panel);
        label_33->setFrameShadow(QFrame::Sunken);
        label_33->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        tabWidgetInspect->addTab(tab_8, QString());
        tab = new QWidget();
        tab->setObjectName("tab");
        EditRegulatedColO = new QSpinBox(tab);
        EditRegulatedColO->setObjectName("EditRegulatedColO");
        EditRegulatedColO->setGeometry(QRect(90, 80, 81, 22));
        EditRegulatedColO->setMaximum(255);
        label_38 = new QLabel(tab);
        label_38->setObjectName("label_38");
        label_38->setGeometry(QRect(8, 50, 81, 21));
        label_38->setFrameShape(QFrame::Panel);
        label_38->setFrameShadow(QFrame::Sunken);
        label_38->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditRegulatedColI = new QSpinBox(tab);
        EditRegulatedColI->setObjectName("EditRegulatedColI");
        EditRegulatedColI->setGeometry(QRect(90, 50, 81, 22));
        EditRegulatedColI->setMaximum(255);
        label_39 = new QLabel(tab);
        label_39->setObjectName("label_39");
        label_39->setGeometry(QRect(8, 80, 81, 21));
        label_39->setFrameShape(QFrame::Panel);
        label_39->setFrameShadow(QFrame::Sunken);
        label_39->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        checkBModeUseRegularBrightness = new QCheckBox(tab);
        checkBModeUseRegularBrightness->setObjectName("checkBModeUseRegularBrightness");
        checkBModeUseRegularBrightness->setGeometry(QRect(10, 20, 311, 18));
        tabWidgetInspect->addTab(tab, QString());
        Search = new QWidget();
        Search->setObjectName("Search");
        label_27 = new QLabel(Search);
        label_27->setObjectName("label_27");
        label_27->setGeometry(QRect(0, 20, 250, 21));
        label_27->setFrameShape(QFrame::Panel);
        label_27->setFrameShadow(QFrame::Sunken);
        label_27->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_36 = new QLabel(Search);
        label_36->setObjectName("label_36");
        label_36->setGeometry(QRect(0, 40, 250, 21));
        label_36->setFrameShape(QFrame::Panel);
        label_36->setFrameShadow(QFrame::Sunken);
        label_36->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditSearchDot = new QSpinBox(Search);
        EditSearchDot->setObjectName("EditSearchDot");
        EditSearchDot->setGeometry(QRect(250, 20, 64, 22));
        EditGlobalSearchDot = new QSpinBox(Search);
        EditGlobalSearchDot->setObjectName("EditGlobalSearchDot");
        EditGlobalSearchDot->setGeometry(QRect(250, 40, 64, 22));
        EditGlobalSearchDot->setMaximum(9999);
        tabWidgetInspect->addTab(Search, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName("tab_2");
        label_32 = new QLabel(tab_2);
        label_32->setObjectName("label_32");
        label_32->setGeometry(QRect(10, 80, 211, 21));
        label_32->setFrameShape(QFrame::Panel);
        label_32->setFrameShadow(QFrame::Sunken);
        label_32->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditTransitDot = new QSpinBox(tab_2);
        EditTransitDot->setObjectName("EditTransitDot");
        EditTransitDot->setGeometry(QRect(230, 80, 81, 22));
        EditTransitDot->setMaximum(255);
        label_45 = new QLabel(tab_2);
        label_45->setObjectName("label_45");
        label_45->setGeometry(QRect(10, 110, 211, 21));
        label_45->setFrameShape(QFrame::Panel);
        label_45->setFrameShadow(QFrame::Sunken);
        label_45->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditAngleNumb = new QSpinBox(tab_2);
        EditAngleNumb->setObjectName("EditAngleNumb");
        EditAngleNumb->setGeometry(QRect(230, 110, 81, 22));
        EditAngleNumb->setMaximum(255);
        label = new QLabel(tab_2);
        label->setObjectName("label");
        label->setGeometry(QRect(10, 20, 301, 41));
        label->setWordWrap(true);
        tabWidgetInspect->addTab(tab_2, QString());
        EditLibID = new QLineEdit(ShowOperationalPanel);
        EditLibID->setObjectName("EditLibID");
        EditLibID->setGeometry(QRect(20, 510, 61, 21));
        EditLibID->setReadOnly(true);
        frame_SimImage = new QFrame(ShowOperationalPanel);
        frame_SimImage->setObjectName("frame_SimImage");
        frame_SimImage->setGeometry(QRect(820, 110, 461, 411));
        frame_SimImage->setFrameShape(QFrame::StyledPanel);
        frame_SimImage->setFrameShadow(QFrame::Sunken);
        label_7 = new QLabel(ShowOperationalPanel);
        label_7->setObjectName("label_7");
        label_7->setGeometry(QRect(360, 5, 131, 21));
        frame = new QFrame(ShowOperationalPanel);
        frame->setObjectName("frame");
        frame->setGeometry(QRect(580, 410, 211, 311));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Sunken);
        label_31 = new QLabel(frame);
        label_31->setObjectName("label_31");
        label_31->setGeometry(QRect(0, 0, 201, 21));
        label_31->setFrameShape(QFrame::Panel);
        label_31->setFrameShadow(QFrame::Sunken);
        label_31->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        ButtonCalc = new QPushButton(frame);
        ButtonCalc->setObjectName("ButtonCalc");
        ButtonCalc->setGeometry(QRect(50, 280, 121, 31));
        ButtonCalc->setAcceptDrops(true);
        labelUnitName_11 = new QLabel(frame);
        labelUnitName_11->setObjectName("labelUnitName_11");
        labelUnitName_11->setGeometry(QRect(10, 50, 51, 20));
        labelUnitName_11->setFrameShape(QFrame::NoFrame);
        labelUnitName_11->setFrameShadow(QFrame::Sunken);
        labelUnitName_11->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        labelResultIL = new QLabel(frame);
        labelResultIL->setObjectName("labelResultIL");
        labelResultIL->setGeometry(QRect(120, 30, 81, 21));
        labelResultIL->setFrameShape(QFrame::Panel);
        labelResultIL->setFrameShadow(QFrame::Sunken);
        labelResultIL->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_11 = new QLabel(frame);
        label_11->setObjectName("label_11");
        label_11->setGeometry(QRect(10, 30, 111, 21));
        label_11->setFrameShape(QFrame::Panel);
        label_11->setFrameShadow(QFrame::Sunken);
        label_11->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        labelResultILUnit = new QLabel(frame);
        labelResultILUnit->setObjectName("labelResultILUnit");
        labelResultILUnit->setEnabled(false);
        labelResultILUnit->setGeometry(QRect(120, 50, 81, 21));
        QPalette palette;
        QBrush brush(QColor(255, 255, 127, 255));
        brush.setStyle(Qt::BrushStyle::SolidPattern);
        palette.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush);
        QBrush brush1(QColor(255, 170, 0, 255));
        brush1.setStyle(Qt::BrushStyle::SolidPattern);
        palette.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Window, brush1);
        palette.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush);
        palette.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Window, brush1);
        palette.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush1);
        palette.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Window, brush1);
        labelResultILUnit->setPalette(palette);
        labelResultILUnit->setAutoFillBackground(true);
        labelResultILUnit->setFrameShape(QFrame::Panel);
        labelResultILUnit->setFrameShadow(QFrame::Sunken);
        labelResultILUnit->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        labelUnitName_12 = new QLabel(frame);
        labelUnitName_12->setObjectName("labelUnitName_12");
        labelUnitName_12->setGeometry(QRect(10, 100, 51, 20));
        labelUnitName_12->setFrameShape(QFrame::NoFrame);
        labelUnitName_12->setFrameShadow(QFrame::Sunken);
        labelUnitName_12->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        labelResultIH = new QLabel(frame);
        labelResultIH->setObjectName("labelResultIH");
        labelResultIH->setGeometry(QRect(120, 80, 81, 21));
        labelResultIH->setFrameShape(QFrame::Panel);
        labelResultIH->setFrameShadow(QFrame::Sunken);
        labelResultIH->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        labelResultIHUnit = new QLabel(frame);
        labelResultIHUnit->setObjectName("labelResultIHUnit");
        labelResultIHUnit->setEnabled(false);
        labelResultIHUnit->setGeometry(QRect(120, 100, 81, 21));
        QPalette palette1;
        palette1.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush);
        palette1.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Window, brush1);
        palette1.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush);
        palette1.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Window, brush1);
        palette1.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush1);
        palette1.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Window, brush1);
        labelResultIHUnit->setPalette(palette1);
        labelResultIHUnit->setAutoFillBackground(true);
        labelResultIHUnit->setFrameShape(QFrame::Panel);
        labelResultIHUnit->setFrameShadow(QFrame::Sunken);
        labelResultIHUnit->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_14 = new QLabel(frame);
        label_14->setObjectName("label_14");
        label_14->setGeometry(QRect(10, 80, 111, 21));
        label_14->setFrameShape(QFrame::Panel);
        label_14->setFrameShadow(QFrame::Sunken);
        label_14->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        labelUnitName_13 = new QLabel(frame);
        labelUnitName_13->setObjectName("labelUnitName_13");
        labelUnitName_13->setGeometry(QRect(10, 150, 51, 20));
        labelUnitName_13->setFrameShape(QFrame::NoFrame);
        labelUnitName_13->setFrameShadow(QFrame::Sunken);
        labelUnitName_13->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        labelResultOL = new QLabel(frame);
        labelResultOL->setObjectName("labelResultOL");
        labelResultOL->setGeometry(QRect(120, 130, 81, 21));
        labelResultOL->setFrameShape(QFrame::Panel);
        labelResultOL->setFrameShadow(QFrame::Sunken);
        labelResultOL->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        labelResultOLUnit = new QLabel(frame);
        labelResultOLUnit->setObjectName("labelResultOLUnit");
        labelResultOLUnit->setEnabled(false);
        labelResultOLUnit->setGeometry(QRect(120, 150, 81, 21));
        QPalette palette2;
        palette2.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush);
        palette2.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Window, brush1);
        palette2.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush);
        palette2.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Window, brush1);
        palette2.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush1);
        palette2.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Window, brush1);
        labelResultOLUnit->setPalette(palette2);
        labelResultOLUnit->setAutoFillBackground(true);
        labelResultOLUnit->setFrameShape(QFrame::Panel);
        labelResultOLUnit->setFrameShadow(QFrame::Sunken);
        labelResultOLUnit->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_15 = new QLabel(frame);
        label_15->setObjectName("label_15");
        label_15->setGeometry(QRect(10, 130, 111, 21));
        label_15->setFrameShape(QFrame::Panel);
        label_15->setFrameShadow(QFrame::Sunken);
        label_15->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        labelUnitName_14 = new QLabel(frame);
        labelUnitName_14->setObjectName("labelUnitName_14");
        labelUnitName_14->setGeometry(QRect(10, 200, 51, 20));
        labelUnitName_14->setFrameShape(QFrame::NoFrame);
        labelUnitName_14->setFrameShadow(QFrame::Sunken);
        labelUnitName_14->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        labelResultOH = new QLabel(frame);
        labelResultOH->setObjectName("labelResultOH");
        labelResultOH->setGeometry(QRect(120, 180, 81, 21));
        labelResultOH->setFrameShape(QFrame::Panel);
        labelResultOH->setFrameShadow(QFrame::Sunken);
        labelResultOH->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        labelResultOHUnit = new QLabel(frame);
        labelResultOHUnit->setObjectName("labelResultOHUnit");
        labelResultOHUnit->setEnabled(false);
        labelResultOHUnit->setGeometry(QRect(120, 200, 81, 21));
        QPalette palette3;
        palette3.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush);
        palette3.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Window, brush1);
        palette3.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush);
        palette3.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Window, brush1);
        palette3.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush1);
        palette3.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Window, brush1);
        labelResultOHUnit->setPalette(palette3);
        labelResultOHUnit->setAutoFillBackground(true);
        labelResultOHUnit->setFrameShape(QFrame::Panel);
        labelResultOHUnit->setFrameShadow(QFrame::Sunken);
        labelResultOHUnit->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_16 = new QLabel(frame);
        label_16->setObjectName("label_16");
        label_16->setGeometry(QRect(10, 180, 111, 21));
        label_16->setFrameShape(QFrame::Panel);
        label_16->setFrameShadow(QFrame::Sunken);
        label_16->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_17 = new QLabel(frame);
        label_17->setObjectName("label_17");
        label_17->setGeometry(QRect(10, 230, 111, 21));
        label_17->setFrameShape(QFrame::Panel);
        label_17->setFrameShadow(QFrame::Sunken);
        label_17->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        comboBoxAngleNumber = new QComboBox(frame);
        comboBoxAngleNumber->setObjectName("comboBoxAngleNumber");
        comboBoxAngleNumber->setGeometry(QRect(120, 250, 81, 24));
        labelResultAngleNumber = new QLabel(frame);
        labelResultAngleNumber->setObjectName("labelResultAngleNumber");
        labelResultAngleNumber->setGeometry(QRect(120, 230, 81, 21));
        labelResultAngleNumber->setFrameShape(QFrame::Panel);
        labelResultAngleNumber->setFrameShadow(QFrame::Sunken);
        labelResultAngleNumber->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_6 = new QLabel(ShowOperationalPanel);
        label_6->setObjectName("label_6");
        label_6->setGeometry(QRect(220, 410, 20, 201));
        label_6->setFrameShape(QFrame::Panel);
        label_6->setFrameShadow(QFrame::Raised);
        label_6->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_6->setIndent(1);
        frameMaster = new QFrame(ShowOperationalPanel);
        frameMaster->setObjectName("frameMaster");
        frameMaster->setGeometry(QRect(160, 4, 21, 21));
        frameMaster->setFrameShape(QFrame::NoFrame);
        frameMaster->setFrameShadow(QFrame::Plain);
        label_8 = new QLabel(ShowOperationalPanel);
        label_8->setObjectName("label_8");
        label_8->setGeometry(QRect(520, 5, 131, 21));
        frameLayer = new QFrame(ShowOperationalPanel);
        frameLayer->setObjectName("frameLayer");
        frameLayer->setGeometry(QRect(30, 400, 171, 41));
        frameLayer->setFrameShape(QFrame::NoFrame);
        frameLayer->setFrameShadow(QFrame::Plain);
        listWidgetHistList = new QListWidget(ShowOperationalPanel);
        listWidgetHistList->setObjectName("listWidgetHistList");
        listWidgetHistList->setGeometry(QRect(390, 640, 181, 81));
        label_9 = new QLabel(ShowOperationalPanel);
        label_9->setObjectName("label_9");
        label_9->setGeometry(QRect(20, 440, 191, 20));
        label_9->setFrameShape(QFrame::Panel);
        label_9->setFrameShadow(QFrame::Sunken);
        label_9->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        toolButtonSimShowArea = new QToolButton(ShowOperationalPanel);
        toolButtonSimShowArea->setObjectName("toolButtonSimShowArea");
        toolButtonSimShowArea->setGeometry(QRect(820, 20, 141, 41));
        toolButtonSimShowArea->setCheckable(true);
        toolButtonSimShowArea->setChecked(true);
        ButtonSaveToLibrary = new QPushButton(ShowOperationalPanel);
        ButtonSaveToLibrary->setObjectName("ButtonSaveToLibrary");
        ButtonSaveToLibrary->setGeometry(QRect(20, 680, 171, 41));
        ButtonSaveToLibrary->setAcceptDrops(true);
        pushButtonTransmitItemNameAll = new QPushButton(ShowOperationalPanel);
        pushButtonTransmitItemNameAll->setObjectName("pushButtonTransmitItemNameAll");
        pushButtonTransmitItemNameAll->setGeometry(QRect(160, 460, 51, 23));
        groupBox = new QGroupBox(ShowOperationalPanel);
        groupBox->setObjectName("groupBox");
        groupBox->setGeometry(QRect(20, 540, 191, 21));
        radioButtonLightSide1 = new QRadioButton(groupBox);
        radioButtonLightSide1->setObjectName("radioButtonLightSide1");
        radioButtonLightSide1->setGeometry(QRect(100, 0, 81, 18));
        radioButtonLightSide1->setChecked(false);
        radioButtonDarkSide1 = new QRadioButton(groupBox);
        radioButtonDarkSide1->setObjectName("radioButtonDarkSide1");
        radioButtonDarkSide1->setGeometry(QRect(20, 0, 81, 18));
        radioButtonDarkSide1->setChecked(true);
        label_40 = new QLabel(ShowOperationalPanel);
        label_40->setObjectName("label_40");
        label_40->setGeometry(QRect(390, 620, 181, 21));
        label_40->setFrameShape(QFrame::Panel);
        label_40->setFrameShadow(QFrame::Sunken);
        label_40->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        ButtonLoadFromLibrary = new QPushButton(ShowOperationalPanel);
        ButtonLoadFromLibrary->setObjectName("ButtonLoadFromLibrary");
        ButtonLoadFromLibrary->setGeometry(QRect(200, 680, 171, 41));
        ButtonLoadFromLibrary->setAcceptDrops(true);
        frameThreshold = new QFrame(ShowOperationalPanel);
        frameThreshold->setObjectName("frameThreshold");
        frameThreshold->setGeometry(QRect(490, 4, 21, 21));
        frameThreshold->setFrameShape(QFrame::NoFrame);
        frameThreshold->setFrameShadow(QFrame::Plain);
        label_4 = new QLabel(ShowOperationalPanel);
        label_4->setObjectName("label_4");
        label_4->setGeometry(QRect(20, 490, 62, 20));
        label_4->setFrameShape(QFrame::Panel);
        label_4->setFrameShadow(QFrame::Sunken);
        label_4->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        ButtonRelrectOnlyBlock = new QPushButton(ShowOperationalPanel);
        ButtonRelrectOnlyBlock->setObjectName("ButtonRelrectOnlyBlock");
        ButtonRelrectOnlyBlock->setGeometry(QRect(20, 630, 171, 41));
        ButtonRelrectOnlyBlock->setAcceptDrops(true);
        ButtonReflectAllBlocks = new QPushButton(ShowOperationalPanel);
        ButtonReflectAllBlocks->setObjectName("ButtonReflectAllBlocks");
        ButtonReflectAllBlocks->setGeometry(QRect(200, 630, 171, 41));
        ButtonReflectAllBlocks->setAcceptDrops(true);
        label_5 = new QLabel(ShowOperationalPanel);
        label_5->setObjectName("label_5");
        label_5->setGeometry(QRect(80, 490, 101, 20));
        label_5->setFrameShape(QFrame::Panel);
        label_5->setFrameShadow(QFrame::Sunken);
        label_5->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        pushButtonChangeLib = new QPushButton(ShowOperationalPanel);
        pushButtonChangeLib->setObjectName("pushButtonChangeLib");
        pushButtonChangeLib->setGeometry(QRect(180, 510, 31, 23));
        toolButtonSimShowInside = new QToolButton(ShowOperationalPanel);
        toolButtonSimShowInside->setObjectName("toolButtonSimShowInside");
        toolButtonSimShowInside->setGeometry(QRect(820, 60, 141, 41));
        toolButtonSimShowInside->setCheckable(true);
        toolButtonSimShowInside->setChecked(true);
        EditLibName = new QLineEdit(ShowOperationalPanel);
        EditLibName->setObjectName("EditLibName");
        EditLibName->setGeometry(QRect(80, 510, 101, 21));
        EditLibName->setReadOnly(true);
        ButtonClose = new QPushButton(ShowOperationalPanel);
        ButtonClose->setObjectName("ButtonClose");
        ButtonClose->setGeometry(QRect(980, 680, 171, 41));
        frameLineGraphI = new QFrame(ShowOperationalPanel);
        frameLineGraphI->setObjectName("frameLineGraphI");
        frameLineGraphI->setGeometry(QRect(10, 50, 781, 161));
        frameLineGraphI->setFrameShape(QFrame::NoFrame);
        frameLineGraphI->setFrameShadow(QFrame::Plain);
        pushButtonSimShowCenterPos = new QPushButton(ShowOperationalPanel);
        pushButtonSimShowCenterPos->setObjectName("pushButtonSimShowCenterPos");
        pushButtonSimShowCenterPos->setGeometry(QRect(1160, 60, 111, 41));
        frameTarget = new QFrame(ShowOperationalPanel);
        frameTarget->setObjectName("frameTarget");
        frameTarget->setGeometry(QRect(330, 4, 21, 21));
        frameTarget->setFrameShape(QFrame::NoFrame);
        frameTarget->setFrameShadow(QFrame::Plain);
        frameLineGraphO = new QFrame(ShowOperationalPanel);
        frameLineGraphO->setObjectName("frameLineGraphO");
        frameLineGraphO->setGeometry(QRect(10, 240, 781, 161));
        frameLineGraphO->setFrameShape(QFrame::NoFrame);
        frameLineGraphO->setFrameShadow(QFrame::Plain);
        label_12 = new QLabel(ShowOperationalPanel);
        label_12->setObjectName("label_12");
        label_12->setGeometry(QRect(10, 30, 271, 20));
        label_12->setFrameShape(QFrame::Panel);
        label_12->setFrameShadow(QFrame::Sunken);
        label_13 = new QLabel(ShowOperationalPanel);
        label_13->setObjectName("label_13");
        label_13->setGeometry(QRect(10, 220, 261, 20));
        label_13->setFrameShape(QFrame::Panel);
        label_13->setFrameShadow(QFrame::Sunken);
        EditMasterColI = new QLineEdit(ShowOperationalPanel);
        EditMasterColI->setObjectName("EditMasterColI");
        EditMasterColI->setGeometry(QRect(470, 30, 61, 21));
        QPalette palette4;
        QBrush brush2(QColor(0, 255, 255, 255));
        brush2.setStyle(Qt::BrushStyle::SolidPattern);
        palette4.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush2);
        palette4.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush2);
        QBrush brush3(QColor(192, 192, 192, 255));
        brush3.setStyle(Qt::BrushStyle::SolidPattern);
        palette4.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush3);
        EditMasterColI->setPalette(palette4);
        EditMasterColI->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_41 = new QLabel(ShowOperationalPanel);
        label_41->setObjectName("label_41");
        label_41->setGeometry(QRect(300, 30, 171, 21));
        label_41->setFrameShape(QFrame::Panel);
        label_41->setFrameShadow(QFrame::Sunken);
        label_41->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_42 = new QLabel(ShowOperationalPanel);
        label_42->setObjectName("label_42");
        label_42->setGeometry(QRect(560, 30, 161, 21));
        label_42->setFrameShape(QFrame::Panel);
        label_42->setFrameShadow(QFrame::Sunken);
        label_42->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditTargetColI = new QLineEdit(ShowOperationalPanel);
        EditTargetColI->setObjectName("EditTargetColI");
        EditTargetColI->setGeometry(QRect(720, 30, 61, 21));
        QPalette palette5;
        palette5.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush2);
        palette5.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush2);
        palette5.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush3);
        EditTargetColI->setPalette(palette5);
        EditTargetColI->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_43 = new QLabel(ShowOperationalPanel);
        label_43->setObjectName("label_43");
        label_43->setGeometry(QRect(560, 220, 161, 21));
        label_43->setFrameShape(QFrame::Panel);
        label_43->setFrameShadow(QFrame::Sunken);
        label_43->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditMasterColO = new QLineEdit(ShowOperationalPanel);
        EditMasterColO->setObjectName("EditMasterColO");
        EditMasterColO->setGeometry(QRect(470, 220, 61, 21));
        QPalette palette6;
        palette6.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush2);
        palette6.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush2);
        palette6.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush3);
        EditMasterColO->setPalette(palette6);
        EditMasterColO->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_44 = new QLabel(ShowOperationalPanel);
        label_44->setObjectName("label_44");
        label_44->setGeometry(QRect(300, 220, 171, 21));
        label_44->setFrameShape(QFrame::Panel);
        label_44->setFrameShadow(QFrame::Sunken);
        label_44->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditTargetColO = new QLineEdit(ShowOperationalPanel);
        EditTargetColO->setObjectName("EditTargetColO");
        EditTargetColO->setGeometry(QRect(720, 220, 61, 21));
        QPalette palette7;
        palette7.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush2);
        palette7.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush2);
        palette7.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush3);
        EditTargetColO->setPalette(palette7);
        EditTargetColO->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        tableWidgetShift = new QTableWidget(ShowOperationalPanel);
        if (tableWidgetShift->columnCount() < 2)
            tableWidgetShift->setColumnCount(2);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        tableWidgetShift->setHorizontalHeaderItem(0, __qtablewidgetitem);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        tableWidgetShift->setHorizontalHeaderItem(1, __qtablewidgetitem1);
        if (tableWidgetShift->rowCount() < 3)
            tableWidgetShift->setRowCount(3);
        QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
        tableWidgetShift->setVerticalHeaderItem(0, __qtablewidgetitem2);
        QTableWidgetItem *__qtablewidgetitem3 = new QTableWidgetItem();
        tableWidgetShift->setVerticalHeaderItem(1, __qtablewidgetitem3);
        QTableWidgetItem *__qtablewidgetitem4 = new QTableWidgetItem();
        tableWidgetShift->setVerticalHeaderItem(2, __qtablewidgetitem4);
        tableWidgetShift->setObjectName("tableWidgetShift");
        tableWidgetShift->setGeometry(QRect(820, 530, 331, 141));
        tableWidgetShift->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tableWidgetShift->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);

        retranslateUi(ShowOperationalPanel);

        tabWidgetInspect->setCurrentIndex(5);


        QMetaObject::connectSlotsByName(ShowOperationalPanel);
    } // setupUi

    void retranslateUi(QWidget *ShowOperationalPanel)
    {
        ShowOperationalPanel->setWindowTitle(QCoreApplication::translate("ShowOperationalPanel", "Form", nullptr));
        toolButtonSimShowNGMark->setText(QCoreApplication::translate("ShowOperationalPanel", "NG mark", nullptr));
        toolButtonSimShowOutside->setText(QCoreApplication::translate("ShowOperationalPanel", "Outside", nullptr));
        EditItemName->setText(QCoreApplication::translate("ShowOperationalPanel", "XXX", nullptr));
        label_3->setText(QCoreApplication::translate("ShowOperationalPanel", "\343\203\236\343\202\271\343\202\277\343\203\274\347\224\273\345\203\217", nullptr));
        labelUnitName_8->setText(QCoreApplication::translate("ShowOperationalPanel", "mm", nullptr));
        label_35->setText(QCoreApplication::translate("ShowOperationalPanel", "<html><head/><body><p>\345\206\205</p><p>\345\201\264</p></body></html>", nullptr));
        label_20->setText(QCoreApplication::translate("ShowOperationalPanel", "\346\230\216\345\201\264", nullptr));
        label_21->setText(QCoreApplication::translate("ShowOperationalPanel", "OK\350\274\235\345\272\246\347\257\204\345\233\262", nullptr));
        label_22->setText(QCoreApplication::translate("ShowOperationalPanel", "OK\343\203\211\343\203\203\343\203\210\346\225\260", nullptr));
        label_23->setText(QCoreApplication::translate("ShowOperationalPanel", "\346\232\227\345\201\264", nullptr));
        label_37->setText(QCoreApplication::translate("ShowOperationalPanel", "<html><head/><body><p>\345\244\226</p><p>\345\201\264</p></body></html>", nullptr));
        label_24->setText(QCoreApplication::translate("ShowOperationalPanel", "OK\350\274\235\345\272\246\347\257\204\345\233\262", nullptr));
        label_28->setText(QCoreApplication::translate("ShowOperationalPanel", "\346\230\216\345\201\264", nullptr));
        label_29->setText(QCoreApplication::translate("ShowOperationalPanel", "OK\343\203\211\343\203\203\343\203\210\346\225\260", nullptr));
        label_30->setText(QCoreApplication::translate("ShowOperationalPanel", "\346\232\227\345\201\264", nullptr));
        tabWidgetInspect->setTabText(tabWidgetInspect->indexOf(tab_6), QCoreApplication::translate("ShowOperationalPanel", "Threshold", nullptr));
        checkBModeAbsoluteBright->setText(QCoreApplication::translate("ShowOperationalPanel", "\347\265\266\345\257\276\350\274\235\345\272\246", nullptr));
        checkBModeDynamicMask->setText(QCoreApplication::translate("ShowOperationalPanel", "\345\256\237\350\241\214\343\203\236\343\202\271\343\202\257", nullptr));
        checkBModeEnabled->setText(QCoreApplication::translate("ShowOperationalPanel", "\346\244\234\346\237\273\346\234\211\345\212\271", nullptr));
        checkBModeCenterBrightFromParts->setText(QCoreApplication::translate("ShowOperationalPanel", "\351\203\250\345\223\201\343\201\213\343\202\211\350\274\235\345\272\246\343\202\222\346\212\275\345\207\272\343\201\231\343\202\213", nullptr));
        tabWidgetInspect->setTabText(tabWidgetInspect->indexOf(tab_7), QCoreApplication::translate("ShowOperationalPanel", "\345\261\236\346\200\247", nullptr));
        label_26->setText(QCoreApplication::translate("ShowOperationalPanel", "\345\206\205\345\201\264\343\200\200\346\230\216\345\201\264\343\200\200\346\234\200\345\244\247\350\243\234\346\255\243\350\274\235\345\272\246\351\207\217", nullptr));
        label_25->setText(QCoreApplication::translate("ShowOperationalPanel", "\345\206\205\345\201\264\343\200\200\346\232\227\345\201\264\343\200\200\346\234\200\345\244\247\350\243\234\346\255\243\350\274\235\345\272\246\351\207\217", nullptr));
        label_34->setText(QCoreApplication::translate("ShowOperationalPanel", "\345\244\226\345\201\264\343\200\200\346\230\216\345\201\264\343\200\200\346\234\200\345\244\247\350\243\234\346\255\243\350\274\235\345\272\246\351\207\217", nullptr));
        label_33->setText(QCoreApplication::translate("ShowOperationalPanel", "\345\244\226\345\201\264\343\200\200\346\232\227\345\201\264\343\200\200\346\234\200\345\244\247\350\243\234\346\255\243\350\274\235\345\272\246\351\207\217", nullptr));
        tabWidgetInspect->setTabText(tabWidgetInspect->indexOf(tab_8), QCoreApplication::translate("ShowOperationalPanel", "\350\243\234\346\255\243", nullptr));
        label_38->setText(QCoreApplication::translate("ShowOperationalPanel", "\345\206\205\345\201\264", nullptr));
        label_39->setText(QCoreApplication::translate("ShowOperationalPanel", "\345\244\226\345\201\264", nullptr));
        checkBModeUseRegularBrightness->setText(QCoreApplication::translate("ShowOperationalPanel", "\345\237\272\346\272\226\350\274\235\345\272\246\343\202\222\344\275\277\343\201\206", nullptr));
        tabWidgetInspect->setTabText(tabWidgetInspect->indexOf(tab), QCoreApplication::translate("ShowOperationalPanel", "\350\274\235\345\272\246", nullptr));
        label_27->setText(QCoreApplication::translate("ShowOperationalPanel", "\345\215\230\344\275\223\343\201\247\343\201\256\346\216\242\347\264\242\343\203\211\343\203\203\343\203\210\346\225\260", nullptr));
        label_36->setText(QCoreApplication::translate("ShowOperationalPanel", "\345\205\250\344\275\223\343\201\247\343\201\256\346\216\242\347\264\242\343\203\211\343\203\203\343\203\210\346\225\260", nullptr));
        tabWidgetInspect->setTabText(tabWidgetInspect->indexOf(Search), QCoreApplication::translate("ShowOperationalPanel", "Search", nullptr));
        label_32->setText(QCoreApplication::translate("ShowOperationalPanel", "\350\274\252\351\203\255\351\203\250\345\210\206\343\201\256\347\247\273\350\241\214\345\271\205", nullptr));
        label_45->setText(QCoreApplication::translate("ShowOperationalPanel", "\350\247\222\345\272\246\346\225\260", nullptr));
        label->setText(QCoreApplication::translate("ShowOperationalPanel", "When these are changed, please finalize editing again", nullptr));
        tabWidgetInspect->setTabText(tabWidgetInspect->indexOf(tab_2), QCoreApplication::translate("ShowOperationalPanel", "\347\224\237\346\210\220", nullptr));
        EditLibID->setText(QCoreApplication::translate("ShowOperationalPanel", "12345", nullptr));
        label_7->setText(QCoreApplication::translate("ShowOperationalPanel", "\346\244\234\346\237\273\347\224\273\345\203\217", nullptr));
        label_31->setText(QCoreApplication::translate("ShowOperationalPanel", "\345\275\223\350\251\262\347\256\207\346\211\200\343\201\256\345\210\244\345\256\232\347\265\220\346\236\234", nullptr));
        ButtonCalc->setText(QCoreApplication::translate("ShowOperationalPanel", "\350\250\210\347\256\227", nullptr));
        labelUnitName_11->setText(QCoreApplication::translate("ShowOperationalPanel", "mm", nullptr));
        labelResultIL->setText(QCoreApplication::translate("ShowOperationalPanel", "123", nullptr));
        label_11->setText(QCoreApplication::translate("ShowOperationalPanel", "\345\206\205\345\201\264\343\200\200\346\232\227\345\201\264", nullptr));
        labelResultILUnit->setText(QCoreApplication::translate("ShowOperationalPanel", "123", nullptr));
        labelUnitName_12->setText(QCoreApplication::translate("ShowOperationalPanel", "mm", nullptr));
        labelResultIH->setText(QCoreApplication::translate("ShowOperationalPanel", "123", nullptr));
        labelResultIHUnit->setText(QCoreApplication::translate("ShowOperationalPanel", "123", nullptr));
        label_14->setText(QCoreApplication::translate("ShowOperationalPanel", "\345\206\205\345\201\264\343\200\200\346\230\216\345\201\264", nullptr));
        labelUnitName_13->setText(QCoreApplication::translate("ShowOperationalPanel", "mm", nullptr));
        labelResultOL->setText(QCoreApplication::translate("ShowOperationalPanel", "123", nullptr));
        labelResultOLUnit->setText(QCoreApplication::translate("ShowOperationalPanel", "123", nullptr));
        label_15->setText(QCoreApplication::translate("ShowOperationalPanel", "\345\244\226\345\201\264\343\200\200\346\232\227\345\201\264", nullptr));
        labelUnitName_14->setText(QCoreApplication::translate("ShowOperationalPanel", "mm", nullptr));
        labelResultOH->setText(QCoreApplication::translate("ShowOperationalPanel", "123", nullptr));
        labelResultOHUnit->setText(QCoreApplication::translate("ShowOperationalPanel", "123", nullptr));
        label_16->setText(QCoreApplication::translate("ShowOperationalPanel", "\345\244\226\345\201\264\343\200\200\346\230\216\345\201\264", nullptr));
        label_17->setText(QCoreApplication::translate("ShowOperationalPanel", "Angle No", nullptr));
        labelResultAngleNumber->setText(QCoreApplication::translate("ShowOperationalPanel", "123", nullptr));
        label_6->setText(QCoreApplication::translate("ShowOperationalPanel", "\346\244\234\n"
"\346\237\273", nullptr));
        label_8->setText(QCoreApplication::translate("ShowOperationalPanel", "\343\201\227\343\201\215\343\201\204\345\200\244", nullptr));
        label_9->setText(QCoreApplication::translate("ShowOperationalPanel", "Item name", nullptr));
        toolButtonSimShowArea->setText(QCoreApplication::translate("ShowOperationalPanel", "Area", nullptr));
        ButtonSaveToLibrary->setText(QCoreApplication::translate("ShowOperationalPanel", "\343\203\251\343\202\244\343\203\226\343\203\251\343\203\252\343\201\253\344\277\235\345\255\230", nullptr));
        pushButtonTransmitItemNameAll->setText(QCoreApplication::translate("ShowOperationalPanel", "To all", nullptr));
        radioButtonLightSide1->setText(QCoreApplication::translate("ShowOperationalPanel", "Light", nullptr));
        radioButtonDarkSide1->setText(QCoreApplication::translate("ShowOperationalPanel", "Dark", nullptr));
        label_40->setText(QCoreApplication::translate("ShowOperationalPanel", "\345\275\223\350\251\262\347\256\207\346\211\200\343\201\256\343\203\220\343\203\251\343\201\244\343\201\215\343\202\260\343\203\251\343\203\225", nullptr));
        ButtonLoadFromLibrary->setText(QCoreApplication::translate("ShowOperationalPanel", "\343\203\251\343\202\244\343\203\226\343\203\251\343\203\252\343\201\213\343\202\211\350\252\255\343\201\277\345\207\272\343\201\227", nullptr));
        label_4->setText(QCoreApplication::translate("ShowOperationalPanel", "\343\203\251\343\202\244\343\203\226\343\203\251\343\203\252\357\274\251\357\274\244", nullptr));
        ButtonRelrectOnlyBlock->setText(QCoreApplication::translate("ShowOperationalPanel", "\343\201\223\343\201\256\351\240\230\345\237\237\343\201\240\343\201\221\343\201\253\345\217\215\346\230\240", nullptr));
        ButtonReflectAllBlocks->setText(QCoreApplication::translate("ShowOperationalPanel", "\345\220\214\344\270\200\347\250\256\351\241\236\343\201\256\351\240\230\345\237\237\343\201\253\345\217\215\346\230\240", nullptr));
        label_5->setText(QCoreApplication::translate("ShowOperationalPanel", "\343\203\251\343\202\244\343\203\226\343\203\251\343\203\252\345\220\215\347\247\260", nullptr));
        pushButtonChangeLib->setText(QCoreApplication::translate("ShowOperationalPanel", "...", nullptr));
        toolButtonSimShowInside->setText(QCoreApplication::translate("ShowOperationalPanel", "Inside", nullptr));
        EditLibName->setText(QCoreApplication::translate("ShowOperationalPanel", "XXX", nullptr));
        ButtonClose->setText(QCoreApplication::translate("ShowOperationalPanel", "\351\226\211\343\201\230\343\202\213", nullptr));
        pushButtonSimShowCenterPos->setText(QCoreApplication::translate("ShowOperationalPanel", "\345\276\251\345\270\260", nullptr));
        label_12->setText(QCoreApplication::translate("ShowOperationalPanel", "Inside of pattern", nullptr));
        label_13->setText(QCoreApplication::translate("ShowOperationalPanel", "Outside of pattern", nullptr));
        label_41->setText(QCoreApplication::translate("ShowOperationalPanel", "\343\203\236\343\202\271\343\202\277\343\203\274\344\270\255\345\277\203\350\274\235\345\272\246", nullptr));
        label_42->setText(QCoreApplication::translate("ShowOperationalPanel", "Target\344\270\255\345\277\203\350\274\235\345\272\246", nullptr));
        label_43->setText(QCoreApplication::translate("ShowOperationalPanel", "Target\344\270\255\345\277\203\350\274\235\345\272\246", nullptr));
        label_44->setText(QCoreApplication::translate("ShowOperationalPanel", "\343\203\236\343\202\271\343\202\277\343\203\274\344\270\255\345\277\203\350\274\235\345\272\246", nullptr));
        QTableWidgetItem *___qtablewidgetitem = tableWidgetShift->horizontalHeaderItem(0);
        ___qtablewidgetitem->setText(QCoreApplication::translate("ShowOperationalPanel", "X", nullptr));
        QTableWidgetItem *___qtablewidgetitem1 = tableWidgetShift->horizontalHeaderItem(1);
        ___qtablewidgetitem1->setText(QCoreApplication::translate("ShowOperationalPanel", "Y", nullptr));
        QTableWidgetItem *___qtablewidgetitem2 = tableWidgetShift->verticalHeaderItem(0);
        ___qtablewidgetitem2->setText(QCoreApplication::translate("ShowOperationalPanel", "By Alignment", nullptr));
        QTableWidgetItem *___qtablewidgetitem3 = tableWidgetShift->verticalHeaderItem(1);
        ___qtablewidgetitem3->setText(QCoreApplication::translate("ShowOperationalPanel", "By Global", nullptr));
        QTableWidgetItem *___qtablewidgetitem4 = tableWidgetShift->verticalHeaderItem(2);
        ___qtablewidgetitem4->setText(QCoreApplication::translate("ShowOperationalPanel", "By Self", nullptr));
    } // retranslateUi

};

namespace Ui {
    class ShowOperationalPanel: public Ui_ShowOperationalPanel {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_SHOWOPERATIONALPANEL_H
