#ifndef ADJUSTMOVEALLAFTERLOADMASTER_GLOBAL_H
#define ADJUSTMOVEALLAFTERLOADMASTER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef ADJUSTMOVEALLAFTERLOADMASTER_LIB
# define ADJUSTMOVEALLAFTERLOADMASTER_EXPORT Q_DECL_EXPORT
#else
# define ADJUSTMOVEALLAFTERLOADMASTER_EXPORT Q_DECL_IMPORT
#endif

#endif // ADJUSTMOVEALLAFTERLOADMASTER_GLOBAL_H
