#ifndef FILTERHORIZONTALBAND_GLOBAL_H
#define FILTERHORIZONTALBAND_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef FILTERHORIZONTALBAND_LIB
# define FILTERHORIZONTALBAND_EXPORT Q_DECL_EXPORT
#else
# define FILTERHORIZONTALBAND_EXPORT Q_DECL_IMPORT
#endif

#endif // FILTERHORIZONTALBAND_GLOBAL_H
