#ifndef PROPERTYREALTIMEGRAPH_GLOBAL_H
#define PROPERTYREALTIMEGRAPH_GLOBAL_H

#include <qglobal.h>

#ifdef PROPERTYREALTIMEGRAPH_LIB
# define PROPERTYREALTIMEGRAPH_EXPORT Q_DECL_EXPORT
#else
# define PROPERTYREALTIMEGRAPH_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTYREALTIMEGRAPH_GLOBAL_H
