#ifndef BUTTONIMAGETRANSFORMER_GLOBAL_H
#define BUTTONIMAGETRANSFORMER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONIMAGETRANSFORMER_LIB
# define BUTTONIMAGETRANSFORMER_EXPORT Q_DECL_EXPORT
#else
# define BUTTONIMAGETRANSFORMER_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONIMAGETRANSFORMER_GLOBAL_H
