#ifndef SHOWALIGNMENTRESULT_GLOBAL_H
#define SHOWALIGNMENTRESULT_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SHOWALIGNMENTRESULT_LIB
# define SHOWALIGNMENTRESULT_EXPORT Q_DECL_EXPORT
#else
# define SHOWALIGNMENTRESULT_EXPORT Q_DECL_IMPORT
#endif

#endif // SHOWALIGNMENTRESULT_GLOBAL_H
