#ifndef SHOWRESULTALARM_GLOBAL_H
#define SHOWRESULTALARM_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SHOWRESULTALARM_LIB
# define SHOWRESULTALARM_EXPORT Q_DECL_EXPORT
#else
# define SHOWRESULTALARM_EXPORT Q_DECL_IMPORT
#endif

#endif // SHOWRESULTALARM_GLOBAL_H
