#ifndef BUTTONSELECTSTACKEDPAGE_GLOBAL_H
#define BUTTONSELECTSTACKEDPAGE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONSELECTSTACKEDPAGE_LIB
# define BUTTONSELECTSTACKEDPAGE_EXPORT Q_DECL_EXPORT
#else
# define BUTTONSELECTSTACKEDPAGE_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONSELECTSTACKEDPAGE_GLOBAL_H
