#ifndef HOUGHINSPECTION_GLOBAL_H
#define HOUGHINSPECTION_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef HOUGHINSPECTION_LIB
# define HOUGHINSPECTION_EXPORT Q_DECL_EXPORT
#else
# define HOUGHINSPECTION_EXPORT Q_DECL_IMPORT
#endif

#endif // HOUGHINSPECTION_GLOBAL_H
