#ifndef CONTROLPRECISIONCHECKER_GLOBAL_H
#define CONTROLPRECISIONCHECKER_GLOBAL_H

#include <qglobal.h>

#ifdef CONTROLPRECISIONCHECKER_LIB
# define CONTROLPRECISIONCHECKER_EXPORT Q_DECL_EXPORT
#else
# define CONTROLPRECISIONCHECKER_EXPORT Q_DECL_IMPORT
#endif

#endif // CONTROLPRECISIONCHECKER_GLOBAL_H
