#ifndef SETTHRESHOLDBYHISTOGRAM_GLOBAL_H
#define SETTHRESHOLDBYHISTOGRAM_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SETTHRESHOLDBYHISTOGRAM_LIB
# define SETTHRESHOLDBYHISTOGRAM_EXPORT Q_DECL_EXPORT
#else
# define SETTHRESHOLDBYHISTOGRAM_EXPORT Q_DECL_IMPORT
#endif

#endif // SETTHRESHOLDBYHISTOGRAM_GLOBAL_H
