#ifndef GENERALPANEL_GLOBAL_H
#define GENERALPANEL_GLOBAL_H

#include <qglobal.h>

#ifdef GENERALPANEL_LIB
# define GENERALPANEL_EXPORT Q_DECL_EXPORT
#else
# define GENERALPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // GENERALPANEL_GLOBAL_H
