/********************************************************************************
** Form generated from reading UI file 'PropertyAreaFilterForm.ui'
**
** Created by: Qt User Interface Compiler version 6.10.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_PROPERTYAREAFILTERFORM_H
#define UI_PROPERTYAREAFILTERFORM_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QWidget>
#include "guiformbase.h"

QT_BEGIN_NAMESPACE

class Ui_PropertyAreaFilterFormClass
{
public:
    QFrame *frameLibFolder;
    QTableWidget *tableWidgetLibList;
    QFrame *frame_2;
    QLabel *label_5;
    QLineEdit *EditLibID;
    QLineEdit *EditLibName;
    QStackedWidget *stackedWidget;
    QWidget *pagePattenInverted;
    QSpinBox *spinBoxMinNGLength;
    QLabel *label_12;
    QLabel *label_8;
    QSpinBox *spinBoxDarkLevel;
    QLabel *label_9;
    QLabel *label_11;
    QSpinBox *spinBoxLightLevel;
    QSpinBox *spinBoxLineWidth;
    QWidget *pageVerticalEmphasize;
    QSpinBox *spinBoxMinNGLength_2;
    QSpinBox *spinBoxWaveSize;
    QSpinBox *spinBoxVarLevel;
    QLabel *label_16;
    QSpinBox *spinBoxRelativeLevel;
    QLabel *label_15;
    QLabel *label_13;
    QLabel *label_14;
    QWidget *pageLineEmphasize;
    QLabel *label_17;
    QSpinBox *spinBoxBlockSize;
    QLabel *label_10;
    QSpinBox *spinBoxEmphasizeRate;
    QLabel *label_18;
    QSpinBox *spinBoxSkipSita;
    QLabel *label_20;
    QLabel *label_21;
    QSpinBox *spinBoxSkipKy;
    QDoubleSpinBox *spinBoxUpperBlocksPercentageByVariance;
    QLabel *label_22;
    QSpinBox *spinBoxUnifiedLineNumb;
    QWidget *pageLargeEnflat;
    QSpinBox *spinBoxLineLargeEnflat_BlockSize;
    QLabel *label_19;
    QLabel *label_23;
    QCheckBox *checkBoxMoveByAlignment;
    QLabel *label_24;
    QSpinBox *spinBoxSkipDot;
    QLabel *label_25;
    QSpinBox *spinBoxGeneratedBrightness;
    QLabel *label_26;
    QDoubleSpinBox *doubleSpinBoxAdoptedRate;
    QWidget *pageHorizontalEmphasize;
    QLabel *label_27;
    QLabel *label_29;
    QSpinBox *spinBoxHorizEmphaBlockSize;
    QSpinBox *spinBoxEmphasizeRate2;
    QCheckBox *checkBoxMoveByAlignment2;
    QLabel *label_28;
    QLabel *label_30;
    QSpinBox *spinBoxSkipDot2;
    QSpinBox *spinBoxBlockHeight;
    QLabel *label_31;
    QWidget *Differential;
    QLabel *label_32;
    QLabel *label_33;
    QSpinBox *spinBoxBlockDifferentialShrinkRate;
    QSpinBox *spinBoxDifferentialBlockSize;
    QGroupBox *groupBox;
    QRadioButton *radioButtonTypePatternInverted;
    QRadioButton *radioButtonTypeVerticalEmphasize;
    QRadioButton *radioButtonTypeLineEmphasize;
    QRadioButton *radioButtonTypeLineLargeEnflat;
    QRadioButton *radioButtonTypeHorizontalEmphasize;
    QRadioButton *radioButtonTypeDifferential;
    QLabel *label_6;
    QPushButton *ButtonLibDelete;
    QPushButton *ButtonLibNew;
    QPushButton *ButtonLibSave;
    QPushButton *ButtonLibSaveNew;
    QTableWidget *tableWidgetItems;

    void setupUi(GUIFormBase *PropertyAreaFilterFormClass)
    {
        if (PropertyAreaFilterFormClass->objectName().isEmpty())
            PropertyAreaFilterFormClass->setObjectName("PropertyAreaFilterFormClass");
        PropertyAreaFilterFormClass->resize(400, 591);
        frameLibFolder = new QFrame(PropertyAreaFilterFormClass);
        frameLibFolder->setObjectName("frameLibFolder");
        frameLibFolder->setGeometry(QRect(10, 10, 191, 141));
        frameLibFolder->setFrameShape(QFrame::StyledPanel);
        frameLibFolder->setFrameShadow(QFrame::Sunken);
        tableWidgetLibList = new QTableWidget(PropertyAreaFilterFormClass);
        if (tableWidgetLibList->columnCount() < 2)
            tableWidgetLibList->setColumnCount(2);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        tableWidgetLibList->setHorizontalHeaderItem(0, __qtablewidgetitem);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        tableWidgetLibList->setHorizontalHeaderItem(1, __qtablewidgetitem1);
        tableWidgetLibList->setObjectName("tableWidgetLibList");
        tableWidgetLibList->setGeometry(QRect(210, 10, 181, 141));
        tableWidgetLibList->setSelectionMode(QAbstractItemView::SingleSelection);
        tableWidgetLibList->setSelectionBehavior(QAbstractItemView::SelectRows);
        frame_2 = new QFrame(PropertyAreaFilterFormClass);
        frame_2->setObjectName("frame_2");
        frame_2->setGeometry(QRect(10, 160, 381, 271));
        frame_2->setFrameShape(QFrame::StyledPanel);
        frame_2->setFrameShadow(QFrame::Sunken);
        label_5 = new QLabel(frame_2);
        label_5->setObjectName("label_5");
        label_5->setGeometry(QRect(10, 40, 41, 20));
        label_5->setFrameShape(QFrame::Panel);
        label_5->setFrameShadow(QFrame::Sunken);
        label_5->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditLibID = new QLineEdit(frame_2);
        EditLibID->setObjectName("EditLibID");
        EditLibID->setGeometry(QRect(60, 10, 39, 21));
        EditLibID->setReadOnly(true);
        EditLibName = new QLineEdit(frame_2);
        EditLibName->setObjectName("EditLibName");
        EditLibName->setGeometry(QRect(60, 40, 91, 21));
        stackedWidget = new QStackedWidget(frame_2);
        stackedWidget->setObjectName("stackedWidget");
        stackedWidget->setGeometry(QRect(160, 10, 211, 201));
        pagePattenInverted = new QWidget();
        pagePattenInverted->setObjectName("pagePattenInverted");
        spinBoxMinNGLength = new QSpinBox(pagePattenInverted);
        spinBoxMinNGLength->setObjectName("spinBoxMinNGLength");
        spinBoxMinNGLength->setGeometry(QRect(110, 100, 81, 22));
        spinBoxMinNGLength->setMaximum(9999999);
        label_12 = new QLabel(pagePattenInverted);
        label_12->setObjectName("label_12");
        label_12->setGeometry(QRect(10, 100, 91, 20));
        label_12->setFrameShape(QFrame::Panel);
        label_12->setFrameShadow(QFrame::Sunken);
        label_12->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_8 = new QLabel(pagePattenInverted);
        label_8->setObjectName("label_8");
        label_8->setGeometry(QRect(10, 10, 91, 21));
        label_8->setFrameShape(QFrame::Panel);
        label_8->setFrameShadow(QFrame::Sunken);
        label_8->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        spinBoxDarkLevel = new QSpinBox(pagePattenInverted);
        spinBoxDarkLevel->setObjectName("spinBoxDarkLevel");
        spinBoxDarkLevel->setGeometry(QRect(110, 10, 81, 22));
        spinBoxDarkLevel->setMaximum(255);
        label_9 = new QLabel(pagePattenInverted);
        label_9->setObjectName("label_9");
        label_9->setGeometry(QRect(10, 40, 91, 21));
        label_9->setFrameShape(QFrame::Panel);
        label_9->setFrameShadow(QFrame::Sunken);
        label_9->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_11 = new QLabel(pagePattenInverted);
        label_11->setObjectName("label_11");
        label_11->setGeometry(QRect(10, 70, 91, 20));
        label_11->setFrameShape(QFrame::Panel);
        label_11->setFrameShadow(QFrame::Sunken);
        label_11->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        spinBoxLightLevel = new QSpinBox(pagePattenInverted);
        spinBoxLightLevel->setObjectName("spinBoxLightLevel");
        spinBoxLightLevel->setGeometry(QRect(110, 40, 81, 22));
        spinBoxLightLevel->setMaximum(255);
        spinBoxLineWidth = new QSpinBox(pagePattenInverted);
        spinBoxLineWidth->setObjectName("spinBoxLineWidth");
        spinBoxLineWidth->setGeometry(QRect(110, 70, 81, 22));
        spinBoxLineWidth->setMaximum(999);
        stackedWidget->addWidget(pagePattenInverted);
        pageVerticalEmphasize = new QWidget();
        pageVerticalEmphasize->setObjectName("pageVerticalEmphasize");
        spinBoxMinNGLength_2 = new QSpinBox(pageVerticalEmphasize);
        spinBoxMinNGLength_2->setObjectName("spinBoxMinNGLength_2");
        spinBoxMinNGLength_2->setGeometry(QRect(110, 100, 81, 22));
        spinBoxMinNGLength_2->setMaximum(9999999);
        spinBoxWaveSize = new QSpinBox(pageVerticalEmphasize);
        spinBoxWaveSize->setObjectName("spinBoxWaveSize");
        spinBoxWaveSize->setGeometry(QRect(110, 70, 81, 22));
        spinBoxWaveSize->setMaximum(999);
        spinBoxVarLevel = new QSpinBox(pageVerticalEmphasize);
        spinBoxVarLevel->setObjectName("spinBoxVarLevel");
        spinBoxVarLevel->setGeometry(QRect(110, 40, 81, 22));
        spinBoxVarLevel->setMaximum(255);
        label_16 = new QLabel(pageVerticalEmphasize);
        label_16->setObjectName("label_16");
        label_16->setGeometry(QRect(10, 70, 91, 20));
        label_16->setFrameShape(QFrame::Panel);
        label_16->setFrameShadow(QFrame::Sunken);
        label_16->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        spinBoxRelativeLevel = new QSpinBox(pageVerticalEmphasize);
        spinBoxRelativeLevel->setObjectName("spinBoxRelativeLevel");
        spinBoxRelativeLevel->setGeometry(QRect(110, 10, 81, 22));
        spinBoxRelativeLevel->setMaximum(255);
        label_15 = new QLabel(pageVerticalEmphasize);
        label_15->setObjectName("label_15");
        label_15->setGeometry(QRect(10, 40, 91, 21));
        label_15->setFrameShape(QFrame::Panel);
        label_15->setFrameShadow(QFrame::Sunken);
        label_15->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_13 = new QLabel(pageVerticalEmphasize);
        label_13->setObjectName("label_13");
        label_13->setGeometry(QRect(10, 10, 91, 21));
        label_13->setFrameShape(QFrame::Panel);
        label_13->setFrameShadow(QFrame::Sunken);
        label_13->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_14 = new QLabel(pageVerticalEmphasize);
        label_14->setObjectName("label_14");
        label_14->setGeometry(QRect(10, 100, 91, 20));
        label_14->setFrameShape(QFrame::Panel);
        label_14->setFrameShadow(QFrame::Sunken);
        label_14->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        stackedWidget->addWidget(pageVerticalEmphasize);
        pageLineEmphasize = new QWidget();
        pageLineEmphasize->setObjectName("pageLineEmphasize");
        label_17 = new QLabel(pageLineEmphasize);
        label_17->setObjectName("label_17");
        label_17->setGeometry(QRect(10, 10, 91, 21));
        label_17->setFrameShape(QFrame::Panel);
        label_17->setFrameShadow(QFrame::Sunken);
        label_17->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        spinBoxBlockSize = new QSpinBox(pageLineEmphasize);
        spinBoxBlockSize->setObjectName("spinBoxBlockSize");
        spinBoxBlockSize->setGeometry(QRect(110, 10, 81, 22));
        spinBoxBlockSize->setMaximum(500);
        spinBoxBlockSize->setValue(100);
        label_10 = new QLabel(pageLineEmphasize);
        label_10->setObjectName("label_10");
        label_10->setGeometry(QRect(10, 40, 91, 21));
        label_10->setFrameShape(QFrame::Panel);
        label_10->setFrameShadow(QFrame::Sunken);
        label_10->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        spinBoxEmphasizeRate = new QSpinBox(pageLineEmphasize);
        spinBoxEmphasizeRate->setObjectName("spinBoxEmphasizeRate");
        spinBoxEmphasizeRate->setGeometry(QRect(110, 40, 81, 22));
        spinBoxEmphasizeRate->setMaximum(100);
        spinBoxEmphasizeRate->setValue(5);
        label_18 = new QLabel(pageLineEmphasize);
        label_18->setObjectName("label_18");
        label_18->setGeometry(QRect(10, 70, 91, 21));
        label_18->setFrameShape(QFrame::Panel);
        label_18->setFrameShadow(QFrame::Sunken);
        label_18->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        spinBoxSkipSita = new QSpinBox(pageLineEmphasize);
        spinBoxSkipSita->setObjectName("spinBoxSkipSita");
        spinBoxSkipSita->setGeometry(QRect(110, 100, 81, 22));
        spinBoxSkipSita->setMaximum(180);
        spinBoxSkipSita->setValue(5);
        label_20 = new QLabel(pageLineEmphasize);
        label_20->setObjectName("label_20");
        label_20->setGeometry(QRect(10, 100, 91, 21));
        label_20->setFrameShape(QFrame::Panel);
        label_20->setFrameShadow(QFrame::Sunken);
        label_20->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_21 = new QLabel(pageLineEmphasize);
        label_21->setObjectName("label_21");
        label_21->setGeometry(QRect(10, 130, 91, 21));
        label_21->setFrameShape(QFrame::Panel);
        label_21->setFrameShadow(QFrame::Sunken);
        label_21->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        spinBoxSkipKy = new QSpinBox(pageLineEmphasize);
        spinBoxSkipKy->setObjectName("spinBoxSkipKy");
        spinBoxSkipKy->setGeometry(QRect(110, 130, 81, 22));
        spinBoxSkipKy->setMinimum(1);
        spinBoxSkipKy->setMaximum(25);
        spinBoxSkipKy->setValue(3);
        spinBoxUpperBlocksPercentageByVariance = new QDoubleSpinBox(pageLineEmphasize);
        spinBoxUpperBlocksPercentageByVariance->setObjectName("spinBoxUpperBlocksPercentageByVariance");
        spinBoxUpperBlocksPercentageByVariance->setGeometry(QRect(110, 70, 81, 22));
        spinBoxUpperBlocksPercentageByVariance->setMinimum(1.000000000000000);
        spinBoxUpperBlocksPercentageByVariance->setMaximum(100.000000000000000);
        spinBoxUpperBlocksPercentageByVariance->setSingleStep(0.010000000000000);
        spinBoxUpperBlocksPercentageByVariance->setValue(10.000000000000000);
        label_22 = new QLabel(pageLineEmphasize);
        label_22->setObjectName("label_22");
        label_22->setGeometry(QRect(10, 160, 91, 21));
        label_22->setFrameShape(QFrame::Panel);
        label_22->setFrameShadow(QFrame::Sunken);
        label_22->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        spinBoxUnifiedLineNumb = new QSpinBox(pageLineEmphasize);
        spinBoxUnifiedLineNumb->setObjectName("spinBoxUnifiedLineNumb");
        spinBoxUnifiedLineNumb->setGeometry(QRect(110, 160, 81, 22));
        spinBoxUnifiedLineNumb->setMaximum(25);
        spinBoxUnifiedLineNumb->setValue(5);
        stackedWidget->addWidget(pageLineEmphasize);
        pageLargeEnflat = new QWidget();
        pageLargeEnflat->setObjectName("pageLargeEnflat");
        spinBoxLineLargeEnflat_BlockSize = new QSpinBox(pageLargeEnflat);
        spinBoxLineLargeEnflat_BlockSize->setObjectName("spinBoxLineLargeEnflat_BlockSize");
        spinBoxLineLargeEnflat_BlockSize->setGeometry(QRect(110, 10, 81, 22));
        spinBoxLineLargeEnflat_BlockSize->setMaximum(500);
        spinBoxLineLargeEnflat_BlockSize->setValue(100);
        label_19 = new QLabel(pageLargeEnflat);
        label_19->setObjectName("label_19");
        label_19->setGeometry(QRect(10, 10, 91, 21));
        label_19->setFrameShape(QFrame::Panel);
        label_19->setFrameShadow(QFrame::Sunken);
        label_19->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_23 = new QLabel(pageLargeEnflat);
        label_23->setObjectName("label_23");
        label_23->setGeometry(QRect(10, 40, 151, 21));
        label_23->setFrameShape(QFrame::Panel);
        label_23->setFrameShadow(QFrame::Sunken);
        label_23->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        checkBoxMoveByAlignment = new QCheckBox(pageLargeEnflat);
        checkBoxMoveByAlignment->setObjectName("checkBoxMoveByAlignment");
        checkBoxMoveByAlignment->setGeometry(QRect(170, 40, 21, 19));
        label_24 = new QLabel(pageLargeEnflat);
        label_24->setObjectName("label_24");
        label_24->setGeometry(QRect(10, 70, 91, 21));
        label_24->setFrameShape(QFrame::Panel);
        label_24->setFrameShadow(QFrame::Sunken);
        label_24->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        spinBoxSkipDot = new QSpinBox(pageLargeEnflat);
        spinBoxSkipDot->setObjectName("spinBoxSkipDot");
        spinBoxSkipDot->setGeometry(QRect(110, 70, 81, 22));
        spinBoxSkipDot->setMaximum(500);
        spinBoxSkipDot->setValue(100);
        label_25 = new QLabel(pageLargeEnflat);
        label_25->setObjectName("label_25");
        label_25->setGeometry(QRect(10, 100, 91, 21));
        label_25->setFrameShape(QFrame::Panel);
        label_25->setFrameShadow(QFrame::Sunken);
        label_25->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        spinBoxGeneratedBrightness = new QSpinBox(pageLargeEnflat);
        spinBoxGeneratedBrightness->setObjectName("spinBoxGeneratedBrightness");
        spinBoxGeneratedBrightness->setGeometry(QRect(110, 100, 81, 22));
        spinBoxGeneratedBrightness->setMaximum(255);
        spinBoxGeneratedBrightness->setValue(100);
        label_26 = new QLabel(pageLargeEnflat);
        label_26->setObjectName("label_26");
        label_26->setGeometry(QRect(10, 130, 91, 21));
        label_26->setFrameShape(QFrame::Panel);
        label_26->setFrameShadow(QFrame::Sunken);
        label_26->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        doubleSpinBoxAdoptedRate = new QDoubleSpinBox(pageLargeEnflat);
        doubleSpinBoxAdoptedRate->setObjectName("doubleSpinBoxAdoptedRate");
        doubleSpinBoxAdoptedRate->setGeometry(QRect(110, 130, 81, 22));
        doubleSpinBoxAdoptedRate->setMaximum(100.000000000000000);
        stackedWidget->addWidget(pageLargeEnflat);
        pageHorizontalEmphasize = new QWidget();
        pageHorizontalEmphasize->setObjectName("pageHorizontalEmphasize");
        label_27 = new QLabel(pageHorizontalEmphasize);
        label_27->setObjectName("label_27");
        label_27->setGeometry(QRect(0, 40, 121, 21));
        label_27->setFrameShape(QFrame::Panel);
        label_27->setFrameShadow(QFrame::Sunken);
        label_27->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_29 = new QLabel(pageHorizontalEmphasize);
        label_29->setObjectName("label_29");
        label_29->setGeometry(QRect(0, 10, 121, 21));
        label_29->setFrameShape(QFrame::Panel);
        label_29->setFrameShadow(QFrame::Sunken);
        label_29->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        spinBoxHorizEmphaBlockSize = new QSpinBox(pageHorizontalEmphasize);
        spinBoxHorizEmphaBlockSize->setObjectName("spinBoxHorizEmphaBlockSize");
        spinBoxHorizEmphaBlockSize->setGeometry(QRect(130, 10, 81, 22));
        spinBoxHorizEmphaBlockSize->setMaximum(1000);
        spinBoxEmphasizeRate2 = new QSpinBox(pageHorizontalEmphasize);
        spinBoxEmphasizeRate2->setObjectName("spinBoxEmphasizeRate2");
        spinBoxEmphasizeRate2->setGeometry(QRect(130, 40, 81, 22));
        spinBoxEmphasizeRate2->setMinimum(-10000);
        spinBoxEmphasizeRate2->setMaximum(10000);
        spinBoxEmphasizeRate2->setValue(100);
        checkBoxMoveByAlignment2 = new QCheckBox(pageHorizontalEmphasize);
        checkBoxMoveByAlignment2->setObjectName("checkBoxMoveByAlignment2");
        checkBoxMoveByAlignment2->setGeometry(QRect(190, 70, 21, 19));
        label_28 = new QLabel(pageHorizontalEmphasize);
        label_28->setObjectName("label_28");
        label_28->setGeometry(QRect(0, 70, 181, 21));
        label_28->setFrameShape(QFrame::Panel);
        label_28->setFrameShadow(QFrame::Sunken);
        label_28->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_30 = new QLabel(pageHorizontalEmphasize);
        label_30->setObjectName("label_30");
        label_30->setGeometry(QRect(0, 100, 121, 21));
        label_30->setFrameShape(QFrame::Panel);
        label_30->setFrameShadow(QFrame::Sunken);
        label_30->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        spinBoxSkipDot2 = new QSpinBox(pageHorizontalEmphasize);
        spinBoxSkipDot2->setObjectName("spinBoxSkipDot2");
        spinBoxSkipDot2->setGeometry(QRect(130, 100, 81, 22));
        spinBoxSkipDot2->setMaximum(500);
        spinBoxSkipDot2->setValue(100);
        spinBoxBlockHeight = new QSpinBox(pageHorizontalEmphasize);
        spinBoxBlockHeight->setObjectName("spinBoxBlockHeight");
        spinBoxBlockHeight->setGeometry(QRect(130, 130, 81, 22));
        spinBoxBlockHeight->setMaximum(5000);
        spinBoxBlockHeight->setValue(100);
        label_31 = new QLabel(pageHorizontalEmphasize);
        label_31->setObjectName("label_31");
        label_31->setGeometry(QRect(0, 130, 121, 21));
        label_31->setFrameShape(QFrame::Panel);
        label_31->setFrameShadow(QFrame::Sunken);
        label_31->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        stackedWidget->addWidget(pageHorizontalEmphasize);
        Differential = new QWidget();
        Differential->setObjectName("Differential");
        label_32 = new QLabel(Differential);
        label_32->setObjectName("label_32");
        label_32->setGeometry(QRect(0, 130, 121, 21));
        label_32->setFrameShape(QFrame::Panel);
        label_32->setFrameShadow(QFrame::Sunken);
        label_32->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_33 = new QLabel(Differential);
        label_33->setObjectName("label_33");
        label_33->setGeometry(QRect(0, 10, 121, 21));
        label_33->setFrameShape(QFrame::Panel);
        label_33->setFrameShadow(QFrame::Sunken);
        label_33->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        spinBoxBlockDifferentialShrinkRate = new QSpinBox(Differential);
        spinBoxBlockDifferentialShrinkRate->setObjectName("spinBoxBlockDifferentialShrinkRate");
        spinBoxBlockDifferentialShrinkRate->setGeometry(QRect(130, 130, 81, 22));
        spinBoxBlockDifferentialShrinkRate->setMaximum(5000);
        spinBoxBlockDifferentialShrinkRate->setValue(100);
        spinBoxDifferentialBlockSize = new QSpinBox(Differential);
        spinBoxDifferentialBlockSize->setObjectName("spinBoxDifferentialBlockSize");
        spinBoxDifferentialBlockSize->setGeometry(QRect(130, 10, 81, 22));
        spinBoxDifferentialBlockSize->setMaximum(1000);
        stackedWidget->addWidget(Differential);
        groupBox = new QGroupBox(frame_2);
        groupBox->setObjectName("groupBox");
        groupBox->setGeometry(QRect(10, 70, 151, 161));
        radioButtonTypePatternInverted = new QRadioButton(groupBox);
        radioButtonTypePatternInverted->setObjectName("radioButtonTypePatternInverted");
        radioButtonTypePatternInverted->setGeometry(QRect(10, 20, 131, 16));
        radioButtonTypePatternInverted->setChecked(true);
        radioButtonTypeVerticalEmphasize = new QRadioButton(groupBox);
        radioButtonTypeVerticalEmphasize->setObjectName("radioButtonTypeVerticalEmphasize");
        radioButtonTypeVerticalEmphasize->setGeometry(QRect(10, 40, 141, 16));
        radioButtonTypeVerticalEmphasize->setChecked(false);
        radioButtonTypeLineEmphasize = new QRadioButton(groupBox);
        radioButtonTypeLineEmphasize->setObjectName("radioButtonTypeLineEmphasize");
        radioButtonTypeLineEmphasize->setGeometry(QRect(10, 60, 131, 16));
        radioButtonTypeLineEmphasize->setChecked(false);
        radioButtonTypeLineLargeEnflat = new QRadioButton(groupBox);
        radioButtonTypeLineLargeEnflat->setObjectName("radioButtonTypeLineLargeEnflat");
        radioButtonTypeLineLargeEnflat->setGeometry(QRect(10, 80, 131, 16));
        radioButtonTypeLineLargeEnflat->setChecked(false);
        radioButtonTypeHorizontalEmphasize = new QRadioButton(groupBox);
        radioButtonTypeHorizontalEmphasize->setObjectName("radioButtonTypeHorizontalEmphasize");
        radioButtonTypeHorizontalEmphasize->setGeometry(QRect(10, 100, 141, 16));
        radioButtonTypeHorizontalEmphasize->setChecked(false);
        radioButtonTypeDifferential = new QRadioButton(groupBox);
        radioButtonTypeDifferential->setObjectName("radioButtonTypeDifferential");
        radioButtonTypeDifferential->setGeometry(QRect(10, 120, 141, 16));
        radioButtonTypeDifferential->setChecked(false);
        label_6 = new QLabel(frame_2);
        label_6->setObjectName("label_6");
        label_6->setGeometry(QRect(10, 10, 41, 20));
        label_6->setFrameShape(QFrame::Panel);
        label_6->setFrameShadow(QFrame::Sunken);
        label_6->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        ButtonLibDelete = new QPushButton(frame_2);
        ButtonLibDelete->setObjectName("ButtonLibDelete");
        ButtonLibDelete->setGeometry(QRect(110, 240, 75, 23));
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/Qtres/Delete.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        ButtonLibDelete->setIcon(icon);
        ButtonLibNew = new QPushButton(frame_2);
        ButtonLibNew->setObjectName("ButtonLibNew");
        ButtonLibNew->setGeometry(QRect(20, 240, 81, 23));
        QIcon icon1;
        icon1.addFile(QString::fromUtf8(":/Qtres/ClearNew.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        ButtonLibNew->setIcon(icon1);
        ButtonLibSave = new QPushButton(frame_2);
        ButtonLibSave->setObjectName("ButtonLibSave");
        ButtonLibSave->setGeometry(QRect(280, 240, 81, 23));
        QIcon icon2;
        icon2.addFile(QString::fromUtf8(":/Qtres/Update.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        ButtonLibSave->setIcon(icon2);
        ButtonLibSaveNew = new QPushButton(frame_2);
        ButtonLibSaveNew->setObjectName("ButtonLibSaveNew");
        ButtonLibSaveNew->setGeometry(QRect(190, 240, 81, 23));
        QIcon icon3;
        icon3.addFile(QString::fromUtf8(":/Qtres/SaveNew.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        ButtonLibSaveNew->setIcon(icon3);
        tableWidgetItems = new QTableWidget(PropertyAreaFilterFormClass);
        if (tableWidgetItems->columnCount() < 5)
            tableWidgetItems->setColumnCount(5);
        QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
        tableWidgetItems->setHorizontalHeaderItem(0, __qtablewidgetitem2);
        QTableWidgetItem *__qtablewidgetitem3 = new QTableWidgetItem();
        tableWidgetItems->setHorizontalHeaderItem(1, __qtablewidgetitem3);
        QTableWidgetItem *__qtablewidgetitem4 = new QTableWidgetItem();
        tableWidgetItems->setHorizontalHeaderItem(2, __qtablewidgetitem4);
        QTableWidgetItem *__qtablewidgetitem5 = new QTableWidgetItem();
        tableWidgetItems->setHorizontalHeaderItem(3, __qtablewidgetitem5);
        QTableWidgetItem *__qtablewidgetitem6 = new QTableWidgetItem();
        tableWidgetItems->setHorizontalHeaderItem(4, __qtablewidgetitem6);
        tableWidgetItems->setObjectName("tableWidgetItems");
        tableWidgetItems->setGeometry(QRect(10, 440, 381, 141));
        tableWidgetItems->setSelectionMode(QAbstractItemView::SingleSelection);
        tableWidgetItems->setSelectionBehavior(QAbstractItemView::SelectRows);

        retranslateUi(PropertyAreaFilterFormClass);

        stackedWidget->setCurrentIndex(5);


        QMetaObject::connectSlotsByName(PropertyAreaFilterFormClass);
    } // setupUi

    void retranslateUi(GUIFormBase *PropertyAreaFilterFormClass)
    {
        PropertyAreaFilterFormClass->setWindowTitle(QCoreApplication::translate("PropertyAreaFilterFormClass", "PropertyAreaFilterForm", nullptr));
        QTableWidgetItem *___qtablewidgetitem = tableWidgetLibList->horizontalHeaderItem(0);
        ___qtablewidgetitem->setText(QCoreApplication::translate("PropertyAreaFilterFormClass", "ID", nullptr));
        QTableWidgetItem *___qtablewidgetitem1 = tableWidgetLibList->horizontalHeaderItem(1);
        ___qtablewidgetitem1->setText(QCoreApplication::translate("PropertyAreaFilterFormClass", "Name", nullptr));
        label_5->setText(QCoreApplication::translate("PropertyAreaFilterFormClass", "Name", nullptr));
        EditLibID->setText(QCoreApplication::translate("PropertyAreaFilterFormClass", "123", nullptr));
        EditLibName->setText(QCoreApplication::translate("PropertyAreaFilterFormClass", "Library name", nullptr));
        label_12->setText(QCoreApplication::translate("PropertyAreaFilterFormClass", "NG\343\202\265\343\202\244\343\202\272", nullptr));
        label_8->setText(QCoreApplication::translate("PropertyAreaFilterFormClass", "\346\232\227\345\201\264\351\226\276\345\200\244", nullptr));
        label_9->setText(QCoreApplication::translate("PropertyAreaFilterFormClass", "\346\230\216\345\201\264\351\226\276\345\200\244", nullptr));
        label_11->setText(QCoreApplication::translate("PropertyAreaFilterFormClass", "\347\267\232\343\201\256\345\244\252\343\201\225", nullptr));
        label_16->setText(QCoreApplication::translate("PropertyAreaFilterFormClass", "\346\250\241\346\247\230\343\201\256\343\202\265\343\202\244\343\202\272", nullptr));
        label_15->setText(QCoreApplication::translate("PropertyAreaFilterFormClass", "\343\201\260\343\202\211\343\201\244\343\201\215\351\226\276\345\200\244", nullptr));
        label_13->setText(QCoreApplication::translate("PropertyAreaFilterFormClass", "\347\233\270\345\257\276\351\226\276\345\200\244", nullptr));
        label_14->setText(QCoreApplication::translate("PropertyAreaFilterFormClass", "NG\343\202\265\343\202\244\343\202\272", nullptr));
        label_17->setText(QCoreApplication::translate("PropertyAreaFilterFormClass", "\343\203\226\343\203\255\343\203\203\343\202\257\343\202\265\343\202\244\343\202\272", nullptr));
        label_10->setText(QCoreApplication::translate("PropertyAreaFilterFormClass", "\345\274\267\350\252\277\345\272\246\345\220\210", nullptr));
        label_18->setText(QCoreApplication::translate("PropertyAreaFilterFormClass", "\345\274\267\350\252\277\343\201\231\343\202\213\344\270\212\344\275\215\357\274\205", nullptr));
        label_20->setText(QCoreApplication::translate("PropertyAreaFilterFormClass", "\351\226\223\345\274\225\343\201\217\350\247\222\345\272\246", nullptr));
        label_21->setText(QCoreApplication::translate("PropertyAreaFilterFormClass", "\351\226\223\345\274\225\343\201\217\343\203\211\343\203\203\343\203\210\346\225\260", nullptr));
        label_22->setText(QCoreApplication::translate("PropertyAreaFilterFormClass", "\345\244\252\343\201\204\345\202\267\343\201\270\343\201\256\345\274\267\343\201\225", nullptr));
        label_19->setText(QCoreApplication::translate("PropertyAreaFilterFormClass", "\343\203\226\343\203\255\343\203\203\343\202\257\343\202\265\343\202\244\343\202\272", nullptr));
        label_23->setText(QCoreApplication::translate("PropertyAreaFilterFormClass", "\344\275\215\347\275\256\345\220\210\343\202\217\343\201\233\343\201\256\345\275\261\351\237\277", nullptr));
        checkBoxMoveByAlignment->setText(QString());
        label_24->setText(QCoreApplication::translate("PropertyAreaFilterFormClass", "\351\226\223\345\274\225\343\201\215\343\203\211\343\203\203\343\203\210", nullptr));
        label_25->setText(QCoreApplication::translate("PropertyAreaFilterFormClass", "\347\224\237\346\210\220\350\274\235\345\272\246", nullptr));
        label_26->setText(QCoreApplication::translate("PropertyAreaFilterFormClass", "\346\216\241\347\224\250\347\216\207\357\274\210\357\274\205\357\274\211", nullptr));
        label_27->setText(QCoreApplication::translate("PropertyAreaFilterFormClass", "\345\274\267\350\252\277\345\272\246(%)", nullptr));
        label_29->setText(QCoreApplication::translate("PropertyAreaFilterFormClass", "\346\250\252\343\201\256\343\203\225\343\202\243\343\203\253\343\202\277\343\202\265\343\202\244\343\202\272", nullptr));
        checkBoxMoveByAlignment2->setText(QString());
        label_28->setText(QCoreApplication::translate("PropertyAreaFilterFormClass", "\344\275\215\347\275\256\345\220\210\343\202\217\343\201\233\343\201\256\345\275\261\351\237\277", nullptr));
        label_30->setText(QCoreApplication::translate("PropertyAreaFilterFormClass", "\351\226\223\345\274\225\343\201\215\343\203\211\343\203\203\343\203\210", nullptr));
        label_31->setText(QCoreApplication::translate("PropertyAreaFilterFormClass", "\347\270\246\343\201\256\343\203\225\343\202\243\343\203\253\343\202\277\343\202\265\343\202\244\343\202\272", nullptr));
        label_32->setText(QCoreApplication::translate("PropertyAreaFilterFormClass", "\351\226\223\345\274\225\343\201\215\343\203\211\343\203\203\343\203\210", nullptr));
        label_33->setText(QCoreApplication::translate("PropertyAreaFilterFormClass", "\343\203\225\343\202\243\343\203\253\343\202\277\343\202\265\343\202\244\343\202\272", nullptr));
        groupBox->setTitle(QCoreApplication::translate("PropertyAreaFilterFormClass", "\346\244\234\346\237\273\346\226\271\346\263\225", nullptr));
        radioButtonTypePatternInverted->setText(QCoreApplication::translate("PropertyAreaFilterFormClass", "PatternInverted", nullptr));
        radioButtonTypeVerticalEmphasize->setText(QCoreApplication::translate("PropertyAreaFilterFormClass", "VerticalEmphasize", nullptr));
        radioButtonTypeLineEmphasize->setText(QCoreApplication::translate("PropertyAreaFilterFormClass", "\347\267\232\345\274\267\350\252\277", nullptr));
        radioButtonTypeLineLargeEnflat->setText(QCoreApplication::translate("PropertyAreaFilterFormClass", "\345\244\247\345\237\237\345\235\207\344\270\200\345\214\226", nullptr));
        radioButtonTypeHorizontalEmphasize->setText(QCoreApplication::translate("PropertyAreaFilterFormClass", "Horizontal emphasize", nullptr));
        radioButtonTypeDifferential->setText(QCoreApplication::translate("PropertyAreaFilterFormClass", "\345\276\256\345\210\206", nullptr));
        label_6->setText(QCoreApplication::translate("PropertyAreaFilterFormClass", "ID", nullptr));
        ButtonLibDelete->setText(QCoreApplication::translate("PropertyAreaFilterFormClass", "Delete", nullptr));
        ButtonLibNew->setText(QCoreApplication::translate("PropertyAreaFilterFormClass", "Clear new", nullptr));
        ButtonLibSave->setText(QCoreApplication::translate("PropertyAreaFilterFormClass", "Update", nullptr));
        ButtonLibSaveNew->setText(QCoreApplication::translate("PropertyAreaFilterFormClass", "Save new", nullptr));
        QTableWidgetItem *___qtablewidgetitem2 = tableWidgetItems->horizontalHeaderItem(0);
        ___qtablewidgetitem2->setText(QCoreApplication::translate("PropertyAreaFilterFormClass", "Page", nullptr));
        QTableWidgetItem *___qtablewidgetitem3 = tableWidgetItems->horizontalHeaderItem(1);
        ___qtablewidgetitem3->setText(QCoreApplication::translate("PropertyAreaFilterFormClass", "Layer", nullptr));
        QTableWidgetItem *___qtablewidgetitem4 = tableWidgetItems->horizontalHeaderItem(2);
        ___qtablewidgetitem4->setText(QCoreApplication::translate("PropertyAreaFilterFormClass", "ID", nullptr));
        QTableWidgetItem *___qtablewidgetitem5 = tableWidgetItems->horizontalHeaderItem(3);
        ___qtablewidgetitem5->setText(QCoreApplication::translate("PropertyAreaFilterFormClass", "LibID", nullptr));
        QTableWidgetItem *___qtablewidgetitem6 = tableWidgetItems->horizontalHeaderItem(4);
        ___qtablewidgetitem6->setText(QCoreApplication::translate("PropertyAreaFilterFormClass", "LibName", nullptr));
    } // retranslateUi

};

namespace Ui {
    class PropertyAreaFilterFormClass: public Ui_PropertyAreaFilterFormClass {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_PROPERTYAREAFILTERFORM_H
