#ifndef SHOWCURRENTLIGHTNAME_GLOBAL_H
#define SHOWCURRENTLIGHTNAME_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SHOWCURRENTLIGHTNAME_LIB
# define SHOWCURRENTLIGHTNAME_EXPORT Q_DECL_EXPORT
#else
# define SHOWCURRENTLIGHTNAME_EXPORT Q_DECL_IMPORT
#endif

#endif // SHOWCURRENTLIGHTNAME_GLOBAL_H
