#ifndef PROJECTEDINSPECTIONIMAGEPANEL_GLOBAL_H
#define PROJECTEDINSPECTIONIMAGEPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PROJECTEDINSPECTIONIMAGEPANEL_LIB
# define PROJECTEDINSPECTIONIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define PROJECTEDINSPECTIONIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // PROJECTEDINSPECTIONIMAGEPANEL_GLOBAL_H
