#ifndef PROPERTYPROJECTEDINSPECTION_GLOBAL_H
#define PROPERTYPROJECTEDINSPECTION_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PROPERTYPROJECTEDINSPECTION_LIB
# define PROPERTYPROJECTEDINSPECTION_EXPORT Q_DECL_EXPORT
#else
# define PROPERTYPROJECTEDINSPECTION_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTYPROJECTEDINSPECTION_GLOBAL_H
