#ifndef HOOKALGORITHMIMAGEPANEL_GLOBAL_H
#define HOOKALGORITHMIMAGEPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef HOOKALGORITHMIMAGEPANEL_LIB
# define HOOKALGORITHMIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define HOOKALGORITHMIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // HOOKALGORITHMIMAGEPANEL_GLOBAL_H
