/********************************************************************************
** Form generated from reading UI file 'EulerRingL1HistgramForm.ui'
**
** Created by: Qt User Interface Compiler version 6.10.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_EULERRINGL1HISTGRAMFORM_H
#define UI_EULERRINGL1HISTGRAMFORM_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QListWidget>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QToolButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_EulerRingL1HistgramForm
{
public:
    QLabel *label_40;
    QPushButton *pushButtonSimShowCenterPos;
    QLabel *label_38;
    QLabel *label_7;
    QFrame *frameMaster;
    QLabel *label_5;
    QPushButton *ButtonReflectAllBlocks;
    QPushButton *ButtonLoadFromLibrary;
    QLabel *label_9;
    QLabel *label_3;
    QLineEdit *EditItemName;
    QGroupBox *groupBox;
    QRadioButton *radioButtonLightSide1;
    QRadioButton *radioButtonDarkSide1;
    QTabWidget *tabWidgetInspect;
    QWidget *tab_6;
    QLabel *label_23;
    QLabel *label_22;
    QLabel *label_21;
    QSpinBox *EditDarkWidth;
    QSpinBox *EditLightWidth;
    QLabel *label_37;
    QSpinBox *EditConnectLen;
    QLabel *labelUnitName_8;
    QDoubleSpinBox *doubleSpinBoxConnectLenMM;
    QLabel *labelUnitName_3;
    QCheckBox *checkModeEnableOpenRingCheck;
    QWidget *tab_5;
    QSpinBox *EditMinHoleDiameter;
    QLabel *label_17;
    QSpinBox *EditMaxShiftHole;
    QLabel *label_32;
    QDoubleSpinBox *doubleSpinBoxMinHoleDiameterMM;
    QDoubleSpinBox *doubleSpinBoxMaxShiftHoleMM;
    QLabel *labelUnitName_2;
    QDoubleSpinBox *doubleSpinBoxMaxHoleDiameterMM;
    QSpinBox *EditMaxHoleDiameter;
    QLabel *label_18;
    QLabel *label_20;
    QSpinBox *EditHoleBrightnessAsReference;
    QWidget *tab_7;
    QCheckBox *checkModeEnabled;
    QCheckBox *checkModeAbsoluteBright;
    QCheckBox *checkModeCenterBrightFromParts;
    QCheckBox *checkModeDynamicMask;
    QCheckBox *checkModeEnableHoleCheck;
    QCheckBox *checkModeEnableInRound;
    QWidget *tab_8;
    QLabel *label_26;
    QLabel *label_25;
    QSpinBox *EditAdjustWhite;
    QSpinBox *EditAdjustBlack;
    QWidget *Search;
    QLabel *label_27;
    QSpinBox *EditSearchDot;
    QLabel *labelUnitName_4;
    QDoubleSpinBox *doubleSpinBoxSearchDotMM;
    QWidget *tab;
    QDoubleSpinBox *doubleSpinBoxExpandForDynamicMaskMM;
    QSpinBox *EditExpandForDynamicMask;
    QLabel *label_19;
    QLineEdit *EditCenterBrightMaster;
    QStackedWidget *stackedWidgetParts;
    QWidget *page;
    QWidget *page_3;
    QPushButton *ButtonRelrectSaveParts;
    QWidget *page_2;
    QLabel *label_8;
    QListWidget *listWidgetHistList;
    QFrame *frameThreshold;
    QLabel *label_39;
    QPushButton *ButtonClose;
    QPushButton *ButtonSaveToLibrary;
    QFrame *frameTarget;
    QFrame *frame_SimImage;
    QLabel *label_6;
    QFrame *frame;
    QLabel *label_31;
    QLabel *label;
    QLabel *label_2;
    QLabel *labelResultHoleDiameter;
    QLabel *labelResultHoleShift;
    QPushButton *ButtonCalc;
    QLabel *labelResultHoleDiameterUnit;
    QLabel *labelResultHoleShiftUnit;
    QLabel *labelUnitName_9;
    QLabel *labelUnitName_10;
    QLabel *label_10;
    QLabel *labelResultRing;
    QLabel *labelUnitName_11;
    QLabel *labelMasterHoleDiameter;
    QLabel *label_11;
    QLabel *labelMasterHoleDiameterUnit;
    QPushButton *pushButtonChangeLib;
    QLineEdit *EditLibID;
    QToolButton *toolButtonSimShowRing;
    QPushButton *pushButtonTransmitItemNameAll;
    QLineEdit *EditLibName;
    QLabel *label_4;
    QLineEdit *EditCenterBrightTarget;
    QFrame *frameLayer;
    QFrame *frameLineGraph;
    QToolButton *toolButtonSimShowBlock;
    QPushButton *ButtonRelrectOnlyBlock;
    QToolButton *toolButtonSimShowHole;
    QToolButton *toolButtonSimShowMask;
    QToolButton *toolButtonSimShowNGMark;
    QPushButton *pushButtonRestore;

    void setupUi(QWidget *EulerRingL1HistgramForm)
    {
        if (EulerRingL1HistgramForm->objectName().isEmpty())
            EulerRingL1HistgramForm->setObjectName("EulerRingL1HistgramForm");
        EulerRingL1HistgramForm->resize(1322, 768);
        label_40 = new QLabel(EulerRingL1HistgramForm);
        label_40->setObjectName("label_40");
        label_40->setGeometry(QRect(410, 610, 181, 21));
        label_40->setFrameShape(QFrame::Panel);
        label_40->setFrameShadow(QFrame::Sunken);
        label_40->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        pushButtonSimShowCenterPos = new QPushButton(EulerRingL1HistgramForm);
        pushButtonSimShowCenterPos->setObjectName("pushButtonSimShowCenterPos");
        pushButtonSimShowCenterPos->setGeometry(QRect(1180, 60, 111, 41));
        label_38 = new QLabel(EulerRingL1HistgramForm);
        label_38->setObjectName("label_38");
        label_38->setGeometry(QRect(40, 570, 121, 21));
        label_38->setFrameShape(QFrame::Panel);
        label_38->setFrameShadow(QFrame::Sunken);
        label_38->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_7 = new QLabel(EulerRingL1HistgramForm);
        label_7->setObjectName("label_7");
        label_7->setGeometry(QRect(380, 10, 131, 21));
        frameMaster = new QFrame(EulerRingL1HistgramForm);
        frameMaster->setObjectName("frameMaster");
        frameMaster->setGeometry(QRect(180, 10, 21, 21));
        frameMaster->setFrameShape(QFrame::NoFrame);
        frameMaster->setFrameShadow(QFrame::Plain);
        label_5 = new QLabel(EulerRingL1HistgramForm);
        label_5->setObjectName("label_5");
        label_5->setGeometry(QRect(100, 490, 101, 20));
        label_5->setFrameShape(QFrame::Panel);
        label_5->setFrameShadow(QFrame::Sunken);
        label_5->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        ButtonReflectAllBlocks = new QPushButton(EulerRingL1HistgramForm);
        ButtonReflectAllBlocks->setObjectName("ButtonReflectAllBlocks");
        ButtonReflectAllBlocks->setGeometry(QRect(220, 620, 171, 41));
        ButtonReflectAllBlocks->setAcceptDrops(true);
        ButtonLoadFromLibrary = new QPushButton(EulerRingL1HistgramForm);
        ButtonLoadFromLibrary->setObjectName("ButtonLoadFromLibrary");
        ButtonLoadFromLibrary->setGeometry(QRect(220, 670, 171, 41));
        ButtonLoadFromLibrary->setAcceptDrops(true);
        label_9 = new QLabel(EulerRingL1HistgramForm);
        label_9->setObjectName("label_9");
        label_9->setGeometry(QRect(40, 440, 191, 20));
        label_9->setFrameShape(QFrame::Panel);
        label_9->setFrameShadow(QFrame::Sunken);
        label_9->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_3 = new QLabel(EulerRingL1HistgramForm);
        label_3->setObjectName("label_3");
        label_3->setGeometry(QRect(210, 10, 131, 21));
        EditItemName = new QLineEdit(EulerRingL1HistgramForm);
        EditItemName->setObjectName("EditItemName");
        EditItemName->setGeometry(QRect(40, 460, 141, 21));
        EditItemName->setReadOnly(false);
        groupBox = new QGroupBox(EulerRingL1HistgramForm);
        groupBox->setObjectName("groupBox");
        groupBox->setGeometry(QRect(40, 540, 191, 21));
        radioButtonLightSide1 = new QRadioButton(groupBox);
        radioButtonLightSide1->setObjectName("radioButtonLightSide1");
        radioButtonLightSide1->setGeometry(QRect(100, 0, 51, 18));
        radioButtonLightSide1->setChecked(false);
        radioButtonDarkSide1 = new QRadioButton(groupBox);
        radioButtonDarkSide1->setObjectName("radioButtonDarkSide1");
        radioButtonDarkSide1->setGeometry(QRect(20, 0, 51, 18));
        radioButtonDarkSide1->setChecked(true);
        tabWidgetInspect = new QTabWidget(EulerRingL1HistgramForm);
        tabWidgetInspect->setObjectName("tabWidgetInspect");
        tabWidgetInspect->setGeometry(QRect(260, 400, 331, 181));
        tab_6 = new QWidget();
        tab_6->setObjectName("tab_6");
        label_23 = new QLabel(tab_6);
        label_23->setObjectName("label_23");
        label_23->setGeometry(QRect(140, 10, 91, 21));
        label_23->setFrameShape(QFrame::Panel);
        label_23->setFrameShadow(QFrame::Sunken);
        label_23->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_22 = new QLabel(tab_6);
        label_22->setObjectName("label_22");
        label_22->setGeometry(QRect(10, 30, 121, 20));
        label_22->setFrameShape(QFrame::Panel);
        label_22->setFrameShadow(QFrame::Sunken);
        label_22->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_21 = new QLabel(tab_6);
        label_21->setObjectName("label_21");
        label_21->setGeometry(QRect(230, 10, 91, 21));
        label_21->setFrameShape(QFrame::Panel);
        label_21->setFrameShadow(QFrame::Sunken);
        label_21->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditDarkWidth = new QSpinBox(tab_6);
        EditDarkWidth->setObjectName("EditDarkWidth");
        EditDarkWidth->setGeometry(QRect(140, 30, 91, 20));
        EditDarkWidth->setMinimum(-255);
        EditDarkWidth->setMaximum(255);
        EditLightWidth = new QSpinBox(tab_6);
        EditLightWidth->setObjectName("EditLightWidth");
        EditLightWidth->setGeometry(QRect(230, 30, 91, 20));
        EditLightWidth->setMinimum(-255);
        EditLightWidth->setMaximum(255);
        label_37 = new QLabel(tab_6);
        label_37->setObjectName("label_37");
        label_37->setGeometry(QRect(10, 70, 121, 21));
        label_37->setFrameShape(QFrame::Panel);
        label_37->setFrameShadow(QFrame::Sunken);
        label_37->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditConnectLen = new QSpinBox(tab_6);
        EditConnectLen->setObjectName("EditConnectLen");
        EditConnectLen->setGeometry(QRect(140, 70, 91, 22));
        EditConnectLen->setMinimum(-9999);
        EditConnectLen->setMaximum(99999999);
        labelUnitName_8 = new QLabel(tab_6);
        labelUnitName_8->setObjectName("labelUnitName_8");
        labelUnitName_8->setGeometry(QRect(320, 60, 61, 20));
        labelUnitName_8->setFrameShape(QFrame::NoFrame);
        labelUnitName_8->setFrameShadow(QFrame::Sunken);
        labelUnitName_8->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        doubleSpinBoxConnectLenMM = new QDoubleSpinBox(tab_6);
        doubleSpinBoxConnectLenMM->setObjectName("doubleSpinBoxConnectLenMM");
        doubleSpinBoxConnectLenMM->setGeometry(QRect(230, 70, 91, 22));
        QPalette palette;
        QBrush brush(QColor(255, 170, 0, 255));
        brush.setStyle(Qt::BrushStyle::SolidPattern);
        palette.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush);
        palette.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush);
        QBrush brush1(QColor(240, 240, 240, 255));
        brush1.setStyle(Qt::BrushStyle::SolidPattern);
        palette.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush1);
        doubleSpinBoxConnectLenMM->setPalette(palette);
        doubleSpinBoxConnectLenMM->setMaximum(9999999999.000000000000000);
        labelUnitName_3 = new QLabel(tab_6);
        labelUnitName_3->setObjectName("labelUnitName_3");
        labelUnitName_3->setGeometry(QRect(220, 50, 91, 20));
        labelUnitName_3->setFrameShape(QFrame::NoFrame);
        labelUnitName_3->setFrameShadow(QFrame::Sunken);
        labelUnitName_3->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        checkModeEnableOpenRingCheck = new QCheckBox(tab_6);
        checkModeEnableOpenRingCheck->setObjectName("checkModeEnableOpenRingCheck");
        checkModeEnableOpenRingCheck->setGeometry(QRect(20, 110, 291, 20));
        tabWidgetInspect->addTab(tab_6, QString());
        tab_5 = new QWidget();
        tab_5->setObjectName("tab_5");
        EditMinHoleDiameter = new QSpinBox(tab_5);
        EditMinHoleDiameter->setObjectName("EditMinHoleDiameter");
        EditMinHoleDiameter->setGeometry(QRect(140, 60, 91, 20));
        EditMinHoleDiameter->setMinimum(-255);
        EditMinHoleDiameter->setMaximum(255);
        label_17 = new QLabel(tab_5);
        label_17->setObjectName("label_17");
        label_17->setGeometry(QRect(10, 60, 121, 21));
        label_17->setFrameShape(QFrame::Panel);
        label_17->setFrameShadow(QFrame::Sunken);
        label_17->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditMaxShiftHole = new QSpinBox(tab_5);
        EditMaxShiftHole->setObjectName("EditMaxShiftHole");
        EditMaxShiftHole->setGeometry(QRect(140, 120, 91, 20));
        EditMaxShiftHole->setMaximum(99999999);
        label_32 = new QLabel(tab_5);
        label_32->setObjectName("label_32");
        label_32->setGeometry(QRect(10, 120, 121, 20));
        label_32->setFrameShape(QFrame::Panel);
        label_32->setFrameShadow(QFrame::Sunken);
        label_32->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        doubleSpinBoxMinHoleDiameterMM = new QDoubleSpinBox(tab_5);
        doubleSpinBoxMinHoleDiameterMM->setObjectName("doubleSpinBoxMinHoleDiameterMM");
        doubleSpinBoxMinHoleDiameterMM->setGeometry(QRect(230, 60, 91, 22));
        QPalette palette1;
        palette1.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush);
        palette1.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush);
        palette1.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush1);
        doubleSpinBoxMinHoleDiameterMM->setPalette(palette1);
        doubleSpinBoxMinHoleDiameterMM->setMaximum(9999999999.000000000000000);
        doubleSpinBoxMaxShiftHoleMM = new QDoubleSpinBox(tab_5);
        doubleSpinBoxMaxShiftHoleMM->setObjectName("doubleSpinBoxMaxShiftHoleMM");
        doubleSpinBoxMaxShiftHoleMM->setGeometry(QRect(230, 120, 91, 22));
        QPalette palette2;
        palette2.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush);
        palette2.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush);
        palette2.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush1);
        doubleSpinBoxMaxShiftHoleMM->setPalette(palette2);
        doubleSpinBoxMaxShiftHoleMM->setMaximum(9999999999.000000000000000);
        labelUnitName_2 = new QLabel(tab_5);
        labelUnitName_2->setObjectName("labelUnitName_2");
        labelUnitName_2->setGeometry(QRect(220, 40, 91, 20));
        labelUnitName_2->setFrameShape(QFrame::NoFrame);
        labelUnitName_2->setFrameShadow(QFrame::Sunken);
        labelUnitName_2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        doubleSpinBoxMaxHoleDiameterMM = new QDoubleSpinBox(tab_5);
        doubleSpinBoxMaxHoleDiameterMM->setObjectName("doubleSpinBoxMaxHoleDiameterMM");
        doubleSpinBoxMaxHoleDiameterMM->setGeometry(QRect(230, 90, 91, 22));
        QPalette palette3;
        palette3.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush);
        palette3.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush);
        palette3.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush1);
        doubleSpinBoxMaxHoleDiameterMM->setPalette(palette3);
        doubleSpinBoxMaxHoleDiameterMM->setMaximum(9999999999.000000000000000);
        EditMaxHoleDiameter = new QSpinBox(tab_5);
        EditMaxHoleDiameter->setObjectName("EditMaxHoleDiameter");
        EditMaxHoleDiameter->setGeometry(QRect(140, 90, 91, 20));
        EditMaxHoleDiameter->setMinimum(-255);
        EditMaxHoleDiameter->setMaximum(255);
        label_18 = new QLabel(tab_5);
        label_18->setObjectName("label_18");
        label_18->setGeometry(QRect(10, 90, 121, 21));
        label_18->setFrameShape(QFrame::Panel);
        label_18->setFrameShadow(QFrame::Sunken);
        label_18->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_20 = new QLabel(tab_5);
        label_20->setObjectName("label_20");
        label_20->setGeometry(QRect(10, 20, 121, 21));
        label_20->setFrameShape(QFrame::Panel);
        label_20->setFrameShadow(QFrame::Sunken);
        label_20->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditHoleBrightnessAsReference = new QSpinBox(tab_5);
        EditHoleBrightnessAsReference->setObjectName("EditHoleBrightnessAsReference");
        EditHoleBrightnessAsReference->setGeometry(QRect(140, 20, 91, 20));
        EditHoleBrightnessAsReference->setMinimum(-255);
        EditHoleBrightnessAsReference->setMaximum(255);
        tabWidgetInspect->addTab(tab_5, QString());
        tab_7 = new QWidget();
        tab_7->setObjectName("tab_7");
        checkModeEnabled = new QCheckBox(tab_7);
        checkModeEnabled->setObjectName("checkModeEnabled");
        checkModeEnabled->setGeometry(QRect(10, 10, 141, 18));
        checkModeAbsoluteBright = new QCheckBox(tab_7);
        checkModeAbsoluteBright->setObjectName("checkModeAbsoluteBright");
        checkModeAbsoluteBright->setGeometry(QRect(10, 30, 141, 18));
        checkModeCenterBrightFromParts = new QCheckBox(tab_7);
        checkModeCenterBrightFromParts->setObjectName("checkModeCenterBrightFromParts");
        checkModeCenterBrightFromParts->setGeometry(QRect(10, 90, 211, 18));
        checkModeDynamicMask = new QCheckBox(tab_7);
        checkModeDynamicMask->setObjectName("checkModeDynamicMask");
        checkModeDynamicMask->setGeometry(QRect(10, 50, 141, 18));
        checkModeEnableHoleCheck = new QCheckBox(tab_7);
        checkModeEnableHoleCheck->setObjectName("checkModeEnableHoleCheck");
        checkModeEnableHoleCheck->setGeometry(QRect(10, 70, 211, 18));
        checkModeEnableInRound = new QCheckBox(tab_7);
        checkModeEnableInRound->setObjectName("checkModeEnableInRound");
        checkModeEnableInRound->setGeometry(QRect(10, 110, 211, 18));
        checkModeEnableInRound->setAutoFillBackground(false);
        checkModeEnableInRound->setChecked(false);
        checkModeEnableInRound->setAutoRepeat(false);
        checkModeEnableInRound->setAutoExclusive(false);
        checkModeEnableInRound->setTristate(false);
        tabWidgetInspect->addTab(tab_7, QString());
        tab_8 = new QWidget();
        tab_8->setObjectName("tab_8");
        label_26 = new QLabel(tab_8);
        label_26->setObjectName("label_26");
        label_26->setGeometry(QRect(10, 70, 201, 21));
        label_26->setFrameShape(QFrame::Panel);
        label_26->setFrameShadow(QFrame::Sunken);
        label_26->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_25 = new QLabel(tab_8);
        label_25->setObjectName("label_25");
        label_25->setGeometry(QRect(10, 40, 201, 21));
        label_25->setFrameShape(QFrame::Panel);
        label_25->setFrameShadow(QFrame::Sunken);
        label_25->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditAdjustWhite = new QSpinBox(tab_8);
        EditAdjustWhite->setObjectName("EditAdjustWhite");
        EditAdjustWhite->setGeometry(QRect(220, 70, 81, 22));
        EditAdjustWhite->setMaximum(255);
        EditAdjustBlack = new QSpinBox(tab_8);
        EditAdjustBlack->setObjectName("EditAdjustBlack");
        EditAdjustBlack->setGeometry(QRect(220, 40, 81, 22));
        EditAdjustBlack->setMaximum(255);
        tabWidgetInspect->addTab(tab_8, QString());
        Search = new QWidget();
        Search->setObjectName("Search");
        label_27 = new QLabel(Search);
        label_27->setObjectName("label_27");
        label_27->setGeometry(QRect(10, 20, 291, 21));
        label_27->setFrameShape(QFrame::Panel);
        label_27->setFrameShadow(QFrame::Sunken);
        label_27->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditSearchDot = new QSpinBox(Search);
        EditSearchDot->setObjectName("EditSearchDot");
        EditSearchDot->setGeometry(QRect(20, 50, 81, 22));
        EditSearchDot->setMaximum(255);
        labelUnitName_4 = new QLabel(Search);
        labelUnitName_4->setObjectName("labelUnitName_4");
        labelUnitName_4->setGeometry(QRect(210, 50, 91, 20));
        labelUnitName_4->setFrameShape(QFrame::NoFrame);
        labelUnitName_4->setFrameShadow(QFrame::Sunken);
        labelUnitName_4->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        doubleSpinBoxSearchDotMM = new QDoubleSpinBox(Search);
        doubleSpinBoxSearchDotMM->setObjectName("doubleSpinBoxSearchDotMM");
        doubleSpinBoxSearchDotMM->setGeometry(QRect(120, 50, 91, 22));
        QPalette palette4;
        palette4.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush);
        palette4.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush);
        palette4.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush1);
        doubleSpinBoxSearchDotMM->setPalette(palette4);
        doubleSpinBoxSearchDotMM->setReadOnly(true);
        doubleSpinBoxSearchDotMM->setMaximum(9999999999.000000000000000);
        tabWidgetInspect->addTab(Search, QString());
        tab = new QWidget();
        tab->setObjectName("tab");
        doubleSpinBoxExpandForDynamicMaskMM = new QDoubleSpinBox(tab);
        doubleSpinBoxExpandForDynamicMaskMM->setObjectName("doubleSpinBoxExpandForDynamicMaskMM");
        doubleSpinBoxExpandForDynamicMaskMM->setGeometry(QRect(230, 20, 91, 22));
        QPalette palette5;
        palette5.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush);
        palette5.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush);
        palette5.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush1);
        doubleSpinBoxExpandForDynamicMaskMM->setPalette(palette5);
        doubleSpinBoxExpandForDynamicMaskMM->setMaximum(9999999999.000000000000000);
        EditExpandForDynamicMask = new QSpinBox(tab);
        EditExpandForDynamicMask->setObjectName("EditExpandForDynamicMask");
        EditExpandForDynamicMask->setGeometry(QRect(140, 20, 91, 20));
        EditExpandForDynamicMask->setMinimum(-255);
        EditExpandForDynamicMask->setMaximum(255);
        label_19 = new QLabel(tab);
        label_19->setObjectName("label_19");
        label_19->setGeometry(QRect(10, 20, 121, 21));
        label_19->setFrameShape(QFrame::Panel);
        label_19->setFrameShadow(QFrame::Sunken);
        label_19->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        tabWidgetInspect->addTab(tab, QString());
        EditCenterBrightMaster = new QLineEdit(EulerRingL1HistgramForm);
        EditCenterBrightMaster->setObjectName("EditCenterBrightMaster");
        EditCenterBrightMaster->setGeometry(QRect(170, 570, 61, 21));
        QPalette palette6;
        QBrush brush2(QColor(0, 255, 255, 255));
        brush2.setStyle(Qt::BrushStyle::SolidPattern);
        palette6.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush2);
        palette6.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush2);
        QBrush brush3(QColor(192, 192, 192, 255));
        brush3.setStyle(Qt::BrushStyle::SolidPattern);
        palette6.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush3);
        EditCenterBrightMaster->setPalette(palette6);
        EditCenterBrightMaster->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        stackedWidgetParts = new QStackedWidget(EulerRingL1HistgramForm);
        stackedWidgetParts->setObjectName("stackedWidgetParts");
        stackedWidgetParts->setGeometry(QRect(40, 690, 181, 41));
        page = new QWidget();
        page->setObjectName("page");
        stackedWidgetParts->addWidget(page);
        page_3 = new QWidget();
        page_3->setObjectName("page_3");
        ButtonRelrectSaveParts = new QPushButton(page_3);
        ButtonRelrectSaveParts->setObjectName("ButtonRelrectSaveParts");
        ButtonRelrectSaveParts->setGeometry(QRect(0, 0, 171, 41));
        stackedWidgetParts->addWidget(page_3);
        page_2 = new QWidget();
        page_2->setObjectName("page_2");
        stackedWidgetParts->addWidget(page_2);
        label_8 = new QLabel(EulerRingL1HistgramForm);
        label_8->setObjectName("label_8");
        label_8->setGeometry(QRect(540, 10, 131, 21));
        listWidgetHistList = new QListWidget(EulerRingL1HistgramForm);
        listWidgetHistList->setObjectName("listWidgetHistList");
        listWidgetHistList->setGeometry(QRect(410, 630, 181, 91));
        frameThreshold = new QFrame(EulerRingL1HistgramForm);
        frameThreshold->setObjectName("frameThreshold");
        frameThreshold->setGeometry(QRect(510, 10, 21, 21));
        frameThreshold->setFrameShape(QFrame::NoFrame);
        frameThreshold->setFrameShadow(QFrame::Plain);
        label_39 = new QLabel(EulerRingL1HistgramForm);
        label_39->setObjectName("label_39");
        label_39->setGeometry(QRect(40, 590, 121, 21));
        label_39->setFrameShape(QFrame::Panel);
        label_39->setFrameShadow(QFrame::Sunken);
        label_39->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        ButtonClose = new QPushButton(EulerRingL1HistgramForm);
        ButtonClose->setObjectName("ButtonClose");
        ButtonClose->setGeometry(QRect(610, 710, 171, 51));
        ButtonSaveToLibrary = new QPushButton(EulerRingL1HistgramForm);
        ButtonSaveToLibrary->setObjectName("ButtonSaveToLibrary");
        ButtonSaveToLibrary->setGeometry(QRect(40, 670, 171, 41));
        ButtonSaveToLibrary->setAcceptDrops(true);
        frameTarget = new QFrame(EulerRingL1HistgramForm);
        frameTarget->setObjectName("frameTarget");
        frameTarget->setGeometry(QRect(350, 10, 21, 21));
        frameTarget->setFrameShape(QFrame::NoFrame);
        frameTarget->setFrameShadow(QFrame::Plain);
        frame_SimImage = new QFrame(EulerRingL1HistgramForm);
        frame_SimImage->setObjectName("frame_SimImage");
        frame_SimImage->setGeometry(QRect(840, 120, 461, 581));
        frame_SimImage->setFrameShape(QFrame::StyledPanel);
        frame_SimImage->setFrameShadow(QFrame::Sunken);
        label_6 = new QLabel(EulerRingL1HistgramForm);
        label_6->setObjectName("label_6");
        label_6->setGeometry(QRect(240, 400, 20, 181));
        label_6->setFrameShape(QFrame::Panel);
        label_6->setFrameShadow(QFrame::Raised);
        label_6->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_6->setIndent(1);
        frame = new QFrame(EulerRingL1HistgramForm);
        frame->setObjectName("frame");
        frame->setGeometry(QRect(600, 400, 211, 251));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Sunken);
        label_31 = new QLabel(frame);
        label_31->setObjectName("label_31");
        label_31->setGeometry(QRect(0, 0, 201, 21));
        label_31->setFrameShape(QFrame::Panel);
        label_31->setFrameShadow(QFrame::Sunken);
        label_31->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label = new QLabel(frame);
        label->setObjectName("label");
        label->setGeometry(QRect(10, 80, 101, 21));
        label->setFrameShape(QFrame::Panel);
        label->setFrameShadow(QFrame::Sunken);
        label->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_2 = new QLabel(frame);
        label_2->setObjectName("label_2");
        label_2->setGeometry(QRect(10, 130, 101, 21));
        label_2->setFrameShape(QFrame::Panel);
        label_2->setFrameShadow(QFrame::Sunken);
        label_2->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        labelResultHoleDiameter = new QLabel(frame);
        labelResultHoleDiameter->setObjectName("labelResultHoleDiameter");
        labelResultHoleDiameter->setGeometry(QRect(120, 80, 81, 21));
        labelResultHoleDiameter->setFrameShape(QFrame::Panel);
        labelResultHoleDiameter->setFrameShadow(QFrame::Sunken);
        labelResultHoleDiameter->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        labelResultHoleShift = new QLabel(frame);
        labelResultHoleShift->setObjectName("labelResultHoleShift");
        labelResultHoleShift->setGeometry(QRect(120, 130, 81, 21));
        labelResultHoleShift->setFrameShape(QFrame::Panel);
        labelResultHoleShift->setFrameShadow(QFrame::Sunken);
        labelResultHoleShift->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        ButtonCalc = new QPushButton(frame);
        ButtonCalc->setObjectName("ButtonCalc");
        ButtonCalc->setGeometry(QRect(50, 210, 121, 31));
        ButtonCalc->setAcceptDrops(true);
        labelResultHoleDiameterUnit = new QLabel(frame);
        labelResultHoleDiameterUnit->setObjectName("labelResultHoleDiameterUnit");
        labelResultHoleDiameterUnit->setEnabled(false);
        labelResultHoleDiameterUnit->setGeometry(QRect(120, 100, 81, 21));
        QPalette palette7;
        QBrush brush4(QColor(255, 255, 127, 255));
        brush4.setStyle(Qt::BrushStyle::SolidPattern);
        palette7.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush4);
        palette7.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Window, brush);
        palette7.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush4);
        palette7.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Window, brush);
        palette7.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush);
        palette7.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Window, brush);
        labelResultHoleDiameterUnit->setPalette(palette7);
        labelResultHoleDiameterUnit->setAutoFillBackground(true);
        labelResultHoleDiameterUnit->setFrameShape(QFrame::Panel);
        labelResultHoleDiameterUnit->setFrameShadow(QFrame::Sunken);
        labelResultHoleDiameterUnit->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        labelResultHoleShiftUnit = new QLabel(frame);
        labelResultHoleShiftUnit->setObjectName("labelResultHoleShiftUnit");
        labelResultHoleShiftUnit->setGeometry(QRect(120, 150, 81, 21));
        QPalette palette8;
        palette8.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush4);
        palette8.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Window, brush);
        palette8.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush4);
        palette8.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Window, brush);
        palette8.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush);
        palette8.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Window, brush);
        labelResultHoleShiftUnit->setPalette(palette8);
        labelResultHoleShiftUnit->setAutoFillBackground(true);
        labelResultHoleShiftUnit->setFrameShape(QFrame::Panel);
        labelResultHoleShiftUnit->setFrameShadow(QFrame::Sunken);
        labelResultHoleShiftUnit->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        labelUnitName_9 = new QLabel(frame);
        labelUnitName_9->setObjectName("labelUnitName_9");
        labelUnitName_9->setGeometry(QRect(10, 100, 51, 20));
        labelUnitName_9->setFrameShape(QFrame::NoFrame);
        labelUnitName_9->setFrameShadow(QFrame::Sunken);
        labelUnitName_9->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        labelUnitName_10 = new QLabel(frame);
        labelUnitName_10->setObjectName("labelUnitName_10");
        labelUnitName_10->setGeometry(QRect(10, 150, 51, 20));
        labelUnitName_10->setFrameShape(QFrame::NoFrame);
        labelUnitName_10->setFrameShadow(QFrame::Sunken);
        labelUnitName_10->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_10 = new QLabel(frame);
        label_10->setObjectName("label_10");
        label_10->setGeometry(QRect(10, 180, 81, 21));
        label_10->setFrameShape(QFrame::Panel);
        label_10->setFrameShadow(QFrame::Sunken);
        label_10->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        labelResultRing = new QLabel(frame);
        labelResultRing->setObjectName("labelResultRing");
        labelResultRing->setGeometry(QRect(100, 180, 101, 21));
        labelResultRing->setFrameShape(QFrame::Panel);
        labelResultRing->setFrameShadow(QFrame::Sunken);
        labelResultRing->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        labelUnitName_11 = new QLabel(frame);
        labelUnitName_11->setObjectName("labelUnitName_11");
        labelUnitName_11->setGeometry(QRect(10, 50, 51, 20));
        labelUnitName_11->setFrameShape(QFrame::NoFrame);
        labelUnitName_11->setFrameShadow(QFrame::Sunken);
        labelUnitName_11->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        labelMasterHoleDiameter = new QLabel(frame);
        labelMasterHoleDiameter->setObjectName("labelMasterHoleDiameter");
        labelMasterHoleDiameter->setGeometry(QRect(120, 30, 81, 21));
        labelMasterHoleDiameter->setFrameShape(QFrame::Panel);
        labelMasterHoleDiameter->setFrameShadow(QFrame::Sunken);
        labelMasterHoleDiameter->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_11 = new QLabel(frame);
        label_11->setObjectName("label_11");
        label_11->setGeometry(QRect(10, 30, 101, 21));
        label_11->setFrameShape(QFrame::Panel);
        label_11->setFrameShadow(QFrame::Sunken);
        label_11->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        labelMasterHoleDiameterUnit = new QLabel(frame);
        labelMasterHoleDiameterUnit->setObjectName("labelMasterHoleDiameterUnit");
        labelMasterHoleDiameterUnit->setEnabled(false);
        labelMasterHoleDiameterUnit->setGeometry(QRect(120, 50, 81, 21));
        QPalette palette9;
        palette9.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush4);
        palette9.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Window, brush);
        palette9.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush4);
        palette9.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Window, brush);
        palette9.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush);
        palette9.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Window, brush);
        labelMasterHoleDiameterUnit->setPalette(palette9);
        labelMasterHoleDiameterUnit->setAutoFillBackground(true);
        labelMasterHoleDiameterUnit->setFrameShape(QFrame::Panel);
        labelMasterHoleDiameterUnit->setFrameShadow(QFrame::Sunken);
        labelMasterHoleDiameterUnit->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        pushButtonChangeLib = new QPushButton(EulerRingL1HistgramForm);
        pushButtonChangeLib->setObjectName("pushButtonChangeLib");
        pushButtonChangeLib->setGeometry(QRect(200, 510, 31, 23));
        EditLibID = new QLineEdit(EulerRingL1HistgramForm);
        EditLibID->setObjectName("EditLibID");
        EditLibID->setGeometry(QRect(40, 510, 61, 21));
        EditLibID->setReadOnly(true);
        toolButtonSimShowRing = new QToolButton(EulerRingL1HistgramForm);
        toolButtonSimShowRing->setObjectName("toolButtonSimShowRing");
        toolButtonSimShowRing->setGeometry(QRect(1000, 20, 141, 41));
        toolButtonSimShowRing->setCheckable(true);
        toolButtonSimShowRing->setChecked(true);
        pushButtonTransmitItemNameAll = new QPushButton(EulerRingL1HistgramForm);
        pushButtonTransmitItemNameAll->setObjectName("pushButtonTransmitItemNameAll");
        pushButtonTransmitItemNameAll->setGeometry(QRect(180, 460, 51, 23));
        EditLibName = new QLineEdit(EulerRingL1HistgramForm);
        EditLibName->setObjectName("EditLibName");
        EditLibName->setGeometry(QRect(100, 510, 101, 21));
        EditLibName->setReadOnly(true);
        label_4 = new QLabel(EulerRingL1HistgramForm);
        label_4->setObjectName("label_4");
        label_4->setGeometry(QRect(40, 490, 62, 20));
        label_4->setFrameShape(QFrame::Panel);
        label_4->setFrameShadow(QFrame::Sunken);
        label_4->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditCenterBrightTarget = new QLineEdit(EulerRingL1HistgramForm);
        EditCenterBrightTarget->setObjectName("EditCenterBrightTarget");
        EditCenterBrightTarget->setGeometry(QRect(170, 590, 61, 21));
        QPalette palette10;
        palette10.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush2);
        palette10.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush2);
        palette10.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush3);
        EditCenterBrightTarget->setPalette(palette10);
        EditCenterBrightTarget->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        frameLayer = new QFrame(EulerRingL1HistgramForm);
        frameLayer->setObjectName("frameLayer");
        frameLayer->setGeometry(QRect(50, 400, 171, 41));
        frameLayer->setFrameShape(QFrame::NoFrame);
        frameLayer->setFrameShadow(QFrame::Plain);
        frameLineGraph = new QFrame(EulerRingL1HistgramForm);
        frameLineGraph->setObjectName("frameLineGraph");
        frameLineGraph->setGeometry(QRect(30, 40, 781, 351));
        frameLineGraph->setFrameShape(QFrame::NoFrame);
        frameLineGraph->setFrameShadow(QFrame::Plain);
        toolButtonSimShowBlock = new QToolButton(EulerRingL1HistgramForm);
        toolButtonSimShowBlock->setObjectName("toolButtonSimShowBlock");
        toolButtonSimShowBlock->setGeometry(QRect(840, 20, 141, 41));
        toolButtonSimShowBlock->setCheckable(true);
        toolButtonSimShowBlock->setChecked(true);
        ButtonRelrectOnlyBlock = new QPushButton(EulerRingL1HistgramForm);
        ButtonRelrectOnlyBlock->setObjectName("ButtonRelrectOnlyBlock");
        ButtonRelrectOnlyBlock->setGeometry(QRect(40, 620, 171, 41));
        ButtonRelrectOnlyBlock->setAcceptDrops(true);
        toolButtonSimShowHole = new QToolButton(EulerRingL1HistgramForm);
        toolButtonSimShowHole->setObjectName("toolButtonSimShowHole");
        toolButtonSimShowHole->setGeometry(QRect(840, 60, 141, 41));
        toolButtonSimShowHole->setCheckable(true);
        toolButtonSimShowHole->setChecked(true);
        toolButtonSimShowMask = new QToolButton(EulerRingL1HistgramForm);
        toolButtonSimShowMask->setObjectName("toolButtonSimShowMask");
        toolButtonSimShowMask->setGeometry(QRect(1000, 60, 141, 41));
        toolButtonSimShowMask->setCheckable(true);
        toolButtonSimShowMask->setChecked(true);
        toolButtonSimShowNGMark = new QToolButton(EulerRingL1HistgramForm);
        toolButtonSimShowNGMark->setObjectName("toolButtonSimShowNGMark");
        toolButtonSimShowNGMark->setGeometry(QRect(1160, 20, 141, 41));
        toolButtonSimShowNGMark->setCheckable(true);
        toolButtonSimShowNGMark->setChecked(true);
        pushButtonRestore = new QPushButton(EulerRingL1HistgramForm);
        pushButtonRestore->setObjectName("pushButtonRestore");
        pushButtonRestore->setGeometry(QRect(220, 720, 171, 41));
        pushButtonRestore->setAcceptDrops(true);

        retranslateUi(EulerRingL1HistgramForm);

        tabWidgetInspect->setCurrentIndex(1);
        stackedWidgetParts->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(EulerRingL1HistgramForm);
    } // setupUi

    void retranslateUi(QWidget *EulerRingL1HistgramForm)
    {
        EulerRingL1HistgramForm->setWindowTitle(QCoreApplication::translate("EulerRingL1HistgramForm", "EulerRingL1 histogram", nullptr));
        label_40->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "\345\275\223\350\251\262\347\256\207\346\211\200\343\201\256\343\203\220\343\203\251\343\201\244\343\201\215\343\202\260\343\203\251\343\203\225", nullptr));
        pushButtonSimShowCenterPos->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "\345\276\251\345\270\260", nullptr));
        label_38->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "\343\203\236\343\202\271\343\202\277\343\203\274\344\270\255\345\277\203\350\274\235\345\272\246", nullptr));
        label_7->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "\346\244\234\346\237\273\347\224\273\345\203\217", nullptr));
        label_5->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "\343\203\251\343\202\244\343\203\226\343\203\251\343\203\252\345\220\215\347\247\260", nullptr));
        ButtonReflectAllBlocks->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "\345\220\214\344\270\200\347\250\256\351\241\236\343\201\256\351\240\230\345\237\237\343\201\253\345\217\215\346\230\240", nullptr));
        ButtonLoadFromLibrary->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "\343\203\251\343\202\244\343\203\226\343\203\251\343\203\252\343\201\213\343\202\211\350\252\255\343\201\277\345\207\272\343\201\227", nullptr));
        label_9->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "Item name", nullptr));
        label_3->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "\343\203\236\343\202\271\343\202\277\343\203\274\347\224\273\345\203\217", nullptr));
        EditItemName->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "XXX", nullptr));
        radioButtonLightSide1->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "Light", nullptr));
        radioButtonDarkSide1->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "Dark", nullptr));
        label_23->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "\346\232\227\345\201\264", nullptr));
        label_22->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "OK\350\274\235\345\272\246\347\257\204\345\233\262", nullptr));
        label_21->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "\346\230\216\345\201\264", nullptr));
        label_37->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "\346\216\245\347\266\232\350\267\235\351\233\242", nullptr));
        labelUnitName_8->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "mm", nullptr));
        labelUnitName_3->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "mm", nullptr));
        checkModeEnableOpenRingCheck->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "\345\272\247\345\210\207\343\202\214\346\244\234\346\237\273\343\202\222\345\256\237\350\241\214", nullptr));
        tabWidgetInspect->setTabText(tabWidgetInspect->indexOf(tab_6), QCoreApplication::translate("EulerRingL1HistgramForm", "Ring", nullptr));
        label_17->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "\346\234\200\345\260\217\347\251\264\345\276\204", nullptr));
        label_32->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "\347\251\264\347\247\273\345\213\225\347\257\204\345\233\262", nullptr));
        labelUnitName_2->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "mm", nullptr));
        label_18->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "\346\234\200\345\244\247\347\251\264\345\276\204", nullptr));
        label_20->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "\345\217\202\350\200\203\350\274\235\345\272\246", nullptr));
        tabWidgetInspect->setTabText(tabWidgetInspect->indexOf(tab_5), QCoreApplication::translate("EulerRingL1HistgramForm", "Hole", nullptr));
        checkModeEnabled->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "\346\244\234\346\237\273\346\234\211\345\212\271", nullptr));
        checkModeAbsoluteBright->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "\347\265\266\345\257\276\350\274\235\345\272\246", nullptr));
        checkModeCenterBrightFromParts->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "\351\203\250\345\223\201\343\201\213\343\202\211\350\274\235\345\272\246\343\202\222\346\212\275\345\207\272\343\201\231\343\202\213", nullptr));
        checkModeDynamicMask->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "\345\256\237\350\241\214\343\203\236\343\202\271\343\202\257\347\224\237\346\210\220", nullptr));
        checkModeEnableHoleCheck->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "\347\251\264\345\210\244\345\256\232\343\202\222\350\241\214\343\201\206", nullptr));
        checkModeEnableInRound->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "Enable in Round", nullptr));
        tabWidgetInspect->setTabText(tabWidgetInspect->indexOf(tab_7), QCoreApplication::translate("EulerRingL1HistgramForm", "\345\261\236\346\200\247", nullptr));
        label_26->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "\346\230\216\345\201\264\343\200\200\346\234\200\345\244\247\350\243\234\346\255\243\350\274\235\345\272\246\351\207\217", nullptr));
        label_25->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "\346\232\227\345\201\264\343\200\200\346\234\200\345\244\247\350\243\234\346\255\243\350\274\235\345\272\246\351\207\217", nullptr));
        tabWidgetInspect->setTabText(tabWidgetInspect->indexOf(tab_8), QCoreApplication::translate("EulerRingL1HistgramForm", "\350\243\234\346\255\243", nullptr));
        label_27->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "Search area (Pixel)", nullptr));
        labelUnitName_4->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "mm", nullptr));
        tabWidgetInspect->setTabText(tabWidgetInspect->indexOf(Search), QCoreApplication::translate("EulerRingL1HistgramForm", "Search", nullptr));
        label_19->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "\343\203\236\343\202\271\343\202\257\350\206\250\345\274\265\343\203\211\343\203\203\343\203\210", nullptr));
        tabWidgetInspect->setTabText(tabWidgetInspect->indexOf(tab), QCoreApplication::translate("EulerRingL1HistgramForm", "\343\203\236\343\202\271\343\202\257\347\224\237\346\210\220", nullptr));
        ButtonRelrectSaveParts->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "\351\203\250\345\223\201\344\277\235\345\255\230", nullptr));
        label_8->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "\343\201\227\343\201\215\343\201\204\345\200\244", nullptr));
        label_39->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "Target\344\270\255\345\277\203\350\274\235\345\272\246", nullptr));
        ButtonClose->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "\351\226\211\343\201\230\343\202\213", nullptr));
        ButtonSaveToLibrary->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "\343\203\251\343\202\244\343\203\226\343\203\251\343\203\252\343\201\253\344\277\235\345\255\230", nullptr));
        label_6->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "\346\244\234\n"
"\346\237\273", nullptr));
        label_31->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "\345\275\223\350\251\262\347\256\207\346\211\200\343\201\256\345\210\244\345\256\232\347\265\220\346\236\234", nullptr));
        label->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "\347\251\264\345\276\204", nullptr));
        label_2->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "\347\251\264\343\201\232\343\202\214", nullptr));
        labelResultHoleDiameter->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "123", nullptr));
        labelResultHoleShift->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "123", nullptr));
        ButtonCalc->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "\350\250\210\347\256\227", nullptr));
        labelResultHoleDiameterUnit->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "123", nullptr));
        labelResultHoleShiftUnit->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "123", nullptr));
        labelUnitName_9->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "mm", nullptr));
        labelUnitName_10->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "mm", nullptr));
        label_10->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "Ring", nullptr));
        labelResultRing->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "123", nullptr));
        labelUnitName_11->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "mm", nullptr));
        labelMasterHoleDiameter->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "123", nullptr));
        label_11->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "\345\237\272\346\272\226\347\251\264\345\276\204", nullptr));
        labelMasterHoleDiameterUnit->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "123", nullptr));
        pushButtonChangeLib->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "...", nullptr));
        EditLibID->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "12345", nullptr));
        toolButtonSimShowRing->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "Ring", nullptr));
        pushButtonTransmitItemNameAll->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "To all", nullptr));
        EditLibName->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "XXX", nullptr));
        label_4->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "\343\203\251\343\202\244\343\203\226\343\203\251\343\203\252\357\274\251\357\274\244", nullptr));
        toolButtonSimShowBlock->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "Block", nullptr));
        ButtonRelrectOnlyBlock->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "\343\201\223\343\201\256\343\203\226\343\203\255\343\203\203\343\202\257\343\201\240\343\201\221\343\201\253\345\217\215\346\230\240", nullptr));
        toolButtonSimShowHole->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "Hole", nullptr));
        toolButtonSimShowMask->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "Mask", nullptr));
        toolButtonSimShowNGMark->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "NG mark", nullptr));
        pushButtonRestore->setText(QCoreApplication::translate("EulerRingL1HistgramForm", "Restore", nullptr));
    } // retranslateUi

};

namespace Ui {
    class EulerRingL1HistgramForm: public Ui_EulerRingL1HistgramForm {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_EULERRINGL1HISTGRAMFORM_H
