#ifndef SIGNALRESULTDONETOMASTER_GLOBAL_H
#define SIGNALRESULTDONETOMASTER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SIGNALRESULTDONETOMASTER_LIB
# define SIGNALRESULTDONETOMASTER_EXPORT Q_DECL_EXPORT
#else
# define SIGNALRESULTDONETOMASTER_EXPORT Q_DECL_IMPORT
#endif

#endif // SIGNALRESULTDONETOMASTER_GLOBAL_H
