#ifndef DISPLAYSTATUS_GLOBAL_H
#define DISPLAYSTATUS_GLOBAL_H

#include <qglobal.h>

#ifdef DISPLAYSTATUS_LIB
# define DISPLAYSTATUS_EXPORT Q_DECL_EXPORT
#else
# define DISPLAYSTATUS_EXPORT Q_DECL_IMPORT
#endif

#endif // DISPLAYSTATUS_GLOBAL_H
