#ifndef PROPERTYALIGNMENTFLEXAREA_GLOBAL_H
#define PROPERTYALIGNMENTFLEXAREA_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PROPERTYALIGNMENTFLEXAREA_LIB
# define PROPERTYALIGNMENTFLEXAREA_EXPORT Q_DECL_EXPORT
#else
# define PROPERTYALIGNMENTFLEXAREA_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTYALIGNMENTFLEXAREA_GLOBAL_H
