#ifndef PROPERTYEULERRINGL1_GLOBAL_H
#define PROPERTYEULERRINGL1_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PROPERTYEULERRINGL1_LIB
# define PROPERTYEULERRINGL1_EXPORT Q_DECL_EXPORT
#else
# define PROPERTYEULERRINGL1_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTYEULERRINGL1_GLOBAL_H
