#ifndef CONTECBITACCESS_GLOBAL_H
#define CONTECBITACCESS_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef CONTECBITACCESS_LIB
# define CONTECBITACCESS_EXPORT Q_DECL_EXPORT
#else
# define CONTECBITACCESS_EXPORT Q_DECL_IMPORT
#endif

#endif // CONTECBITACCESS_GLOBAL_H
