#ifndef AREASHADERIMAGEPANEL_GLOBAL_H
#define AREASHADERIMAGEPANEL_GLOBAL_H

#include <qglobal.h>

#ifdef AREASHADERIMAGEPANEL_LIB
# define AREASHADERIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define AREASHADERIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // AREASHADERIMAGEPANEL_GLOBAL_H
