#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(SHIFTIMSGEINLAYERPAGE_LIB)
#  define SHIFTIMSGEINLAYERPAGE_EXPORT Q_DECL_EXPORT
# else
#  define SHIFTIMSGEINLAYERPAGE_EXPORT Q_DECL_IMPORT
# endif
#else
# define SHIFTIMSGEINLAYERPAGE_EXPORT
#endif
