#ifndef NGIMAGEFORREVIEW_GLOBAL_H
#define NGIMAGEFORREVIEW_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef NGIMAGEFORREVIEW_LIB
# define NGIMAGEFORREVIEW_EXPORT Q_DECL_EXPORT
#else
# define NGIMAGEFORREVIEW_EXPORT Q_DECL_IMPORT
#endif

#endif // NGIMAGEFORREVIEW_GLOBAL_H
