#ifndef INTEGRATIONSHOWNAME_GLOBAL_H
#define INTEGRATIONSHOWNAME_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef INTEGRATIONSHOWNAME_LIB
# define INTEGRATIONSHOWNAME_EXPORT Q_DECL_EXPORT
#else
# define INTEGRATIONSHOWNAME_EXPORT Q_DECL_IMPORT
#endif

#endif // INTEGRATIONSHOWNAME_GLOBAL_H
