#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(COLORCORRECTORIMAGEPANEL_LIB)
#  define COLORCORRECTORIMAGEPANEL_EXPORT Q_DECL_EXPORT
# else
#  define COLORCORRECTORIMAGEPANEL_EXPORT Q_DECL_IMPORT
# endif
#else
# define COLORCORRECTORIMAGEPANEL_EXPORT
#endif
