#ifndef BUTTONTRANSFERREQUIREMASTERDATA_GLOBAL_H
#define BUTTONTRANSFERREQUIREMASTERDATA_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONTRANSFERREQUIREMASTERDATA_LIB
# define BUTTONTRANSFERREQUIREMASTERDATA_EXPORT Q_DECL_EXPORT
#else
# define BUTTONTRANSFERREQUIREMASTERDATA_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONTRANSFERREQUIREMASTERDATA_GLOBAL_H
