#ifndef DISPLAYNGLISTBUTTON_GLOBAL_H
#define DISPLAYNGLISTBUTTON_GLOBAL_H

#include <qglobal.h>

#ifdef DISPLAYNGLISTBUTTON_LIB
# define DISPLAYNGLISTBUTTON_EXPORT Q_DECL_EXPORT
#else
# define DISPLAYNGLISTBUTTON_EXPORT Q_DECL_IMPORT
#endif

#endif // DISPLAYNGLISTBUTTON_GLOBAL_H
