#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(RESULTXMLMULTIDELIVERY_LIB)
#  define RESULTXMLMULTIDELIVERY_EXPORT Q_DECL_EXPORT
# else
#  define RESULTXMLMULTIDELIVERY_EXPORT Q_DECL_IMPORT
# endif
#else
# define RESULTXMLMULTIDELIVERY_EXPORT
#endif
