# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = ConvertPixImage
DESTDIR = ../../
CONFIG += debug
DEFINES += QT_LARGEFILE_SUPPORT
LIBS += -L"./../../Lib/Release" \
    -lServiceLib
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += .
RCC_DIR += .
include(ConvertPixImage.pri)
win32:RC_FILE = ConvertPixImage.rc
