#ifndef GENERALGROUP_GLOBAL_H
#define GENERALGROUP_GLOBAL_H

#include <qglobal.h>

#ifdef GENERALGROUP_LIB
# define GENERALGROUP_EXPORT Q_DECL_EXPORT
#else
# define GENERALGROUP_EXPORT Q_DECL_IMPORT
#endif

#endif // GENERALGROUP_GLOBAL_H
