#ifndef MEASUREHOLEPOS_GLOBAL_H
#define MEASUREHOLEPOS_GLOBAL_H

#include <qglobal.h>

#ifdef MEASUREHOLEPOS_LIB
# define MEASUREHOLEPOS_EXPORT Q_DECL_EXPORT
#else
# define MEASUREHOLEPOS_EXPORT Q_DECL_IMPORT
#endif

#endif // MEASUREHOLEPOS_GLOBAL_H
