#ifndef SHOWBLADESETTING_GLOBAL_H
#define SHOWBLADESETTING_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SHOWBLADESETTING_LIB
# define SHOWBLADESETTING_EXPORT Q_DECL_EXPORT
#else
# define SHOWBLADESETTING_EXPORT Q_DECL_IMPORT
#endif

#endif // SHOWBLADESETTING_GLOBAL_H
