#ifndef LIGHTDLL4PORT_GLOBAL_H
#define LIGHTDLL4PORT_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef LIGHTDLL4PORT_LIB
# define LIGHTDLL4PORT_EXPORT Q_DECL_EXPORT
#else
# define LIGHTDLL4PORT_EXPORT Q_DECL_IMPORT
#endif

#endif // LIGHTDLL4PORT_GLOBAL_H
