#ifndef EULERRINGL1IMAGEPANEL_GLOBAL_H
#define EULERRINGL1IMAGEPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef EULERRINGL1IMAGEPANEL_LIB
# define EULERRINGL1IMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define EULERRINGL1IMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // EULERRINGL1IMAGEPANEL_GLOBAL_H
