#ifndef HOUGHINSPECTIONIMAGEPANEL_GLOBAL_H
#define HOUGHINSPECTIONIMAGEPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef HOUGHINSPECTIONIMAGEPANEL_LIB
# define HOUGHINSPECTIONIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define HOUGHINSPECTIONIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // HOUGHINSPECTIONIMAGEPANEL_GLOBAL_H
