#ifndef PIECEFORREVIEWIMAGEPANEL_GLOBAL_H
#define PIECEFORREVIEWIMAGEPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PIECEFORREVIEWIMAGEPANEL_LIB
# define PIECEFORREVIEWIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define PIECEFORREVIEWIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // PIECEFORREVIEWIMAGEPANEL_GLOBAL_H
