#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(INTEGRATIONSHOWTHRESHOLDLEVEL_LIB)
#  define INTEGRATIONSHOWTHRESHOLDLEVEL_EXPORT Q_DECL_EXPORT
# else
#  define INTEGRATIONSHOWTHRESHOLDLEVEL_EXPORT Q_DECL_IMPORT
# endif
#else
# define INTEGRATIONSHOWTHRESHOLDLEVEL_EXPORT
#endif
