#ifndef SHOWKIDAMEASURERESULT_GLOBAL_H
#define SHOWKIDAMEASURERESULT_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SHOWKIDAMEASURERESULT_LIB
# define SHOWKIDAMEASURERESULT_EXPORT Q_DECL_EXPORT
#else
# define SHOWKIDAMEASURERESULT_EXPORT Q_DECL_IMPORT
#endif

#endif // SHOWKIDAMEASURERESULT_GLOBAL_H
