#ifndef FILTERBRIGHTNESSTHRESHOLDCONVERT_GLOBAL_H
#define FILTERBRIGHTNESSTHRESHOLDCONVERT_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef FILTERBRIGHTNESSTHRESHOLDCONVERT_LIB
# define FILTERBRIGHTNESSTHRESHOLDCONVERT_EXPORT Q_DECL_EXPORT
#else
# define FILTERBRIGHTNESSTHRESHOLDCONVERT_EXPORT Q_DECL_IMPORT
#endif

#endif // FILTERBRIGHTNESSTHRESHOLDCONVERT_GLOBAL_H
