#ifndef SHOWOLDNGNAMING_GLOBAL_H
#define SHOWOLDNGNAMING_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SHOWOLDNGNAMING_LIB
# define SHOWOLDNGNAMING_EXPORT Q_DECL_EXPORT
#else
# define SHOWOLDNGNAMING_EXPORT Q_DECL_IMPORT
#endif

#endif // SHOWOLDNGNAMING_GLOBAL_H
