#ifndef SHOWRESULTSMALLLOT_GLOBAL_H
#define SHOWRESULTSMALLLOT_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SHOWRESULTSMALLLOT_LIB
# define SHOWRESULTSMALLLOT_EXPORT Q_DECL_EXPORT
#else
# define SHOWRESULTSMALLLOT_EXPORT Q_DECL_IMPORT
#endif

#endif // SHOWRESULTSMALLLOT_GLOBAL_H
