#ifndef KOREAST8CHGUI_GLOBAL_H
#define KOREAST8CHGUI_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef KOREAST8CHGUI_LIB
# define KOREAST8CHGUI_EXPORT Q_DECL_EXPORT
#else
# define KOREAST8CHGUI_EXPORT Q_DECL_IMPORT
#endif

#endif // KOREAST8CHGUI_GLOBAL_H
