#ifndef COMPRESSIMAGEINDICATOR_GLOBAL_H
#define COMPRESSIMAGEINDICATOR_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef COMPRESSIMAGEINDICATOR_LIB
# define COMPRESSIMAGEINDICATOR_EXPORT Q_DECL_EXPORT
#else
# define COMPRESSIMAGEINDICATOR_EXPORT Q_DECL_IMPORT
#endif

#endif // COMPRESSIMAGEINDICATOR_GLOBAL_H
