#ifndef BUTTONSHOWRESULTANALIZER_GLOBAL_H
#define BUTTONSHOWRESULTANALIZER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONSHOWRESULTANALIZER_LIB
# define BUTTONSHOWRESULTANALIZER_EXPORT Q_DECL_EXPORT
#else
# define BUTTONSHOWRESULTANALIZER_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONSHOWRESULTANALIZER_GLOBAL_H
