#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(INTEGRATIONSTOPUPDATETHUMBNAIL_LIB)
#  define INTEGRATIONSTOPUPDATETHUMBNAIL_EXPORT Q_DECL_EXPORT
# else
#  define INTEGRATIONSTOPUPDATETHUMBNAIL_EXPORT Q_DECL_IMPORT
# endif
#else
# define INTEGRATIONSTOPUPDATETHUMBNAIL_EXPORT
#endif
