# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = CameraXtiumFx8ColorMonoLineTrigger
DESTDIR = ../../
CONFIG += debug
DEFINES += QT_LARGEFILE_SUPPORT CAMERAXTIUMFX8COLORMONOLINETRIGGER_LIB
LIBS += -L"./../../../Lib/Release" \
    -L"$(SAPERA)/lib/Win64" \
    -lcorapi \
    -lSapClassBasic \
    -lComponent \
    -lServiceLib
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += .
RCC_DIR += ./GeneratedFiles
include(CameraXtiumFx8ColorMonoLineTrigger.pri)
