#ifndef BUTTONSAVEHISTOGRAMDATA_GLOBAL_H
#define BUTTONSAVEHISTOGRAMDATA_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONSAVEHISTOGRAMDATA_LIB
# define BUTTONSAVEHISTOGRAMDATA_EXPORT Q_DECL_EXPORT
#else
# define BUTTONSAVEHISTOGRAMDATA_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONSAVEHISTOGRAMDATA_GLOBAL_H
