#ifndef SHOWCHECKEVERYDAY_GLOBAL_H
#define SHOWCHECKEVERYDAY_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SHOWCHECKEVERYDAY_LIB
# define SHOWCHECKEVERYDAY_EXPORT Q_DECL_EXPORT
#else
# define SHOWCHECKEVERYDAY_EXPORT Q_DECL_IMPORT
#endif

#endif // SHOWCHECKEVERYDAY_GLOBAL_H
