#ifndef EASYPROPERTYDOTCOLORMATCH_GLOBAL_H
#define EASYPROPERTYDOTCOLORMATCH_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef EASYPROPERTYDOTCOLORMATCH_LIB
# define EASYPROPERTYDOTCOLORMATCH_EXPORT Q_DECL_EXPORT
#else
# define EASYPROPERTYDOTCOLORMATCH_EXPORT Q_DECL_IMPORT
#endif

#endif // EASYPROPERTYDOTCOLORMATCH_GLOBAL_H
