#ifndef VIDEOCONTROLLER_GLOBAL_H
#define VIDEOCONTROLLER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef VIDEOCONTROLLER_LIB
# define VIDEOCONTROLLER_EXPORT Q_DECL_EXPORT
#else
# define VIDEOCONTROLLER_EXPORT Q_DECL_IMPORT
#endif

#endif // VIDEOCONTROLLER_GLOBAL_H
