/********************************************************************************
** Form generated from reading UI file 'EditWizardParameter.ui'
**
** Created by: Qt User Interface Compiler version 6.10.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_EDITWIZARDPARAMETER_H
#define UI_EDITWIZARDPARAMETER_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QListView>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QProgressBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_EditWizardParameterClass
{
public:
    QWidget *centralWidget;
    QLineEdit *lineEditFileName;
    QLabel *label;
    QPushButton *pushButtonSearchFileName;
    QStackedWidget *stackedWidget;
    QWidget *Resolution;
    QLabel *label_2;
    QLabel *label_3;
    QDoubleSpinBox *doubleSpinBoxTransformUnitPerPixel;
    QPushButton *pushButtonNext1;
    QLabel *label_69;
    QSpinBox *spinBoxSmallNumberFigure;
    QWidget *page_2;
    QLabel *label_5;
    QGroupBox *groupBox;
    QRadioButton *radioButtonMono;
    QRadioButton *radioButtonColor;
    QSpinBox *spinBoxLayerNumb;
    QLabel *label_6;
    QPushButton *pushButtonNext2;
    QPushButton *pushButtonPrevious2;
    QWidget *page;
    QLabel *label_7;
    QFrame *frame_3;
    QDoubleSpinBox *doubleSpinBoxYMilimeter;
    QDoubleSpinBox *doubleSpinBoxXMilimeter;
    QLabel *label_8;
    QLabel *label_9;
    QFrame *frame_4;
    QLabel *label_10;
    QLabel *label_11;
    QSpinBox *spinBoxDotPerLine;
    QSpinBox *spinBoxMaxLines;
    QPushButton *pushButtonMMToPixel;
    QPushButton *pushButtonPixelToMM;
    QPushButton *pushButtonNext3;
    QPushButton *pushButtonPrevious3;
    QWidget *page_3;
    QLabel *label_12;
    QPushButton *pushButtonNext4;
    QPushButton *pushButtonPrevious4;
    QFrame *frame_5;
    QLabel *label_13;
    QLabel *label_14;
    QSpinBox *spinBoxPhaseNumb;
    QSpinBox *spinBoxTotalCameraNumb;
    QSpinBox *spinBoxPageNumb;
    QLabel *label_53;
    QWidget *page_4;
    QPushButton *pushButtonPrevious5;
    QPushButton *pushButtonNext5;
    QLabel *label_15;
    QLabel *label_16;
    QLineEdit *lineEditLocalDatabase_HostName;
    QLabel *label_17;
    QLineEdit *lineEditLocalDatabase_FileName;
    QPushButton *pushButtonLocalDatabase_FileName;
    QLabel *label_18;
    QSpinBox *spinBoxLocalDatabase_Port;
    QLabel *label_24;
    QLineEdit *lineEditDatabaseDDL_FileName;
    QPushButton *pushButtonDatabaseDDL_FileName;
    QWidget *page_5;
    QLabel *label_19;
    QPushButton *pushButtonNext6;
    QPushButton *pushButtonPrevious6;
    QLineEdit *lineEditImageFilePath;
    QLabel *label_20;
    QPushButton *pushButtonImageFilePath;
    QWidget *page_6;
    QPushButton *pushButtonPrevious7;
    QLabel *label_21;
    QPushButton *pushButtonNext7;
    QPushButton *pushButtonSequence_FileName;
    QLineEdit *lineEditSequence_FileName;
    QLabel *label_22;
    QLineEdit *lineEditIODLL_FileName;
    QPushButton *pushButtonIODLL_FileName;
    QLabel *label_23;
    QLabel *label_25;
    QLineEdit *lineEditIODefine_FileName;
    QPushButton *pushButtonIODefine_FileName;
    QLabel *label_26;
    QLineEdit *lineEditIOSomething;
    QWidget *page_7;
    QLabel *label_27;
    QPushButton *pushButtonNext8;
    QPushButton *pushButtonPrevious8;
    QLineEdit *lineEditCameraSetting_FileName;
    QPushButton *pushButtonCameraSetting_FileName;
    QLabel *label_28;
    QLabel *label_29;
    QPushButton *pushButtonCameraDLL_FileName;
    QLineEdit *lineEditCameraDLL_FileName;
    QLabel *label_30;
    QLineEdit *lineEditCameraAllocation;
    QLabel *label_70;
    QLineEdit *lineEditCameraDLL_FileName2;
    QLabel *label_71;
    QLineEdit *lineEditCameraAllocation2;
    QPushButton *pushButtonCameraDLL_FileName2;
    QPushButton *pushButtonCameraAllocation;
    QPushButton *pushButtonCameraAllocation2;
    QWidget *page_8;
    QPushButton *pushButtonNext9;
    QPushButton *pushButtonPrevious9;
    QLabel *label_31;
    QLineEdit *lineEditResultDLLFileName;
    QLabel *label_32;
    QPushButton *pushButtonResultDLLFileName;
    QLabel *label_33;
    QSpinBox *spinBoxMaxNGCountsPerCam;
    QLabel *label_34;
    QSpinBox *spinBoxMaxNGImageNumbPerPage;
    QLabel *label_35;
    QSpinBox *spinBoxMaxInspectMilisec;
    QLabel *label_36;
    QSpinBox *spinBoxNGCacheNumb;
    QLabel *label_37;
    QCheckBox *checkBoxOutputResult;
    QWidget *page_15;
    QPushButton *pushButtonPrevious10;
    QPushButton *pushButtonNext10;
    QLabel *label_51;
    QLabel *label_52;
    QCheckBox *checkBoxAllocateMasterBuff;
    QCheckBox *checkBoxAllocateTargetBuff;
    QLabel *label_54;
    QLabel *label_55;
    QCheckBox *checkBoxAllocRawTargetBuffForNGImage;
    QLabel *label_56;
    QCheckBox *checkBoxAllocCamTargetBuffer;
    QLabel *label_57;
    QCheckBox *checkBoxAllocViewTargetBuffer;
    QLabel *label_58;
    QSpinBox *spinBoxSwapOutSizeMegaByte;
    QTableWidget *tableWidgetShowMemory;
    QPushButton *pushButtonCalcMemory;
    QWidget *page_9;
    QPushButton *pushButtonPrevious11;
    QPushButton *pushButtonNext11;
    QLabel *label_38;
    QLabel *label_48;
    QLineEdit *lineEditFilterDefFile;
    QPushButton *pushButtonFilterDefFile;
    QTableWidget *tableWidgetFilterListInPage;
    QListView *listViewFilterList;
    QComboBox *comboBoxPhaseForFIlter;
    QLabel *label_72;
    QWidget *page_10;
    QLabel *label_39;
    QPushButton *pushButtonPrevious12;
    QPushButton *pushButtonNext12;
    QLabel *label_59;
    QSpinBox *spinBoxMaxWaitingCommMilisec;
    QLabel *label_60;
    QCheckBox *checkBoxMaster;
    QStackedWidget *stackedWidget_2;
    QWidget *Master;
    QTableWidget *tableWidgetSlaveList;
    QWidget *Slave;
    QLabel *label_73;
    QLineEdit *lineEditIPAddressInSlave;
    QWidget *page_11;
    QLabel *label_40;
    QPushButton *pushButtonPrevious13;
    QPushButton *pushButtonNext13;
    QTableWidget *tableWidgetOutlineOffsetList;
    QPushButton *pushButtonOTileXutlineOffset;
    QPushButton *pushButtonOutlineOffsetTileY;
    QLabel *label_66;
    QComboBox *comboBoxOutlineOffsetMachine;
    QLabel *label_67;
    QComboBox *comboBoxOutlineOffsetPhase;
    QWidget *page_12;
    QLabel *label_41;
    QPushButton *pushButtonPrevious14;
    QPushButton *pushButtonNext14;
    QLabel *label_42;
    QPushButton *pushButtonLightSettingFileName;
    QLineEdit *lineEditLightDLLFileName;
    QLabel *label_43;
    QLineEdit *lineEditLightSettingFileName;
    QLabel *label_44;
    QLineEdit *lineEditLightParamStr;
    QPushButton *pushButtonLightDLLFileName;
    QLabel *label_45;
    QLineEdit *lineEditLightParamStr2;
    QLabel *label_46;
    QPushButton *pushButtonLightDLLFileName2;
    QLineEdit *lineEditLightDLLFileName2;
    QCheckBox *checkBoxInitialLightON;
    QLabel *label_47;
    QWidget *page_13;
    QPushButton *pushButtonNext15;
    QPushButton *pushButtonPrevious15;
    QLabel *label_49;
    QLabel *label_61;
    QLineEdit *lineEditSyncGUIFileName;
    QPushButton *pushButtonSyncGUIFileName;
    QLineEdit *lineEditSyncGUIPartnerIP;
    QLabel *label_62;
    QLabel *label_63;
    QSpinBox *spinBoxSyncGUIPartnerPort;
    QSpinBox *spinBoxSyncGUIPort;
    QLabel *label_64;
    QWidget *page_14;
    QPushButton *pushButtonNext16;
    QPushButton *pushButtonPrevious16;
    QLabel *label_50;
    QTableWidget *tableWidgetImageDirection;
    QWidget *page_16;
    QPushButton *pushButtonNext17;
    QLabel *label_65;
    QPushButton *pushButtonPrevious17;
    QPushButton *pushButtonEditParameter;
    QPushButton *pushButtonEditAlgorithmParam;
    QPushButton *pushButtonEditGUIParam;
    QPushButton *pushButtonEditResultParam;
    QPushButton *pushButtonEditCameraParam;
    QPushButton *pushButtonEditLightParam;
    QLabel *label_68;
    QPushButton *pushButtonGUIFileName;
    QLineEdit *lineEditGUIFileName;
    QFrame *frame;
    QPushButton *pushButtonUpdate;
    QPushButton *pushButtonSaveNew;
    QPushButton *pushButtonClose;
    QFrame *frame_2;
    QProgressBar *progressBar;

    void setupUi(QMainWindow *EditWizardParameterClass)
    {
        if (EditWizardParameterClass->objectName().isEmpty())
            EditWizardParameterClass->setObjectName("EditWizardParameterClass");
        EditWizardParameterClass->resize(562, 437);
        centralWidget = new QWidget(EditWizardParameterClass);
        centralWidget->setObjectName("centralWidget");
        lineEditFileName = new QLineEdit(centralWidget);
        lineEditFileName->setObjectName("lineEditFileName");
        lineEditFileName->setGeometry(QRect(110, 10, 391, 31));
        QFont font;
        font.setPointSize(12);
        lineEditFileName->setFont(font);
        label = new QLabel(centralWidget);
        label->setObjectName("label");
        label->setGeometry(QRect(10, 10, 91, 31));
        label->setFont(font);
        label->setFrameShape(QFrame::Panel);
        label->setFrameShadow(QFrame::Sunken);
        pushButtonSearchFileName = new QPushButton(centralWidget);
        pushButtonSearchFileName->setObjectName("pushButtonSearchFileName");
        pushButtonSearchFileName->setGeometry(QRect(510, 10, 51, 31));
        stackedWidget = new QStackedWidget(centralWidget);
        stackedWidget->setObjectName("stackedWidget");
        stackedWidget->setGeometry(QRect(10, 90, 541, 291));
        Resolution = new QWidget();
        Resolution->setObjectName("Resolution");
        label_2 = new QLabel(Resolution);
        label_2->setObjectName("label_2");
        label_2->setGeometry(QRect(0, 0, 141, 31));
        QFont font1;
        font1.setPointSize(16);
        font1.setBold(true);
        label_2->setFont(font1);
        label_3 = new QLabel(Resolution);
        label_3->setObjectName("label_3");
        label_3->setGeometry(QRect(80, 60, 211, 21));
        QFont font2;
        font2.setPointSize(12);
        font2.setBold(true);
        label_3->setFont(font2);
        doubleSpinBoxTransformUnitPerPixel = new QDoubleSpinBox(Resolution);
        doubleSpinBoxTransformUnitPerPixel->setObjectName("doubleSpinBoxTransformUnitPerPixel");
        doubleSpinBoxTransformUnitPerPixel->setGeometry(QRect(310, 60, 141, 31));
        QFont font3;
        font3.setPointSize(10);
        doubleSpinBoxTransformUnitPerPixel->setFont(font3);
        doubleSpinBoxTransformUnitPerPixel->setDecimals(3);
        doubleSpinBoxTransformUnitPerPixel->setMaximum(99999999.000000000000000);
        pushButtonNext1 = new QPushButton(Resolution);
        pushButtonNext1->setObjectName("pushButtonNext1");
        pushButtonNext1->setGeometry(QRect(440, 250, 93, 28));
        label_69 = new QLabel(Resolution);
        label_69->setObjectName("label_69");
        label_69->setGeometry(QRect(181, 104, 121, 21));
        label_69->setFont(font2);
        spinBoxSmallNumberFigure = new QSpinBox(Resolution);
        spinBoxSmallNumberFigure->setObjectName("spinBoxSmallNumberFigure");
        spinBoxSmallNumberFigure->setGeometry(QRect(310, 100, 91, 31));
        spinBoxSmallNumberFigure->setFont(font3);
        spinBoxSmallNumberFigure->setMaximum(999999);
        stackedWidget->addWidget(Resolution);
        page_2 = new QWidget();
        page_2->setObjectName("page_2");
        label_5 = new QLabel(page_2);
        label_5->setObjectName("label_5");
        label_5->setGeometry(QRect(0, 0, 141, 31));
        label_5->setFont(font1);
        groupBox = new QGroupBox(page_2);
        groupBox->setObjectName("groupBox");
        groupBox->setGeometry(QRect(149, 56, 241, 111));
        radioButtonMono = new QRadioButton(groupBox);
        radioButtonMono->setObjectName("radioButtonMono");
        radioButtonMono->setGeometry(QRect(30, 20, 141, 19));
        radioButtonMono->setFont(font);
        radioButtonMono->setChecked(true);
        radioButtonColor = new QRadioButton(groupBox);
        radioButtonColor->setObjectName("radioButtonColor");
        radioButtonColor->setGeometry(QRect(30, 60, 141, 19));
        radioButtonColor->setFont(font);
        spinBoxLayerNumb = new QSpinBox(page_2);
        spinBoxLayerNumb->setObjectName("spinBoxLayerNumb");
        spinBoxLayerNumb->setGeometry(QRect(299, 186, 91, 31));
        spinBoxLayerNumb->setMaximum(999999);
        label_6 = new QLabel(page_2);
        label_6->setObjectName("label_6");
        label_6->setGeometry(QRect(170, 190, 121, 21));
        label_6->setFont(font2);
        pushButtonNext2 = new QPushButton(page_2);
        pushButtonNext2->setObjectName("pushButtonNext2");
        pushButtonNext2->setGeometry(QRect(440, 250, 93, 28));
        pushButtonPrevious2 = new QPushButton(page_2);
        pushButtonPrevious2->setObjectName("pushButtonPrevious2");
        pushButtonPrevious2->setGeometry(QRect(10, 250, 93, 28));
        stackedWidget->addWidget(page_2);
        page = new QWidget();
        page->setObjectName("page");
        label_7 = new QLabel(page);
        label_7->setObjectName("label_7");
        label_7->setGeometry(QRect(0, 0, 231, 31));
        label_7->setFont(font1);
        frame_3 = new QFrame(page);
        frame_3->setObjectName("frame_3");
        frame_3->setGeometry(QRect(140, 40, 291, 71));
        frame_3->setFrameShape(QFrame::Panel);
        frame_3->setFrameShadow(QFrame::Raised);
        doubleSpinBoxYMilimeter = new QDoubleSpinBox(frame_3);
        doubleSpinBoxYMilimeter->setObjectName("doubleSpinBoxYMilimeter");
        doubleSpinBoxYMilimeter->setGeometry(QRect(140, 40, 141, 22));
        doubleSpinBoxXMilimeter = new QDoubleSpinBox(frame_3);
        doubleSpinBoxXMilimeter->setObjectName("doubleSpinBoxXMilimeter");
        doubleSpinBoxXMilimeter->setGeometry(QRect(140, 10, 141, 22));
        label_8 = new QLabel(frame_3);
        label_8->setObjectName("label_8");
        label_8->setGeometry(QRect(20, 10, 111, 21));
        label_8->setFont(font);
        label_9 = new QLabel(frame_3);
        label_9->setObjectName("label_9");
        label_9->setGeometry(QRect(20, 40, 111, 21));
        label_9->setFont(font);
        frame_4 = new QFrame(page);
        frame_4->setObjectName("frame_4");
        frame_4->setGeometry(QRect(140, 170, 291, 71));
        frame_4->setFrameShape(QFrame::Panel);
        frame_4->setFrameShadow(QFrame::Raised);
        label_10 = new QLabel(frame_4);
        label_10->setObjectName("label_10");
        label_10->setGeometry(QRect(20, 10, 111, 21));
        label_10->setFont(font);
        label_11 = new QLabel(frame_4);
        label_11->setObjectName("label_11");
        label_11->setGeometry(QRect(20, 40, 111, 21));
        label_11->setFont(font);
        spinBoxDotPerLine = new QSpinBox(frame_4);
        spinBoxDotPerLine->setObjectName("spinBoxDotPerLine");
        spinBoxDotPerLine->setGeometry(QRect(140, 10, 121, 22));
        spinBoxDotPerLine->setMaximum(999999999);
        spinBoxMaxLines = new QSpinBox(frame_4);
        spinBoxMaxLines->setObjectName("spinBoxMaxLines");
        spinBoxMaxLines->setGeometry(QRect(140, 40, 121, 22));
        spinBoxMaxLines->setMaximum(999999999);
        pushButtonMMToPixel = new QPushButton(page);
        pushButtonMMToPixel->setObjectName("pushButtonMMToPixel");
        pushButtonMMToPixel->setGeometry(QRect(170, 120, 93, 41));
        pushButtonPixelToMM = new QPushButton(page);
        pushButtonPixelToMM->setObjectName("pushButtonPixelToMM");
        pushButtonPixelToMM->setGeometry(QRect(310, 120, 93, 41));
        pushButtonNext3 = new QPushButton(page);
        pushButtonNext3->setObjectName("pushButtonNext3");
        pushButtonNext3->setGeometry(QRect(440, 250, 93, 28));
        pushButtonPrevious3 = new QPushButton(page);
        pushButtonPrevious3->setObjectName("pushButtonPrevious3");
        pushButtonPrevious3->setGeometry(QRect(10, 250, 93, 28));
        stackedWidget->addWidget(page);
        page_3 = new QWidget();
        page_3->setObjectName("page_3");
        label_12 = new QLabel(page_3);
        label_12->setObjectName("label_12");
        label_12->setGeometry(QRect(0, 0, 361, 31));
        label_12->setFont(font1);
        pushButtonNext4 = new QPushButton(page_3);
        pushButtonNext4->setObjectName("pushButtonNext4");
        pushButtonNext4->setGeometry(QRect(440, 250, 93, 28));
        pushButtonPrevious4 = new QPushButton(page_3);
        pushButtonPrevious4->setObjectName("pushButtonPrevious4");
        pushButtonPrevious4->setGeometry(QRect(10, 250, 93, 28));
        frame_5 = new QFrame(page_3);
        frame_5->setObjectName("frame_5");
        frame_5->setGeometry(QRect(140, 90, 291, 101));
        frame_5->setFrameShape(QFrame::Panel);
        frame_5->setFrameShadow(QFrame::Raised);
        label_13 = new QLabel(frame_5);
        label_13->setObjectName("label_13");
        label_13->setGeometry(QRect(20, 10, 131, 21));
        label_13->setFont(font);
        label_14 = new QLabel(frame_5);
        label_14->setObjectName("label_14");
        label_14->setGeometry(QRect(20, 70, 131, 21));
        label_14->setFont(font);
        spinBoxPhaseNumb = new QSpinBox(frame_5);
        spinBoxPhaseNumb->setObjectName("spinBoxPhaseNumb");
        spinBoxPhaseNumb->setGeometry(QRect(160, 10, 121, 22));
        spinBoxPhaseNumb->setMaximum(999999999);
        spinBoxTotalCameraNumb = new QSpinBox(frame_5);
        spinBoxTotalCameraNumb->setObjectName("spinBoxTotalCameraNumb");
        spinBoxTotalCameraNumb->setGeometry(QRect(160, 70, 121, 22));
        spinBoxTotalCameraNumb->setMaximum(999999999);
        spinBoxPageNumb = new QSpinBox(frame_5);
        spinBoxPageNumb->setObjectName("spinBoxPageNumb");
        spinBoxPageNumb->setGeometry(QRect(160, 40, 121, 22));
        spinBoxPageNumb->setMaximum(999999999);
        label_53 = new QLabel(frame_5);
        label_53->setObjectName("label_53");
        label_53->setGeometry(QRect(20, 40, 131, 21));
        label_53->setFont(font);
        stackedWidget->addWidget(page_3);
        page_4 = new QWidget();
        page_4->setObjectName("page_4");
        pushButtonPrevious5 = new QPushButton(page_4);
        pushButtonPrevious5->setObjectName("pushButtonPrevious5");
        pushButtonPrevious5->setGeometry(QRect(10, 250, 93, 28));
        pushButtonNext5 = new QPushButton(page_4);
        pushButtonNext5->setObjectName("pushButtonNext5");
        pushButtonNext5->setGeometry(QRect(440, 250, 93, 28));
        label_15 = new QLabel(page_4);
        label_15->setObjectName("label_15");
        label_15->setGeometry(QRect(0, 0, 271, 31));
        label_15->setFont(font1);
        label_16 = new QLabel(page_4);
        label_16->setObjectName("label_16");
        label_16->setGeometry(QRect(20, 40, 411, 21));
        QFont font4;
        font4.setPointSize(10);
        font4.setBold(true);
        label_16->setFont(font4);
        lineEditLocalDatabase_HostName = new QLineEdit(page_4);
        lineEditLocalDatabase_HostName->setObjectName("lineEditLocalDatabase_HostName");
        lineEditLocalDatabase_HostName->setGeometry(QRect(20, 60, 441, 28));
        lineEditLocalDatabase_HostName->setFont(font);
        label_17 = new QLabel(page_4);
        label_17->setObjectName("label_17");
        label_17->setGeometry(QRect(20, 90, 511, 21));
        label_17->setFont(font4);
        lineEditLocalDatabase_FileName = new QLineEdit(page_4);
        lineEditLocalDatabase_FileName->setObjectName("lineEditLocalDatabase_FileName");
        lineEditLocalDatabase_FileName->setGeometry(QRect(20, 110, 441, 28));
        lineEditLocalDatabase_FileName->setFont(font);
        pushButtonLocalDatabase_FileName = new QPushButton(page_4);
        pushButtonLocalDatabase_FileName->setObjectName("pushButtonLocalDatabase_FileName");
        pushButtonLocalDatabase_FileName->setGeometry(QRect(470, 110, 51, 28));
        label_18 = new QLabel(page_4);
        label_18->setObjectName("label_18");
        label_18->setGeometry(QRect(20, 200, 321, 31));
        label_18->setFont(font4);
        spinBoxLocalDatabase_Port = new QSpinBox(page_4);
        spinBoxLocalDatabase_Port->setObjectName("spinBoxLocalDatabase_Port");
        spinBoxLocalDatabase_Port->setGeometry(QRect(350, 200, 91, 31));
        spinBoxLocalDatabase_Port->setFont(font3);
        spinBoxLocalDatabase_Port->setMaximum(65535);
        label_24 = new QLabel(page_4);
        label_24->setObjectName("label_24");
        label_24->setGeometry(QRect(20, 140, 511, 21));
        label_24->setFont(font4);
        lineEditDatabaseDDL_FileName = new QLineEdit(page_4);
        lineEditDatabaseDDL_FileName->setObjectName("lineEditDatabaseDDL_FileName");
        lineEditDatabaseDDL_FileName->setGeometry(QRect(20, 160, 441, 28));
        lineEditDatabaseDDL_FileName->setFont(font);
        pushButtonDatabaseDDL_FileName = new QPushButton(page_4);
        pushButtonDatabaseDDL_FileName->setObjectName("pushButtonDatabaseDDL_FileName");
        pushButtonDatabaseDDL_FileName->setGeometry(QRect(470, 160, 51, 28));
        stackedWidget->addWidget(page_4);
        page_5 = new QWidget();
        page_5->setObjectName("page_5");
        label_19 = new QLabel(page_5);
        label_19->setObjectName("label_19");
        label_19->setGeometry(QRect(0, 0, 271, 31));
        label_19->setFont(font1);
        pushButtonNext6 = new QPushButton(page_5);
        pushButtonNext6->setObjectName("pushButtonNext6");
        pushButtonNext6->setGeometry(QRect(440, 250, 93, 28));
        pushButtonPrevious6 = new QPushButton(page_5);
        pushButtonPrevious6->setObjectName("pushButtonPrevious6");
        pushButtonPrevious6->setGeometry(QRect(10, 250, 93, 28));
        lineEditImageFilePath = new QLineEdit(page_5);
        lineEditImageFilePath->setObjectName("lineEditImageFilePath");
        lineEditImageFilePath->setGeometry(QRect(40, 60, 431, 28));
        lineEditImageFilePath->setFont(font);
        label_20 = new QLabel(page_5);
        label_20->setObjectName("label_20");
        label_20->setGeometry(QRect(40, 40, 411, 21));
        label_20->setFont(font4);
        pushButtonImageFilePath = new QPushButton(page_5);
        pushButtonImageFilePath->setObjectName("pushButtonImageFilePath");
        pushButtonImageFilePath->setGeometry(QRect(480, 60, 51, 28));
        stackedWidget->addWidget(page_5);
        page_6 = new QWidget();
        page_6->setObjectName("page_6");
        pushButtonPrevious7 = new QPushButton(page_6);
        pushButtonPrevious7->setObjectName("pushButtonPrevious7");
        pushButtonPrevious7->setGeometry(QRect(10, 250, 93, 28));
        label_21 = new QLabel(page_6);
        label_21->setObjectName("label_21");
        label_21->setGeometry(QRect(0, 0, 271, 31));
        label_21->setFont(font1);
        pushButtonNext7 = new QPushButton(page_6);
        pushButtonNext7->setObjectName("pushButtonNext7");
        pushButtonNext7->setGeometry(QRect(440, 250, 93, 28));
        pushButtonSequence_FileName = new QPushButton(page_6);
        pushButtonSequence_FileName->setObjectName("pushButtonSequence_FileName");
        pushButtonSequence_FileName->setGeometry(QRect(470, 60, 51, 28));
        lineEditSequence_FileName = new QLineEdit(page_6);
        lineEditSequence_FileName->setObjectName("lineEditSequence_FileName");
        lineEditSequence_FileName->setGeometry(QRect(30, 60, 431, 28));
        lineEditSequence_FileName->setFont(font);
        label_22 = new QLabel(page_6);
        label_22->setObjectName("label_22");
        label_22->setGeometry(QRect(30, 40, 411, 21));
        label_22->setFont(font4);
        lineEditIODLL_FileName = new QLineEdit(page_6);
        lineEditIODLL_FileName->setObjectName("lineEditIODLL_FileName");
        lineEditIODLL_FileName->setGeometry(QRect(30, 110, 431, 28));
        lineEditIODLL_FileName->setFont(font);
        pushButtonIODLL_FileName = new QPushButton(page_6);
        pushButtonIODLL_FileName->setObjectName("pushButtonIODLL_FileName");
        pushButtonIODLL_FileName->setGeometry(QRect(470, 110, 51, 28));
        label_23 = new QLabel(page_6);
        label_23->setObjectName("label_23");
        label_23->setGeometry(QRect(30, 90, 411, 21));
        label_23->setFont(font4);
        label_25 = new QLabel(page_6);
        label_25->setObjectName("label_25");
        label_25->setGeometry(QRect(30, 140, 411, 21));
        label_25->setFont(font4);
        lineEditIODefine_FileName = new QLineEdit(page_6);
        lineEditIODefine_FileName->setObjectName("lineEditIODefine_FileName");
        lineEditIODefine_FileName->setGeometry(QRect(30, 160, 431, 28));
        lineEditIODefine_FileName->setFont(font);
        pushButtonIODefine_FileName = new QPushButton(page_6);
        pushButtonIODefine_FileName->setObjectName("pushButtonIODefine_FileName");
        pushButtonIODefine_FileName->setGeometry(QRect(470, 160, 51, 28));
        label_26 = new QLabel(page_6);
        label_26->setObjectName("label_26");
        label_26->setGeometry(QRect(30, 190, 411, 21));
        label_26->setFont(font4);
        lineEditIOSomething = new QLineEdit(page_6);
        lineEditIOSomething->setObjectName("lineEditIOSomething");
        lineEditIOSomething->setGeometry(QRect(30, 210, 431, 28));
        lineEditIOSomething->setFont(font);
        stackedWidget->addWidget(page_6);
        page_7 = new QWidget();
        page_7->setObjectName("page_7");
        label_27 = new QLabel(page_7);
        label_27->setObjectName("label_27");
        label_27->setGeometry(QRect(0, 0, 271, 31));
        label_27->setFont(font1);
        pushButtonNext8 = new QPushButton(page_7);
        pushButtonNext8->setObjectName("pushButtonNext8");
        pushButtonNext8->setGeometry(QRect(440, 250, 93, 28));
        pushButtonPrevious8 = new QPushButton(page_7);
        pushButtonPrevious8->setObjectName("pushButtonPrevious8");
        pushButtonPrevious8->setGeometry(QRect(10, 250, 93, 28));
        lineEditCameraSetting_FileName = new QLineEdit(page_7);
        lineEditCameraSetting_FileName->setObjectName("lineEditCameraSetting_FileName");
        lineEditCameraSetting_FileName->setGeometry(QRect(30, 50, 431, 28));
        lineEditCameraSetting_FileName->setFont(font);
        pushButtonCameraSetting_FileName = new QPushButton(page_7);
        pushButtonCameraSetting_FileName->setObjectName("pushButtonCameraSetting_FileName");
        pushButtonCameraSetting_FileName->setGeometry(QRect(470, 50, 51, 28));
        label_28 = new QLabel(page_7);
        label_28->setObjectName("label_28");
        label_28->setGeometry(QRect(30, 30, 411, 21));
        label_28->setFont(font4);
        label_29 = new QLabel(page_7);
        label_29->setObjectName("label_29");
        label_29->setGeometry(QRect(10, 100, 161, 21));
        label_29->setFont(font4);
        pushButtonCameraDLL_FileName = new QPushButton(page_7);
        pushButtonCameraDLL_FileName->setObjectName("pushButtonCameraDLL_FileName");
        pushButtonCameraDLL_FileName->setGeometry(QRect(470, 100, 51, 28));
        lineEditCameraDLL_FileName = new QLineEdit(page_7);
        lineEditCameraDLL_FileName->setObjectName("lineEditCameraDLL_FileName");
        lineEditCameraDLL_FileName->setGeometry(QRect(170, 100, 291, 28));
        lineEditCameraDLL_FileName->setFont(font);
        label_30 = new QLabel(page_7);
        label_30->setObjectName("label_30");
        label_30->setGeometry(QRect(60, 130, 151, 21));
        label_30->setFont(font4);
        lineEditCameraAllocation = new QLineEdit(page_7);
        lineEditCameraAllocation->setObjectName("lineEditCameraAllocation");
        lineEditCameraAllocation->setGeometry(QRect(220, 130, 241, 28));
        lineEditCameraAllocation->setFont(font);
        label_70 = new QLabel(page_7);
        label_70->setObjectName("label_70");
        label_70->setGeometry(QRect(60, 200, 151, 21));
        label_70->setFont(font4);
        lineEditCameraDLL_FileName2 = new QLineEdit(page_7);
        lineEditCameraDLL_FileName2->setObjectName("lineEditCameraDLL_FileName2");
        lineEditCameraDLL_FileName2->setGeometry(QRect(170, 170, 291, 28));
        lineEditCameraDLL_FileName2->setFont(font);
        label_71 = new QLabel(page_7);
        label_71->setObjectName("label_71");
        label_71->setGeometry(QRect(10, 170, 161, 21));
        label_71->setFont(font4);
        lineEditCameraAllocation2 = new QLineEdit(page_7);
        lineEditCameraAllocation2->setObjectName("lineEditCameraAllocation2");
        lineEditCameraAllocation2->setGeometry(QRect(220, 200, 241, 28));
        lineEditCameraAllocation2->setFont(font);
        pushButtonCameraDLL_FileName2 = new QPushButton(page_7);
        pushButtonCameraDLL_FileName2->setObjectName("pushButtonCameraDLL_FileName2");
        pushButtonCameraDLL_FileName2->setGeometry(QRect(470, 170, 51, 28));
        pushButtonCameraAllocation = new QPushButton(page_7);
        pushButtonCameraAllocation->setObjectName("pushButtonCameraAllocation");
        pushButtonCameraAllocation->setGeometry(QRect(470, 130, 51, 28));
        pushButtonCameraAllocation2 = new QPushButton(page_7);
        pushButtonCameraAllocation2->setObjectName("pushButtonCameraAllocation2");
        pushButtonCameraAllocation2->setGeometry(QRect(470, 200, 51, 28));
        stackedWidget->addWidget(page_7);
        page_8 = new QWidget();
        page_8->setObjectName("page_8");
        pushButtonNext9 = new QPushButton(page_8);
        pushButtonNext9->setObjectName("pushButtonNext9");
        pushButtonNext9->setGeometry(QRect(440, 250, 93, 28));
        pushButtonPrevious9 = new QPushButton(page_8);
        pushButtonPrevious9->setObjectName("pushButtonPrevious9");
        pushButtonPrevious9->setGeometry(QRect(10, 250, 93, 28));
        label_31 = new QLabel(page_8);
        label_31->setObjectName("label_31");
        label_31->setGeometry(QRect(0, 0, 271, 31));
        label_31->setFont(font1);
        lineEditResultDLLFileName = new QLineEdit(page_8);
        lineEditResultDLLFileName->setObjectName("lineEditResultDLLFileName");
        lineEditResultDLLFileName->setGeometry(QRect(30, 50, 431, 28));
        lineEditResultDLLFileName->setFont(font);
        label_32 = new QLabel(page_8);
        label_32->setObjectName("label_32");
        label_32->setGeometry(QRect(30, 30, 411, 21));
        label_32->setFont(font4);
        pushButtonResultDLLFileName = new QPushButton(page_8);
        pushButtonResultDLLFileName->setObjectName("pushButtonResultDLLFileName");
        pushButtonResultDLLFileName->setGeometry(QRect(470, 50, 51, 28));
        label_33 = new QLabel(page_8);
        label_33->setObjectName("label_33");
        label_33->setGeometry(QRect(30, 120, 331, 21));
        label_33->setFont(font4);
        spinBoxMaxNGCountsPerCam = new QSpinBox(page_8);
        spinBoxMaxNGCountsPerCam->setObjectName("spinBoxMaxNGCountsPerCam");
        spinBoxMaxNGCountsPerCam->setGeometry(QRect(370, 120, 91, 22));
        spinBoxMaxNGCountsPerCam->setMaximum(99999999);
        label_34 = new QLabel(page_8);
        label_34->setObjectName("label_34");
        label_34->setGeometry(QRect(30, 150, 331, 21));
        label_34->setFont(font4);
        spinBoxMaxNGImageNumbPerPage = new QSpinBox(page_8);
        spinBoxMaxNGImageNumbPerPage->setObjectName("spinBoxMaxNGImageNumbPerPage");
        spinBoxMaxNGImageNumbPerPage->setGeometry(QRect(370, 150, 91, 22));
        spinBoxMaxNGImageNumbPerPage->setMaximum(100000000);
        label_35 = new QLabel(page_8);
        label_35->setObjectName("label_35");
        label_35->setGeometry(QRect(30, 180, 331, 21));
        label_35->setFont(font4);
        spinBoxMaxInspectMilisec = new QSpinBox(page_8);
        spinBoxMaxInspectMilisec->setObjectName("spinBoxMaxInspectMilisec");
        spinBoxMaxInspectMilisec->setGeometry(QRect(370, 180, 91, 22));
        spinBoxMaxInspectMilisec->setMaximum(1024000);
        label_36 = new QLabel(page_8);
        label_36->setObjectName("label_36");
        label_36->setGeometry(QRect(30, 90, 331, 21));
        label_36->setFont(font4);
        spinBoxNGCacheNumb = new QSpinBox(page_8);
        spinBoxNGCacheNumb->setObjectName("spinBoxNGCacheNumb");
        spinBoxNGCacheNumb->setGeometry(QRect(370, 90, 91, 22));
        spinBoxNGCacheNumb->setMaximum(1000000);
        label_37 = new QLabel(page_8);
        label_37->setObjectName("label_37");
        label_37->setGeometry(QRect(30, 210, 331, 21));
        label_37->setFont(font4);
        checkBoxOutputResult = new QCheckBox(page_8);
        checkBoxOutputResult->setObjectName("checkBoxOutputResult");
        checkBoxOutputResult->setGeometry(QRect(370, 210, 93, 19));
        stackedWidget->addWidget(page_8);
        page_15 = new QWidget();
        page_15->setObjectName("page_15");
        pushButtonPrevious10 = new QPushButton(page_15);
        pushButtonPrevious10->setObjectName("pushButtonPrevious10");
        pushButtonPrevious10->setGeometry(QRect(10, 250, 93, 28));
        pushButtonNext10 = new QPushButton(page_15);
        pushButtonNext10->setObjectName("pushButtonNext10");
        pushButtonNext10->setGeometry(QRect(440, 250, 93, 28));
        label_51 = new QLabel(page_15);
        label_51->setObjectName("label_51");
        label_51->setGeometry(QRect(0, 0, 271, 31));
        label_51->setFont(font1);
        label_52 = new QLabel(page_15);
        label_52->setObjectName("label_52");
        label_52->setGeometry(QRect(20, 40, 251, 21));
        label_52->setFont(font4);
        checkBoxAllocateMasterBuff = new QCheckBox(page_15);
        checkBoxAllocateMasterBuff->setObjectName("checkBoxAllocateMasterBuff");
        checkBoxAllocateMasterBuff->setGeometry(QRect(290, 40, 24, 19));
        checkBoxAllocateTargetBuff = new QCheckBox(page_15);
        checkBoxAllocateTargetBuff->setObjectName("checkBoxAllocateTargetBuff");
        checkBoxAllocateTargetBuff->setGeometry(QRect(290, 70, 24, 19));
        label_54 = new QLabel(page_15);
        label_54->setObjectName("label_54");
        label_54->setGeometry(QRect(20, 70, 251, 21));
        label_54->setFont(font4);
        label_55 = new QLabel(page_15);
        label_55->setObjectName("label_55");
        label_55->setGeometry(QRect(20, 100, 251, 21));
        label_55->setFont(font4);
        checkBoxAllocRawTargetBuffForNGImage = new QCheckBox(page_15);
        checkBoxAllocRawTargetBuffForNGImage->setObjectName("checkBoxAllocRawTargetBuffForNGImage");
        checkBoxAllocRawTargetBuffForNGImage->setGeometry(QRect(290, 100, 24, 19));
        label_56 = new QLabel(page_15);
        label_56->setObjectName("label_56");
        label_56->setGeometry(QRect(20, 130, 251, 21));
        label_56->setFont(font4);
        checkBoxAllocCamTargetBuffer = new QCheckBox(page_15);
        checkBoxAllocCamTargetBuffer->setObjectName("checkBoxAllocCamTargetBuffer");
        checkBoxAllocCamTargetBuffer->setGeometry(QRect(290, 130, 24, 19));
        label_57 = new QLabel(page_15);
        label_57->setObjectName("label_57");
        label_57->setGeometry(QRect(20, 160, 251, 21));
        label_57->setFont(font4);
        checkBoxAllocViewTargetBuffer = new QCheckBox(page_15);
        checkBoxAllocViewTargetBuffer->setObjectName("checkBoxAllocViewTargetBuffer");
        checkBoxAllocViewTargetBuffer->setGeometry(QRect(290, 160, 24, 19));
        label_58 = new QLabel(page_15);
        label_58->setObjectName("label_58");
        label_58->setGeometry(QRect(20, 190, 301, 21));
        label_58->setFont(font4);
        spinBoxSwapOutSizeMegaByte = new QSpinBox(page_15);
        spinBoxSwapOutSizeMegaByte->setObjectName("spinBoxSwapOutSizeMegaByte");
        spinBoxSwapOutSizeMegaByte->setGeometry(QRect(220, 220, 91, 22));
        spinBoxSwapOutSizeMegaByte->setMaximum(99999999);
        tableWidgetShowMemory = new QTableWidget(page_15);
        if (tableWidgetShowMemory->columnCount() < 1)
            tableWidgetShowMemory->setColumnCount(1);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        tableWidgetShowMemory->setHorizontalHeaderItem(0, __qtablewidgetitem);
        if (tableWidgetShowMemory->rowCount() < 2)
            tableWidgetShowMemory->setRowCount(2);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        tableWidgetShowMemory->setVerticalHeaderItem(0, __qtablewidgetitem1);
        QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
        tableWidgetShowMemory->setVerticalHeaderItem(1, __qtablewidgetitem2);
        tableWidgetShowMemory->setObjectName("tableWidgetShowMemory");
        tableWidgetShowMemory->setGeometry(QRect(340, 50, 191, 192));
        pushButtonCalcMemory = new QPushButton(page_15);
        pushButtonCalcMemory->setObjectName("pushButtonCalcMemory");
        pushButtonCalcMemory->setGeometry(QRect(390, 20, 93, 28));
        stackedWidget->addWidget(page_15);
        page_9 = new QWidget();
        page_9->setObjectName("page_9");
        pushButtonPrevious11 = new QPushButton(page_9);
        pushButtonPrevious11->setObjectName("pushButtonPrevious11");
        pushButtonPrevious11->setGeometry(QRect(10, 250, 93, 28));
        pushButtonNext11 = new QPushButton(page_9);
        pushButtonNext11->setObjectName("pushButtonNext11");
        pushButtonNext11->setGeometry(QRect(440, 250, 93, 28));
        label_38 = new QLabel(page_9);
        label_38->setObjectName("label_38");
        label_38->setGeometry(QRect(0, 0, 271, 31));
        label_38->setFont(font1);
        label_48 = new QLabel(page_9);
        label_48->setObjectName("label_48");
        label_48->setGeometry(QRect(10, 40, 151, 21));
        label_48->setFont(font4);
        lineEditFilterDefFile = new QLineEdit(page_9);
        lineEditFilterDefFile->setObjectName("lineEditFilterDefFile");
        lineEditFilterDefFile->setGeometry(QRect(170, 40, 301, 28));
        lineEditFilterDefFile->setFont(font);
        pushButtonFilterDefFile = new QPushButton(page_9);
        pushButtonFilterDefFile->setObjectName("pushButtonFilterDefFile");
        pushButtonFilterDefFile->setGeometry(QRect(480, 40, 51, 28));
        tableWidgetFilterListInPage = new QTableWidget(page_9);
        if (tableWidgetFilterListInPage->columnCount() < 2)
            tableWidgetFilterListInPage->setColumnCount(2);
        QTableWidgetItem *__qtablewidgetitem3 = new QTableWidgetItem();
        tableWidgetFilterListInPage->setHorizontalHeaderItem(0, __qtablewidgetitem3);
        QTableWidgetItem *__qtablewidgetitem4 = new QTableWidgetItem();
        tableWidgetFilterListInPage->setHorizontalHeaderItem(1, __qtablewidgetitem4);
        tableWidgetFilterListInPage->setObjectName("tableWidgetFilterListInPage");
        tableWidgetFilterListInPage->setGeometry(QRect(20, 110, 271, 131));
        tableWidgetFilterListInPage->setSelectionMode(QAbstractItemView::SingleSelection);
        tableWidgetFilterListInPage->setSelectionBehavior(QAbstractItemView::SelectRows);
        listViewFilterList = new QListView(page_9);
        listViewFilterList->setObjectName("listViewFilterList");
        listViewFilterList->setGeometry(QRect(300, 110, 221, 131));
        comboBoxPhaseForFIlter = new QComboBox(page_9);
        comboBoxPhaseForFIlter->setObjectName("comboBoxPhaseForFIlter");
        comboBoxPhaseForFIlter->setGeometry(QRect(150, 80, 80, 22));
        label_72 = new QLabel(page_9);
        label_72->setObjectName("label_72");
        label_72->setGeometry(QRect(50, 80, 81, 21));
        label_72->setFont(font4);
        stackedWidget->addWidget(page_9);
        page_10 = new QWidget();
        page_10->setObjectName("page_10");
        label_39 = new QLabel(page_10);
        label_39->setObjectName("label_39");
        label_39->setGeometry(QRect(0, 0, 271, 31));
        label_39->setFont(font1);
        pushButtonPrevious12 = new QPushButton(page_10);
        pushButtonPrevious12->setObjectName("pushButtonPrevious12");
        pushButtonPrevious12->setGeometry(QRect(10, 250, 93, 28));
        pushButtonNext12 = new QPushButton(page_10);
        pushButtonNext12->setObjectName("pushButtonNext12");
        pushButtonNext12->setGeometry(QRect(440, 250, 93, 28));
        label_59 = new QLabel(page_10);
        label_59->setObjectName("label_59");
        label_59->setGeometry(QRect(20, 40, 401, 21));
        label_59->setFont(font4);
        spinBoxMaxWaitingCommMilisec = new QSpinBox(page_10);
        spinBoxMaxWaitingCommMilisec->setObjectName("spinBoxMaxWaitingCommMilisec");
        spinBoxMaxWaitingCommMilisec->setGeometry(QRect(440, 40, 91, 22));
        spinBoxMaxWaitingCommMilisec->setMaximum(99999999);
        label_60 = new QLabel(page_10);
        label_60->setObjectName("label_60");
        label_60->setGeometry(QRect(20, 70, 61, 21));
        label_60->setFont(font4);
        checkBoxMaster = new QCheckBox(page_10);
        checkBoxMaster->setObjectName("checkBoxMaster");
        checkBoxMaster->setGeometry(QRect(100, 70, 24, 19));
        stackedWidget_2 = new QStackedWidget(page_10);
        stackedWidget_2->setObjectName("stackedWidget_2");
        stackedWidget_2->setGeometry(QRect(0, 100, 541, 151));
        Master = new QWidget();
        Master->setObjectName("Master");
        tableWidgetSlaveList = new QTableWidget(Master);
        if (tableWidgetSlaveList->columnCount() < 4)
            tableWidgetSlaveList->setColumnCount(4);
        QTableWidgetItem *__qtablewidgetitem5 = new QTableWidgetItem();
        tableWidgetSlaveList->setHorizontalHeaderItem(0, __qtablewidgetitem5);
        QTableWidgetItem *__qtablewidgetitem6 = new QTableWidgetItem();
        tableWidgetSlaveList->setHorizontalHeaderItem(1, __qtablewidgetitem6);
        QTableWidgetItem *__qtablewidgetitem7 = new QTableWidgetItem();
        tableWidgetSlaveList->setHorizontalHeaderItem(2, __qtablewidgetitem7);
        QTableWidgetItem *__qtablewidgetitem8 = new QTableWidgetItem();
        tableWidgetSlaveList->setHorizontalHeaderItem(3, __qtablewidgetitem8);
        tableWidgetSlaveList->setObjectName("tableWidgetSlaveList");
        tableWidgetSlaveList->setGeometry(QRect(10, 0, 531, 141));
        stackedWidget_2->addWidget(Master);
        Slave = new QWidget();
        Slave->setObjectName("Slave");
        label_73 = new QLabel(Slave);
        label_73->setObjectName("label_73");
        label_73->setGeometry(QRect(20, 10, 401, 21));
        label_73->setFont(font4);
        lineEditIPAddressInSlave = new QLineEdit(Slave);
        lineEditIPAddressInSlave->setObjectName("lineEditIPAddressInSlave");
        lineEditIPAddressInSlave->setGeometry(QRect(30, 30, 471, 21));
        stackedWidget_2->addWidget(Slave);
        stackedWidget->addWidget(page_10);
        page_11 = new QWidget();
        page_11->setObjectName("page_11");
        label_40 = new QLabel(page_11);
        label_40->setObjectName("label_40");
        label_40->setGeometry(QRect(0, 0, 271, 31));
        label_40->setFont(font1);
        pushButtonPrevious13 = new QPushButton(page_11);
        pushButtonPrevious13->setObjectName("pushButtonPrevious13");
        pushButtonPrevious13->setGeometry(QRect(10, 250, 93, 28));
        pushButtonNext13 = new QPushButton(page_11);
        pushButtonNext13->setObjectName("pushButtonNext13");
        pushButtonNext13->setGeometry(QRect(440, 250, 93, 28));
        tableWidgetOutlineOffsetList = new QTableWidget(page_11);
        if (tableWidgetOutlineOffsetList->columnCount() < 3)
            tableWidgetOutlineOffsetList->setColumnCount(3);
        QTableWidgetItem *__qtablewidgetitem9 = new QTableWidgetItem();
        tableWidgetOutlineOffsetList->setHorizontalHeaderItem(0, __qtablewidgetitem9);
        QTableWidgetItem *__qtablewidgetitem10 = new QTableWidgetItem();
        tableWidgetOutlineOffsetList->setHorizontalHeaderItem(1, __qtablewidgetitem10);
        QTableWidgetItem *__qtablewidgetitem11 = new QTableWidgetItem();
        tableWidgetOutlineOffsetList->setHorizontalHeaderItem(2, __qtablewidgetitem11);
        tableWidgetOutlineOffsetList->setObjectName("tableWidgetOutlineOffsetList");
        tableWidgetOutlineOffsetList->setGeometry(QRect(20, 71, 371, 171));
        pushButtonOTileXutlineOffset = new QPushButton(page_11);
        pushButtonOTileXutlineOffset->setObjectName("pushButtonOTileXutlineOffset");
        pushButtonOTileXutlineOffset->setGeometry(QRect(410, 50, 121, 31));
        pushButtonOutlineOffsetTileY = new QPushButton(page_11);
        pushButtonOutlineOffsetTileY->setObjectName("pushButtonOutlineOffsetTileY");
        pushButtonOutlineOffsetTileY->setGeometry(QRect(410, 90, 121, 31));
        label_66 = new QLabel(page_11);
        label_66->setObjectName("label_66");
        label_66->setGeometry(QRect(10, 40, 81, 21));
        label_66->setFont(font4);
        comboBoxOutlineOffsetMachine = new QComboBox(page_11);
        comboBoxOutlineOffsetMachine->setObjectName("comboBoxOutlineOffsetMachine");
        comboBoxOutlineOffsetMachine->setGeometry(QRect(100, 40, 80, 22));
        label_67 = new QLabel(page_11);
        label_67->setObjectName("label_67");
        label_67->setGeometry(QRect(240, 40, 61, 21));
        label_67->setFont(font4);
        comboBoxOutlineOffsetPhase = new QComboBox(page_11);
        comboBoxOutlineOffsetPhase->setObjectName("comboBoxOutlineOffsetPhase");
        comboBoxOutlineOffsetPhase->setGeometry(QRect(310, 40, 80, 22));
        stackedWidget->addWidget(page_11);
        page_12 = new QWidget();
        page_12->setObjectName("page_12");
        label_41 = new QLabel(page_12);
        label_41->setObjectName("label_41");
        label_41->setGeometry(QRect(0, 0, 271, 31));
        label_41->setFont(font1);
        pushButtonPrevious14 = new QPushButton(page_12);
        pushButtonPrevious14->setObjectName("pushButtonPrevious14");
        pushButtonPrevious14->setGeometry(QRect(10, 250, 93, 28));
        pushButtonNext14 = new QPushButton(page_12);
        pushButtonNext14->setObjectName("pushButtonNext14");
        pushButtonNext14->setGeometry(QRect(440, 250, 93, 28));
        label_42 = new QLabel(page_12);
        label_42->setObjectName("label_42");
        label_42->setGeometry(QRect(80, 140, 141, 21));
        label_42->setFont(font4);
        pushButtonLightSettingFileName = new QPushButton(page_12);
        pushButtonLightSettingFileName->setObjectName("pushButtonLightSettingFileName");
        pushButtonLightSettingFileName->setGeometry(QRect(470, 50, 51, 28));
        lineEditLightDLLFileName = new QLineEdit(page_12);
        lineEditLightDLLFileName->setObjectName("lineEditLightDLLFileName");
        lineEditLightDLLFileName->setGeometry(QRect(150, 110, 311, 26));
        lineEditLightDLLFileName->setFont(font);
        label_43 = new QLabel(page_12);
        label_43->setObjectName("label_43");
        label_43->setGeometry(QRect(30, 30, 411, 21));
        label_43->setFont(font4);
        lineEditLightSettingFileName = new QLineEdit(page_12);
        lineEditLightSettingFileName->setObjectName("lineEditLightSettingFileName");
        lineEditLightSettingFileName->setGeometry(QRect(30, 50, 431, 28));
        lineEditLightSettingFileName->setFont(font);
        label_44 = new QLabel(page_12);
        label_44->setObjectName("label_44");
        label_44->setGeometry(QRect(10, 110, 141, 21));
        label_44->setFont(font4);
        lineEditLightParamStr = new QLineEdit(page_12);
        lineEditLightParamStr->setObjectName("lineEditLightParamStr");
        lineEditLightParamStr->setGeometry(QRect(230, 140, 291, 28));
        lineEditLightParamStr->setFont(font);
        pushButtonLightDLLFileName = new QPushButton(page_12);
        pushButtonLightDLLFileName->setObjectName("pushButtonLightDLLFileName");
        pushButtonLightDLLFileName->setGeometry(QRect(470, 110, 51, 26));
        label_45 = new QLabel(page_12);
        label_45->setObjectName("label_45");
        label_45->setGeometry(QRect(10, 180, 141, 21));
        label_45->setFont(font4);
        lineEditLightParamStr2 = new QLineEdit(page_12);
        lineEditLightParamStr2->setObjectName("lineEditLightParamStr2");
        lineEditLightParamStr2->setGeometry(QRect(230, 210, 291, 28));
        lineEditLightParamStr2->setFont(font);
        label_46 = new QLabel(page_12);
        label_46->setObjectName("label_46");
        label_46->setGeometry(QRect(80, 210, 141, 21));
        label_46->setFont(font4);
        pushButtonLightDLLFileName2 = new QPushButton(page_12);
        pushButtonLightDLLFileName2->setObjectName("pushButtonLightDLLFileName2");
        pushButtonLightDLLFileName2->setGeometry(QRect(470, 180, 51, 26));
        lineEditLightDLLFileName2 = new QLineEdit(page_12);
        lineEditLightDLLFileName2->setObjectName("lineEditLightDLLFileName2");
        lineEditLightDLLFileName2->setGeometry(QRect(150, 180, 311, 26));
        lineEditLightDLLFileName2->setFont(font);
        checkBoxInitialLightON = new QCheckBox(page_12);
        checkBoxInitialLightON->setObjectName("checkBoxInitialLightON");
        checkBoxInitialLightON->setGeometry(QRect(380, 80, 93, 19));
        label_47 = new QLabel(page_12);
        label_47->setObjectName("label_47");
        label_47->setGeometry(QRect(250, 80, 121, 21));
        label_47->setFont(font4);
        stackedWidget->addWidget(page_12);
        page_13 = new QWidget();
        page_13->setObjectName("page_13");
        pushButtonNext15 = new QPushButton(page_13);
        pushButtonNext15->setObjectName("pushButtonNext15");
        pushButtonNext15->setGeometry(QRect(440, 250, 93, 28));
        pushButtonPrevious15 = new QPushButton(page_13);
        pushButtonPrevious15->setObjectName("pushButtonPrevious15");
        pushButtonPrevious15->setGeometry(QRect(10, 250, 93, 28));
        label_49 = new QLabel(page_13);
        label_49->setObjectName("label_49");
        label_49->setGeometry(QRect(0, 0, 271, 31));
        label_49->setFont(font1);
        label_61 = new QLabel(page_13);
        label_61->setObjectName("label_61");
        label_61->setGeometry(QRect(40, 40, 411, 21));
        label_61->setFont(font4);
        lineEditSyncGUIFileName = new QLineEdit(page_13);
        lineEditSyncGUIFileName->setObjectName("lineEditSyncGUIFileName");
        lineEditSyncGUIFileName->setGeometry(QRect(40, 60, 431, 28));
        lineEditSyncGUIFileName->setFont(font);
        pushButtonSyncGUIFileName = new QPushButton(page_13);
        pushButtonSyncGUIFileName->setObjectName("pushButtonSyncGUIFileName");
        pushButtonSyncGUIFileName->setGeometry(QRect(480, 60, 51, 28));
        lineEditSyncGUIPartnerIP = new QLineEdit(page_13);
        lineEditSyncGUIPartnerIP->setObjectName("lineEditSyncGUIPartnerIP");
        lineEditSyncGUIPartnerIP->setGeometry(QRect(40, 160, 441, 28));
        lineEditSyncGUIPartnerIP->setFont(font);
        label_62 = new QLabel(page_13);
        label_62->setObjectName("label_62");
        label_62->setGeometry(QRect(40, 140, 411, 21));
        label_62->setFont(font4);
        label_63 = new QLabel(page_13);
        label_63->setObjectName("label_63");
        label_63->setGeometry(QRect(190, 200, 181, 21));
        label_63->setFont(font4);
        spinBoxSyncGUIPartnerPort = new QSpinBox(page_13);
        spinBoxSyncGUIPartnerPort->setObjectName("spinBoxSyncGUIPartnerPort");
        spinBoxSyncGUIPartnerPort->setGeometry(QRect(380, 200, 91, 22));
        spinBoxSyncGUIPartnerPort->setMaximum(65535);
        spinBoxSyncGUIPort = new QSpinBox(page_13);
        spinBoxSyncGUIPort->setObjectName("spinBoxSyncGUIPort");
        spinBoxSyncGUIPort->setGeometry(QRect(380, 100, 91, 22));
        spinBoxSyncGUIPort->setMaximum(65535);
        label_64 = new QLabel(page_13);
        label_64->setObjectName("label_64");
        label_64->setGeometry(QRect(190, 100, 181, 21));
        label_64->setFont(font4);
        stackedWidget->addWidget(page_13);
        page_14 = new QWidget();
        page_14->setObjectName("page_14");
        pushButtonNext16 = new QPushButton(page_14);
        pushButtonNext16->setObjectName("pushButtonNext16");
        pushButtonNext16->setGeometry(QRect(440, 250, 93, 28));
        pushButtonPrevious16 = new QPushButton(page_14);
        pushButtonPrevious16->setObjectName("pushButtonPrevious16");
        pushButtonPrevious16->setGeometry(QRect(10, 250, 93, 28));
        label_50 = new QLabel(page_14);
        label_50->setObjectName("label_50");
        label_50->setGeometry(QRect(0, 0, 271, 31));
        label_50->setFont(font1);
        tableWidgetImageDirection = new QTableWidget(page_14);
        if (tableWidgetImageDirection->columnCount() < 4)
            tableWidgetImageDirection->setColumnCount(4);
        QTableWidgetItem *__qtablewidgetitem12 = new QTableWidgetItem();
        tableWidgetImageDirection->setHorizontalHeaderItem(0, __qtablewidgetitem12);
        QTableWidgetItem *__qtablewidgetitem13 = new QTableWidgetItem();
        tableWidgetImageDirection->setHorizontalHeaderItem(1, __qtablewidgetitem13);
        QTableWidgetItem *__qtablewidgetitem14 = new QTableWidgetItem();
        tableWidgetImageDirection->setHorizontalHeaderItem(2, __qtablewidgetitem14);
        QTableWidgetItem *__qtablewidgetitem15 = new QTableWidgetItem();
        tableWidgetImageDirection->setHorizontalHeaderItem(3, __qtablewidgetitem15);
        tableWidgetImageDirection->setObjectName("tableWidgetImageDirection");
        tableWidgetImageDirection->setGeometry(QRect(10, 40, 521, 192));
        stackedWidget->addWidget(page_14);
        page_16 = new QWidget();
        page_16->setObjectName("page_16");
        pushButtonNext17 = new QPushButton(page_16);
        pushButtonNext17->setObjectName("pushButtonNext17");
        pushButtonNext17->setGeometry(QRect(440, 250, 93, 28));
        label_65 = new QLabel(page_16);
        label_65->setObjectName("label_65");
        label_65->setGeometry(QRect(0, 0, 271, 31));
        label_65->setFont(font1);
        pushButtonPrevious17 = new QPushButton(page_16);
        pushButtonPrevious17->setObjectName("pushButtonPrevious17");
        pushButtonPrevious17->setGeometry(QRect(10, 250, 93, 28));
        pushButtonEditParameter = new QPushButton(page_16);
        pushButtonEditParameter->setObjectName("pushButtonEditParameter");
        pushButtonEditParameter->setGeometry(QRect(60, 100, 191, 28));
        pushButtonEditAlgorithmParam = new QPushButton(page_16);
        pushButtonEditAlgorithmParam->setObjectName("pushButtonEditAlgorithmParam");
        pushButtonEditAlgorithmParam->setGeometry(QRect(60, 150, 191, 28));
        pushButtonEditGUIParam = new QPushButton(page_16);
        pushButtonEditGUIParam->setObjectName("pushButtonEditGUIParam");
        pushButtonEditGUIParam->setGeometry(QRect(60, 180, 191, 28));
        pushButtonEditResultParam = new QPushButton(page_16);
        pushButtonEditResultParam->setObjectName("pushButtonEditResultParam");
        pushButtonEditResultParam->setGeometry(QRect(60, 210, 191, 28));
        pushButtonEditCameraParam = new QPushButton(page_16);
        pushButtonEditCameraParam->setObjectName("pushButtonEditCameraParam");
        pushButtonEditCameraParam->setGeometry(QRect(290, 150, 191, 28));
        pushButtonEditLightParam = new QPushButton(page_16);
        pushButtonEditLightParam->setObjectName("pushButtonEditLightParam");
        pushButtonEditLightParam->setGeometry(QRect(290, 180, 191, 28));
        label_68 = new QLabel(page_16);
        label_68->setObjectName("label_68");
        label_68->setGeometry(QRect(40, 30, 411, 21));
        label_68->setFont(font4);
        pushButtonGUIFileName = new QPushButton(page_16);
        pushButtonGUIFileName->setObjectName("pushButtonGUIFileName");
        pushButtonGUIFileName->setGeometry(QRect(480, 50, 51, 28));
        lineEditGUIFileName = new QLineEdit(page_16);
        lineEditGUIFileName->setObjectName("lineEditGUIFileName");
        lineEditGUIFileName->setGeometry(QRect(40, 50, 431, 28));
        lineEditGUIFileName->setFont(font);
        stackedWidget->addWidget(page_16);
        frame = new QFrame(centralWidget);
        frame->setObjectName("frame");
        frame->setGeometry(QRect(0, 380, 561, 51));
        frame->setFrameShape(QFrame::Panel);
        frame->setFrameShadow(QFrame::Raised);
        pushButtonUpdate = new QPushButton(frame);
        pushButtonUpdate->setObjectName("pushButtonUpdate");
        pushButtonUpdate->setGeometry(QRect(130, 10, 93, 31));
        pushButtonSaveNew = new QPushButton(frame);
        pushButtonSaveNew->setObjectName("pushButtonSaveNew");
        pushButtonSaveNew->setGeometry(QRect(20, 10, 93, 31));
        pushButtonClose = new QPushButton(frame);
        pushButtonClose->setObjectName("pushButtonClose");
        pushButtonClose->setGeometry(QRect(450, 10, 93, 31));
        frame_2 = new QFrame(centralWidget);
        frame_2->setObjectName("frame_2");
        frame_2->setGeometry(QRect(10, 50, 541, 31));
        frame_2->setFrameShape(QFrame::StyledPanel);
        frame_2->setFrameShadow(QFrame::Raised);
        progressBar = new QProgressBar(frame_2);
        progressBar->setObjectName("progressBar");
        progressBar->setGeometry(QRect(0, 0, 531, 23));
        progressBar->setValue(24);
        EditWizardParameterClass->setCentralWidget(centralWidget);

        retranslateUi(EditWizardParameterClass);

        stackedWidget->setCurrentIndex(9);
        stackedWidget_2->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(EditWizardParameterClass);
    } // setupUi

    void retranslateUi(QMainWindow *EditWizardParameterClass)
    {
        EditWizardParameterClass->setWindowTitle(QCoreApplication::translate("EditWizardParameterClass", "EditWizardParameter", nullptr));
        label->setText(QCoreApplication::translate("EditWizardParameterClass", "File name", nullptr));
        pushButtonSearchFileName->setText(QCoreApplication::translate("EditWizardParameterClass", "...", nullptr));
        label_2->setText(QCoreApplication::translate("EditWizardParameterClass", "Resolution", nullptr));
        label_3->setText(QCoreApplication::translate("EditWizardParameterClass", "Resolution (mm/pixel)", nullptr));
        pushButtonNext1->setText(QCoreApplication::translate("EditWizardParameterClass", "Next", nullptr));
        label_69->setText(QCoreApplication::translate("EditWizardParameterClass", "Layer count", nullptr));
        label_5->setText(QCoreApplication::translate("EditWizardParameterClass", "Type", nullptr));
        groupBox->setTitle(QString());
        radioButtonMono->setText(QCoreApplication::translate("EditWizardParameterClass", "Monochrome", nullptr));
        radioButtonColor->setText(QCoreApplication::translate("EditWizardParameterClass", "Color", nullptr));
        label_6->setText(QCoreApplication::translate("EditWizardParameterClass", "Layer count", nullptr));
        pushButtonNext2->setText(QCoreApplication::translate("EditWizardParameterClass", "Next", nullptr));
        pushButtonPrevious2->setText(QCoreApplication::translate("EditWizardParameterClass", "Previous", nullptr));
        label_7->setText(QCoreApplication::translate("EditWizardParameterClass", "X-Y pixel count", nullptr));
        label_8->setText(QCoreApplication::translate("EditWizardParameterClass", "X size (mm)", nullptr));
        label_9->setText(QCoreApplication::translate("EditWizardParameterClass", "Y size (mm)", nullptr));
        label_10->setText(QCoreApplication::translate("EditWizardParameterClass", "X pixels", nullptr));
        label_11->setText(QCoreApplication::translate("EditWizardParameterClass", "Y pixels", nullptr));
        pushButtonMMToPixel->setText(QCoreApplication::translate("EditWizardParameterClass", "\342\206\223", nullptr));
        pushButtonPixelToMM->setText(QCoreApplication::translate("EditWizardParameterClass", "\342\206\221", nullptr));
        pushButtonNext3->setText(QCoreApplication::translate("EditWizardParameterClass", "Next", nullptr));
        pushButtonPrevious3->setText(QCoreApplication::translate("EditWizardParameterClass", "Previous", nullptr));
        label_12->setText(QCoreApplication::translate("EditWizardParameterClass", "Phase / Page/Camera count", nullptr));
        pushButtonNext4->setText(QCoreApplication::translate("EditWizardParameterClass", "Next", nullptr));
        pushButtonPrevious4->setText(QCoreApplication::translate("EditWizardParameterClass", "Previous", nullptr));
        label_13->setText(QCoreApplication::translate("EditWizardParameterClass", "Phase count", nullptr));
        label_14->setText(QCoreApplication::translate("EditWizardParameterClass", "Camera count", nullptr));
        label_53->setText(QCoreApplication::translate("EditWizardParameterClass", "Page count", nullptr));
        pushButtonPrevious5->setText(QCoreApplication::translate("EditWizardParameterClass", "Previous", nullptr));
        pushButtonNext5->setText(QCoreApplication::translate("EditWizardParameterClass", "Next", nullptr));
        label_15->setText(QCoreApplication::translate("EditWizardParameterClass", "SQL Database", nullptr));
        label_16->setText(QCoreApplication::translate("EditWizardParameterClass", "SQL server IP address / Computer name", nullptr));
        label_17->setText(QCoreApplication::translate("EditWizardParameterClass", "SQL database file name (with local path , must be real drive)", nullptr));
        pushButtonLocalDatabase_FileName->setText(QCoreApplication::translate("EditWizardParameterClass", "...", nullptr));
        label_18->setText(QCoreApplication::translate("EditWizardParameterClass", "Firebird port number (Default : 3050)", nullptr));
        label_24->setText(QCoreApplication::translate("EditWizardParameterClass", "DDL file name with path", nullptr));
        pushButtonDatabaseDDL_FileName->setText(QCoreApplication::translate("EditWizardParameterClass", "...", nullptr));
        label_19->setText(QCoreApplication::translate("EditWizardParameterClass", "Master data", nullptr));
        pushButtonNext6->setText(QCoreApplication::translate("EditWizardParameterClass", "Next", nullptr));
        pushButtonPrevious6->setText(QCoreApplication::translate("EditWizardParameterClass", "Previous", nullptr));
        label_20->setText(QCoreApplication::translate("EditWizardParameterClass", "Master data path (netword drive is OK)", nullptr));
        pushButtonImageFilePath->setText(QCoreApplication::translate("EditWizardParameterClass", "...", nullptr));
        pushButtonPrevious7->setText(QCoreApplication::translate("EditWizardParameterClass", "Previous", nullptr));
        label_21->setText(QCoreApplication::translate("EditWizardParameterClass", "Sequence and I/O", nullptr));
        pushButtonNext7->setText(QCoreApplication::translate("EditWizardParameterClass", "Next", nullptr));
        pushButtonSequence_FileName->setText(QCoreApplication::translate("EditWizardParameterClass", "...", nullptr));
        label_22->setText(QCoreApplication::translate("EditWizardParameterClass", "Sequence file with path", nullptr));
        pushButtonIODLL_FileName->setText(QCoreApplication::translate("EditWizardParameterClass", "...", nullptr));
        label_23->setText(QCoreApplication::translate("EditWizardParameterClass", "PIO DLL file", nullptr));
        label_25->setText(QCoreApplication::translate("EditWizardParameterClass", "IO def file with path", nullptr));
        pushButtonIODefine_FileName->setText(QCoreApplication::translate("EditWizardParameterClass", "...", nullptr));
        label_26->setText(QCoreApplication::translate("EditWizardParameterClass", "Parameter in I/O DLL", nullptr));
        label_27->setText(QCoreApplication::translate("EditWizardParameterClass", "Camera", nullptr));
        pushButtonNext8->setText(QCoreApplication::translate("EditWizardParameterClass", "Next", nullptr));
        pushButtonPrevious8->setText(QCoreApplication::translate("EditWizardParameterClass", "Previous", nullptr));
        pushButtonCameraSetting_FileName->setText(QCoreApplication::translate("EditWizardParameterClass", "...", nullptr));
        label_28->setText(QCoreApplication::translate("EditWizardParameterClass", "Camera setting file name with path", nullptr));
        label_29->setText(QCoreApplication::translate("EditWizardParameterClass", "1:Camera DLL file", nullptr));
        pushButtonCameraDLL_FileName->setText(QCoreApplication::translate("EditWizardParameterClass", "...", nullptr));
        label_30->setText(QCoreApplication::translate("EditWizardParameterClass", "Camera allocation", nullptr));
        label_70->setText(QCoreApplication::translate("EditWizardParameterClass", "Camera allocation", nullptr));
        label_71->setText(QCoreApplication::translate("EditWizardParameterClass", "2:Camera DLL file", nullptr));
        pushButtonCameraDLL_FileName2->setText(QCoreApplication::translate("EditWizardParameterClass", "...", nullptr));
        pushButtonCameraAllocation->setText(QCoreApplication::translate("EditWizardParameterClass", "...", nullptr));
        pushButtonCameraAllocation2->setText(QCoreApplication::translate("EditWizardParameterClass", "...", nullptr));
        pushButtonNext9->setText(QCoreApplication::translate("EditWizardParameterClass", "Next", nullptr));
        pushButtonPrevious9->setText(QCoreApplication::translate("EditWizardParameterClass", "Previous", nullptr));
        label_31->setText(QCoreApplication::translate("EditWizardParameterClass", "Result", nullptr));
        label_32->setText(QCoreApplication::translate("EditWizardParameterClass", "Result DLL file with path", nullptr));
        pushButtonResultDLLFileName->setText(QCoreApplication::translate("EditWizardParameterClass", "...", nullptr));
        label_33->setText(QCoreApplication::translate("EditWizardParameterClass", "Max NG count in each page", nullptr));
        label_34->setText(QCoreApplication::translate("EditWizardParameterClass", "Max NG image count in each page", nullptr));
        label_35->setText(QCoreApplication::translate("EditWizardParameterClass", "Max inspection time(mili sec)", nullptr));
        label_36->setText(QCoreApplication::translate("EditWizardParameterClass", "Result buffer count", nullptr));
        label_37->setText(QCoreApplication::translate("EditWizardParameterClass", "Write NG", nullptr));
        checkBoxOutputResult->setText(QString());
        pushButtonPrevious10->setText(QCoreApplication::translate("EditWizardParameterClass", "Previous", nullptr));
        pushButtonNext10->setText(QCoreApplication::translate("EditWizardParameterClass", "Next", nullptr));
        label_51->setText(QCoreApplication::translate("EditWizardParameterClass", "Memory", nullptr));
        label_52->setText(QCoreApplication::translate("EditWizardParameterClass", "Allocate Master image buffer", nullptr));
        checkBoxAllocateMasterBuff->setText(QString());
        checkBoxAllocateTargetBuff->setText(QString());
        label_54->setText(QCoreApplication::translate("EditWizardParameterClass", "Allocate Target image buffer", nullptr));
        label_55->setText(QCoreApplication::translate("EditWizardParameterClass", "Allocate Raw image buffer", nullptr));
        checkBoxAllocRawTargetBuffForNGImage->setText(QString());
        label_56->setText(QCoreApplication::translate("EditWizardParameterClass", "Allocate Camera image buffer", nullptr));
        checkBoxAllocCamTargetBuffer->setText(QString());
        label_57->setText(QCoreApplication::translate("EditWizardParameterClass", "Allocate Delayed view buffer", nullptr));
        checkBoxAllocViewTargetBuffer->setText(QString());
        label_58->setText(QCoreApplication::translate("EditWizardParameterClass", "Memory size to swap out(MegaByte)", nullptr));
        QTableWidgetItem *___qtablewidgetitem = tableWidgetShowMemory->horizontalHeaderItem(0);
        ___qtablewidgetitem->setText(QCoreApplication::translate("EditWizardParameterClass", "Byte", nullptr));
        QTableWidgetItem *___qtablewidgetitem1 = tableWidgetShowMemory->verticalHeaderItem(0);
        ___qtablewidgetitem1->setText(QCoreApplication::translate("EditWizardParameterClass", "Total", nullptr));
        QTableWidgetItem *___qtablewidgetitem2 = tableWidgetShowMemory->verticalHeaderItem(1);
        ___qtablewidgetitem2->setText(QCoreApplication::translate("EditWizardParameterClass", "Each slave", nullptr));
        pushButtonCalcMemory->setText(QCoreApplication::translate("EditWizardParameterClass", "Calc", nullptr));
        pushButtonPrevious11->setText(QCoreApplication::translate("EditWizardParameterClass", "Previous", nullptr));
        pushButtonNext11->setText(QCoreApplication::translate("EditWizardParameterClass", "Next", nullptr));
        label_38->setText(QCoreApplication::translate("EditWizardParameterClass", "Filter", nullptr));
        label_48->setText(QCoreApplication::translate("EditWizardParameterClass", "Filter setting file", nullptr));
        pushButtonFilterDefFile->setText(QCoreApplication::translate("EditWizardParameterClass", "...", nullptr));
        QTableWidgetItem *___qtablewidgetitem3 = tableWidgetFilterListInPage->horizontalHeaderItem(0);
        ___qtablewidgetitem3->setText(QCoreApplication::translate("EditWizardParameterClass", "Page", nullptr));
        QTableWidgetItem *___qtablewidgetitem4 = tableWidgetFilterListInPage->horizontalHeaderItem(1);
        ___qtablewidgetitem4->setText(QCoreApplication::translate("EditWizardParameterClass", "Filter", nullptr));
        label_72->setText(QCoreApplication::translate("EditWizardParameterClass", "Phase", nullptr));
        label_39->setText(QCoreApplication::translate("EditWizardParameterClass", "Slave / Strategy", nullptr));
        pushButtonPrevious12->setText(QCoreApplication::translate("EditWizardParameterClass", "Previous", nullptr));
        pushButtonNext12->setText(QCoreApplication::translate("EditWizardParameterClass", "Next", nullptr));
        label_59->setText(QCoreApplication::translate("EditWizardParameterClass", "Waiting time to communicate to Slave( mili sec)", nullptr));
        label_60->setText(QCoreApplication::translate("EditWizardParameterClass", "Master", nullptr));
        checkBoxMaster->setText(QString());
        QTableWidgetItem *___qtablewidgetitem5 = tableWidgetSlaveList->horizontalHeaderItem(0);
        ___qtablewidgetitem5->setText(QCoreApplication::translate("EditWizardParameterClass", "Slave PC", nullptr));
        QTableWidgetItem *___qtablewidgetitem6 = tableWidgetSlaveList->horizontalHeaderItem(1);
        ___qtablewidgetitem6->setText(QCoreApplication::translate("EditWizardParameterClass", "Camera count", nullptr));
        QTableWidgetItem *___qtablewidgetitem7 = tableWidgetSlaveList->horizontalHeaderItem(2);
        ___qtablewidgetitem7->setText(QCoreApplication::translate("EditWizardParameterClass", "Page count", nullptr));
        QTableWidgetItem *___qtablewidgetitem8 = tableWidgetSlaveList->horizontalHeaderItem(3);
        ___qtablewidgetitem8->setText(QCoreApplication::translate("EditWizardParameterClass", "Allocate", nullptr));
        label_73->setText(QCoreApplication::translate("EditWizardParameterClass", "Master IP/Computer and Port(Optional)", nullptr));
        label_40->setText(QCoreApplication::translate("EditWizardParameterClass", "Outline offset", nullptr));
        pushButtonPrevious13->setText(QCoreApplication::translate("EditWizardParameterClass", "Previous", nullptr));
        pushButtonNext13->setText(QCoreApplication::translate("EditWizardParameterClass", "Next", nullptr));
        QTableWidgetItem *___qtablewidgetitem9 = tableWidgetOutlineOffsetList->horizontalHeaderItem(0);
        ___qtablewidgetitem9->setText(QCoreApplication::translate("EditWizardParameterClass", "Page", nullptr));
        QTableWidgetItem *___qtablewidgetitem10 = tableWidgetOutlineOffsetList->horizontalHeaderItem(1);
        ___qtablewidgetitem10->setText(QCoreApplication::translate("EditWizardParameterClass", "X Pos", nullptr));
        QTableWidgetItem *___qtablewidgetitem11 = tableWidgetOutlineOffsetList->horizontalHeaderItem(2);
        ___qtablewidgetitem11->setText(QCoreApplication::translate("EditWizardParameterClass", "Y Pos", nullptr));
        pushButtonOTileXutlineOffset->setText(QCoreApplication::translate("EditWizardParameterClass", "Tile X", nullptr));
        pushButtonOutlineOffsetTileY->setText(QCoreApplication::translate("EditWizardParameterClass", "Tile Y", nullptr));
        label_66->setText(QCoreApplication::translate("EditWizardParameterClass", "Machine", nullptr));
        label_67->setText(QCoreApplication::translate("EditWizardParameterClass", "Phase", nullptr));
        label_41->setText(QCoreApplication::translate("EditWizardParameterClass", "Light", nullptr));
        pushButtonPrevious14->setText(QCoreApplication::translate("EditWizardParameterClass", "Previous", nullptr));
        pushButtonNext14->setText(QCoreApplication::translate("EditWizardParameterClass", "Next", nullptr));
        label_42->setText(QCoreApplication::translate("EditWizardParameterClass", "Light parameter", nullptr));
        pushButtonLightSettingFileName->setText(QCoreApplication::translate("EditWizardParameterClass", "...", nullptr));
        label_43->setText(QCoreApplication::translate("EditWizardParameterClass", "Light setting file name with path", nullptr));
        label_44->setText(QCoreApplication::translate("EditWizardParameterClass", "1:Light DLL file", nullptr));
        pushButtonLightDLLFileName->setText(QCoreApplication::translate("EditWizardParameterClass", "...", nullptr));
        label_45->setText(QCoreApplication::translate("EditWizardParameterClass", "2:Light DLL file", nullptr));
        label_46->setText(QCoreApplication::translate("EditWizardParameterClass", "Light parameter", nullptr));
        pushButtonLightDLLFileName2->setText(QCoreApplication::translate("EditWizardParameterClass", "...", nullptr));
        checkBoxInitialLightON->setText(QString());
        label_47->setText(QCoreApplication::translate("EditWizardParameterClass", "Initial ON", nullptr));
        pushButtonNext15->setText(QCoreApplication::translate("EditWizardParameterClass", "Next", nullptr));
        pushButtonPrevious15->setText(QCoreApplication::translate("EditWizardParameterClass", "Previous", nullptr));
        label_49->setText(QCoreApplication::translate("EditWizardParameterClass", "Sync GUI", nullptr));
        label_61->setText(QCoreApplication::translate("EditWizardParameterClass", "SyncGUI file name with path", nullptr));
        pushButtonSyncGUIFileName->setText(QCoreApplication::translate("EditWizardParameterClass", "...", nullptr));
        label_62->setText(QCoreApplication::translate("EditWizardParameterClass", "Partner IP/Computer name", nullptr));
        label_63->setText(QCoreApplication::translate("EditWizardParameterClass", "Partner port number", nullptr));
        label_64->setText(QCoreApplication::translate("EditWizardParameterClass", "Own port number", nullptr));
        pushButtonNext16->setText(QCoreApplication::translate("EditWizardParameterClass", "Next", nullptr));
        pushButtonPrevious16->setText(QCoreApplication::translate("EditWizardParameterClass", "Previous", nullptr));
        label_50->setText(QCoreApplication::translate("EditWizardParameterClass", "Image direction", nullptr));
        QTableWidgetItem *___qtablewidgetitem12 = tableWidgetImageDirection->horizontalHeaderItem(0);
        ___qtablewidgetitem12->setText(QCoreApplication::translate("EditWizardParameterClass", "Page", nullptr));
        QTableWidgetItem *___qtablewidgetitem13 = tableWidgetImageDirection->horizontalHeaderItem(1);
        ___qtablewidgetitem13->setText(QCoreApplication::translate("EditWizardParameterClass", "X reverse", nullptr));
        QTableWidgetItem *___qtablewidgetitem14 = tableWidgetImageDirection->horizontalHeaderItem(2);
        ___qtablewidgetitem14->setText(QCoreApplication::translate("EditWizardParameterClass", "Y reverse", nullptr));
        QTableWidgetItem *___qtablewidgetitem15 = tableWidgetImageDirection->horizontalHeaderItem(3);
        ___qtablewidgetitem15->setText(QCoreApplication::translate("EditWizardParameterClass", "Y Delay", nullptr));
        pushButtonNext17->setText(QCoreApplication::translate("EditWizardParameterClass", "Next", nullptr));
        label_65->setText(QCoreApplication::translate("EditWizardParameterClass", "Detail", nullptr));
        pushButtonPrevious17->setText(QCoreApplication::translate("EditWizardParameterClass", "Previous", nullptr));
        pushButtonEditParameter->setText(QCoreApplication::translate("EditWizardParameterClass", "Edit parameter", nullptr));
        pushButtonEditAlgorithmParam->setText(QCoreApplication::translate("EditWizardParameterClass", "Edit Algorithm parameter", nullptr));
        pushButtonEditGUIParam->setText(QCoreApplication::translate("EditWizardParameterClass", "Edit GUI parameter", nullptr));
        pushButtonEditResultParam->setText(QCoreApplication::translate("EditWizardParameterClass", "Edit Result parameter", nullptr));
        pushButtonEditCameraParam->setText(QCoreApplication::translate("EditWizardParameterClass", "Edit Camera parameter", nullptr));
        pushButtonEditLightParam->setText(QCoreApplication::translate("EditWizardParameterClass", "Edit Light setting", nullptr));
        label_68->setText(QCoreApplication::translate("EditWizardParameterClass", "GUI file name with path", nullptr));
        pushButtonGUIFileName->setText(QCoreApplication::translate("EditWizardParameterClass", "...", nullptr));
        pushButtonUpdate->setText(QCoreApplication::translate("EditWizardParameterClass", "Update", nullptr));
        pushButtonSaveNew->setText(QCoreApplication::translate("EditWizardParameterClass", "Save new", nullptr));
        pushButtonClose->setText(QCoreApplication::translate("EditWizardParameterClass", "Close", nullptr));
    } // retranslateUi

};

namespace Ui {
    class EditWizardParameterClass: public Ui_EditWizardParameterClass {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_EDITWIZARDPARAMETER_H
