#ifndef PROPERTYALIGNMENTLARGE_GLOBAL_H
#define PROPERTYALIGNMENTLARGE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PROPERTYALIGNMENTLARGE_LIB
# define PROPERTYALIGNMENTLARGE_EXPORT Q_DECL_EXPORT
#else
# define PROPERTYALIGNMENTLARGE_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTYALIGNMENTLARGE_GLOBAL_H
