#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(INTEGRATIONCALIBRATECAMERA_LIB)
#  define INTEGRATIONCALIBRATECAMERA_EXPORT Q_DECL_EXPORT
# else
#  define INTEGRATIONCALIBRATECAMERA_EXPORT Q_DECL_IMPORT
# endif
#else
# define INTEGRATIONCALIBRATECAMERA_EXPORT
#endif
