#ifndef HOOKEDPROJECTEDHISTGRAM_GLOBAL_H
#define HOOKEDPROJECTEDHISTGRAM_GLOBAL_H

#include <qglobal.h>

#ifdef HOOKEDPROJECTEDHISTGRAM_LIB
# define HOOKEDPROJECTEDHISTGRAM_EXPORT Q_DECL_EXPORT
#else
# define HOOKEDPROJECTEDHISTGRAM_EXPORT Q_DECL_IMPORT
#endif

#endif // HOOKEDPROJECTEDHISTGRAM_GLOBAL_H
