#ifndef WIZARDMASTERMENU_GLOBAL_H
#define WIZARDMASTERMENU_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef WIZARDMASTERMENU_LIB
# define WIZARDMASTERMENU_EXPORT Q_DECL_EXPORT
#else
# define WIZARDMASTERMENU_EXPORT Q_DECL_IMPORT
#endif

#endif // WIZARDMASTERMENU_GLOBAL_H
