# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = WizardMasterMenu
DESTDIR = ../../../GUI
CONFIG += debug
DEFINES += WIZARDMASTERMENU_LIB
LIBS += -L"./../../../Lib/Release" \
    -lComponent \
    -lServiceLib \
    -lIntegrationLib
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += .
RCC_DIR += ./GeneratedFiles
include(WizardMasterMenu.pri)
