#ifndef BUTTONMODEAUTOINCSCANNUMBER_GLOBAL_H
#define BUTTONMODEAUTOINCSCANNUMBER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONMODEAUTOINCSCANNUMBER_LIB
# define BUTTONMODEAUTOINCSCANNUMBER_EXPORT Q_DECL_EXPORT
#else
# define BUTTONMODEAUTOINCSCANNUMBER_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONMODEAUTOINCSCANNUMBER_GLOBAL_H
