#ifndef DOTREGULATION_GLOBAL_H
#define DOTREGULATION_GLOBAL_H

#include <qglobal.h>

#ifdef DOTREGULATION_LIB
# define DOTREGULATION_EXPORT Q_DECL_EXPORT
#else
# define DOTREGULATION_EXPORT Q_DECL_IMPORT
#endif

#endif // DOTREGULATION_GLOBAL_H
