#ifndef REALTIMEIMAGEPANEL_GLOBAL_H
#define REALTIMEIMAGEPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef REALTIMEIMAGEPANEL_LIB
# define REALTIMEIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define REALTIMEIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // REALTIMEIMAGEPANEL_GLOBAL_H
