#ifndef SAVEOUTLINEOFFSETINMASTER_GLOBAL_H
#define SAVEOUTLINEOFFSETINMASTER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SAVEOUTLINEOFFSETINMASTER_LIB
# define SAVEOUTLINEOFFSETINMASTER_EXPORT Q_DECL_EXPORT
#else
# define SAVEOUTLINEOFFSETINMASTER_EXPORT Q_DECL_IMPORT
#endif

#endif // SAVEOUTLINEOFFSETINMASTER_GLOBAL_H
