#ifndef CONTECNC2DSEQ_GLOBAL_H
#define CONTECNC2DSEQ_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef CONTECNC2DSEQ_LIB
# define CONTECNC2DSEQ_EXPORT Q_DECL_EXPORT
#else
# define CONTECNC2DSEQ_EXPORT Q_DECL_IMPORT
#endif

#endif // CONTECNC2DSEQ_GLOBAL_H
