#ifndef LISTMASTERDATAANDLOAD_GLOBAL_H
#define LISTMASTERDATAANDLOAD_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef LISTMASTERDATAANDLOAD_LIB
# define LISTMASTERDATAANDLOAD_EXPORT Q_DECL_EXPORT
#else
# define LISTMASTERDATAANDLOAD_EXPORT Q_DECL_IMPORT
#endif

#endif // LISTMASTERDATAANDLOAD_GLOBAL_H
