#ifndef BUTTONARRANGEPAGE_GLOBAL_H
#define BUTTONARRANGEPAGE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONARRANGEPAGE_LIB
# define BUTTONARRANGEPAGE_EXPORT Q_DECL_EXPORT
#else
# define BUTTONARRANGEPAGE_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONARRANGEPAGE_GLOBAL_H
