#ifndef RESULTXMLMULTIDELIVERY_GLOBAL_H
#define RESULTXMLMULTIDELIVERY_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef RESULTXMLMULTIDELIVERY_LIB
# define RESULTXMLMULTIDELIVERY_EXPORT Q_DECL_EXPORT
#else
# define RESULTXMLMULTIDELIVERY_EXPORT Q_DECL_IMPORT
#endif

#endif // RESULTXMLMULTIDELIVERY_GLOBAL_H
