#ifndef FILTERNOTHING_GLOBAL_H
#define FILTERNOTHING_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef FILTERNOTHING_LIB
# define FILTERNOTHING_EXPORT Q_DECL_EXPORT
#else
# define FILTERNOTHING_EXPORT Q_DECL_IMPORT
#endif

#endif // FILTERNOTHING_GLOBAL_H
