#ifndef RESULTBINDERIMAGEPANEL_GLOBAL_H
#define RESULTBINDERIMAGEPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef RESULTBINDERIMAGEPANEL_LIB
# define RESULTBINDERIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define RESULTBINDERIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // RESULTBINDERIMAGEPANEL_GLOBAL_H
