#ifndef GENERALDIVIDEDPANELS_GLOBAL_H
#define GENERALDIVIDEDPANELS_GLOBAL_H

#include <qglobal.h>

#ifdef GENERALDIVIDEDPANELS_LIB
# define GENERALDIVIDEDPANELS_EXPORT Q_DECL_EXPORT
#else
# define GENERALDIVIDEDPANELS_EXPORT Q_DECL_IMPORT
#endif

#endif // GENERALDIVIDEDPANELS_GLOBAL_H
