#ifndef OUTPUTMESSAGER_GLOBAL_H
#define OUTPUTMESSAGER_GLOBAL_H

#include <qglobal.h>

#ifdef OUTPUTMESSAGER_LIB
# define OUTPUTMESSAGER_EXPORT Q_DECL_EXPORT
#else
# define OUTPUTMESSAGER_EXPORT Q_DECL_IMPORT
#endif

#endif // OUTPUTMESSAGER_GLOBAL_H
