/********************************************************************************
** Form generated from reading UI file 'HistogramForm.ui'
**
** Created by: Qt User Interface Compiler version 6.10.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_HISTOGRAMFORM_H
#define UI_HISTOGRAMFORM_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QListWidget>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QToolButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_HistogramFormClass
{
public:
    QLineEdit *EditLibID;
    QLabel *label_4;
    QLabel *label_5;
    QLineEdit *EditLibName;
    QTabWidget *tabWidgetInspect;
    QWidget *tab_6;
    QLabel *label_23;
    QLabel *label_22;
    QLabel *label_24;
    QLabel *label_21;
    QSpinBox *EditBOKDotL;
    QSpinBox *EditBOKDotH;
    QSpinBox *EditBBrightWidthL;
    QSpinBox *EditBBrightWidthH;
    QSpinBox *EditBOKLengthH;
    QLabel *label_34;
    QSpinBox *EditBOKLengthL;
    QSpinBox *EditBMinNGCountL;
    QSpinBox *EditBMinNGCountH;
    QLabel *label_35;
    QLabel *label_37;
    QSpinBox *EditBConnectLen;
    QLabel *label_51;
    QCheckBox *checkBModeBindBWBroad;
    QSpinBox *EditBMaxNGDotH;
    QSpinBox *EditBMaxNGDotL;
    QDoubleSpinBox *doubleSpinBoxBOKDotL;
    QDoubleSpinBox *doubleSpinBoxBOKDotH;
    QDoubleSpinBox *doubleSpinBoxBOKLengthL;
    QDoubleSpinBox *doubleSpinBoxBOKLengthH;
    QDoubleSpinBox *doubleSpinBoxBMaxNGDotL;
    QDoubleSpinBox *doubleSpinBoxBMaxNGDotH;
    QLabel *labelUnitName_4;
    QLabel *labelUnitName_5;
    QLabel *labelUnitName_6;
    QLabel *labelUnitName_8;
    QWidget *tab_5;
    QSpinBox *EditNBrightWidthL;
    QSpinBox *EditNOKDotL;
    QSpinBox *EditNOKDotH;
    QLabel *label_17;
    QLabel *label_18;
    QSpinBox *EditNBrightWidthH;
    QLabel *label_19;
    QLabel *label_20;
    QSpinBox *EditNOKLengthL;
    QLabel *label_32;
    QSpinBox *EditNOKLengthH;
    QSpinBox *EditNMinNGCountL;
    QSpinBox *EditNMinNGCountH;
    QLabel *label_33;
    QSpinBox *EditNConnectLen;
    QLabel *label_36;
    QLabel *label_52;
    QCheckBox *checkBModeBindBWNarrow;
    QSpinBox *EditNMaxNGDotH;
    QSpinBox *EditNMaxNGDotL;
    QDoubleSpinBox *doubleSpinBoxNOKDotL;
    QDoubleSpinBox *doubleSpinBoxNOKDotH;
    QDoubleSpinBox *doubleSpinBoxNOKLengthL;
    QDoubleSpinBox *doubleSpinBoxNOKLengthH;
    QDoubleSpinBox *doubleSpinBoxNMaxNGDotL;
    QDoubleSpinBox *doubleSpinBoxNMaxNGDotH;
    QLabel *labelUnitName;
    QLabel *labelUnitName_2;
    QLabel *labelUnitName_3;
    QWidget *tab_7;
    QCheckBox *checkBModeEnabled;
    QCheckBox *checkBModeAbsoluteBright;
    QCheckBox *checkBModeNGCluster;
    QCheckBox *checkBModeDiffer;
    QCheckBox *checkBModeOnlyMatching;
    QCheckBox *checkBModeWhiteMask;
    QCheckBox *checkBModeBlackMask;
    QCheckBox *checkBModeCenterBrightFromParts;
    QCheckBox *checkBModeInvertLogic;
    QCheckBox *checkBModeSearchDetail;
    QCheckBox *checkBModeDynamicMask;
    QCheckBox *checkBModeAdoptBiggest;
    QCheckBox *checkBModeUseMasterImage;
    QCheckBox *checkBPermitInverted;
    QComboBox *comboBoxMatchPosition;
    QCheckBox *checkBModeOppositeRange;
    QCheckBox *checkBModeUseGlobalLine;
    QSpinBox *EditExpandForGenMask;
    QLabel *label_53;
    QCheckBox *checkModeCalcBothBN;
    QWidget *tab_8;
    QLabel *label_26;
    QLabel *label_25;
    QSpinBox *EditAdjustWhite;
    QCheckBox *checkBModeAdjustable;
    QSpinBox *EditAdjustBlack;
    QWidget *tab_9;
    QLabel *label_27;
    QLabel *label_28;
    QCheckBox *checkBModeCommonMovable;
    QSpinBox *EditSelfSearch;
    QSpinBox *EditCommonMoveDot;
    QDoubleSpinBox *doubleSpinBoxSelfSearch;
    QDoubleSpinBox *doubleSpinBoxCommonMoveDot;
    QLabel *labelUnitName_7;
    QSpinBox *EditFollowLineLayer;
    QLabel *label_44;
    QWidget *Differential;
    QLabel *label_41;
    QSpinBox *EditDiffBrightWidthL;
    QLabel *label_42;
    QSpinBox *EditDiffBrightWidthH;
    QLabel *label_43;
    QFrame *frameLayer;
    QGroupBox *groupBox;
    QRadioButton *radioButtonLightSide1;
    QRadioButton *radioButtonDarkSide1;
    QFrame *frameLineGraph;
    QPushButton *ButtonReflectAllBlocks;
    QPushButton *ButtonClose;
    QFrame *frame;
    QLabel *label_31;
    QLabel *label_29;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_30;
    QLabel *labelResultNLight;
    QLabel *labelResultBDark;
    QLabel *labelResultBLight;
    QLabel *labelResultNDark;
    QPushButton *ButtonCalc;
    QLabel *labelResultNDarkUnit;
    QLabel *labelResultNLightUnit;
    QLabel *labelResultBDarkUnit;
    QLabel *labelResultBLightUnit;
    QLabel *labelUnitName_9;
    QLabel *labelUnitName_10;
    QStackedWidget *stackedWidgetParts;
    QWidget *page;
    QPushButton *ButtonRelrectOnlyBlock;
    QWidget *page_3;
    QPushButton *ButtonRelrectSaveParts;
    QWidget *page_2;
    QPushButton *ButtonLoadFromLibrary;
    QPushButton *ButtonSaveToLibrary;
    QFrame *frameMaster;
    QLabel *label_3;
    QLabel *label_7;
    QFrame *frameTarget;
    QFrame *frameThreshold;
    QLabel *label_8;
    QPushButton *pushButtonChangeLib;
    QLabel *label_38;
    QLabel *label_39;
    QLineEdit *EditCenterBrightMaster;
    QLineEdit *EditCenterBrightTarget;
    QLabel *label_40;
    QListWidget *listWidgetHistList;
    QFrame *frame_SimImage;
    QToolButton *toolButtonSimShowBlock;
    QToolButton *toolButtonSimShowBright;
    QPushButton *pushButtonSimShowCenterPos;
    QLabel *label_9;
    QLineEdit *EditItemName;
    QPushButton *pushButtonTransmitItemNameAll;
    QCheckBox *checkBoxUseRegularBrightness;
    QPushButton *pushButtonClearManualChange;
    QTableWidget *tableWidgetShift;
    QPushButton *pushButtonRestore;

    void setupUi(QWidget *HistogramFormClass)
    {
        if (HistogramFormClass->objectName().isEmpty())
            HistogramFormClass->setObjectName("HistogramFormClass");
        HistogramFormClass->resize(1021, 759);
        EditLibID = new QLineEdit(HistogramFormClass);
        EditLibID->setObjectName("EditLibID");
        EditLibID->setGeometry(QRect(10, 470, 61, 21));
        EditLibID->setReadOnly(true);
        label_4 = new QLabel(HistogramFormClass);
        label_4->setObjectName("label_4");
        label_4->setGeometry(QRect(10, 450, 62, 20));
        label_4->setFrameShape(QFrame::Panel);
        label_4->setFrameShadow(QFrame::Sunken);
        label_4->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_5 = new QLabel(HistogramFormClass);
        label_5->setObjectName("label_5");
        label_5->setGeometry(QRect(70, 450, 101, 20));
        label_5->setFrameShape(QFrame::Panel);
        label_5->setFrameShadow(QFrame::Sunken);
        label_5->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditLibName = new QLineEdit(HistogramFormClass);
        EditLibName->setObjectName("EditLibName");
        EditLibName->setGeometry(QRect(10, 490, 131, 21));
        EditLibName->setReadOnly(true);
        tabWidgetInspect = new QTabWidget(HistogramFormClass);
        tabWidgetInspect->setObjectName("tabWidgetInspect");
        tabWidgetInspect->setGeometry(QRect(180, 360, 331, 291));
        tab_6 = new QWidget();
        tab_6->setObjectName("tab_6");
        label_23 = new QLabel(tab_6);
        label_23->setObjectName("label_23");
        label_23->setGeometry(QRect(140, 10, 91, 21));
        label_23->setFrameShape(QFrame::Panel);
        label_23->setFrameShadow(QFrame::Sunken);
        label_23->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_22 = new QLabel(tab_6);
        label_22->setObjectName("label_22");
        label_22->setGeometry(QRect(10, 30, 121, 20));
        label_22->setFrameShape(QFrame::Panel);
        label_22->setFrameShadow(QFrame::Sunken);
        label_22->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_24 = new QLabel(tab_6);
        label_24->setObjectName("label_24");
        label_24->setGeometry(QRect(10, 50, 121, 20));
        label_24->setFrameShape(QFrame::Panel);
        label_24->setFrameShadow(QFrame::Sunken);
        label_24->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_21 = new QLabel(tab_6);
        label_21->setObjectName("label_21");
        label_21->setGeometry(QRect(230, 10, 91, 21));
        label_21->setFrameShape(QFrame::Panel);
        label_21->setFrameShadow(QFrame::Sunken);
        label_21->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditBOKDotL = new QSpinBox(tab_6);
        EditBOKDotL->setObjectName("EditBOKDotL");
        EditBOKDotL->setGeometry(QRect(140, 50, 91, 20));
        EditBOKDotL->setMaximum(99999999);
        EditBOKDotL->setValue(1000000);
        EditBOKDotH = new QSpinBox(tab_6);
        EditBOKDotH->setObjectName("EditBOKDotH");
        EditBOKDotH->setGeometry(QRect(230, 50, 91, 20));
        EditBOKDotH->setMaximum(99999999);
        EditBBrightWidthL = new QSpinBox(tab_6);
        EditBBrightWidthL->setObjectName("EditBBrightWidthL");
        EditBBrightWidthL->setGeometry(QRect(140, 30, 91, 20));
        EditBBrightWidthL->setMinimum(-255);
        EditBBrightWidthL->setMaximum(255);
        EditBBrightWidthH = new QSpinBox(tab_6);
        EditBBrightWidthH->setObjectName("EditBBrightWidthH");
        EditBBrightWidthH->setGeometry(QRect(230, 30, 91, 20));
        EditBBrightWidthH->setMinimum(-255);
        EditBBrightWidthH->setMaximum(255);
        EditBOKLengthH = new QSpinBox(tab_6);
        EditBOKLengthH->setObjectName("EditBOKLengthH");
        EditBOKLengthH->setGeometry(QRect(230, 100, 91, 20));
        EditBOKLengthH->setMaximum(99999999);
        label_34 = new QLabel(tab_6);
        label_34->setObjectName("label_34");
        label_34->setGeometry(QRect(10, 100, 121, 20));
        label_34->setFrameShape(QFrame::Panel);
        label_34->setFrameShadow(QFrame::Sunken);
        label_34->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditBOKLengthL = new QSpinBox(tab_6);
        EditBOKLengthL->setObjectName("EditBOKLengthL");
        EditBOKLengthL->setGeometry(QRect(140, 100, 91, 20));
        EditBOKLengthL->setMaximum(99999999);
        EditBMinNGCountL = new QSpinBox(tab_6);
        EditBMinNGCountL->setObjectName("EditBMinNGCountL");
        EditBMinNGCountL->setGeometry(QRect(140, 200, 91, 20));
        EditBMinNGCountL->setMaximum(99999999);
        EditBMinNGCountH = new QSpinBox(tab_6);
        EditBMinNGCountH->setObjectName("EditBMinNGCountH");
        EditBMinNGCountH->setGeometry(QRect(230, 200, 91, 20));
        EditBMinNGCountH->setMaximum(99999999);
        label_35 = new QLabel(tab_6);
        label_35->setObjectName("label_35");
        label_35->setGeometry(QRect(10, 200, 121, 20));
        label_35->setFrameShape(QFrame::Panel);
        label_35->setFrameShadow(QFrame::Sunken);
        label_35->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_37 = new QLabel(tab_6);
        label_37->setObjectName("label_37");
        label_37->setGeometry(QRect(10, 230, 121, 21));
        label_37->setFrameShape(QFrame::Panel);
        label_37->setFrameShadow(QFrame::Sunken);
        label_37->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditBConnectLen = new QSpinBox(tab_6);
        EditBConnectLen->setObjectName("EditBConnectLen");
        EditBConnectLen->setGeometry(QRect(140, 230, 91, 22));
        EditBConnectLen->setMinimum(-9999);
        EditBConnectLen->setMaximum(99999999);
        label_51 = new QLabel(tab_6);
        label_51->setObjectName("label_51");
        label_51->setGeometry(QRect(10, 150, 121, 20));
        label_51->setFrameShape(QFrame::Panel);
        label_51->setFrameShadow(QFrame::Sunken);
        label_51->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        checkBModeBindBWBroad = new QCheckBox(tab_6);
        checkBModeBindBWBroad->setObjectName("checkBModeBindBWBroad");
        checkBModeBindBWBroad->setGeometry(QRect(10, 10, 111, 18));
        EditBMaxNGDotH = new QSpinBox(tab_6);
        EditBMaxNGDotH->setObjectName("EditBMaxNGDotH");
        EditBMaxNGDotH->setGeometry(QRect(230, 150, 91, 20));
        EditBMaxNGDotH->setMaximum(99999999);
        EditBMaxNGDotL = new QSpinBox(tab_6);
        EditBMaxNGDotL->setObjectName("EditBMaxNGDotL");
        EditBMaxNGDotL->setGeometry(QRect(140, 150, 91, 20));
        EditBMaxNGDotL->setMaximum(99999999);
        doubleSpinBoxBOKDotL = new QDoubleSpinBox(tab_6);
        doubleSpinBoxBOKDotL->setObjectName("doubleSpinBoxBOKDotL");
        doubleSpinBoxBOKDotL->setGeometry(QRect(140, 70, 91, 22));
        QPalette palette;
        QBrush brush(QColor(255, 170, 0, 255));
        brush.setStyle(Qt::BrushStyle::SolidPattern);
        palette.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush);
        palette.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush);
        QBrush brush1(QColor(240, 240, 240, 255));
        brush1.setStyle(Qt::BrushStyle::SolidPattern);
        palette.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush1);
        doubleSpinBoxBOKDotL->setPalette(palette);
        doubleSpinBoxBOKDotL->setMaximum(9999999999.000000000000000);
        doubleSpinBoxBOKDotH = new QDoubleSpinBox(tab_6);
        doubleSpinBoxBOKDotH->setObjectName("doubleSpinBoxBOKDotH");
        doubleSpinBoxBOKDotH->setGeometry(QRect(230, 70, 91, 22));
        QPalette palette1;
        palette1.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush);
        palette1.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush);
        palette1.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush1);
        doubleSpinBoxBOKDotH->setPalette(palette1);
        doubleSpinBoxBOKDotH->setMaximum(9999999999.000000000000000);
        doubleSpinBoxBOKLengthL = new QDoubleSpinBox(tab_6);
        doubleSpinBoxBOKLengthL->setObjectName("doubleSpinBoxBOKLengthL");
        doubleSpinBoxBOKLengthL->setGeometry(QRect(140, 120, 91, 22));
        QPalette palette2;
        palette2.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush);
        palette2.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush);
        palette2.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush1);
        doubleSpinBoxBOKLengthL->setPalette(palette2);
        doubleSpinBoxBOKLengthL->setMaximum(9999999999.000000000000000);
        doubleSpinBoxBOKLengthH = new QDoubleSpinBox(tab_6);
        doubleSpinBoxBOKLengthH->setObjectName("doubleSpinBoxBOKLengthH");
        doubleSpinBoxBOKLengthH->setGeometry(QRect(230, 120, 91, 22));
        QPalette palette3;
        palette3.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush);
        palette3.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush);
        palette3.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush1);
        doubleSpinBoxBOKLengthH->setPalette(palette3);
        doubleSpinBoxBOKLengthH->setMaximum(9999999999.000000000000000);
        doubleSpinBoxBMaxNGDotL = new QDoubleSpinBox(tab_6);
        doubleSpinBoxBMaxNGDotL->setObjectName("doubleSpinBoxBMaxNGDotL");
        doubleSpinBoxBMaxNGDotL->setGeometry(QRect(140, 170, 91, 22));
        QPalette palette4;
        palette4.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush);
        palette4.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush);
        palette4.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush1);
        doubleSpinBoxBMaxNGDotL->setPalette(palette4);
        doubleSpinBoxBMaxNGDotL->setMaximum(9999999999.000000000000000);
        doubleSpinBoxBMaxNGDotH = new QDoubleSpinBox(tab_6);
        doubleSpinBoxBMaxNGDotH->setObjectName("doubleSpinBoxBMaxNGDotH");
        doubleSpinBoxBMaxNGDotH->setGeometry(QRect(230, 170, 91, 22));
        QPalette palette5;
        palette5.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush);
        palette5.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush);
        palette5.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush1);
        doubleSpinBoxBMaxNGDotH->setPalette(palette5);
        doubleSpinBoxBMaxNGDotH->setMaximum(9999999999.000000000000000);
        labelUnitName_4 = new QLabel(tab_6);
        labelUnitName_4->setObjectName("labelUnitName_4");
        labelUnitName_4->setGeometry(QRect(40, 70, 91, 20));
        labelUnitName_4->setFrameShape(QFrame::NoFrame);
        labelUnitName_4->setFrameShadow(QFrame::Sunken);
        labelUnitName_4->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        labelUnitName_5 = new QLabel(tab_6);
        labelUnitName_5->setObjectName("labelUnitName_5");
        labelUnitName_5->setGeometry(QRect(40, 120, 91, 20));
        labelUnitName_5->setFrameShape(QFrame::NoFrame);
        labelUnitName_5->setFrameShadow(QFrame::Sunken);
        labelUnitName_5->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        labelUnitName_6 = new QLabel(tab_6);
        labelUnitName_6->setObjectName("labelUnitName_6");
        labelUnitName_6->setGeometry(QRect(40, 170, 91, 20));
        labelUnitName_6->setFrameShape(QFrame::NoFrame);
        labelUnitName_6->setFrameShadow(QFrame::Sunken);
        labelUnitName_6->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        labelUnitName_8 = new QLabel(tab_6);
        labelUnitName_8->setObjectName("labelUnitName_8");
        labelUnitName_8->setGeometry(QRect(320, 60, 61, 20));
        labelUnitName_8->setFrameShape(QFrame::NoFrame);
        labelUnitName_8->setFrameShadow(QFrame::Sunken);
        labelUnitName_8->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        tabWidgetInspect->addTab(tab_6, QString());
        tab_5 = new QWidget();
        tab_5->setObjectName("tab_5");
        EditNBrightWidthL = new QSpinBox(tab_5);
        EditNBrightWidthL->setObjectName("EditNBrightWidthL");
        EditNBrightWidthL->setGeometry(QRect(140, 30, 91, 20));
        EditNBrightWidthL->setMinimum(-255);
        EditNBrightWidthL->setMaximum(255);
        EditNOKDotL = new QSpinBox(tab_5);
        EditNOKDotL->setObjectName("EditNOKDotL");
        EditNOKDotL->setGeometry(QRect(140, 50, 91, 20));
        EditNOKDotL->setMaximum(99999999);
        EditNOKDotH = new QSpinBox(tab_5);
        EditNOKDotH->setObjectName("EditNOKDotH");
        EditNOKDotH->setGeometry(QRect(230, 50, 91, 20));
        EditNOKDotH->setMaximum(99999999);
        label_17 = new QLabel(tab_5);
        label_17->setObjectName("label_17");
        label_17->setGeometry(QRect(10, 30, 121, 21));
        label_17->setFrameShape(QFrame::Panel);
        label_17->setFrameShadow(QFrame::Sunken);
        label_17->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_18 = new QLabel(tab_5);
        label_18->setObjectName("label_18");
        label_18->setGeometry(QRect(10, 50, 121, 20));
        label_18->setFrameShape(QFrame::Panel);
        label_18->setFrameShadow(QFrame::Sunken);
        label_18->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditNBrightWidthH = new QSpinBox(tab_5);
        EditNBrightWidthH->setObjectName("EditNBrightWidthH");
        EditNBrightWidthH->setGeometry(QRect(230, 30, 91, 20));
        EditNBrightWidthH->setMinimum(-255);
        EditNBrightWidthH->setMaximum(255);
        label_19 = new QLabel(tab_5);
        label_19->setObjectName("label_19");
        label_19->setGeometry(QRect(140, 10, 91, 21));
        label_19->setFrameShape(QFrame::Panel);
        label_19->setFrameShadow(QFrame::Sunken);
        label_19->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_20 = new QLabel(tab_5);
        label_20->setObjectName("label_20");
        label_20->setGeometry(QRect(230, 10, 91, 21));
        label_20->setFrameShape(QFrame::Panel);
        label_20->setFrameShadow(QFrame::Sunken);
        label_20->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditNOKLengthL = new QSpinBox(tab_5);
        EditNOKLengthL->setObjectName("EditNOKLengthL");
        EditNOKLengthL->setGeometry(QRect(140, 100, 91, 20));
        EditNOKLengthL->setMaximum(99999999);
        label_32 = new QLabel(tab_5);
        label_32->setObjectName("label_32");
        label_32->setGeometry(QRect(10, 100, 121, 20));
        label_32->setFrameShape(QFrame::Panel);
        label_32->setFrameShadow(QFrame::Sunken);
        label_32->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditNOKLengthH = new QSpinBox(tab_5);
        EditNOKLengthH->setObjectName("EditNOKLengthH");
        EditNOKLengthH->setGeometry(QRect(230, 100, 91, 20));
        EditNOKLengthH->setMaximum(99999999);
        EditNMinNGCountL = new QSpinBox(tab_5);
        EditNMinNGCountL->setObjectName("EditNMinNGCountL");
        EditNMinNGCountL->setGeometry(QRect(140, 200, 91, 20));
        EditNMinNGCountL->setMaximum(99999999);
        EditNMinNGCountH = new QSpinBox(tab_5);
        EditNMinNGCountH->setObjectName("EditNMinNGCountH");
        EditNMinNGCountH->setGeometry(QRect(230, 200, 91, 20));
        EditNMinNGCountH->setMaximum(99999999);
        label_33 = new QLabel(tab_5);
        label_33->setObjectName("label_33");
        label_33->setGeometry(QRect(10, 200, 121, 20));
        label_33->setFrameShape(QFrame::Panel);
        label_33->setFrameShadow(QFrame::Sunken);
        label_33->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditNConnectLen = new QSpinBox(tab_5);
        EditNConnectLen->setObjectName("EditNConnectLen");
        EditNConnectLen->setGeometry(QRect(140, 230, 91, 22));
        EditNConnectLen->setMinimum(-9999);
        EditNConnectLen->setMaximum(99999999);
        label_36 = new QLabel(tab_5);
        label_36->setObjectName("label_36");
        label_36->setGeometry(QRect(10, 230, 121, 20));
        label_36->setFrameShape(QFrame::Panel);
        label_36->setFrameShadow(QFrame::Sunken);
        label_36->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_52 = new QLabel(tab_5);
        label_52->setObjectName("label_52");
        label_52->setGeometry(QRect(10, 150, 121, 20));
        label_52->setFrameShape(QFrame::Panel);
        label_52->setFrameShadow(QFrame::Sunken);
        label_52->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        checkBModeBindBWNarrow = new QCheckBox(tab_5);
        checkBModeBindBWNarrow->setObjectName("checkBModeBindBWNarrow");
        checkBModeBindBWNarrow->setGeometry(QRect(10, 10, 111, 18));
        EditNMaxNGDotH = new QSpinBox(tab_5);
        EditNMaxNGDotH->setObjectName("EditNMaxNGDotH");
        EditNMaxNGDotH->setGeometry(QRect(230, 150, 91, 20));
        EditNMaxNGDotH->setMaximum(99999999);
        EditNMaxNGDotL = new QSpinBox(tab_5);
        EditNMaxNGDotL->setObjectName("EditNMaxNGDotL");
        EditNMaxNGDotL->setGeometry(QRect(140, 150, 91, 20));
        EditNMaxNGDotL->setMaximum(99999999);
        doubleSpinBoxNOKDotL = new QDoubleSpinBox(tab_5);
        doubleSpinBoxNOKDotL->setObjectName("doubleSpinBoxNOKDotL");
        doubleSpinBoxNOKDotL->setGeometry(QRect(140, 70, 91, 22));
        QPalette palette6;
        palette6.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush);
        palette6.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush);
        palette6.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush1);
        doubleSpinBoxNOKDotL->setPalette(palette6);
        doubleSpinBoxNOKDotL->setMaximum(9999999999.000000000000000);
        doubleSpinBoxNOKDotH = new QDoubleSpinBox(tab_5);
        doubleSpinBoxNOKDotH->setObjectName("doubleSpinBoxNOKDotH");
        doubleSpinBoxNOKDotH->setGeometry(QRect(230, 70, 91, 22));
        QPalette palette7;
        palette7.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush);
        palette7.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush);
        palette7.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush1);
        doubleSpinBoxNOKDotH->setPalette(palette7);
        doubleSpinBoxNOKDotH->setMaximum(9999999999.000000000000000);
        doubleSpinBoxNOKLengthL = new QDoubleSpinBox(tab_5);
        doubleSpinBoxNOKLengthL->setObjectName("doubleSpinBoxNOKLengthL");
        doubleSpinBoxNOKLengthL->setGeometry(QRect(140, 120, 91, 22));
        QPalette palette8;
        palette8.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush);
        palette8.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush);
        palette8.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush1);
        doubleSpinBoxNOKLengthL->setPalette(palette8);
        doubleSpinBoxNOKLengthL->setMaximum(9999999999.000000000000000);
        doubleSpinBoxNOKLengthH = new QDoubleSpinBox(tab_5);
        doubleSpinBoxNOKLengthH->setObjectName("doubleSpinBoxNOKLengthH");
        doubleSpinBoxNOKLengthH->setGeometry(QRect(230, 120, 91, 22));
        QPalette palette9;
        palette9.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush);
        palette9.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush);
        palette9.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush1);
        doubleSpinBoxNOKLengthH->setPalette(palette9);
        doubleSpinBoxNOKLengthH->setMaximum(9999999999.000000000000000);
        doubleSpinBoxNMaxNGDotL = new QDoubleSpinBox(tab_5);
        doubleSpinBoxNMaxNGDotL->setObjectName("doubleSpinBoxNMaxNGDotL");
        doubleSpinBoxNMaxNGDotL->setGeometry(QRect(140, 170, 91, 22));
        QPalette palette10;
        palette10.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush);
        palette10.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush);
        palette10.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush1);
        doubleSpinBoxNMaxNGDotL->setPalette(palette10);
        doubleSpinBoxNMaxNGDotL->setMaximum(9999999999.000000000000000);
        doubleSpinBoxNMaxNGDotH = new QDoubleSpinBox(tab_5);
        doubleSpinBoxNMaxNGDotH->setObjectName("doubleSpinBoxNMaxNGDotH");
        doubleSpinBoxNMaxNGDotH->setGeometry(QRect(230, 170, 91, 22));
        QPalette palette11;
        palette11.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush);
        palette11.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush);
        palette11.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush1);
        doubleSpinBoxNMaxNGDotH->setPalette(palette11);
        doubleSpinBoxNMaxNGDotH->setMaximum(9999999999.000000000000000);
        labelUnitName = new QLabel(tab_5);
        labelUnitName->setObjectName("labelUnitName");
        labelUnitName->setGeometry(QRect(40, 70, 91, 20));
        labelUnitName->setFrameShape(QFrame::NoFrame);
        labelUnitName->setFrameShadow(QFrame::Sunken);
        labelUnitName->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        labelUnitName_2 = new QLabel(tab_5);
        labelUnitName_2->setObjectName("labelUnitName_2");
        labelUnitName_2->setGeometry(QRect(40, 120, 91, 20));
        labelUnitName_2->setFrameShape(QFrame::NoFrame);
        labelUnitName_2->setFrameShadow(QFrame::Sunken);
        labelUnitName_2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        labelUnitName_3 = new QLabel(tab_5);
        labelUnitName_3->setObjectName("labelUnitName_3");
        labelUnitName_3->setGeometry(QRect(40, 170, 91, 20));
        labelUnitName_3->setFrameShape(QFrame::NoFrame);
        labelUnitName_3->setFrameShadow(QFrame::Sunken);
        labelUnitName_3->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        tabWidgetInspect->addTab(tab_5, QString());
        tab_7 = new QWidget();
        tab_7->setObjectName("tab_7");
        checkBModeEnabled = new QCheckBox(tab_7);
        checkBModeEnabled->setObjectName("checkBModeEnabled");
        checkBModeEnabled->setGeometry(QRect(10, 10, 141, 18));
        checkBModeAbsoluteBright = new QCheckBox(tab_7);
        checkBModeAbsoluteBright->setObjectName("checkBModeAbsoluteBright");
        checkBModeAbsoluteBright->setGeometry(QRect(10, 30, 141, 18));
        checkBModeNGCluster = new QCheckBox(tab_7);
        checkBModeNGCluster->setObjectName("checkBModeNGCluster");
        checkBModeNGCluster->setGeometry(QRect(10, 50, 141, 18));
        checkBModeDiffer = new QCheckBox(tab_7);
        checkBModeDiffer->setObjectName("checkBModeDiffer");
        checkBModeDiffer->setGeometry(QRect(10, 70, 141, 18));
        checkBModeOnlyMatching = new QCheckBox(tab_7);
        checkBModeOnlyMatching->setObjectName("checkBModeOnlyMatching");
        checkBModeOnlyMatching->setGeometry(QRect(160, 10, 141, 18));
        checkBModeWhiteMask = new QCheckBox(tab_7);
        checkBModeWhiteMask->setObjectName("checkBModeWhiteMask");
        checkBModeWhiteMask->setGeometry(QRect(160, 30, 141, 18));
        checkBModeBlackMask = new QCheckBox(tab_7);
        checkBModeBlackMask->setObjectName("checkBModeBlackMask");
        checkBModeBlackMask->setGeometry(QRect(160, 50, 141, 18));
        checkBModeCenterBrightFromParts = new QCheckBox(tab_7);
        checkBModeCenterBrightFromParts->setObjectName("checkBModeCenterBrightFromParts");
        checkBModeCenterBrightFromParts->setGeometry(QRect(160, 70, 141, 18));
        checkBModeInvertLogic = new QCheckBox(tab_7);
        checkBModeInvertLogic->setObjectName("checkBModeInvertLogic");
        checkBModeInvertLogic->setGeometry(QRect(160, 90, 141, 18));
        checkBModeSearchDetail = new QCheckBox(tab_7);
        checkBModeSearchDetail->setObjectName("checkBModeSearchDetail");
        checkBModeSearchDetail->setGeometry(QRect(160, 130, 141, 18));
        checkBModeDynamicMask = new QCheckBox(tab_7);
        checkBModeDynamicMask->setObjectName("checkBModeDynamicMask");
        checkBModeDynamicMask->setGeometry(QRect(160, 150, 141, 18));
        checkBModeAdoptBiggest = new QCheckBox(tab_7);
        checkBModeAdoptBiggest->setObjectName("checkBModeAdoptBiggest");
        checkBModeAdoptBiggest->setGeometry(QRect(10, 130, 141, 18));
        checkBModeUseMasterImage = new QCheckBox(tab_7);
        checkBModeUseMasterImage->setObjectName("checkBModeUseMasterImage");
        checkBModeUseMasterImage->setGeometry(QRect(160, 170, 151, 18));
        checkBPermitInverted = new QCheckBox(tab_7);
        checkBPermitInverted->setObjectName("checkBPermitInverted");
        checkBPermitInverted->setGeometry(QRect(10, 110, 141, 18));
        comboBoxMatchPosition = new QComboBox(tab_7);
        comboBoxMatchPosition->addItem(QString());
        comboBoxMatchPosition->addItem(QString());
        comboBoxMatchPosition->addItem(QString());
        comboBoxMatchPosition->addItem(QString());
        comboBoxMatchPosition->setObjectName("comboBoxMatchPosition");
        comboBoxMatchPosition->setGeometry(QRect(10, 160, 141, 24));
        checkBModeOppositeRange = new QCheckBox(tab_7);
        checkBModeOppositeRange->setObjectName("checkBModeOppositeRange");
        checkBModeOppositeRange->setGeometry(QRect(160, 110, 161, 18));
        checkBModeUseGlobalLine = new QCheckBox(tab_7);
        checkBModeUseGlobalLine->setObjectName("checkBModeUseGlobalLine");
        checkBModeUseGlobalLine->setGeometry(QRect(10, 190, 151, 18));
        EditExpandForGenMask = new QSpinBox(tab_7);
        EditExpandForGenMask->setObjectName("EditExpandForGenMask");
        EditExpandForGenMask->setGeometry(QRect(260, 220, 61, 21));
        QFont font;
        font.setPointSize(9);
        EditExpandForGenMask->setFont(font);
        EditExpandForGenMask->setMaximum(1000);
        label_53 = new QLabel(tab_7);
        label_53->setObjectName("label_53");
        label_53->setGeometry(QRect(10, 220, 241, 21));
        label_53->setFrameShape(QFrame::Panel);
        label_53->setFrameShadow(QFrame::Sunken);
        label_53->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        checkModeCalcBothBN = new QCheckBox(tab_7);
        checkModeCalcBothBN->setObjectName("checkModeCalcBothBN");
        checkModeCalcBothBN->setGeometry(QRect(160, 190, 151, 18));
        tabWidgetInspect->addTab(tab_7, QString());
        tab_8 = new QWidget();
        tab_8->setObjectName("tab_8");
        label_26 = new QLabel(tab_8);
        label_26->setObjectName("label_26");
        label_26->setGeometry(QRect(10, 70, 201, 21));
        label_26->setFrameShape(QFrame::Panel);
        label_26->setFrameShadow(QFrame::Sunken);
        label_26->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_25 = new QLabel(tab_8);
        label_25->setObjectName("label_25");
        label_25->setGeometry(QRect(10, 40, 201, 21));
        label_25->setFrameShape(QFrame::Panel);
        label_25->setFrameShadow(QFrame::Sunken);
        label_25->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditAdjustWhite = new QSpinBox(tab_8);
        EditAdjustWhite->setObjectName("EditAdjustWhite");
        EditAdjustWhite->setGeometry(QRect(220, 70, 81, 22));
        EditAdjustWhite->setMaximum(255);
        checkBModeAdjustable = new QCheckBox(tab_8);
        checkBModeAdjustable->setObjectName("checkBModeAdjustable");
        checkBModeAdjustable->setGeometry(QRect(30, 10, 241, 18));
        EditAdjustBlack = new QSpinBox(tab_8);
        EditAdjustBlack->setObjectName("EditAdjustBlack");
        EditAdjustBlack->setGeometry(QRect(220, 40, 81, 22));
        EditAdjustBlack->setMaximum(255);
        tabWidgetInspect->addTab(tab_8, QString());
        tab_9 = new QWidget();
        tab_9->setObjectName("tab_9");
        label_27 = new QLabel(tab_9);
        label_27->setObjectName("label_27");
        label_27->setGeometry(QRect(10, 40, 201, 21));
        label_27->setFrameShape(QFrame::Panel);
        label_27->setFrameShadow(QFrame::Sunken);
        label_27->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_28 = new QLabel(tab_9);
        label_28->setObjectName("label_28");
        label_28->setGeometry(QRect(10, 100, 201, 21));
        label_28->setFrameShape(QFrame::Panel);
        label_28->setFrameShadow(QFrame::Sunken);
        label_28->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        checkBModeCommonMovable = new QCheckBox(tab_9);
        checkBModeCommonMovable->setObjectName("checkBModeCommonMovable");
        checkBModeCommonMovable->setGeometry(QRect(40, 10, 231, 18));
        EditSelfSearch = new QSpinBox(tab_9);
        EditSelfSearch->setObjectName("EditSelfSearch");
        EditSelfSearch->setGeometry(QRect(220, 40, 91, 22));
        EditCommonMoveDot = new QSpinBox(tab_9);
        EditCommonMoveDot->setObjectName("EditCommonMoveDot");
        EditCommonMoveDot->setGeometry(QRect(220, 100, 91, 22));
        doubleSpinBoxSelfSearch = new QDoubleSpinBox(tab_9);
        doubleSpinBoxSelfSearch->setObjectName("doubleSpinBoxSelfSearch");
        doubleSpinBoxSelfSearch->setGeometry(QRect(220, 60, 91, 22));
        QPalette palette12;
        palette12.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush);
        palette12.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush);
        palette12.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush1);
        doubleSpinBoxSelfSearch->setPalette(palette12);
        doubleSpinBoxSelfSearch->setMaximum(9999999999.000000000000000);
        doubleSpinBoxCommonMoveDot = new QDoubleSpinBox(tab_9);
        doubleSpinBoxCommonMoveDot->setObjectName("doubleSpinBoxCommonMoveDot");
        doubleSpinBoxCommonMoveDot->setGeometry(QRect(220, 120, 91, 22));
        QPalette palette13;
        palette13.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush);
        palette13.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush);
        palette13.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush1);
        doubleSpinBoxCommonMoveDot->setPalette(palette13);
        doubleSpinBoxCommonMoveDot->setMaximum(9999999999.000000000000000);
        labelUnitName_7 = new QLabel(tab_9);
        labelUnitName_7->setObjectName("labelUnitName_7");
        labelUnitName_7->setGeometry(QRect(120, 60, 91, 20));
        labelUnitName_7->setFrameShape(QFrame::NoFrame);
        labelUnitName_7->setFrameShadow(QFrame::Sunken);
        labelUnitName_7->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        EditFollowLineLayer = new QSpinBox(tab_9);
        EditFollowLineLayer->setObjectName("EditFollowLineLayer");
        EditFollowLineLayer->setGeometry(QRect(220, 150, 91, 22));
        EditFollowLineLayer->setMinimum(-1);
        label_44 = new QLabel(tab_9);
        label_44->setObjectName("label_44");
        label_44->setGeometry(QRect(10, 150, 201, 21));
        label_44->setFrameShape(QFrame::Panel);
        label_44->setFrameShadow(QFrame::Sunken);
        label_44->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        tabWidgetInspect->addTab(tab_9, QString());
        Differential = new QWidget();
        Differential->setObjectName("Differential");
        label_41 = new QLabel(Differential);
        label_41->setObjectName("label_41");
        label_41->setGeometry(QRect(10, 30, 121, 21));
        label_41->setFrameShape(QFrame::Panel);
        label_41->setFrameShadow(QFrame::Sunken);
        label_41->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditDiffBrightWidthL = new QSpinBox(Differential);
        EditDiffBrightWidthL->setObjectName("EditDiffBrightWidthL");
        EditDiffBrightWidthL->setGeometry(QRect(140, 30, 81, 20));
        EditDiffBrightWidthL->setMinimum(-255);
        EditDiffBrightWidthL->setMaximum(255);
        label_42 = new QLabel(Differential);
        label_42->setObjectName("label_42");
        label_42->setGeometry(QRect(230, 10, 81, 21));
        label_42->setFrameShape(QFrame::Panel);
        label_42->setFrameShadow(QFrame::Sunken);
        label_42->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditDiffBrightWidthH = new QSpinBox(Differential);
        EditDiffBrightWidthH->setObjectName("EditDiffBrightWidthH");
        EditDiffBrightWidthH->setGeometry(QRect(230, 30, 81, 20));
        EditDiffBrightWidthH->setMinimum(-255);
        EditDiffBrightWidthH->setMaximum(255);
        label_43 = new QLabel(Differential);
        label_43->setObjectName("label_43");
        label_43->setGeometry(QRect(140, 10, 81, 21));
        label_43->setFrameShape(QFrame::Panel);
        label_43->setFrameShadow(QFrame::Sunken);
        label_43->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        tabWidgetInspect->addTab(Differential, QString());
        frameLayer = new QFrame(HistogramFormClass);
        frameLayer->setObjectName("frameLayer");
        frameLayer->setGeometry(QRect(10, 360, 161, 41));
        frameLayer->setFrameShape(QFrame::NoFrame);
        frameLayer->setFrameShadow(QFrame::Plain);
        groupBox = new QGroupBox(HistogramFormClass);
        groupBox->setObjectName("groupBox");
        groupBox->setGeometry(QRect(0, 530, 171, 21));
        radioButtonLightSide1 = new QRadioButton(groupBox);
        radioButtonLightSide1->setObjectName("radioButtonLightSide1");
        radioButtonLightSide1->setGeometry(QRect(90, 0, 81, 18));
        radioButtonLightSide1->setChecked(false);
        radioButtonDarkSide1 = new QRadioButton(groupBox);
        radioButtonDarkSide1->setObjectName("radioButtonDarkSide1");
        radioButtonDarkSide1->setGeometry(QRect(10, 0, 81, 18));
        radioButtonDarkSide1->setChecked(true);
        frameLineGraph = new QFrame(HistogramFormClass);
        frameLineGraph->setObjectName("frameLineGraph");
        frameLineGraph->setGeometry(QRect(0, 40, 691, 311));
        frameLineGraph->setFrameShape(QFrame::NoFrame);
        frameLineGraph->setFrameShadow(QFrame::Plain);
        ButtonReflectAllBlocks = new QPushButton(HistogramFormClass);
        ButtonReflectAllBlocks->setObjectName("ButtonReflectAllBlocks");
        ButtonReflectAllBlocks->setGeometry(QRect(190, 660, 171, 41));
        ButtonReflectAllBlocks->setAcceptDrops(true);
        ButtonClose = new QPushButton(HistogramFormClass);
        ButtonClose->setObjectName("ButtonClose");
        ButtonClose->setGeometry(QRect(370, 710, 131, 41));
        frame = new QFrame(HistogramFormClass);
        frame->setObjectName("frame");
        frame->setGeometry(QRect(510, 360, 181, 211));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Sunken);
        label_31 = new QLabel(frame);
        label_31->setObjectName("label_31");
        label_31->setGeometry(QRect(0, 0, 181, 21));
        label_31->setFrameShape(QFrame::Panel);
        label_31->setFrameShadow(QFrame::Sunken);
        label_31->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_29 = new QLabel(frame);
        label_29->setObjectName("label_29");
        label_29->setGeometry(QRect(110, 30, 61, 21));
        label_29->setFrameShape(QFrame::Panel);
        label_29->setFrameShadow(QFrame::Sunken);
        label_29->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label = new QLabel(frame);
        label->setObjectName("label");
        label->setGeometry(QRect(4, 60, 47, 21));
        label->setFrameShape(QFrame::Panel);
        label->setFrameShadow(QFrame::Sunken);
        label->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_2 = new QLabel(frame);
        label_2->setObjectName("label_2");
        label_2->setGeometry(QRect(4, 110, 47, 21));
        label_2->setFrameShape(QFrame::Panel);
        label_2->setFrameShadow(QFrame::Sunken);
        label_2->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_30 = new QLabel(frame);
        label_30->setObjectName("label_30");
        label_30->setGeometry(QRect(50, 30, 61, 21));
        label_30->setFrameShape(QFrame::Panel);
        label_30->setFrameShadow(QFrame::Sunken);
        label_30->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        labelResultNLight = new QLabel(frame);
        labelResultNLight->setObjectName("labelResultNLight");
        labelResultNLight->setGeometry(QRect(110, 60, 61, 21));
        labelResultNLight->setFrameShape(QFrame::Panel);
        labelResultNLight->setFrameShadow(QFrame::Sunken);
        labelResultNLight->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        labelResultBDark = new QLabel(frame);
        labelResultBDark->setObjectName("labelResultBDark");
        labelResultBDark->setGeometry(QRect(50, 110, 61, 21));
        labelResultBDark->setFrameShape(QFrame::Panel);
        labelResultBDark->setFrameShadow(QFrame::Sunken);
        labelResultBDark->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        labelResultBLight = new QLabel(frame);
        labelResultBLight->setObjectName("labelResultBLight");
        labelResultBLight->setGeometry(QRect(110, 110, 61, 21));
        labelResultBLight->setFrameShape(QFrame::Panel);
        labelResultBLight->setFrameShadow(QFrame::Sunken);
        labelResultBLight->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        labelResultNDark = new QLabel(frame);
        labelResultNDark->setObjectName("labelResultNDark");
        labelResultNDark->setGeometry(QRect(50, 60, 61, 21));
        labelResultNDark->setFrameShape(QFrame::Panel);
        labelResultNDark->setFrameShadow(QFrame::Sunken);
        labelResultNDark->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        ButtonCalc = new QPushButton(frame);
        ButtonCalc->setObjectName("ButtonCalc");
        ButtonCalc->setGeometry(QRect(50, 170, 111, 31));
        ButtonCalc->setAcceptDrops(true);
        labelResultNDarkUnit = new QLabel(frame);
        labelResultNDarkUnit->setObjectName("labelResultNDarkUnit");
        labelResultNDarkUnit->setGeometry(QRect(50, 80, 61, 21));
        QPalette palette14;
        QBrush brush2(QColor(255, 255, 127, 255));
        brush2.setStyle(Qt::BrushStyle::SolidPattern);
        palette14.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush2);
        palette14.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Window, brush);
        palette14.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush2);
        palette14.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Window, brush);
        palette14.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush);
        palette14.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Window, brush);
        labelResultNDarkUnit->setPalette(palette14);
        labelResultNDarkUnit->setAutoFillBackground(true);
        labelResultNDarkUnit->setFrameShape(QFrame::Panel);
        labelResultNDarkUnit->setFrameShadow(QFrame::Sunken);
        labelResultNDarkUnit->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        labelResultNLightUnit = new QLabel(frame);
        labelResultNLightUnit->setObjectName("labelResultNLightUnit");
        labelResultNLightUnit->setGeometry(QRect(110, 80, 61, 21));
        QPalette palette15;
        palette15.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush2);
        palette15.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Window, brush);
        palette15.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush2);
        palette15.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Window, brush);
        palette15.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush);
        palette15.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Window, brush);
        labelResultNLightUnit->setPalette(palette15);
        labelResultNLightUnit->setAutoFillBackground(true);
        labelResultNLightUnit->setFrameShape(QFrame::Panel);
        labelResultNLightUnit->setFrameShadow(QFrame::Sunken);
        labelResultNLightUnit->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        labelResultBDarkUnit = new QLabel(frame);
        labelResultBDarkUnit->setObjectName("labelResultBDarkUnit");
        labelResultBDarkUnit->setGeometry(QRect(50, 130, 61, 21));
        QPalette palette16;
        palette16.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush2);
        palette16.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Window, brush);
        palette16.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush2);
        palette16.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Window, brush);
        palette16.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush);
        palette16.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Window, brush);
        labelResultBDarkUnit->setPalette(palette16);
        labelResultBDarkUnit->setAutoFillBackground(true);
        labelResultBDarkUnit->setFrameShape(QFrame::Panel);
        labelResultBDarkUnit->setFrameShadow(QFrame::Sunken);
        labelResultBDarkUnit->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        labelResultBLightUnit = new QLabel(frame);
        labelResultBLightUnit->setObjectName("labelResultBLightUnit");
        labelResultBLightUnit->setGeometry(QRect(110, 130, 61, 21));
        QPalette palette17;
        palette17.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush2);
        palette17.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Window, brush);
        palette17.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush2);
        palette17.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Window, brush);
        palette17.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush);
        palette17.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Window, brush);
        labelResultBLightUnit->setPalette(palette17);
        labelResultBLightUnit->setAutoFillBackground(true);
        labelResultBLightUnit->setFrameShape(QFrame::Panel);
        labelResultBLightUnit->setFrameShadow(QFrame::Sunken);
        labelResultBLightUnit->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        labelUnitName_9 = new QLabel(frame);
        labelUnitName_9->setObjectName("labelUnitName_9");
        labelUnitName_9->setGeometry(QRect(10, 80, 31, 20));
        labelUnitName_9->setFrameShape(QFrame::NoFrame);
        labelUnitName_9->setFrameShadow(QFrame::Sunken);
        labelUnitName_9->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        labelUnitName_10 = new QLabel(frame);
        labelUnitName_10->setObjectName("labelUnitName_10");
        labelUnitName_10->setGeometry(QRect(10, 130, 31, 20));
        labelUnitName_10->setFrameShape(QFrame::NoFrame);
        labelUnitName_10->setFrameShadow(QFrame::Sunken);
        labelUnitName_10->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        stackedWidgetParts = new QStackedWidget(HistogramFormClass);
        stackedWidgetParts->setObjectName("stackedWidgetParts");
        stackedWidgetParts->setGeometry(QRect(10, 660, 181, 41));
        page = new QWidget();
        page->setObjectName("page");
        ButtonRelrectOnlyBlock = new QPushButton(page);
        ButtonRelrectOnlyBlock->setObjectName("ButtonRelrectOnlyBlock");
        ButtonRelrectOnlyBlock->setGeometry(QRect(0, 0, 171, 41));
        ButtonRelrectOnlyBlock->setAcceptDrops(true);
        stackedWidgetParts->addWidget(page);
        page_3 = new QWidget();
        page_3->setObjectName("page_3");
        ButtonRelrectSaveParts = new QPushButton(page_3);
        ButtonRelrectSaveParts->setObjectName("ButtonRelrectSaveParts");
        ButtonRelrectSaveParts->setGeometry(QRect(0, 0, 171, 41));
        stackedWidgetParts->addWidget(page_3);
        page_2 = new QWidget();
        page_2->setObjectName("page_2");
        stackedWidgetParts->addWidget(page_2);
        ButtonLoadFromLibrary = new QPushButton(HistogramFormClass);
        ButtonLoadFromLibrary->setObjectName("ButtonLoadFromLibrary");
        ButtonLoadFromLibrary->setGeometry(QRect(190, 710, 171, 41));
        ButtonLoadFromLibrary->setAcceptDrops(true);
        ButtonSaveToLibrary = new QPushButton(HistogramFormClass);
        ButtonSaveToLibrary->setObjectName("ButtonSaveToLibrary");
        ButtonSaveToLibrary->setGeometry(QRect(10, 710, 171, 41));
        ButtonSaveToLibrary->setAcceptDrops(true);
        frameMaster = new QFrame(HistogramFormClass);
        frameMaster->setObjectName("frameMaster");
        frameMaster->setGeometry(QRect(150, 10, 21, 21));
        frameMaster->setFrameShape(QFrame::NoFrame);
        frameMaster->setFrameShadow(QFrame::Plain);
        label_3 = new QLabel(HistogramFormClass);
        label_3->setObjectName("label_3");
        label_3->setGeometry(QRect(180, 10, 131, 21));
        label_7 = new QLabel(HistogramFormClass);
        label_7->setObjectName("label_7");
        label_7->setGeometry(QRect(350, 10, 131, 21));
        frameTarget = new QFrame(HistogramFormClass);
        frameTarget->setObjectName("frameTarget");
        frameTarget->setGeometry(QRect(320, 10, 21, 21));
        frameTarget->setFrameShape(QFrame::NoFrame);
        frameTarget->setFrameShadow(QFrame::Plain);
        frameThreshold = new QFrame(HistogramFormClass);
        frameThreshold->setObjectName("frameThreshold");
        frameThreshold->setGeometry(QRect(480, 10, 21, 21));
        frameThreshold->setFrameShape(QFrame::NoFrame);
        frameThreshold->setFrameShadow(QFrame::Plain);
        label_8 = new QLabel(HistogramFormClass);
        label_8->setObjectName("label_8");
        label_8->setGeometry(QRect(510, 10, 131, 21));
        pushButtonChangeLib = new QPushButton(HistogramFormClass);
        pushButtonChangeLib->setObjectName("pushButtonChangeLib");
        pushButtonChangeLib->setGeometry(QRect(140, 490, 31, 23));
        label_38 = new QLabel(HistogramFormClass);
        label_38->setObjectName("label_38");
        label_38->setGeometry(QRect(10, 600, 121, 21));
        label_38->setFrameShape(QFrame::Panel);
        label_38->setFrameShadow(QFrame::Sunken);
        label_38->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_39 = new QLabel(HistogramFormClass);
        label_39->setObjectName("label_39");
        label_39->setGeometry(QRect(10, 620, 121, 21));
        label_39->setFrameShape(QFrame::Panel);
        label_39->setFrameShadow(QFrame::Sunken);
        label_39->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditCenterBrightMaster = new QLineEdit(HistogramFormClass);
        EditCenterBrightMaster->setObjectName("EditCenterBrightMaster");
        EditCenterBrightMaster->setGeometry(QRect(130, 600, 41, 21));
        QPalette palette18;
        QBrush brush3(QColor(0, 255, 255, 255));
        brush3.setStyle(Qt::BrushStyle::SolidPattern);
        palette18.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush3);
        palette18.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush3);
        QBrush brush4(QColor(192, 192, 192, 255));
        brush4.setStyle(Qt::BrushStyle::SolidPattern);
        palette18.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush4);
        EditCenterBrightMaster->setPalette(palette18);
        EditCenterBrightMaster->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        EditCenterBrightTarget = new QLineEdit(HistogramFormClass);
        EditCenterBrightTarget->setObjectName("EditCenterBrightTarget");
        EditCenterBrightTarget->setGeometry(QRect(130, 620, 41, 21));
        QPalette palette19;
        palette19.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush3);
        palette19.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush3);
        palette19.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush4);
        EditCenterBrightTarget->setPalette(palette19);
        EditCenterBrightTarget->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_40 = new QLabel(HistogramFormClass);
        label_40->setObjectName("label_40");
        label_40->setGeometry(QRect(510, 640, 181, 21));
        label_40->setFrameShape(QFrame::Panel);
        label_40->setFrameShadow(QFrame::Sunken);
        label_40->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        listWidgetHistList = new QListWidget(HistogramFormClass);
        listWidgetHistList->setObjectName("listWidgetHistList");
        listWidgetHistList->setGeometry(QRect(510, 660, 181, 91));
        frame_SimImage = new QFrame(HistogramFormClass);
        frame_SimImage->setObjectName("frame_SimImage");
        frame_SimImage->setGeometry(QRect(700, 50, 311, 541));
        frame_SimImage->setFrameShape(QFrame::StyledPanel);
        frame_SimImage->setFrameShadow(QFrame::Sunken);
        toolButtonSimShowBlock = new QToolButton(HistogramFormClass);
        toolButtonSimShowBlock->setObjectName("toolButtonSimShowBlock");
        toolButtonSimShowBlock->setGeometry(QRect(700, 10, 101, 41));
        toolButtonSimShowBlock->setCheckable(true);
        toolButtonSimShowBlock->setChecked(true);
        toolButtonSimShowBright = new QToolButton(HistogramFormClass);
        toolButtonSimShowBright->setObjectName("toolButtonSimShowBright");
        toolButtonSimShowBright->setGeometry(QRect(820, 10, 101, 41));
        toolButtonSimShowBright->setCheckable(true);
        toolButtonSimShowBright->setChecked(true);
        pushButtonSimShowCenterPos = new QPushButton(HistogramFormClass);
        pushButtonSimShowCenterPos->setObjectName("pushButtonSimShowCenterPos");
        pushButtonSimShowCenterPos->setGeometry(QRect(940, 10, 71, 41));
        label_9 = new QLabel(HistogramFormClass);
        label_9->setObjectName("label_9");
        label_9->setGeometry(QRect(10, 400, 161, 20));
        label_9->setFrameShape(QFrame::Panel);
        label_9->setFrameShadow(QFrame::Sunken);
        label_9->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditItemName = new QLineEdit(HistogramFormClass);
        EditItemName->setObjectName("EditItemName");
        EditItemName->setGeometry(QRect(10, 420, 111, 21));
        EditItemName->setReadOnly(false);
        pushButtonTransmitItemNameAll = new QPushButton(HistogramFormClass);
        pushButtonTransmitItemNameAll->setObjectName("pushButtonTransmitItemNameAll");
        pushButtonTransmitItemNameAll->setGeometry(QRect(120, 420, 51, 23));
        checkBoxUseRegularBrightness = new QCheckBox(HistogramFormClass);
        checkBoxUseRegularBrightness->setObjectName("checkBoxUseRegularBrightness");
        checkBoxUseRegularBrightness->setGeometry(QRect(10, 570, 151, 19));
        pushButtonClearManualChange = new QPushButton(HistogramFormClass);
        pushButtonClearManualChange->setObjectName("pushButtonClearManualChange");
        pushButtonClearManualChange->setGeometry(QRect(510, 580, 181, 41));
        tableWidgetShift = new QTableWidget(HistogramFormClass);
        if (tableWidgetShift->columnCount() < 2)
            tableWidgetShift->setColumnCount(2);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        tableWidgetShift->setHorizontalHeaderItem(0, __qtablewidgetitem);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        tableWidgetShift->setHorizontalHeaderItem(1, __qtablewidgetitem1);
        if (tableWidgetShift->rowCount() < 3)
            tableWidgetShift->setRowCount(3);
        QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
        tableWidgetShift->setVerticalHeaderItem(0, __qtablewidgetitem2);
        QTableWidgetItem *__qtablewidgetitem3 = new QTableWidgetItem();
        tableWidgetShift->setVerticalHeaderItem(1, __qtablewidgetitem3);
        QTableWidgetItem *__qtablewidgetitem4 = new QTableWidgetItem();
        tableWidgetShift->setVerticalHeaderItem(2, __qtablewidgetitem4);
        tableWidgetShift->setObjectName("tableWidgetShift");
        tableWidgetShift->setGeometry(QRect(700, 600, 311, 141));
        pushButtonRestore = new QPushButton(HistogramFormClass);
        pushButtonRestore->setObjectName("pushButtonRestore");
        pushButtonRestore->setGeometry(QRect(370, 660, 131, 41));

        retranslateUi(HistogramFormClass);

        tabWidgetInspect->setCurrentIndex(0);
        stackedWidgetParts->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(HistogramFormClass);
    } // setupUi

    void retranslateUi(QWidget *HistogramFormClass)
    {
        HistogramFormClass->setWindowTitle(QCoreApplication::translate("HistogramFormClass", "HistogramForm", nullptr));
        EditLibID->setText(QCoreApplication::translate("HistogramFormClass", "12345", nullptr));
        label_4->setText(QCoreApplication::translate("HistogramFormClass", "\343\203\251\343\202\244\343\203\226\343\203\251\343\203\252\357\274\251\357\274\244", nullptr));
        label_5->setText(QCoreApplication::translate("HistogramFormClass", "\343\203\251\343\202\244\343\203\226\343\203\251\343\203\252\345\220\215\347\247\260", nullptr));
        EditLibName->setText(QCoreApplication::translate("HistogramFormClass", "XXX", nullptr));
        label_23->setText(QCoreApplication::translate("HistogramFormClass", "\346\232\227\345\201\264", nullptr));
        label_22->setText(QCoreApplication::translate("HistogramFormClass", "OK\350\274\235\345\272\246\347\257\204\345\233\262", nullptr));
        label_24->setText(QCoreApplication::translate("HistogramFormClass", "OK\343\203\211\343\203\203\343\203\210\346\225\260", nullptr));
        label_21->setText(QCoreApplication::translate("HistogramFormClass", "\346\230\216\345\201\264", nullptr));
        label_34->setText(QCoreApplication::translate("HistogramFormClass", "\343\201\223\343\202\214\344\273\245\344\270\212\343\201\256\351\225\267\343\201\225\343\201\247\357\274\256\357\274\247", nullptr));
        label_35->setText(QCoreApplication::translate("HistogramFormClass", "\357\274\256\357\274\247\345\241\212\345\200\213\346\225\260", nullptr));
        label_37->setText(QCoreApplication::translate("HistogramFormClass", "NG\346\216\245\347\266\232\350\267\235\351\233\242(\345\205\261\351\200\232\357\274\211", nullptr));
        label_51->setText(QCoreApplication::translate("HistogramFormClass", "\346\234\200\345\244\247NG\351\235\242\347\251\215", nullptr));
        checkBModeBindBWBroad->setText(QCoreApplication::translate("HistogramFormClass", "\346\230\216\346\232\227\345\220\210\344\270\200", nullptr));
        labelUnitName_4->setText(QCoreApplication::translate("HistogramFormClass", "mm", nullptr));
        labelUnitName_5->setText(QCoreApplication::translate("HistogramFormClass", "mm", nullptr));
        labelUnitName_6->setText(QCoreApplication::translate("HistogramFormClass", "mm", nullptr));
        labelUnitName_8->setText(QCoreApplication::translate("HistogramFormClass", "mm", nullptr));
        tabWidgetInspect->setTabText(tabWidgetInspect->indexOf(tab_6), QCoreApplication::translate("HistogramFormClass", "\345\272\203\345\237\237", nullptr));
        label_17->setText(QCoreApplication::translate("HistogramFormClass", "OK\350\274\235\345\272\246\347\257\204\345\233\262", nullptr));
        label_18->setText(QCoreApplication::translate("HistogramFormClass", "OK\343\203\211\343\203\203\343\203\210\346\225\260", nullptr));
        label_19->setText(QCoreApplication::translate("HistogramFormClass", "\346\232\227\345\201\264", nullptr));
        label_20->setText(QCoreApplication::translate("HistogramFormClass", "\346\230\216\345\201\264", nullptr));
        label_32->setText(QCoreApplication::translate("HistogramFormClass", "\343\201\223\343\202\214\344\273\245\344\270\212\343\201\256\351\225\267\343\201\225\343\201\247\357\274\256\357\274\247", nullptr));
        label_33->setText(QCoreApplication::translate("HistogramFormClass", "NG\345\241\212\345\200\213\346\225\260", nullptr));
        label_36->setText(QCoreApplication::translate("HistogramFormClass", "NG\346\216\245\347\266\232\350\267\235\351\233\242(\345\205\261\351\200\232\357\274\211", nullptr));
        label_52->setText(QCoreApplication::translate("HistogramFormClass", "\346\234\200\345\244\247NG\351\235\242\347\251\215", nullptr));
        checkBModeBindBWNarrow->setText(QCoreApplication::translate("HistogramFormClass", "\346\230\216\346\232\227\345\220\210\344\270\200", nullptr));
        labelUnitName->setText(QCoreApplication::translate("HistogramFormClass", "mm", nullptr));
        labelUnitName_2->setText(QCoreApplication::translate("HistogramFormClass", "mm", nullptr));
        labelUnitName_3->setText(QCoreApplication::translate("HistogramFormClass", "mm", nullptr));
        tabWidgetInspect->setTabText(tabWidgetInspect->indexOf(tab_5), QCoreApplication::translate("HistogramFormClass", "\347\213\255\345\237\237", nullptr));
        checkBModeEnabled->setText(QCoreApplication::translate("HistogramFormClass", "\346\244\234\346\237\273\346\234\211\345\212\271", nullptr));
        checkBModeAbsoluteBright->setText(QCoreApplication::translate("HistogramFormClass", "\347\265\266\345\257\276\350\274\235\345\272\246", nullptr));
        checkBModeNGCluster->setText(QCoreApplication::translate("HistogramFormClass", "\345\241\212\346\244\234\346\237\273", nullptr));
        checkBModeDiffer->setText(QCoreApplication::translate("HistogramFormClass", "\345\267\256\345\210\206\346\244\234\346\237\273", nullptr));
        checkBModeOnlyMatching->setText(QCoreApplication::translate("HistogramFormClass", "\347\265\220\346\236\234\345\207\272\345\212\233\343\201\227\343\201\252\343\201\204", nullptr));
        checkBModeWhiteMask->setText(QCoreApplication::translate("HistogramFormClass", "\347\231\275\343\203\236\343\202\271\343\202\257", nullptr));
        checkBModeBlackMask->setText(QCoreApplication::translate("HistogramFormClass", "\351\273\222\343\203\236\343\202\271\343\202\257", nullptr));
        checkBModeCenterBrightFromParts->setText(QCoreApplication::translate("HistogramFormClass", "\351\203\250\345\223\201\343\201\213\343\202\211\350\274\235\345\272\246\343\202\222\346\212\275\345\207\272\343\201\231\343\202\213", nullptr));
        checkBModeInvertLogic->setText(QCoreApplication::translate("HistogramFormClass", "\350\253\226\347\220\206\345\217\215\350\273\242", nullptr));
        checkBModeSearchDetail->setText(QCoreApplication::translate("HistogramFormClass", "\350\251\263\347\264\260\346\216\242\347\264\242", nullptr));
        checkBModeDynamicMask->setText(QCoreApplication::translate("HistogramFormClass", "\345\256\237\350\241\214\343\203\236\343\202\271\343\202\257", nullptr));
        checkBModeAdoptBiggest->setText(QCoreApplication::translate("HistogramFormClass", "\346\234\200\345\244\247NG\343\201\256\343\201\277\345\210\244\345\256\232", nullptr));
        checkBModeUseMasterImage->setText(QCoreApplication::translate("HistogramFormClass", "Master\347\224\273\345\203\217\343\202\222\344\275\277\347\224\250", nullptr));
        checkBPermitInverted->setText(QCoreApplication::translate("HistogramFormClass", "Permit inverted", nullptr));
        comboBoxMatchPosition->setItemText(0, QCoreApplication::translate("HistogramFormClass", "\350\274\252\351\203\255\350\277\275\351\232\217\343\201\252\343\201\227", nullptr));
        comboBoxMatchPosition->setItemText(1, QCoreApplication::translate("HistogramFormClass", "\350\274\252\351\203\255\350\277\275\351\232\217\357\274\232\351\273\222\347\231\275\347\204\241\350\246\226", nullptr));
        comboBoxMatchPosition->setItemText(2, QCoreApplication::translate("HistogramFormClass", "\350\274\252\351\203\255\350\277\275\351\232\217\357\274\232\345\206\205\351\203\250\347\231\275", nullptr));
        comboBoxMatchPosition->setItemText(3, QCoreApplication::translate("HistogramFormClass", "\350\274\252\351\203\255\350\277\275\351\232\217\357\274\232\345\206\205\351\203\250\351\273\222", nullptr));

        checkBModeOppositeRange->setText(QCoreApplication::translate("HistogramFormClass", "Opposite range", nullptr));
        checkBModeUseGlobalLine->setText(QCoreApplication::translate("HistogramFormClass", "Use GlobalLine", nullptr));
        label_53->setText(QCoreApplication::translate("HistogramFormClass", "Expansion for GenMask", nullptr));
        checkModeCalcBothBN->setText(QCoreApplication::translate("HistogramFormClass", "Calc both BN", nullptr));
        tabWidgetInspect->setTabText(tabWidgetInspect->indexOf(tab_7), QCoreApplication::translate("HistogramFormClass", "\345\261\236\346\200\247", nullptr));
        label_26->setText(QCoreApplication::translate("HistogramFormClass", "\346\230\216\345\201\264\343\200\200\346\234\200\345\244\247\350\243\234\346\255\243\350\274\235\345\272\246\351\207\217", nullptr));
        label_25->setText(QCoreApplication::translate("HistogramFormClass", "\346\232\227\345\201\264\343\200\200\346\234\200\345\244\247\350\243\234\346\255\243\350\274\235\345\272\246\351\207\217", nullptr));
        checkBModeAdjustable->setText(QCoreApplication::translate("HistogramFormClass", "\344\270\255\345\277\203\350\274\235\345\272\246\350\243\234\346\255\243\343\202\222\346\234\211\345\212\271\343\201\253\343\201\231\343\202\213", nullptr));
        tabWidgetInspect->setTabText(tabWidgetInspect->indexOf(tab_8), QCoreApplication::translate("HistogramFormClass", "\350\243\234\346\255\243", nullptr));
        label_27->setText(QCoreApplication::translate("HistogramFormClass", "\343\203\226\343\203\255\343\203\203\343\202\257\345\215\230\344\275\223\343\201\247\343\201\256\346\216\242\347\264\242\343\203\211\343\203\203\343\203\210\346\225\260", nullptr));
        label_28->setText(QCoreApplication::translate("HistogramFormClass", "\345\205\250\344\275\223\343\201\247\343\201\256\346\216\242\347\264\242\343\203\211\343\203\203\343\203\210\346\225\260", nullptr));
        checkBModeCommonMovable->setText(QCoreApplication::translate("HistogramFormClass", "\345\205\250\344\275\223\343\201\247\343\201\256\346\216\242\347\264\242\343\202\222\346\234\211\345\212\271\343\201\253\343\201\231\343\202\213", nullptr));
        labelUnitName_7->setText(QCoreApplication::translate("HistogramFormClass", "mm", nullptr));
        label_44->setText(QCoreApplication::translate("HistogramFormClass", "FollowLine \343\201\256\345\256\237\350\241\214\343\203\254\343\202\244\343\203\244\343\203\274", nullptr));
        tabWidgetInspect->setTabText(tabWidgetInspect->indexOf(tab_9), QCoreApplication::translate("HistogramFormClass", "\346\216\242\347\264\242", nullptr));
        label_41->setText(QCoreApplication::translate("HistogramFormClass", "OK\350\274\235\345\272\246\347\257\204\345\233\262", nullptr));
        label_42->setText(QCoreApplication::translate("HistogramFormClass", "\346\230\216\345\201\264", nullptr));
        label_43->setText(QCoreApplication::translate("HistogramFormClass", "\346\232\227\345\201\264", nullptr));
        tabWidgetInspect->setTabText(tabWidgetInspect->indexOf(Differential), QCoreApplication::translate("HistogramFormClass", "Differential", nullptr));
        radioButtonLightSide1->setText(QCoreApplication::translate("HistogramFormClass", "Light", nullptr));
        radioButtonDarkSide1->setText(QCoreApplication::translate("HistogramFormClass", "Dark", nullptr));
        ButtonReflectAllBlocks->setText(QCoreApplication::translate("HistogramFormClass", "\345\220\214\344\270\200\347\250\256\351\241\236\343\201\256\343\203\226\343\203\255\343\203\203\343\202\257\343\201\253\345\217\215\346\230\240", nullptr));
        ButtonClose->setText(QCoreApplication::translate("HistogramFormClass", "\351\226\211\343\201\230\343\202\213", nullptr));
        label_31->setText(QCoreApplication::translate("HistogramFormClass", "\345\275\223\350\251\262\347\256\207\346\211\200\343\201\256\345\210\244\345\256\232\347\265\220\346\236\234", nullptr));
        label_29->setText(QCoreApplication::translate("HistogramFormClass", "\346\230\216\345\201\264", nullptr));
        label->setText(QCoreApplication::translate("HistogramFormClass", "\347\213\255\345\237\237", nullptr));
        label_2->setText(QCoreApplication::translate("HistogramFormClass", "\345\272\203\345\237\237", nullptr));
        label_30->setText(QCoreApplication::translate("HistogramFormClass", "\346\232\227\345\201\264", nullptr));
        labelResultNLight->setText(QCoreApplication::translate("HistogramFormClass", "123", nullptr));
        labelResultBDark->setText(QCoreApplication::translate("HistogramFormClass", "123", nullptr));
        labelResultBLight->setText(QCoreApplication::translate("HistogramFormClass", "123", nullptr));
        labelResultNDark->setText(QCoreApplication::translate("HistogramFormClass", "123", nullptr));
        ButtonCalc->setText(QCoreApplication::translate("HistogramFormClass", "\350\250\210\347\256\227", nullptr));
        labelResultNDarkUnit->setText(QCoreApplication::translate("HistogramFormClass", "123", nullptr));
        labelResultNLightUnit->setText(QCoreApplication::translate("HistogramFormClass", "123", nullptr));
        labelResultBDarkUnit->setText(QCoreApplication::translate("HistogramFormClass", "123", nullptr));
        labelResultBLightUnit->setText(QCoreApplication::translate("HistogramFormClass", "123", nullptr));
        labelUnitName_9->setText(QCoreApplication::translate("HistogramFormClass", "mm", nullptr));
        labelUnitName_10->setText(QCoreApplication::translate("HistogramFormClass", "mm", nullptr));
        ButtonRelrectOnlyBlock->setText(QCoreApplication::translate("HistogramFormClass", "\343\201\223\343\201\256\343\203\226\343\203\255\343\203\203\343\202\257\343\201\240\343\201\221\343\201\253\345\217\215\346\230\240", nullptr));
        ButtonRelrectSaveParts->setText(QCoreApplication::translate("HistogramFormClass", "\351\203\250\345\223\201\344\277\235\345\255\230", nullptr));
        ButtonLoadFromLibrary->setText(QCoreApplication::translate("HistogramFormClass", "\343\203\251\343\202\244\343\203\226\343\203\251\343\203\252\343\201\213\343\202\211\350\252\255\343\201\277\345\207\272\343\201\227", nullptr));
        ButtonSaveToLibrary->setText(QCoreApplication::translate("HistogramFormClass", "\343\203\251\343\202\244\343\203\226\343\203\251\343\203\252\343\201\253\344\277\235\345\255\230", nullptr));
        label_3->setText(QCoreApplication::translate("HistogramFormClass", "\343\203\236\343\202\271\343\202\277\343\203\274\347\224\273\345\203\217", nullptr));
        label_7->setText(QCoreApplication::translate("HistogramFormClass", "\346\244\234\346\237\273\347\224\273\345\203\217", nullptr));
        label_8->setText(QCoreApplication::translate("HistogramFormClass", "\343\201\227\343\201\215\343\201\204\345\200\244", nullptr));
        pushButtonChangeLib->setText(QCoreApplication::translate("HistogramFormClass", "...", nullptr));
        label_38->setText(QCoreApplication::translate("HistogramFormClass", "\343\203\236\343\202\271\343\202\277\343\203\274\344\270\255\345\277\203\350\274\235\345\272\246", nullptr));
        label_39->setText(QCoreApplication::translate("HistogramFormClass", "Target\344\270\255\345\277\203\350\274\235\345\272\246", nullptr));
        EditCenterBrightMaster->setText(QCoreApplication::translate("HistogramFormClass", "256", nullptr));
        EditCenterBrightTarget->setText(QCoreApplication::translate("HistogramFormClass", "256", nullptr));
        label_40->setText(QCoreApplication::translate("HistogramFormClass", "\345\275\223\350\251\262\347\256\207\346\211\200\343\201\256\343\203\220\343\203\251\343\201\244\343\201\215\343\202\260\343\203\251\343\203\225", nullptr));
        toolButtonSimShowBlock->setText(QCoreApplication::translate("HistogramFormClass", "Block", nullptr));
        toolButtonSimShowBright->setText(QCoreApplication::translate("HistogramFormClass", "\350\274\235\345\272\246NG", nullptr));
        pushButtonSimShowCenterPos->setText(QCoreApplication::translate("HistogramFormClass", "\345\276\251\345\270\260", nullptr));
        label_9->setText(QCoreApplication::translate("HistogramFormClass", "Item name", nullptr));
        EditItemName->setText(QCoreApplication::translate("HistogramFormClass", "XXX", nullptr));
        pushButtonTransmitItemNameAll->setText(QCoreApplication::translate("HistogramFormClass", "To all", nullptr));
        checkBoxUseRegularBrightness->setText(QCoreApplication::translate("HistogramFormClass", "UseRegularBrightness", nullptr));
        pushButtonClearManualChange->setText(QCoreApplication::translate("HistogramFormClass", "Clear manual change", nullptr));
        QTableWidgetItem *___qtablewidgetitem = tableWidgetShift->horizontalHeaderItem(0);
        ___qtablewidgetitem->setText(QCoreApplication::translate("HistogramFormClass", "X", nullptr));
        QTableWidgetItem *___qtablewidgetitem1 = tableWidgetShift->horizontalHeaderItem(1);
        ___qtablewidgetitem1->setText(QCoreApplication::translate("HistogramFormClass", "Y", nullptr));
        QTableWidgetItem *___qtablewidgetitem2 = tableWidgetShift->verticalHeaderItem(0);
        ___qtablewidgetitem2->setText(QCoreApplication::translate("HistogramFormClass", "By Alignment", nullptr));
        QTableWidgetItem *___qtablewidgetitem3 = tableWidgetShift->verticalHeaderItem(1);
        ___qtablewidgetitem3->setText(QCoreApplication::translate("HistogramFormClass", "By Common", nullptr));
        QTableWidgetItem *___qtablewidgetitem4 = tableWidgetShift->verticalHeaderItem(2);
        ___qtablewidgetitem4->setText(QCoreApplication::translate("HistogramFormClass", "By Self", nullptr));
        pushButtonRestore->setText(QCoreApplication::translate("HistogramFormClass", "Restore", nullptr));
    } // retranslateUi

};

namespace Ui {
    class HistogramFormClass: public Ui_HistogramFormClass {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_HISTOGRAMFORM_H
