#ifndef VIAINSPECTIONIMAGEPANEL_GLOBAL_H
#define VIAINSPECTIONIMAGEPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef VIAINSPECTIONIMAGEPANEL_LIB
# define VIAINSPECTIONIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define VIAINSPECTIONIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // VIAINSPECTIONIMAGEPANEL_GLOBAL_H
