#ifndef BUTTONANYMODE_GLOBAL_H
#define BUTTONANYMODE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONANYMODE_LIB
# define BUTTONANYMODE_EXPORT Q_DECL_EXPORT
#else
# define BUTTONANYMODE_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONANYMODE_GLOBAL_H
