#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(SETALIGNMENTLARGEHEADLINE_LIB)
#  define SETALIGNMENTLARGEHEADLINE_EXPORT Q_DECL_EXPORT
# else
#  define SETALIGNMENTLARGEHEADLINE_EXPORT Q_DECL_IMPORT
# endif
#else
# define SETALIGNMENTLARGEHEADLINE_EXPORT
#endif
