#ifndef FIXEDIMAGESIZE_GLOBAL_H
#define FIXEDIMAGESIZE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef FIXEDIMAGESIZE_LIB
# define FIXEDIMAGESIZE_EXPORT Q_DECL_EXPORT
#else
# define FIXEDIMAGESIZE_EXPORT Q_DECL_IMPORT
#endif

#endif // FIXEDIMAGESIZE_GLOBAL_H
