# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


TEMPLATE = subdirs
SUBDIRS += PieceDefImagePanel/PieceDefImagePanel.pro \
    PropertyPieceDef/PropertyPieceDef.pro \
    CheckBrightnessImagePanel/CheckBrightnessImagePanel.pro \
    PropertyCheckBrightness/PropertyCheckBrightness.pro \
    ShowCheckBrightnessPanel/ShowCheckBrightnessPanel.pro \
    PropertyGerberFast/PropertyGerberFast.pro \
    GerberFastImagePanel/GerberFastImagePanel.pro \
    ButtonGenerateFromGerber/ButtonGenerateFromGerber.pro \
    PropertyViaInspection/PropertyViaInspection.pro \
    VIAInspectionImagePanel/VIAInspectionImagePanel.pro \
    PropertyCheckEveryday/PropertyCheckEveryday.pro \
    ShowCheckEveryday/ShowCheckEveryday.pro \
    CheckEverydayImagePanel/CheckEverydayImagePanel.pro \
    CheckEverydayResultHistory/CheckEverydayResultHistory.pro \
    PropertyMultiFileMap/PropertyMultiFileMap.pro \
    MultiFileMapImagePanel/MultiFileMapImagePanel.pro \
    ThinMetalImagePanel/ThinMetalImagePanel.pro \
    PropertyThinMetal/PropertyThinMetal.pro \
    ButtonToStoreSamplesThinMetal/ButtonToStoreSamplesThinMetal.pro \
    ShowThinMetalResultList/ShowThinMetalResultList.pro \
    ProjectedInspectionImagePanel/ProjectedInspectionImagePanel.pro \
    PropertyProjectedInspection/PropertyProjectedInspection.pro \
    StepLineEnhancerLImagePanel/StepLineEnhancerLImagePanel.pro \
    PropertyStepLineEnhancerL/PropertyStepLineEnhancerL.pro \
    HoughInspectionImagePanel/HoughInspectionImagePanel.pro \
    PropertyHoughInspection/PropertyHoughInspection.pro \
    PartialImagingImagePanel/PartialImagingImagePanel.pro \
    PropertyPartialImaging/PropertyPartialImaging.pro \
    ShowPartialImagingPanel/ShowPartialImagingPanel.pro \
    ShowPartialImagingList/ShowPartialImagingList.pro \
    SkipMarkImagePanel/SkipMarkImagePanel.pro \
    PropertySkipMark/PropertySkipMark.pro \
    ShowBlockList/ShowBlockList.pro \
    EulerRingL1ImagePanel/EulerRingL1ImagePanel.pro \
    PropertyEulerRingL1/PropertyEulerRingL1.pro \
    AlignmentFlexAreaImagePanel/AlignmentFlexAreaImagePanel.pro \
    PropertyAlignmentFlexArea/PropertyAlignmentFlexArea.pro \
    FrameDefImagePanel/FrameDefImagePanel.pro \
    PropertyFrameDef/PropertyFrameDef.pro \
    SelectResultLotFrame/SelectResultLotFrame.pro \
    ShowResultFrame/ShowResultFrame.pro \
    OCRImagePanel/OCRImagePanel.pro \
    PropertyOCR/PropertyOCR.pro \
    Process3DImagePanel/Process3DImagePanel.pro \
    PropertyProcess3D/PropertyProcess3D.pro \
    LinePatternImagePanel/LinePatternImagePanel.pro \
    PropertyLinePattern/PropertyLinePattern.pro \
    MatchShiftRotationImagePanel/MatchShiftRotationImagePanel.pro \
    PropertyMatchShiftRotation/PropertyMatchShiftRotation.pro \
    ShowMatchShiftRotation/ShowMatchShiftRotation.pro \
    NickInspectionImagePanel/NickInspectionImagePanel.pro \
    PropertyNickInspection/PropertyNickInspection.pro \
    DotColorMatchingImagePanel/DotColorMatchingImagePanel.pro \
    PropertyDotColorMatching/PropertyDotColorMatching.pro \
    ButtonResetThresholdDotColorMatching/ButtonResetThresholdDotColorMatching.pro \
    ExecuteBatch/ExecuteBatch.pro \
    PanelXYSize/PanelXYSize.pro \
    HookAlgorithmImagePanel/HookAlgorithmImagePanel.pro \
    GeneralPanelFromSeq/GeneralPanelFromSeq.pro \
    ButtonSynchronizeImagePanel/ButtonSynchronizeImagePanel.pro \
    ChangeWindowSizeInvisible/ChangeWindowSizeInvisible.pro \
    CompressImageIndicator/CompressImageIndicator.pro \
    PanelXYCalc/PanelXYCalc.pro \
    ButtonModeAutoIncScanNumber/ButtonModeAutoIncScanNumber.pro \
    PanelInputInformation/PanelInputInformation.pro \
    ShortcutKeyInvisible/ShortcutKeyInvisible.pro \
    PanelXYZSize/PanelXYZSize.pro \
    PanelMaxStock/PanelMaxStock.pro \
    ChangeTurnTop/ChangeTurnTop.pro \
    PanelHidable/PanelHidable.pro
