# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


TEMPLATE = subdirs
SUBDIRS += PropertySwitchPhase/PropertySwitchPhase.pro \
    SwitchPhaseImagePanel/SwitchPhaseImagePanel.pro \
    ShowSwitchPhaseResultList/ShowSwitchPhaseResultList.pro \
    HoleWallInspectionImagePanel/HoleWallInspectionImagePanel.pro \
    PropertyHoleWallInspection/PropertyHoleWallInspection.pro \
    DentImagePanel/DentImagePanel.pro \
    PropertyDent/PropertyDent.pro \
    DXFOperationImagePanel/DXFOperationImagePanel.pro \
    PropertyDXFOperation/PropertyDXFOperation.pro \
    AlignmentProjectionImagePanel/AlignmentProjectionImagePanel.pro \
    PropertyAlignmentProjection/PropertyAlignmentProjection.pro \
    ColorDifferenceImagePanel/ColorDifferenceImagePanel.pro \
    PropertyColorDifference/PropertyColorDifference.pro \
    MakeAverageImagePanel/MakeAverageImagePanel.pro \
    PropertyMakeAverageImage/PropertyMakeAverageImage.pro \
    CounterImagePanel/CounterImagePanel.pro \
    PropertyCounter/PropertyCounter.pro \
    SavePartialImagePanel/SavePartialImagePanel.pro \
    PropertySavePartialImage/PropertySavePartialImage.pro \
    PropertySaveFexedImageByInspect/PropertySaveFexedImageByInspect.pro \
    RasterImagePanel/RasterImagePanel.pro \
    PropertyRaster/PropertyRaster.pro \
    AreaColorConverterImagePanel/AreaColorConverterImagePanel.pro \
    AGVImagePanel/AGVImagePanel.pro \
    PropertyAGV/PropertyAGV.pro \
    KDSBeltInspectionImagePanel/KDSBeltInspectionImagePanel.pro \
    PropertyKDSBeltInspection/PropertyKDSBeltInspection.pro \
    PropertyPalletize/PropertyPalletize.pro \
    PalletizeImagePanel/PalletizeImagePanel.pro \
    MultiSpectralImagePanel/MultiSpectralImagePanel.pro \
    PropertyMultiSpectral/PropertyMultiSpectral.pro \
    RasterInspectionImagePanel/RasterInspectionImagePanel.pro \
    PropertyRasterInspection/PropertyRasterInspection.pro \
    PropertyRepeatControl/PropertyRepeatControl.pro \
    RepeatControlImagePanel/RepeatControlImagePanel.pro \
    ReplaceImagePanel/ReplaceImagePanel.pro \
    PropertyReplaceImage/PropertyReplaceImage.pro \
    ButtonReplaceImageControl/ButtonReplaceImageControl.pro \
    PropertyColorCorrector/PropertyColorCorrector.pro \
    ColorCorrectorImagePanel/ColorCorrectorImagePanel.pro \
    CopyMirroredTransfer/CopyMirroredTransfer.pro \
    ButtonLoadMasterDataInPhase/ButtonLoadMasterDataInPhase.pro \
    ButtonClearMasterInfo/ButtonClearMasterInfo.pro \
    ButtonCopyAnyPhasePageLayer/ButtonCopyAnyPhasePageLayer.pro \
    ButtonSaveScreenCapture/ButtonSaveScreenCapture.pro \
    PanelOkNgEachPhasePage/PanelOkNgEachPhasePage.pro \
    ButtonSwitchPhaseSynchronize/ButtonSwitchPhaseSynchronize.pro \
    ButtonChange/ButtonChange.pro \
    ButtonToShowCrossLine/ButtonToShowCrossLine.pro \
    ButtonSelectStackedPage/ButtonSelectStackedPage.pro \
    ShowMultiImage/ShowMultiImage.pro \
    PanelHide/PanelHide.pro \
    ShowCycleTime/ShowCycleTime.pro \
    ShowFileListBrowser/ShowFileListBrowser.pro \
    PlayVideoWidget/PlayVideoWidget.pro
