# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


TEMPLATE = subdirs
SUBDIRS += DisplayPointingMessage/DisplayPointingMessage.pro \
    ShowMinMaxButton/ShowMinMaxButton.pro \
    ButtonSwitchDelayedView/ButtonSwitchDelayedView.pro \
    DisplayLibFolder/DisplayLibFolder.pro \
    DisplayScanPhaseNumber/DisplayScanPhaseNumber.pro \
    ImagePanelTools/ImagePanelTools.pro \
    DisplayOldImagePanel/DisplayOldImagePanel.pro \
    FixedImageSize/FixedImageSize.pro \
    DisplayRealtimeGraph/DisplayRealtimeGraph.pro \
    PropertyRealtimeGraph/PropertyRealtimeGraph.pro \
    RealtimeGraphMeasure1/RealtimeGraphMeasure1.pro \
    RealtimeImagePanel/RealtimeImagePanel.pro \
    MakeShading/MakeShading.pro \
    PieceForReviewImagePanel/PieceForReviewImagePanel.pro \
    PropertyPieceForReview/PropertyPieceForReview.pro \
    PieceListReviewSide/PieceListReviewSide.pro \
    ButtonSelectLot/ButtonSelectLot.pro \
    ShowHistgramTotal/ShowHistgramTotal.pro \
    ButtonSaveHistogramData/ButtonSaveHistogramData.pro \
    ButtonLoadHistogramData/ButtonLoadHistogramData.pro \
    ButtonClearHistogram/ButtonClearHistogram.pro \
    LoadImageInAnyPageLayer/LoadImageInAnyPageLayer.pro \
    LoadImageInAnyPage/LoadImageInAnyPage.pro \
    ProgressOnIdle/ProgressOnIdle.pro \
    ButtonShowPlayerInside/ButtonShowPlayerInside.pro \
    ButtonForMarkingON/ButtonForMarkingON.pro \
    ButtonAnyMode/ButtonAnyMode.pro \
    ShowSeqMessage/ShowSeqMessage.pro \
    ButtonStartCaptureContinuousLy/ButtonStartCaptureContinuousLy.pro \
    ButtonRewindInspection/ButtonRewindInspection.pro \
    SetMechanicalOffset/SetMechanicalOffset.pro \
    SetSpetialValue/SetSpetialValue.pro \
    ButtonPasswordEnabler/ButtonPasswordEnabler.pro \
    ButtonPasswordOpener/ButtonPasswordOpener.pro \
    FixedWindowSize/FixedWindowSize.pro \
    ListCachTargetImage/ListCachTargetImage.pro \
    LineEnhancerImagePanel/LineEnhancerImagePanel.pro \
    PropertyLineEnhancer/PropertyLineEnhancer.pro \
    GerberImagePanel/GerberImagePanel.pro \
    PropertyGerber/PropertyGerber.pro \
    DynamicClassifyImagePanel/DynamicClassifyImagePanel.pro \
    PropertyDynamicClassify/PropertyDynamicClassify.pro \
    ARArrangeImagePanel/ARArrangeImagePanel.pro \
    PropertyARArrange/PropertyARArrange.pro \
    LineEnhancer1LImagePanel/LineEnhancer1LImagePanel.pro \
    PropertyLineEnhancer1L/PropertyLineEnhancer1L.pro \
    ResultImportanceImagePanel/ResultImportanceImagePanel.pro \
    PropertyResultImportance/PropertyResultImportance.pro \
    VCutProperty/VCutProperty.pro \
    VCutImagePanel/VCutImagePanel.pro \
    MeasureHoleImagePanel/MeasureHoleImagePanel.pro \
    PropertyMeasureHole/PropertyMeasureHole.pro \
    MeasureLineMoveImagePanel/MeasureLineMoveImagePanel.pro \
    PropertyMeasureLineMove/PropertyMeasureLineMove.pro \
    MeasureShowGrid/MeasureShowGrid.pro \
    ButtonAutoGenerateMeasureLineMove/ButtonAutoGenerateMeasureLineMove.pro \
    MeasureHolePosImagePanel/MeasureHolePosImagePanel.pro \
    PropertyMeasureHolePos/PropertyMeasureHolePos.pro \
    ShowMeasureHolePosResultList/ShowMeasureHolePosResultList.pro \
    PCBCounterImagePanel/PCBCounterImagePanel.pro \
    PropertyPCBCounter/PropertyPCBCounter.pro \
    ShowPCBCount/ShowPCBCount.pro \
    TreeMasterImagePanel/TreeMasterImagePanel.pro \
    PropertyTreeMaster/PropertyTreeMaster.pro \
    TreeMasterShowResultList/TreeMasterShowResultList.pro \
    BuslineImagePanel/BuslineImagePanel.pro \
    PropertyBusline/PropertyBusline.pro \
    DotMatchingImagePanel/DotMatchingImagePanel.pro \
    PropertyDotMatching/PropertyDotMatching.pro \
    AlignmentLargeImagePanel/AlignmentLargeImagePanel.pro \
    PropertyAlignmentLarge/PropertyAlignmentLarge.pro \
    ButtonAlignmentLargeTransform/ButtonAlignmentLargeTransform.pro \
    ShowAlignmentResult/ShowAlignmentResult.pro \
    PropertyResultBinder/PropertyResultBinder.pro \
    ResultBinderImagePanel/ResultBinderImagePanel.pro \
    BCRImagePanel/BCRImagePanel.pro \
    PropertyBCR/PropertyBCR.pro \
    ShowBarCode/ShowBarCode.pro \
    ShowTopBottomSideInfo/ShowTopBottomSideInfo.pro \
    ButtonImageTransformer/ButtonImageTransformer.pro \
    ButtonFilterUpsideDown/ButtonFilterUpsideDown.pro \
    ButtonFilterUDColorShift/ButtonFilterUDColorShift.pro \
    ShowOldNGNaming/ShowOldNGNaming.pro \
    ShowSumTimer/ShowSumTimer.pro \
    ShowPieceResultList/ShowPieceResultList.pro \
    SetThresholdByHistogram/SetThresholdByHistogram.pro \
    ShowResultAlarm/ShowResultAlarm.pro \
    ShowItemNameResultSeq/ShowItemNameResultSeq.pro \
    WindUpImage/WindUpImage.pro \
    ShowTotalNGNaming/ShowTotalNGNaming.pro \
    ButtonLightON/ButtonLightON.pro \
    ShowCurrentLightName/ShowCurrentLightName.pro
