#ifndef BUTTONSYNCHRONIZEIMAGEPANEL_GLOBAL_H
#define BUTTONSYNCHRONIZEIMAGEPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONSYNCHRONIZEIMAGEPANEL_LIB
# define BUTTONSYNCHRONIZEIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define BUTTONSYNCHRONIZEIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONSYNCHRONIZEIMAGEPANEL_GLOBAL_H
