#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(RWEDITOBJECTIMAGEPANEL_LIB)
#  define RWEDITOBJECTIMAGEPANEL_EXPORT Q_DECL_EXPORT
# else
#  define RWEDITOBJECTIMAGEPANEL_EXPORT Q_DECL_IMPORT
# endif
#else
# define RWEDITOBJECTIMAGEPANEL_EXPORT
#endif
