#ifndef PROPERTYPIECEDEF_GLOBAL_H
#define PROPERTYPIECEDEF_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PROPERTYPIECEDEF_LIB
# define PROPERTYPIECEDEF_EXPORT Q_DECL_EXPORT
#else
# define PROPERTYPIECEDEF_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTYPIECEDEF_GLOBAL_H
