#ifndef BUTTONSHRINKIMAGE_GLOBAL_H
#define BUTTONSHRINKIMAGE_GLOBAL_H

#include <qglobal.h>

#ifdef BUTTONSHRINKIMAGE_LIB
# define BUTTONSHRINKIMAGE_EXPORT Q_DECL_EXPORT
#else
# define BUTTONSHRINKIMAGE_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONSHRINKIMAGE_GLOBAL_H
