#ifndef FILTERVBANDONELAYER_GLOBAL_H
#define FILTERVBANDONELAYER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef FILTERVBANDONELAYER_LIB
# define FILTERVBANDONELAYER_EXPORT Q_DECL_EXPORT
#else
# define FILTERVBANDONELAYER_EXPORT Q_DECL_IMPORT
#endif

#endif // FILTERVBANDONELAYER_GLOBAL_H
