# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = TransFileServer
DESTDIR = ../../
CONFIG += release
DEFINES += QT_LARGEFILE_SUPPORT
LIBS += -L"./../../Lib/Release" \
    -lServiceLib \
    -lComponent
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += .
RCC_DIR += .
include(TransFileServer.pri)
win32:RC_FILE = TransFileServer.rc
