#ifndef TRANSFILESERVER_GLOBAL_H
#define TRANSFILESERVER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef TRANSFILESERVER_LIB
# define TRANSFILESERVER_EXPORT Q_DECL_EXPORT
#else
# define TRANSFILESERVER_EXPORT Q_DECL_IMPORT
#endif

#endif // TRANSFILESERVER_GLOBAL_H
