#ifndef REVIEWSTRUCTURE_GLOBAL_H
#define REVIEWSTRUCTURE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef REVIEWSTRUCTURE_LIB
# define REVIEWSTRUCTURE_EXPORT Q_DECL_EXPORT
#else
# define REVIEWSTRUCTURE_EXPORT Q_DECL_IMPORT
#endif

#endif // REVIEWSTRUCTURE_GLOBAL_H
