/********************************************************************************
** Form generated from reading UI file 'EditLibraryDialog.ui'
**
** Created by: Qt User Interface Compiler version 6.10.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_EDITLIBRARYDIALOG_H
#define UI_EDITLIBRARYDIALOG_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QDialog>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QToolButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_EditLibraryDialog
{
public:
    QStackedWidget *stackedWidget;
    QWidget *page;
    QFrame *frame_3;
    QSpinBox *EditLineWidthInPattern;
    QLabel *label_9;
    QSpinBox *EditLineWidthOutside;
    QLabel *label_10;
    QLabel *label_13;
    QSpinBox *EditLimitLength;
    QLabel *label_32;
    QSpinBox *EditGlobalSize;
    QLabel *label_14;
    QLabel *label_15;
    QSpinBox *EditMinLineLength;
    QFrame *frame;
    QTableWidget *tableWidgetSubtractLibList;
    QPushButton *ButtonDelSubtractLib;
    QPushButton *ButtonAddSubtractLib;
    QLabel *label_31;
    QFrame *framePickLayer;
    QLabel *label;
    QFrame *frameGenLayer;
    QLabel *label_2;
    QFrame *frame_2;
    QLabel *label_38;
    QSpinBox *EditAngleNumb;
    QLabel *label_16;
    QWidget *page_3;
    QFrame *frame_6;
    QLabel *label_35;
    QLabel *label_20;
    QLabel *label_17;
    QSpinBox *EditNGSizeIH;
    QLabel *label_18;
    QSpinBox *EditBrightWidthIL;
    QSpinBox *EditNGSizeIL;
    QSpinBox *EditBrightWidthIH;
    QLabel *label_19;
    QFrame *frame_7;
    QLabel *label_37;
    QLabel *label_22;
    QSpinBox *EditNGSizeOH;
    QLabel *label_21;
    QSpinBox *EditNGSizeOL;
    QSpinBox *EditBrightWidthOL;
    QLabel *label_24;
    QLabel *label_23;
    QSpinBox *EditBrightWidthOH;
    QFrame *frame_9;
    QLabel *label_39;
    QCheckBox *checkBModeAbsoluteBright;
    QCheckBox *checkBModeCenterBrightFromParts;
    QCheckBox *checkBModeEnabled;
    QCheckBox *checkBModeDynamicMask;
    QLabel *label_30;
    QSpinBox *EditTransitDot;
    QFrame *frame_11;
    QLabel *label_41;
    QSpinBox *EditAdjustBrightIL;
    QSpinBox *EditAdjustBrightIH;
    QLabel *label_26;
    QLabel *label_25;
    QSpinBox *EditAdjustBrightOH;
    QLabel *label_29;
    QSpinBox *EditAdjustBrightOL;
    QLabel *label_34;
    QFrame *frame_13;
    QLabel *label_43;
    QFrame *frame_14;
    QLabel *label_44;
    QSpinBox *EditSearchDot;
    QLabel *label_27;
    QLabel *label_28;
    QSpinBox *EditGlobalSearchDot;
    QFrame *frame_12;
    QLabel *label_42;
    QCheckBox *checkBModeUseRegularBrightness;
    QLabel *label_33;
    QSpinBox *EditRegulatedColI;
    QSpinBox *EditRegulatedColO;
    QLabel *label_36;
    QWidget *page_2;
    QFrame *frame_8;
    QToolButton *toolButtonInspect;
    QToolButton *toolButtonPickup;
    QLineEdit *EditLibID;
    QPushButton *ButtonLibDelete;
    QPushButton *ButtonLibNew;
    QLineEdit *EditLibName;
    QPushButton *ButtonLibSave;
    QPushButton *pushButton;
    QTableWidget *tableWidgetLibList;
    QFrame *frameLibFolder;
    QLabel *label_4;
    QPushButton *ButtonLibSaveNew;

    void setupUi(QDialog *EditLibraryDialog)
    {
        if (EditLibraryDialog->objectName().isEmpty())
            EditLibraryDialog->setObjectName("EditLibraryDialog");
        EditLibraryDialog->resize(651, 773);
        stackedWidget = new QStackedWidget(EditLibraryDialog);
        stackedWidget->setObjectName("stackedWidget");
        stackedWidget->setGeometry(QRect(240, 100, 401, 531));
        page = new QWidget();
        page->setObjectName("page");
        frame_3 = new QFrame(page);
        frame_3->setObjectName("frame_3");
        frame_3->setGeometry(QRect(0, 230, 393, 161));
        frame_3->setFrameShape(QFrame::StyledPanel);
        frame_3->setFrameShadow(QFrame::Sunken);
        EditLineWidthInPattern = new QSpinBox(frame_3);
        EditLineWidthInPattern->setObjectName("EditLineWidthInPattern");
        EditLineWidthInPattern->setGeometry(QRect(290, 10, 81, 22));
        EditLineWidthInPattern->setMaximum(1000000);
        label_9 = new QLabel(frame_3);
        label_9->setObjectName("label_9");
        label_9->setGeometry(QRect(42, 30, 241, 21));
        label_9->setFrameShape(QFrame::Panel);
        label_9->setFrameShadow(QFrame::Sunken);
        label_9->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditLineWidthOutside = new QSpinBox(frame_3);
        EditLineWidthOutside->setObjectName("EditLineWidthOutside");
        EditLineWidthOutside->setGeometry(QRect(290, 30, 81, 22));
        EditLineWidthOutside->setMaximum(1000000);
        label_10 = new QLabel(frame_3);
        label_10->setObjectName("label_10");
        label_10->setGeometry(QRect(42, 10, 241, 21));
        label_10->setFrameShape(QFrame::Panel);
        label_10->setFrameShadow(QFrame::Sunken);
        label_10->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_13 = new QLabel(frame_3);
        label_13->setObjectName("label_13");
        label_13->setGeometry(QRect(40, 100, 241, 21));
        label_13->setFrameShape(QFrame::Panel);
        label_13->setFrameShadow(QFrame::Sunken);
        label_13->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditLimitLength = new QSpinBox(frame_3);
        EditLimitLength->setObjectName("EditLimitLength");
        EditLimitLength->setGeometry(QRect(288, 100, 81, 22));
        EditLimitLength->setMaximum(99999);
        label_32 = new QLabel(frame_3);
        label_32->setObjectName("label_32");
        label_32->setGeometry(QRect(0, 0, 31, 161));
        label_32->setFrameShape(QFrame::Panel);
        label_32->setFrameShadow(QFrame::Raised);
        label_32->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_32->setIndent(1);
        EditGlobalSize = new QSpinBox(frame_3);
        EditGlobalSize->setObjectName("EditGlobalSize");
        EditGlobalSize->setGeometry(QRect(288, 130, 81, 22));
        EditGlobalSize->setMaximum(99999999);
        label_14 = new QLabel(frame_3);
        label_14->setObjectName("label_14");
        label_14->setGeometry(QRect(40, 130, 241, 21));
        label_14->setFrameShape(QFrame::Panel);
        label_14->setFrameShadow(QFrame::Sunken);
        label_14->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_15 = new QLabel(frame_3);
        label_15->setObjectName("label_15");
        label_15->setGeometry(QRect(42, 70, 241, 21));
        label_15->setFrameShape(QFrame::Panel);
        label_15->setFrameShadow(QFrame::Sunken);
        label_15->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditMinLineLength = new QSpinBox(frame_3);
        EditMinLineLength->setObjectName("EditMinLineLength");
        EditMinLineLength->setGeometry(QRect(290, 70, 81, 22));
        EditMinLineLength->setMaximum(99999);
        frame = new QFrame(page);
        frame->setObjectName("frame");
        frame->setGeometry(QRect(0, 100, 393, 121));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Sunken);
        tableWidgetSubtractLibList = new QTableWidget(frame);
        if (tableWidgetSubtractLibList->columnCount() < 2)
            tableWidgetSubtractLibList->setColumnCount(2);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        tableWidgetSubtractLibList->setHorizontalHeaderItem(0, __qtablewidgetitem);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        tableWidgetSubtractLibList->setHorizontalHeaderItem(1, __qtablewidgetitem1);
        tableWidgetSubtractLibList->setObjectName("tableWidgetSubtractLibList");
        tableWidgetSubtractLibList->setGeometry(QRect(40, 10, 241, 101));
        tableWidgetSubtractLibList->setSelectionMode(QAbstractItemView::SingleSelection);
        tableWidgetSubtractLibList->setSelectionBehavior(QAbstractItemView::SelectRows);
        ButtonDelSubtractLib = new QPushButton(frame);
        ButtonDelSubtractLib->setObjectName("ButtonDelSubtractLib");
        ButtonDelSubtractLib->setGeometry(QRect(290, 60, 101, 31));
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/Qtres/Delete.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        ButtonDelSubtractLib->setIcon(icon);
        ButtonAddSubtractLib = new QPushButton(frame);
        ButtonAddSubtractLib->setObjectName("ButtonAddSubtractLib");
        ButtonAddSubtractLib->setGeometry(QRect(290, 20, 101, 31));
        QIcon icon1;
        icon1.addFile(QString::fromUtf8(":/Qtres/Add.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        ButtonAddSubtractLib->setIcon(icon1);
        label_31 = new QLabel(frame);
        label_31->setObjectName("label_31");
        label_31->setGeometry(QRect(0, 0, 31, 121));
        label_31->setFrameShape(QFrame::Panel);
        label_31->setFrameShadow(QFrame::Raised);
        label_31->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_31->setIndent(1);
        framePickLayer = new QFrame(page);
        framePickLayer->setObjectName("framePickLayer");
        framePickLayer->setGeometry(QRect(0, 20, 393, 28));
        framePickLayer->setFrameShape(QFrame::NoFrame);
        framePickLayer->setFrameShadow(QFrame::Plain);
        label = new QLabel(page);
        label->setObjectName("label");
        label->setGeometry(QRect(0, 0, 393, 21));
        label->setFrameShape(QFrame::Panel);
        label->setFrameShadow(QFrame::Sunken);
        label->setTextFormat(Qt::AutoText);
        label->setAlignment(Qt::AlignCenter);
        frameGenLayer = new QFrame(page);
        frameGenLayer->setObjectName("frameGenLayer");
        frameGenLayer->setGeometry(QRect(0, 70, 393, 28));
        frameGenLayer->setFrameShape(QFrame::NoFrame);
        frameGenLayer->setFrameShadow(QFrame::Plain);
        label_2 = new QLabel(page);
        label_2->setObjectName("label_2");
        label_2->setGeometry(QRect(0, 50, 393, 21));
        label_2->setFrameShape(QFrame::Panel);
        label_2->setFrameShadow(QFrame::Sunken);
        label_2->setTextFormat(Qt::AutoText);
        label_2->setAlignment(Qt::AlignCenter);
        frame_2 = new QFrame(page);
        frame_2->setObjectName("frame_2");
        frame_2->setGeometry(QRect(0, 400, 393, 61));
        frame_2->setFrameShape(QFrame::StyledPanel);
        frame_2->setFrameShadow(QFrame::Sunken);
        label_38 = new QLabel(frame_2);
        label_38->setObjectName("label_38");
        label_38->setGeometry(QRect(0, 0, 31, 61));
        label_38->setFrameShape(QFrame::Panel);
        label_38->setFrameShadow(QFrame::Raised);
        label_38->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_38->setIndent(1);
        EditAngleNumb = new QSpinBox(frame_2);
        EditAngleNumb->setObjectName("EditAngleNumb");
        EditAngleNumb->setGeometry(QRect(288, 20, 81, 22));
        EditAngleNumb->setMaximum(99999999);
        label_16 = new QLabel(frame_2);
        label_16->setObjectName("label_16");
        label_16->setGeometry(QRect(40, 20, 241, 21));
        label_16->setFrameShape(QFrame::Panel);
        label_16->setFrameShadow(QFrame::Sunken);
        label_16->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        stackedWidget->addWidget(page);
        page_3 = new QWidget();
        page_3->setObjectName("page_3");
        frame_6 = new QFrame(page_3);
        frame_6->setObjectName("frame_6");
        frame_6->setGeometry(QRect(0, 4, 396, 81));
        frame_6->setFrameShape(QFrame::StyledPanel);
        frame_6->setFrameShadow(QFrame::Sunken);
        label_35 = new QLabel(frame_6);
        label_35->setObjectName("label_35");
        label_35->setGeometry(QRect(0, 0, 31, 81));
        label_35->setFrameShape(QFrame::Panel);
        label_35->setFrameShadow(QFrame::Raised);
        label_35->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_35->setIndent(1);
        label_20 = new QLabel(frame_6);
        label_20->setObjectName("label_20");
        label_20->setGeometry(QRect(306, 8, 72, 21));
        label_20->setFrameShape(QFrame::Panel);
        label_20->setFrameShadow(QFrame::Sunken);
        label_20->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_17 = new QLabel(frame_6);
        label_17->setObjectName("label_17");
        label_17->setGeometry(QRect(36, 28, 176, 21));
        label_17->setFrameShape(QFrame::Panel);
        label_17->setFrameShadow(QFrame::Sunken);
        label_17->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditNGSizeIH = new QSpinBox(frame_6);
        EditNGSizeIH->setObjectName("EditNGSizeIH");
        EditNGSizeIH->setGeometry(QRect(306, 48, 72, 22));
        EditNGSizeIH->setMaximum(99999999);
        label_18 = new QLabel(frame_6);
        label_18->setObjectName("label_18");
        label_18->setGeometry(QRect(36, 48, 176, 21));
        label_18->setFrameShape(QFrame::Panel);
        label_18->setFrameShadow(QFrame::Sunken);
        label_18->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditBrightWidthIL = new QSpinBox(frame_6);
        EditBrightWidthIL->setObjectName("EditBrightWidthIL");
        EditBrightWidthIL->setGeometry(QRect(218, 28, 81, 22));
        EditBrightWidthIL->setMaximum(255);
        EditNGSizeIL = new QSpinBox(frame_6);
        EditNGSizeIL->setObjectName("EditNGSizeIL");
        EditNGSizeIL->setGeometry(QRect(218, 48, 81, 22));
        EditNGSizeIL->setMaximum(99999999);
        EditBrightWidthIH = new QSpinBox(frame_6);
        EditBrightWidthIH->setObjectName("EditBrightWidthIH");
        EditBrightWidthIH->setGeometry(QRect(306, 28, 72, 22));
        EditBrightWidthIH->setMaximum(255);
        label_19 = new QLabel(frame_6);
        label_19->setObjectName("label_19");
        label_19->setGeometry(QRect(218, 8, 81, 21));
        label_19->setFrameShape(QFrame::Panel);
        label_19->setFrameShadow(QFrame::Sunken);
        label_19->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        frame_7 = new QFrame(page_3);
        frame_7->setObjectName("frame_7");
        frame_7->setGeometry(QRect(0, 90, 396, 81));
        frame_7->setFrameShape(QFrame::StyledPanel);
        frame_7->setFrameShadow(QFrame::Sunken);
        label_37 = new QLabel(frame_7);
        label_37->setObjectName("label_37");
        label_37->setGeometry(QRect(0, 0, 31, 81));
        label_37->setFrameShape(QFrame::Panel);
        label_37->setFrameShadow(QFrame::Raised);
        label_37->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_37->setIndent(1);
        label_22 = new QLabel(frame_7);
        label_22->setObjectName("label_22");
        label_22->setGeometry(QRect(36, 30, 176, 21));
        label_22->setFrameShape(QFrame::Panel);
        label_22->setFrameShadow(QFrame::Sunken);
        label_22->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditNGSizeOH = new QSpinBox(frame_7);
        EditNGSizeOH->setObjectName("EditNGSizeOH");
        EditNGSizeOH->setGeometry(QRect(306, 50, 72, 22));
        EditNGSizeOH->setMaximum(99999999);
        label_21 = new QLabel(frame_7);
        label_21->setObjectName("label_21");
        label_21->setGeometry(QRect(306, 10, 72, 21));
        label_21->setFrameShape(QFrame::Panel);
        label_21->setFrameShadow(QFrame::Sunken);
        label_21->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditNGSizeOL = new QSpinBox(frame_7);
        EditNGSizeOL->setObjectName("EditNGSizeOL");
        EditNGSizeOL->setGeometry(QRect(218, 50, 81, 22));
        EditNGSizeOL->setMaximum(99999999);
        EditBrightWidthOL = new QSpinBox(frame_7);
        EditBrightWidthOL->setObjectName("EditBrightWidthOL");
        EditBrightWidthOL->setGeometry(QRect(218, 30, 81, 22));
        EditBrightWidthOL->setMaximum(255);
        label_24 = new QLabel(frame_7);
        label_24->setObjectName("label_24");
        label_24->setGeometry(QRect(36, 50, 176, 21));
        label_24->setFrameShape(QFrame::Panel);
        label_24->setFrameShadow(QFrame::Sunken);
        label_24->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_23 = new QLabel(frame_7);
        label_23->setObjectName("label_23");
        label_23->setGeometry(QRect(218, 10, 81, 21));
        label_23->setFrameShape(QFrame::Panel);
        label_23->setFrameShadow(QFrame::Sunken);
        label_23->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditBrightWidthOH = new QSpinBox(frame_7);
        EditBrightWidthOH->setObjectName("EditBrightWidthOH");
        EditBrightWidthOH->setGeometry(QRect(306, 30, 72, 22));
        EditBrightWidthOH->setMaximum(255);
        frame_9 = new QFrame(page_3);
        frame_9->setObjectName("frame_9");
        frame_9->setGeometry(QRect(0, 180, 396, 91));
        frame_9->setFrameShape(QFrame::StyledPanel);
        frame_9->setFrameShadow(QFrame::Sunken);
        label_39 = new QLabel(frame_9);
        label_39->setObjectName("label_39");
        label_39->setGeometry(QRect(0, 0, 31, 91));
        label_39->setFrameShape(QFrame::Panel);
        label_39->setFrameShadow(QFrame::Raised);
        label_39->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_39->setIndent(1);
        checkBModeAbsoluteBright = new QCheckBox(frame_9);
        checkBModeAbsoluteBright->setObjectName("checkBModeAbsoluteBright");
        checkBModeAbsoluteBright->setGeometry(QRect(40, 30, 161, 18));
        checkBModeCenterBrightFromParts = new QCheckBox(frame_9);
        checkBModeCenterBrightFromParts->setObjectName("checkBModeCenterBrightFromParts");
        checkBModeCenterBrightFromParts->setGeometry(QRect(190, 10, 191, 18));
        checkBModeEnabled = new QCheckBox(frame_9);
        checkBModeEnabled->setObjectName("checkBModeEnabled");
        checkBModeEnabled->setGeometry(QRect(40, 10, 161, 18));
        checkBModeDynamicMask = new QCheckBox(frame_9);
        checkBModeDynamicMask->setObjectName("checkBModeDynamicMask");
        checkBModeDynamicMask->setGeometry(QRect(190, 30, 191, 18));
        label_30 = new QLabel(frame_9);
        label_30->setObjectName("label_30");
        label_30->setGeometry(QRect(40, 60, 266, 21));
        label_30->setFrameShape(QFrame::Panel);
        label_30->setFrameShadow(QFrame::Sunken);
        label_30->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditTransitDot = new QSpinBox(frame_9);
        EditTransitDot->setObjectName("EditTransitDot");
        EditTransitDot->setGeometry(QRect(310, 60, 81, 22));
        EditTransitDot->setMaximum(1000);
        frame_11 = new QFrame(page_3);
        frame_11->setObjectName("frame_11");
        frame_11->setGeometry(QRect(0, 280, 396, 111));
        frame_11->setFrameShape(QFrame::StyledPanel);
        frame_11->setFrameShadow(QFrame::Sunken);
        label_41 = new QLabel(frame_11);
        label_41->setObjectName("label_41");
        label_41->setGeometry(QRect(0, 0, 31, 111));
        label_41->setFrameShape(QFrame::Panel);
        label_41->setFrameShadow(QFrame::Raised);
        label_41->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_41->setIndent(1);
        EditAdjustBrightIL = new QSpinBox(frame_11);
        EditAdjustBrightIL->setObjectName("EditAdjustBrightIL");
        EditAdjustBrightIL->setGeometry(QRect(310, 10, 81, 22));
        EditAdjustBrightIL->setMaximum(255);
        EditAdjustBrightIH = new QSpinBox(frame_11);
        EditAdjustBrightIH->setObjectName("EditAdjustBrightIH");
        EditAdjustBrightIH->setGeometry(QRect(310, 30, 81, 22));
        EditAdjustBrightIH->setMaximum(255);
        label_26 = new QLabel(frame_11);
        label_26->setObjectName("label_26");
        label_26->setGeometry(QRect(40, 30, 266, 21));
        label_26->setFrameShape(QFrame::Panel);
        label_26->setFrameShadow(QFrame::Sunken);
        label_26->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_25 = new QLabel(frame_11);
        label_25->setObjectName("label_25");
        label_25->setGeometry(QRect(40, 10, 266, 21));
        label_25->setFrameShape(QFrame::Panel);
        label_25->setFrameShadow(QFrame::Sunken);
        label_25->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditAdjustBrightOH = new QSpinBox(frame_11);
        EditAdjustBrightOH->setObjectName("EditAdjustBrightOH");
        EditAdjustBrightOH->setGeometry(QRect(310, 80, 81, 22));
        EditAdjustBrightOH->setMaximum(255);
        label_29 = new QLabel(frame_11);
        label_29->setObjectName("label_29");
        label_29->setGeometry(QRect(40, 60, 266, 21));
        label_29->setFrameShape(QFrame::Panel);
        label_29->setFrameShadow(QFrame::Sunken);
        label_29->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditAdjustBrightOL = new QSpinBox(frame_11);
        EditAdjustBrightOL->setObjectName("EditAdjustBrightOL");
        EditAdjustBrightOL->setGeometry(QRect(310, 60, 81, 22));
        EditAdjustBrightOL->setMaximum(255);
        label_34 = new QLabel(frame_11);
        label_34->setObjectName("label_34");
        label_34->setGeometry(QRect(40, 80, 266, 21));
        label_34->setFrameShape(QFrame::Panel);
        label_34->setFrameShadow(QFrame::Sunken);
        label_34->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        frame_13 = new QFrame(page_3);
        frame_13->setObjectName("frame_13");
        frame_13->setGeometry(QRect(0, 470, 396, 61));
        frame_13->setFrameShape(QFrame::StyledPanel);
        frame_13->setFrameShadow(QFrame::Sunken);
        label_43 = new QLabel(frame_13);
        label_43->setObjectName("label_43");
        label_43->setGeometry(QRect(0, 0, 31, 61));
        label_43->setFrameShape(QFrame::Panel);
        label_43->setFrameShadow(QFrame::Raised);
        label_43->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_43->setIndent(1);
        frame_14 = new QFrame(frame_13);
        frame_14->setObjectName("frame_14");
        frame_14->setGeometry(QRect(10, 120, 371, 101));
        frame_14->setFrameShape(QFrame::StyledPanel);
        frame_14->setFrameShadow(QFrame::Sunken);
        label_44 = new QLabel(frame_14);
        label_44->setObjectName("label_44");
        label_44->setGeometry(QRect(0, 0, 20, 61));
        label_44->setFrameShape(QFrame::Panel);
        label_44->setFrameShadow(QFrame::Raised);
        label_44->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_44->setIndent(1);
        EditSearchDot = new QSpinBox(frame_13);
        EditSearchDot->setObjectName("EditSearchDot");
        EditSearchDot->setGeometry(QRect(310, 10, 81, 22));
        EditSearchDot->setMaximum(999999);
        label_27 = new QLabel(frame_13);
        label_27->setObjectName("label_27");
        label_27->setGeometry(QRect(40, 10, 266, 21));
        label_27->setFrameShape(QFrame::Panel);
        label_27->setFrameShadow(QFrame::Sunken);
        label_27->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_28 = new QLabel(frame_13);
        label_28->setObjectName("label_28");
        label_28->setGeometry(QRect(40, 30, 266, 21));
        label_28->setFrameShape(QFrame::Panel);
        label_28->setFrameShadow(QFrame::Sunken);
        label_28->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditGlobalSearchDot = new QSpinBox(frame_13);
        EditGlobalSearchDot->setObjectName("EditGlobalSearchDot");
        EditGlobalSearchDot->setGeometry(QRect(310, 30, 81, 22));
        EditGlobalSearchDot->setMaximum(999999);
        frame_12 = new QFrame(page_3);
        frame_12->setObjectName("frame_12");
        frame_12->setGeometry(QRect(0, 400, 391, 61));
        frame_12->setFrameShape(QFrame::StyledPanel);
        frame_12->setFrameShadow(QFrame::Sunken);
        label_42 = new QLabel(frame_12);
        label_42->setObjectName("label_42");
        label_42->setGeometry(QRect(0, 0, 31, 61));
        label_42->setFrameShape(QFrame::Panel);
        label_42->setFrameShadow(QFrame::Raised);
        label_42->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_42->setIndent(1);
        checkBModeUseRegularBrightness = new QCheckBox(frame_12);
        checkBModeUseRegularBrightness->setObjectName("checkBModeUseRegularBrightness");
        checkBModeUseRegularBrightness->setGeometry(QRect(40, 4, 341, 18));
        label_33 = new QLabel(frame_12);
        label_33->setObjectName("label_33");
        label_33->setGeometry(QRect(40, 30, 81, 21));
        label_33->setFrameShape(QFrame::Panel);
        label_33->setFrameShadow(QFrame::Sunken);
        label_33->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditRegulatedColI = new QSpinBox(frame_12);
        EditRegulatedColI->setObjectName("EditRegulatedColI");
        EditRegulatedColI->setGeometry(QRect(122, 30, 81, 22));
        EditRegulatedColI->setMaximum(255);
        EditRegulatedColO = new QSpinBox(frame_12);
        EditRegulatedColO->setObjectName("EditRegulatedColO");
        EditRegulatedColO->setGeometry(QRect(302, 30, 81, 22));
        EditRegulatedColO->setMaximum(255);
        label_36 = new QLabel(frame_12);
        label_36->setObjectName("label_36");
        label_36->setGeometry(QRect(220, 30, 81, 21));
        label_36->setFrameShape(QFrame::Panel);
        label_36->setFrameShadow(QFrame::Sunken);
        label_36->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        stackedWidget->addWidget(page_3);
        page_2 = new QWidget();
        page_2->setObjectName("page_2");
        stackedWidget->addWidget(page_2);
        frame_8 = new QFrame(EditLibraryDialog);
        frame_8->setObjectName("frame_8");
        frame_8->setGeometry(QRect(260, 10, 381, 51));
        frame_8->setFrameShape(QFrame::StyledPanel);
        frame_8->setFrameShadow(QFrame::Raised);
        toolButtonInspect = new QToolButton(frame_8);
        toolButtonInspect->setObjectName("toolButtonInspect");
        toolButtonInspect->setGeometry(QRect(230, 10, 141, 31));
        toolButtonInspect->setCheckable(true);
        toolButtonInspect->setAutoExclusive(true);
        toolButtonPickup = new QToolButton(frame_8);
        toolButtonPickup->setObjectName("toolButtonPickup");
        toolButtonPickup->setGeometry(QRect(10, 10, 141, 31));
        toolButtonPickup->setCheckable(true);
        toolButtonPickup->setChecked(true);
        toolButtonPickup->setAutoExclusive(true);
        EditLibID = new QLineEdit(EditLibraryDialog);
        EditLibID->setObjectName("EditLibID");
        EditLibID->setGeometry(QRect(300, 60, 81, 31));
        QFont font;
        font.setPointSize(12);
        EditLibID->setFont(font);
        EditLibID->setReadOnly(true);
        ButtonLibDelete = new QPushButton(EditLibraryDialog);
        ButtonLibDelete->setObjectName("ButtonLibDelete");
        ButtonLibDelete->setGeometry(QRect(240, 690, 131, 31));
        QFont font1;
        font1.setPointSize(11);
        ButtonLibDelete->setFont(font1);
        ButtonLibDelete->setIcon(icon);
        ButtonLibNew = new QPushButton(EditLibraryDialog);
        ButtonLibNew->setObjectName("ButtonLibNew");
        ButtonLibNew->setGeometry(QRect(240, 650, 131, 31));
        ButtonLibNew->setFont(font1);
        QIcon icon2;
        icon2.addFile(QString::fromUtf8(":/Qtres/ClearNew.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        ButtonLibNew->setIcon(icon2);
        EditLibName = new QLineEdit(EditLibraryDialog);
        EditLibName->setObjectName("EditLibName");
        EditLibName->setGeometry(QRect(380, 60, 261, 31));
        EditLibName->setFont(font);
        ButtonLibSave = new QPushButton(EditLibraryDialog);
        ButtonLibSave->setObjectName("ButtonLibSave");
        ButtonLibSave->setGeometry(QRect(520, 690, 121, 31));
        ButtonLibSave->setFont(font1);
        QIcon icon3;
        icon3.addFile(QString::fromUtf8(":/Qtres/Update.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        ButtonLibSave->setIcon(icon3);
        pushButton = new QPushButton(EditLibraryDialog);
        pushButton->setObjectName("pushButton");
        pushButton->setGeometry(QRect(520, 730, 121, 31));
        pushButton->setFont(font1);
        QIcon icon4;
        icon4.addFile(QString::fromUtf8(":/Qtres/Close.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        pushButton->setIcon(icon4);
        tableWidgetLibList = new QTableWidget(EditLibraryDialog);
        if (tableWidgetLibList->columnCount() < 2)
            tableWidgetLibList->setColumnCount(2);
        QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
        tableWidgetLibList->setHorizontalHeaderItem(0, __qtablewidgetitem2);
        QTableWidgetItem *__qtablewidgetitem3 = new QTableWidgetItem();
        tableWidgetLibList->setHorizontalHeaderItem(1, __qtablewidgetitem3);
        tableWidgetLibList->setObjectName("tableWidgetLibList");
        tableWidgetLibList->setGeometry(QRect(10, 280, 221, 281));
        tableWidgetLibList->setSelectionMode(QAbstractItemView::SingleSelection);
        tableWidgetLibList->setSelectionBehavior(QAbstractItemView::SelectRows);
        frameLibFolder = new QFrame(EditLibraryDialog);
        frameLibFolder->setObjectName("frameLibFolder");
        frameLibFolder->setGeometry(QRect(10, 10, 221, 251));
        frameLibFolder->setFrameShape(QFrame::StyledPanel);
        frameLibFolder->setFrameShadow(QFrame::Sunken);
        label_4 = new QLabel(EditLibraryDialog);
        label_4->setObjectName("label_4");
        label_4->setGeometry(QRect(250, 60, 51, 31));
        label_4->setFont(font);
        label_4->setFrameShape(QFrame::Panel);
        label_4->setFrameShadow(QFrame::Sunken);
        label_4->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        ButtonLibSaveNew = new QPushButton(EditLibraryDialog);
        ButtonLibSaveNew->setObjectName("ButtonLibSaveNew");
        ButtonLibSaveNew->setGeometry(QRect(380, 690, 131, 31));
        ButtonLibSaveNew->setFont(font1);
        ButtonLibSaveNew->setIcon(icon2);

        retranslateUi(EditLibraryDialog);

        stackedWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(EditLibraryDialog);
    } // setupUi

    void retranslateUi(QDialog *EditLibraryDialog)
    {
        EditLibraryDialog->setWindowTitle(QCoreApplication::translate("EditLibraryDialog", "Dialog", nullptr));
        label_9->setText(QCoreApplication::translate("EditLibraryDialog", "\345\244\226\345\201\264\345\271\205", nullptr));
        label_10->setText(QCoreApplication::translate("EditLibraryDialog", "\345\206\205\345\201\264\345\271\205", nullptr));
        label_13->setText(QCoreApplication::translate("EditLibraryDialog", "\351\231\220\347\225\214\351\225\267\343\201\225", nullptr));
        label_32->setText(QCoreApplication::translate("EditLibraryDialog", "\343\202\265\n"
"\343\202\244\n"
"\343\202\272", nullptr));
        label_14->setText(QCoreApplication::translate("EditLibraryDialog", "\345\244\247\345\237\237\346\216\242\347\264\242\343\201\256\345\241\212\343\202\265\343\202\244\343\202\272", nullptr));
        label_15->setText(QCoreApplication::translate("EditLibraryDialog", "\346\234\200\345\260\217\351\225\267\343\201\225", nullptr));
        QTableWidgetItem *___qtablewidgetitem = tableWidgetSubtractLibList->horizontalHeaderItem(0);
        ___qtablewidgetitem->setText(QCoreApplication::translate("EditLibraryDialog", "ID", nullptr));
        QTableWidgetItem *___qtablewidgetitem1 = tableWidgetSubtractLibList->horizontalHeaderItem(1);
        ___qtablewidgetitem1->setText(QCoreApplication::translate("EditLibraryDialog", "Name", nullptr));
        ButtonDelSubtractLib->setText(QCoreApplication::translate("EditLibraryDialog", "\345\211\212\351\231\244", nullptr));
        ButtonAddSubtractLib->setText(QCoreApplication::translate("EditLibraryDialog", "\350\277\275\345\212\240", nullptr));
        label_31->setText(QCoreApplication::translate("EditLibraryDialog", "\351\231\244\n"
"\345\216\273", nullptr));
        label->setText(QCoreApplication::translate("EditLibraryDialog", "\346\212\275\345\207\272\351\201\251\347\224\250\343\203\254\343\202\244\343\203\244\343\203\274", nullptr));
        label_2->setText(QCoreApplication::translate("EditLibraryDialog", "\347\224\237\346\210\220\351\201\251\347\224\250\343\203\254\343\202\244\343\203\244\343\203\274", nullptr));
        label_38->setText(QCoreApplication::translate("EditLibraryDialog", "<html><head/><body><p>\350\247\222</p><p>\345\272\246</p></body></html>", nullptr));
        label_16->setText(QCoreApplication::translate("EditLibraryDialog", "\350\247\222\345\272\246\346\225\260", nullptr));
        label_35->setText(QCoreApplication::translate("EditLibraryDialog", "<html><head/><body><p>\345\206\205</p><p>\345\201\264</p></body></html>", nullptr));
        label_20->setText(QCoreApplication::translate("EditLibraryDialog", "\346\230\216\345\201\264", nullptr));
        label_17->setText(QCoreApplication::translate("EditLibraryDialog", "OK\350\274\235\345\272\246\347\257\204\345\233\262", nullptr));
        label_18->setText(QCoreApplication::translate("EditLibraryDialog", "OK\343\203\211\343\203\203\343\203\210\346\225\260", nullptr));
        label_19->setText(QCoreApplication::translate("EditLibraryDialog", "\346\232\227\345\201\264", nullptr));
        label_37->setText(QCoreApplication::translate("EditLibraryDialog", "<html><head/><body><p>\345\244\226</p><p>\345\201\264</p></body></html>", nullptr));
        label_22->setText(QCoreApplication::translate("EditLibraryDialog", "OK\350\274\235\345\272\246\347\257\204\345\233\262", nullptr));
        label_21->setText(QCoreApplication::translate("EditLibraryDialog", "\346\230\216\345\201\264", nullptr));
        label_24->setText(QCoreApplication::translate("EditLibraryDialog", "OK\343\203\211\343\203\203\343\203\210\346\225\260", nullptr));
        label_23->setText(QCoreApplication::translate("EditLibraryDialog", "\346\232\227\345\201\264", nullptr));
        label_39->setText(QCoreApplication::translate("EditLibraryDialog", "\345\261\236\n"
"\346\200\247", nullptr));
        checkBModeAbsoluteBright->setText(QCoreApplication::translate("EditLibraryDialog", "\347\265\266\345\257\276\350\274\235\345\272\246", nullptr));
        checkBModeCenterBrightFromParts->setText(QCoreApplication::translate("EditLibraryDialog", "\351\203\250\345\223\201\343\201\213\343\202\211\350\274\235\345\272\246\343\202\222\346\212\275\345\207\272\343\201\231\343\202\213", nullptr));
        checkBModeEnabled->setText(QCoreApplication::translate("EditLibraryDialog", "\346\244\234\346\237\273\346\234\211\345\212\271", nullptr));
        checkBModeDynamicMask->setText(QCoreApplication::translate("EditLibraryDialog", "\345\256\237\350\241\214\343\203\236\343\202\271\343\202\257", nullptr));
        label_30->setText(QCoreApplication::translate("EditLibraryDialog", "\350\274\252\351\203\255\351\203\250\345\210\206\343\201\256\347\247\273\350\241\214\345\271\205", nullptr));
        label_41->setText(QCoreApplication::translate("EditLibraryDialog", "\350\243\234\n"
"\346\255\243", nullptr));
        label_26->setText(QCoreApplication::translate("EditLibraryDialog", "\345\206\205\345\201\264\343\200\200\346\230\216\345\201\264\343\200\200\346\234\200\345\244\247\350\243\234\346\255\243\350\274\235\345\272\246\351\207\217", nullptr));
        label_25->setText(QCoreApplication::translate("EditLibraryDialog", "\345\206\205\345\201\264\343\200\200\346\232\227\345\201\264\343\200\200\346\234\200\345\244\247\350\243\234\346\255\243\350\274\235\345\272\246\351\207\217", nullptr));
        label_29->setText(QCoreApplication::translate("EditLibraryDialog", "\345\244\226\345\201\264\343\200\200\346\232\227\345\201\264\343\200\200\346\234\200\345\244\247\350\243\234\346\255\243\350\274\235\345\272\246\351\207\217", nullptr));
        label_34->setText(QCoreApplication::translate("EditLibraryDialog", "\345\244\226\345\201\264\343\200\200\346\230\216\345\201\264\343\200\200\346\234\200\345\244\247\350\243\234\346\255\243\350\274\235\345\272\246\351\207\217", nullptr));
        label_43->setText(QCoreApplication::translate("EditLibraryDialog", "\346\216\242\n"
"\347\264\242", nullptr));
        label_44->setText(QCoreApplication::translate("EditLibraryDialog", "\350\274\235\n"
"\345\272\246", nullptr));
        label_27->setText(QCoreApplication::translate("EditLibraryDialog", "\345\215\230\344\275\223\343\201\247\343\201\256\346\216\242\347\264\242\343\203\211\343\203\203\343\203\210\346\225\260", nullptr));
        label_28->setText(QCoreApplication::translate("EditLibraryDialog", "\345\205\250\344\275\223\343\201\247\343\201\256\346\216\242\347\264\242\343\203\211\343\203\203\343\203\210\346\225\260", nullptr));
        label_42->setText(QCoreApplication::translate("EditLibraryDialog", "\350\274\235\n"
"\345\272\246", nullptr));
        checkBModeUseRegularBrightness->setText(QCoreApplication::translate("EditLibraryDialog", "\345\237\272\346\272\226\350\274\235\345\272\246\343\202\222\344\275\277\343\201\206", nullptr));
        label_33->setText(QCoreApplication::translate("EditLibraryDialog", "\345\206\205\345\201\264", nullptr));
        label_36->setText(QCoreApplication::translate("EditLibraryDialog", "\345\244\226\345\201\264", nullptr));
        toolButtonInspect->setText(QCoreApplication::translate("EditLibraryDialog", "\346\244\234\346\237\273", nullptr));
        toolButtonPickup->setText(QCoreApplication::translate("EditLibraryDialog", "\347\224\237\346\210\220", nullptr));
        EditLibID->setText(QCoreApplication::translate("EditLibraryDialog", "12345", nullptr));
        ButtonLibDelete->setText(QCoreApplication::translate("EditLibraryDialog", "Delete", nullptr));
        ButtonLibNew->setText(QCoreApplication::translate("EditLibraryDialog", "Clear new", nullptr));
        EditLibName->setText(QCoreApplication::translate("EditLibraryDialog", "Library Name", nullptr));
        ButtonLibSave->setText(QCoreApplication::translate("EditLibraryDialog", "Update", nullptr));
        pushButton->setText(QCoreApplication::translate("EditLibraryDialog", "\351\226\211\343\201\230\343\202\213", nullptr));
        QTableWidgetItem *___qtablewidgetitem2 = tableWidgetLibList->horizontalHeaderItem(0);
        ___qtablewidgetitem2->setText(QCoreApplication::translate("EditLibraryDialog", "ID", nullptr));
        QTableWidgetItem *___qtablewidgetitem3 = tableWidgetLibList->horizontalHeaderItem(1);
        ___qtablewidgetitem3->setText(QCoreApplication::translate("EditLibraryDialog", "Name", nullptr));
        label_4->setText(QCoreApplication::translate("EditLibraryDialog", "\345\220\215\347\247\260", nullptr));
        ButtonLibSaveNew->setText(QCoreApplication::translate("EditLibraryDialog", "Save New", nullptr));
    } // retranslateUi

};

namespace Ui {
    class EditLibraryDialog: public Ui_EditLibraryDialog {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_EDITLIBRARYDIALOG_H
