/********************************************************************************
** Form generated from reading UI file 'PropertyLinePatternForm.ui'
**
** Created by: Qt User Interface Compiler version 6.10.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_PROPERTYLINEPATTERNFORM_H
#define UI_PROPERTYLINEPATTERNFORM_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QToolButton>
#include <QtWidgets/QWidget>
#include "guiformbase.h"

QT_BEGIN_NAMESPACE

class Ui_PropertyLinePatternForm
{
public:
    QWidget *widget;
    QToolButton *toolButtonCreateBlock;
    QToolButton *toolButtonLibrary;
    QStackedWidget *stackedWidget;
    QWidget *page;
    QPushButton *pushButtonEditLibFolder;
    QLabel *labelLibFolderName;
    QTableWidget *tableWidgetLibList;
    QTableWidget *tableWidgetGeneratedLibList;
    QPushButton *pushButtonSetFrom;
    QPushButton *pushButtonGetBack;
    QPushButton *pushButtonEditLibrary;
    QPushButton *ButtonGenerateLibs;
    QFrame *frame_4;
    QLineEdit *EditLibName;
    QLabel *label_3;
    QLineEdit *EditLibID;
    QLabel *label_4;
    QPushButton *ButtonLibSave;
    QFrame *frame_3;
    QSpinBox *EditLineWidthInPattern;
    QLabel *label_9;
    QSpinBox *EditLineWidthOutside;
    QLabel *label_10;
    QLabel *label_13;
    QSpinBox *EditLimitLength;
    QLabel *label_53;
    QLabel *label_30;
    QLabel *label_31;
    QPushButton *pushButtonGetBackAll;
    QPushButton *pushButtonSetFromAll;
    QWidget *page_2;
    QTableWidget *tableWidgetBlockInfo;
    QLabel *label_32;
    QFrame *frameBlockInfoOnMouse;
    QLabel *label_33;
    QFrame *frame;
    QLineEdit *EditLibNameInBlock;
    QLineEdit *EditLibIDnBlock;
    QLabel *label_34;
    QFrame *frame_9;
    QLabel *label_39;
    QCheckBox *checkBModeAbsoluteBright;
    QCheckBox *checkBModeCenterBrightFromParts;
    QCheckBox *checkBModeEnabled;
    QCheckBox *checkBModeDynamicMask;
    QLabel *label_35;
    QSpinBox *EditTransitDot;
    QFrame *frame_6;
    QLabel *label_36;
    QLabel *label_20;
    QLabel *label_17;
    QSpinBox *EditNGSizeIH;
    QLabel *label_18;
    QSpinBox *EditBrightWidthIL;
    QSpinBox *EditNGSizeIL;
    QSpinBox *EditBrightWidthIH;
    QLabel *label_19;
    QFrame *frame_7;
    QLabel *label_37;
    QLabel *label_22;
    QSpinBox *EditNGSizeOH;
    QSpinBox *EditNGSizeOL;
    QSpinBox *EditBrightWidthOL;
    QLabel *label_24;
    QSpinBox *EditBrightWidthOH;
    QFrame *frame_13;
    QLabel *label_43;
    QFrame *frame_14;
    QLabel *label_44;
    QSpinBox *EditSearchDot;
    QLabel *label_27;
    QLabel *label_28;
    QSpinBox *EditGlobalSearchDot;
    QFrame *frame_11;
    QLabel *label_41;
    QFrame *frame_12;
    QLabel *label_42;
    QSpinBox *EditAdjustBrightIL;
    QSpinBox *EditAdjustBrightIH;
    QLabel *label_26;
    QLabel *label_25;
    QSpinBox *EditAdjustBrightOH;
    QLabel *label_29;
    QSpinBox *EditAdjustBrightOL;
    QLabel *label_38;
    QFrame *frame_15;
    QLabel *label_45;
    QCheckBox *checkBModeUseRegularBrightness;
    QLabel *label_40;
    QSpinBox *EditRegulatedColI;
    QSpinBox *EditRegulatedColO;
    QLabel *label_46;
    QFrame *frame_2;
    QToolButton *toolButtonArea;
    QToolButton *toolButtonInside;
    QToolButton *toolButtonOutside;
    QComboBox *comboBoxResultAngleNumber;

    void setupUi(GUIFormBase *PropertyLinePatternForm)
    {
        if (PropertyLinePatternForm->objectName().isEmpty())
            PropertyLinePatternForm->setObjectName("PropertyLinePatternForm");
        PropertyLinePatternForm->resize(400, 700);
        widget = new QWidget(PropertyLinePatternForm);
        widget->setObjectName("widget");
        widget->setGeometry(QRect(4, 4, 211, 31));
        toolButtonCreateBlock = new QToolButton(widget);
        toolButtonCreateBlock->setObjectName("toolButtonCreateBlock");
        toolButtonCreateBlock->setGeometry(QRect(110, 0, 101, 31));
        toolButtonCreateBlock->setCheckable(true);
        toolButtonCreateBlock->setAutoExclusive(true);
        toolButtonLibrary = new QToolButton(widget);
        toolButtonLibrary->setObjectName("toolButtonLibrary");
        toolButtonLibrary->setGeometry(QRect(3, 0, 101, 31));
        toolButtonLibrary->setCheckable(true);
        toolButtonLibrary->setChecked(true);
        toolButtonLibrary->setAutoExclusive(true);
        toolButtonLibrary->setToolButtonStyle(Qt::ToolButtonTextBesideIcon);
        stackedWidget = new QStackedWidget(PropertyLinePatternForm);
        stackedWidget->setObjectName("stackedWidget");
        stackedWidget->setGeometry(QRect(0, 40, 401, 671));
        page = new QWidget();
        page->setObjectName("page");
        pushButtonEditLibFolder = new QPushButton(page);
        pushButtonEditLibFolder->setObjectName("pushButtonEditLibFolder");
        pushButtonEditLibFolder->setGeometry(QRect(20, 0, 101, 31));
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/Qtres/Class.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        pushButtonEditLibFolder->setIcon(icon);
        labelLibFolderName = new QLabel(page);
        labelLibFolderName->setObjectName("labelLibFolderName");
        labelLibFolderName->setGeometry(QRect(140, 0, 241, 31));
        QFont font;
        font.setPointSize(16);
        labelLibFolderName->setFont(font);
        tableWidgetLibList = new QTableWidget(page);
        if (tableWidgetLibList->columnCount() < 2)
            tableWidgetLibList->setColumnCount(2);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        tableWidgetLibList->setHorizontalHeaderItem(0, __qtablewidgetitem);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        tableWidgetLibList->setHorizontalHeaderItem(1, __qtablewidgetitem1);
        tableWidgetLibList->setObjectName("tableWidgetLibList");
        tableWidgetLibList->setGeometry(QRect(10, 60, 161, 161));
        tableWidgetLibList->setSelectionMode(QAbstractItemView::SingleSelection);
        tableWidgetLibList->setSelectionBehavior(QAbstractItemView::SelectRows);
        tableWidgetGeneratedLibList = new QTableWidget(page);
        if (tableWidgetGeneratedLibList->columnCount() < 2)
            tableWidgetGeneratedLibList->setColumnCount(2);
        QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
        tableWidgetGeneratedLibList->setHorizontalHeaderItem(0, __qtablewidgetitem2);
        QTableWidgetItem *__qtablewidgetitem3 = new QTableWidgetItem();
        tableWidgetGeneratedLibList->setHorizontalHeaderItem(1, __qtablewidgetitem3);
        tableWidgetGeneratedLibList->setObjectName("tableWidgetGeneratedLibList");
        tableWidgetGeneratedLibList->setGeometry(QRect(230, 60, 161, 161));
        tableWidgetGeneratedLibList->setSelectionBehavior(QAbstractItemView::SelectRows);
        pushButtonSetFrom = new QPushButton(page);
        pushButtonSetFrom->setObjectName("pushButtonSetFrom");
        pushButtonSetFrom->setGeometry(QRect(180, 90, 39, 23));
        pushButtonGetBack = new QPushButton(page);
        pushButtonGetBack->setObjectName("pushButtonGetBack");
        pushButtonGetBack->setGeometry(QRect(180, 120, 39, 23));
        pushButtonEditLibrary = new QPushButton(page);
        pushButtonEditLibrary->setObjectName("pushButtonEditLibrary");
        pushButtonEditLibrary->setGeometry(QRect(200, 230, 191, 31));
        QFont font1;
        font1.setPointSize(12);
        pushButtonEditLibrary->setFont(font1);
        QIcon icon1;
        icon1.addFile(QString::fromUtf8(":/Qtres/Edit.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        pushButtonEditLibrary->setIcon(icon1);
        ButtonGenerateLibs = new QPushButton(page);
        ButtonGenerateLibs->setObjectName("ButtonGenerateLibs");
        ButtonGenerateLibs->setGeometry(QRect(14, 270, 381, 61));
        QFont font2;
        font2.setPointSize(11);
        ButtonGenerateLibs->setFont(font2);
        QIcon icon2;
        icon2.addFile(QString::fromUtf8(":/Qtres/Add.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        ButtonGenerateLibs->setIcon(icon2);
        frame_4 = new QFrame(page);
        frame_4->setObjectName("frame_4");
        frame_4->setGeometry(QRect(10, 350, 381, 311));
        frame_4->setFrameShape(QFrame::StyledPanel);
        frame_4->setFrameShadow(QFrame::Sunken);
        EditLibName = new QLineEdit(frame_4);
        EditLibName->setObjectName("EditLibName");
        EditLibName->setGeometry(QRect(140, 20, 231, 21));
        EditLibName->setFont(font1);
        label_3 = new QLabel(frame_4);
        label_3->setObjectName("label_3");
        label_3->setGeometry(QRect(0, 0, 381, 21));
        label_3->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditLibID = new QLineEdit(frame_4);
        EditLibID->setObjectName("EditLibID");
        EditLibID->setGeometry(QRect(60, 20, 81, 21));
        EditLibID->setFont(font1);
        EditLibID->setReadOnly(true);
        label_4 = new QLabel(frame_4);
        label_4->setObjectName("label_4");
        label_4->setGeometry(QRect(10, 20, 51, 21));
        label_4->setFont(font1);
        label_4->setFrameShape(QFrame::Panel);
        label_4->setFrameShadow(QFrame::Sunken);
        label_4->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        ButtonLibSave = new QPushButton(frame_4);
        ButtonLibSave->setObjectName("ButtonLibSave");
        ButtonLibSave->setGeometry(QRect(10, 270, 361, 31));
        QIcon icon3;
        icon3.addFile(QString::fromUtf8(":/Qtres/Update.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        ButtonLibSave->setIcon(icon3);
        frame_3 = new QFrame(frame_4);
        frame_3->setObjectName("frame_3");
        frame_3->setGeometry(QRect(10, 50, 361, 91));
        frame_3->setFrameShape(QFrame::StyledPanel);
        frame_3->setFrameShadow(QFrame::Sunken);
        EditLineWidthInPattern = new QSpinBox(frame_3);
        EditLineWidthInPattern->setObjectName("EditLineWidthInPattern");
        EditLineWidthInPattern->setGeometry(QRect(220, 10, 81, 22));
        EditLineWidthInPattern->setMaximum(1000000);
        label_9 = new QLabel(frame_3);
        label_9->setObjectName("label_9");
        label_9->setGeometry(QRect(42, 30, 168, 21));
        label_9->setFrameShape(QFrame::Panel);
        label_9->setFrameShadow(QFrame::Sunken);
        label_9->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditLineWidthOutside = new QSpinBox(frame_3);
        EditLineWidthOutside->setObjectName("EditLineWidthOutside");
        EditLineWidthOutside->setGeometry(QRect(220, 30, 81, 22));
        EditLineWidthOutside->setMaximum(1000000);
        label_10 = new QLabel(frame_3);
        label_10->setObjectName("label_10");
        label_10->setGeometry(QRect(42, 10, 168, 21));
        label_10->setFrameShape(QFrame::Panel);
        label_10->setFrameShadow(QFrame::Sunken);
        label_10->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_13 = new QLabel(frame_3);
        label_13->setObjectName("label_13");
        label_13->setGeometry(QRect(42, 60, 168, 21));
        label_13->setFrameShape(QFrame::Panel);
        label_13->setFrameShadow(QFrame::Sunken);
        label_13->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditLimitLength = new QSpinBox(frame_3);
        EditLimitLength->setObjectName("EditLimitLength");
        EditLimitLength->setGeometry(QRect(220, 60, 61, 22));
        EditLimitLength->setMaximum(99999);
        label_53 = new QLabel(frame_3);
        label_53->setObjectName("label_53");
        label_53->setGeometry(QRect(0, 0, 31, 91));
        label_53->setFrameShape(QFrame::Panel);
        label_53->setFrameShadow(QFrame::Raised);
        label_53->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_53->setIndent(1);
        label_30 = new QLabel(page);
        label_30->setObjectName("label_30");
        label_30->setGeometry(QRect(10, 40, 161, 20));
        label_30->setFrameShape(QFrame::Panel);
        label_30->setFrameShadow(QFrame::Sunken);
        label_30->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_31 = new QLabel(page);
        label_31->setObjectName("label_31");
        label_31->setGeometry(QRect(230, 40, 161, 20));
        label_31->setFrameShape(QFrame::Panel);
        label_31->setFrameShadow(QFrame::Sunken);
        label_31->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        pushButtonGetBackAll = new QPushButton(page);
        pushButtonGetBackAll->setObjectName("pushButtonGetBackAll");
        pushButtonGetBackAll->setGeometry(QRect(180, 200, 39, 23));
        pushButtonSetFromAll = new QPushButton(page);
        pushButtonSetFromAll->setObjectName("pushButtonSetFromAll");
        pushButtonSetFromAll->setGeometry(QRect(180, 170, 39, 23));
        stackedWidget->addWidget(page);
        page_2 = new QWidget();
        page_2->setObjectName("page_2");
        tableWidgetBlockInfo = new QTableWidget(page_2);
        if (tableWidgetBlockInfo->columnCount() < 4)
            tableWidgetBlockInfo->setColumnCount(4);
        QTableWidgetItem *__qtablewidgetitem4 = new QTableWidgetItem();
        tableWidgetBlockInfo->setHorizontalHeaderItem(0, __qtablewidgetitem4);
        QTableWidgetItem *__qtablewidgetitem5 = new QTableWidgetItem();
        tableWidgetBlockInfo->setHorizontalHeaderItem(1, __qtablewidgetitem5);
        QTableWidgetItem *__qtablewidgetitem6 = new QTableWidgetItem();
        tableWidgetBlockInfo->setHorizontalHeaderItem(2, __qtablewidgetitem6);
        QTableWidgetItem *__qtablewidgetitem7 = new QTableWidgetItem();
        tableWidgetBlockInfo->setHorizontalHeaderItem(3, __qtablewidgetitem7);
        tableWidgetBlockInfo->setObjectName("tableWidgetBlockInfo");
        tableWidgetBlockInfo->setGeometry(QRect(10, 20, 381, 131));
        tableWidgetBlockInfo->setSelectionMode(QAbstractItemView::MultiSelection);
        label_32 = new QLabel(page_2);
        label_32->setObjectName("label_32");
        label_32->setGeometry(QRect(10, 0, 381, 21));
        label_32->setFont(font1);
        label_32->setFrameShape(QFrame::Panel);
        label_32->setFrameShadow(QFrame::Sunken);
        label_32->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        frameBlockInfoOnMouse = new QFrame(page_2);
        frameBlockInfoOnMouse->setObjectName("frameBlockInfoOnMouse");
        frameBlockInfoOnMouse->setGeometry(QRect(4, 160, 391, 491));
        frameBlockInfoOnMouse->setFrameShape(QFrame::StyledPanel);
        frameBlockInfoOnMouse->setFrameShadow(QFrame::Sunken);
        label_33 = new QLabel(frameBlockInfoOnMouse);
        label_33->setObjectName("label_33");
        label_33->setGeometry(QRect(0, 0, 371, 31));
        label_33->setFont(font1);
        label_33->setFrameShape(QFrame::Panel);
        label_33->setFrameShadow(QFrame::Sunken);
        label_33->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        frame = new QFrame(frameBlockInfoOnMouse);
        frame->setObjectName("frame");
        frame->setGeometry(QRect(0, 40, 391, 451));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Raised);
        EditLibNameInBlock = new QLineEdit(frame);
        EditLibNameInBlock->setObjectName("EditLibNameInBlock");
        EditLibNameInBlock->setGeometry(QRect(120, 0, 231, 31));
        EditLibNameInBlock->setFont(font1);
        EditLibIDnBlock = new QLineEdit(frame);
        EditLibIDnBlock->setObjectName("EditLibIDnBlock");
        EditLibIDnBlock->setGeometry(QRect(60, 0, 61, 31));
        EditLibIDnBlock->setFont(font1);
        EditLibIDnBlock->setReadOnly(true);
        label_34 = new QLabel(frame);
        label_34->setObjectName("label_34");
        label_34->setGeometry(QRect(10, 0, 51, 31));
        label_34->setFont(font1);
        label_34->setFrameShape(QFrame::Panel);
        label_34->setFrameShadow(QFrame::Sunken);
        label_34->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        frame_9 = new QFrame(frame);
        frame_9->setObjectName("frame_9");
        frame_9->setGeometry(QRect(4, 150, 381, 71));
        frame_9->setFrameShape(QFrame::StyledPanel);
        frame_9->setFrameShadow(QFrame::Sunken);
        label_39 = new QLabel(frame_9);
        label_39->setObjectName("label_39");
        label_39->setGeometry(QRect(0, 0, 24, 71));
        label_39->setFrameShape(QFrame::Panel);
        label_39->setFrameShadow(QFrame::Raised);
        label_39->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_39->setIndent(1);
        checkBModeAbsoluteBright = new QCheckBox(frame_9);
        checkBModeAbsoluteBright->setObjectName("checkBModeAbsoluteBright");
        checkBModeAbsoluteBright->setGeometry(QRect(40, 24, 141, 18));
        checkBModeCenterBrightFromParts = new QCheckBox(frame_9);
        checkBModeCenterBrightFromParts->setObjectName("checkBModeCenterBrightFromParts");
        checkBModeCenterBrightFromParts->setGeometry(QRect(190, 4, 191, 18));
        checkBModeEnabled = new QCheckBox(frame_9);
        checkBModeEnabled->setObjectName("checkBModeEnabled");
        checkBModeEnabled->setGeometry(QRect(40, 4, 141, 18));
        checkBModeDynamicMask = new QCheckBox(frame_9);
        checkBModeDynamicMask->setObjectName("checkBModeDynamicMask");
        checkBModeDynamicMask->setGeometry(QRect(190, 24, 191, 18));
        label_35 = new QLabel(frame_9);
        label_35->setObjectName("label_35");
        label_35->setGeometry(QRect(40, 46, 241, 21));
        label_35->setFrameShape(QFrame::Panel);
        label_35->setFrameShadow(QFrame::Sunken);
        label_35->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditTransitDot = new QSpinBox(frame_9);
        EditTransitDot->setObjectName("EditTransitDot");
        EditTransitDot->setGeometry(QRect(290, 46, 81, 22));
        EditTransitDot->setMaximum(255);
        frame_6 = new QFrame(frame);
        frame_6->setObjectName("frame_6");
        frame_6->setGeometry(QRect(4, 30, 381, 72));
        frame_6->setFrameShape(QFrame::StyledPanel);
        frame_6->setFrameShadow(QFrame::Sunken);
        label_36 = new QLabel(frame_6);
        label_36->setObjectName("label_36");
        label_36->setGeometry(QRect(0, 0, 24, 72));
        label_36->setFrameShape(QFrame::Panel);
        label_36->setFrameShadow(QFrame::Raised);
        label_36->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_36->setIndent(1);
        label_20 = new QLabel(frame_6);
        label_20->setObjectName("label_20");
        label_20->setGeometry(QRect(290, 8, 72, 21));
        label_20->setFrameShape(QFrame::Panel);
        label_20->setFrameShadow(QFrame::Sunken);
        label_20->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_17 = new QLabel(frame_6);
        label_17->setObjectName("label_17");
        label_17->setGeometry(QRect(36, 28, 176, 21));
        label_17->setFrameShape(QFrame::Panel);
        label_17->setFrameShadow(QFrame::Sunken);
        label_17->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditNGSizeIH = new QSpinBox(frame_6);
        EditNGSizeIH->setObjectName("EditNGSizeIH");
        EditNGSizeIH->setGeometry(QRect(290, 48, 72, 22));
        EditNGSizeIH->setMaximum(99999999);
        label_18 = new QLabel(frame_6);
        label_18->setObjectName("label_18");
        label_18->setGeometry(QRect(36, 48, 176, 21));
        label_18->setFrameShape(QFrame::Panel);
        label_18->setFrameShadow(QFrame::Sunken);
        label_18->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditBrightWidthIL = new QSpinBox(frame_6);
        EditBrightWidthIL->setObjectName("EditBrightWidthIL");
        EditBrightWidthIL->setGeometry(QRect(218, 28, 72, 22));
        EditBrightWidthIL->setMaximum(255);
        EditNGSizeIL = new QSpinBox(frame_6);
        EditNGSizeIL->setObjectName("EditNGSizeIL");
        EditNGSizeIL->setGeometry(QRect(218, 48, 72, 22));
        EditNGSizeIL->setMaximum(99999999);
        EditBrightWidthIH = new QSpinBox(frame_6);
        EditBrightWidthIH->setObjectName("EditBrightWidthIH");
        EditBrightWidthIH->setGeometry(QRect(290, 28, 72, 22));
        EditBrightWidthIH->setMaximum(255);
        label_19 = new QLabel(frame_6);
        label_19->setObjectName("label_19");
        label_19->setGeometry(QRect(218, 8, 72, 21));
        label_19->setFrameShape(QFrame::Panel);
        label_19->setFrameShadow(QFrame::Sunken);
        label_19->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        frame_7 = new QFrame(frame);
        frame_7->setObjectName("frame_7");
        frame_7->setGeometry(QRect(4, 100, 381, 51));
        frame_7->setFrameShape(QFrame::StyledPanel);
        frame_7->setFrameShadow(QFrame::Sunken);
        label_37 = new QLabel(frame_7);
        label_37->setObjectName("label_37");
        label_37->setGeometry(QRect(0, 0, 24, 51));
        label_37->setFrameShape(QFrame::Panel);
        label_37->setFrameShadow(QFrame::Raised);
        label_37->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_37->setIndent(1);
        label_22 = new QLabel(frame_7);
        label_22->setObjectName("label_22");
        label_22->setGeometry(QRect(36, 4, 176, 21));
        label_22->setFrameShape(QFrame::Panel);
        label_22->setFrameShadow(QFrame::Sunken);
        label_22->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditNGSizeOH = new QSpinBox(frame_7);
        EditNGSizeOH->setObjectName("EditNGSizeOH");
        EditNGSizeOH->setGeometry(QRect(290, 24, 72, 22));
        EditNGSizeOH->setMaximum(99999999);
        EditNGSizeOL = new QSpinBox(frame_7);
        EditNGSizeOL->setObjectName("EditNGSizeOL");
        EditNGSizeOL->setGeometry(QRect(218, 24, 72, 22));
        EditNGSizeOL->setMaximum(99999999);
        EditBrightWidthOL = new QSpinBox(frame_7);
        EditBrightWidthOL->setObjectName("EditBrightWidthOL");
        EditBrightWidthOL->setGeometry(QRect(218, 4, 72, 22));
        EditBrightWidthOL->setMaximum(255);
        label_24 = new QLabel(frame_7);
        label_24->setObjectName("label_24");
        label_24->setGeometry(QRect(36, 24, 176, 21));
        label_24->setFrameShape(QFrame::Panel);
        label_24->setFrameShadow(QFrame::Sunken);
        label_24->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditBrightWidthOH = new QSpinBox(frame_7);
        EditBrightWidthOH->setObjectName("EditBrightWidthOH");
        EditBrightWidthOH->setGeometry(QRect(290, 4, 72, 22));
        EditBrightWidthOH->setMaximum(255);
        frame_13 = new QFrame(frame);
        frame_13->setObjectName("frame_13");
        frame_13->setGeometry(QRect(4, 222, 381, 51));
        frame_13->setFrameShape(QFrame::StyledPanel);
        frame_13->setFrameShadow(QFrame::Sunken);
        label_43 = new QLabel(frame_13);
        label_43->setObjectName("label_43");
        label_43->setGeometry(QRect(0, 0, 24, 51));
        label_43->setFrameShape(QFrame::Panel);
        label_43->setFrameShadow(QFrame::Raised);
        label_43->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_43->setIndent(1);
        frame_14 = new QFrame(frame_13);
        frame_14->setObjectName("frame_14");
        frame_14->setGeometry(QRect(10, 120, 371, 101));
        frame_14->setFrameShape(QFrame::StyledPanel);
        frame_14->setFrameShadow(QFrame::Sunken);
        label_44 = new QLabel(frame_14);
        label_44->setObjectName("label_44");
        label_44->setGeometry(QRect(0, 0, 20, 61));
        label_44->setFrameShape(QFrame::Panel);
        label_44->setFrameShadow(QFrame::Raised);
        label_44->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_44->setIndent(1);
        EditSearchDot = new QSpinBox(frame_13);
        EditSearchDot->setObjectName("EditSearchDot");
        EditSearchDot->setGeometry(QRect(290, 4, 81, 22));
        label_27 = new QLabel(frame_13);
        label_27->setObjectName("label_27");
        label_27->setGeometry(QRect(30, 4, 251, 21));
        label_27->setFrameShape(QFrame::Panel);
        label_27->setFrameShadow(QFrame::Sunken);
        label_27->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_28 = new QLabel(frame_13);
        label_28->setObjectName("label_28");
        label_28->setGeometry(QRect(30, 24, 251, 21));
        label_28->setFrameShape(QFrame::Panel);
        label_28->setFrameShadow(QFrame::Sunken);
        label_28->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditGlobalSearchDot = new QSpinBox(frame_13);
        EditGlobalSearchDot->setObjectName("EditGlobalSearchDot");
        EditGlobalSearchDot->setGeometry(QRect(290, 24, 81, 22));
        frame_11 = new QFrame(frame);
        frame_11->setObjectName("frame_11");
        frame_11->setGeometry(QRect(4, 274, 381, 101));
        frame_11->setFrameShape(QFrame::StyledPanel);
        frame_11->setFrameShadow(QFrame::Sunken);
        label_41 = new QLabel(frame_11);
        label_41->setObjectName("label_41");
        label_41->setGeometry(QRect(0, 0, 24, 101));
        label_41->setFrameShape(QFrame::Panel);
        label_41->setFrameShadow(QFrame::Raised);
        label_41->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_41->setIndent(1);
        frame_12 = new QFrame(frame_11);
        frame_12->setObjectName("frame_12");
        frame_12->setGeometry(QRect(10, 120, 371, 101));
        frame_12->setFrameShape(QFrame::StyledPanel);
        frame_12->setFrameShadow(QFrame::Sunken);
        label_42 = new QLabel(frame_12);
        label_42->setObjectName("label_42");
        label_42->setGeometry(QRect(0, 0, 20, 61));
        label_42->setFrameShape(QFrame::Panel);
        label_42->setFrameShadow(QFrame::Raised);
        label_42->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_42->setIndent(1);
        EditAdjustBrightIL = new QSpinBox(frame_11);
        EditAdjustBrightIL->setObjectName("EditAdjustBrightIL");
        EditAdjustBrightIL->setGeometry(QRect(290, 4, 81, 22));
        EditAdjustBrightIL->setMaximum(255);
        EditAdjustBrightIH = new QSpinBox(frame_11);
        EditAdjustBrightIH->setObjectName("EditAdjustBrightIH");
        EditAdjustBrightIH->setGeometry(QRect(290, 24, 81, 22));
        EditAdjustBrightIH->setMaximum(255);
        label_26 = new QLabel(frame_11);
        label_26->setObjectName("label_26");
        label_26->setGeometry(QRect(32, 24, 250, 21));
        label_26->setFrameShape(QFrame::Panel);
        label_26->setFrameShadow(QFrame::Sunken);
        label_26->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_25 = new QLabel(frame_11);
        label_25->setObjectName("label_25");
        label_25->setGeometry(QRect(32, 4, 250, 21));
        label_25->setFrameShape(QFrame::Panel);
        label_25->setFrameShadow(QFrame::Sunken);
        label_25->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditAdjustBrightOH = new QSpinBox(frame_11);
        EditAdjustBrightOH->setObjectName("EditAdjustBrightOH");
        EditAdjustBrightOH->setGeometry(QRect(290, 72, 81, 22));
        EditAdjustBrightOH->setMaximum(255);
        label_29 = new QLabel(frame_11);
        label_29->setObjectName("label_29");
        label_29->setGeometry(QRect(32, 52, 250, 21));
        label_29->setFrameShape(QFrame::Panel);
        label_29->setFrameShadow(QFrame::Sunken);
        label_29->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditAdjustBrightOL = new QSpinBox(frame_11);
        EditAdjustBrightOL->setObjectName("EditAdjustBrightOL");
        EditAdjustBrightOL->setGeometry(QRect(290, 52, 81, 22));
        EditAdjustBrightOL->setMaximum(255);
        label_38 = new QLabel(frame_11);
        label_38->setObjectName("label_38");
        label_38->setGeometry(QRect(32, 72, 250, 21));
        label_38->setFrameShape(QFrame::Panel);
        label_38->setFrameShadow(QFrame::Sunken);
        label_38->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        frame_15 = new QFrame(frame);
        frame_15->setObjectName("frame_15");
        frame_15->setGeometry(QRect(0, 380, 391, 61));
        frame_15->setFrameShape(QFrame::StyledPanel);
        frame_15->setFrameShadow(QFrame::Sunken);
        label_45 = new QLabel(frame_15);
        label_45->setObjectName("label_45");
        label_45->setGeometry(QRect(0, 0, 31, 61));
        label_45->setFrameShape(QFrame::Panel);
        label_45->setFrameShadow(QFrame::Raised);
        label_45->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_45->setIndent(1);
        checkBModeUseRegularBrightness = new QCheckBox(frame_15);
        checkBModeUseRegularBrightness->setObjectName("checkBModeUseRegularBrightness");
        checkBModeUseRegularBrightness->setGeometry(QRect(40, 4, 341, 18));
        label_40 = new QLabel(frame_15);
        label_40->setObjectName("label_40");
        label_40->setGeometry(QRect(40, 30, 81, 21));
        label_40->setFrameShape(QFrame::Panel);
        label_40->setFrameShadow(QFrame::Sunken);
        label_40->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditRegulatedColI = new QSpinBox(frame_15);
        EditRegulatedColI->setObjectName("EditRegulatedColI");
        EditRegulatedColI->setGeometry(QRect(122, 30, 81, 22));
        EditRegulatedColI->setMaximum(255);
        EditRegulatedColO = new QSpinBox(frame_15);
        EditRegulatedColO->setObjectName("EditRegulatedColO");
        EditRegulatedColO->setGeometry(QRect(302, 30, 81, 22));
        EditRegulatedColO->setMaximum(255);
        label_46 = new QLabel(frame_15);
        label_46->setObjectName("label_46");
        label_46->setGeometry(QRect(220, 30, 81, 21));
        label_46->setFrameShape(QFrame::Panel);
        label_46->setFrameShadow(QFrame::Sunken);
        label_46->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        stackedWidget->addWidget(page_2);
        frame_2 = new QFrame(PropertyLinePatternForm);
        frame_2->setObjectName("frame_2");
        frame_2->setGeometry(QRect(220, 4, 121, 31));
        frame_2->setFrameShape(QFrame::StyledPanel);
        frame_2->setFrameShadow(QFrame::Raised);
        toolButtonArea = new QToolButton(frame_2);
        toolButtonArea->setObjectName("toolButtonArea");
        toolButtonArea->setGeometry(QRect(0, 0, 41, 31));
        toolButtonArea->setCheckable(true);
        toolButtonArea->setChecked(true);
        toolButtonInside = new QToolButton(frame_2);
        toolButtonInside->setObjectName("toolButtonInside");
        toolButtonInside->setGeometry(QRect(40, 0, 41, 31));
        toolButtonInside->setCheckable(true);
        toolButtonOutside = new QToolButton(frame_2);
        toolButtonOutside->setObjectName("toolButtonOutside");
        toolButtonOutside->setGeometry(QRect(80, 0, 41, 31));
        toolButtonOutside->setCheckable(true);
        comboBoxResultAngleNumber = new QComboBox(PropertyLinePatternForm);
        comboBoxResultAngleNumber->addItem(QString());
        comboBoxResultAngleNumber->addItem(QString());
        comboBoxResultAngleNumber->addItem(QString());
        comboBoxResultAngleNumber->addItem(QString());
        comboBoxResultAngleNumber->addItem(QString());
        comboBoxResultAngleNumber->addItem(QString());
        comboBoxResultAngleNumber->addItem(QString());
        comboBoxResultAngleNumber->addItem(QString());
        comboBoxResultAngleNumber->addItem(QString());
        comboBoxResultAngleNumber->addItem(QString());
        comboBoxResultAngleNumber->addItem(QString());
        comboBoxResultAngleNumber->addItem(QString());
        comboBoxResultAngleNumber->addItem(QString());
        comboBoxResultAngleNumber->setObjectName("comboBoxResultAngleNumber");
        comboBoxResultAngleNumber->setGeometry(QRect(340, 10, 56, 24));

        retranslateUi(PropertyLinePatternForm);

        stackedWidget->setCurrentIndex(1);


        QMetaObject::connectSlotsByName(PropertyLinePatternForm);
    } // setupUi

    void retranslateUi(GUIFormBase *PropertyLinePatternForm)
    {
        PropertyLinePatternForm->setWindowTitle(QCoreApplication::translate("PropertyLinePatternForm", "Form", nullptr));
        toolButtonCreateBlock->setText(QCoreApplication::translate("PropertyLinePatternForm", "Create Block", nullptr));
        toolButtonLibrary->setText(QCoreApplication::translate("PropertyLinePatternForm", "Library Test", nullptr));
        pushButtonEditLibFolder->setText(QCoreApplication::translate("PropertyLinePatternForm", "\345\210\206\351\241\236\351\201\270\346\212\236", nullptr));
        labelLibFolderName->setText(QCoreApplication::translate("PropertyLinePatternForm", "\357\274\270\357\274\270\357\274\270", nullptr));
        QTableWidgetItem *___qtablewidgetitem = tableWidgetLibList->horizontalHeaderItem(0);
        ___qtablewidgetitem->setText(QCoreApplication::translate("PropertyLinePatternForm", "ID", nullptr));
        QTableWidgetItem *___qtablewidgetitem1 = tableWidgetLibList->horizontalHeaderItem(1);
        ___qtablewidgetitem1->setText(QCoreApplication::translate("PropertyLinePatternForm", "Name", nullptr));
        QTableWidgetItem *___qtablewidgetitem2 = tableWidgetGeneratedLibList->horizontalHeaderItem(0);
        ___qtablewidgetitem2->setText(QCoreApplication::translate("PropertyLinePatternForm", "ID", nullptr));
        QTableWidgetItem *___qtablewidgetitem3 = tableWidgetGeneratedLibList->horizontalHeaderItem(1);
        ___qtablewidgetitem3->setText(QCoreApplication::translate("PropertyLinePatternForm", "Name", nullptr));
        pushButtonSetFrom->setText(QCoreApplication::translate("PropertyLinePatternForm", "=>", nullptr));
        pushButtonGetBack->setText(QCoreApplication::translate("PropertyLinePatternForm", "<=", nullptr));
        pushButtonEditLibrary->setText(QCoreApplication::translate("PropertyLinePatternForm", "\343\203\251\343\202\244\343\203\226\343\203\251\343\203\252\347\267\250\351\233\206", nullptr));
        ButtonGenerateLibs->setText(QCoreApplication::translate("PropertyLinePatternForm", "\344\270\212\343\201\256\345\205\250\343\201\246\343\201\256\343\203\251\343\202\244\343\203\226\343\203\251\343\203\252\343\201\247\347\224\237\346\210\220", nullptr));
        EditLibName->setText(QCoreApplication::translate("PropertyLinePatternForm", "Library Name", nullptr));
        label_3->setText(QCoreApplication::translate("PropertyLinePatternForm", "\343\203\251\343\202\244\343\203\226\343\203\251\343\203\252\343\203\227\343\203\255\343\203\221\343\203\206\343\202\243", nullptr));
        EditLibID->setText(QCoreApplication::translate("PropertyLinePatternForm", "12345", nullptr));
        label_4->setText(QCoreApplication::translate("PropertyLinePatternForm", "\345\220\215\347\247\260", nullptr));
        ButtonLibSave->setText(QCoreApplication::translate("PropertyLinePatternForm", "\343\203\207\343\203\274\343\202\277\343\203\231\343\203\274\343\202\271\343\201\270\343\201\256\346\233\264\346\226\260", nullptr));
        label_9->setText(QCoreApplication::translate("PropertyLinePatternForm", "\345\244\226\345\201\264\345\271\205", nullptr));
        label_10->setText(QCoreApplication::translate("PropertyLinePatternForm", "\345\206\205\345\201\264\345\271\205", nullptr));
        label_13->setText(QCoreApplication::translate("PropertyLinePatternForm", "\351\231\220\347\225\214\351\225\267\343\201\225", nullptr));
        label_53->setText(QCoreApplication::translate("PropertyLinePatternForm", "\343\202\265\n"
"\343\202\244\n"
"\343\202\272", nullptr));
        label_30->setText(QCoreApplication::translate("PropertyLinePatternForm", "\347\231\273\351\214\262\343\201\225\343\202\214\343\201\246\343\201\204\343\202\213\343\203\251\343\202\244\343\203\226\343\203\251\343\203\252\343\203\252\343\202\271\343\203\210", nullptr));
        label_31->setText(QCoreApplication::translate("PropertyLinePatternForm", "\344\273\212\345\233\236\344\275\277\347\224\250\343\201\231\343\202\213\350\250\255\345\256\232", nullptr));
        pushButtonGetBackAll->setText(QCoreApplication::translate("PropertyLinePatternForm", "<<=", nullptr));
        pushButtonSetFromAll->setText(QCoreApplication::translate("PropertyLinePatternForm", "=>>", nullptr));
        QTableWidgetItem *___qtablewidgetitem4 = tableWidgetBlockInfo->horizontalHeaderItem(0);
        ___qtablewidgetitem4->setText(QCoreApplication::translate("PropertyLinePatternForm", "ID", nullptr));
        QTableWidgetItem *___qtablewidgetitem5 = tableWidgetBlockInfo->horizontalHeaderItem(1);
        ___qtablewidgetitem5->setText(QCoreApplication::translate("PropertyLinePatternForm", "\343\203\251\343\202\244\343\203\226\343\203\251\343\203\252\345\220\215", nullptr));
        QTableWidgetItem *___qtablewidgetitem6 = tableWidgetBlockInfo->horizontalHeaderItem(2);
        ___qtablewidgetitem6->setText(QCoreApplication::translate("PropertyLinePatternForm", "\351\240\230\345\237\237\347\267\217\346\225\260", nullptr));
        QTableWidgetItem *___qtablewidgetitem7 = tableWidgetBlockInfo->horizontalHeaderItem(3);
        ___qtablewidgetitem7->setText(QCoreApplication::translate("PropertyLinePatternForm", "\343\203\254\343\202\244\343\203\244\343\203\274\357\274\221", nullptr));
        label_32->setText(QCoreApplication::translate("PropertyLinePatternForm", "\344\275\277\347\224\250\343\201\225\343\202\214\343\201\246\343\201\204\343\202\213\351\240\230\345\237\237\346\203\205\345\240\261", nullptr));
        label_33->setText(QCoreApplication::translate("PropertyLinePatternForm", "\343\203\236\343\202\246\343\202\271\343\202\253\343\203\274\343\202\275\343\203\253\344\275\215\347\275\256\343\201\256\351\240\230\345\237\237\346\203\205\345\240\261", nullptr));
        EditLibNameInBlock->setText(QCoreApplication::translate("PropertyLinePatternForm", "Library Name", nullptr));
        EditLibIDnBlock->setText(QCoreApplication::translate("PropertyLinePatternForm", "12345", nullptr));
        label_34->setText(QCoreApplication::translate("PropertyLinePatternForm", "\345\220\215\347\247\260", nullptr));
        label_39->setText(QCoreApplication::translate("PropertyLinePatternForm", "\345\261\236\n"
"\346\200\247", nullptr));
        checkBModeAbsoluteBright->setText(QCoreApplication::translate("PropertyLinePatternForm", "\347\265\266\345\257\276\350\274\235\345\272\246", nullptr));
        checkBModeCenterBrightFromParts->setText(QCoreApplication::translate("PropertyLinePatternForm", "\351\203\250\345\223\201\343\201\213\343\202\211\350\274\235\345\272\246\343\202\222\346\212\275\345\207\272", nullptr));
        checkBModeEnabled->setText(QCoreApplication::translate("PropertyLinePatternForm", "\346\244\234\346\237\273\346\234\211\345\212\271", nullptr));
        checkBModeDynamicMask->setText(QCoreApplication::translate("PropertyLinePatternForm", "\345\256\237\350\241\214\343\203\236\343\202\271\343\202\257", nullptr));
        label_35->setText(QCoreApplication::translate("PropertyLinePatternForm", "\350\274\252\351\203\255\351\203\250\345\210\206\343\201\256\347\247\273\350\241\214\345\271\205", nullptr));
        label_36->setText(QCoreApplication::translate("PropertyLinePatternForm", "<html><head/><body><p>\345\206\205</p><p>\345\201\264</p></body></html>", nullptr));
        label_20->setText(QCoreApplication::translate("PropertyLinePatternForm", "\346\230\216\345\201\264", nullptr));
        label_17->setText(QCoreApplication::translate("PropertyLinePatternForm", "OK\350\274\235\345\272\246\347\257\204\345\233\262", nullptr));
        label_18->setText(QCoreApplication::translate("PropertyLinePatternForm", "OK\343\203\211\343\203\203\343\203\210\346\225\260", nullptr));
        label_19->setText(QCoreApplication::translate("PropertyLinePatternForm", "\346\232\227\345\201\264", nullptr));
        label_37->setText(QCoreApplication::translate("PropertyLinePatternForm", "<html><head/><body><p>\345\244\226</p><p>\345\201\264</p></body></html>", nullptr));
        label_22->setText(QCoreApplication::translate("PropertyLinePatternForm", "OK\350\274\235\345\272\246\347\257\204\345\233\262", nullptr));
        label_24->setText(QCoreApplication::translate("PropertyLinePatternForm", "OK\343\203\211\343\203\203\343\203\210\346\225\260", nullptr));
        label_43->setText(QCoreApplication::translate("PropertyLinePatternForm", "\346\216\242\n"
"\347\264\242", nullptr));
        label_44->setText(QCoreApplication::translate("PropertyLinePatternForm", "\350\274\235\n"
"\345\272\246", nullptr));
        label_27->setText(QCoreApplication::translate("PropertyLinePatternForm", "\345\215\230\344\275\223\343\201\247\343\201\256\346\216\242\347\264\242\343\203\211\343\203\203\343\203\210\346\225\260", nullptr));
        label_28->setText(QCoreApplication::translate("PropertyLinePatternForm", "\345\205\250\344\275\223\343\201\247\343\201\256\346\216\242\347\264\242\343\203\211\343\203\203\343\203\210\346\225\260", nullptr));
        label_41->setText(QCoreApplication::translate("PropertyLinePatternForm", "\350\243\234\n"
"\346\255\243", nullptr));
        label_42->setText(QCoreApplication::translate("PropertyLinePatternForm", "\350\274\235\n"
"\345\272\246", nullptr));
        label_26->setText(QCoreApplication::translate("PropertyLinePatternForm", "\345\206\205\345\201\264\343\200\200\346\230\216\345\201\264\343\200\200\346\234\200\345\244\247\350\243\234\346\255\243\350\274\235\345\272\246\351\207\217", nullptr));
        label_25->setText(QCoreApplication::translate("PropertyLinePatternForm", "\345\206\205\345\201\264\343\200\200\346\232\227\345\201\264\343\200\200\346\234\200\345\244\247\350\243\234\346\255\243\350\274\235\345\272\246\351\207\217", nullptr));
        label_29->setText(QCoreApplication::translate("PropertyLinePatternForm", "\345\244\226\345\201\264\343\200\200\346\232\227\345\201\264\343\200\200\346\234\200\345\244\247\350\243\234\346\255\243\350\274\235\345\272\246\351\207\217", nullptr));
        label_38->setText(QCoreApplication::translate("PropertyLinePatternForm", "\345\244\226\345\201\264\343\200\200\346\230\216\345\201\264\343\200\200\346\234\200\345\244\247\350\243\234\346\255\243\350\274\235\345\272\246\351\207\217", nullptr));
        label_45->setText(QCoreApplication::translate("PropertyLinePatternForm", "\350\274\235\n"
"\345\272\246", nullptr));
        checkBModeUseRegularBrightness->setText(QCoreApplication::translate("PropertyLinePatternForm", "\345\237\272\346\272\226\350\274\235\345\272\246\343\202\222\344\275\277\343\201\206", nullptr));
        label_40->setText(QCoreApplication::translate("PropertyLinePatternForm", "\345\206\205\345\201\264", nullptr));
        label_46->setText(QCoreApplication::translate("PropertyLinePatternForm", "\345\244\226\345\201\264", nullptr));
        toolButtonArea->setText(QCoreApplication::translate("PropertyLinePatternForm", "A", nullptr));
        toolButtonInside->setText(QCoreApplication::translate("PropertyLinePatternForm", "I", nullptr));
        toolButtonOutside->setText(QCoreApplication::translate("PropertyLinePatternForm", "O", nullptr));
        comboBoxResultAngleNumber->setItemText(0, QCoreApplication::translate("PropertyLinePatternForm", "0", nullptr));
        comboBoxResultAngleNumber->setItemText(1, QCoreApplication::translate("PropertyLinePatternForm", "1A", nullptr));
        comboBoxResultAngleNumber->setItemText(2, QCoreApplication::translate("PropertyLinePatternForm", "1B", nullptr));
        comboBoxResultAngleNumber->setItemText(3, QCoreApplication::translate("PropertyLinePatternForm", "2A", nullptr));
        comboBoxResultAngleNumber->setItemText(4, QCoreApplication::translate("PropertyLinePatternForm", "2B", nullptr));
        comboBoxResultAngleNumber->setItemText(5, QCoreApplication::translate("PropertyLinePatternForm", "3A", nullptr));
        comboBoxResultAngleNumber->setItemText(6, QCoreApplication::translate("PropertyLinePatternForm", "3B", nullptr));
        comboBoxResultAngleNumber->setItemText(7, QCoreApplication::translate("PropertyLinePatternForm", "4A", nullptr));
        comboBoxResultAngleNumber->setItemText(8, QCoreApplication::translate("PropertyLinePatternForm", "4B", nullptr));
        comboBoxResultAngleNumber->setItemText(9, QCoreApplication::translate("PropertyLinePatternForm", "5A", nullptr));
        comboBoxResultAngleNumber->setItemText(10, QCoreApplication::translate("PropertyLinePatternForm", "5B", nullptr));
        comboBoxResultAngleNumber->setItemText(11, QCoreApplication::translate("PropertyLinePatternForm", "6A", nullptr));
        comboBoxResultAngleNumber->setItemText(12, QCoreApplication::translate("PropertyLinePatternForm", "6B", nullptr));

    } // retranslateUi

};

namespace Ui {
    class PropertyLinePatternForm: public Ui_PropertyLinePatternForm {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_PROPERTYLINEPATTERNFORM_H
