#ifndef HOLEWALLINSPECTIONIMAGEPANEL_GLOBAL_H
#define HOLEWALLINSPECTIONIMAGEPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef HOLEWALLINSPECTIONIMAGEPANEL_LIB
# define HOLEWALLINSPECTIONIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define HOLEWALLINSPECTIONIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // HOLEWALLINSPECTIONIMAGEPANEL_GLOBAL_H
