# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = ReportDisk
DESTDIR = ../../../
CONFIG += debug
LIBS += -L"./../../../Lib/Release" \
    -lServiceLib
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += .
RCC_DIR += ./GeneratedFiles
include(ReportDisk.pri)
win32:RC_FILE = ReportDisk.rc
