#ifndef DISPLAYOLDIMAGEPANEL_GLOBAL_H
#define DISPLAYOLDIMAGEPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef DISPLAYOLDIMAGEPANEL_LIB
# define DISPLAYOLDIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define DISPLAYOLDIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // DISPLAYOLDIMAGEPANEL_GLOBAL_H
