#ifndef EASYCOLORDIFFERENCEIMAGEPANEL_GLOBAL_H
#define EASYCOLORDIFFERENCEIMAGEPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef EASYCOLORDIFFERENCEIMAGEPANEL_LIB
# define EASYCOLORDIFFERENCEIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define EASYCOLORDIFFERENCEIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // EASYCOLORDIFFERENCEIMAGEPANEL_GLOBAL_H
