#ifndef SHOWSWITCHPHASERESULTLIST_GLOBAL_H
#define SHOWSWITCHPHASERESULTLIST_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SHOWSWITCHPHASERESULTLIST_LIB
# define SHOWSWITCHPHASERESULTLIST_EXPORT Q_DECL_EXPORT
#else
# define SHOWSWITCHPHASERESULTLIST_EXPORT Q_DECL_IMPORT
#endif

#endif // SHOWSWITCHPHASERESULTLIST_GLOBAL_H
