#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(INTEGRATIONCAMERACHANGEQUICKPROPERTY_LIB)
#  define INTEGRATIONCAMERACHANGEQUICKPROPERTY_EXPORT Q_DECL_EXPORT
# else
#  define INTEGRATIONCAMERACHANGEQUICKPROPERTY_EXPORT Q_DECL_IMPORT
# endif
#else
# define INTEGRATIONCAMERACHANGEQUICKPROPERTY_EXPORT
#endif
