#ifndef FILTERLINEARHORIZONTAL_GLOBAL_H
#define FILTERLINEARHORIZONTAL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef FILTERLINEARHORIZONTAL_LIB
# define FILTERLINEARHORIZONTAL_EXPORT Q_DECL_EXPORT
#else
# define FILTERLINEARHORIZONTAL_EXPORT Q_DECL_IMPORT
#endif

#endif // FILTERLINEARHORIZONTAL_GLOBAL_H
