#ifndef DALSALOADIMAGE_GLOBAL_H
#define DALSALOADIMAGE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef DALSALOADIMAGE_LIB
# define DALSALOADIMAGE_EXPORT Q_DECL_EXPORT
#else
# define DALSALOADIMAGE_EXPORT Q_DECL_IMPORT
#endif

#endif // DALSALOADIMAGE_GLOBAL_H
