#ifndef SHOWBLOCKLIST_GLOBAL_H
#define SHOWBLOCKLIST_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SHOWBLOCKLIST_LIB
# define SHOWBLOCKLIST_EXPORT Q_DECL_EXPORT
#else
# define SHOWBLOCKLIST_EXPORT Q_DECL_IMPORT
#endif

#endif // SHOWBLOCKLIST_GLOBAL_H
