#ifndef DISPLAYLIBFOLDER_GLOBAL_H
#define DISPLAYLIBFOLDER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef DISPLAYLIBFOLDER_LIB
# define DISPLAYLIBFOLDER_EXPORT Q_DECL_EXPORT
#else
# define DISPLAYLIBFOLDER_EXPORT Q_DECL_IMPORT
#endif

#endif // DISPLAYLIBFOLDER_GLOBAL_H
