#ifndef LIGHTDLL2PORT_GLOBAL_H
#define LIGHTDLL2PORT_GLOBAL_H

#include <qglobal.h>

#ifdef LIGHTDLL2PORT_LIB
# define LIGHTDLL2PORT_EXPORT Q_DECL_EXPORT
#else
# define LIGHTDLL2PORT_EXPORT Q_DECL_IMPORT
#endif

#endif // LIGHTDLL2PORT_GLOBAL_H
