#ifndef PROPERTYDOTMATCHING_GLOBAL_H
#define PROPERTYDOTMATCHING_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PROPERTYDOTMATCHING_LIB
# define PROPERTYDOTMATCHING_EXPORT Q_DECL_EXPORT
#else
# define PROPERTYDOTMATCHING_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTYDOTMATCHING_GLOBAL_H
