#ifndef LIVECAMERAARTCAM035IMXWOM_GLOBAL_H
#define LIVECAMERAARTCAM035IMXWOM_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef LIVECAMERAARTCAM035IMXWOM_LIB
# define LIVECAMERAARTCAM035IMXWOM_EXPORT Q_DECL_EXPORT
#else
# define LIVECAMERAARTCAM035IMXWOM_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONTOSHOWTOTALNGMAP_GLOBAL_H
