#ifndef ALIGNMENTFLEXAREAIMAGEPANEL_GLOBAL_H
#define ALIGNMENTFLEXAREAIMAGEPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef ALIGNMENTFLEXAREAIMAGEPANEL_LIB
# define ALIGNMENTFLEXAREAIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define ALIGNMENTFLEXAREAIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // ALIGNMENTFLEXAREAIMAGEPANEL_GLOBAL_H
