#ifndef PROPERTYHOUGHINSPECTION_GLOBAL_H
#define PROPERTYHOUGHINSPECTION_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PROPERTYHOUGHINSPECTION_LIB
# define PROPERTYHOUGHINSPECTION_EXPORT Q_DECL_EXPORT
#else
# define PROPERTYHOUGHINSPECTION_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTYHOUGHINSPECTION_GLOBAL_H
