#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(RWCAMRECOGNITIONIMAGEPANEL_LIB)
#  define RWCAMRECOGNITIONIMAGEPANEL_EXPORT Q_DECL_EXPORT
# else
#  define RWCAMRECOGNITIONIMAGEPANEL_EXPORT Q_DECL_IMPORT
# endif
#else
# define RWCAMRECOGNITIONIMAGEPANEL_EXPORT
#endif
