#ifndef PANELOFFSETFORVRS_GLOBAL_H
#define PANELOFFSETFORVRS_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PANELOFFSETFORVRS_LIB
# define PANELOFFSETFORVRS_EXPORT Q_DECL_EXPORT
#else
# define PANELOFFSETFORVRS_EXPORT Q_DECL_IMPORT
#endif

#endif // PANELOFFSETFORVRS_GLOBAL_H
