#ifndef LIGHTUSB8PORT_GLOBAL_H
#define LIGHTUSB8PORT_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef LIGHTUSB8PORT_LIB
# define LIGHTUSB8PORT_EXPORT Q_DECL_EXPORT
#else
# define LIGHTUSB8PORT_EXPORT Q_DECL_IMPORT
#endif

#endif // LIGHTUSB8PORT_GLOBAL_H
