#ifndef BUTTONSHOWPLAYERINSIDE_GLOBAL_H
#define BUTTONSHOWPLAYERINSIDE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONSHOWPLAYERINSIDE_LIB
# define BUTTONSHOWPLAYERINSIDE_EXPORT Q_DECL_EXPORT
#else
# define BUTTONSHOWPLAYERINSIDE_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONSHOWPLAYERINSIDE_GLOBAL_H
