#ifndef LEDCONTROL16G_GLOBAL_H
#define LEDCONTROL16G_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef LEDCONTROL16G_LIB
# define LEDCONTROL16G_EXPORT Q_DECL_EXPORT
#else
# define LEDCONTROL16G_EXPORT Q_DECL_IMPORT
#endif

#endif // LEDCONTROL16G_GLOBAL_H
