#ifndef AUTOSAVEIMAGELISTFORSEARCH_GLOBAL_H
#define AUTOSAVEIMAGELISTFORSEARCH_GLOBAL_H

#include <qglobal.h>

#ifdef AUTOSAVEIMAGELISTFORSEARCH_LIB
# define AUTOSAVEIMAGELISTFORSEARCH_EXPORT Q_DECL_EXPORT
#else
# define AUTOSAVEIMAGELISTFORSEARCH_EXPORT Q_DECL_IMPORT
#endif

#endif // AUTOSAVEIMAGELISTFORSEARCH_GLOBAL_H
