#ifndef PANELSCROLLABLE_GLOBAL_H
#define PANELSCROLLABLE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PANELSCROLLABLE_LIB
# define PANELSCROLLABLE_EXPORT Q_DECL_EXPORT
#else
# define PANELSCROLLABLE_EXPORT Q_DECL_IMPORT
#endif

#endif // PANELSCROLLABLE_GLOBAL_H
