# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./ContecNC2D.h
SOURCES += ./main.cpp \
    ./ContecNC2D.cpp
FORMS += ./ContecNC2D.ui
RESOURCES += ContecNC2D.qrc
