#ifndef EASYMASKINGIMAGEPANEL_GLOBAL_H
#define EASYMASKINGIMAGEPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef EASYMASKINGIMAGEPANEL_LIB
# define EASYMASKINGIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define EASYMASKINGIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // EASYMASKINGIMAGEPANEL_GLOBAL_H
