#ifndef RECORDMOVIE_GLOBAL_H
#define RECORDMOVIE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef RECORDMOVIE_LIB
# define RECORDMOVIE_EXPORT Q_DECL_EXPORT
#else
# define RECORDMOVIE_EXPORT Q_DECL_IMPORT
#endif

#endif // RECORDMOVIE_GLOBAL_H
