#ifndef LINEENHANCER_GLOBAL_H
#define LINEENHANCER_GLOBAL_H

#include <qglobal.h>

#ifdef LINEENHANCER_LIB
# define LINEENHANCER_EXPORT Q_DECL_EXPORT
#else
# define LINEENHANCER_EXPORT Q_DECL_IMPORT
#endif

#endif // LINEENHANCER_GLOBAL_H
