#ifndef PROPERTYTHINMETAL_GLOBAL_H
#define PROPERTYTHINMETAL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PROPERTYTHINMETAL_LIB
# define PROPERTYTHINMETAL_EXPORT Q_DECL_EXPORT
#else
# define PROPERTYTHINMETAL_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTYTHINMETAL_GLOBAL_H
