#ifndef ALIGNMENTPROJECTION_GLOBAL_H
#define ALIGNMENTPROJECTION_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef ALIGNMENTPROJECTION_LIB
# define ALIGNMENTPROJECTION_EXPORT Q_DECL_EXPORT
#else
# define ALIGNMENTPROJECTION_EXPORT Q_DECL_IMPORT
#endif

#endif // ALIGNMENTPROJECTION_GLOBAL_H
