#ifndef BUTTONTOSAVECOPIEDITEMDIRECTLY_GLOBAL_H
#define BUTTONTOSAVECOPIEDITEMDIRECTLY_GLOBAL_H

#include <qglobal.h>

#ifdef BUTTONTOSAVECOPIEDITEMDIRECTLY_LIB
# define BUTTONTOSAVECOPIEDITEMDIRECTLY_EXPORT Q_DECL_EXPORT
#else
# define BUTTONTOSAVECOPIEDITEMDIRECTLY_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONTOSAVECOPIEDITEMDIRECTLY_GLOBAL_H
