# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = CameraMVSLinear
DESTDIR = ../../
CONFIG += release
DEFINES += CAMERAMVSLINEAR_LIB
LIBS += -L"./MVS/Development/Libraries/win64" \
    -L"./../../../Lib/Release" \
    -lServiceLib \
    -lMvCameraControl
DEPENDPATH += .
MOC_DIR += GeneratedFiles/$(ConfigurationName)
OBJECTS_DIR += release
UI_DIR += GeneratedFiles
RCC_DIR += GeneratedFiles
include(CameraMVSLinear.pri)

FORMS += \
    SettingLinearCameraDialog.ui

HEADERS += \
    SettingLinearCameraDialog.h

SOURCES += \
    SettingLinearCameraDialog.cpp
