#ifndef WAVELE1DINSPECTION_GLOBAL_H
#define WAVELE1DINSPECTION_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef WAVELE1DINSPECTION_LIB
# define WAVELE1DINSPECTION_EXPORT Q_DECL_EXPORT
#else
# define WAVELE1DINSPECTION_EXPORT Q_DECL_IMPORT
#endif

#endif // WAVELE1DINSPECTION_GLOBAL_H
