#ifndef ALIGNMENTLARGEIMAGEPANEL_GLOBAL_H
#define ALIGNMENTLARGEIMAGEPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef ALIGNMENTLARGEIMAGEPANEL_LIB
# define ALIGNMENTLARGEIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define ALIGNMENTLARGEIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // ALIGNMENTLARGEIMAGEPANEL_GLOBAL_H
