# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = CameraXtiumLinearHSColorMonoLineTrigger
DESTDIR = ../../
CONFIG += debug
DEFINES += CAMERAXTIUMLINEARHSCOLORMONOLINETRIGGER_LIB
LIBS += -L"./../../../Lib/Release" \
    -L"$(SAPERA)/lib/Win64" \
    -lcorapi \
    -lSapClassBasic \
    -lComponent \
    -lServiceLib \
    -lSeqLib
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += .
RCC_DIR += GeneratedFiles
include(CameraXtiumLinearHSColorMonoLineTrigger.pri)
