#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(CAMERAXTIUMLINEARHSCOLORMONOLINETRIGGER_LIB)
#  define CAMERAXTIUMLINEARHSCOLORMONOLINETRIGGER_EXPORT Q_DECL_EXPORT
# else
#  define CAMERAXTIUMLINEARHSCOLORMONOLINETRIGGER_EXPORT Q_DECL_IMPORT
# endif
#else
# define CAMERAXTIUMLINEARHSCOLORMONOLINETRIGGER_EXPORT
#endif
