#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(CAMERACHANGEQUICKPROPERTY_LIB)
#  define CAMERACHANGEQUICKPROPERTY_EXPORT Q_DECL_EXPORT
# else
#  define CAMERACHANGEQUICKPROPERTY_EXPORT Q_DECL_IMPORT
# endif
#else
# define CAMERACHANGEQUICKPROPERTY_EXPORT
#endif
