#ifndef SHOWRESULTMULTIDELIVERY_GLOBAL_H
#define SHOWRESULTMULTIDELIVERY_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SHOWRESULTMULTIDELIVERY_LIB
# define SHOWRESULTMULTIDELIVERY_EXPORT Q_DECL_EXPORT
#else
# define SHOWRESULTMULTIDELIVERY_EXPORT Q_DECL_IMPORT
#endif

#endif // SHOWRESULTMULTIDELIVERY_GLOBAL_H
