#ifndef STARTCAPTUREONLYTARGET_GLOBAL_H
#define STARTCAPTUREONLYTARGET_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef STARTCAPTUREONLYTARGET_LIB
# define STARTCAPTUREONLYTARGET_EXPORT Q_DECL_EXPORT
#else
# define STARTCAPTUREONLYTARGET_EXPORT Q_DECL_IMPORT
#endif

#endif // STARTCAPTUREONLYTARGET_GLOBAL_H
