#ifndef ALIGNMENTLARGE_GLOBAL_H
#define ALIGNMENTLARGE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef ALIGNMENTLARGE_LIB
# define ALIGNMENTLARGE_EXPORT Q_DECL_EXPORT
#else
# define ALIGNMENTLARGE_EXPORT Q_DECL_IMPORT
#endif

#endif // ALIGNMENTLARGE_GLOBAL_H
