#ifndef INTEGRATIONUPDATEHISTORYLIST_GLOBAL_H
#define INTEGRATIONUPDATEHISTORYLIST_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef INTEGRATIONUPDATEHISTORYLIST_LIB
# define INTEGRATIONUPDATEHISTORYLIST_EXPORT Q_DECL_EXPORT
#else
# define INTEGRATIONUPDATEHISTORYLIST_EXPORT Q_DECL_IMPORT
#endif

#endif // INTEGRATIONUPDATEHISTORYLIST_GLOBAL_H
