#ifndef DENTINSPECTION_GLOBAL_H
#define DENTINSPECTION_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef DENTINSPECTION_LIB
# define DENTINSPECTION_EXPORT Q_DECL_EXPORT
#else
# define DENTINSPECTION_EXPORT Q_DECL_IMPORT
#endif

#endif // DENTINSPECTION_GLOBAL_H
