#ifndef SHOWCURRENTTIME_GLOBAL_H
#define SHOWCURRENTTIME_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SHOWCURRENTTIME_LIB
# define SHOWCURRENTTIME_EXPORT Q_DECL_EXPORT
#else
# define SHOWCURRENTTIME_EXPORT Q_DECL_IMPORT
#endif

#endif // SHOWCURRENTTIME_GLOBAL_H
