#ifndef BUTTONTOSHOWCROSSLINE_GLOBAL_H
#define BUTTONTOSHOWCROSSLINE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONTOSHOWCROSSLINE_LIB
# define BUTTONTOSHOWCROSSLINE_EXPORT Q_DECL_EXPORT
#else
# define BUTTONTOSHOWCROSSLINE_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONTOSHOWCROSSLINE_GLOBAL_H
