#ifndef PANELINPUTINFORMATION_GLOBAL_H
#define PANELINPUTINFORMATION_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PANELINPUTINFORMATION_LIB
# define PANELINPUTINFORMATION_EXPORT Q_DECL_EXPORT
#else
# define PANELINPUTINFORMATION_EXPORT Q_DECL_IMPORT
#endif

#endif // PANELINPUTINFORMATION_GLOBAL_H
