#ifndef INTEGRATIONSHOWSAVEDIMAGE_GLOBAL_H
#define INTEGRATIONSHOWSAVEDIMAGE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef INTEGRATIONSHOWSAVEDIMAGE_LIB
# define INTEGRATIONSHOWSAVEDIMAGE_EXPORT Q_DECL_EXPORT
#else
# define INTEGRATIONSHOWSAVEDIMAGE_EXPORT Q_DECL_IMPORT
#endif

#endif // INTEGRATIONSHOWSAVEDIMAGE_GLOBAL_H
