#ifndef BUTTONCHANGESERVERFORMASTER_GLOBAL_H
#define BUTTONCHANGESERVERFORMASTER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONCHANGESERVERFORMASTER_LIB
# define BUTTONCHANGESERVERFORMASTER_EXPORT Q_DECL_EXPORT
#else
# define BUTTONCHANGESERVERFORMASTER_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONCHANGESERVERFORMASTER_GLOBAL_H
