#ifndef FILTERHRESOLUTION_GLOBAL_H
#define FILTERHRESOLUTION_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef FILTERHRESOLUTION_LIB
# define FILTERHRESOLUTION_EXPORT Q_DECL_EXPORT
#else
# define FILTERHRESOLUTION_EXPORT Q_DECL_IMPORT
#endif

#endif // FILTERHRESOLUTION_GLOBAL_H
