#ifndef LIGHTDLL6PORT_GLOBAL_H
#define LIGHTDLL6PORT_GLOBAL_H

#include <qglobal.h>

#ifdef LIGHTDLL6PORT_LIB
# define LIGHTDLL6PORT_EXPORT Q_DECL_EXPORT
#else
# define LIGHTDLL6PORT_EXPORT Q_DECL_IMPORT
#endif

#endif // LIGHTDLL6PORT_GLOBAL_H
