#ifndef BUTTONSETTINGTHRESHOLD_GLOBAL_H
#define BUTTONSETTINGTHRESHOLD_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONSETTINGTHRESHOLD_LIB
# define BUTTONSETTINGTHRESHOLD_EXPORT Q_DECL_EXPORT
#else
# define BUTTONSETTINGTHRESHOLD_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONSETTINGTHRESHOLD_GLOBAL_H
