#ifndef LEDCONTROL16P16_GLOBAL_H
#define LEDCONTROL16P16_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef LEDCONTROL16P16_LIB
# define LEDCONTROL16P16_EXPORT Q_DECL_EXPORT
#else
# define LEDCONTROL16P16_EXPORT Q_DECL_IMPORT
#endif

#endif // LEDCONTROL16P16_GLOBAL_H
