#ifndef RESULTIMPORTANCEIMAGEPANEL_GLOBAL_H
#define RESULTIMPORTANCEIMAGEPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef RESULTIMPORTANCEIMAGEPANEL_LIB
# define RESULTIMPORTANCEIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define RESULTIMPORTANCEIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // RESULTIMPORTANCEIMAGEPANEL_GLOBAL_H
