/********************************************************************************
** Form generated from reading UI file 'SettingCameraDialog.ui'
**
** Created by: Qt User Interface Compiler version 6.10.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_SETTINGCAMERADIALOG_H
#define UI_SETTINGCAMERADIALOG_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDialog>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_SettingCameraDialog
{
public:
    QTabWidget *tabWidget;
    QWidget *tab;
    QLabel *label_2;
    QComboBox *comboBoxImageSize;
    QWidget *tab_2;
    QLabel *label_3;
    QSlider *horizontalSliderBrightness;
    QLabel *labelBrightness;
    QLabel *label_5;
    QSlider *horizontalSliderContrast;
    QLabel *labelContrast;
    QLabel *label_7;
    QSlider *horizontalSliderColor;
    QLabel *labelColor;
    QLabel *label_9;
    QSlider *horizontalSliderVivid;
    QLabel *labelVivid;
    QLabel *label_11;
    QSlider *horizontalSliderVividation;
    QLabel *labelVividation;
    QLabel *label_13;
    QSlider *horizontalSliderGamma;
    QLabel *labelGamma;
    QLabel *label_15;
    QSlider *horizontalSliderWhiteBalance;
    QLabel *labelWhiteBalance;
    QLabel *label_17;
    QCheckBox *checkBoxWhiteBalance;
    QSlider *horizontalSliderReflection;
    QLabel *labelReflection;
    QLabel *label_19;
    QSlider *horizontalSliderGain;
    QLabel *labelGain;
    QLabel *label_21;
    QLabel *label_22;
    QComboBox *comboBoxPowerFrequency;
    QLabel *labelExposure;
    QCheckBox *checkBoxExposure;
    QLabel *label_31;
    QSlider *horizontalSliderExposure;
    QPushButton *pushButtonResetSettingEachCamera;
    QWidget *tab_3;
    QSlider *horizontalSliderZoom;
    QLabel *labelZoom;
    QLabel *label_25;
    QLabel *label_26;
    QCheckBox *checkBoxZoom;
    QSlider *horizontalSliderFocus;
    QLabel *labelFocus;
    QCheckBox *checkBoxFocus;
    QLabel *label_28;
    QSlider *horizontalSliderIris;
    QLabel *labelIris;
    QCheckBox *checkBoxIris;
    QLabel *label_32;
    QSlider *horizontalSliderPan;
    QLabel *labelPan;
    QCheckBox *checkBoxPan;
    QLabel *label_34;
    QSlider *horizontalSliderTilt;
    QLabel *labelTilt;
    QCheckBox *checkBoxTilt;
    QLabel *label_36;
    QSlider *horizontalSliderRotation;
    QLabel *labelRotation;
    QCheckBox *checkBoxRotation;
    QLabel *label_38;
    QCheckBox *checkBoxAdjustLow;
    QPushButton *pushButtonDefault;
    QSpinBox *spinBoxTotalCamCount;
    QLabel *label;
    QLabel *label_23;
    QComboBox *comboBoxCurrentCamNo;
    QPushButton *pushButtonOK;
    QPushButton *pushButtonCancel;
    QLineEdit *lineEditCamDevice;
    QLabel *label_39;
    QComboBox *comboBoxSource;
    QPushButton *pushButtonSave;
    QPushButton *pushButtonLoad;
    QCheckBox *checkBoxBrightness;
    QCheckBox *checkBoxGamma;
    QCheckBox *checkBoxVivid;
    QCheckBox *checkBoxVividation;
    QCheckBox *checkBoxColor;
    QCheckBox *checkBoxGain;
    QCheckBox *checkBoxReflection;
    QCheckBox *checkBoxContrast;

    void setupUi(QDialog *SettingCameraDialog)
    {
        if (SettingCameraDialog->objectName().isEmpty())
            SettingCameraDialog->setObjectName("SettingCameraDialog");
        SettingCameraDialog->resize(679, 687);
        tabWidget = new QTabWidget(SettingCameraDialog);
        tabWidget->setObjectName("tabWidget");
        tabWidget->setGeometry(QRect(20, 80, 651, 551));
        tab = new QWidget();
        tab->setObjectName("tab");
        label_2 = new QLabel(tab);
        label_2->setObjectName("label_2");
        label_2->setGeometry(QRect(10, 20, 191, 21));
        label_2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        comboBoxImageSize = new QComboBox(tab);
        comboBoxImageSize->setObjectName("comboBoxImageSize");
        comboBoxImageSize->setGeometry(QRect(220, 20, 381, 24));
        tabWidget->addTab(tab, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName("tab_2");
        label_3 = new QLabel(tab_2);
        label_3->setObjectName("label_3");
        label_3->setGeometry(QRect(10, 40, 161, 21));
        label_3->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        horizontalSliderBrightness = new QSlider(tab_2);
        horizontalSliderBrightness->setObjectName("horizontalSliderBrightness");
        horizontalSliderBrightness->setEnabled(true);
        horizontalSliderBrightness->setGeometry(QRect(180, 40, 331, 22));
        horizontalSliderBrightness->setMaximum(255);
        horizontalSliderBrightness->setOrientation(Qt::Horizontal);
        labelBrightness = new QLabel(tab_2);
        labelBrightness->setObjectName("labelBrightness");
        labelBrightness->setGeometry(QRect(520, 40, 61, 31));
        labelBrightness->setFrameShape(QFrame::Panel);
        labelBrightness->setFrameShadow(QFrame::Sunken);
        label_5 = new QLabel(tab_2);
        label_5->setObjectName("label_5");
        label_5->setGeometry(QRect(580, 10, 61, 21));
        label_5->setAlignment(Qt::AlignCenter);
        horizontalSliderContrast = new QSlider(tab_2);
        horizontalSliderContrast->setObjectName("horizontalSliderContrast");
        horizontalSliderContrast->setGeometry(QRect(180, 120, 331, 22));
        horizontalSliderContrast->setMaximum(256);
        horizontalSliderContrast->setOrientation(Qt::Horizontal);
        labelContrast = new QLabel(tab_2);
        labelContrast->setObjectName("labelContrast");
        labelContrast->setGeometry(QRect(520, 120, 61, 31));
        labelContrast->setFrameShape(QFrame::Panel);
        labelContrast->setFrameShadow(QFrame::Sunken);
        label_7 = new QLabel(tab_2);
        label_7->setObjectName("label_7");
        label_7->setGeometry(QRect(10, 120, 161, 21));
        label_7->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        horizontalSliderColor = new QSlider(tab_2);
        horizontalSliderColor->setObjectName("horizontalSliderColor");
        horizontalSliderColor->setGeometry(QRect(180, 160, 331, 22));
        horizontalSliderColor->setMaximum(256);
        horizontalSliderColor->setOrientation(Qt::Horizontal);
        labelColor = new QLabel(tab_2);
        labelColor->setObjectName("labelColor");
        labelColor->setGeometry(QRect(520, 160, 61, 31));
        labelColor->setFrameShape(QFrame::Panel);
        labelColor->setFrameShadow(QFrame::Sunken);
        label_9 = new QLabel(tab_2);
        label_9->setObjectName("label_9");
        label_9->setGeometry(QRect(10, 160, 161, 21));
        label_9->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        horizontalSliderVivid = new QSlider(tab_2);
        horizontalSliderVivid->setObjectName("horizontalSliderVivid");
        horizontalSliderVivid->setGeometry(QRect(180, 200, 331, 22));
        horizontalSliderVivid->setMaximum(256);
        horizontalSliderVivid->setOrientation(Qt::Horizontal);
        labelVivid = new QLabel(tab_2);
        labelVivid->setObjectName("labelVivid");
        labelVivid->setGeometry(QRect(520, 200, 61, 31));
        labelVivid->setFrameShape(QFrame::Panel);
        labelVivid->setFrameShadow(QFrame::Sunken);
        label_11 = new QLabel(tab_2);
        label_11->setObjectName("label_11");
        label_11->setGeometry(QRect(10, 200, 161, 21));
        label_11->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        horizontalSliderVividation = new QSlider(tab_2);
        horizontalSliderVividation->setObjectName("horizontalSliderVividation");
        horizontalSliderVividation->setGeometry(QRect(180, 240, 331, 22));
        horizontalSliderVividation->setMaximum(256);
        horizontalSliderVividation->setOrientation(Qt::Horizontal);
        labelVividation = new QLabel(tab_2);
        labelVividation->setObjectName("labelVividation");
        labelVividation->setGeometry(QRect(520, 240, 61, 31));
        labelVividation->setFrameShape(QFrame::Panel);
        labelVividation->setFrameShadow(QFrame::Sunken);
        label_13 = new QLabel(tab_2);
        label_13->setObjectName("label_13");
        label_13->setGeometry(QRect(10, 240, 161, 21));
        label_13->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        horizontalSliderGamma = new QSlider(tab_2);
        horizontalSliderGamma->setObjectName("horizontalSliderGamma");
        horizontalSliderGamma->setGeometry(QRect(180, 280, 331, 22));
        horizontalSliderGamma->setMaximum(256);
        horizontalSliderGamma->setOrientation(Qt::Horizontal);
        labelGamma = new QLabel(tab_2);
        labelGamma->setObjectName("labelGamma");
        labelGamma->setGeometry(QRect(520, 280, 61, 31));
        labelGamma->setFrameShape(QFrame::Panel);
        labelGamma->setFrameShadow(QFrame::Sunken);
        label_15 = new QLabel(tab_2);
        label_15->setObjectName("label_15");
        label_15->setGeometry(QRect(10, 280, 161, 21));
        label_15->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        horizontalSliderWhiteBalance = new QSlider(tab_2);
        horizontalSliderWhiteBalance->setObjectName("horizontalSliderWhiteBalance");
        horizontalSliderWhiteBalance->setGeometry(QRect(180, 320, 331, 22));
        horizontalSliderWhiteBalance->setMaximum(10000);
        horizontalSliderWhiteBalance->setOrientation(Qt::Horizontal);
        labelWhiteBalance = new QLabel(tab_2);
        labelWhiteBalance->setObjectName("labelWhiteBalance");
        labelWhiteBalance->setGeometry(QRect(520, 320, 61, 31));
        labelWhiteBalance->setFrameShape(QFrame::Panel);
        labelWhiteBalance->setFrameShadow(QFrame::Sunken);
        label_17 = new QLabel(tab_2);
        label_17->setObjectName("label_17");
        label_17->setGeometry(QRect(10, 320, 161, 21));
        label_17->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        checkBoxWhiteBalance = new QCheckBox(tab_2);
        checkBoxWhiteBalance->setObjectName("checkBoxWhiteBalance");
        checkBoxWhiteBalance->setGeometry(QRect(600, 320, 31, 22));
        horizontalSliderReflection = new QSlider(tab_2);
        horizontalSliderReflection->setObjectName("horizontalSliderReflection");
        horizontalSliderReflection->setGeometry(QRect(180, 360, 331, 22));
        horizontalSliderReflection->setMaximum(256);
        horizontalSliderReflection->setOrientation(Qt::Horizontal);
        labelReflection = new QLabel(tab_2);
        labelReflection->setObjectName("labelReflection");
        labelReflection->setGeometry(QRect(520, 360, 61, 31));
        labelReflection->setFrameShape(QFrame::Panel);
        labelReflection->setFrameShadow(QFrame::Sunken);
        label_19 = new QLabel(tab_2);
        label_19->setObjectName("label_19");
        label_19->setGeometry(QRect(10, 360, 161, 21));
        label_19->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        horizontalSliderGain = new QSlider(tab_2);
        horizontalSliderGain->setObjectName("horizontalSliderGain");
        horizontalSliderGain->setGeometry(QRect(180, 400, 331, 22));
        horizontalSliderGain->setMaximum(100);
        horizontalSliderGain->setOrientation(Qt::Horizontal);
        labelGain = new QLabel(tab_2);
        labelGain->setObjectName("labelGain");
        labelGain->setGeometry(QRect(520, 400, 61, 31));
        labelGain->setFrameShape(QFrame::Panel);
        labelGain->setFrameShadow(QFrame::Sunken);
        label_21 = new QLabel(tab_2);
        label_21->setObjectName("label_21");
        label_21->setGeometry(QRect(10, 400, 161, 21));
        label_21->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_22 = new QLabel(tab_2);
        label_22->setObjectName("label_22");
        label_22->setGeometry(QRect(90, 440, 411, 21));
        label_22->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        comboBoxPowerFrequency = new QComboBox(tab_2);
        comboBoxPowerFrequency->addItem(QString());
        comboBoxPowerFrequency->addItem(QString());
        comboBoxPowerFrequency->addItem(QString());
        comboBoxPowerFrequency->setObjectName("comboBoxPowerFrequency");
        comboBoxPowerFrequency->setGeometry(QRect(520, 440, 71, 24));
        labelExposure = new QLabel(tab_2);
        labelExposure->setObjectName("labelExposure");
        labelExposure->setGeometry(QRect(520, 80, 61, 31));
        labelExposure->setFrameShape(QFrame::Panel);
        labelExposure->setFrameShadow(QFrame::Sunken);
        checkBoxExposure = new QCheckBox(tab_2);
        checkBoxExposure->setObjectName("checkBoxExposure");
        checkBoxExposure->setGeometry(QRect(600, 80, 31, 22));
        label_31 = new QLabel(tab_2);
        label_31->setObjectName("label_31");
        label_31->setGeometry(QRect(10, 80, 161, 21));
        label_31->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        horizontalSliderExposure = new QSlider(tab_2);
        horizontalSliderExposure->setObjectName("horizontalSliderExposure");
        horizontalSliderExposure->setGeometry(QRect(180, 80, 331, 22));
        horizontalSliderExposure->setMinimum(-10);
        horizontalSliderExposure->setMaximum(10);
        horizontalSliderExposure->setOrientation(Qt::Horizontal);
        pushButtonResetSettingEachCamera = new QPushButton(tab_2);
        pushButtonResetSettingEachCamera->setObjectName("pushButtonResetSettingEachCamera");
        pushButtonResetSettingEachCamera->setGeometry(QRect(230, 480, 151, 34));
        tabWidget->addTab(tab_2, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName("tab_3");
        horizontalSliderZoom = new QSlider(tab_3);
        horizontalSliderZoom->setObjectName("horizontalSliderZoom");
        horizontalSliderZoom->setGeometry(QRect(180, 40, 331, 22));
        horizontalSliderZoom->setMaximum(100);
        horizontalSliderZoom->setOrientation(Qt::Horizontal);
        labelZoom = new QLabel(tab_3);
        labelZoom->setObjectName("labelZoom");
        labelZoom->setGeometry(QRect(520, 40, 61, 31));
        labelZoom->setFrameShape(QFrame::Panel);
        labelZoom->setFrameShadow(QFrame::Sunken);
        label_25 = new QLabel(tab_3);
        label_25->setObjectName("label_25");
        label_25->setGeometry(QRect(580, 10, 61, 21));
        label_25->setAlignment(Qt::AlignCenter);
        label_26 = new QLabel(tab_3);
        label_26->setObjectName("label_26");
        label_26->setGeometry(QRect(10, 40, 161, 21));
        label_26->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        checkBoxZoom = new QCheckBox(tab_3);
        checkBoxZoom->setObjectName("checkBoxZoom");
        checkBoxZoom->setGeometry(QRect(600, 40, 31, 22));
        horizontalSliderFocus = new QSlider(tab_3);
        horizontalSliderFocus->setObjectName("horizontalSliderFocus");
        horizontalSliderFocus->setGeometry(QRect(180, 80, 331, 22));
        horizontalSliderFocus->setMaximum(100);
        horizontalSliderFocus->setOrientation(Qt::Horizontal);
        labelFocus = new QLabel(tab_3);
        labelFocus->setObjectName("labelFocus");
        labelFocus->setGeometry(QRect(520, 80, 61, 31));
        labelFocus->setFrameShape(QFrame::Panel);
        labelFocus->setFrameShadow(QFrame::Sunken);
        checkBoxFocus = new QCheckBox(tab_3);
        checkBoxFocus->setObjectName("checkBoxFocus");
        checkBoxFocus->setGeometry(QRect(600, 80, 31, 22));
        label_28 = new QLabel(tab_3);
        label_28->setObjectName("label_28");
        label_28->setGeometry(QRect(10, 80, 161, 21));
        label_28->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        horizontalSliderIris = new QSlider(tab_3);
        horizontalSliderIris->setObjectName("horizontalSliderIris");
        horizontalSliderIris->setGeometry(QRect(180, 120, 331, 22));
        horizontalSliderIris->setMaximum(100);
        horizontalSliderIris->setOrientation(Qt::Horizontal);
        labelIris = new QLabel(tab_3);
        labelIris->setObjectName("labelIris");
        labelIris->setGeometry(QRect(520, 120, 61, 31));
        labelIris->setFrameShape(QFrame::Panel);
        labelIris->setFrameShadow(QFrame::Sunken);
        checkBoxIris = new QCheckBox(tab_3);
        checkBoxIris->setObjectName("checkBoxIris");
        checkBoxIris->setGeometry(QRect(600, 120, 31, 22));
        label_32 = new QLabel(tab_3);
        label_32->setObjectName("label_32");
        label_32->setGeometry(QRect(10, 120, 161, 21));
        label_32->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        horizontalSliderPan = new QSlider(tab_3);
        horizontalSliderPan->setObjectName("horizontalSliderPan");
        horizontalSliderPan->setGeometry(QRect(180, 160, 331, 22));
        horizontalSliderPan->setMaximum(100);
        horizontalSliderPan->setOrientation(Qt::Horizontal);
        labelPan = new QLabel(tab_3);
        labelPan->setObjectName("labelPan");
        labelPan->setGeometry(QRect(520, 160, 61, 31));
        labelPan->setFrameShape(QFrame::Panel);
        labelPan->setFrameShadow(QFrame::Sunken);
        checkBoxPan = new QCheckBox(tab_3);
        checkBoxPan->setObjectName("checkBoxPan");
        checkBoxPan->setGeometry(QRect(600, 160, 31, 22));
        label_34 = new QLabel(tab_3);
        label_34->setObjectName("label_34");
        label_34->setGeometry(QRect(10, 160, 161, 21));
        label_34->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        horizontalSliderTilt = new QSlider(tab_3);
        horizontalSliderTilt->setObjectName("horizontalSliderTilt");
        horizontalSliderTilt->setGeometry(QRect(180, 200, 331, 22));
        horizontalSliderTilt->setMaximum(100);
        horizontalSliderTilt->setOrientation(Qt::Horizontal);
        labelTilt = new QLabel(tab_3);
        labelTilt->setObjectName("labelTilt");
        labelTilt->setGeometry(QRect(520, 200, 61, 31));
        labelTilt->setFrameShape(QFrame::Panel);
        labelTilt->setFrameShadow(QFrame::Sunken);
        checkBoxTilt = new QCheckBox(tab_3);
        checkBoxTilt->setObjectName("checkBoxTilt");
        checkBoxTilt->setGeometry(QRect(600, 200, 31, 22));
        label_36 = new QLabel(tab_3);
        label_36->setObjectName("label_36");
        label_36->setGeometry(QRect(10, 200, 161, 21));
        label_36->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        horizontalSliderRotation = new QSlider(tab_3);
        horizontalSliderRotation->setObjectName("horizontalSliderRotation");
        horizontalSliderRotation->setGeometry(QRect(180, 240, 331, 22));
        horizontalSliderRotation->setMaximum(100);
        horizontalSliderRotation->setOrientation(Qt::Horizontal);
        labelRotation = new QLabel(tab_3);
        labelRotation->setObjectName("labelRotation");
        labelRotation->setGeometry(QRect(520, 240, 61, 31));
        labelRotation->setFrameShape(QFrame::Panel);
        labelRotation->setFrameShadow(QFrame::Sunken);
        checkBoxRotation = new QCheckBox(tab_3);
        checkBoxRotation->setObjectName("checkBoxRotation");
        checkBoxRotation->setGeometry(QRect(600, 240, 31, 22));
        label_38 = new QLabel(tab_3);
        label_38->setObjectName("label_38");
        label_38->setGeometry(QRect(10, 240, 161, 21));
        label_38->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        checkBoxAdjustLow = new QCheckBox(tab_3);
        checkBoxAdjustLow->setObjectName("checkBoxAdjustLow");
        checkBoxAdjustLow->setGeometry(QRect(180, 280, 231, 22));
        pushButtonDefault = new QPushButton(tab_3);
        pushButtonDefault->setObjectName("pushButtonDefault");
        pushButtonDefault->setGeometry(QRect(260, 370, 112, 34));
        tabWidget->addTab(tab_3, QString());
        spinBoxTotalCamCount = new QSpinBox(SettingCameraDialog);
        spinBoxTotalCamCount->setObjectName("spinBoxTotalCamCount");
        spinBoxTotalCamCount->setGeometry(QRect(240, 10, 61, 24));
        QPalette palette;
        QBrush brush(QColor(85, 255, 255, 255));
        brush.setStyle(Qt::BrushStyle::SolidPattern);
        palette.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush);
        palette.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush);
        QBrush brush1(QColor(240, 240, 240, 255));
        brush1.setStyle(Qt::BrushStyle::SolidPattern);
        palette.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush1);
        spinBoxTotalCamCount->setPalette(palette);
        spinBoxTotalCamCount->setReadOnly(true);
        label = new QLabel(SettingCameraDialog);
        label->setObjectName("label");
        label->setGeometry(QRect(20, 10, 201, 21));
        label->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_23 = new QLabel(SettingCameraDialog);
        label_23->setObjectName("label_23");
        label_23->setGeometry(QRect(30, 840, 201, 21));
        label_23->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        comboBoxCurrentCamNo = new QComboBox(SettingCameraDialog);
        comboBoxCurrentCamNo->setObjectName("comboBoxCurrentCamNo");
        comboBoxCurrentCamNo->setGeometry(QRect(250, 840, 201, 24));
        pushButtonOK = new QPushButton(SettingCameraDialog);
        pushButtonOK->setObjectName("pushButtonOK");
        pushButtonOK->setGeometry(QRect(400, 640, 112, 34));
        pushButtonCancel = new QPushButton(SettingCameraDialog);
        pushButtonCancel->setObjectName("pushButtonCancel");
        pushButtonCancel->setGeometry(QRect(530, 640, 112, 34));
        lineEditCamDevice = new QLineEdit(SettingCameraDialog);
        lineEditCamDevice->setObjectName("lineEditCamDevice");
        lineEditCamDevice->setGeometry(QRect(240, 40, 381, 24));
        label_39 = new QLabel(SettingCameraDialog);
        label_39->setObjectName("label_39");
        label_39->setGeometry(QRect(30, 40, 191, 21));
        label_39->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        comboBoxSource = new QComboBox(SettingCameraDialog);
        comboBoxSource->setObjectName("comboBoxSource");
        comboBoxSource->setGeometry(QRect(250, 810, 381, 24));
        QPalette palette1;
        palette1.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Button, brush);
        palette1.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush);
        palette1.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Window, brush);
        palette1.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Button, brush);
        palette1.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush);
        palette1.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Window, brush);
        palette1.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Button, brush);
        palette1.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush);
        palette1.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Window, brush);
        comboBoxSource->setPalette(palette1);
        comboBoxSource->setMaxCount(32);
        pushButtonSave = new QPushButton(SettingCameraDialog);
        pushButtonSave->setObjectName("pushButtonSave");
        pushButtonSave->setGeometry(QRect(10, 640, 112, 34));
        pushButtonLoad = new QPushButton(SettingCameraDialog);
        pushButtonLoad->setObjectName("pushButtonLoad");
        pushButtonLoad->setGeometry(QRect(140, 640, 112, 34));
        checkBoxBrightness = new QCheckBox(SettingCameraDialog);
        checkBoxBrightness->setObjectName("checkBoxBrightness");
        checkBoxBrightness->setGeometry(QRect(520, 920, 31, 22));
        checkBoxGamma = new QCheckBox(SettingCameraDialog);
        checkBoxGamma->setObjectName("checkBoxGamma");
        checkBoxGamma->setGeometry(QRect(520, 1100, 31, 22));
        checkBoxVivid = new QCheckBox(SettingCameraDialog);
        checkBoxVivid->setObjectName("checkBoxVivid");
        checkBoxVivid->setGeometry(QRect(520, 1020, 31, 22));
        checkBoxVividation = new QCheckBox(SettingCameraDialog);
        checkBoxVividation->setObjectName("checkBoxVividation");
        checkBoxVividation->setGeometry(QRect(520, 1060, 31, 22));
        checkBoxColor = new QCheckBox(SettingCameraDialog);
        checkBoxColor->setObjectName("checkBoxColor");
        checkBoxColor->setGeometry(QRect(520, 980, 31, 22));
        checkBoxGain = new QCheckBox(SettingCameraDialog);
        checkBoxGain->setObjectName("checkBoxGain");
        checkBoxGain->setGeometry(QRect(580, 970, 31, 22));
        checkBoxReflection = new QCheckBox(SettingCameraDialog);
        checkBoxReflection->setObjectName("checkBoxReflection");
        checkBoxReflection->setGeometry(QRect(580, 930, 31, 22));
        checkBoxContrast = new QCheckBox(SettingCameraDialog);
        checkBoxContrast->setObjectName("checkBoxContrast");
        checkBoxContrast->setGeometry(QRect(520, 950, 31, 22));
        label_23->raise();
        comboBoxCurrentCamNo->raise();
        tabWidget->raise();
        spinBoxTotalCamCount->raise();
        label->raise();
        pushButtonOK->raise();
        pushButtonCancel->raise();
        lineEditCamDevice->raise();
        label_39->raise();
        comboBoxSource->raise();
        pushButtonSave->raise();
        pushButtonLoad->raise();
        checkBoxBrightness->raise();
        checkBoxGamma->raise();
        checkBoxVivid->raise();
        checkBoxVividation->raise();
        checkBoxColor->raise();
        checkBoxGain->raise();
        checkBoxReflection->raise();
        checkBoxContrast->raise();

        retranslateUi(SettingCameraDialog);

        tabWidget->setCurrentIndex(1);


        QMetaObject::connectSlotsByName(SettingCameraDialog);
    } // setupUi

    void retranslateUi(QDialog *SettingCameraDialog)
    {
        SettingCameraDialog->setWindowTitle(QCoreApplication::translate("SettingCameraDialog", "Dialog", nullptr));
        label_2->setText(QCoreApplication::translate("SettingCameraDialog", "\346\222\256\345\203\217\347\224\273\345\203\217\343\202\265\343\202\244\343\202\272", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab), QCoreApplication::translate("SettingCameraDialog", "\345\237\272\346\234\254\350\250\255\345\256\232", nullptr));
        label_3->setText(QCoreApplication::translate("SettingCameraDialog", "\346\230\216\343\202\213\343\201\225", nullptr));
        labelBrightness->setText(QCoreApplication::translate("SettingCameraDialog", "255", nullptr));
        label_5->setText(QCoreApplication::translate("SettingCameraDialog", "\350\207\252\345\213\225", nullptr));
        labelContrast->setText(QCoreApplication::translate("SettingCameraDialog", "255", nullptr));
        label_7->setText(QCoreApplication::translate("SettingCameraDialog", "\343\202\263\343\203\263\343\203\210\343\203\251\343\202\271\343\203\210", nullptr));
        labelColor->setText(QCoreApplication::translate("SettingCameraDialog", "255", nullptr));
        label_9->setText(QCoreApplication::translate("SettingCameraDialog", "\350\211\262\345\220\210\343\201\204", nullptr));
        labelVivid->setText(QCoreApplication::translate("SettingCameraDialog", "255", nullptr));
        label_11->setText(QCoreApplication::translate("SettingCameraDialog", "\351\256\256\343\202\204\343\201\213\343\201\225", nullptr));
        labelVividation->setText(QCoreApplication::translate("SettingCameraDialog", "255", nullptr));
        label_13->setText(QCoreApplication::translate("SettingCameraDialog", "\351\256\256\346\230\216\345\272\246", nullptr));
        labelGamma->setText(QCoreApplication::translate("SettingCameraDialog", "255", nullptr));
        label_15->setText(QCoreApplication::translate("SettingCameraDialog", "\343\202\254\343\203\263\343\203\236", nullptr));
        labelWhiteBalance->setText(QCoreApplication::translate("SettingCameraDialog", "255", nullptr));
        label_17->setText(QCoreApplication::translate("SettingCameraDialog", "\343\203\233\343\203\257\343\202\244\343\203\210\343\203\220\343\203\251\343\203\263\343\202\271", nullptr));
        checkBoxWhiteBalance->setText(QString());
        labelReflection->setText(QCoreApplication::translate("SettingCameraDialog", "255", nullptr));
        label_19->setText(QCoreApplication::translate("SettingCameraDialog", "\351\200\206\345\205\211\350\243\234\346\255\243", nullptr));
        labelGain->setText(QCoreApplication::translate("SettingCameraDialog", "255", nullptr));
        label_21->setText(QCoreApplication::translate("SettingCameraDialog", "\343\202\262\343\202\244\343\203\263", nullptr));
        label_22->setText(QCoreApplication::translate("SettingCameraDialog", "\351\233\273\346\272\220\343\203\251\343\202\244\343\203\263\343\201\256\345\221\250\346\263\242\346\225\260\357\274\210\343\201\241\343\202\211\343\201\244\343\201\215\350\243\234\346\255\243\357\274\211", nullptr));
        comboBoxPowerFrequency->setItemText(0, QCoreApplication::translate("SettingCameraDialog", "\347\204\241\345\212\271", nullptr));
        comboBoxPowerFrequency->setItemText(1, QCoreApplication::translate("SettingCameraDialog", "50Hz", nullptr));
        comboBoxPowerFrequency->setItemText(2, QCoreApplication::translate("SettingCameraDialog", "60Hz", nullptr));

        labelExposure->setText(QCoreApplication::translate("SettingCameraDialog", "255", nullptr));
        checkBoxExposure->setText(QString());
        label_31->setText(QCoreApplication::translate("SettingCameraDialog", "\351\234\262\345\207\272", nullptr));
        pushButtonResetSettingEachCamera->setText(QCoreApplication::translate("SettingCameraDialog", "\345\237\272\346\234\254\350\250\255\345\256\232\343\201\256\343\203\252\343\202\273\343\203\203\343\203\210", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QCoreApplication::translate("SettingCameraDialog", "\347\224\273\345\203\217\343\201\256\350\252\277\346\225\264", nullptr));
        labelZoom->setText(QCoreApplication::translate("SettingCameraDialog", "255", nullptr));
        label_25->setText(QCoreApplication::translate("SettingCameraDialog", "\350\207\252\345\213\225", nullptr));
        label_26->setText(QCoreApplication::translate("SettingCameraDialog", "\343\202\272\343\203\274\343\203\240", nullptr));
        checkBoxZoom->setText(QString());
        labelFocus->setText(QCoreApplication::translate("SettingCameraDialog", "255", nullptr));
        checkBoxFocus->setText(QString());
        label_28->setText(QCoreApplication::translate("SettingCameraDialog", "\347\204\246\347\202\271", nullptr));
        labelIris->setText(QCoreApplication::translate("SettingCameraDialog", "255", nullptr));
        checkBoxIris->setText(QString());
        label_32->setText(QCoreApplication::translate("SettingCameraDialog", "\347\265\236\343\202\212", nullptr));
        labelPan->setText(QCoreApplication::translate("SettingCameraDialog", "255", nullptr));
        checkBoxPan->setText(QString());
        label_34->setText(QCoreApplication::translate("SettingCameraDialog", "\343\203\221\343\203\263", nullptr));
        labelTilt->setText(QCoreApplication::translate("SettingCameraDialog", "255", nullptr));
        checkBoxTilt->setText(QString());
        label_36->setText(QCoreApplication::translate("SettingCameraDialog", "\345\202\276\343\201\215", nullptr));
        labelRotation->setText(QCoreApplication::translate("SettingCameraDialog", "255", nullptr));
        checkBoxRotation->setText(QString());
        label_38->setText(QCoreApplication::translate("SettingCameraDialog", "\345\233\236\350\273\242", nullptr));
        checkBoxAdjustLow->setText(QCoreApplication::translate("SettingCameraDialog", "\344\275\216\345\205\211\351\207\217\350\243\234\346\255\243", nullptr));
        pushButtonDefault->setText(QCoreApplication::translate("SettingCameraDialog", "\350\246\217\345\256\232\345\200\244", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_3), QCoreApplication::translate("SettingCameraDialog", "\343\202\253\343\203\241\343\203\251\345\210\266\345\276\241", nullptr));
        label->setText(QCoreApplication::translate("SettingCameraDialog", "\343\202\253\343\203\241\343\203\251\347\225\252\345\217\267", nullptr));
        label_23->setText(QCoreApplication::translate("SettingCameraDialog", "\350\250\255\345\256\232\343\201\231\343\202\213\343\202\253\343\203\241\343\203\251\347\225\252\345\217\267", nullptr));
        pushButtonOK->setText(QCoreApplication::translate("SettingCameraDialog", "OK", nullptr));
        pushButtonCancel->setText(QCoreApplication::translate("SettingCameraDialog", "\343\202\255\343\203\243\343\203\263\343\202\273\343\203\253", nullptr));
        label_39->setText(QCoreApplication::translate("SettingCameraDialog", "\343\202\253\343\203\241\343\203\251", nullptr));
        pushButtonSave->setText(QCoreApplication::translate("SettingCameraDialog", "\344\277\235\345\255\230", nullptr));
        pushButtonLoad->setText(QCoreApplication::translate("SettingCameraDialog", "\350\252\255\343\201\277\350\276\274\343\201\277", nullptr));
        checkBoxBrightness->setText(QString());
        checkBoxGamma->setText(QString());
        checkBoxVivid->setText(QString());
        checkBoxVividation->setText(QString());
        checkBoxColor->setText(QString());
        checkBoxGain->setText(QString());
        checkBoxReflection->setText(QString());
        checkBoxContrast->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class SettingCameraDialog: public Ui_SettingCameraDialog {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_SETTINGCAMERADIALOG_H
