#ifndef FILTERMULTICONVERTBRIGHTNESS_GLOBAL_H
#define FILTERMULTICONVERTBRIGHTNESS_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef FILTERMULTICONVERTBRIGHTNESS_LIB
# define FILTERMULTICONVERTBRIGHTNESS_EXPORT Q_DECL_EXPORT
#else
# define FILTERMULTICONVERTBRIGHTNESS_EXPORT Q_DECL_IMPORT
#endif

#endif // FILTERMULTICONVERTBRIGHTNESS_GLOBAL_H
