#ifndef LEDCONTROL16D_GLOBAL_H
#define LEDCONTROL16D_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef LEDCONTROL16D_LIB
# define LEDCONTROL16D_EXPORT Q_DECL_EXPORT
#else
# define LEDCONTROL16D_EXPORT Q_DECL_IMPORT
#endif

#endif // LEDCONTROL16D_GLOBAL_H
