# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = CheckDataValidation
DESTDIR = ../x64/Debug
CONFIG += debug
DEFINES += CHECKDATAVALIDATION_LIB
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += GeneratedFiles
RCC_DIR += GeneratedFiles
include(CheckDataValidation.pri)
