# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./AFVI_CommPLC.h \
    ./afvi_commplc_global.h
SOURCES += ../../../Open/SystemVersion.cpp \
    ./AFVI_CommPLC.cpp
