#ifndef COLORDIFFERENCEIMAGEPANEL_GLOBAL_H
#define COLORDIFFERENCEIMAGEPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef COLORDIFFERENCEIMAGEPANEL_LIB
# define COLORDIFFERENCEIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define COLORDIFFERENCEIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // COLORDIFFERENCEIMAGEPANEL_GLOBAL_H
