#ifndef LEDCONTROL16B_GLOBAL_H
#define LEDCONTROL16B_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef LEDCONTROL16B_LIB
# define LEDCONTROL16B_EXPORT Q_DECL_EXPORT
#else
# define LEDCONTROL16B_EXPORT Q_DECL_IMPORT
#endif

#endif // LEDCONTROL16B_GLOBAL_H
