#ifndef BUTTONTRANSFERPUSHGUI_GLOBAL_H
#define BUTTONTRANSFERPUSHGUI_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONTRANSFERPUSHGUI_LIB
# define BUTTONTRANSFERPUSHGUI_EXPORT Q_DECL_EXPORT
#else
# define BUTTONTRANSFERPUSHGUI_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONTRANSFERPUSHGUI_GLOBAL_H
