/********************************************************************************
** Form generated from reading UI file 'EditColorBlockLibrary.ui'
**
** Created by: Qt User Interface Compiler version 6.10.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_EDITCOLORBLOCKLIBRARY_H
#define UI_EDITCOLORBLOCKLIBRARY_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDialog>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QToolButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_EditColorBlockLibraryClass
{
public:
    QFrame *frameLibFolder;
    QTableWidget *tableWidgetLibList;
    QToolButton *toolButtonPickup;
    QToolButton *toolButtonInspect;
    QLineEdit *EditLibID;
    QLineEdit *EditLibName;
    QLabel *label_4;
    QStackedWidget *stackedWidget;
    QWidget *page_4;
    QFrame *frame_15;
    QSpinBox *EditMinBlockSize;
    QLabel *label_58;
    QSpinBox *EditMaxBlockSize;
    QLabel *label_59;
    QSpinBox *EditMinBlockDots;
    QLabel *label_60;
    QSpinBox *EditMaxBlockDots;
    QLabel *label_61;
    QLabel *label_62;
    QSpinBox *EditLimitBlockSize;
    QLabel *label_63;
    QFrame *frame_16;
    QLabel *label_64;
    QComboBox *comboBGenerationCategory;
    QCheckBox *checkBTransparent;
    QCheckBox *checkBLeftPickup;
    QCheckBox *checkBOverlappedGen;
    QFrame *frame_17;
    QTableWidget *tableWidgetSubtractLibList;
    QPushButton *ButtonDelSubtractLib_3;
    QPushButton *ButtonAddSubtractLib_3;
    QLabel *label_65;
    QFrame *frame_18;
    QLabel *label_68;
    QSpinBox *EditPickupGH;
    QLabel *label_66;
    QLabel *label_67;
    QSpinBox *EditPickupBL;
    QSpinBox *EditPickupRH;
    QSpinBox *EditPickupRL;
    QSpinBox *EditPickupBH;
    QLabel *label_94;
    QLabel *label_95;
    QSpinBox *EditPickupGL;
    QLabel *label_96;
    QFrame *frame_4;
    QLabel *label_14;
    QSpinBox *EditSpaceToOutline;
    QSpinBox *EditNoiseSize;
    QLabel *label_16;
    QSpinBox *EditPriority;
    QLabel *label_33;
    QLabel *label_48;
    QLabel *label_49;
    QSpinBox *EditNoiseSizePinHole;
    QWidget *page_5;
    QFrame *frame_23;
    QLabel *label_84;
    QFrame *frame_24;
    QLabel *label_85;
    QCheckBox *checkBModeOnlyMatching;
    QCheckBox *checkBModeAbsoluteBright;
    QCheckBox *checkBModeDiffer;
    QCheckBox *checkBModeCenterBrightFromParts;
    QCheckBox *checkBModeNGCluster;
    QCheckBox *checkBModeBlackMask;
    QCheckBox *checkBModeEnabled;
    QCheckBox *checkBModeWhiteMask;
    QFrame *frame_27;
    QLabel *label_90;
    QFrame *frame_28;
    QLabel *label_91;
    QSpinBox *EditSelfSearch;
    QLabel *label_92;
    QLabel *label_93;
    QCheckBox *checkBModeCommonMovable;
    QSpinBox *EditCommonMoveDot;
    QFrame *frame;
    QFrame *frame_25;
    QLabel *label_86;
    QFrame *frame_26;
    QLabel *label_87;
    QSpinBox *EditAdjustBlack;
    QCheckBox *checkBModeAdjustable;
    QSpinBox *EditAdjustWhite;
    QLabel *label_88;
    QLabel *label_89;
    QFrame *frame_20;
    QLabel *label_73;
    QLabel *label_74;
    QLabel *label_75;
    QSpinBox *EditNOKDotH;
    QLabel *label_76;
    QSpinBox *EditNBrightWidthL;
    QSpinBox *EditNOKDotL;
    QSpinBox *EditNBrightWidthH;
    QLabel *label_77;
    QSpinBox *EditNMinNGCountL;
    QSpinBox *EditNMinNGCountH;
    QLabel *label_30;
    QLabel *label_29;
    QSpinBox *EditNOKLengthH;
    QSpinBox *EditNOKLengthL;
    QFrame *frame_21;
    QLabel *label_78;
    QFrame *frame_22;
    QLabel *label_79;
    QLabel *label_80;
    QSpinBox *EditBOKDotH;
    QLabel *label_81;
    QSpinBox *EditBOKDotL;
    QSpinBox *EditBBrightWidthL;
    QLabel *label_82;
    QLabel *label_83;
    QSpinBox *EditBBrightWidthH;
    QSpinBox *EditBMinNGCountL;
    QSpinBox *EditBMinNGCountH;
    QLabel *label_31;
    QSpinBox *EditBOKLengthL;
    QSpinBox *EditBOKLengthH;
    QLabel *label_34;
    QToolButton *toolButtonR;
    QToolButton *toolButtonG;
    QToolButton *toolButtonB;
    QWidget *page_6;
    QPushButton *ButtonLibDelete;
    QPushButton *ButtonLibNew;
    QPushButton *pushButtonClose;
    QPushButton *ButtonLibSave;
    QPushButton *ButtonLibSaveNew;

    void setupUi(QDialog *EditColorBlockLibraryClass)
    {
        if (EditColorBlockLibraryClass->objectName().isEmpty())
            EditColorBlockLibraryClass->setObjectName("EditColorBlockLibraryClass");
        EditColorBlockLibraryClass->resize(619, 789);
        frameLibFolder = new QFrame(EditColorBlockLibraryClass);
        frameLibFolder->setObjectName("frameLibFolder");
        frameLibFolder->setGeometry(QRect(10, 60, 221, 201));
        frameLibFolder->setFrameShape(QFrame::StyledPanel);
        frameLibFolder->setFrameShadow(QFrame::Sunken);
        tableWidgetLibList = new QTableWidget(EditColorBlockLibraryClass);
        if (tableWidgetLibList->columnCount() < 2)
            tableWidgetLibList->setColumnCount(2);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        tableWidgetLibList->setHorizontalHeaderItem(0, __qtablewidgetitem);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        tableWidgetLibList->setHorizontalHeaderItem(1, __qtablewidgetitem1);
        tableWidgetLibList->setObjectName("tableWidgetLibList");
        tableWidgetLibList->setGeometry(QRect(10, 280, 221, 161));
        tableWidgetLibList->setSelectionMode(QAbstractItemView::SingleSelection);
        tableWidgetLibList->setSelectionBehavior(QAbstractItemView::SelectRows);
        toolButtonPickup = new QToolButton(EditColorBlockLibraryClass);
        toolButtonPickup->setObjectName("toolButtonPickup");
        toolButtonPickup->setGeometry(QRect(260, 10, 141, 31));
        toolButtonPickup->setCheckable(true);
        toolButtonPickup->setChecked(true);
        toolButtonPickup->setAutoExclusive(true);
        toolButtonInspect = new QToolButton(EditColorBlockLibraryClass);
        toolButtonInspect->setObjectName("toolButtonInspect");
        toolButtonInspect->setGeometry(QRect(460, 10, 141, 31));
        toolButtonInspect->setCheckable(true);
        toolButtonInspect->setAutoExclusive(true);
        EditLibID = new QLineEdit(EditColorBlockLibraryClass);
        EditLibID->setObjectName("EditLibID");
        EditLibID->setGeometry(QRect(320, 50, 81, 31));
        QFont font;
        font.setPointSize(12);
        EditLibID->setFont(font);
        EditLibID->setReadOnly(true);
        EditLibName = new QLineEdit(EditColorBlockLibraryClass);
        EditLibName->setObjectName("EditLibName");
        EditLibName->setGeometry(QRect(400, 50, 211, 31));
        EditLibName->setFont(font);
        label_4 = new QLabel(EditColorBlockLibraryClass);
        label_4->setObjectName("label_4");
        label_4->setGeometry(QRect(270, 50, 51, 31));
        label_4->setFont(font);
        label_4->setFrameShape(QFrame::Panel);
        label_4->setFrameShadow(QFrame::Sunken);
        label_4->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        stackedWidget = new QStackedWidget(EditColorBlockLibraryClass);
        stackedWidget->setObjectName("stackedWidget");
        stackedWidget->setGeometry(QRect(240, 90, 381, 611));
        page_4 = new QWidget();
        page_4->setObjectName("page_4");
        frame_15 = new QFrame(page_4);
        frame_15->setObjectName("frame_15");
        frame_15->setGeometry(QRect(0, 220, 371, 141));
        frame_15->setFrameShape(QFrame::StyledPanel);
        frame_15->setFrameShadow(QFrame::Sunken);
        EditMinBlockSize = new QSpinBox(frame_15);
        EditMinBlockSize->setObjectName("EditMinBlockSize");
        EditMinBlockSize->setGeometry(QRect(180, 10, 81, 22));
        EditMinBlockSize->setMaximum(1000000);
        label_58 = new QLabel(frame_15);
        label_58->setObjectName("label_58");
        label_58->setGeometry(QRect(50, 30, 111, 21));
        label_58->setFrameShape(QFrame::Panel);
        label_58->setFrameShadow(QFrame::Sunken);
        label_58->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditMaxBlockSize = new QSpinBox(frame_15);
        EditMaxBlockSize->setObjectName("EditMaxBlockSize");
        EditMaxBlockSize->setGeometry(QRect(180, 30, 81, 22));
        EditMaxBlockSize->setMaximum(1000000);
        label_59 = new QLabel(frame_15);
        label_59->setObjectName("label_59");
        label_59->setGeometry(QRect(50, 10, 111, 21));
        label_59->setFrameShape(QFrame::Panel);
        label_59->setFrameShadow(QFrame::Sunken);
        label_59->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditMinBlockDots = new QSpinBox(frame_15);
        EditMinBlockDots->setObjectName("EditMinBlockDots");
        EditMinBlockDots->setGeometry(QRect(180, 60, 101, 22));
        EditMinBlockDots->setMaximum(2000000000);
        label_60 = new QLabel(frame_15);
        label_60->setObjectName("label_60");
        label_60->setGeometry(QRect(50, 60, 111, 21));
        label_60->setFrameShape(QFrame::Panel);
        label_60->setFrameShadow(QFrame::Sunken);
        label_60->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditMaxBlockDots = new QSpinBox(frame_15);
        EditMaxBlockDots->setObjectName("EditMaxBlockDots");
        EditMaxBlockDots->setGeometry(QRect(180, 80, 101, 22));
        EditMaxBlockDots->setMaximum(2000000000);
        EditMaxBlockDots->setValue(2000000000);
        label_61 = new QLabel(frame_15);
        label_61->setObjectName("label_61");
        label_61->setGeometry(QRect(50, 80, 111, 21));
        label_61->setFrameShape(QFrame::Panel);
        label_61->setFrameShadow(QFrame::Sunken);
        label_61->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_62 = new QLabel(frame_15);
        label_62->setObjectName("label_62");
        label_62->setGeometry(QRect(50, 110, 111, 21));
        label_62->setFrameShape(QFrame::Panel);
        label_62->setFrameShadow(QFrame::Sunken);
        label_62->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditLimitBlockSize = new QSpinBox(frame_15);
        EditLimitBlockSize->setObjectName("EditLimitBlockSize");
        EditLimitBlockSize->setGeometry(QRect(180, 110, 61, 22));
        EditLimitBlockSize->setMaximum(99999);
        label_63 = new QLabel(frame_15);
        label_63->setObjectName("label_63");
        label_63->setGeometry(QRect(0, 0, 31, 141));
        label_63->setFrameShape(QFrame::Panel);
        label_63->setFrameShadow(QFrame::Raised);
        label_63->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_63->setIndent(1);
        frame_16 = new QFrame(page_4);
        frame_16->setObjectName("frame_16");
        frame_16->setGeometry(QRect(0, 480, 371, 71));
        frame_16->setFrameShape(QFrame::StyledPanel);
        frame_16->setFrameShadow(QFrame::Sunken);
        label_64 = new QLabel(frame_16);
        label_64->setObjectName("label_64");
        label_64->setGeometry(QRect(0, 0, 31, 71));
        label_64->setFrameShape(QFrame::Panel);
        label_64->setFrameShadow(QFrame::Raised);
        label_64->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_64->setIndent(1);
        comboBGenerationCategory = new QComboBox(frame_16);
        comboBGenerationCategory->addItem(QString());
        comboBGenerationCategory->addItem(QString());
        comboBGenerationCategory->addItem(QString());
        comboBGenerationCategory->addItem(QString());
        comboBGenerationCategory->addItem(QString());
        comboBGenerationCategory->addItem(QString());
        comboBGenerationCategory->addItem(QString());
        comboBGenerationCategory->addItem(QString());
        comboBGenerationCategory->setObjectName("comboBGenerationCategory");
        comboBGenerationCategory->setGeometry(QRect(50, 10, 111, 22));
        checkBTransparent = new QCheckBox(frame_16);
        checkBTransparent->setObjectName("checkBTransparent");
        checkBTransparent->setGeometry(QRect(180, 10, 161, 18));
        checkBLeftPickup = new QCheckBox(frame_16);
        checkBLeftPickup->setObjectName("checkBLeftPickup");
        checkBLeftPickup->setGeometry(QRect(180, 30, 161, 18));
        checkBOverlappedGen = new QCheckBox(frame_16);
        checkBOverlappedGen->setObjectName("checkBOverlappedGen");
        checkBOverlappedGen->setGeometry(QRect(180, 50, 161, 18));
        frame_17 = new QFrame(page_4);
        frame_17->setObjectName("frame_17");
        frame_17->setGeometry(QRect(0, 0, 371, 121));
        frame_17->setFrameShape(QFrame::StyledPanel);
        frame_17->setFrameShadow(QFrame::Sunken);
        tableWidgetSubtractLibList = new QTableWidget(frame_17);
        if (tableWidgetSubtractLibList->columnCount() < 2)
            tableWidgetSubtractLibList->setColumnCount(2);
        QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
        tableWidgetSubtractLibList->setHorizontalHeaderItem(0, __qtablewidgetitem2);
        QTableWidgetItem *__qtablewidgetitem3 = new QTableWidgetItem();
        tableWidgetSubtractLibList->setHorizontalHeaderItem(1, __qtablewidgetitem3);
        tableWidgetSubtractLibList->setObjectName("tableWidgetSubtractLibList");
        tableWidgetSubtractLibList->setGeometry(QRect(60, 10, 191, 101));
        tableWidgetSubtractLibList->setSelectionMode(QAbstractItemView::SingleSelection);
        tableWidgetSubtractLibList->setSelectionBehavior(QAbstractItemView::SelectRows);
        ButtonDelSubtractLib_3 = new QPushButton(frame_17);
        ButtonDelSubtractLib_3->setObjectName("ButtonDelSubtractLib_3");
        ButtonDelSubtractLib_3->setGeometry(QRect(260, 60, 101, 31));
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/Qtres/Delete.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        ButtonDelSubtractLib_3->setIcon(icon);
        ButtonAddSubtractLib_3 = new QPushButton(frame_17);
        ButtonAddSubtractLib_3->setObjectName("ButtonAddSubtractLib_3");
        ButtonAddSubtractLib_3->setGeometry(QRect(260, 20, 101, 31));
        QIcon icon1;
        icon1.addFile(QString::fromUtf8(":/Qtres/Add.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        ButtonAddSubtractLib_3->setIcon(icon1);
        label_65 = new QLabel(frame_17);
        label_65->setObjectName("label_65");
        label_65->setGeometry(QRect(0, 0, 31, 121));
        label_65->setFrameShape(QFrame::Panel);
        label_65->setFrameShadow(QFrame::Raised);
        label_65->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_65->setIndent(1);
        frame_18 = new QFrame(page_4);
        frame_18->setObjectName("frame_18");
        frame_18->setGeometry(QRect(0, 130, 371, 81));
        frame_18->setFrameShape(QFrame::StyledPanel);
        frame_18->setFrameShadow(QFrame::Sunken);
        label_68 = new QLabel(frame_18);
        label_68->setObjectName("label_68");
        label_68->setGeometry(QRect(0, 0, 31, 81));
        label_68->setFrameShape(QFrame::Panel);
        label_68->setFrameShadow(QFrame::Raised);
        label_68->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_68->setIndent(1);
        EditPickupGH = new QSpinBox(frame_18);
        EditPickupGH->setObjectName("EditPickupGH");
        EditPickupGH->setGeometry(QRect(230, 50, 61, 22));
        EditPickupGH->setMaximum(255);
        label_66 = new QLabel(frame_18);
        label_66->setObjectName("label_66");
        label_66->setGeometry(QRect(160, 10, 61, 21));
        label_66->setFrameShape(QFrame::Panel);
        label_66->setFrameShadow(QFrame::Sunken);
        label_66->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_67 = new QLabel(frame_18);
        label_67->setObjectName("label_67");
        label_67->setGeometry(QRect(300, 10, 61, 21));
        label_67->setFrameShape(QFrame::Panel);
        label_67->setFrameShadow(QFrame::Sunken);
        label_67->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditPickupBL = new QSpinBox(frame_18);
        EditPickupBL->setObjectName("EditPickupBL");
        EditPickupBL->setGeometry(QRect(300, 30, 61, 22));
        EditPickupBL->setMaximum(255);
        EditPickupRH = new QSpinBox(frame_18);
        EditPickupRH->setObjectName("EditPickupRH");
        EditPickupRH->setGeometry(QRect(160, 50, 61, 22));
        EditPickupRH->setMaximum(255);
        EditPickupRL = new QSpinBox(frame_18);
        EditPickupRL->setObjectName("EditPickupRL");
        EditPickupRL->setGeometry(QRect(160, 30, 61, 22));
        EditPickupRL->setMaximum(255);
        EditPickupBH = new QSpinBox(frame_18);
        EditPickupBH->setObjectName("EditPickupBH");
        EditPickupBH->setGeometry(QRect(300, 50, 61, 22));
        EditPickupBH->setMaximum(255);
        label_94 = new QLabel(frame_18);
        label_94->setObjectName("label_94");
        label_94->setGeometry(QRect(50, 30, 101, 21));
        label_94->setFrameShape(QFrame::Panel);
        label_94->setFrameShadow(QFrame::Sunken);
        label_94->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_95 = new QLabel(frame_18);
        label_95->setObjectName("label_95");
        label_95->setGeometry(QRect(50, 50, 101, 21));
        label_95->setFrameShape(QFrame::Panel);
        label_95->setFrameShadow(QFrame::Sunken);
        label_95->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditPickupGL = new QSpinBox(frame_18);
        EditPickupGL->setObjectName("EditPickupGL");
        EditPickupGL->setGeometry(QRect(230, 30, 61, 22));
        EditPickupGL->setMaximum(255);
        label_96 = new QLabel(frame_18);
        label_96->setObjectName("label_96");
        label_96->setGeometry(QRect(230, 10, 61, 21));
        label_96->setFrameShape(QFrame::Panel);
        label_96->setFrameShadow(QFrame::Sunken);
        label_96->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        frame_4 = new QFrame(page_4);
        frame_4->setObjectName("frame_4");
        frame_4->setGeometry(QRect(0, 370, 371, 101));
        frame_4->setFrameShape(QFrame::StyledPanel);
        frame_4->setFrameShadow(QFrame::Sunken);
        label_14 = new QLabel(frame_4);
        label_14->setObjectName("label_14");
        label_14->setGeometry(QRect(60, 10, 171, 21));
        label_14->setFrameShape(QFrame::Panel);
        label_14->setFrameShadow(QFrame::Sunken);
        label_14->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditSpaceToOutline = new QSpinBox(frame_4);
        EditSpaceToOutline->setObjectName("EditSpaceToOutline");
        EditSpaceToOutline->setGeometry(QRect(240, 10, 61, 23));
        EditNoiseSize = new QSpinBox(frame_4);
        EditNoiseSize->setObjectName("EditNoiseSize");
        EditNoiseSize->setGeometry(QRect(240, 30, 61, 23));
        QFont font1;
        font1.setPointSize(9);
        EditNoiseSize->setFont(font1);
        label_16 = new QLabel(frame_4);
        label_16->setObjectName("label_16");
        label_16->setGeometry(QRect(60, 70, 171, 21));
        label_16->setFrameShape(QFrame::Panel);
        label_16->setFrameShadow(QFrame::Sunken);
        label_16->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditPriority = new QSpinBox(frame_4);
        EditPriority->setObjectName("EditPriority");
        EditPriority->setGeometry(QRect(240, 70, 61, 23));
        EditPriority->setFont(font1);
        label_33 = new QLabel(frame_4);
        label_33->setObjectName("label_33");
        label_33->setGeometry(QRect(0, 0, 31, 101));
        label_33->setFrameShape(QFrame::Panel);
        label_33->setFrameShadow(QFrame::Raised);
        label_33->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_33->setIndent(1);
        label_48 = new QLabel(frame_4);
        label_48->setObjectName("label_48");
        label_48->setGeometry(QRect(60, 50, 171, 21));
        label_48->setFrameShape(QFrame::Panel);
        label_48->setFrameShadow(QFrame::Sunken);
        label_48->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_49 = new QLabel(frame_4);
        label_49->setObjectName("label_49");
        label_49->setGeometry(QRect(60, 30, 171, 21));
        label_49->setFrameShape(QFrame::Panel);
        label_49->setFrameShadow(QFrame::Sunken);
        label_49->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditNoiseSizePinHole = new QSpinBox(frame_4);
        EditNoiseSizePinHole->setObjectName("EditNoiseSizePinHole");
        EditNoiseSizePinHole->setGeometry(QRect(240, 50, 61, 23));
        EditNoiseSizePinHole->setFont(font1);
        stackedWidget->addWidget(page_4);
        page_5 = new QWidget();
        page_5->setObjectName("page_5");
        frame_23 = new QFrame(page_5);
        frame_23->setObjectName("frame_23");
        frame_23->setGeometry(QRect(0, 430, 371, 91));
        frame_23->setFrameShape(QFrame::StyledPanel);
        frame_23->setFrameShadow(QFrame::Sunken);
        label_84 = new QLabel(frame_23);
        label_84->setObjectName("label_84");
        label_84->setGeometry(QRect(0, 0, 31, 91));
        label_84->setFrameShape(QFrame::Panel);
        label_84->setFrameShadow(QFrame::Raised);
        label_84->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_84->setIndent(1);
        frame_24 = new QFrame(frame_23);
        frame_24->setObjectName("frame_24");
        frame_24->setGeometry(QRect(10, 120, 371, 101));
        frame_24->setFrameShape(QFrame::StyledPanel);
        frame_24->setFrameShadow(QFrame::Sunken);
        label_85 = new QLabel(frame_24);
        label_85->setObjectName("label_85");
        label_85->setGeometry(QRect(0, 0, 20, 61));
        label_85->setFrameShape(QFrame::Panel);
        label_85->setFrameShadow(QFrame::Raised);
        label_85->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_85->setIndent(1);
        checkBModeOnlyMatching = new QCheckBox(frame_23);
        checkBModeOnlyMatching->setObjectName("checkBModeOnlyMatching");
        checkBModeOnlyMatching->setGeometry(QRect(200, 10, 141, 18));
        checkBModeAbsoluteBright = new QCheckBox(frame_23);
        checkBModeAbsoluteBright->setObjectName("checkBModeAbsoluteBright");
        checkBModeAbsoluteBright->setGeometry(QRect(50, 30, 141, 18));
        checkBModeDiffer = new QCheckBox(frame_23);
        checkBModeDiffer->setObjectName("checkBModeDiffer");
        checkBModeDiffer->setGeometry(QRect(50, 70, 141, 18));
        checkBModeCenterBrightFromParts = new QCheckBox(frame_23);
        checkBModeCenterBrightFromParts->setObjectName("checkBModeCenterBrightFromParts");
        checkBModeCenterBrightFromParts->setGeometry(QRect(200, 70, 141, 18));
        checkBModeNGCluster = new QCheckBox(frame_23);
        checkBModeNGCluster->setObjectName("checkBModeNGCluster");
        checkBModeNGCluster->setGeometry(QRect(50, 50, 141, 18));
        checkBModeBlackMask = new QCheckBox(frame_23);
        checkBModeBlackMask->setObjectName("checkBModeBlackMask");
        checkBModeBlackMask->setGeometry(QRect(200, 50, 141, 18));
        checkBModeEnabled = new QCheckBox(frame_23);
        checkBModeEnabled->setObjectName("checkBModeEnabled");
        checkBModeEnabled->setGeometry(QRect(50, 10, 141, 18));
        checkBModeWhiteMask = new QCheckBox(frame_23);
        checkBModeWhiteMask->setObjectName("checkBModeWhiteMask");
        checkBModeWhiteMask->setGeometry(QRect(200, 30, 141, 18));
        frame_27 = new QFrame(page_5);
        frame_27->setObjectName("frame_27");
        frame_27->setGeometry(QRect(0, 530, 371, 81));
        frame_27->setFrameShape(QFrame::StyledPanel);
        frame_27->setFrameShadow(QFrame::Sunken);
        label_90 = new QLabel(frame_27);
        label_90->setObjectName("label_90");
        label_90->setGeometry(QRect(0, 0, 31, 81));
        label_90->setFrameShape(QFrame::Panel);
        label_90->setFrameShadow(QFrame::Raised);
        label_90->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_90->setIndent(1);
        frame_28 = new QFrame(frame_27);
        frame_28->setObjectName("frame_28");
        frame_28->setGeometry(QRect(10, 120, 371, 101));
        frame_28->setFrameShape(QFrame::StyledPanel);
        frame_28->setFrameShadow(QFrame::Sunken);
        label_91 = new QLabel(frame_28);
        label_91->setObjectName("label_91");
        label_91->setGeometry(QRect(0, 0, 20, 61));
        label_91->setFrameShape(QFrame::Panel);
        label_91->setFrameShadow(QFrame::Raised);
        label_91->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_91->setIndent(1);
        EditSelfSearch = new QSpinBox(frame_27);
        EditSelfSearch->setObjectName("EditSelfSearch");
        EditSelfSearch->setGeometry(QRect(260, 30, 81, 22));
        label_92 = new QLabel(frame_27);
        label_92->setObjectName("label_92");
        label_92->setGeometry(QRect(50, 30, 201, 21));
        label_92->setFrameShape(QFrame::Panel);
        label_92->setFrameShadow(QFrame::Sunken);
        label_92->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_93 = new QLabel(frame_27);
        label_93->setObjectName("label_93");
        label_93->setGeometry(QRect(50, 50, 201, 21));
        label_93->setFrameShape(QFrame::Panel);
        label_93->setFrameShadow(QFrame::Sunken);
        label_93->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        checkBModeCommonMovable = new QCheckBox(frame_27);
        checkBModeCommonMovable->setObjectName("checkBModeCommonMovable");
        checkBModeCommonMovable->setGeometry(QRect(80, 10, 231, 18));
        EditCommonMoveDot = new QSpinBox(frame_27);
        EditCommonMoveDot->setObjectName("EditCommonMoveDot");
        EditCommonMoveDot->setGeometry(QRect(260, 50, 81, 22));
        frame = new QFrame(page_5);
        frame->setObjectName("frame");
        frame->setGeometry(QRect(0, 0, 371, 421));
        frame->setFrameShape(QFrame::Panel);
        frame->setFrameShadow(QFrame::Sunken);
        frame_25 = new QFrame(frame);
        frame_25->setObjectName("frame_25");
        frame_25->setGeometry(QRect(10, 310, 351, 101));
        frame_25->setFrameShape(QFrame::StyledPanel);
        frame_25->setFrameShadow(QFrame::Sunken);
        label_86 = new QLabel(frame_25);
        label_86->setObjectName("label_86");
        label_86->setGeometry(QRect(0, 0, 31, 101));
        label_86->setFrameShape(QFrame::Panel);
        label_86->setFrameShadow(QFrame::Raised);
        label_86->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_86->setIndent(1);
        frame_26 = new QFrame(frame_25);
        frame_26->setObjectName("frame_26");
        frame_26->setGeometry(QRect(10, 120, 371, 101));
        frame_26->setFrameShape(QFrame::StyledPanel);
        frame_26->setFrameShadow(QFrame::Sunken);
        label_87 = new QLabel(frame_26);
        label_87->setObjectName("label_87");
        label_87->setGeometry(QRect(0, 0, 20, 61));
        label_87->setFrameShape(QFrame::Panel);
        label_87->setFrameShadow(QFrame::Raised);
        label_87->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_87->setIndent(1);
        EditAdjustBlack = new QSpinBox(frame_25);
        EditAdjustBlack->setObjectName("EditAdjustBlack");
        EditAdjustBlack->setGeometry(QRect(250, 40, 81, 22));
        EditAdjustBlack->setMaximum(255);
        checkBModeAdjustable = new QCheckBox(frame_25);
        checkBModeAdjustable->setObjectName("checkBModeAdjustable");
        checkBModeAdjustable->setGeometry(QRect(50, 10, 241, 18));
        EditAdjustWhite = new QSpinBox(frame_25);
        EditAdjustWhite->setObjectName("EditAdjustWhite");
        EditAdjustWhite->setGeometry(QRect(250, 70, 81, 22));
        EditAdjustWhite->setMaximum(255);
        label_88 = new QLabel(frame_25);
        label_88->setObjectName("label_88");
        label_88->setGeometry(QRect(40, 70, 201, 21));
        label_88->setFrameShape(QFrame::Panel);
        label_88->setFrameShadow(QFrame::Sunken);
        label_88->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_89 = new QLabel(frame_25);
        label_89->setObjectName("label_89");
        label_89->setGeometry(QRect(40, 40, 201, 21));
        label_89->setFrameShape(QFrame::Panel);
        label_89->setFrameShadow(QFrame::Sunken);
        label_89->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        frame_20 = new QFrame(frame);
        frame_20->setObjectName("frame_20");
        frame_20->setGeometry(QRect(10, 50, 351, 121));
        frame_20->setFrameShape(QFrame::StyledPanel);
        frame_20->setFrameShadow(QFrame::Sunken);
        label_73 = new QLabel(frame_20);
        label_73->setObjectName("label_73");
        label_73->setGeometry(QRect(0, 0, 31, 121));
        label_73->setFrameShape(QFrame::Panel);
        label_73->setFrameShadow(QFrame::Raised);
        label_73->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_73->setIndent(1);
        label_74 = new QLabel(frame_20);
        label_74->setObjectName("label_74");
        label_74->setGeometry(QRect(260, 10, 81, 21));
        label_74->setFrameShape(QFrame::Panel);
        label_74->setFrameShadow(QFrame::Sunken);
        label_74->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_75 = new QLabel(frame_20);
        label_75->setObjectName("label_75");
        label_75->setGeometry(QRect(40, 30, 121, 21));
        label_75->setFrameShape(QFrame::Panel);
        label_75->setFrameShadow(QFrame::Sunken);
        label_75->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditNOKDotH = new QSpinBox(frame_20);
        EditNOKDotH->setObjectName("EditNOKDotH");
        EditNOKDotH->setGeometry(QRect(260, 50, 81, 22));
        EditNOKDotH->setMaximum(99999999);
        label_76 = new QLabel(frame_20);
        label_76->setObjectName("label_76");
        label_76->setGeometry(QRect(40, 50, 121, 21));
        label_76->setFrameShape(QFrame::Panel);
        label_76->setFrameShadow(QFrame::Sunken);
        label_76->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditNBrightWidthL = new QSpinBox(frame_20);
        EditNBrightWidthL->setObjectName("EditNBrightWidthL");
        EditNBrightWidthL->setGeometry(QRect(170, 30, 81, 22));
        EditNBrightWidthL->setMaximum(255);
        EditNOKDotL = new QSpinBox(frame_20);
        EditNOKDotL->setObjectName("EditNOKDotL");
        EditNOKDotL->setGeometry(QRect(170, 50, 81, 22));
        EditNOKDotL->setMaximum(99999999);
        EditNBrightWidthH = new QSpinBox(frame_20);
        EditNBrightWidthH->setObjectName("EditNBrightWidthH");
        EditNBrightWidthH->setGeometry(QRect(260, 30, 81, 22));
        EditNBrightWidthH->setMaximum(255);
        label_77 = new QLabel(frame_20);
        label_77->setObjectName("label_77");
        label_77->setGeometry(QRect(170, 10, 81, 21));
        label_77->setFrameShape(QFrame::Panel);
        label_77->setFrameShadow(QFrame::Sunken);
        label_77->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditNMinNGCountL = new QSpinBox(frame_20);
        EditNMinNGCountL->setObjectName("EditNMinNGCountL");
        EditNMinNGCountL->setGeometry(QRect(170, 90, 81, 22));
        EditNMinNGCountL->setMaximum(99999999);
        EditNMinNGCountH = new QSpinBox(frame_20);
        EditNMinNGCountH->setObjectName("EditNMinNGCountH");
        EditNMinNGCountH->setGeometry(QRect(260, 90, 81, 22));
        EditNMinNGCountH->setMaximum(99999999);
        label_30 = new QLabel(frame_20);
        label_30->setObjectName("label_30");
        label_30->setGeometry(QRect(40, 90, 121, 21));
        label_30->setFrameShape(QFrame::Panel);
        label_30->setFrameShadow(QFrame::Sunken);
        label_30->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_29 = new QLabel(frame_20);
        label_29->setObjectName("label_29");
        label_29->setGeometry(QRect(40, 70, 121, 21));
        label_29->setFrameShape(QFrame::Panel);
        label_29->setFrameShadow(QFrame::Sunken);
        label_29->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditNOKLengthH = new QSpinBox(frame_20);
        EditNOKLengthH->setObjectName("EditNOKLengthH");
        EditNOKLengthH->setGeometry(QRect(260, 70, 81, 22));
        EditNOKLengthH->setMaximum(99999999);
        EditNOKLengthL = new QSpinBox(frame_20);
        EditNOKLengthL->setObjectName("EditNOKLengthL");
        EditNOKLengthL->setGeometry(QRect(170, 70, 81, 22));
        EditNOKLengthL->setMaximum(99999999);
        frame_21 = new QFrame(frame);
        frame_21->setObjectName("frame_21");
        frame_21->setGeometry(QRect(10, 180, 351, 121));
        frame_21->setFrameShape(QFrame::StyledPanel);
        frame_21->setFrameShadow(QFrame::Sunken);
        label_78 = new QLabel(frame_21);
        label_78->setObjectName("label_78");
        label_78->setGeometry(QRect(0, 0, 31, 121));
        label_78->setFrameShape(QFrame::Panel);
        label_78->setFrameShadow(QFrame::Raised);
        label_78->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_78->setIndent(1);
        frame_22 = new QFrame(frame_21);
        frame_22->setObjectName("frame_22");
        frame_22->setGeometry(QRect(10, 120, 371, 101));
        frame_22->setFrameShape(QFrame::StyledPanel);
        frame_22->setFrameShadow(QFrame::Sunken);
        label_79 = new QLabel(frame_22);
        label_79->setObjectName("label_79");
        label_79->setGeometry(QRect(0, 0, 20, 61));
        label_79->setFrameShape(QFrame::Panel);
        label_79->setFrameShadow(QFrame::Raised);
        label_79->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_79->setIndent(1);
        label_80 = new QLabel(frame_21);
        label_80->setObjectName("label_80");
        label_80->setGeometry(QRect(40, 30, 121, 21));
        label_80->setFrameShape(QFrame::Panel);
        label_80->setFrameShadow(QFrame::Sunken);
        label_80->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditBOKDotH = new QSpinBox(frame_21);
        EditBOKDotH->setObjectName("EditBOKDotH");
        EditBOKDotH->setGeometry(QRect(260, 50, 81, 22));
        EditBOKDotH->setMaximum(99999999);
        label_81 = new QLabel(frame_21);
        label_81->setObjectName("label_81");
        label_81->setGeometry(QRect(260, 10, 81, 21));
        label_81->setFrameShape(QFrame::Panel);
        label_81->setFrameShadow(QFrame::Sunken);
        label_81->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditBOKDotL = new QSpinBox(frame_21);
        EditBOKDotL->setObjectName("EditBOKDotL");
        EditBOKDotL->setGeometry(QRect(170, 50, 81, 22));
        EditBOKDotL->setMaximum(99999999);
        EditBBrightWidthL = new QSpinBox(frame_21);
        EditBBrightWidthL->setObjectName("EditBBrightWidthL");
        EditBBrightWidthL->setGeometry(QRect(170, 30, 81, 22));
        EditBBrightWidthL->setMaximum(255);
        label_82 = new QLabel(frame_21);
        label_82->setObjectName("label_82");
        label_82->setGeometry(QRect(40, 50, 121, 21));
        label_82->setFrameShape(QFrame::Panel);
        label_82->setFrameShadow(QFrame::Sunken);
        label_82->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_83 = new QLabel(frame_21);
        label_83->setObjectName("label_83");
        label_83->setGeometry(QRect(170, 10, 81, 21));
        label_83->setFrameShape(QFrame::Panel);
        label_83->setFrameShadow(QFrame::Sunken);
        label_83->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditBBrightWidthH = new QSpinBox(frame_21);
        EditBBrightWidthH->setObjectName("EditBBrightWidthH");
        EditBBrightWidthH->setGeometry(QRect(260, 30, 81, 22));
        EditBBrightWidthH->setMaximum(255);
        EditBMinNGCountL = new QSpinBox(frame_21);
        EditBMinNGCountL->setObjectName("EditBMinNGCountL");
        EditBMinNGCountL->setGeometry(QRect(170, 90, 81, 22));
        EditBMinNGCountL->setMaximum(99999999);
        EditBMinNGCountH = new QSpinBox(frame_21);
        EditBMinNGCountH->setObjectName("EditBMinNGCountH");
        EditBMinNGCountH->setGeometry(QRect(260, 90, 81, 22));
        EditBMinNGCountH->setMaximum(99999999);
        label_31 = new QLabel(frame_21);
        label_31->setObjectName("label_31");
        label_31->setGeometry(QRect(40, 90, 121, 21));
        label_31->setFrameShape(QFrame::Panel);
        label_31->setFrameShadow(QFrame::Sunken);
        label_31->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditBOKLengthL = new QSpinBox(frame_21);
        EditBOKLengthL->setObjectName("EditBOKLengthL");
        EditBOKLengthL->setGeometry(QRect(170, 70, 81, 22));
        EditBOKLengthL->setMaximum(99999999);
        EditBOKLengthH = new QSpinBox(frame_21);
        EditBOKLengthH->setObjectName("EditBOKLengthH");
        EditBOKLengthH->setGeometry(QRect(260, 70, 81, 22));
        EditBOKLengthH->setMaximum(99999999);
        label_34 = new QLabel(frame_21);
        label_34->setObjectName("label_34");
        label_34->setGeometry(QRect(40, 70, 121, 21));
        label_34->setFrameShape(QFrame::Panel);
        label_34->setFrameShadow(QFrame::Sunken);
        label_34->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        toolButtonR = new QToolButton(frame);
        toolButtonR->setObjectName("toolButtonR");
        toolButtonR->setGeometry(QRect(10, 10, 111, 31));
        toolButtonR->setCheckable(true);
        toolButtonR->setChecked(true);
        toolButtonR->setAutoExclusive(true);
        toolButtonG = new QToolButton(frame);
        toolButtonG->setObjectName("toolButtonG");
        toolButtonG->setGeometry(QRect(130, 10, 111, 31));
        toolButtonG->setCheckable(true);
        toolButtonG->setChecked(false);
        toolButtonG->setAutoExclusive(true);
        toolButtonB = new QToolButton(frame);
        toolButtonB->setObjectName("toolButtonB");
        toolButtonB->setGeometry(QRect(250, 10, 111, 31));
        toolButtonB->setCheckable(true);
        toolButtonB->setAutoExclusive(true);
        stackedWidget->addWidget(page_5);
        page_6 = new QWidget();
        page_6->setObjectName("page_6");
        stackedWidget->addWidget(page_6);
        ButtonLibDelete = new QPushButton(EditColorBlockLibraryClass);
        ButtonLibDelete->setObjectName("ButtonLibDelete");
        ButtonLibDelete->setGeometry(QRect(340, 710, 81, 31));
        QFont font2;
        font2.setPointSize(11);
        ButtonLibDelete->setFont(font2);
        ButtonLibDelete->setIcon(icon);
        ButtonLibNew = new QPushButton(EditColorBlockLibraryClass);
        ButtonLibNew->setObjectName("ButtonLibNew");
        ButtonLibNew->setGeometry(QRect(240, 710, 91, 31));
        ButtonLibNew->setFont(font2);
        QIcon icon2;
        icon2.addFile(QString::fromUtf8(":/Qtres/ClearNew.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        ButtonLibNew->setIcon(icon2);
        pushButtonClose = new QPushButton(EditColorBlockLibraryClass);
        pushButtonClose->setObjectName("pushButtonClose");
        pushButtonClose->setGeometry(QRect(530, 750, 81, 31));
        pushButtonClose->setFont(font2);
        QIcon icon3;
        icon3.addFile(QString::fromUtf8(":/Qtres/Close.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        pushButtonClose->setIcon(icon3);
        ButtonLibSave = new QPushButton(EditColorBlockLibraryClass);
        ButtonLibSave->setObjectName("ButtonLibSave");
        ButtonLibSave->setGeometry(QRect(530, 710, 81, 31));
        ButtonLibSave->setFont(font2);
        QIcon icon4;
        icon4.addFile(QString::fromUtf8(":/Qtres/Update.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        ButtonLibSave->setIcon(icon4);
        ButtonLibSaveNew = new QPushButton(EditColorBlockLibraryClass);
        ButtonLibSaveNew->setObjectName("ButtonLibSaveNew");
        ButtonLibSaveNew->setGeometry(QRect(430, 710, 91, 31));
        ButtonLibSaveNew->setFont(font2);
        QIcon icon5;
        icon5.addFile(QString::fromUtf8(":/Qtres/SaveNew.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        ButtonLibSaveNew->setIcon(icon5);

        retranslateUi(EditColorBlockLibraryClass);

        stackedWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(EditColorBlockLibraryClass);
    } // setupUi

    void retranslateUi(QDialog *EditColorBlockLibraryClass)
    {
        EditColorBlockLibraryClass->setWindowTitle(QCoreApplication::translate("EditColorBlockLibraryClass", "EditColorBlockLibrary", nullptr));
        QTableWidgetItem *___qtablewidgetitem = tableWidgetLibList->horizontalHeaderItem(0);
        ___qtablewidgetitem->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "ID", nullptr));
        QTableWidgetItem *___qtablewidgetitem1 = tableWidgetLibList->horizontalHeaderItem(1);
        ___qtablewidgetitem1->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "Name", nullptr));
        toolButtonPickup->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\347\224\237\346\210\220", nullptr));
        toolButtonInspect->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\346\244\234\346\237\273", nullptr));
        EditLibID->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "12345", nullptr));
        EditLibName->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "Library Name", nullptr));
        label_4->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\345\220\215\347\247\260", nullptr));
        label_58->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\343\203\226\343\203\255\343\203\203\343\202\257\346\234\200\345\244\247\343\202\265\343\202\244\343\202\272", nullptr));
        label_59->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\343\203\226\343\203\255\343\203\203\343\202\257\346\234\200\345\260\217\343\202\265\343\202\244\343\202\272", nullptr));
        label_60->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\343\203\226\343\203\255\343\203\203\343\202\257\346\234\200\345\260\217\351\235\242\347\251\215", nullptr));
        label_61->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\343\203\226\343\203\255\343\203\203\343\202\257\346\234\200\345\244\247\351\235\242\347\251\215", nullptr));
        label_62->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\351\231\220\347\225\214\343\202\265\343\202\244\343\202\272", nullptr));
        label_63->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\343\202\265\n"
"\343\202\244\n"
"\343\202\272", nullptr));
        label_64->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\343\201\235\n"
"\343\201\256\n"
"\344\273\226", nullptr));
        comboBGenerationCategory->setItemText(0, QCoreApplication::translate("EditColorBlockLibraryClass", "Pad", nullptr));
        comboBGenerationCategory->setItemText(1, QCoreApplication::translate("EditColorBlockLibraryClass", "Hole", nullptr));
        comboBGenerationCategory->setItemText(2, QCoreApplication::translate("EditColorBlockLibraryClass", "Silk", nullptr));
        comboBGenerationCategory->setItemText(3, QCoreApplication::translate("EditColorBlockLibraryClass", "Resist", nullptr));
        comboBGenerationCategory->setItemText(4, QCoreApplication::translate("EditColorBlockLibraryClass", "OtherMask", nullptr));
        comboBGenerationCategory->setItemText(5, QCoreApplication::translate("EditColorBlockLibraryClass", "FinePad", nullptr));
        comboBGenerationCategory->setItemText(6, QCoreApplication::translate("EditColorBlockLibraryClass", "Surround", nullptr));
        comboBGenerationCategory->setItemText(7, QCoreApplication::translate("EditColorBlockLibraryClass", "Any", nullptr));

        checkBTransparent->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\346\216\222\344\273\226\347\224\237\346\210\220", nullptr));
        checkBLeftPickup->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\346\256\213\343\202\250\343\203\252\343\202\242", nullptr));
        checkBOverlappedGen->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\351\207\215\350\244\207\347\224\237\346\210\220", nullptr));
        QTableWidgetItem *___qtablewidgetitem2 = tableWidgetSubtractLibList->horizontalHeaderItem(0);
        ___qtablewidgetitem2->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "ID", nullptr));
        QTableWidgetItem *___qtablewidgetitem3 = tableWidgetSubtractLibList->horizontalHeaderItem(1);
        ___qtablewidgetitem3->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "Name", nullptr));
        ButtonDelSubtractLib_3->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\345\211\212\351\231\244", nullptr));
        ButtonAddSubtractLib_3->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\350\277\275\345\212\240", nullptr));
        label_65->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\351\231\244\n"
"\345\216\273", nullptr));
        label_68->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\350\274\235\n"
"\345\272\246", nullptr));
        label_66->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "L1(R)", nullptr));
        label_67->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "L3(B)", nullptr));
        label_94->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\346\212\275\345\207\272\350\274\235\345\272\246\343\200\200\346\232\227\345\201\264", nullptr));
        label_95->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\346\212\275\345\207\272\350\274\235\345\272\246\343\200\200\346\230\216\345\201\264", nullptr));
        label_96->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "L2(G)", nullptr));
        label_14->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\350\274\252\351\203\255\343\201\213\343\202\211\343\201\256\351\226\223\351\232\224", nullptr));
        label_16->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\345\204\252\345\205\210\345\272\246", nullptr));
        label_33->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\347\224\237\n"
"\346\210\220", nullptr));
        label_48->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\343\203\216\343\202\244\343\202\272\343\202\265\343\202\244\343\202\272\343\200\200\343\203\224\343\203\263\343\203\233\343\203\274\343\203\253\345\211\212\351\231\244", nullptr));
        label_49->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\343\203\216\343\202\244\343\202\272\343\202\265\343\202\244\343\202\272 \345\255\244\347\253\213\347\202\271\345\211\212\351\231\244", nullptr));
        label_84->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\345\261\236\n"
"\346\200\247", nullptr));
        label_85->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\350\274\235\n"
"\345\272\246", nullptr));
        checkBModeOnlyMatching->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\347\265\220\346\236\234\345\207\272\345\212\233\343\201\227\343\201\252\343\201\204", nullptr));
        checkBModeAbsoluteBright->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\347\265\266\345\257\276\350\274\235\345\272\246", nullptr));
        checkBModeDiffer->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\345\267\256\345\210\206\346\244\234\346\237\273", nullptr));
        checkBModeCenterBrightFromParts->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\351\203\250\345\223\201\343\201\213\343\202\211\350\274\235\345\272\246\343\202\222\346\212\275\345\207\272\343\201\231\343\202\213", nullptr));
        checkBModeNGCluster->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\345\241\212\346\244\234\346\237\273", nullptr));
        checkBModeBlackMask->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\351\273\222\343\203\236\343\202\271\343\202\257", nullptr));
        checkBModeEnabled->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\346\244\234\346\237\273\346\234\211\345\212\271", nullptr));
        checkBModeWhiteMask->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\347\231\275\343\203\236\343\202\271\343\202\257", nullptr));
        label_90->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\346\216\242\n"
"\347\264\242", nullptr));
        label_91->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\350\274\235\n"
"\345\272\246", nullptr));
        label_92->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\343\203\226\343\203\255\343\203\203\343\202\257\345\215\230\344\275\223\343\201\247\343\201\256\346\216\242\347\264\242\343\203\211\343\203\203\343\203\210\346\225\260", nullptr));
        label_93->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\345\205\250\344\275\223\343\201\247\343\201\256\346\216\242\347\264\242\343\203\211\343\203\203\343\203\210\346\225\260", nullptr));
        checkBModeCommonMovable->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\345\205\250\344\275\223\343\201\247\343\201\256\346\216\242\347\264\242\343\202\222\346\234\211\345\212\271\343\201\253\343\201\231\343\202\213", nullptr));
        label_86->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\350\243\234\n"
"\346\255\243", nullptr));
        label_87->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\350\274\235\n"
"\345\272\246", nullptr));
        checkBModeAdjustable->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\344\270\255\345\277\203\350\274\235\345\272\246\350\243\234\346\255\243\343\202\222\346\234\211\345\212\271\343\201\253\343\201\231\343\202\213", nullptr));
        label_88->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\346\230\216\345\201\264\343\200\200\346\234\200\345\244\247\350\243\234\346\255\243\350\274\235\345\272\246\351\207\217", nullptr));
        label_89->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\346\232\227\345\201\264\343\200\200\346\234\200\345\244\247\350\243\234\346\255\243\350\274\235\345\272\246\351\207\217", nullptr));
        label_73->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\347\213\255\n"
"\345\237\237", nullptr));
        label_74->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\346\230\216\345\201\264", nullptr));
        label_75->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "OK\350\274\235\345\272\246\347\257\204\345\233\262", nullptr));
        label_76->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "OK\343\203\211\343\203\203\343\203\210\346\225\260", nullptr));
        label_77->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\346\232\227\345\201\264", nullptr));
        label_30->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "NG\345\241\212\345\200\213\346\225\260", nullptr));
        label_29->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\343\201\223\343\202\214\344\273\245\344\270\212\343\201\256\351\225\267\343\201\225\343\201\247\357\274\256\357\274\247", nullptr));
        label_78->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\345\272\203\n"
"\345\237\237", nullptr));
        label_79->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\350\274\235\n"
"\345\272\246", nullptr));
        label_80->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "OK\350\274\235\345\272\246\347\257\204\345\233\262", nullptr));
        label_81->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\346\230\216\345\201\264", nullptr));
        label_82->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "OK\343\203\211\343\203\203\343\203\210\346\225\260", nullptr));
        label_83->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\346\232\227\345\201\264", nullptr));
        label_31->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\357\274\256\357\274\247\345\241\212\345\200\213\346\225\260", nullptr));
        label_34->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\343\201\223\343\202\214\344\273\245\344\270\212\343\201\256\351\225\267\343\201\225\343\201\247\357\274\256\357\274\247", nullptr));
        ButtonLibDelete->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "Delete", nullptr));
        ButtonLibNew->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "Clear new", nullptr));
        pushButtonClose->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "\351\226\211\343\201\230\343\202\213", nullptr));
        ButtonLibSave->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "Update", nullptr));
        ButtonLibSaveNew->setText(QCoreApplication::translate("EditColorBlockLibraryClass", "Save New", nullptr));
    } // retranslateUi

};

namespace Ui {
    class EditColorBlockLibraryClass: public Ui_EditColorBlockLibraryClass {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_EDITCOLORBLOCKLIBRARY_H
