#ifndef WHOLEIMAGEFORREVIEW_GLOBAL_H
#define WHOLEIMAGEFORREVIEW_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef WHOLEIMAGEFORREVIEW_LIB
# define WHOLEIMAGEFORREVIEW_EXPORT Q_DECL_EXPORT
#else
# define WHOLEIMAGEFORREVIEW_EXPORT Q_DECL_IMPORT
#endif

#endif // WHOLEIMAGEFORREVIEW_GLOBAL_H
