#ifndef BUTTONCLEARMASTERINFO_GLOBAL_H
#define BUTTONCLEARMASTERINFO_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONCLEARMASTERINFO_LIB
# define BUTTONCLEARMASTERINFO_EXPORT Q_DECL_EXPORT
#else
# define BUTTONCLEARMASTERINFO_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONCLEARMASTERINFO_GLOBAL_H
