#ifndef FILTERBRIGHTNESSLOGCONVERT_GLOBAL_H
#define FILTERBRIGHTNESSLOGCONVERT_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef FILTERBRIGHTNESSLOGCONVERT_LIB
# define FILTERBRIGHTNESSLOGCONVERT_EXPORT Q_DECL_EXPORT
#else
# define FILTERBRIGHTNESSLOGCONVERT_EXPORT Q_DECL_IMPORT
#endif

#endif // FILTERBRIGHTNESSLOGCONVERT_GLOBAL_H
