/********************************************************************************
** Form generated from reading UI file 'ShowOperationalPanel.ui'
**
** Created by: Qt User Interface Compiler version 6.10.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_SHOWOPERATIONALPANEL_H
#define UI_SHOWOPERATIONALPANEL_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QToolButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_ShowOperationalPanel
{
public:
    QFrame *frame;
    QCheckBox *checkBoxCompareToMaster;
    QLabel *label_41;
    QSpinBox *EditReferredBrightness;
    QLabel *label_42;
    QSpinBox *EditSearchDotToMaster;
    QCheckBox *checkBoxAutoBinarize;
    QCheckBox *checkBoxReduceNoise;
    QSpinBox *EditBinarizedLength;
    QLabel *label_40;
    QCheckBox *checkBoxDarkside;
    QPushButton *ButtonLoadFromLibrary;
    QPushButton *ButtonReflectAllBlocks;
    QPushButton *ButtonSaveToLibrary;
    QPushButton *ButtonClose;
    QPushButton *ButtonRelrectOnlyBlock;
    QLineEdit *EditLibName;
    QLineEdit *EditLibID;
    QLabel *label_4;
    QLabel *label_5;
    QFrame *frame_2;
    QSpinBox *EditMinGap;
    QLabel *label_44;
    QLabel *label_27;
    QLabel *label_28;
    QSpinBox *EditMinWidth;
    QLabel *label_43;
    QLabel *label_45;
    QSpinBox *EditOKNickRate;
    QSpinBox *EditWidthToIgnoreEdge;
    QLabel *label_46;
    QSpinBox *EditOKShortRate;
    QLabel *label_47;
    QLineEdit *lineEditMinArea;
    QLineEdit *lineEditMaxArea;
    QLabel *label_29;
    QSpinBox *EditMinSize;
    QFrame *frame_3;
    QLabel *label_48;
    QLabel *label_49;
    QLabel *label_51;
    QSpinBox *EditBrightnessWidthInsideL;
    QLabel *label_53;
    QLabel *label_54;
    QSpinBox *EditBrightnessWidthOutsideL;
    QSpinBox *EditBrightnessWidthOutsideH;
    QSpinBox *EditBrightnessWidthInsideH;
    QLabel *label_52;
    QLabel *label_50;
    QFrame *frame_4;
    QLabel *label_55;
    QLabel *label_56;
    QLabel *label_57;
    QLabel *label_58;
    QLabel *labelPeakL;
    QLabel *labelThresholdBrightness;
    QLabel *labelPeakH;
    QFrame *frame_SimImage;
    QPushButton *pushButtonSimShowCenterPos;
    QPushButton *pushButtonCalc;
    QLabel *labelResultNGOpen;
    QLabel *label_59;
    QLabel *labelResultNGShort;
    QLabel *label_60;
    QToolButton *toolButtonSimShowOpen;
    QToolButton *toolButtonSimShowShort;
    QToolButton *toolButtonSimShowBinary;

    void setupUi(QWidget *ShowOperationalPanel)
    {
        if (ShowOperationalPanel->objectName().isEmpty())
            ShowOperationalPanel->setObjectName("ShowOperationalPanel");
        ShowOperationalPanel->resize(905, 620);
        frame = new QFrame(ShowOperationalPanel);
        frame->setObjectName("frame");
        frame->setGeometry(QRect(10, 70, 281, 191));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Sunken);
        checkBoxCompareToMaster = new QCheckBox(frame);
        checkBoxCompareToMaster->setObjectName("checkBoxCompareToMaster");
        checkBoxCompareToMaster->setGeometry(QRect(10, 30, 181, 17));
        label_41 = new QLabel(frame);
        label_41->setObjectName("label_41");
        label_41->setGeometry(QRect(10, 106, 191, 21));
        label_41->setFrameShape(QFrame::Panel);
        label_41->setFrameShadow(QFrame::Sunken);
        label_41->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditReferredBrightness = new QSpinBox(frame);
        EditReferredBrightness->setObjectName("EditReferredBrightness");
        EditReferredBrightness->setGeometry(QRect(200, 106, 71, 22));
        EditReferredBrightness->setMaximum(99999);
        label_42 = new QLabel(frame);
        label_42->setObjectName("label_42");
        label_42->setGeometry(QRect(10, 160, 191, 21));
        label_42->setFrameShape(QFrame::Panel);
        label_42->setFrameShadow(QFrame::Sunken);
        label_42->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditSearchDotToMaster = new QSpinBox(frame);
        EditSearchDotToMaster->setObjectName("EditSearchDotToMaster");
        EditSearchDotToMaster->setGeometry(QRect(200, 160, 71, 22));
        EditSearchDotToMaster->setMaximum(99999);
        checkBoxAutoBinarize = new QCheckBox(frame);
        checkBoxAutoBinarize->setObjectName("checkBoxAutoBinarize");
        checkBoxAutoBinarize->setGeometry(QRect(170, 130, 101, 20));
        checkBoxReduceNoise = new QCheckBox(frame);
        checkBoxReduceNoise->setObjectName("checkBoxReduceNoise");
        checkBoxReduceNoise->setGeometry(QRect(10, 50, 181, 17));
        EditBinarizedLength = new QSpinBox(frame);
        EditBinarizedLength->setObjectName("EditBinarizedLength");
        EditBinarizedLength->setGeometry(QRect(200, 82, 71, 22));
        EditBinarizedLength->setMaximum(99999);
        label_40 = new QLabel(frame);
        label_40->setObjectName("label_40");
        label_40->setGeometry(QRect(10, 82, 191, 21));
        label_40->setFrameShape(QFrame::Panel);
        label_40->setFrameShadow(QFrame::Sunken);
        label_40->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        checkBoxDarkside = new QCheckBox(frame);
        checkBoxDarkside->setObjectName("checkBoxDarkside");
        checkBoxDarkside->setGeometry(QRect(10, 10, 341, 17));
        ButtonLoadFromLibrary = new QPushButton(ShowOperationalPanel);
        ButtonLoadFromLibrary->setObjectName("ButtonLoadFromLibrary");
        ButtonLoadFromLibrary->setGeometry(QRect(290, 550, 261, 41));
        ButtonLoadFromLibrary->setAcceptDrops(true);
        ButtonReflectAllBlocks = new QPushButton(ShowOperationalPanel);
        ButtonReflectAllBlocks->setObjectName("ButtonReflectAllBlocks");
        ButtonReflectAllBlocks->setGeometry(QRect(290, 500, 271, 41));
        ButtonReflectAllBlocks->setAcceptDrops(true);
        ButtonSaveToLibrary = new QPushButton(ShowOperationalPanel);
        ButtonSaveToLibrary->setObjectName("ButtonSaveToLibrary");
        ButtonSaveToLibrary->setGeometry(QRect(20, 550, 261, 41));
        ButtonSaveToLibrary->setAcceptDrops(true);
        ButtonClose = new QPushButton(ShowOperationalPanel);
        ButtonClose->setObjectName("ButtonClose");
        ButtonClose->setGeometry(QRect(720, 520, 171, 41));
        ButtonRelrectOnlyBlock = new QPushButton(ShowOperationalPanel);
        ButtonRelrectOnlyBlock->setObjectName("ButtonRelrectOnlyBlock");
        ButtonRelrectOnlyBlock->setGeometry(QRect(10, 500, 271, 41));
        ButtonRelrectOnlyBlock->setAcceptDrops(true);
        EditLibName = new QLineEdit(ShowOperationalPanel);
        EditLibName->setObjectName("EditLibName");
        EditLibName->setGeometry(QRect(70, 30, 391, 21));
        EditLibName->setReadOnly(true);
        EditLibID = new QLineEdit(ShowOperationalPanel);
        EditLibID->setObjectName("EditLibID");
        EditLibID->setGeometry(QRect(10, 30, 61, 21));
        EditLibID->setReadOnly(true);
        label_4 = new QLabel(ShowOperationalPanel);
        label_4->setObjectName("label_4");
        label_4->setGeometry(QRect(10, 10, 62, 20));
        label_4->setFrameShape(QFrame::Panel);
        label_4->setFrameShadow(QFrame::Sunken);
        label_4->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_5 = new QLabel(ShowOperationalPanel);
        label_5->setObjectName("label_5");
        label_5->setGeometry(QRect(70, 10, 391, 20));
        label_5->setFrameShape(QFrame::Panel);
        label_5->setFrameShadow(QFrame::Sunken);
        label_5->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        frame_2 = new QFrame(ShowOperationalPanel);
        frame_2->setObjectName("frame_2");
        frame_2->setGeometry(QRect(10, 270, 361, 221));
        frame_2->setFrameShape(QFrame::StyledPanel);
        frame_2->setFrameShadow(QFrame::Sunken);
        EditMinGap = new QSpinBox(frame_2);
        EditMinGap->setObjectName("EditMinGap");
        EditMinGap->setGeometry(QRect(258, 32, 71, 22));
        EditMinGap->setMaximum(999999);
        label_44 = new QLabel(frame_2);
        label_44->setObjectName("label_44");
        label_44->setGeometry(QRect(10, 82, 221, 21));
        label_44->setFrameShape(QFrame::Panel);
        label_44->setFrameShadow(QFrame::Sunken);
        label_44->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_27 = new QLabel(frame_2);
        label_27->setObjectName("label_27");
        label_27->setGeometry(QRect(10, 10, 241, 21));
        label_27->setFrameShape(QFrame::Panel);
        label_27->setFrameShadow(QFrame::Sunken);
        label_27->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_28 = new QLabel(frame_2);
        label_28->setObjectName("label_28");
        label_28->setGeometry(QRect(10, 32, 241, 21));
        label_28->setFrameShape(QFrame::Panel);
        label_28->setFrameShadow(QFrame::Sunken);
        label_28->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditMinWidth = new QSpinBox(frame_2);
        EditMinWidth->setObjectName("EditMinWidth");
        EditMinWidth->setGeometry(QRect(258, 10, 71, 22));
        EditMinWidth->setMaximum(999999);
        label_43 = new QLabel(frame_2);
        label_43->setObjectName("label_43");
        label_43->setGeometry(QRect(10, 60, 221, 21));
        label_43->setFrameShape(QFrame::Panel);
        label_43->setFrameShadow(QFrame::Sunken);
        label_43->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_45 = new QLabel(frame_2);
        label_45->setObjectName("label_45");
        label_45->setGeometry(QRect(12, 140, 241, 21));
        label_45->setFrameShape(QFrame::Panel);
        label_45->setFrameShadow(QFrame::Sunken);
        label_45->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditOKNickRate = new QSpinBox(frame_2);
        EditOKNickRate->setObjectName("EditOKNickRate");
        EditOKNickRate->setGeometry(QRect(260, 170, 91, 22));
        EditOKNickRate->setMaximum(2147483647);
        EditWidthToIgnoreEdge = new QSpinBox(frame_2);
        EditWidthToIgnoreEdge->setObjectName("EditWidthToIgnoreEdge");
        EditWidthToIgnoreEdge->setGeometry(QRect(260, 140, 91, 22));
        EditWidthToIgnoreEdge->setMaximum(2147483647);
        label_46 = new QLabel(frame_2);
        label_46->setObjectName("label_46");
        label_46->setGeometry(QRect(12, 170, 241, 21));
        label_46->setFrameShape(QFrame::Panel);
        label_46->setFrameShadow(QFrame::Sunken);
        label_46->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditOKShortRate = new QSpinBox(frame_2);
        EditOKShortRate->setObjectName("EditOKShortRate");
        EditOKShortRate->setGeometry(QRect(260, 192, 91, 22));
        EditOKShortRate->setMaximum(2147483647);
        label_47 = new QLabel(frame_2);
        label_47->setObjectName("label_47");
        label_47->setGeometry(QRect(12, 192, 241, 21));
        label_47->setFrameShape(QFrame::Panel);
        label_47->setFrameShadow(QFrame::Sunken);
        label_47->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lineEditMinArea = new QLineEdit(frame_2);
        lineEditMinArea->setObjectName("lineEditMinArea");
        lineEditMinArea->setGeometry(QRect(240, 60, 113, 21));
        lineEditMaxArea = new QLineEdit(frame_2);
        lineEditMaxArea->setObjectName("lineEditMaxArea");
        lineEditMaxArea->setGeometry(QRect(240, 82, 113, 21));
        label_29 = new QLabel(frame_2);
        label_29->setObjectName("label_29");
        label_29->setGeometry(QRect(10, 110, 241, 21));
        label_29->setFrameShape(QFrame::Panel);
        label_29->setFrameShadow(QFrame::Sunken);
        label_29->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditMinSize = new QSpinBox(frame_2);
        EditMinSize->setObjectName("EditMinSize");
        EditMinSize->setGeometry(QRect(260, 110, 91, 22));
        EditMinSize->setMaximum(999999);
        frame_3 = new QFrame(ShowOperationalPanel);
        frame_3->setObjectName("frame_3");
        frame_3->setGeometry(QRect(390, 70, 171, 191));
        frame_3->setFrameShape(QFrame::Panel);
        frame_3->setFrameShadow(QFrame::Sunken);
        label_48 = new QLabel(frame_3);
        label_48->setObjectName("label_48");
        label_48->setGeometry(QRect(0, 0, 171, 21));
        label_48->setFrameShape(QFrame::Panel);
        label_48->setFrameShadow(QFrame::Sunken);
        label_48->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_49 = new QLabel(frame_3);
        label_49->setObjectName("label_49");
        label_49->setGeometry(QRect(10, 30, 151, 21));
        label_49->setFrameShape(QFrame::Panel);
        label_49->setFrameShadow(QFrame::Sunken);
        label_49->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_51 = new QLabel(frame_3);
        label_51->setObjectName("label_51");
        label_51->setGeometry(QRect(10, 50, 71, 21));
        label_51->setFrameShape(QFrame::Panel);
        label_51->setFrameShadow(QFrame::Sunken);
        label_51->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditBrightnessWidthInsideL = new QSpinBox(frame_3);
        EditBrightnessWidthInsideL->setObjectName("EditBrightnessWidthInsideL");
        EditBrightnessWidthInsideL->setGeometry(QRect(10, 70, 71, 22));
        EditBrightnessWidthInsideL->setMinimum(-256);
        EditBrightnessWidthInsideL->setMaximum(256);
        label_53 = new QLabel(frame_3);
        label_53->setObjectName("label_53");
        label_53->setGeometry(QRect(10, 110, 151, 21));
        label_53->setFrameShape(QFrame::Panel);
        label_53->setFrameShadow(QFrame::Sunken);
        label_53->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_54 = new QLabel(frame_3);
        label_54->setObjectName("label_54");
        label_54->setGeometry(QRect(10, 130, 71, 21));
        label_54->setFrameShape(QFrame::Panel);
        label_54->setFrameShadow(QFrame::Sunken);
        label_54->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditBrightnessWidthOutsideL = new QSpinBox(frame_3);
        EditBrightnessWidthOutsideL->setObjectName("EditBrightnessWidthOutsideL");
        EditBrightnessWidthOutsideL->setGeometry(QRect(10, 150, 71, 22));
        EditBrightnessWidthOutsideL->setMinimum(-256);
        EditBrightnessWidthOutsideL->setMaximum(256);
        EditBrightnessWidthOutsideH = new QSpinBox(frame_3);
        EditBrightnessWidthOutsideH->setObjectName("EditBrightnessWidthOutsideH");
        EditBrightnessWidthOutsideH->setGeometry(QRect(80, 150, 71, 22));
        EditBrightnessWidthOutsideH->setMinimum(-256);
        EditBrightnessWidthOutsideH->setMaximum(256);
        EditBrightnessWidthInsideH = new QSpinBox(frame_3);
        EditBrightnessWidthInsideH->setObjectName("EditBrightnessWidthInsideH");
        EditBrightnessWidthInsideH->setGeometry(QRect(80, 70, 71, 22));
        EditBrightnessWidthInsideH->setMinimum(-256);
        EditBrightnessWidthInsideH->setMaximum(256);
        label_52 = new QLabel(frame_3);
        label_52->setObjectName("label_52");
        label_52->setGeometry(QRect(80, 130, 71, 21));
        label_52->setFrameShape(QFrame::Panel);
        label_52->setFrameShadow(QFrame::Sunken);
        label_52->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_50 = new QLabel(frame_3);
        label_50->setObjectName("label_50");
        label_50->setGeometry(QRect(80, 50, 71, 21));
        label_50->setFrameShape(QFrame::Panel);
        label_50->setFrameShadow(QFrame::Sunken);
        label_50->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        frame_4 = new QFrame(ShowOperationalPanel);
        frame_4->setObjectName("frame_4");
        frame_4->setGeometry(QRect(390, 260, 171, 81));
        frame_4->setFrameShape(QFrame::Panel);
        frame_4->setFrameShadow(QFrame::Sunken);
        label_55 = new QLabel(frame_4);
        label_55->setObjectName("label_55");
        label_55->setGeometry(QRect(0, 0, 171, 21));
        label_55->setFrameShape(QFrame::Panel);
        label_55->setFrameShadow(QFrame::Sunken);
        label_55->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_56 = new QLabel(frame_4);
        label_56->setObjectName("label_56");
        label_56->setGeometry(QRect(0, 30, 51, 21));
        label_56->setFrameShape(QFrame::Panel);
        label_56->setFrameShadow(QFrame::Sunken);
        label_56->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_57 = new QLabel(frame_4);
        label_57->setObjectName("label_57");
        label_57->setGeometry(QRect(60, 30, 51, 21));
        label_57->setFrameShape(QFrame::Panel);
        label_57->setFrameShadow(QFrame::Sunken);
        label_57->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_58 = new QLabel(frame_4);
        label_58->setObjectName("label_58");
        label_58->setGeometry(QRect(120, 30, 51, 21));
        label_58->setFrameShape(QFrame::Panel);
        label_58->setFrameShadow(QFrame::Sunken);
        label_58->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        labelPeakL = new QLabel(frame_4);
        labelPeakL->setObjectName("labelPeakL");
        labelPeakL->setGeometry(QRect(0, 50, 51, 21));
        labelPeakL->setFrameShape(QFrame::Panel);
        labelPeakL->setFrameShadow(QFrame::Sunken);
        labelPeakL->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        labelThresholdBrightness = new QLabel(frame_4);
        labelThresholdBrightness->setObjectName("labelThresholdBrightness");
        labelThresholdBrightness->setGeometry(QRect(60, 50, 51, 21));
        labelThresholdBrightness->setFrameShape(QFrame::Panel);
        labelThresholdBrightness->setFrameShadow(QFrame::Sunken);
        labelThresholdBrightness->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        labelPeakH = new QLabel(frame_4);
        labelPeakH->setObjectName("labelPeakH");
        labelPeakH->setGeometry(QRect(120, 50, 51, 21));
        labelPeakH->setFrameShape(QFrame::Panel);
        labelPeakH->setFrameShadow(QFrame::Sunken);
        labelPeakH->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        frame_SimImage = new QFrame(ShowOperationalPanel);
        frame_SimImage->setObjectName("frame_SimImage");
        frame_SimImage->setGeometry(QRect(580, 50, 311, 451));
        frame_SimImage->setFrameShape(QFrame::StyledPanel);
        frame_SimImage->setFrameShadow(QFrame::Sunken);
        pushButtonSimShowCenterPos = new QPushButton(ShowOperationalPanel);
        pushButtonSimShowCenterPos->setObjectName("pushButtonSimShowCenterPos");
        pushButtonSimShowCenterPos->setGeometry(QRect(820, 10, 71, 41));
        pushButtonCalc = new QPushButton(ShowOperationalPanel);
        pushButtonCalc->setObjectName("pushButtonCalc");
        pushButtonCalc->setGeometry(QRect(450, 350, 112, 51));
        labelResultNGOpen = new QLabel(ShowOperationalPanel);
        labelResultNGOpen->setObjectName("labelResultNGOpen");
        labelResultNGOpen->setGeometry(QRect(390, 430, 81, 21));
        labelResultNGOpen->setFrameShape(QFrame::Panel);
        labelResultNGOpen->setFrameShadow(QFrame::Sunken);
        labelResultNGOpen->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_59 = new QLabel(ShowOperationalPanel);
        label_59->setObjectName("label_59");
        label_59->setGeometry(QRect(390, 410, 81, 21));
        label_59->setFrameShape(QFrame::Panel);
        label_59->setFrameShadow(QFrame::Sunken);
        label_59->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        labelResultNGShort = new QLabel(ShowOperationalPanel);
        labelResultNGShort->setObjectName("labelResultNGShort");
        labelResultNGShort->setGeometry(QRect(480, 430, 81, 21));
        labelResultNGShort->setFrameShape(QFrame::Panel);
        labelResultNGShort->setFrameShadow(QFrame::Sunken);
        labelResultNGShort->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_60 = new QLabel(ShowOperationalPanel);
        label_60->setObjectName("label_60");
        label_60->setGeometry(QRect(480, 410, 81, 21));
        label_60->setFrameShape(QFrame::Panel);
        label_60->setFrameShadow(QFrame::Sunken);
        label_60->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        toolButtonSimShowOpen = new QToolButton(ShowOperationalPanel);
        toolButtonSimShowOpen->setObjectName("toolButtonSimShowOpen");
        toolButtonSimShowOpen->setGeometry(QRect(660, 10, 71, 41));
        toolButtonSimShowOpen->setCheckable(true);
        toolButtonSimShowOpen->setChecked(true);
        toolButtonSimShowShort = new QToolButton(ShowOperationalPanel);
        toolButtonSimShowShort->setObjectName("toolButtonSimShowShort");
        toolButtonSimShowShort->setGeometry(QRect(740, 10, 71, 41));
        toolButtonSimShowShort->setCheckable(true);
        toolButtonSimShowShort->setChecked(true);
        toolButtonSimShowBinary = new QToolButton(ShowOperationalPanel);
        toolButtonSimShowBinary->setObjectName("toolButtonSimShowBinary");
        toolButtonSimShowBinary->setGeometry(QRect(580, 10, 71, 41));
        toolButtonSimShowBinary->setCheckable(true);
        toolButtonSimShowBinary->setChecked(false);

        retranslateUi(ShowOperationalPanel);

        QMetaObject::connectSlotsByName(ShowOperationalPanel);
    } // setupUi

    void retranslateUi(QWidget *ShowOperationalPanel)
    {
        ShowOperationalPanel->setWindowTitle(QCoreApplication::translate("ShowOperationalPanel", "Threshold BuslineInspection", nullptr));
        checkBoxCompareToMaster->setText(QCoreApplication::translate("ShowOperationalPanel", "\343\203\236\343\202\271\343\202\277\343\203\274\347\224\273\345\203\217\343\201\250\343\201\256\346\257\224\350\274\203", nullptr));
        label_41->setText(QCoreApplication::translate("ShowOperationalPanel", "\357\274\222\345\200\244\345\214\226\345\217\202\347\205\247\350\274\235\345\272\246\345\200\244", nullptr));
        label_42->setText(QCoreApplication::translate("ShowOperationalPanel", "\343\203\236\343\202\271\343\202\277\343\203\274\343\201\250\343\201\256\346\257\224\350\274\203\346\231\202\343\201\256\346\216\242\347\264\242\347\257\204\345\233\262", nullptr));
        checkBoxAutoBinarize->setText(QCoreApplication::translate("ShowOperationalPanel", "\350\207\252\345\213\225", nullptr));
        checkBoxReduceNoise->setText(QCoreApplication::translate("ShowOperationalPanel", "\343\203\216\343\202\244\343\202\272\345\211\212\351\231\244", nullptr));
        label_40->setText(QCoreApplication::translate("ShowOperationalPanel", "\351\203\250\345\210\206\347\232\204\357\274\222\345\200\244\345\214\226\343\201\256\343\202\265\343\202\244\343\202\272", nullptr));
        checkBoxDarkside->setText(QCoreApplication::translate("ShowOperationalPanel", "\346\232\227\345\201\264", nullptr));
        ButtonLoadFromLibrary->setText(QCoreApplication::translate("ShowOperationalPanel", "\343\203\251\343\202\244\343\203\226\343\203\251\343\203\252\343\201\213\343\202\211\350\252\255\343\201\277\345\207\272\343\201\227", nullptr));
        ButtonReflectAllBlocks->setText(QCoreApplication::translate("ShowOperationalPanel", "\345\220\214\344\270\200\347\250\256\351\241\236\343\201\256\343\203\226\343\203\255\343\203\203\343\202\257\343\201\253\345\217\215\346\230\240", nullptr));
        ButtonSaveToLibrary->setText(QCoreApplication::translate("ShowOperationalPanel", "\343\203\251\343\202\244\343\203\226\343\203\251\343\203\252\343\201\253\344\277\235\345\255\230", nullptr));
        ButtonClose->setText(QCoreApplication::translate("ShowOperationalPanel", "\351\226\211\343\201\230\343\202\213", nullptr));
        ButtonRelrectOnlyBlock->setText(QCoreApplication::translate("ShowOperationalPanel", "\343\201\223\343\201\256\343\203\226\343\203\255\343\203\203\343\202\257\343\201\240\343\201\221\343\201\253\345\217\215\346\230\240", nullptr));
        EditLibName->setText(QCoreApplication::translate("ShowOperationalPanel", "XXX", nullptr));
        EditLibID->setText(QCoreApplication::translate("ShowOperationalPanel", "12345", nullptr));
        label_4->setText(QCoreApplication::translate("ShowOperationalPanel", "\343\203\251\343\202\244\343\203\226\343\203\251\343\203\252\357\274\251\357\274\244", nullptr));
        label_5->setText(QCoreApplication::translate("ShowOperationalPanel", "\343\203\251\343\202\244\343\203\226\343\203\251\343\203\252\345\220\215\347\247\260", nullptr));
        label_44->setText(QCoreApplication::translate("ShowOperationalPanel", "\346\234\200\345\244\247\351\235\242\347\251\215", nullptr));
        label_27->setText(QCoreApplication::translate("ShowOperationalPanel", "\346\234\200\345\260\217\343\203\251\343\202\244\343\203\263\345\271\205", nullptr));
        label_28->setText(QCoreApplication::translate("ShowOperationalPanel", "\346\234\200\345\260\217\351\226\223\351\232\224", nullptr));
        label_43->setText(QCoreApplication::translate("ShowOperationalPanel", "\346\234\200\345\260\217\351\235\242\347\251\215", nullptr));
        label_45->setText(QCoreApplication::translate("ShowOperationalPanel", "\350\274\252\351\203\255\347\204\241\350\246\226\343\203\224\343\202\257\343\202\273\343\203\253", nullptr));
        label_46->setText(QCoreApplication::translate("ShowOperationalPanel", "\346\254\240\343\201\221\345\210\244\345\256\232\343\201\256\345\244\247\343\201\215\343\201\225\357\274\210\357\274\220\357\275\236100\357\274\205\357\274\211", nullptr));
        label_47->setText(QCoreApplication::translate("ShowOperationalPanel", "\347\252\201\345\207\272\345\210\244\345\256\232\343\201\256\345\244\247\343\201\215\343\201\225\357\274\210\357\274\220\357\275\236100\357\274\205\357\274\211", nullptr));
        label_29->setText(QCoreApplication::translate("ShowOperationalPanel", "\346\234\200\345\260\217\343\202\265\343\202\244\343\202\272", nullptr));
        label_48->setText(QCoreApplication::translate("ShowOperationalPanel", "OK\345\210\244\345\256\232\343\201\256\350\274\235\345\272\246\345\271\205", nullptr));
        label_49->setText(QCoreApplication::translate("ShowOperationalPanel", "\345\206\205\345\201\264", nullptr));
        label_51->setText(QCoreApplication::translate("ShowOperationalPanel", "\346\232\227\345\201\264", nullptr));
        label_53->setText(QCoreApplication::translate("ShowOperationalPanel", "\345\244\226\345\201\264", nullptr));
        label_54->setText(QCoreApplication::translate("ShowOperationalPanel", "\346\232\227\345\201\264", nullptr));
        label_52->setText(QCoreApplication::translate("ShowOperationalPanel", "\346\230\216\345\201\264", nullptr));
        label_50->setText(QCoreApplication::translate("ShowOperationalPanel", "\346\230\216\345\201\264", nullptr));
        label_55->setText(QCoreApplication::translate("ShowOperationalPanel", "\350\274\235\345\272\246\345\200\244", nullptr));
        label_56->setText(QCoreApplication::translate("ShowOperationalPanel", "\346\232\227\345\201\264", nullptr));
        label_57->setText(QCoreApplication::translate("ShowOperationalPanel", "\351\226\276\345\200\244", nullptr));
        label_58->setText(QCoreApplication::translate("ShowOperationalPanel", "\346\230\216\345\201\264", nullptr));
        labelPeakL->setText(QCoreApplication::translate("ShowOperationalPanel", "123", nullptr));
        labelThresholdBrightness->setText(QCoreApplication::translate("ShowOperationalPanel", "123", nullptr));
        labelPeakH->setText(QCoreApplication::translate("ShowOperationalPanel", "123", nullptr));
        pushButtonSimShowCenterPos->setText(QCoreApplication::translate("ShowOperationalPanel", "\345\276\251\345\270\260", nullptr));
        pushButtonCalc->setText(QCoreApplication::translate("ShowOperationalPanel", "Calc", nullptr));
        labelResultNGOpen->setText(QCoreApplication::translate("ShowOperationalPanel", "123", nullptr));
        label_59->setText(QCoreApplication::translate("ShowOperationalPanel", "Open NG", nullptr));
        labelResultNGShort->setText(QCoreApplication::translate("ShowOperationalPanel", "123", nullptr));
        label_60->setText(QCoreApplication::translate("ShowOperationalPanel", "Short NG", nullptr));
        toolButtonSimShowOpen->setText(QCoreApplication::translate("ShowOperationalPanel", "Open", nullptr));
        toolButtonSimShowShort->setText(QCoreApplication::translate("ShowOperationalPanel", "Short", nullptr));
        toolButtonSimShowBinary->setText(QCoreApplication::translate("ShowOperationalPanel", "Binary", nullptr));
    } // retranslateUi

};

namespace Ui {
    class ShowOperationalPanel: public Ui_ShowOperationalPanel {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_SHOWOPERATIONALPANEL_H
