/********************************************************************************
** Form generated from reading UI file 'PropertyGerberFastForm.ui'
**
** Created by: Qt User Interface Compiler version 6.10.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_PROPERTYGERBERFASTFORM_H
#define UI_PROPERTYGERBERFASTFORM_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QToolButton>
#include <QtWidgets/QWidget>
#include "guiformbase.h"

QT_BEGIN_NAMESPACE

class Ui_PropertyGerberFastForm
{
public:
    QTabWidget *tabWidgetOperation;
    QWidget *tab1;
    QPushButton *pushButtonLoadGerber;
    QPushButton *pushButtonAutoFile;
    QPushButton *pushButtonClear;
    QPushButton *pushButtonEditLayerType;
    QPushButton *pushButtonEditCompositeDef;
    QPushButton *pushButtonSave;
    QPushButton *pushButtonLoad;
    QLabel *label_24;
    QPushButton *pushButtonSetLibFolder;
    QLabel *label_LibFolderName;
    QWidget *tab2;
    QToolButton *toolButtonSimpleMode;
    QFrame *frame;
    QPushButton *pushButtonMove;
    QLabel *label;
    QPushButton *pushButtonRotate;
    QPushButton *pushButtonZoom;
    QPushButton *pushButtonShear;
    QPushButton *pushButtonMirrorX;
    QPushButton *pushButtonMirrorY;
    QPushButton *pushButtonCenterize;
    QPushButton *pushButtonDraw;
    QFrame *frame_2;
    QLabel *label_2;
    QToolButton *toolButtonMove;
    QToolButton *toolButtonRotate;
    QToolButton *toolButtonZoom;
    QToolButton *toolButtonShearX;
    QToolButton *toolButtonShearY;
    QToolButton *toolButtonMatchPoints;
    QToolButton *toolButtonDraw;
    QFrame *frame_6;
    QLabel *label_25;
    QToolButton *toolButtonCreateLine;
    QToolButton *toolButtonCreateArc;
    QToolButton *toolButtonCreatePolygon;
    QWidget *tab3;
    QPushButton *pushButtonMaxEnlarge;
    QPushButton *pushButtonMaxShrink;
    QPushButton *pushButtonShiftable;
    QPushButton *pushButtonUnstableZone;
    QPushButton *pushButtonClearImage;
    QPushButton *pushButtonToImage;
    QPushButton *pushButtonStableZone;
    QPushButton *pushButtonToNormalImage;
    QPushButton *pushButtonToBitImage;
    QPushButton *pushButtonMakeCluster;
    QWidget *tab4;
    QPushButton *pushButtonToAutoMatch;
    QToolButton *toolButtonShowAutoMatchArea;
    QToolButton *toolButtonShowAutoMatchImage;
    QPushButton *pushButtonMakeAutoMatchArea;
    QPushButton *pushButtonClearAutoMatchArea;
    QPushButton *pushButtonMoveOtherAlgorithm;
    QPushButton *pushButtonMatchRoughly;
    QWidget *tab5;
    QPushButton *pushButtonToAlgo;
    QPushButton *pushButtonInitialAlgo;
    QGroupBox *groupBox;
    QCheckBox *checkBoxMakeAlgoShiftable;
    QCheckBox *checkBoxMakeAlgoSeparate;
    QCheckBox *checkBoxMakeAlgoEnlarge;
    QCheckBox *checkBoxMakeAlgoShrinked;
    QPushButton *pushButtonSetFlushMatrix;
    QWidget *Outline;
    QPushButton *pushButtonGenerateOutline;
    QPushButton *pushButtonEchingFactor;
    QPushButton *pushButtonClearOutline;
    QPushButton *pushButtonGenerateCenter;
    QPushButton *pushButtonGenerateAlgorithmFromOutline;
    QSpinBox *spinBoxOutlineWidth;
    QLabel *label_26;
    QTabWidget *tabWidgetProperty;
    QWidget *PTab1;
    QFrame *frameComposit;
    QLabel *label_GerberTitle;
    QPushButton *pushButtonClearSelectComposite;
    QLabel *label_CompositeTitle;
    QPushButton *pushButtonClearSelectLayer;
    QFrame *frameFiles;
    QPushButton *pushButtonClearFIleList;
    QPushButton *pushButtonClearDrawLayer;
    QPushButton *pushButtonClearCompositeDrawLayer;
    QWidget *PTab2;
    QTableWidget *tableWidgetAlignments;
    QFrame *frame_7;
    QPushButton *pushButtonClearMatchPoints;
    QPushButton *pushButtonStartMoveToMatch;
    QWidget *PTab3;
    QLabel *label_5;
    QComboBox *comboBoxUseLayerToAutoMatch;
    QStackedWidget *stackedWidgetAutoMatch;
    QWidget *AutoMatch;
    QFrame *frame_3;
    QTableWidget *tableWidgetAMManualPoints;
    QLabel *label_11;
    QPushButton *pushButtonAMClearPoints;
    QPushButton *pushButtonAMAllocate;
    QLabel *label_12;
    QCheckBox *checkBoxUseStable;
    QLabel *label_10;
    QFrame *frameAutoMatchShiftableLayer;
    QSpinBox *spinBoxMinDotsForAutoMatching;
    QLabel *label_9;
    QSpinBox *spinBoxMinDotsForAutoMatchingArea;
    QFrame *frameAutoMatchShiftableComposite;
    QLabel *label_7;
    QWidget *LikeManual;
    QSpinBox *spinBoxTransDot;
    QLabel *label_13;
    QLabel *label_14;
    QDoubleSpinBox *doubleSpinBoxRoughMatchAreaWidthRate;
    QDoubleSpinBox *doubleSpinBoxRoughMatchAreaHeightRate;
    QLabel *label_15;
    QPushButton *pushButtonSetForAutoMatch;
    QLabel *label_16;
    QSpinBox *spinBoxSearchAreaRoughMatch;
    QSpinBox *spinBoxSearchAreaParallelMatch;
    QLabel *label_17;
    QSpinBox *spinBoxSearchAreaRotateMatch;
    QLabel *label_18;
    QLabel *label_19;
    QSpinBox *spinBoxSearchAreaZoomMatch;
    QLabel *label_20;
    QSpinBox *spinBoxSearchAreaMatchDetail;
    QSpinBox *spinBoxDataIsolation;
    QLabel *label_21;
    QLabel *label_22;
    QSpinBox *spinBoxNearByPattern;
    QDoubleSpinBox *doubleSpinBoxMatchingRateToNeighbor;
    QLabel *label_23;
    QCheckBox *checkBoxBrighterInPattern;
    QFrame *frame_5;
    QToolButton *toolButtonAreaForZoom;
    QToolButton *toolButtonAreaForParallel;
    QToolButton *toolButtonAreaForRotate;
    QWidget *PTab4;
    QFrame *frame_4;
    QTableWidget *tableWidgetCrossedLayer;
    QLabel *label_8;
    QLabel *label_6;
    QPushButton *pushButtonSaveAlgoGen;
    QPushButton *pushButtonLoadAlgoGen;
    QPushButton *pushButtonMergeLoadAlgoGen;
    QTableWidget *tableWidgetGerberInfo;

    void setupUi(GUIFormBase *PropertyGerberFastForm)
    {
        if (PropertyGerberFastForm->objectName().isEmpty())
            PropertyGerberFastForm->setObjectName("PropertyGerberFastForm");
        PropertyGerberFastForm->resize(439, 876);
        tabWidgetOperation = new QTabWidget(PropertyGerberFastForm);
        tabWidgetOperation->setObjectName("tabWidgetOperation");
        tabWidgetOperation->setGeometry(QRect(0, 0, 441, 186));
        tab1 = new QWidget();
        tab1->setObjectName("tab1");
        pushButtonLoadGerber = new QPushButton(tab1);
        pushButtonLoadGerber->setObjectName("pushButtonLoadGerber");
        pushButtonLoadGerber->setGeometry(QRect(150, 2, 171, 41));
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/Qtres/CopyOne.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        pushButtonLoadGerber->setIcon(icon);
        pushButtonAutoFile = new QPushButton(tab1);
        pushButtonAutoFile->setObjectName("pushButtonAutoFile");
        pushButtonAutoFile->setGeometry(QRect(4, 2, 141, 41));
        QIcon icon1;
        icon1.addFile(QString::fromUtf8(":/Qtres/ListView.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        pushButtonAutoFile->setIcon(icon1);
        pushButtonClear = new QPushButton(tab1);
        pushButtonClear->setObjectName("pushButtonClear");
        pushButtonClear->setGeometry(QRect(330, 2, 101, 41));
        QIcon icon2;
        icon2.addFile(QString::fromUtf8(":/Qtres/Clear.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        pushButtonClear->setIcon(icon2);
        pushButtonEditLayerType = new QPushButton(tab1);
        pushButtonEditLayerType->setObjectName("pushButtonEditLayerType");
        pushButtonEditLayerType->setGeometry(QRect(10, 60, 191, 31));
        QIcon icon3;
        icon3.addFile(QString::fromUtf8(":/Qtres/Layers.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        pushButtonEditLayerType->setIcon(icon3);
        pushButtonEditCompositeDef = new QPushButton(tab1);
        pushButtonEditCompositeDef->setObjectName("pushButtonEditCompositeDef");
        pushButtonEditCompositeDef->setGeometry(QRect(10, 120, 191, 31));
        QIcon icon4;
        icon4.addFile(QString::fromUtf8(":/Qtres/Composite.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        pushButtonEditCompositeDef->setIcon(icon4);
        pushButtonSave = new QPushButton(tab1);
        pushButtonSave->setObjectName("pushButtonSave");
        pushButtonSave->setGeometry(QRect(240, 44, 81, 31));
        QIcon icon5;
        icon5.addFile(QString::fromUtf8(":/Qtres/Save.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        pushButtonSave->setIcon(icon5);
        pushButtonLoad = new QPushButton(tab1);
        pushButtonLoad->setObjectName("pushButtonLoad");
        pushButtonLoad->setGeometry(QRect(330, 44, 81, 31));
        QIcon icon6;
        icon6.addFile(QString::fromUtf8(":/Qtres/Load.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        pushButtonLoad->setIcon(icon6);
        label_24 = new QLabel(tab1);
        label_24->setObjectName("label_24");
        label_24->setGeometry(QRect(20, 44, 111, 20));
        label_24->setAlignment(Qt::AlignCenter);
        pushButtonSetLibFolder = new QPushButton(tab1);
        pushButtonSetLibFolder->setObjectName("pushButtonSetLibFolder");
        pushButtonSetLibFolder->setGeometry(QRect(10, 90, 191, 31));
        pushButtonSetLibFolder->setIcon(icon4);
        label_LibFolderName = new QLabel(tab1);
        label_LibFolderName->setObjectName("label_LibFolderName");
        label_LibFolderName->setGeometry(QRect(210, 90, 221, 31));
        label_LibFolderName->setFrameShape(QFrame::Panel);
        label_LibFolderName->setFrameShadow(QFrame::Sunken);
        tabWidgetOperation->addTab(tab1, QString());
        tab2 = new QWidget();
        tab2->setObjectName("tab2");
        toolButtonSimpleMode = new QToolButton(tab2);
        toolButtonSimpleMode->setObjectName("toolButtonSimpleMode");
        toolButtonSimpleMode->setGeometry(QRect(2, 10, 71, 27));
        toolButtonSimpleMode->setCheckable(true);
        toolButtonSimpleMode->setChecked(true);
        frame = new QFrame(tab2);
        frame->setObjectName("frame");
        frame->setGeometry(QRect(80, 10, 178, 146));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Sunken);
        pushButtonMove = new QPushButton(frame);
        pushButtonMove->setObjectName("pushButtonMove");
        pushButtonMove->setGeometry(QRect(2, 20, 87, 31));
        QIcon icon7;
        icon7.addFile(QString::fromUtf8(":/Qtres/Move.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        pushButtonMove->setIcon(icon7);
        label = new QLabel(frame);
        label->setObjectName("label");
        label->setGeometry(QRect(0, 0, 171, 16));
        label->setAlignment(Qt::AlignCenter);
        pushButtonRotate = new QPushButton(frame);
        pushButtonRotate->setObjectName("pushButtonRotate");
        pushButtonRotate->setGeometry(QRect(2, 50, 87, 31));
        QIcon icon8;
        icon8.addFile(QString::fromUtf8(":/Qtres/Rotate.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        pushButtonRotate->setIcon(icon8);
        pushButtonZoom = new QPushButton(frame);
        pushButtonZoom->setObjectName("pushButtonZoom");
        pushButtonZoom->setGeometry(QRect(2, 80, 87, 31));
        QIcon icon9;
        icon9.addFile(QString::fromUtf8(":/Qtres/Zoom.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        pushButtonZoom->setIcon(icon9);
        pushButtonShear = new QPushButton(frame);
        pushButtonShear->setObjectName("pushButtonShear");
        pushButtonShear->setGeometry(QRect(2, 110, 87, 31));
        QIcon icon10;
        icon10.addFile(QString::fromUtf8(":/Qtres/Cut.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        pushButtonShear->setIcon(icon10);
        pushButtonMirrorX = new QPushButton(frame);
        pushButtonMirrorX->setObjectName("pushButtonMirrorX");
        pushButtonMirrorX->setGeometry(QRect(90, 20, 87, 31));
        QIcon icon11;
        icon11.addFile(QString::fromUtf8(":/Qtres/Mirror.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        pushButtonMirrorX->setIcon(icon11);
        pushButtonMirrorY = new QPushButton(frame);
        pushButtonMirrorY->setObjectName("pushButtonMirrorY");
        pushButtonMirrorY->setGeometry(QRect(90, 50, 87, 31));
        pushButtonMirrorY->setIcon(icon11);
        pushButtonCenterize = new QPushButton(frame);
        pushButtonCenterize->setObjectName("pushButtonCenterize");
        pushButtonCenterize->setGeometry(QRect(90, 80, 87, 31));
        pushButtonDraw = new QPushButton(frame);
        pushButtonDraw->setObjectName("pushButtonDraw");
        pushButtonDraw->setGeometry(QRect(90, 110, 87, 31));
        frame_2 = new QFrame(tab2);
        frame_2->setObjectName("frame_2");
        frame_2->setGeometry(QRect(260, 10, 175, 146));
        frame_2->setFrameShape(QFrame::StyledPanel);
        frame_2->setFrameShadow(QFrame::Sunken);
        label_2 = new QLabel(frame_2);
        label_2->setObjectName("label_2");
        label_2->setGeometry(QRect(0, 0, 171, 16));
        label_2->setAlignment(Qt::AlignCenter);
        toolButtonMove = new QToolButton(frame_2);
        toolButtonMove->setObjectName("toolButtonMove");
        toolButtonMove->setGeometry(QRect(2, 20, 85, 31));
        toolButtonMove->setIcon(icon7);
        toolButtonMove->setCheckable(true);
        toolButtonMove->setChecked(false);
        toolButtonMove->setAutoExclusive(false);
        toolButtonMove->setToolButtonStyle(Qt::ToolButtonTextBesideIcon);
        toolButtonRotate = new QToolButton(frame_2);
        toolButtonRotate->setObjectName("toolButtonRotate");
        toolButtonRotate->setGeometry(QRect(2, 50, 85, 31));
        toolButtonRotate->setIcon(icon8);
        toolButtonRotate->setCheckable(true);
        toolButtonRotate->setChecked(false);
        toolButtonRotate->setAutoExclusive(false);
        toolButtonRotate->setToolButtonStyle(Qt::ToolButtonTextBesideIcon);
        toolButtonZoom = new QToolButton(frame_2);
        toolButtonZoom->setObjectName("toolButtonZoom");
        toolButtonZoom->setGeometry(QRect(2, 80, 85, 31));
        toolButtonZoom->setIcon(icon9);
        toolButtonZoom->setCheckable(true);
        toolButtonZoom->setAutoExclusive(false);
        toolButtonZoom->setToolButtonStyle(Qt::ToolButtonTextBesideIcon);
        toolButtonShearX = new QToolButton(frame_2);
        toolButtonShearX->setObjectName("toolButtonShearX");
        toolButtonShearX->setGeometry(QRect(88, 20, 85, 31));
        toolButtonShearX->setIcon(icon10);
        toolButtonShearX->setCheckable(true);
        toolButtonShearX->setAutoExclusive(false);
        toolButtonShearX->setToolButtonStyle(Qt::ToolButtonTextBesideIcon);
        toolButtonShearY = new QToolButton(frame_2);
        toolButtonShearY->setObjectName("toolButtonShearY");
        toolButtonShearY->setGeometry(QRect(88, 50, 85, 31));
        toolButtonShearY->setIcon(icon10);
        toolButtonShearY->setCheckable(true);
        toolButtonShearY->setAutoExclusive(false);
        toolButtonShearY->setToolButtonStyle(Qt::ToolButtonTextBesideIcon);
        toolButtonMatchPoints = new QToolButton(frame_2);
        toolButtonMatchPoints->setObjectName("toolButtonMatchPoints");
        toolButtonMatchPoints->setGeometry(QRect(2, 111, 165, 31));
        toolButtonMatchPoints->setCheckable(true);
        toolButtonMatchPoints->setAutoExclusive(false);
        toolButtonDraw = new QToolButton(frame_2);
        toolButtonDraw->setObjectName("toolButtonDraw");
        toolButtonDraw->setGeometry(QRect(88, 80, 85, 31));
        QIcon icon12;
        icon12.addFile(QString::fromUtf8(":/Qtres/Draw.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        toolButtonDraw->setIcon(icon12);
        toolButtonDraw->setCheckable(true);
        toolButtonDraw->setAutoExclusive(false);
        toolButtonDraw->setToolButtonStyle(Qt::ToolButtonTextBesideIcon);
        frame_6 = new QFrame(tab2);
        frame_6->setObjectName("frame_6");
        frame_6->setGeometry(QRect(0, 40, 78, 116));
        frame_6->setFrameShape(QFrame::StyledPanel);
        frame_6->setFrameShadow(QFrame::Sunken);
        label_25 = new QLabel(frame_6);
        label_25->setObjectName("label_25");
        label_25->setGeometry(QRect(0, 0, 81, 16));
        label_25->setAlignment(Qt::AlignCenter);
        toolButtonCreateLine = new QToolButton(frame_6);
        toolButtonCreateLine->setObjectName("toolButtonCreateLine");
        toolButtonCreateLine->setGeometry(QRect(3, 20, 71, 31));
        toolButtonCreateLine->setCheckable(true);
        toolButtonCreateLine->setAutoExclusive(true);
        toolButtonCreateArc = new QToolButton(frame_6);
        toolButtonCreateArc->setObjectName("toolButtonCreateArc");
        toolButtonCreateArc->setGeometry(QRect(3, 50, 71, 31));
        toolButtonCreateArc->setCheckable(true);
        toolButtonCreateArc->setAutoExclusive(true);
        toolButtonCreatePolygon = new QToolButton(frame_6);
        toolButtonCreatePolygon->setObjectName("toolButtonCreatePolygon");
        toolButtonCreatePolygon->setGeometry(QRect(3, 80, 71, 31));
        toolButtonCreatePolygon->setCheckable(true);
        toolButtonCreatePolygon->setAutoExclusive(true);
        tabWidgetOperation->addTab(tab2, QString());
        tab3 = new QWidget();
        tab3->setObjectName("tab3");
        pushButtonMaxEnlarge = new QPushButton(tab3);
        pushButtonMaxEnlarge->setObjectName("pushButtonMaxEnlarge");
        pushButtonMaxEnlarge->setGeometry(QRect(150, 10, 135, 31));
        pushButtonMaxShrink = new QPushButton(tab3);
        pushButtonMaxShrink->setObjectName("pushButtonMaxShrink");
        pushButtonMaxShrink->setGeometry(QRect(150, 44, 135, 31));
        pushButtonShiftable = new QPushButton(tab3);
        pushButtonShiftable->setObjectName("pushButtonShiftable");
        pushButtonShiftable->setGeometry(QRect(150, 78, 135, 31));
        pushButtonUnstableZone = new QPushButton(tab3);
        pushButtonUnstableZone->setObjectName("pushButtonUnstableZone");
        pushButtonUnstableZone->setGeometry(QRect(292, 10, 136, 31));
        pushButtonClearImage = new QPushButton(tab3);
        pushButtonClearImage->setObjectName("pushButtonClearImage");
        pushButtonClearImage->setGeometry(QRect(310, 120, 116, 31));
        pushButtonClearImage->setIcon(icon2);
        pushButtonToImage = new QPushButton(tab3);
        pushButtonToImage->setObjectName("pushButtonToImage");
        pushButtonToImage->setGeometry(QRect(4, 10, 138, 31));
        pushButtonStableZone = new QPushButton(tab3);
        pushButtonStableZone->setObjectName("pushButtonStableZone");
        pushButtonStableZone->setGeometry(QRect(292, 44, 136, 31));
        pushButtonToNormalImage = new QPushButton(tab3);
        pushButtonToNormalImage->setObjectName("pushButtonToNormalImage");
        pushButtonToNormalImage->setGeometry(QRect(4, 78, 138, 31));
        pushButtonToBitImage = new QPushButton(tab3);
        pushButtonToBitImage->setObjectName("pushButtonToBitImage");
        pushButtonToBitImage->setGeometry(QRect(4, 44, 138, 31));
        pushButtonMakeCluster = new QPushButton(tab3);
        pushButtonMakeCluster->setObjectName("pushButtonMakeCluster");
        pushButtonMakeCluster->setGeometry(QRect(4, 112, 138, 31));
        tabWidgetOperation->addTab(tab3, QString());
        tab4 = new QWidget();
        tab4->setObjectName("tab4");
        pushButtonToAutoMatch = new QPushButton(tab4);
        pushButtonToAutoMatch->setObjectName("pushButtonToAutoMatch");
        pushButtonToAutoMatch->setGeometry(QRect(0, 76, 211, 31));
        QIcon icon13;
        icon13.addFile(QString::fromUtf8(":/Qtres/Start.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        pushButtonToAutoMatch->setIcon(icon13);
        toolButtonShowAutoMatchArea = new QToolButton(tab4);
        toolButtonShowAutoMatchArea->setObjectName("toolButtonShowAutoMatchArea");
        toolButtonShowAutoMatchArea->setGeometry(QRect(0, 2, 211, 31));
        QPalette palette;
        QBrush brush(QColor(170, 85, 255, 255));
        brush.setStyle(Qt::BrushStyle::SolidPattern);
        palette.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Button, brush);
        palette.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Button, brush);
        palette.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Button, brush);
        toolButtonShowAutoMatchArea->setPalette(palette);
        toolButtonShowAutoMatchArea->setAutoFillBackground(true);
        QIcon icon14;
        icon14.addFile(QString::fromUtf8(":/Qtres/Area.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        toolButtonShowAutoMatchArea->setIcon(icon14);
        toolButtonShowAutoMatchArea->setCheckable(true);
        toolButtonShowAutoMatchArea->setChecked(true);
        toolButtonShowAutoMatchArea->setToolButtonStyle(Qt::ToolButtonTextBesideIcon);
        toolButtonShowAutoMatchImage = new QToolButton(tab4);
        toolButtonShowAutoMatchImage->setObjectName("toolButtonShowAutoMatchImage");
        toolButtonShowAutoMatchImage->setGeometry(QRect(220, 2, 211, 31));
        QPalette palette1;
        QBrush brush1(QColor(0, 170, 255, 255));
        brush1.setStyle(Qt::BrushStyle::SolidPattern);
        palette1.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Button, brush1);
        palette1.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Button, brush1);
        palette1.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Button, brush1);
        toolButtonShowAutoMatchImage->setPalette(palette1);
        toolButtonShowAutoMatchImage->setAutoFillBackground(true);
        QIcon icon15;
        icon15.addFile(QString::fromUtf8(":/Qtres/Image.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        toolButtonShowAutoMatchImage->setIcon(icon15);
        toolButtonShowAutoMatchImage->setCheckable(true);
        toolButtonShowAutoMatchImage->setToolButtonStyle(Qt::ToolButtonTextBesideIcon);
        pushButtonMakeAutoMatchArea = new QPushButton(tab4);
        pushButtonMakeAutoMatchArea->setObjectName("pushButtonMakeAutoMatchArea");
        pushButtonMakeAutoMatchArea->setGeometry(QRect(0, 40, 211, 31));
        QIcon icon16;
        icon16.addFile(QString::fromUtf8(":/Qtres/Make.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        pushButtonMakeAutoMatchArea->setIcon(icon16);
        pushButtonClearAutoMatchArea = new QPushButton(tab4);
        pushButtonClearAutoMatchArea->setObjectName("pushButtonClearAutoMatchArea");
        pushButtonClearAutoMatchArea->setGeometry(QRect(220, 40, 211, 31));
        pushButtonClearAutoMatchArea->setIcon(icon2);
        pushButtonMoveOtherAlgorithm = new QPushButton(tab4);
        pushButtonMoveOtherAlgorithm->setObjectName("pushButtonMoveOtherAlgorithm");
        pushButtonMoveOtherAlgorithm->setGeometry(QRect(0, 114, 211, 31));
        pushButtonMoveOtherAlgorithm->setIcon(icon7);
        pushButtonMatchRoughly = new QPushButton(tab4);
        pushButtonMatchRoughly->setObjectName("pushButtonMatchRoughly");
        pushButtonMatchRoughly->setGeometry(QRect(220, 114, 211, 31));
        QIcon icon17;
        icon17.addFile(QString::fromUtf8(":/Qtres/OK.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        pushButtonMatchRoughly->setIcon(icon17);
        tabWidgetOperation->addTab(tab4, QString());
        tab5 = new QWidget();
        tab5->setObjectName("tab5");
        pushButtonToAlgo = new QPushButton(tab5);
        pushButtonToAlgo->setObjectName("pushButtonToAlgo");
        pushButtonToAlgo->setGeometry(QRect(210, 50, 221, 41));
        pushButtonToAlgo->setIcon(icon13);
        pushButtonInitialAlgo = new QPushButton(tab5);
        pushButtonInitialAlgo->setObjectName("pushButtonInitialAlgo");
        pushButtonInitialAlgo->setGeometry(QRect(210, 10, 221, 31));
        pushButtonInitialAlgo->setIcon(icon4);
        groupBox = new QGroupBox(tab5);
        groupBox->setObjectName("groupBox");
        groupBox->setGeometry(QRect(4, 10, 201, 151));
        checkBoxMakeAlgoShiftable = new QCheckBox(groupBox);
        checkBoxMakeAlgoShiftable->setObjectName("checkBoxMakeAlgoShiftable");
        checkBoxMakeAlgoShiftable->setGeometry(QRect(4, 10, 201, 20));
        checkBoxMakeAlgoShiftable->setChecked(true);
        checkBoxMakeAlgoSeparate = new QCheckBox(groupBox);
        checkBoxMakeAlgoSeparate->setObjectName("checkBoxMakeAlgoSeparate");
        checkBoxMakeAlgoSeparate->setGeometry(QRect(4, 40, 201, 20));
        checkBoxMakeAlgoSeparate->setChecked(true);
        checkBoxMakeAlgoEnlarge = new QCheckBox(groupBox);
        checkBoxMakeAlgoEnlarge->setObjectName("checkBoxMakeAlgoEnlarge");
        checkBoxMakeAlgoEnlarge->setGeometry(QRect(4, 70, 201, 20));
        checkBoxMakeAlgoShrinked = new QCheckBox(groupBox);
        checkBoxMakeAlgoShrinked->setObjectName("checkBoxMakeAlgoShrinked");
        checkBoxMakeAlgoShrinked->setGeometry(QRect(4, 100, 201, 20));
        pushButtonSetFlushMatrix = new QPushButton(tab5);
        pushButtonSetFlushMatrix->setObjectName("pushButtonSetFlushMatrix");
        pushButtonSetFlushMatrix->setGeometry(QRect(210, 110, 221, 41));
        QIcon icon18;
        icon18.addFile(QString::fromUtf8(":/Qtres/Setting.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        pushButtonSetFlushMatrix->setIcon(icon18);
        tabWidgetOperation->addTab(tab5, QString());
        Outline = new QWidget();
        Outline->setObjectName("Outline");
        pushButtonGenerateOutline = new QPushButton(Outline);
        pushButtonGenerateOutline->setObjectName("pushButtonGenerateOutline");
        pushButtonGenerateOutline->setGeometry(QRect(10, 10, 211, 31));
        pushButtonEchingFactor = new QPushButton(Outline);
        pushButtonEchingFactor->setObjectName("pushButtonEchingFactor");
        pushButtonEchingFactor->setGeometry(QRect(10, 50, 211, 28));
        pushButtonClearOutline = new QPushButton(Outline);
        pushButtonClearOutline->setObjectName("pushButtonClearOutline");
        pushButtonClearOutline->setGeometry(QRect(230, 10, 161, 28));
        pushButtonGenerateCenter = new QPushButton(Outline);
        pushButtonGenerateCenter->setObjectName("pushButtonGenerateCenter");
        pushButtonGenerateCenter->setGeometry(QRect(10, 80, 211, 31));
        pushButtonGenerateAlgorithmFromOutline = new QPushButton(Outline);
        pushButtonGenerateAlgorithmFromOutline->setObjectName("pushButtonGenerateAlgorithmFromOutline");
        pushButtonGenerateAlgorithmFromOutline->setGeometry(QRect(10, 110, 211, 31));
        spinBoxOutlineWidth = new QSpinBox(Outline);
        spinBoxOutlineWidth->setObjectName("spinBoxOutlineWidth");
        spinBoxOutlineWidth->setGeometry(QRect(350, 111, 71, 31));
        spinBoxOutlineWidth->setMaximum(99999999);
        label_26 = new QLabel(Outline);
        label_26->setObjectName("label_26");
        label_26->setGeometry(QRect(250, 110, 91, 31));
        tabWidgetOperation->addTab(Outline, QString());
        tabWidgetProperty = new QTabWidget(PropertyGerberFastForm);
        tabWidgetProperty->setObjectName("tabWidgetProperty");
        tabWidgetProperty->setGeometry(QRect(3, 190, 435, 551));
        PTab1 = new QWidget();
        PTab1->setObjectName("PTab1");
        frameComposit = new QFrame(PTab1);
        frameComposit->setObjectName("frameComposit");
        frameComposit->setGeometry(QRect(10, 360, 411, 161));
        frameComposit->setFrameShape(QFrame::Panel);
        frameComposit->setFrameShadow(QFrame::Sunken);
        label_GerberTitle = new QLabel(PTab1);
        label_GerberTitle->setObjectName("label_GerberTitle");
        label_GerberTitle->setGeometry(QRect(10, 30, 411, 21));
        QFont font;
        font.setPointSize(10);
        label_GerberTitle->setFont(font);
        label_GerberTitle->setFrameShape(QFrame::Panel);
        label_GerberTitle->setFrameShadow(QFrame::Sunken);
        label_GerberTitle->setAlignment(Qt::AlignCenter);
        pushButtonClearSelectComposite = new QPushButton(PTab1);
        pushButtonClearSelectComposite->setObjectName("pushButtonClearSelectComposite");
        pushButtonClearSelectComposite->setGeometry(QRect(40, 316, 31, 24));
        label_CompositeTitle = new QLabel(PTab1);
        label_CompositeTitle->setObjectName("label_CompositeTitle");
        label_CompositeTitle->setGeometry(QRect(10, 340, 411, 21));
        label_CompositeTitle->setFont(font);
        label_CompositeTitle->setFrameShape(QFrame::Panel);
        label_CompositeTitle->setFrameShadow(QFrame::Sunken);
        label_CompositeTitle->setAlignment(Qt::AlignCenter);
        pushButtonClearSelectLayer = new QPushButton(PTab1);
        pushButtonClearSelectLayer->setObjectName("pushButtonClearSelectLayer");
        pushButtonClearSelectLayer->setGeometry(QRect(40, 4, 31, 24));
        frameFiles = new QFrame(PTab1);
        frameFiles->setObjectName("frameFiles");
        frameFiles->setGeometry(QRect(10, 50, 411, 261));
        frameFiles->setFrameShape(QFrame::Panel);
        frameFiles->setFrameShadow(QFrame::Sunken);
        pushButtonClearFIleList = new QPushButton(PTab1);
        pushButtonClearFIleList->setObjectName("pushButtonClearFIleList");
        pushButtonClearFIleList->setGeometry(QRect(180, 4, 161, 24));
        pushButtonClearFIleList->setIcon(icon2);
        pushButtonClearDrawLayer = new QPushButton(PTab1);
        pushButtonClearDrawLayer->setObjectName("pushButtonClearDrawLayer");
        pushButtonClearDrawLayer->setGeometry(QRect(10, 4, 31, 24));
        pushButtonClearCompositeDrawLayer = new QPushButton(PTab1);
        pushButtonClearCompositeDrawLayer->setObjectName("pushButtonClearCompositeDrawLayer");
        pushButtonClearCompositeDrawLayer->setGeometry(QRect(10, 316, 31, 24));
        tabWidgetProperty->addTab(PTab1, QString());
        PTab2 = new QWidget();
        PTab2->setObjectName("PTab2");
        tableWidgetAlignments = new QTableWidget(PTab2);
        if (tableWidgetAlignments->columnCount() < 2)
            tableWidgetAlignments->setColumnCount(2);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        tableWidgetAlignments->setHorizontalHeaderItem(0, __qtablewidgetitem);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        tableWidgetAlignments->setHorizontalHeaderItem(1, __qtablewidgetitem1);
        if (tableWidgetAlignments->rowCount() < 10)
            tableWidgetAlignments->setRowCount(10);
        QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
        tableWidgetAlignments->setVerticalHeaderItem(0, __qtablewidgetitem2);
        QTableWidgetItem *__qtablewidgetitem3 = new QTableWidgetItem();
        tableWidgetAlignments->setVerticalHeaderItem(1, __qtablewidgetitem3);
        QTableWidgetItem *__qtablewidgetitem4 = new QTableWidgetItem();
        tableWidgetAlignments->setVerticalHeaderItem(2, __qtablewidgetitem4);
        QTableWidgetItem *__qtablewidgetitem5 = new QTableWidgetItem();
        tableWidgetAlignments->setVerticalHeaderItem(3, __qtablewidgetitem5);
        QTableWidgetItem *__qtablewidgetitem6 = new QTableWidgetItem();
        tableWidgetAlignments->setVerticalHeaderItem(4, __qtablewidgetitem6);
        QTableWidgetItem *__qtablewidgetitem7 = new QTableWidgetItem();
        tableWidgetAlignments->setVerticalHeaderItem(5, __qtablewidgetitem7);
        QTableWidgetItem *__qtablewidgetitem8 = new QTableWidgetItem();
        tableWidgetAlignments->setVerticalHeaderItem(6, __qtablewidgetitem8);
        QTableWidgetItem *__qtablewidgetitem9 = new QTableWidgetItem();
        tableWidgetAlignments->setVerticalHeaderItem(7, __qtablewidgetitem9);
        QTableWidgetItem *__qtablewidgetitem10 = new QTableWidgetItem();
        tableWidgetAlignments->setVerticalHeaderItem(8, __qtablewidgetitem10);
        QTableWidgetItem *__qtablewidgetitem11 = new QTableWidgetItem();
        tableWidgetAlignments->setVerticalHeaderItem(9, __qtablewidgetitem11);
        tableWidgetAlignments->setObjectName("tableWidgetAlignments");
        tableWidgetAlignments->setGeometry(QRect(10, 10, 411, 461));
        tableWidgetAlignments->setSelectionMode(QAbstractItemView::SingleSelection);
        frame_7 = new QFrame(PTab2);
        frame_7->setObjectName("frame_7");
        frame_7->setGeometry(QRect(0, 470, 431, 51));
        frame_7->setFrameShape(QFrame::StyledPanel);
        frame_7->setFrameShadow(QFrame::Raised);
        pushButtonClearMatchPoints = new QPushButton(frame_7);
        pushButtonClearMatchPoints->setObjectName("pushButtonClearMatchPoints");
        pushButtonClearMatchPoints->setGeometry(QRect(30, 10, 151, 31));
        pushButtonClearMatchPoints->setIcon(icon2);
        pushButtonStartMoveToMatch = new QPushButton(frame_7);
        pushButtonStartMoveToMatch->setObjectName("pushButtonStartMoveToMatch");
        pushButtonStartMoveToMatch->setGeometry(QRect(210, 10, 211, 31));
        pushButtonStartMoveToMatch->setIcon(icon13);
        tabWidgetProperty->addTab(PTab2, QString());
        PTab3 = new QWidget();
        PTab3->setObjectName("PTab3");
        label_5 = new QLabel(PTab3);
        label_5->setObjectName("label_5");
        label_5->setGeometry(QRect(20, 0, 221, 16));
        comboBoxUseLayerToAutoMatch = new QComboBox(PTab3);
        comboBoxUseLayerToAutoMatch->setObjectName("comboBoxUseLayerToAutoMatch");
        comboBoxUseLayerToAutoMatch->setGeometry(QRect(20, 20, 391, 22));
        stackedWidgetAutoMatch = new QStackedWidget(PTab3);
        stackedWidgetAutoMatch->setObjectName("stackedWidgetAutoMatch");
        stackedWidgetAutoMatch->setGeometry(QRect(0, 50, 431, 461));
        AutoMatch = new QWidget();
        AutoMatch->setObjectName("AutoMatch");
        frame_3 = new QFrame(AutoMatch);
        frame_3->setObjectName("frame_3");
        frame_3->setGeometry(QRect(0, 330, 421, 131));
        frame_3->setFrameShape(QFrame::StyledPanel);
        frame_3->setFrameShadow(QFrame::Sunken);
        tableWidgetAMManualPoints = new QTableWidget(frame_3);
        if (tableWidgetAMManualPoints->columnCount() < 2)
            tableWidgetAMManualPoints->setColumnCount(2);
        QTableWidgetItem *__qtablewidgetitem12 = new QTableWidgetItem();
        tableWidgetAMManualPoints->setHorizontalHeaderItem(0, __qtablewidgetitem12);
        QTableWidgetItem *__qtablewidgetitem13 = new QTableWidgetItem();
        tableWidgetAMManualPoints->setHorizontalHeaderItem(1, __qtablewidgetitem13);
        tableWidgetAMManualPoints->setObjectName("tableWidgetAMManualPoints");
        tableWidgetAMManualPoints->setGeometry(QRect(10, 30, 291, 91));
        tableWidgetAMManualPoints->setSelectionMode(QAbstractItemView::SingleSelection);
        tableWidgetAMManualPoints->setSelectionBehavior(QAbstractItemView::SelectItems);
        label_11 = new QLabel(frame_3);
        label_11->setObjectName("label_11");
        label_11->setGeometry(QRect(0, 0, 421, 21));
        label_11->setFrameShape(QFrame::Panel);
        label_11->setFrameShadow(QFrame::Sunken);
        label_11->setAlignment(Qt::AlignCenter);
        pushButtonAMClearPoints = new QPushButton(frame_3);
        pushButtonAMClearPoints->setObjectName("pushButtonAMClearPoints");
        pushButtonAMClearPoints->setGeometry(QRect(310, 50, 101, 31));
        pushButtonAMAllocate = new QPushButton(frame_3);
        pushButtonAMAllocate->setObjectName("pushButtonAMAllocate");
        pushButtonAMAllocate->setGeometry(QRect(310, 90, 101, 31));
        label_12 = new QLabel(frame_3);
        label_12->setObjectName("label_12");
        label_12->setGeometry(QRect(310, 30, 101, 20));
        label_12->setAlignment(Qt::AlignCenter);
        checkBoxUseStable = new QCheckBox(AutoMatch);
        checkBoxUseStable->setObjectName("checkBoxUseStable");
        checkBoxUseStable->setGeometry(QRect(10, 116, 341, 20));
        label_10 = new QLabel(AutoMatch);
        label_10->setObjectName("label_10");
        label_10->setGeometry(QRect(0, 90, 341, 21));
        label_10->setFrameShape(QFrame::Panel);
        label_10->setFrameShadow(QFrame::Sunken);
        label_10->setAlignment(Qt::AlignCenter);
        frameAutoMatchShiftableLayer = new QFrame(AutoMatch);
        frameAutoMatchShiftableLayer->setObjectName("frameAutoMatchShiftableLayer");
        frameAutoMatchShiftableLayer->setGeometry(QRect(0, 160, 421, 81));
        frameAutoMatchShiftableLayer->setFrameShape(QFrame::StyledPanel);
        frameAutoMatchShiftableLayer->setFrameShadow(QFrame::Sunken);
        spinBoxMinDotsForAutoMatching = new QSpinBox(AutoMatch);
        spinBoxMinDotsForAutoMatching->setObjectName("spinBoxMinDotsForAutoMatching");
        spinBoxMinDotsForAutoMatching->setGeometry(QRect(340, 70, 81, 22));
        spinBoxMinDotsForAutoMatching->setMaximum(999999999);
        label_9 = new QLabel(AutoMatch);
        label_9->setObjectName("label_9");
        label_9->setGeometry(QRect(0, 70, 341, 21));
        label_9->setFrameShape(QFrame::Panel);
        label_9->setFrameShadow(QFrame::Sunken);
        label_9->setAlignment(Qt::AlignCenter);
        spinBoxMinDotsForAutoMatchingArea = new QSpinBox(AutoMatch);
        spinBoxMinDotsForAutoMatchingArea->setObjectName("spinBoxMinDotsForAutoMatchingArea");
        spinBoxMinDotsForAutoMatchingArea->setGeometry(QRect(340, 90, 81, 22));
        spinBoxMinDotsForAutoMatchingArea->setMinimum(-99);
        spinBoxMinDotsForAutoMatchingArea->setMaximum(99);
        spinBoxMinDotsForAutoMatchingArea->setValue(1);
        frameAutoMatchShiftableComposite = new QFrame(AutoMatch);
        frameAutoMatchShiftableComposite->setObjectName("frameAutoMatchShiftableComposite");
        frameAutoMatchShiftableComposite->setGeometry(QRect(0, 250, 421, 71));
        frameAutoMatchShiftableComposite->setFrameShape(QFrame::StyledPanel);
        frameAutoMatchShiftableComposite->setFrameShadow(QFrame::Sunken);
        label_7 = new QLabel(AutoMatch);
        label_7->setObjectName("label_7");
        label_7->setGeometry(QRect(0, 140, 391, 16));
        stackedWidgetAutoMatch->addWidget(AutoMatch);
        LikeManual = new QWidget();
        LikeManual->setObjectName("LikeManual");
        spinBoxTransDot = new QSpinBox(LikeManual);
        spinBoxTransDot->setObjectName("spinBoxTransDot");
        spinBoxTransDot->setGeometry(QRect(321, 90, 101, 22));
        spinBoxTransDot->setMaximum(999999999);
        label_13 = new QLabel(LikeManual);
        label_13->setObjectName("label_13");
        label_13->setGeometry(QRect(4, 90, 314, 21));
        label_13->setFrameShape(QFrame::Panel);
        label_13->setFrameShadow(QFrame::Sunken);
        label_13->setAlignment(Qt::AlignCenter);
        label_14 = new QLabel(LikeManual);
        label_14->setObjectName("label_14");
        label_14->setGeometry(QRect(4, 120, 314, 21));
        label_14->setFrameShape(QFrame::Panel);
        label_14->setFrameShadow(QFrame::Sunken);
        label_14->setAlignment(Qt::AlignCenter);
        doubleSpinBoxRoughMatchAreaWidthRate = new QDoubleSpinBox(LikeManual);
        doubleSpinBoxRoughMatchAreaWidthRate->setObjectName("doubleSpinBoxRoughMatchAreaWidthRate");
        doubleSpinBoxRoughMatchAreaWidthRate->setGeometry(QRect(321, 120, 101, 22));
        doubleSpinBoxRoughMatchAreaHeightRate = new QDoubleSpinBox(LikeManual);
        doubleSpinBoxRoughMatchAreaHeightRate->setObjectName("doubleSpinBoxRoughMatchAreaHeightRate");
        doubleSpinBoxRoughMatchAreaHeightRate->setGeometry(QRect(321, 150, 101, 22));
        label_15 = new QLabel(LikeManual);
        label_15->setObjectName("label_15");
        label_15->setGeometry(QRect(4, 150, 314, 21));
        label_15->setFrameShape(QFrame::Panel);
        label_15->setFrameShadow(QFrame::Sunken);
        label_15->setAlignment(Qt::AlignCenter);
        pushButtonSetForAutoMatch = new QPushButton(LikeManual);
        pushButtonSetForAutoMatch->setObjectName("pushButtonSetForAutoMatch");
        pushButtonSetForAutoMatch->setGeometry(QRect(300, 420, 121, 28));
        pushButtonSetForAutoMatch->setIcon(icon18);
        label_16 = new QLabel(LikeManual);
        label_16->setObjectName("label_16");
        label_16->setGeometry(QRect(4, 180, 314, 21));
        label_16->setFrameShape(QFrame::Panel);
        label_16->setFrameShadow(QFrame::Sunken);
        label_16->setAlignment(Qt::AlignCenter);
        spinBoxSearchAreaRoughMatch = new QSpinBox(LikeManual);
        spinBoxSearchAreaRoughMatch->setObjectName("spinBoxSearchAreaRoughMatch");
        spinBoxSearchAreaRoughMatch->setGeometry(QRect(321, 180, 101, 22));
        spinBoxSearchAreaRoughMatch->setMaximum(999999999);
        spinBoxSearchAreaParallelMatch = new QSpinBox(LikeManual);
        spinBoxSearchAreaParallelMatch->setObjectName("spinBoxSearchAreaParallelMatch");
        spinBoxSearchAreaParallelMatch->setGeometry(QRect(321, 210, 101, 22));
        spinBoxSearchAreaParallelMatch->setMaximum(999999999);
        label_17 = new QLabel(LikeManual);
        label_17->setObjectName("label_17");
        label_17->setGeometry(QRect(4, 210, 314, 21));
        label_17->setFrameShape(QFrame::Panel);
        label_17->setFrameShadow(QFrame::Sunken);
        label_17->setAlignment(Qt::AlignCenter);
        spinBoxSearchAreaRotateMatch = new QSpinBox(LikeManual);
        spinBoxSearchAreaRotateMatch->setObjectName("spinBoxSearchAreaRotateMatch");
        spinBoxSearchAreaRotateMatch->setGeometry(QRect(321, 240, 101, 22));
        spinBoxSearchAreaRotateMatch->setMaximum(999999999);
        label_18 = new QLabel(LikeManual);
        label_18->setObjectName("label_18");
        label_18->setGeometry(QRect(4, 240, 314, 21));
        label_18->setFrameShape(QFrame::Panel);
        label_18->setFrameShadow(QFrame::Sunken);
        label_18->setAlignment(Qt::AlignCenter);
        label_19 = new QLabel(LikeManual);
        label_19->setObjectName("label_19");
        label_19->setGeometry(QRect(4, 270, 314, 21));
        label_19->setFrameShape(QFrame::Panel);
        label_19->setFrameShadow(QFrame::Sunken);
        label_19->setAlignment(Qt::AlignCenter);
        spinBoxSearchAreaZoomMatch = new QSpinBox(LikeManual);
        spinBoxSearchAreaZoomMatch->setObjectName("spinBoxSearchAreaZoomMatch");
        spinBoxSearchAreaZoomMatch->setGeometry(QRect(321, 270, 101, 22));
        spinBoxSearchAreaZoomMatch->setMaximum(999999999);
        label_20 = new QLabel(LikeManual);
        label_20->setObjectName("label_20");
        label_20->setGeometry(QRect(4, 300, 314, 21));
        label_20->setFrameShape(QFrame::Panel);
        label_20->setFrameShadow(QFrame::Sunken);
        label_20->setAlignment(Qt::AlignCenter);
        spinBoxSearchAreaMatchDetail = new QSpinBox(LikeManual);
        spinBoxSearchAreaMatchDetail->setObjectName("spinBoxSearchAreaMatchDetail");
        spinBoxSearchAreaMatchDetail->setGeometry(QRect(321, 300, 101, 22));
        spinBoxSearchAreaMatchDetail->setMaximum(999999999);
        spinBoxDataIsolation = new QSpinBox(LikeManual);
        spinBoxDataIsolation->setObjectName("spinBoxDataIsolation");
        spinBoxDataIsolation->setGeometry(QRect(321, 330, 101, 22));
        spinBoxDataIsolation->setMaximum(999999999);
        label_21 = new QLabel(LikeManual);
        label_21->setObjectName("label_21");
        label_21->setGeometry(QRect(4, 330, 314, 21));
        label_21->setFrameShape(QFrame::Panel);
        label_21->setFrameShadow(QFrame::Sunken);
        label_21->setAlignment(Qt::AlignCenter);
        label_22 = new QLabel(LikeManual);
        label_22->setObjectName("label_22");
        label_22->setGeometry(QRect(4, 360, 314, 21));
        label_22->setFrameShape(QFrame::Panel);
        label_22->setFrameShadow(QFrame::Sunken);
        label_22->setAlignment(Qt::AlignCenter);
        spinBoxNearByPattern = new QSpinBox(LikeManual);
        spinBoxNearByPattern->setObjectName("spinBoxNearByPattern");
        spinBoxNearByPattern->setGeometry(QRect(321, 360, 101, 22));
        spinBoxNearByPattern->setMaximum(999999999);
        doubleSpinBoxMatchingRateToNeighbor = new QDoubleSpinBox(LikeManual);
        doubleSpinBoxMatchingRateToNeighbor->setObjectName("doubleSpinBoxMatchingRateToNeighbor");
        doubleSpinBoxMatchingRateToNeighbor->setGeometry(QRect(321, 390, 101, 22));
        label_23 = new QLabel(LikeManual);
        label_23->setObjectName("label_23");
        label_23->setGeometry(QRect(4, 390, 314, 21));
        label_23->setFrameShape(QFrame::Panel);
        label_23->setFrameShadow(QFrame::Sunken);
        label_23->setAlignment(Qt::AlignCenter);
        checkBoxBrighterInPattern = new QCheckBox(LikeManual);
        checkBoxBrighterInPattern->setObjectName("checkBoxBrighterInPattern");
        checkBoxBrighterInPattern->setGeometry(QRect(20, 420, 171, 20));
        stackedWidgetAutoMatch->addWidget(LikeManual);
        frame_5 = new QFrame(PTab3);
        frame_5->setObjectName("frame_5");
        frame_5->setGeometry(QRect(0, 54, 427, 61));
        frame_5->setFrameShape(QFrame::Panel);
        frame_5->setFrameShadow(QFrame::Plain);
        toolButtonAreaForZoom = new QToolButton(frame_5);
        toolButtonAreaForZoom->setObjectName("toolButtonAreaForZoom");
        toolButtonAreaForZoom->setGeometry(QRect(280, 10, 141, 41));
        toolButtonAreaForZoom->setIcon(icon9);
        toolButtonAreaForZoom->setCheckable(true);
        toolButtonAreaForZoom->setAutoExclusive(true);
        toolButtonAreaForZoom->setToolButtonStyle(Qt::ToolButtonTextBesideIcon);
        toolButtonAreaForParallel = new QToolButton(frame_5);
        toolButtonAreaForParallel->setObjectName("toolButtonAreaForParallel");
        toolButtonAreaForParallel->setGeometry(QRect(4, 10, 121, 41));
        QIcon icon19;
        icon19.addFile(QString::fromUtf8(":/Qtres/MoveY.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        toolButtonAreaForParallel->setIcon(icon19);
        toolButtonAreaForParallel->setCheckable(true);
        toolButtonAreaForParallel->setAutoExclusive(true);
        toolButtonAreaForParallel->setToolButtonStyle(Qt::ToolButtonTextBesideIcon);
        toolButtonAreaForRotate = new QToolButton(frame_5);
        toolButtonAreaForRotate->setObjectName("toolButtonAreaForRotate");
        toolButtonAreaForRotate->setGeometry(QRect(128, 10, 151, 41));
        toolButtonAreaForRotate->setIcon(icon8);
        toolButtonAreaForRotate->setCheckable(true);
        toolButtonAreaForRotate->setAutoExclusive(true);
        toolButtonAreaForRotate->setToolButtonStyle(Qt::ToolButtonTextBesideIcon);
        tabWidgetProperty->addTab(PTab3, QString());
        PTab4 = new QWidget();
        PTab4->setObjectName("PTab4");
        frame_4 = new QFrame(PTab4);
        frame_4->setObjectName("frame_4");
        frame_4->setGeometry(QRect(10, 20, 411, 451));
        frame_4->setFrameShape(QFrame::StyledPanel);
        frame_4->setFrameShadow(QFrame::Raised);
        tableWidgetCrossedLayer = new QTableWidget(frame_4);
        if (tableWidgetCrossedLayer->columnCount() < 4)
            tableWidgetCrossedLayer->setColumnCount(4);
        QTableWidgetItem *__qtablewidgetitem14 = new QTableWidgetItem();
        tableWidgetCrossedLayer->setHorizontalHeaderItem(0, __qtablewidgetitem14);
        QTableWidgetItem *__qtablewidgetitem15 = new QTableWidgetItem();
        tableWidgetCrossedLayer->setHorizontalHeaderItem(1, __qtablewidgetitem15);
        QTableWidgetItem *__qtablewidgetitem16 = new QTableWidgetItem();
        tableWidgetCrossedLayer->setHorizontalHeaderItem(2, __qtablewidgetitem16);
        QTableWidgetItem *__qtablewidgetitem17 = new QTableWidgetItem();
        tableWidgetCrossedLayer->setHorizontalHeaderItem(3, __qtablewidgetitem17);
        tableWidgetCrossedLayer->setObjectName("tableWidgetCrossedLayer");
        tableWidgetCrossedLayer->setGeometry(QRect(0, 20, 411, 431));
        QFont font1;
        font1.setPointSize(8);
        tableWidgetCrossedLayer->setFont(font1);
        tableWidgetCrossedLayer->setSelectionMode(QAbstractItemView::SingleSelection);
        tableWidgetCrossedLayer->setSelectionBehavior(QAbstractItemView::SelectRows);
        label_8 = new QLabel(frame_4);
        label_8->setObjectName("label_8");
        label_8->setGeometry(QRect(0, 0, 411, 20));
        label_8->setFrameShape(QFrame::Panel);
        label_8->setFrameShadow(QFrame::Sunken);
        label_6 = new QLabel(PTab4);
        label_6->setObjectName("label_6");
        label_6->setGeometry(QRect(10, 0, 391, 16));
        pushButtonSaveAlgoGen = new QPushButton(PTab4);
        pushButtonSaveAlgoGen->setObjectName("pushButtonSaveAlgoGen");
        pushButtonSaveAlgoGen->setGeometry(QRect(20, 480, 111, 31));
        pushButtonSaveAlgoGen->setIcon(icon5);
        pushButtonLoadAlgoGen = new QPushButton(PTab4);
        pushButtonLoadAlgoGen->setObjectName("pushButtonLoadAlgoGen");
        pushButtonLoadAlgoGen->setGeometry(QRect(140, 480, 111, 31));
        pushButtonLoadAlgoGen->setIcon(icon6);
        pushButtonMergeLoadAlgoGen = new QPushButton(PTab4);
        pushButtonMergeLoadAlgoGen->setObjectName("pushButtonMergeLoadAlgoGen");
        pushButtonMergeLoadAlgoGen->setGeometry(QRect(260, 480, 161, 31));
        QIcon icon20;
        icon20.addFile(QString::fromUtf8(":/Qtres/Marge.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        pushButtonMergeLoadAlgoGen->setIcon(icon20);
        tabWidgetProperty->addTab(PTab4, QString());
        tableWidgetGerberInfo = new QTableWidget(PropertyGerberFastForm);
        if (tableWidgetGerberInfo->columnCount() < 4)
            tableWidgetGerberInfo->setColumnCount(4);
        QTableWidgetItem *__qtablewidgetitem18 = new QTableWidgetItem();
        tableWidgetGerberInfo->setHorizontalHeaderItem(0, __qtablewidgetitem18);
        QTableWidgetItem *__qtablewidgetitem19 = new QTableWidgetItem();
        tableWidgetGerberInfo->setHorizontalHeaderItem(1, __qtablewidgetitem19);
        QTableWidgetItem *__qtablewidgetitem20 = new QTableWidgetItem();
        tableWidgetGerberInfo->setHorizontalHeaderItem(2, __qtablewidgetitem20);
        QTableWidgetItem *__qtablewidgetitem21 = new QTableWidgetItem();
        tableWidgetGerberInfo->setHorizontalHeaderItem(3, __qtablewidgetitem21);
        tableWidgetGerberInfo->setObjectName("tableWidgetGerberInfo");
        tableWidgetGerberInfo->setGeometry(QRect(3, 740, 431, 131));

        retranslateUi(PropertyGerberFastForm);

        tabWidgetOperation->setCurrentIndex(0);
        tabWidgetProperty->setCurrentIndex(0);
        stackedWidgetAutoMatch->setCurrentIndex(1);


        QMetaObject::connectSlotsByName(PropertyGerberFastForm);
    } // setupUi

    void retranslateUi(GUIFormBase *PropertyGerberFastForm)
    {
        PropertyGerberFastForm->setWindowTitle(QCoreApplication::translate("PropertyGerberFastForm", "Property GerberFast", nullptr));
        pushButtonLoadGerber->setText(QCoreApplication::translate("PropertyGerberFastForm", "2: Load gerber", nullptr));
        pushButtonAutoFile->setText(QCoreApplication::translate("PropertyGerberFastForm", "1: Auto files", nullptr));
        pushButtonClear->setText(QCoreApplication::translate("PropertyGerberFastForm", "Clear", nullptr));
        pushButtonEditLayerType->setText(QCoreApplication::translate("PropertyGerberFastForm", "Edit Layer type", nullptr));
        pushButtonEditCompositeDef->setText(QCoreApplication::translate("PropertyGerberFastForm", "Edit Composite", nullptr));
        pushButtonSave->setText(QCoreApplication::translate("PropertyGerberFastForm", "Save", nullptr));
        pushButtonLoad->setText(QCoreApplication::translate("PropertyGerberFastForm", "Load", nullptr));
        label_24->setText(QCoreApplication::translate("PropertyGerberFastForm", "(Additional)", nullptr));
        pushButtonSetLibFolder->setText(QCoreApplication::translate("PropertyGerberFastForm", "Lib folder", nullptr));
        label_LibFolderName->setText(QCoreApplication::translate("PropertyGerberFastForm", "All", nullptr));
        tabWidgetOperation->setTabText(tabWidgetOperation->indexOf(tab1), QCoreApplication::translate("PropertyGerberFastForm", "Load", nullptr));
        toolButtonSimpleMode->setText(QCoreApplication::translate("PropertyGerberFastForm", "Skelton", nullptr));
        pushButtonMove->setText(QCoreApplication::translate("PropertyGerberFastForm", "Move", nullptr));
        label->setText(QCoreApplication::translate("PropertyGerberFastForm", "Dialog", nullptr));
        pushButtonRotate->setText(QCoreApplication::translate("PropertyGerberFastForm", "Rotate", nullptr));
        pushButtonZoom->setText(QCoreApplication::translate("PropertyGerberFastForm", "Zoom", nullptr));
        pushButtonShear->setText(QCoreApplication::translate("PropertyGerberFastForm", "Shear", nullptr));
        pushButtonMirrorX->setText(QCoreApplication::translate("PropertyGerberFastForm", "Mirror X", nullptr));
        pushButtonMirrorY->setText(QCoreApplication::translate("PropertyGerberFastForm", "Mirror Y", nullptr));
        pushButtonCenterize->setText(QCoreApplication::translate("PropertyGerberFastForm", "ZmCenter", nullptr));
        pushButtonDraw->setText(QCoreApplication::translate("PropertyGerberFastForm", "Draw", nullptr));
        label_2->setText(QCoreApplication::translate("PropertyGerberFastForm", "Operation", nullptr));
        toolButtonMove->setText(QCoreApplication::translate("PropertyGerberFastForm", "Move", nullptr));
        toolButtonRotate->setText(QCoreApplication::translate("PropertyGerberFastForm", "Rotate", nullptr));
        toolButtonZoom->setText(QCoreApplication::translate("PropertyGerberFastForm", "Zoom", nullptr));
        toolButtonShearX->setText(QCoreApplication::translate("PropertyGerberFastForm", "Shear X", nullptr));
        toolButtonShearY->setText(QCoreApplication::translate("PropertyGerberFastForm", "Shear Y", nullptr));
        toolButtonMatchPoints->setText(QCoreApplication::translate("PropertyGerberFastForm", "Match Points", nullptr));
        toolButtonDraw->setText(QCoreApplication::translate("PropertyGerberFastForm", "Draw", nullptr));
        label_25->setText(QCoreApplication::translate("PropertyGerberFastForm", "Creation", nullptr));
        toolButtonCreateLine->setText(QCoreApplication::translate("PropertyGerberFastForm", "Line", nullptr));
        toolButtonCreateArc->setText(QCoreApplication::translate("PropertyGerberFastForm", "Arc", nullptr));
        toolButtonCreatePolygon->setText(QCoreApplication::translate("PropertyGerberFastForm", "Polygon", nullptr));
        tabWidgetOperation->setTabText(tabWidgetOperation->indexOf(tab2), QCoreApplication::translate("PropertyGerberFastForm", "Operation", nullptr));
        pushButtonMaxEnlarge->setText(QCoreApplication::translate("PropertyGerberFastForm", "Max enlarge", nullptr));
        pushButtonMaxShrink->setText(QCoreApplication::translate("PropertyGerberFastForm", "Max shrink", nullptr));
        pushButtonShiftable->setText(QCoreApplication::translate("PropertyGerberFastForm", "Shiftable area", nullptr));
        pushButtonUnstableZone->setText(QCoreApplication::translate("PropertyGerberFastForm", "Unstable zone", nullptr));
        pushButtonClearImage->setText(QCoreApplication::translate("PropertyGerberFastForm", "Clear", nullptr));
        pushButtonToImage->setText(QCoreApplication::translate("PropertyGerberFastForm", "To Master Image", nullptr));
        pushButtonStableZone->setText(QCoreApplication::translate("PropertyGerberFastForm", "Stable zone", nullptr));
        pushButtonToNormalImage->setText(QCoreApplication::translate("PropertyGerberFastForm", "To normal", nullptr));
        pushButtonToBitImage->setText(QCoreApplication::translate("PropertyGerberFastForm", "To Bit Image", nullptr));
        pushButtonMakeCluster->setText(QCoreApplication::translate("PropertyGerberFastForm", "Clusterize", nullptr));
        tabWidgetOperation->setTabText(tabWidgetOperation->indexOf(tab3), QCoreApplication::translate("PropertyGerberFastForm", "Make Image", nullptr));
        pushButtonToAutoMatch->setText(QCoreApplication::translate("PropertyGerberFastForm", "2 : Start auto matching", nullptr));
        toolButtonShowAutoMatchArea->setText(QCoreApplication::translate("PropertyGerberFastForm", "Show auto matching area", nullptr));
        toolButtonShowAutoMatchImage->setText(QCoreApplication::translate("PropertyGerberFastForm", "Show auto matching image", nullptr));
        pushButtonMakeAutoMatchArea->setText(QCoreApplication::translate("PropertyGerberFastForm", "1 : Make matching area", nullptr));
        pushButtonClearAutoMatchArea->setText(QCoreApplication::translate("PropertyGerberFastForm", "Clear matching area", nullptr));
        pushButtonMoveOtherAlgorithm->setText(QCoreApplication::translate("PropertyGerberFastForm", "3 : Move other algorithm", nullptr));
        pushButtonMatchRoughly->setText(QCoreApplication::translate("PropertyGerberFastForm", "Rough match", nullptr));
        tabWidgetOperation->setTabText(tabWidgetOperation->indexOf(tab4), QCoreApplication::translate("PropertyGerberFastForm", "Auto matching", nullptr));
        pushButtonToAlgo->setText(QCoreApplication::translate("PropertyGerberFastForm", "Start to make Algo", nullptr));
        pushButtonInitialAlgo->setText(QCoreApplication::translate("PropertyGerberFastForm", "Initial from layer/composite", nullptr));
        groupBox->setTitle(QString());
        checkBoxMakeAlgoShiftable->setText(QCoreApplication::translate("PropertyGerberFastForm", "Shiftable area", nullptr));
        checkBoxMakeAlgoSeparate->setText(QCoreApplication::translate("PropertyGerberFastForm", "Separate Stable/Unstable", nullptr));
        checkBoxMakeAlgoEnlarge->setText(QCoreApplication::translate("PropertyGerberFastForm", "Enlarge area", nullptr));
        checkBoxMakeAlgoShrinked->setText(QCoreApplication::translate("PropertyGerberFastForm", "Shrinked area", nullptr));
        pushButtonSetFlushMatrix->setText(QCoreApplication::translate("PropertyGerberFastForm", "Set Flush matrix for paste", nullptr));
        tabWidgetOperation->setTabText(tabWidgetOperation->indexOf(tab5), QCoreApplication::translate("PropertyGerberFastForm", "Make algorithm", nullptr));
        pushButtonGenerateOutline->setText(QCoreApplication::translate("PropertyGerberFastForm", "Generate outline", nullptr));
        pushButtonEchingFactor->setText(QCoreApplication::translate("PropertyGerberFastForm", "Eching factor - Corner", nullptr));
        pushButtonClearOutline->setText(QCoreApplication::translate("PropertyGerberFastForm", "Clear outline", nullptr));
        pushButtonGenerateCenter->setText(QCoreApplication::translate("PropertyGerberFastForm", "Centerize", nullptr));
        pushButtonGenerateAlgorithmFromOutline->setText(QCoreApplication::translate("PropertyGerberFastForm", "Make algorithm on line", nullptr));
        label_26->setText(QCoreApplication::translate("PropertyGerberFastForm", "Line width", nullptr));
        tabWidgetOperation->setTabText(tabWidgetOperation->indexOf(Outline), QCoreApplication::translate("PropertyGerberFastForm", "Outline", nullptr));
        label_GerberTitle->setText(QCoreApplication::translate("PropertyGerberFastForm", "Gerber file", nullptr));
        pushButtonClearSelectComposite->setText(QCoreApplication::translate("PropertyGerberFastForm", "C", nullptr));
        label_CompositeTitle->setText(QCoreApplication::translate("PropertyGerberFastForm", "Composite", nullptr));
        pushButtonClearSelectLayer->setText(QCoreApplication::translate("PropertyGerberFastForm", "C", nullptr));
        pushButtonClearFIleList->setText(QCoreApplication::translate("PropertyGerberFastForm", "Clear file list", nullptr));
        pushButtonClearDrawLayer->setText(QCoreApplication::translate("PropertyGerberFastForm", "C", nullptr));
        pushButtonClearCompositeDrawLayer->setText(QCoreApplication::translate("PropertyGerberFastForm", "C", nullptr));
        tabWidgetProperty->setTabText(tabWidgetProperty->indexOf(PTab1), QCoreApplication::translate("PropertyGerberFastForm", "Gerber layer", nullptr));
        QTableWidgetItem *___qtablewidgetitem = tableWidgetAlignments->horizontalHeaderItem(0);
        ___qtablewidgetitem->setText(QCoreApplication::translate("PropertyGerberFastForm", "Image point", nullptr));
        QTableWidgetItem *___qtablewidgetitem1 = tableWidgetAlignments->horizontalHeaderItem(1);
        ___qtablewidgetitem1->setText(QCoreApplication::translate("PropertyGerberFastForm", "Gerber point", nullptr));
        QTableWidgetItem *___qtablewidgetitem2 = tableWidgetAlignments->verticalHeaderItem(0);
        ___qtablewidgetitem2->setText(QCoreApplication::translate("PropertyGerberFastForm", "1", nullptr));
        QTableWidgetItem *___qtablewidgetitem3 = tableWidgetAlignments->verticalHeaderItem(1);
        ___qtablewidgetitem3->setText(QCoreApplication::translate("PropertyGerberFastForm", "2", nullptr));
        QTableWidgetItem *___qtablewidgetitem4 = tableWidgetAlignments->verticalHeaderItem(2);
        ___qtablewidgetitem4->setText(QCoreApplication::translate("PropertyGerberFastForm", "3", nullptr));
        QTableWidgetItem *___qtablewidgetitem5 = tableWidgetAlignments->verticalHeaderItem(3);
        ___qtablewidgetitem5->setText(QCoreApplication::translate("PropertyGerberFastForm", "4", nullptr));
        QTableWidgetItem *___qtablewidgetitem6 = tableWidgetAlignments->verticalHeaderItem(4);
        ___qtablewidgetitem6->setText(QCoreApplication::translate("PropertyGerberFastForm", "5", nullptr));
        QTableWidgetItem *___qtablewidgetitem7 = tableWidgetAlignments->verticalHeaderItem(5);
        ___qtablewidgetitem7->setText(QCoreApplication::translate("PropertyGerberFastForm", "6", nullptr));
        QTableWidgetItem *___qtablewidgetitem8 = tableWidgetAlignments->verticalHeaderItem(6);
        ___qtablewidgetitem8->setText(QCoreApplication::translate("PropertyGerberFastForm", "7", nullptr));
        QTableWidgetItem *___qtablewidgetitem9 = tableWidgetAlignments->verticalHeaderItem(7);
        ___qtablewidgetitem9->setText(QCoreApplication::translate("PropertyGerberFastForm", "8", nullptr));
        QTableWidgetItem *___qtablewidgetitem10 = tableWidgetAlignments->verticalHeaderItem(8);
        ___qtablewidgetitem10->setText(QCoreApplication::translate("PropertyGerberFastForm", "9", nullptr));
        QTableWidgetItem *___qtablewidgetitem11 = tableWidgetAlignments->verticalHeaderItem(9);
        ___qtablewidgetitem11->setText(QCoreApplication::translate("PropertyGerberFastForm", "10", nullptr));
        pushButtonClearMatchPoints->setText(QCoreApplication::translate("PropertyGerberFastForm", "Clear points", nullptr));
        pushButtonStartMoveToMatch->setText(QCoreApplication::translate("PropertyGerberFastForm", "Start move to match", nullptr));
        tabWidgetProperty->setTabText(tabWidgetProperty->indexOf(PTab2), QCoreApplication::translate("PropertyGerberFastForm", "Match points", nullptr));
        label_5->setText(QCoreApplication::translate("PropertyGerberFastForm", "Usage layer to match automatically", nullptr));
        QTableWidgetItem *___qtablewidgetitem12 = tableWidgetAMManualPoints->horizontalHeaderItem(0);
        ___qtablewidgetitem12->setText(QCoreApplication::translate("PropertyGerberFastForm", "ImagePoint", nullptr));
        QTableWidgetItem *___qtablewidgetitem13 = tableWidgetAMManualPoints->horizontalHeaderItem(1);
        ___qtablewidgetitem13->setText(QCoreApplication::translate("PropertyGerberFastForm", "Gerber Point", nullptr));
        label_11->setText(QCoreApplication::translate("PropertyGerberFastForm", "Manual control points", nullptr));
        pushButtonAMClearPoints->setText(QCoreApplication::translate("PropertyGerberFastForm", "Clear all", nullptr));
        pushButtonAMAllocate->setText(QCoreApplication::translate("PropertyGerberFastForm", "Allocate", nullptr));
        label_12->setText(QCoreApplication::translate("PropertyGerberFastForm", "Shift+Click", nullptr));
        checkBoxUseStable->setText(QCoreApplication::translate("PropertyGerberFastForm", "Use positions which are not effected by other item veriety", nullptr));
        label_10->setText(QCoreApplication::translate("PropertyGerberFastForm", "Shrink dot for matching area (Eching factor)", nullptr));
        label_9->setText(QCoreApplication::translate("PropertyGerberFastForm", "Minimum area pixels for matching", nullptr));
        label_7->setText(QCoreApplication::translate("PropertyGerberFastForm", "Shiftable layers", nullptr));
        label_13->setText(QCoreApplication::translate("PropertyGerberFastForm", "Trans Dot", nullptr));
        label_14->setText(QCoreApplication::translate("PropertyGerberFastForm", "Rate for the width of rough-match 0-100", nullptr));
        label_15->setText(QCoreApplication::translate("PropertyGerberFastForm", "Rate for height of rough-match 0-100", nullptr));
        pushButtonSetForAutoMatch->setText(QCoreApplication::translate("PropertyGerberFastForm", "Set", nullptr));
        label_16->setText(QCoreApplication::translate("PropertyGerberFastForm", "Search Area in RoughMatch", nullptr));
        label_17->setText(QCoreApplication::translate("PropertyGerberFastForm", "Search Area in Parallel match", nullptr));
        label_18->setText(QCoreApplication::translate("PropertyGerberFastForm", "Search Area in Rotation match", nullptr));
        label_19->setText(QCoreApplication::translate("PropertyGerberFastForm", "Search Area in Zoom match", nullptr));
        label_20->setText(QCoreApplication::translate("PropertyGerberFastForm", "Search Area in Detail match", nullptr));
        label_21->setText(QCoreApplication::translate("PropertyGerberFastForm", "Data Isolation", nullptr));
        label_22->setText(QCoreApplication::translate("PropertyGerberFastForm", "Near By Pattern", nullptr));
        label_23->setText(QCoreApplication::translate("PropertyGerberFastForm", "Matching RateTo Neighbor 0-100", nullptr));
        checkBoxBrighterInPattern->setText(QCoreApplication::translate("PropertyGerberFastForm", "Brighter in pattern", nullptr));
        toolButtonAreaForZoom->setText(QCoreApplication::translate("PropertyGerberFastForm", "\346\213\241\345\244\247\347\270\256\345\260\217\343\200\200\357\274\223\347\202\271\347\233\256", nullptr));
        toolButtonAreaForParallel->setText(QCoreApplication::translate("PropertyGerberFastForm", "\345\271\263\350\241\214\347\247\273\345\213\225\343\200\2001\347\202\271\347\233\256", nullptr));
        toolButtonAreaForRotate->setText(QCoreApplication::translate("PropertyGerberFastForm", "\345\233\236\350\273\242\357\274\215\345\257\276\350\247\222\343\200\200\357\274\222\347\202\271\347\233\256", nullptr));
        tabWidgetProperty->setTabText(tabWidgetProperty->indexOf(PTab3), QCoreApplication::translate("PropertyGerberFastForm", "Auto matching", nullptr));
        QTableWidgetItem *___qtablewidgetitem14 = tableWidgetCrossedLayer->horizontalHeaderItem(0);
        ___qtablewidgetitem14->setText(QCoreApplication::translate("PropertyGerberFastForm", "L/C", nullptr));
        QTableWidgetItem *___qtablewidgetitem15 = tableWidgetCrossedLayer->horizontalHeaderItem(1);
        ___qtablewidgetitem15->setText(QCoreApplication::translate("PropertyGerberFastForm", "Generate", nullptr));
        QTableWidgetItem *___qtablewidgetitem16 = tableWidgetCrossedLayer->horizontalHeaderItem(2);
        ___qtablewidgetitem16->setText(QCoreApplication::translate("PropertyGerberFastForm", "Type", nullptr));
        QTableWidgetItem *___qtablewidgetitem17 = tableWidgetCrossedLayer->horizontalHeaderItem(3);
        ___qtablewidgetitem17->setText(QCoreApplication::translate("PropertyGerberFastForm", "Name", nullptr));
        label_8->setText(QCoreApplication::translate("PropertyGerberFastForm", "Base layer/composite", nullptr));
        label_6->setText(QCoreApplication::translate("PropertyGerberFastForm", "Setting crossed layer", nullptr));
        pushButtonSaveAlgoGen->setText(QCoreApplication::translate("PropertyGerberFastForm", "Save", nullptr));
        pushButtonLoadAlgoGen->setText(QCoreApplication::translate("PropertyGerberFastForm", "Load", nullptr));
        pushButtonMergeLoadAlgoGen->setText(QCoreApplication::translate("PropertyGerberFastForm", "Merge and Load", nullptr));
        tabWidgetProperty->setTabText(tabWidgetProperty->indexOf(PTab4), QCoreApplication::translate("PropertyGerberFastForm", "Make algorithm", nullptr));
        QTableWidgetItem *___qtablewidgetitem18 = tableWidgetGerberInfo->horizontalHeaderItem(0);
        ___qtablewidgetitem18->setText(QCoreApplication::translate("PropertyGerberFastForm", "Lr", nullptr));
        QTableWidgetItem *___qtablewidgetitem19 = tableWidgetGerberInfo->horizontalHeaderItem(1);
        ___qtablewidgetitem19->setText(QCoreApplication::translate("PropertyGerberFastForm", "Type", nullptr));
        QTableWidgetItem *___qtablewidgetitem20 = tableWidgetGerberInfo->horizontalHeaderItem(2);
        ___qtablewidgetitem20->setText(QCoreApplication::translate("PropertyGerberFastForm", "DCode", nullptr));
        QTableWidgetItem *___qtablewidgetitem21 = tableWidgetGerberInfo->horizontalHeaderItem(3);
        ___qtablewidgetitem21->setText(QCoreApplication::translate("PropertyGerberFastForm", "Position", nullptr));
    } // retranslateUi

};

namespace Ui {
    class PropertyGerberFastForm: public Ui_PropertyGerberFastForm {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_PROPERTYGERBERFASTFORM_H
