#ifndef CONTECNC3DSEQ_GLOBAL_H
#define CONTECNC3DSEQ_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef CONTECNC3DSEQ_LIB
# define CONTECNC3DSEQ_EXPORT Q_DECL_EXPORT
#else
# define CONTECNC3DSEQ_EXPORT Q_DECL_IMPORT
#endif

#endif // CONTECNC3DSEQ_GLOBAL_H
