# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = SharedPIOLib
DESTDIR = ../../../Lib/Release
CONFIG += staticlib debug
DEFINES += SHAREDPIOLIB_LIB
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += ./GeneratedFiles/$(ConfigurationName)
OBJECTS_DIR += release
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles
include(SharedPIOLib.pri)
