#ifndef SLAVEINDICATORINVISIBLE_GLOBAL_H
#define SLAVEINDICATORINVISIBLE_GLOBAL_H

#include <qglobal.h>

#ifdef SLAVEINDICATORINVISIBLE_LIB
# define SLAVEINDICATORINVISIBLE_EXPORT Q_DECL_EXPORT
#else
# define SLAVEINDICATORINVISIBLE_EXPORT Q_DECL_IMPORT
#endif

#endif // SLAVEINDICATORINVISIBLE_GLOBAL_H
