#ifndef PROPERTYARARRANGE_GLOBAL_H
#define PROPERTYARARRANGE_GLOBAL_H

#include <qglobal.h>

#ifdef PROPERTYARARRANGE_LIB
# define PROPERTYARARRANGE_EXPORT Q_DECL_EXPORT
#else
# define PROPERTYARARRANGE_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTYARARRANGE_GLOBAL_H
