#ifndef BUTTONTOSNAPIMAGE_GLOBAL_H
#define BUTTONTOSNAPIMAGE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONTOSNAPIMAGE_LIB
# define BUTTONTOSNAPIMAGE_EXPORT Q_DECL_EXPORT
#else
# define BUTTONTOSNAPIMAGE_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONTOSNAPIMAGE_GLOBAL_H
