#ifndef EASYLEVELALLOCATION_GLOBAL_H
#define EASYLEVELALLOCATION_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef EASYLEVELALLOCATION_LIB
# define EASYLEVELALLOCATION_EXPORT Q_DECL_EXPORT
#else
# define EASYLEVELALLOCATION_EXPORT Q_DECL_IMPORT
#endif

#endif // EASYLEVELALLOCATION_GLOBAL_H
