#ifndef BUTTONSELECTLEARNINGTARGETIMAGE_GLOBAL_H
#define BUTTONSELECTLEARNINGTARGETIMAGE_GLOBAL_H

#include <qglobal.h>

#ifdef BUTTONSELECTLEARNINGTARGETIMAGE_LIB
# define BUTTONSELECTLEARNINGTARGETIMAGE_EXPORT Q_DECL_EXPORT
#else
# define BUTTONSELECTLEARNINGTARGETIMAGE_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONSELECTLEARNINGTARGETIMAGE_GLOBAL_H
