# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./ButtonSelectLearningTargetImageResource.h \
    ./buttonselectlearningtargetimage_global.h \
    ./XSelectLearningPacket.h \
    ./ButtonSelectLearningTargetImage.h \
    ./SelectLearningImageForm.h
SOURCES += ./ButtonSelectLearningTargetImage.cpp \
    ../../Open/GUIDllCommon.cpp \
    ./ButtonSelectLearningTargetImageResource.cpp \
    ./SelectLearningImageForm.cpp \
    ../../Open/SystemVersion.cpp \
    ./XSelectLearningPacket.cpp
FORMS += ./SelectLearningImageForm.ui
RESOURCES += ButtonSelectLearningTargetImage.qrc
