#ifndef BUTTONSETOFFSET_GLOBAL_H
#define BUTTONSETOFFSET_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONSETOFFSET_LIB
# define BUTTONSETOFFSET_EXPORT Q_DECL_EXPORT
#else
# define BUTTONSETOFFSET_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONSETOFFSET_GLOBAL_H
