#ifndef BUTTONSTARTCAPTURECONTINUOUSLY_GLOBAL_H
#define BUTTONSTARTCAPTURECONTINUOUSLY_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONSTARTCAPTURECONTINUOUSLY_LIB
# define BUTTONSTARTCAPTURECONTINUOUSLY_EXPORT Q_DECL_EXPORT
#else
# define BUTTONSTARTCAPTURECONTINUOUSLY_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONSTARTCAPTURECONTINUOUSLY_GLOBAL_H
