#ifndef SHOWPARTIALIMAGINGLIST_GLOBAL_H
#define SHOWPARTIALIMAGINGLIST_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SHOWPARTIALIMAGINGLIST_LIB
# define SHOWPARTIALIMAGINGLIST_EXPORT Q_DECL_EXPORT
#else
# define SHOWPARTIALIMAGINGLIST_EXPORT Q_DECL_IMPORT
#endif

#endif // SHOWPARTIALIMAGINGLIST_GLOBAL_H
