#ifndef PROPERTYMULTIFILEMAP_GLOBAL_H
#define PROPERTYMULTIFILEMAP_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PROPERTYMULTIFILEMAP_LIB
# define PROPERTYMULTIFILEMAP_EXPORT Q_DECL_EXPORT
#else
# define PROPERTYMULTIFILEMAP_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTYMULTIFILEMAP_GLOBAL_H
