#ifndef LIGHTDLLREMOTECONTROLLER_GLOBAL_H
#define LIGHTDLLREMOTECONTROLLER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef LIGHTDLLREMOTECONTROLLER_LIB
# define LIGHTDLLREMOTECONTROLLER_EXPORT Q_DECL_EXPORT
#else
# define LIGHTDLLREMOTECONTROLLER_EXPORT Q_DECL_IMPORT
#endif

#endif // LIGHTDLLREMOTECONTROLLER_GLOBAL_H
