#ifndef DISPLAYSCANPHASENUMBER_GLOBAL_H
#define DISPLAYSCANPHASENUMBER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef DISPLAYSCANPHASENUMBER_LIB
# define DISPLAYSCANPHASENUMBER_EXPORT Q_DECL_EXPORT
#else
# define DISPLAYSCANPHASENUMBER_EXPORT Q_DECL_IMPORT
#endif

#endif // DISPLAYSCANPHASENUMBER_GLOBAL_H
