#ifndef REMOTECONTROLFORSERVER_GLOBAL_H
#define REMOTECONTROLFORSERVER_GLOBAL_H

#include <qglobal.h>

#ifdef REMOTECONTROLFORSERVER_LIB
# define REMOTECONTROLFORSERVER_EXPORT Q_DECL_EXPORT
#else
# define REMOTECONTROLFORSERVER_EXPORT Q_DECL_IMPORT
#endif

#endif // REMOTECONTROLFORSERVER_GLOBAL_H
