#ifndef PANELDOCKINGBASE_GLOBAL_H
#define PANELDOCKINGBASE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PANELDOCKINGBASE_LIB
# define PANELDOCKINGBASE_EXPORT Q_DECL_EXPORT
#else
# define PANELDOCKINGBASE_EXPORT Q_DECL_IMPORT
#endif

#endif // PANELDOCKINGBASE_GLOBAL_H
