#ifndef REALTIMEGRAPHMEASURE1_GLOBAL_H
#define REALTIMEGRAPHMEASURE1_GLOBAL_H

#include <qglobal.h>

#ifdef REALTIMEGRAPHMEASURE1_LIB
# define REALTIMEGRAPHMEASURE1_EXPORT Q_DECL_EXPORT
#else
# define REALTIMEGRAPHMEASURE1_EXPORT Q_DECL_IMPORT
#endif

#endif // REALTIMEGRAPHMEASURE1_GLOBAL_H
