#ifndef EVOBJINSPECTIONID_GLOBAL_H
#define EVOBJINSPECTIONID_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef EVOBJINSPECTIONID_LIB
# define EVOBJINSPECTIONID_EXPORT Q_DECL_EXPORT
#else
# define EVOBJINSPECTIONID_EXPORT Q_DECL_IMPORT
#endif

#endif // EVOBJINSPECTIONID_GLOBAL_H
