#ifndef INTEGRATIONDISPLAYMASTERIMAGE_GLOBAL_H
#define INTEGRATIONDISPLAYMASTERIMAGE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef INTEGRATIONDISPLAYMASTERIMAGE_LIB
# define INTEGRATIONDISPLAYMASTERIMAGE_EXPORT Q_DECL_EXPORT
#else
# define INTEGRATIONDISPLAYMASTERIMAGE_EXPORT Q_DECL_IMPORT
#endif

#endif // INTEGRATIONDISPLAYMASTERIMAGE_GLOBAL_H
