#ifndef AUTOPCBHOLEALIGNER_GLOBAL_H
#define AUTOPCBHOLEALIGNER_GLOBAL_H

#include <qglobal.h>

#ifdef AUTOPCBHOLEALIGNER_LIB
# define AUTOPCBHOLEALIGNER_EXPORT Q_DECL_EXPORT
#else
# define AUTOPCBHOLEALIGNER_EXPORT Q_DECL_IMPORT
#endif

#endif // AUTOPCBHOLEALIGNER_GLOBAL_H
