#ifndef PIECEREVIEWSIDE_GLOBAL_H
#define PIECEREVIEWSIDE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PIECEREVIEWSIDE_LIB
# define PIECEREVIEWSIDE_EXPORT Q_DECL_EXPORT
#else
# define PIECEREVIEWSIDE_EXPORT Q_DECL_IMPORT
#endif

#endif // PIECEREVIEWSIDE_GLOBAL_H
