#ifndef LINEPATTERNINSPECTION_GLOBAL_H
#define LINEPATTERNINSPECTION_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef LINEPATTERNINSPECTION_LIB
# define LINEPATTERNINSPECTION_EXPORT Q_DECL_EXPORT
#else
# define LINEPATTERNINSPECTION_EXPORT Q_DECL_IMPORT
#endif

#endif // LINEPATTERNINSPECTION_GLOBAL_H
