#ifndef FILTERCOLORSHIFT_GLOBAL_H
#define FILTERCOLORSHIFT_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef FILTERCOLORSHIFT_LIB
# define FILTERCOLORSHIFT_EXPORT Q_DECL_EXPORT
#else
# define FILTERCOLORSHIFT_EXPORT Q_DECL_IMPORT
#endif

#endif // FILTERCOLORSHIFT_GLOBAL_H
