#ifndef NETWORKPIOCLIENT_GLOBAL_H
#define NETWORKPIOCLIENT_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef NETWORKPIOCLIENT_LIB
# define NETWORKPIOCLIENT_EXPORT Q_DECL_EXPORT
#else
# define NETWORKPIOCLIENT_EXPORT Q_DECL_IMPORT
#endif

#endif // NETWORKPIOCLIENT_GLOBAL_H
