#ifndef FILTERREVERSELENSSOMELAYER_GLOBAL_H
#define FILTERREVERSELENSSOMELAYER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef FILTERREVERSELENSSOMELAYER_LIB
# define FILTERREVERSELENSSOMELAYER_EXPORT Q_DECL_EXPORT
#else
# define FILTERREVERSELENSSOMELAYER_EXPORT Q_DECL_IMPORT
#endif

#endif // FILTERREVERSELENSSOMELAYER_GLOBAL_H
