#ifndef INTEGRATIONSAVEMASTER_GLOBAL_H
#define INTEGRATIONSAVEMASTER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef INTEGRATIONSAVEMASTER_LIB
# define INTEGRATIONSAVEMASTER_EXPORT Q_DECL_EXPORT
#else
# define INTEGRATIONSAVEMASTER_EXPORT Q_DECL_IMPORT
#endif

#endif // INTEGRATIONSAVEMASTER_GLOBAL_H
