#ifndef SHOWMINMAXBUTTON_GLOBAL_H
#define SHOWMINMAXBUTTON_GLOBAL_H

#include <qglobal.h>

#ifdef SHOWMINMAXBUTTON_LIB
# define SHOWMINMAXBUTTON_EXPORT Q_DECL_EXPORT
#else
# define SHOWMINMAXBUTTON_EXPORT Q_DECL_IMPORT
#endif

#endif // SHOWMINMAXBUTTON_GLOBAL_H
