#ifndef PROPERTYAREASHADER_GLOBAL_H
#define PROPERTYAREASHADER_GLOBAL_H

#include <qglobal.h>

#ifdef PROPERTYAREASHADER_LIB
# define PROPERTYAREASHADER_EXPORT Q_DECL_EXPORT
#else
# define PROPERTYAREASHADER_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTYAREASHADER_GLOBAL_H
