#ifndef IMAGECHECKER_GLOBAL_H
#define IMAGECHECKER_GLOBAL_H

#include <qglobal.h>

#ifdef IMAGECHECKER_LIB
# define IMAGECHECKER_EXPORT Q_DECL_EXPORT
#else
# define IMAGECHECKER_EXPORT Q_DECL_IMPORT
#endif

#endif // IMAGECHECKER_GLOBAL_H
