#ifndef INTEGRATIONTHUMBNAIL_GLOBAL_H
#define INTEGRATIONTHUMBNAIL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef INTEGRATIONTHUMBNAIL_LIB
# define INTEGRATIONTHUMBNAIL_EXPORT Q_DECL_EXPORT
#else
# define INTEGRATIONTHUMBNAIL_EXPORT Q_DECL_IMPORT
#endif

#endif // INTEGRATIONTHUMBNAIL_GLOBAL_H
