#ifndef TRANSDATABASELIB_GLOBAL_H
#define TRANSDATABASELIB_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef TRANSDATABASELIB_LIB
# define TRANSDATABASELIB_EXPORT Q_DECL_EXPORT
#else
# define TRANSDATABASELIB_EXPORT Q_DECL_IMPORT
#endif

#endif // TRANSDATABASELIB_GLOBAL_H
