#ifndef LEDCONTROL16F_GLOBAL_H
#define LEDCONTROL16F_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef LEDCONTROL16F_LIB
# define LEDCONTROL16F_EXPORT Q_DECL_EXPORT
#else
# define LEDCONTROL16F_EXPORT Q_DECL_IMPORT
#endif

#endif // LEDCONTROL16F_GLOBAL_H
