#ifndef CONTROLHAYASHITOKEIGUI_GLOBAL_H
#define CONTROLHAYASHITOKEIGUI_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef CONTROLHAYASHITOKEIGUI_LIB
# define CONTROLHAYASHITOKEIGUI_EXPORT Q_DECL_EXPORT
#else
# define CONTROLHAYASHITOKEIGUI_EXPORT Q_DECL_IMPORT
#endif

#endif // CONTROLHAYASHITOKEIGUI_GLOBAL_H
