#ifndef SKIPMARKIMAGEPANEL_GLOBAL_H
#define SKIPMARKIMAGEPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SKIPMARKIMAGEPANEL_LIB
# define SKIPMARKIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define SKIPMARKIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // SKIPMARKIMAGEPANEL_GLOBAL_H
