#ifndef VIRTUALPIOADAPTER_GLOBAL_H
#define VIRTUALPIOADAPTER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef VIRTUALPIOADAPTER_LIB
# define VIRTUALPIOADAPTER_EXPORT Q_DECL_EXPORT
#else
# define VIRTUALPIOADAPTER_EXPORT Q_DECL_IMPORT
#endif

#endif // VIRTUALPIOADAPTER_GLOBAL_H
