#ifndef AUTOSAVEIMAGEBUTTONSAVE_GLOBAL_H
#define AUTOSAVEIMAGEBUTTONSAVE_GLOBAL_H

#include <qglobal.h>

#ifdef AUTOSAVEIMAGEBUTTONSAVE_LIB
# define AUTOSAVEIMAGEBUTTONSAVE_EXPORT Q_DECL_EXPORT
#else
# define AUTOSAVEIMAGEBUTTONSAVE_EXPORT Q_DECL_IMPORT
#endif

#endif // AUTOSAVEIMAGEBUTTONSAVE_GLOBAL_H
