#ifndef GERBERFASTIMAGEPANEL_GLOBAL_H
#define GERBERFASTIMAGEPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef GERBERFASTIMAGEPANEL_LIB
# define GERBERFASTIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define GERBERFASTIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // GERBERFASTIMAGEPANEL_GLOBAL_H
