#ifndef BUTTONREWINDINSPECTION_GLOBAL_H
#define BUTTONREWINDINSPECTION_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONREWINDINSPECTION_LIB
# define BUTTONREWINDINSPECTION_EXPORT Q_DECL_EXPORT
#else
# define BUTTONREWINDINSPECTION_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONREWINDINSPECTION_GLOBAL_H
