#ifndef TREEMASTERSHOWRESULTLIST_GLOBAL_H
#define TREEMASTERSHOWRESULTLIST_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef TREEMASTERSHOWRESULTLIST_LIB
# define TREEMASTERSHOWRESULTLIST_EXPORT Q_DECL_EXPORT
#else
# define TREEMASTERSHOWRESULTLIST_EXPORT Q_DECL_IMPORT
#endif

#endif // TREEMASTERSHOWRESULTLIST_GLOBAL_H
