#ifndef FILTERHORIZONTALLINEAR_GLOBAL_H
#define FILTERHORIZONTALLINEAR_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef FILTERHORIZONTALLINEAR_LIB
# define FILTERHORIZONTALLINEAR_EXPORT Q_DECL_EXPORT
#else
# define FILTERHORIZONTALLINEAR_EXPORT Q_DECL_IMPORT
#endif

#endif // FILTERHORIZONTALLINEAR_GLOBAL_H
