#ifndef SHOWSIZEPANELSEQ_GLOBAL_H
#define SHOWSIZEPANELSEQ_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SHOWSIZEPANELSEQ_LIB
# define SHOWSIZEPANELSEQ_EXPORT Q_DECL_EXPORT
#else
# define SHOWSIZEPANELSEQ_EXPORT Q_DECL_IMPORT
#endif

#endif // SHOWSIZEPANELSEQ_GLOBAL_H
