#ifndef MAKEAVERAGEIMAGE_GLOBAL_H
#define MAKEAVERAGEIMAGE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef MAKEAVERAGEIMAGE_LIB
# define MAKEAVERAGEIMAGE_EXPORT Q_DECL_EXPORT
#else
# define MAKEAVERAGEIMAGE_EXPORT Q_DECL_IMPORT
#endif

#endif // MAKEAVERAGEIMAGE_GLOBAL_H
