#ifndef PROPERTYRESULTIMPORTANCE_GLOBAL_H
#define PROPERTYRESULTIMPORTANCE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PROPERTYRESULTIMPORTANCE_LIB
# define PROPERTYRESULTIMPORTANCE_EXPORT Q_DECL_EXPORT
#else
# define PROPERTYRESULTIMPORTANCE_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTYRESULTIMPORTANCE_GLOBAL_H
