#ifndef STACKSTOSWITCHMASTERTARGET_GLOBAL_H
#define STACKSTOSWITCHMASTERTARGET_GLOBAL_H

#include <qglobal.h>

#ifdef STACKSTOSWITCHMASTERTARGET_LIB
# define STACKSTOSWITCHMASTERTARGET_EXPORT Q_DECL_EXPORT
#else
# define STACKSTOSWITCHMASTERTARGET_EXPORT Q_DECL_IMPORT
#endif

#endif // STACKSTOSWITCHMASTERTARGET_GLOBAL_H
