#ifndef PIECEDEFIMAGEPANEL_GLOBAL_H
#define PIECEDEFIMAGEPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PIECEDEFIMAGEPANEL_LIB
# define PIECEDEFIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define PIECEDEFIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // PIECEDEFIMAGEPANEL_GLOBAL_H
