#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(EASYSHOWNGMESSAGEFORDATAVALIDATION_LIB)
#  define EASYSHOWNGMESSAGEFORDATAVALIDATION_EXPORT Q_DECL_EXPORT
# else
#  define EASYSHOWNGMESSAGEFORDATAVALIDATION_EXPORT Q_DECL_IMPORT
# endif
#else
# define EASYSHOWNGMESSAGEFORDATAVALIDATION_EXPORT
#endif
