#ifndef CHANGEWINDOWSIZEINVISIBLE_GLOBAL_H
#define CHANGEWINDOWSIZEINVISIBLE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef CHANGEWINDOWSIZEINVISIBLE_LIB
# define CHANGEWINDOWSIZEINVISIBLE_EXPORT Q_DECL_EXPORT
#else
# define CHANGEWINDOWSIZEINVISIBLE_EXPORT Q_DECL_IMPORT
#endif

#endif // CHANGEWINDOWSIZEINVISIBLE_GLOBAL_H
