# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = PropertyRobotAction
DESTDIR = ../
CONFIG += release
DEFINES += PROPERTYROBOTACTION_LIB
LIBS += -L"./../../Lib/Release" \
    -lComponent \
    -lServiceLib
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += .
RCC_DIR += GeneratedFiles
include(PropertyRobotAction.pri)
