#ifndef HASPLOCKSTARTLIB_GLOBAL_H
#define HASPLOCKSTARTLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef HASPLOCKSTARTLIB_LIB
# define HASPLOCKSTARTLIB_EXPORT Q_DECL_EXPORT
#else
# define HASPLOCKSTARTLIB_EXPORT Q_DECL_IMPORT
#endif

#endif // HASPLOCKSTARTLIB_GLOBAL_H
