# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = HaspLockStartLib
DESTDIR = ../../../Lib/Release
CONFIG += staticlib release
DEFINES += HASPLOCKSTARTLIB_LIB
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += ./GeneratedFiles/$(ConfigurationName)
OBJECTS_DIR += release
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles
include(HaspLockStartLib.pri)
