#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(CONTROLMULTISPECTRALSCANNER_LIB)
#  define CONTROLMULTISPECTRALSCANNER_EXPORT Q_DECL_EXPORT
# else
#  define CONTROLMULTISPECTRALSCANNER_EXPORT Q_DECL_IMPORT
# endif
#else
# define CONTROLMULTISPECTRALSCANNER_EXPORT
#endif
