#ifndef FILTERREVERSELENSONELAYER_GLOBAL_H
#define FILTERREVERSELENSONELAYER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef FILTERREVERSELENSONELAYER_LIB
# define FILTERREVERSELENSONELAYER_EXPORT Q_DECL_EXPORT
#else
# define FILTERREVERSELENSONELAYER_EXPORT Q_DECL_IMPORT
#endif

#endif // FILTERREVERSELENSONELAYER_GLOBAL_H
