#ifndef EXECUTEVISUALIZER_GLOBAL_H
#define EXECUTEVISUALIZER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef EXECUTEVISUALIZER_LIB
# define EXECUTEVISUALIZER_EXPORT Q_DECL_EXPORT
#else
# define EXECUTEVISUALIZER_EXPORT Q_DECL_IMPORT
#endif

#endif // EXECUTEVISUALIZER_GLOBAL_H
