#ifndef BUTTONSETMACHINE_GLOBAL_H
#define BUTTONSETMACHINE_GLOBAL_H

#include <qglobal.h>

#ifdef BUTTONSETMACHINE_LIB
# define BUTTONSETMACHINE_EXPORT Q_DECL_EXPORT
#else
# define BUTTONSETMACHINE_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONSETMACHINE_GLOBAL_H
