#ifndef SHOWHISTORYLISTFORREVIEW_GLOBAL_H
#define SHOWHISTORYLISTFORREVIEW_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SHOWHISTORYLISTFORREVIEW_LIB
# define SHOWHISTORYLISTFORREVIEW_EXPORT Q_DECL_EXPORT
#else
# define SHOWHISTORYLISTFORREVIEW_EXPORT Q_DECL_IMPORT
#endif

#endif // SHOWHIERARCHYFORREVIEW_GLOBAL_H
