#ifndef EVOBJSTRATEGYCOUNTER_GLOBAL_H
#define EVOBJSTRATEGYCOUNTER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef EVOBJSTRATEGYCOUNTER_LIB
# define EVOBJSTRATEGYCOUNTER_EXPORT Q_DECL_EXPORT
#else
# define EVOBJSTRATEGYCOUNTER_EXPORT Q_DECL_IMPORT
#endif

#endif // EVOBJSTRATEGYCOUNTER_GLOBAL_H
