#ifndef BUTTONPASSWORDENABLER_GLOBAL_H
#define BUTTONPASSWORDENABLER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONPASSWORDENABLER_LIB
# define BUTTONPASSWORDENABLER_EXPORT Q_DECL_EXPORT
#else
# define BUTTONPASSWORDENABLER_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONPASSWORDENABLER_GLOBAL_H
