#ifndef PROPERTYCHECKEVERYDAY_GLOBAL_H
#define PROPERTYCHECKEVERYDAY_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PROPERTYCHECKEVERYDAY_LIB
# define PROPERTYCHECKEVERYDAY_EXPORT Q_DECL_EXPORT
#else
# define PROPERTYCHECKEVERYDAY_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTYCHECKEVERYDAY_GLOBAL_H
