#ifndef SHOWHISTGRAMTOTAL_GLOBAL_H
#define SHOWHISTGRAMTOTAL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SHOWHISTGRAMTOTAL_LIB
# define SHOWHISTGRAMTOTAL_EXPORT Q_DECL_EXPORT
#else
# define SHOWHISTGRAMTOTAL_EXPORT Q_DECL_IMPORT
#endif

#endif // SHOWHISTGRAMTOTAL_GLOBAL_H
