#ifndef BUTTONMOVEVRSFIXEDPOINT_GLOBAL_H
#define BUTTONMOVEVRSFIXEDPOINT_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONMOVEVRSFIXEDPOINT_LIB
# define BUTTONMOVEVRSFIXEDPOINT_EXPORT Q_DECL_EXPORT
#else
# define BUTTONMOVEVRSFIXEDPOINT_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONMOVEVRSFIXEDPOINT_GLOBAL_H
