#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(RASTERINSPECTIONIMAGEPANEL_LIB)
#  define RASTERINSPECTIONIMAGEPANEL_EXPORT Q_DECL_EXPORT
# else
#  define RASTERINSPECTIONIMAGEPANEL_EXPORT Q_DECL_IMPORT
# endif
#else
# define RASTERINSPECTIONIMAGEPANEL_EXPORT
#endif
