#ifndef EXECUTEMACROLIST_GLOBAL_H
#define EXECUTEMACROLIST_GLOBAL_H

#include <qglobal.h>

#ifdef EXECUTEMACROLIST_LIB
# define EXECUTEMACROLIST_EXPORT Q_DECL_EXPORT
#else
# define EXECUTEMACROLIST_EXPORT Q_DECL_IMPORT
#endif

#endif // EXECUTEMACROLIST_GLOBAL_H
