# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./SelectLibraryInMaskResource.h \
    $$PWD/GeneratePatternEdgeOnSelectedDialog.h \
    ./selectlibraryinmask_global.h \
    ./SelectLibraryInMaskForm.h \
    ./GenerateMaskOnSelectedItemsEdgeDialog.h
SOURCES += ./SelectLibraryInMaskForm.cpp \
    $$PWD/GeneratePatternEdgeOnSelectedDialog.cpp \
    ./SelectLibraryInMaskResource.cpp \
    ./GenerateMaskOnSelectedItemsEdgeDialog.cpp
FORMS += ./SelectLibraryInMaskForm.ui \
    $$PWD/GeneratePatternEdgeOnSelectedDialog.ui \
    ./GenerateMaskOnSelectedItemsEdgeDialog.ui
TRANSLATIONS += ./selectlibraryinmask_ja.ts
RESOURCES += SelectLibraryInMask.qrc
