#ifndef SHOWPRINTTOTALBLADE_GLOBAL_H
#define SHOWPRINTTOTALBLADE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SHOWPRINTTOTALBLADE_LIB
# define SHOWPRINTTOTALBLADE_EXPORT Q_DECL_EXPORT
#else
# define SHOWPRINTTOTALBLADE_EXPORT Q_DECL_IMPORT
#endif

#endif // SHOWPRINTTOTALBLADE_GLOBAL_H
