# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = ShowPrintTotalBlade
DESTDIR = ../../../GUI
CONFIG += debug
DEFINES += SHOWPRINTTOTALBLADE_LIB
LIBS += -L"./../../../Lib/Release" \
    -lServiceLib \
    -lIntegrationLib
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += .
RCC_DIR += ./GeneratedFiles
include(ShowPrintTotalBlade.pri)
