#ifndef IMACCONTROLBYLAN_GLOBAL_H
#define IMACCONTROLBYLAN_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef IMACCONTROLBYLAN_LIB
# define IMACCONTROLBYLAN_EXPORT Q_DECL_EXPORT
#else
# define IMACCONTROLBYLAN_EXPORT Q_DECL_IMPORT
#endif

#endif // IMACCONTROLBYLAN_GLOBAL_H
