#ifndef BUTTONEXECUTECOMMAND_GLOBAL_H
#define BUTTONEXECUTECOMMAND_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONEXECUTECOMMAND_LIB
# define BUTTONEXECUTECOMMAND_EXPORT Q_DECL_EXPORT
#else
# define BUTTONEXECUTECOMMAND_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONEXECUTECOMMAND_GLOBAL_H
