#ifndef HOOKLEARNINGREGISTOKNG_GLOBAL_H
#define HOOKLEARNINGREGISTOKNG_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef HOOKLEARNINGREGISTOKNG_LIB
# define HOOKLEARNINGREGISTOKNG_EXPORT Q_DECL_EXPORT
#else
# define HOOKLEARNINGREGISTOKNG_EXPORT Q_DECL_IMPORT
#endif

#endif // HOOKLEARNINGREGISTOKNG_GLOBAL_H
