#ifndef EASYDENTMEASUREIMAGEPANEL_GLOBAL_H
#define EASYDENTMEASUREIMAGEPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef EASYDENTMEASUREIMAGEPANEL_LIB
# define EASYDENTMEASUREIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define EASYDENTMEASUREIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // EASYDENTMEASUREIMAGEPANEL_GLOBAL_H
