#ifndef LEDCONTROL16EKIDA_GLOBAL_H
#define LEDCONTROL16EKIDA_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef LEDCONTROL16EKIDA_LIB
# define LEDCONTROL16EKIDA_EXPORT Q_DECL_EXPORT
#else
# define LEDCONTROL16EKIDA_EXPORT Q_DECL_IMPORT
#endif

#endif // LEDCONTROL16EKIDA_GLOBAL_H
