# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = JDTUnpacker
DESTDIR = ../
CONFIG += debug
DEFINES += QT_LARGEFILE_SUPPORT
LIBS += -L"./../Lib/Release" \
    -lTransDatabaseLib \
    -lServiceLib
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += .
RCC_DIR += .
include(JDTUnpacker.pri)
win32:RC_FILE = JDTUnpacker.rc
