#ifndef CHECKEVERYDAYIMAGEPANEL_GLOBAL_H
#define CHECKEVERYDAYIMAGEPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef CHECKEVERYDAYIMAGEPANEL_LIB
# define CHECKEVERYDAYIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define CHECKEVERYDAYIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // CHECKEVERYDAYIMAGEPANEL_GLOBAL_H
