#ifndef ZREGULATIONIMAGEPANEL_GLOBAL_H
#define ZREGULATIONIMAGEPANEL_GLOBAL_H

#include <qglobal.h>

#ifdef ZREGULATIONIMAGEPANEL_LIB
# define ZREGULATIONIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define ZREGULATIONIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // ZREGULATIONIMAGEPANEL_GLOBAL_H
