#ifndef SHOWTOPBOTTOMSIDEINFO_GLOBAL_H
#define SHOWTOPBOTTOMSIDEINFO_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SHOWTOPBOTTOMSIDEINFO_LIB
# define SHOWTOPBOTTOMSIDEINFO_EXPORT Q_DECL_EXPORT
#else
# define SHOWTOPBOTTOMSIDEINFO_EXPORT Q_DECL_IMPORT
#endif

#endif // SHOWTOPBOTTOMSIDEINFO_GLOBAL_H
