#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(INTEGRATIONBUTTONSAVEALGORITHM_LIB)
#  define INTEGRATIONBUTTONSAVEALGORITHM_EXPORT Q_DECL_EXPORT
# else
#  define INTEGRATIONBUTTONSAVEALGORITHM_EXPORT Q_DECL_IMPORT
# endif
#else
# define INTEGRATIONBUTTONSAVEALGORITHM_EXPORT
#endif
