#ifndef LISTGENERATECHILDLIBRARY_GLOBAL_H
#define LISTGENERATECHILDLIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef LISTGENERATECHILDLIBRARY_LIB
# define LISTGENERATECHILDLIBRARY_EXPORT Q_DECL_EXPORT
#else
# define LISTGENERATECHILDLIBRARY_EXPORT Q_DECL_IMPORT
#endif

#endif // LISTGENERATECHILDLIBRARY_GLOBAL_H
