#ifndef DISPLAYREALTIMEGRAPH_GLOBAL_H
#define DISPLAYREALTIMEGRAPH_GLOBAL_H

#include <qglobal.h>

#ifdef DISPLAYREALTIMEGRAPH_LIB
# define DISPLAYREALTIMEGRAPH_EXPORT Q_DECL_EXPORT
#else
# define DISPLAYREALTIMEGRAPH_EXPORT Q_DECL_IMPORT
#endif

#endif // DISPLAYREALTIMEGRAPH_GLOBAL_H
