#ifndef MAKEAVERAGEIMAGEPANEL_GLOBAL_H
#define MAKEAVERAGEIMAGEPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef MAKEAVERAGEIMAGEPANEL_LIB
# define MAKEAVERAGEIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define MAKEAVERAGEIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // MAKEAVERAGEIMAGEPANEL_GLOBAL_H
