#ifndef CHECKEVERYDAY_GLOBAL_H
#define CHECKEVERYDAY_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef CHECKEVERYDAY_LIB
# define CHECKEVERYDAY_EXPORT Q_DECL_EXPORT
#else
# define CHECKEVERYDAY_EXPORT Q_DECL_IMPORT
#endif

#endif // CHECKEVERYDAY_GLOBAL_H
