#ifndef BUTTONSELECTCOUNTEDLOT_GLOBAL_H
#define BUTTONSELECTCOUNTEDLOT_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONSELECTCOUNTEDLOT_LIB
# define BUTTONSELECTCOUNTEDLOT_EXPORT Q_DECL_EXPORT
#else
# define BUTTONSELECTCOUNTEDLOT_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONSELECTCOUNTEDLOT_GLOBAL_H
