#ifndef BUTTONTRANSFERREQUIREGLOBALPARAM_GLOBAL_H
#define BUTTONTRANSFERREQUIREGLOBALPARAM_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONTRANSFERREQUIREGLOBALPARAM_LIB
# define BUTTONTRANSFERREQUIREGLOBALPARAM_EXPORT Q_DECL_EXPORT
#else
# define BUTTONTRANSFERREQUIREGLOBALPARAM_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONTRANSFERREQUIREGLOBALPARAM_GLOBAL_H
