#ifndef DOTCOLORMATCHING_GLOBAL_H
#define DOTCOLORMATCHING_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef DOTCOLORMATCHING_LIB
# define DOTCOLORMATCHING_EXPORT Q_DECL_EXPORT
#else
# define DOTCOLORMATCHING_EXPORT Q_DECL_IMPORT
#endif

#endif // DOTCOLORMATCHING_GLOBAL_H
