#ifndef LINEENHANCER1LIMAGEPANEL_GLOBAL_H
#define LINEENHANCER1LIMAGEPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef LINEENHANCER1LIMAGEPANEL_LIB
# define LINEENHANCER1LIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define LINEENHANCER1LIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // LINEENHANCER1LIMAGEPANEL_GLOBAL_H
