#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(SERVICEEXECUTIONSHADOW_LIB)
#  define SERVICEEXECUTIONSHADOW_EXPORT Q_DECL_EXPORT
# else
#  define SERVICEEXECUTIONSHADOW_EXPORT Q_DECL_IMPORT
# endif
#else
# define SERVICEEXECUTIONSHADOW_EXPORT
#endif
