# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


TEMPLATE = subdirs
SUBDIRS += /CartonMenu/CartonMenu.pro \
    /ShowPrintTotalBlade/ShowPrintTotalBlade.pro \
    /EasyPropertyMasking/EasyPropertyMasking.pro \
    /EasyPropertyAlignment/EasyPropertyAlignment.pro \
    /EasyPropertyDentMeasure/EasyPropertyDentMeasure.pro \
    /EasyPropertyDotColorMatch/EasyPropertyDotColorMatch.pro \
    /ShowKidaMeasureResult/ShowKidaMeasureResult.pro \
    /GraphTrendKida/GraphTrendKida.pro \
    /EasyAlignmentImagePanel/EasyAlignmentImagePanel.pro \
    /EasyDentMeasureImagePanel/EasyDentMeasureImagePanel.pro \
    /EasyDotColorMatchImagePanel/EasyDotColorMatchImagePanel.pro \
    /EasyMaskingImagePanel/EasyMaskingImagePanel.pro \
    /EasySwitchPhaseImagePanel/EasySwitchPhaseImagePanel.pro \
    /EasyPropertySwitchPhase/EasyPropertySwitchPhase.pro \
    /EasyDXFOperationImagePanel/EasyDXFOperationImagePanel.pro \
    /EasyPropertyDXFOperation/EasyPropertyDXFOperation.pro \
    /ResultKidaOutput/ResultKidaOutput.pro \
    /ButtonSettingThreshold/ButtonSettingThreshold.pro \
    /ResultKidaInspection/ResultKidaInspection.pro \
    /IntegrationResultLoader/IntegrationResultLoader.pro \
    /WizardMasterMenu/WizardMasterMenu.pro \
    /EasyGenerateMask/EasyGenerateMask.pro \
    /EasyGenerateAlignment/EasyGenerateAlignment.pro \
    /EasyGenerateInspection/EasyGenerateInspection.pro \
    /IntegrationOutputController/IntegrationOutputController.pro \
    /EasyLevelAllocation/EasyLevelAllocation.pro \
    /ButtonResetThresholdDotColorMatching/ButtonResetThresholdDotColorMatching.pro \
    /ShowBladeSetting/ShowBladeSetting.pro \
    /BladeNGList/BladeNGList.pro \
    /EasyColorDifferenceImagePanel/EasyColorDifferenceImagePanel.pro \
    /EasyPropertyColorDifference/EasyPropertyColorDifference.pro \
    /ButtonSettingColorDifference/ButtonSettingColorDifference.pro \
    /GraphTrendColorDifference/GraphTrendColorDifference.pro \
    /EasyMakeAverageImage/EasyMakeAverageImage.pro \
    /EasyMakeAverageImagePanel/EasyMakeAverageImagePanel.pro \
    /ButtonSettingBarcode/ButtonSettingBarcode.pro \
    /EasyBCodeImagePanel/EasyBCodeImagePanel.pro \
    /EasyPropertyBCode/EasyPropertyBCode.pro \
    /ControllerAccessor/ControllerAccessor.pro \
    /ControllerAccessorRPI/ControllerAccessorRPI.pro \
    /EasyRasterImagePanel/EasyRasterImagePanel.pro \
    /EasyPropertyRaster/EasyPropertyRaster.pro \
    /EasyMeasureImagePanel/EasyMeasureImagePanel.pro \
    /EasyPropertyMeasure/EasyPropertyMeasure.pro \
    /ButtonShowConfirm/ButtonShowConfirm.pro \
    /EasyShowAlignment/EasyShowAlignment.pro
