#ifndef PROPERTYDYNAMICCLASSIFY_GLOBAL_H
#define PROPERTYDYNAMICCLASSIFY_GLOBAL_H

#include <qglobal.h>

#ifdef PROPERTYDYNAMICCLASSIFY_LIB
# define PROPERTYDYNAMICCLASSIFY_EXPORT Q_DECL_EXPORT
#else
# define PROPERTYDYNAMICCLASSIFY_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTYDYNAMICCLASSIFY_GLOBAL_H
