#ifndef OPERATETHROUGHNET_GLOBAL_H
#define OPERATETHROUGHNET_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef OPERATETHROUGHNET_LIB
# define OPERATETHROUGHNET_EXPORT Q_DECL_EXPORT
#else
# define OPERATETHROUGHNET_EXPORT Q_DECL_IMPORT
#endif

#endif // OPERATETHROUGHNET_GLOBAL_H
