#ifndef LISTCONDITION_GLOBAL_H
#define LISTCONDITION_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef LISTCONDITION_LIB
# define LISTCONDITION_EXPORT Q_DECL_EXPORT
#else
# define LISTCONDITION_EXPORT Q_DECL_IMPORT
#endif

#endif // LISTCONDITION_GLOBAL_H
