#ifndef REVIEWZHEIGHT_GLOBAL_H
#define REVIEWZHEIGHT_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef REVIEWZHEIGHT_LIB
# define REVIEWZHEIGHT_EXPORT Q_DECL_EXPORT
#else
# define REVIEWZHEIGHT_EXPORT Q_DECL_IMPORT
#endif

#endif // REVIEWZHEIGHT_GLOBAL_H
