#ifndef SPOTREDUCERIMAGEPANEL_GLOBAL_H
#define SPOTREDUCERIMAGEPANEL_GLOBAL_H

#include <qglobal.h>

#ifdef SPOTREDUCERIMAGEPANEL_LIB
# define SPOTREDUCERIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define SPOTREDUCERIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // SPOTREDUCERIMAGEPANEL_GLOBAL_H
