#ifndef FILTERROTATIONMIRROR_GLOBAL_H
#define FILTERROTATIONMIRROR_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef FILTERROTATIONMIRROR_LIB
# define FILTERROTATIONMIRROR_EXPORT Q_DECL_EXPORT
#else
# define FILTERROTATIONMIRROR_EXPORT Q_DECL_IMPORT
#endif

#endif // FILTERROTATIONMIRROR_GLOBAL_H
