#ifndef BUTTONTOSHOWDIALOGONGENERALSTOCKER_GLOBAL_H
#define BUTTONTOSHOWDIALOGONGENERALSTOCKER_GLOBAL_H

#include <qglobal.h>

#ifdef BUTTONTOSHOWDIALOGONGENERALSTOCKER_LIB
# define BUTTONTOSHOWDIALOGONGENERALSTOCKER_EXPORT Q_DECL_EXPORT
#else
# define BUTTONTOSHOWDIALOGONGENERALSTOCKER_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONTOSHOWDIALOGONGENERALSTOCKER_GLOBAL_H
