# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./ButtonToShowDialogOnGeneralStockerResource.h \
    ./buttontoshowdialogongeneralstocker_global.h \
    ../../Open/XDLLOnly.h \
    ../../Open/XDLLType.h \
    ../../Open/XGUIDLL.h \
    ./SelectGeneralStocker.h \
    ./ButtonToShowDialogOnGeneralStocker.h
SOURCES += ./ButtonToShowDialogOnGeneralStocker.cpp \
    ../../Open/GUIDllCommon.cpp \
    ../../Open/SystemVersion.cpp \
    ./ButtonToShowDialogOnGeneralStockerResource.cpp \
    ./SelectGeneralStocker.cpp
FORMS += ./SelectGeneralStocker.ui
RESOURCES += ButtonToShowDialogOnGeneralStocker.qrc
