#ifndef EASYGENERATEINSPECTION_GLOBAL_H
#define EASYGENERATEINSPECTION_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef EASYGENERATEINSPECTION_LIB
# define EASYGENERATEINSPECTION_EXPORT Q_DECL_EXPORT
#else
# define EASYGENERATEINSPECTION_EXPORT Q_DECL_IMPORT
#endif

#endif // EASYGENERATEINSPECTION_GLOBAL_H
