#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(GENERALSTOCKERKIDAYAMASHITA_LIB)
#  define GENERALSTOCKERKIDAYAMASHITA_EXPORT Q_DECL_EXPORT
# else
#  define GENERALSTOCKERKIDAYAMASHITA_EXPORT Q_DECL_IMPORT
# endif
#else
# define GENERALSTOCKERKIDAYAMASHITA_EXPORT
#endif
