#ifndef PROPERTYLINEENHANCER_GLOBAL_H
#define PROPERTYLINEENHANCER_GLOBAL_H

#include <qglobal.h>

#ifdef PROPERTYLINEENHANCER_LIB
# define PROPERTYLINEENHANCER_EXPORT Q_DECL_EXPORT
#else
# define PROPERTYLINEENHANCER_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTYLINEENHANCER_GLOBAL_H
