#ifndef PROPERTYMATCHINGALIGNMENT_GLOBAL_H
#define PROPERTYMATCHINGALIGNMENT_GLOBAL_H

#include <qglobal.h>

#ifdef PROPERTYMATCHINGALIGNMENT_LIB
# define PROPERTYMATCHINGALIGNMENT_EXPORT Q_DECL_EXPORT
#else
# define PROPERTYMATCHINGALIGNMENT_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTYMATCHINGALIGNMENT_GLOBAL_H
