#ifndef INTEGRATIONSELECTMASTER_GLOBAL_H
#define INTEGRATIONSELECTMASTER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef INTEGRATIONSELECTMASTER_LIB
# define INTEGRATIONSELECTMASTER_EXPORT Q_DECL_EXPORT
#else
# define INTEGRATIONSELECTMASTER_EXPORT Q_DECL_IMPORT
#endif

#endif // INTEGRATIONSELECTMASTER_GLOBAL_H
