#ifndef BUTTONSETTINGPRINTER_GLOBAL_H
#define BUTTONSETTINGPRINTER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONSETTINGPRINTER_LIB
# define BUTTONSETTINGPRINTER_EXPORT Q_DECL_EXPORT
#else
# define BUTTONSETTINGPRINTER_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONSETTINGPRINTER_GLOBAL_H
