#ifndef BUTTONOUTLINEOFFSETWINDOW_GLOBAL_H
#define BUTTONOUTLINEOFFSETWINDOW_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONOUTLINEOFFSETWINDOW_LIB
# define BUTTONOUTLINEOFFSETWINDOW_EXPORT Q_DECL_EXPORT
#else
# define BUTTONOUTLINEOFFSETWINDOW_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONOUTLINEOFFSETWINDOW_GLOBAL_H
