#ifndef PROPERTYHOLEWALLINSPECTION_GLOBAL_H
#define PROPERTYHOLEWALLINSPECTION_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PROPERTYHOLEWALLINSPECTION_LIB
# define PROPERTYHOLEWALLINSPECTION_EXPORT Q_DECL_EXPORT
#else
# define PROPERTYHOLEWALLINSPECTION_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTYHOLEWALLINSPECTION_GLOBAL_H
