#ifndef MEASURESHOWGRID_GLOBAL_H
#define MEASURESHOWGRID_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef MEASURESHOWGRID_LIB
# define MEASURESHOWGRID_EXPORT Q_DECL_EXPORT
#else
# define MEASURESHOWGRID_EXPORT Q_DECL_IMPORT
#endif

#endif // MEASURESHOWGRID_GLOBAL_H
