#ifndef AUTOCLASSIFY_GLOBAL_H
#define AUTOCLASSIFY_GLOBAL_H

#include <qglobal.h>

#ifdef AUTOCLASSIFY_LIB
# define AUTOCLASSIFY_EXPORT Q_DECL_EXPORT
#else
# define AUTOCLASSIFY_EXPORT Q_DECL_IMPORT
#endif

#endif // AUTOCLASSIFY_GLOBAL_H
