#ifndef BUTTONAPPENDALGORITHM_GLOBAL_H
#define BUTTONAPPENDALGORITHM_GLOBAL_H

#include <qglobal.h>

#ifdef BUTTONAPPENDALGORITHM_LIB
# define BUTTONAPPENDALGORITHM_EXPORT Q_DECL_EXPORT
#else
# define BUTTONAPPENDALGORITHM_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONAPPENDALGORITHM_GLOBAL_H
