#ifndef EVOBJCHANGEDLOT_GLOBAL_H
#define EVOBJCHANGEDLOT_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef EVOBJCHANGEDLOT_LIB
# define EVOBJCHANGEDLOT_EXPORT Q_DECL_EXPORT
#else
# define EVOBJCHANGEDLOT_EXPORT Q_DECL_IMPORT
#endif

#endif // EVOBJCHANGEDLOT_GLOBAL_H
