#ifndef BUTTONSHOWSNAPIMAGEFILENAME_GLOBAL_H
#define BUTTONSHOWSNAPIMAGEFILENAME_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONSHOWSNAPIMAGEFILENAME_LIB
# define BUTTONSHOWSNAPIMAGEFILENAME_EXPORT Q_DECL_EXPORT
#else
# define BUTTONSHOWSNAPIMAGEFILENAME_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONSHOWSNAPIMAGEFILENAME_GLOBAL_H
