#ifndef CHECKBRIGHTNESSIMAGEPANEL_GLOBAL_H
#define CHECKBRIGHTNESSIMAGEPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef CHECKBRIGHTNESSIMAGEPANEL_LIB
# define CHECKBRIGHTNESSIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define CHECKBRIGHTNESSIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // CHECKBRIGHTNESSIMAGEPANEL_GLOBAL_H
