#ifndef CAMERAXTUMIPX8LINETRIGGER_GLOBAL_H
#define CAMERAXTUMIPX8LINETRIGGER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef CAMERAXTUMIPX8LINETRIGGER_LIB
# define CAMERAXTUMIPX8LINETRIGGER_EXPORT Q_DECL_EXPORT
#else
# define CAMERAXTUMIPX8LINETRIGGER_EXPORT Q_DECL_IMPORT
#endif

#endif // CAMERAXTUMIPX8LINETRIGGER_GLOBAL_H
