#ifndef LEDCONTROL16H_GLOBAL_H
#define LEDCONTROL16H_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef LEDCONTROL16H_LIB
# define LEDCONTROL16H_EXPORT Q_DECL_EXPORT
#else
# define LEDCONTROL16H_EXPORT Q_DECL_IMPORT
#endif

#endif // LEDCONTROL16G_GLOBAL_H
