#ifndef EVOBJBUTTONSTARTINSPECTION_GLOBAL_H
#define EVOBJBUTTONSTARTINSPECTION_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef EVOBJBUTTONSTARTINSPECTION_LIB
# define EVOBJBUTTONSTARTINSPECTION_EXPORT Q_DECL_EXPORT
#else
# define EVOBJBUTTONSTARTINSPECTION_EXPORT Q_DECL_IMPORT
#endif

#endif // EVOBJBUTTONSTARTINSPECTION_GLOBAL_H
