#ifndef SHOWSEQMESSAGE_GLOBAL_H
#define SHOWSEQMESSAGE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SHOWSEQMESSAGE_LIB
# define SHOWSEQMESSAGE_EXPORT Q_DECL_EXPORT
#else
# define SHOWSEQMESSAGE_EXPORT Q_DECL_IMPORT
#endif

#endif // SHOWSEQMESSAGE_GLOBAL_H
