#ifndef INTEGRATIONLOADMASTER_GLOBAL_H
#define INTEGRATIONLOADMASTER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef INTEGRATIONLOADMASTER_LIB
# define INTEGRATIONLOADMASTER_EXPORT Q_DECL_EXPORT
#else
# define INTEGRATIONLOADMASTER_EXPORT Q_DECL_IMPORT
#endif

#endif // INTEGRATIONLOADMASTER_GLOBAL_H
