#ifndef FRAMEDEFIMAGEPANEL_GLOBAL_H
#define FRAMEDEFIMAGEPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef FRAMEDEFIMAGEPANEL_LIB
# define FRAMEDEFIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define FRAMEDEFIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // FRAMEDEFIMAGEPANEL_GLOBAL_H
