#ifndef PROPERTYAUTOCLASSIFY_GLOBAL_H
#define PROPERTYAUTOCLASSIFY_GLOBAL_H

#include <qglobal.h>

#ifdef PROPERTYAUTOCLASSIFY_LIB
# define PROPERTYAUTOCLASSIFY_EXPORT Q_DECL_EXPORT
#else
# define PROPERTYAUTOCLASSIFY_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTYAUTOCLASSIFY_GLOBAL_H
