# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = IntegrationButtonCreateRepeatControl
DESTDIR = ../
CONFIG += debug
DEFINES += INTEGRATIONBUTTONCREATEREPEATCONTROL_LIB
LIBS += -L"./../../../Lib/Release" \
    -lServiceLib \
    -lIntegrationLib
DEPENDPATH += .
MOC_DIR += GeneratedFiles/$(ConfigurationName)
OBJECTS_DIR += release
UI_DIR += GeneratedFiles
RCC_DIR += GeneratedFiles
include(IntegrationButtonCreateRepeatControl.pri)

FORMS += \
    CreateRepeatCountDialog.ui

HEADERS += \
    CreateRepeatCountDialog.h

SOURCES += \
    CreateRepeatCountDialog.cpp
