#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(INTEGRATIONBUTTONCREATEREPEATCONTROL_LIB)
#  define INTEGRATIONBUTTONCREATEREPEATCONTROL_EXPORT Q_DECL_EXPORT
# else
#  define INTEGRATIONBUTTONCREATEREPEATCONTROL_EXPORT Q_DECL_IMPORT
# endif
#else
# define INTEGRATIONBUTTONCREATEREPEATCONTROL_EXPORT
#endif
