#ifndef PROPERTYMEASUREHOLEPOS_GLOBAL_H
#define PROPERTYMEASUREHOLEPOS_GLOBAL_H

#include <qglobal.h>

#ifdef PROPERTYMEASUREHOLEPOS_LIB
# define PROPERTYMEASUREHOLEPOS_EXPORT Q_DECL_EXPORT
#else
# define PROPERTYMEASUREHOLEPOS_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTYMEASUREHOLEPOS_GLOBAL_H
