#ifndef FILTERREVERSELENSONESIDE_GLOBAL_H
#define FILTERREVERSELENSONESIDE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef FILTERREVERSELENSONESIDE_LIB
# define FILTERREVERSELENSONESIDE_EXPORT Q_DECL_EXPORT
#else
# define FILTERREVERSELENSONESIDE_EXPORT Q_DECL_IMPORT
#endif

#endif // FILTERREVERSELENSONESIDE_GLOBAL_H
