#ifndef DYNAMICCLASSIFYIMAGEPANEL_GLOBAL_H
#define DYNAMICCLASSIFYIMAGEPANEL_GLOBAL_H

#include <qglobal.h>

#ifdef DYNAMICCLASSIFYIMAGEPANEL_LIB
# define DYNAMICCLASSIFYIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define DYNAMICCLASSIFYIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // DYNAMICCLASSIFYIMAGEPANEL_GLOBAL_H
