#ifndef SEQRELAY4BYFTDI_GLOBAL_H
#define SEQRELAY4BYFTDI_GLOBAL_H

#include <QGlobal.h>

#ifdef SEQRELAY4BYFTDI_LIB
# define SEQRELAY4BYFTDI_EXPORT Q_DECL_EXPORT
#else
# define SEQRELAY4BYFTDI_EXPORT Q_DECL_IMPORT
#endif

#endif // SEQRELAY4BYFTDI_GLOBAL_H
