#ifndef SELECTRESULTLOTFROME_GLOBAL_H
#define SELECTRESULTLOTFROME_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SELECTRESULTLOTFROME_LIB
# define SELECTRESULTLOTFROME_EXPORT Q_DECL_EXPORT
#else
# define SELECTRESULTLOTFROME_EXPORT Q_DECL_IMPORT
#endif

#endif // SELECTRESULTLOTFROME_GLOBAL_H
