#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(INTEGRATIONBUTTONLOADALGORITHM_LIB)
#  define INTEGRATIONBUTTONLOADALGORITHM_EXPORT Q_DECL_EXPORT
# else
#  define INTEGRATIONBUTTONLOADALGORITHM_EXPORT Q_DECL_IMPORT
# endif
#else
# define INTEGRATIONBUTTONLOADALGORITHM_EXPORT
#endif
