#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(AREACOLORCONVERTERIMAGEPANEL_LIB)
#  define AREACOLORCONVERTERIMAGEPANEL_EXPORT Q_DECL_EXPORT
# else
#  define AREACOLORCONVERTERIMAGEPANEL_EXPORT Q_DECL_IMPORT
# endif
#else
# define AREACOLORCONVERTERIMAGEPANEL_EXPORT
#endif
