#ifndef BUTTONSWAPOUT_GLOBAL_H
#define BUTTONSWAPOUT_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONSWAPOUT_LIB
# define BUTTONSWAPOUT_EXPORT Q_DECL_EXPORT
#else
# define BUTTONSWAPOUT_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONSWAPOUT_GLOBAL_H
