#ifndef AUTOSAVEIMAGESELECTLOT_GLOBAL_H
#define AUTOSAVEIMAGESELECTLOT_GLOBAL_H

#include <qglobal.h>

#ifdef AUTOSAVEIMAGESELECTLOT_LIB
# define AUTOSAVEIMAGESELECTLOT_EXPORT Q_DECL_EXPORT
#else
# define AUTOSAVEIMAGESELECTLOT_EXPORT Q_DECL_IMPORT
#endif

#endif // AUTOSAVEIMAGESELECTLOT_GLOBAL_H
