#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(ALIGNMENTBLOCKIMAGEPANEL_LIB)
#  define ALIGNMENTBLOCKIMAGEPANEL_EXPORT Q_DECL_EXPORT
# else
#  define ALIGNMENTBLOCKIMAGEPANEL_EXPORT Q_DECL_IMPORT
# endif
#else
# define ALIGNMENTBLOCKIMAGEPANEL_EXPORT
#endif
