#ifndef LIVECAMERAALGONTSC_GLOBAL_H
#define LIVECAMERAALGONTSC_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef LIVECAMERAALGONTSC_LIB
# define LIVECAMERAALGONTSC_EXPORT Q_DECL_EXPORT
#else
# define LIVECAMERAALGONTSC_EXPORT Q_DECL_IMPORT
#endif

#endif // LIVECAMERAALGONTSC_GLOBAL_H
