#ifndef DYNAMICCLASSIFY_GLOBAL_H
#define DYNAMICCLASSIFY_GLOBAL_H

#include <qglobal.h>

#ifdef DYNAMICCLASSIFY_LIB
# define DYNAMICCLASSIFY_EXPORT Q_DECL_EXPORT
#else
# define DYNAMICCLASSIFY_EXPORT Q_DECL_IMPORT
#endif

#endif // DYNAMICCLASSIFY_GLOBAL_H
