#ifndef BUTTONTRANSFERLOADGUI_GLOBAL_H
#define BUTTONTRANSFERLOADGUI_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONTRANSFERLOADGUI_LIB
# define BUTTONTRANSFERLOADGUI_EXPORT Q_DECL_EXPORT
#else
# define BUTTONTRANSFERLOADGUI_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONTRANSFERLOADGUI_GLOBAL_H
