#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(SHOWCOLORDIFFERENCERESULTLIST_LIB)
#  define SHOWCOLORDIFFERENCERESULTLIST_EXPORT Q_DECL_EXPORT
# else
#  define SHOWCOLORDIFFERENCERESULTLIST_EXPORT Q_DECL_IMPORT
# endif
#else
# define SHOWCOLORDIFFERENCERESULTLIST_EXPORT
#endif
