#ifndef INTEGRATIONINPUTLOT_GLOBAL_H
#define INTEGRATIONINPUTLOT_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef INTEGRATIONINPUTLOT_LIB
# define INTEGRATIONINPUTLOT_EXPORT Q_DECL_EXPORT
#else
# define INTEGRATIONINPUTLOT_EXPORT Q_DECL_IMPORT
#endif

#endif // INTEGRATIONINPUTLOT_GLOBAL_H
