#ifndef CHECKPROGRAMRUN_GLOBAL_H
#define CHECKPROGRAMRUN_GLOBAL_H

#include <qglobal.h>

#ifdef CHECKPROGRAMRUN_LIB
# define CHECKPROGRAMRUN_EXPORT Q_DECL_EXPORT
#else
# define CHECKPROGRAMRUN_EXPORT Q_DECL_IMPORT
#endif

#endif // CHECKPROGRAMRUN_GLOBAL_H
