#ifndef BUTTONINITIALIZE_GLOBAL_H
#define BUTTONINITIALIZE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONINITIALIZE_LIB
# define BUTTONINITIALIZE_EXPORT Q_DECL_EXPORT
#else
# define BUTTONINITIALIZE_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONINITIALIZE_GLOBAL_H
