#ifndef EASYGENERATEMASK_GLOBAL_H
#define EASYGENERATEMASK_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef EASYGENERATEMASK_LIB
# define EASYGENERATEMASK_EXPORT Q_DECL_EXPORT
#else
# define EASYGENERATEMASK_EXPORT Q_DECL_IMPORT
#endif

#endif // EASYGENERATEMASK_GLOBAL_H
