#ifndef EASYMAKEAVERAGEIMAGE_GLOBAL_H
#define EASYMAKEAVERAGEIMAGE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef EASYMAKEAVERAGEIMAGE_LIB
# define EASYMAKEAVERAGEIMAGE_EXPORT Q_DECL_EXPORT
#else
# define EASYMAKEAVERAGEIMAGE_EXPORT Q_DECL_IMPORT
#endif

#endif // EASYMAKEAVERAGEIMAGE_GLOBAL_H
