# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = SlaveIndicator
DESTDIR = ../../
CONFIG += release
LIBS += -L"./../../Lib/Release" \
    -lComponent \
    -lServiceLib
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += .
RCC_DIR += ./GeneratedFiles
include(SlaveIndicator.pri)
win32:RC_FILE = SlaveIndicator.rc
