#ifndef PROPERTYMATCHSHIFTROTATION_GLOBAL_H
#define PROPERTYMATCHSHIFTROTATION_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PROPERTYMATCHSHIFTROTATION_LIB
# define PROPERTYMATCHSHIFTROTATION_EXPORT Q_DECL_EXPORT
#else
# define PROPERTYMATCHSHIFTROTATION_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTYMATCHSHIFTROTATION_GLOBAL_H
