/********************************************************************************
** Form generated from reading UI file 'ContecNC3D.ui'
**
** Created: Tue May 19 09:24:45 2015
**      by: Qt User Interface Compiler version 4.8.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_CONTECNC3D_H
#define UI_CONTECNC3D_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QCheckBox>
#include <QtGui/QDoubleSpinBox>
#include <QtGui/QFrame>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QLineEdit>
#include <QMainWindow>
#include <QtGui/QPushButton>
#include <QtGui/QSpinBox>
#include <QtGui/QToolButton>
#include <QWidget>

QT_BEGIN_NAMESPACE

class Ui_ContecNC3DClass
{
public:
    QWidget *centralWidget;
    QFrame *frame_2;
    QLabel *label_15;
    QSpinBox *spinBoxBoardSizeX;
    QLabel *label_16;
    QLabel *label_17;
    QSpinBox *spinBoxBoardSizeY;
    QLabel *label_26;
    QSpinBox *spinBoxSpaceY;
    QToolButton *toolButtonPatlightY;
    QPushButton *pushButtonConvertToScan;
    QPushButton *pushButtonSave;
    QFrame *frame;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QSpinBox *spinBoxStartPosX;
    QSpinBox *spinBoxStartPosY;
    QLabel *label_4;
    QLabel *label_5;
    QSpinBox *spinBoxStartVelocity;
    QLabel *label_7;
    QSpinBox *spinBoxScanPulse;
    QLabel *label_8;
    QSpinBox *spinBoxScanVelocity;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_11;
    QSpinBox *spinBoxStepPulse;
    QSpinBox *spinBoxStepVelocity;
    QLabel *label_12;
    QSpinBox *spinBoxScanCount;
    QLabel *label_13;
    QSpinBox *spinBoxCurrentScan;
    QLabel *label_14;
    QLabel *label_18;
    QLabel *label_19;
    QLabel *label_20;
    QSpinBox *spinBoxVelocityZ;
    QLabel *label_30;
    QLabel *label_31;
    QLabel *label_32;
    QLabel *label_33;
    QLabel *label_34;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *label_37;
    QLabel *label_38;
    QToolButton *toolButtonEnableDoorSensor;
    QToolButton *toolButtonEnableAreaSensor;
    QDoubleSpinBox *doubleSpinBoxPosZ;
    QToolButton *toolButtonPatlightR;
    QCheckBox *checkBoxVacuumSwitch;
    QCheckBox *checkBoxAreaSensor;
    QLabel *label_24;
    QToolButton *toolButtonVacuum;
    QToolButton *toolButtonPatlightG;
    QCheckBox *checkBoxButtonLeft;
    QFrame *frame_3;
    QPushButton *pushButtonGoOriginXY;
    QPushButton *pushButtonStartScanXY;
    QPushButton *pushButtonGoStartPosXY;
    QPushButton *pushButtonStopXY;
    QToolButton *toolButtonJogYP;
    QToolButton *toolButtonJogYM;
    QToolButton *toolButtonJogXP;
    QToolButton *toolButtonJogXM;
    QFrame *frame_4;
    QPushButton *pushButtonGoOriginZ;
    QPushButton *pushButtonStartScanZ;
    QPushButton *pushButtonStopZ;
    QToolButton *toolButtonJogZP;
    QToolButton *toolButtonJogZM;
    QLabel *label_27;
    QLabel *label_28;
    QPushButton *pushButtonSetting;
    QCheckBox *checkBoxCoverSensor;
    QCheckBox *checkBoxButtonRight;
    QToolButton *toolButtonSwitchLampR;
    QToolButton *toolButtonSwitchLampL;
    QFrame *frame_5;
    QLabel *label_25;
    QSpinBox *spinBoxCurrentPulseX;
    QCheckBox *checkBoxALMX;
    QCheckBox *checkBoxTIMX;
    QCheckBox *checkBoxLimitPX;
    QCheckBox *checkBoxLimitMX;
    QCheckBox *checkBoxORGX;
    QCheckBox *checkBoxReadyX;
    QLabel *label_6;
    QToolButton *toolButtonAW0X;
    QToolButton *toolButtonFreeX;
    QToolButton *toolButtonAlmRstX;
    QLineEdit *lineEditCurrentPosMMX;
    QLabel *label_43;
    QLabel *label_44;
    QFrame *frame_6;
    QCheckBox *checkBoxALMY;
    QCheckBox *checkBoxTIMY;
    QCheckBox *checkBoxLimitPY;
    QCheckBox *checkBoxLimitMY;
    QCheckBox *checkBoxORGY;
    QCheckBox *checkBoxReadyY;
    QLabel *label_21;
    QLabel *label_23;
    QSpinBox *spinBoxCurrentPulseY;
    QToolButton *toolButtonAW0Y;
    QToolButton *toolButtonAlmRstY;
    QToolButton *toolButtonFreeY;
    QLineEdit *lineEditCurrentPosMMY;
    QLabel *label_41;
    QLabel *label_42;
    QFrame *frame_7;
    QCheckBox *checkBoxALMZ;
    QCheckBox *checkBoxTIMZ;
    QCheckBox *checkBoxLimitPZ;
    QCheckBox *checkBoxLimitMZ;
    QCheckBox *checkBoxORGZ;
    QCheckBox *checkBoxReadyZ;
    QLabel *label_22;
    QLabel *label_29;
    QSpinBox *spinBoxCurrentPulseZ;
    QToolButton *toolButtonAW0Z;
    QToolButton *toolButtonAlmRstZ;
    QToolButton *toolButtonFreeZ;
    QLineEdit *lineEditCurrentPosMMZ;
    QLabel *label_39;
    QLabel *label_40;
    QCheckBox *checkBoxEmergency;
    QToolButton *toolButtonDirectionDignal;
    QToolButton *toolButtonBlinkMode;

    void setupUi(QMainWindow *ContecNC3DClass)
    {
        if (ContecNC3DClass->objectName().isEmpty())
            ContecNC3DClass->setObjectName(QString::fromUtf8("ContecNC3DClass"));
        ContecNC3DClass->resize(842, 638);
        centralWidget = new QWidget(ContecNC3DClass);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        frame_2 = new QFrame(centralWidget);
        frame_2->setObjectName(QString::fromUtf8("frame_2"));
        frame_2->setGeometry(QRect(480, 10, 351, 81));
        frame_2->setFrameShape(QFrame::StyledPanel);
        frame_2->setFrameShadow(QFrame::Sunken);
        label_15 = new QLabel(frame_2);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(0, 0, 351, 16));
        label_15->setFrameShape(QFrame::Panel);
        label_15->setFrameShadow(QFrame::Sunken);
        label_15->setAlignment(Qt::AlignCenter);
        spinBoxBoardSizeX = new QSpinBox(frame_2);
        spinBoxBoardSizeX->setObjectName(QString::fromUtf8("spinBoxBoardSizeX"));
        spinBoxBoardSizeX->setGeometry(QRect(80, 20, 81, 22));
        spinBoxBoardSizeX->setMaximum(99999999);
        label_16 = new QLabel(frame_2);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(30, 20, 41, 21));
        label_16->setFrameShape(QFrame::Panel);
        label_16->setFrameShadow(QFrame::Sunken);
        label_17 = new QLabel(frame_2);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(180, 20, 41, 21));
        label_17->setFrameShape(QFrame::Panel);
        label_17->setFrameShadow(QFrame::Sunken);
        spinBoxBoardSizeY = new QSpinBox(frame_2);
        spinBoxBoardSizeY->setObjectName(QString::fromUtf8("spinBoxBoardSizeY"));
        spinBoxBoardSizeY->setGeometry(QRect(230, 20, 81, 22));
        spinBoxBoardSizeY->setMaximum(99999999);
        label_26 = new QLabel(frame_2);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(140, 50, 81, 21));
        label_26->setFrameShape(QFrame::Panel);
        label_26->setFrameShadow(QFrame::Sunken);
        spinBoxSpaceY = new QSpinBox(frame_2);
        spinBoxSpaceY->setObjectName(QString::fromUtf8("spinBoxSpaceY"));
        spinBoxSpaceY->setGeometry(QRect(230, 50, 81, 22));
        spinBoxSpaceY->setMaximum(99999999);
        toolButtonPatlightY = new QToolButton(centralWidget);
        toolButtonPatlightY->setObjectName(QString::fromUtf8("toolButtonPatlightY"));
        toolButtonPatlightY->setGeometry(QRect(320, 80, 81, 31));
        toolButtonPatlightY->setCheckable(true);
        pushButtonConvertToScan = new QPushButton(centralWidget);
        pushButtonConvertToScan->setObjectName(QString::fromUtf8("pushButtonConvertToScan"));
        pushButtonConvertToScan->setGeometry(QRect(600, 100, 101, 41));
        pushButtonSave = new QPushButton(centralWidget);
        pushButtonSave->setObjectName(QString::fromUtf8("pushButtonSave"));
        pushButtonSave->setGeometry(QRect(510, 550, 75, 31));
        frame = new QFrame(centralWidget);
        frame->setObjectName(QString::fromUtf8("frame"));
        frame->setGeometry(QRect(480, 150, 351, 381));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Sunken);
        label = new QLabel(frame);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(10, 10, 331, 16));
        label->setFrameShape(QFrame::Panel);
        label->setFrameShadow(QFrame::Sunken);
        label_2 = new QLabel(frame);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(20, 30, 41, 21));
        label_2->setFrameShape(QFrame::Panel);
        label_2->setFrameShadow(QFrame::Sunken);
        label_3 = new QLabel(frame);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(190, 30, 41, 21));
        label_3->setFrameShape(QFrame::Panel);
        label_3->setFrameShadow(QFrame::Sunken);
        spinBoxStartPosX = new QSpinBox(frame);
        spinBoxStartPosX->setObjectName(QString::fromUtf8("spinBoxStartPosX"));
        spinBoxStartPosX->setGeometry(QRect(70, 30, 81, 22));
        spinBoxStartPosX->setMinimum(-99999999);
        spinBoxStartPosX->setMaximum(99999999);
        spinBoxStartPosY = new QSpinBox(frame);
        spinBoxStartPosY->setObjectName(QString::fromUtf8("spinBoxStartPosY"));
        spinBoxStartPosY->setGeometry(QRect(240, 30, 81, 22));
        spinBoxStartPosY->setMaximum(99999999);
        label_4 = new QLabel(frame);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(10, 100, 331, 16));
        label_4->setFrameShape(QFrame::Panel);
        label_4->setFrameShadow(QFrame::Sunken);
        label_5 = new QLabel(frame);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(20, 60, 41, 21));
        label_5->setFrameShape(QFrame::Panel);
        label_5->setFrameShadow(QFrame::Sunken);
        spinBoxStartVelocity = new QSpinBox(frame);
        spinBoxStartVelocity->setObjectName(QString::fromUtf8("spinBoxStartVelocity"));
        spinBoxStartVelocity->setGeometry(QRect(70, 60, 81, 22));
        spinBoxStartVelocity->setMaximum(99999999);
        label_7 = new QLabel(frame);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(20, 120, 41, 21));
        label_7->setFrameShape(QFrame::Panel);
        label_7->setFrameShadow(QFrame::Sunken);
        spinBoxScanPulse = new QSpinBox(frame);
        spinBoxScanPulse->setObjectName(QString::fromUtf8("spinBoxScanPulse"));
        spinBoxScanPulse->setGeometry(QRect(70, 120, 81, 22));
        spinBoxScanPulse->setMaximum(99999999);
        label_8 = new QLabel(frame);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(190, 120, 41, 21));
        label_8->setFrameShape(QFrame::Panel);
        label_8->setFrameShadow(QFrame::Sunken);
        spinBoxScanVelocity = new QSpinBox(frame);
        spinBoxScanVelocity->setObjectName(QString::fromUtf8("spinBoxScanVelocity"));
        spinBoxScanVelocity->setGeometry(QRect(240, 120, 61, 22));
        spinBoxScanVelocity->setMaximum(99999999);
        label_9 = new QLabel(frame);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(10, 150, 331, 16));
        label_9->setFrameShape(QFrame::Panel);
        label_9->setFrameShadow(QFrame::Sunken);
        label_10 = new QLabel(frame);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(190, 170, 41, 21));
        label_10->setFrameShape(QFrame::Panel);
        label_10->setFrameShadow(QFrame::Sunken);
        label_11 = new QLabel(frame);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(20, 170, 41, 21));
        label_11->setFrameShape(QFrame::Panel);
        label_11->setFrameShadow(QFrame::Sunken);
        spinBoxStepPulse = new QSpinBox(frame);
        spinBoxStepPulse->setObjectName(QString::fromUtf8("spinBoxStepPulse"));
        spinBoxStepPulse->setGeometry(QRect(70, 170, 81, 22));
        spinBoxStepPulse->setMaximum(99999999);
        spinBoxStepVelocity = new QSpinBox(frame);
        spinBoxStepVelocity->setObjectName(QString::fromUtf8("spinBoxStepVelocity"));
        spinBoxStepVelocity->setGeometry(QRect(240, 170, 61, 22));
        spinBoxStepVelocity->setMaximum(99999999);
        label_12 = new QLabel(frame);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(10, 250, 331, 16));
        label_12->setFrameShape(QFrame::Panel);
        label_12->setFrameShadow(QFrame::Sunken);
        spinBoxScanCount = new QSpinBox(frame);
        spinBoxScanCount->setObjectName(QString::fromUtf8("spinBoxScanCount"));
        spinBoxScanCount->setGeometry(QRect(140, 270, 51, 22));
        spinBoxScanCount->setMaximum(99999999);
        label_13 = new QLabel(frame);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(60, 270, 71, 21));
        label_13->setFrameShape(QFrame::Panel);
        label_13->setFrameShadow(QFrame::Sunken);
        spinBoxCurrentScan = new QSpinBox(frame);
        spinBoxCurrentScan->setObjectName(QString::fromUtf8("spinBoxCurrentScan"));
        spinBoxCurrentScan->setGeometry(QRect(290, 270, 51, 22));
        spinBoxCurrentScan->setMaximum(99999999);
        label_14 = new QLabel(frame);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(210, 270, 81, 21));
        label_14->setFrameShape(QFrame::Panel);
        label_14->setFrameShadow(QFrame::Sunken);
        label_18 = new QLabel(frame);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(20, 220, 41, 21));
        label_18->setFrameShape(QFrame::Panel);
        label_18->setFrameShadow(QFrame::Sunken);
        label_19 = new QLabel(frame);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(10, 200, 331, 16));
        label_19->setFrameShape(QFrame::Panel);
        label_19->setFrameShadow(QFrame::Sunken);
        label_20 = new QLabel(frame);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(190, 220, 41, 21));
        label_20->setFrameShape(QFrame::Panel);
        label_20->setFrameShadow(QFrame::Sunken);
        spinBoxVelocityZ = new QSpinBox(frame);
        spinBoxVelocityZ->setObjectName(QString::fromUtf8("spinBoxVelocityZ"));
        spinBoxVelocityZ->setGeometry(QRect(240, 220, 61, 22));
        spinBoxVelocityZ->setMaximum(99999999);
        label_30 = new QLabel(frame);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(150, 40, 21, 16));
        label_31 = new QLabel(frame);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(320, 40, 21, 16));
        label_32 = new QLabel(frame);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(150, 130, 21, 16));
        label_33 = new QLabel(frame);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(150, 180, 21, 16));
        label_34 = new QLabel(frame);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(150, 230, 21, 16));
        label_35 = new QLabel(frame);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(150, 70, 31, 16));
        label_36 = new QLabel(frame);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(300, 130, 31, 16));
        label_37 = new QLabel(frame);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(300, 180, 31, 16));
        label_38 = new QLabel(frame);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(300, 230, 31, 16));
        toolButtonEnableDoorSensor = new QToolButton(frame);
        toolButtonEnableDoorSensor->setObjectName(QString::fromUtf8("toolButtonEnableDoorSensor"));
        toolButtonEnableDoorSensor->setGeometry(QRect(180, 310, 151, 31));
        toolButtonEnableDoorSensor->setCheckable(true);
        toolButtonEnableAreaSensor = new QToolButton(frame);
        toolButtonEnableAreaSensor->setObjectName(QString::fromUtf8("toolButtonEnableAreaSensor"));
        toolButtonEnableAreaSensor->setGeometry(QRect(20, 310, 151, 31));
        toolButtonEnableAreaSensor->setCheckable(true);
        doubleSpinBoxPosZ = new QDoubleSpinBox(frame);
        doubleSpinBoxPosZ->setObjectName(QString::fromUtf8("doubleSpinBoxPosZ"));
        doubleSpinBoxPosZ->setGeometry(QRect(70, 220, 81, 22));
        doubleSpinBoxPosZ->setMaximum(1e+06);
        toolButtonPatlightR = new QToolButton(centralWidget);
        toolButtonPatlightR->setObjectName(QString::fromUtf8("toolButtonPatlightR"));
        toolButtonPatlightR->setGeometry(QRect(320, 50, 81, 31));
        toolButtonPatlightR->setCheckable(true);
        checkBoxVacuumSwitch = new QCheckBox(centralWidget);
        checkBoxVacuumSwitch->setObjectName(QString::fromUtf8("checkBoxVacuumSwitch"));
        checkBoxVacuumSwitch->setGeometry(QRect(310, 290, 141, 17));
        checkBoxAreaSensor = new QCheckBox(centralWidget);
        checkBoxAreaSensor->setObjectName(QString::fromUtf8("checkBoxAreaSensor"));
        checkBoxAreaSensor->setGeometry(QRect(310, 350, 141, 17));
        label_24 = new QLabel(centralWidget);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(10, 390, 451, 16));
        label_24->setFrameShape(QFrame::Panel);
        label_24->setFrameShadow(QFrame::Sunken);
        label_24->setAlignment(Qt::AlignCenter);
        toolButtonVacuum = new QToolButton(centralWidget);
        toolButtonVacuum->setObjectName(QString::fromUtf8("toolButtonVacuum"));
        toolButtonVacuum->setGeometry(QRect(320, 10, 81, 31));
        toolButtonVacuum->setCheckable(true);
        toolButtonPatlightG = new QToolButton(centralWidget);
        toolButtonPatlightG->setObjectName(QString::fromUtf8("toolButtonPatlightG"));
        toolButtonPatlightG->setGeometry(QRect(320, 110, 81, 31));
        toolButtonPatlightG->setCheckable(true);
        checkBoxButtonLeft = new QCheckBox(centralWidget);
        checkBoxButtonLeft->setObjectName(QString::fromUtf8("checkBoxButtonLeft"));
        checkBoxButtonLeft->setGeometry(QRect(310, 310, 76, 17));
        frame_3 = new QFrame(centralWidget);
        frame_3->setObjectName(QString::fromUtf8("frame_3"));
        frame_3->setGeometry(QRect(10, 30, 281, 181));
        frame_3->setFrameShape(QFrame::StyledPanel);
        frame_3->setFrameShadow(QFrame::Sunken);
        pushButtonGoOriginXY = new QPushButton(frame_3);
        pushButtonGoOriginXY->setObjectName(QString::fromUtf8("pushButtonGoOriginXY"));
        pushButtonGoOriginXY->setGeometry(QRect(10, 10, 121, 51));
        pushButtonStartScanXY = new QPushButton(frame_3);
        pushButtonStartScanXY->setObjectName(QString::fromUtf8("pushButtonStartScanXY"));
        pushButtonStartScanXY->setGeometry(QRect(150, 10, 121, 51));
        pushButtonGoStartPosXY = new QPushButton(frame_3);
        pushButtonGoStartPosXY->setObjectName(QString::fromUtf8("pushButtonGoStartPosXY"));
        pushButtonGoStartPosXY->setGeometry(QRect(150, 140, 121, 31));
        pushButtonStopXY = new QPushButton(frame_3);
        pushButtonStopXY->setObjectName(QString::fromUtf8("pushButtonStopXY"));
        pushButtonStopXY->setGeometry(QRect(150, 80, 121, 41));
        toolButtonJogYP = new QToolButton(frame_3);
        toolButtonJogYP->setObjectName(QString::fromUtf8("toolButtonJogYP"));
        toolButtonJogYP->setGeometry(QRect(40, 90, 61, 21));
        toolButtonJogYP->setCheckable(true);
        toolButtonJogYP->setAutoExclusive(false);
        toolButtonJogYM = new QToolButton(frame_3);
        toolButtonJogYM->setObjectName(QString::fromUtf8("toolButtonJogYM"));
        toolButtonJogYM->setGeometry(QRect(40, 150, 61, 21));
        toolButtonJogYM->setCheckable(true);
        toolButtonJogYM->setAutoExclusive(false);
        toolButtonJogXP = new QToolButton(frame_3);
        toolButtonJogXP->setObjectName(QString::fromUtf8("toolButtonJogXP"));
        toolButtonJogXP->setGeometry(QRect(10, 120, 51, 21));
        toolButtonJogXP->setCheckable(true);
        toolButtonJogXP->setAutoExclusive(false);
        toolButtonJogXM = new QToolButton(frame_3);
        toolButtonJogXM->setObjectName(QString::fromUtf8("toolButtonJogXM"));
        toolButtonJogXM->setGeometry(QRect(80, 120, 51, 21));
        toolButtonJogXM->setCheckable(true);
        toolButtonJogXM->setAutoExclusive(false);
        frame_4 = new QFrame(centralWidget);
        frame_4->setObjectName(QString::fromUtf8("frame_4"));
        frame_4->setGeometry(QRect(10, 250, 281, 131));
        frame_4->setFrameShape(QFrame::StyledPanel);
        frame_4->setFrameShadow(QFrame::Sunken);
        pushButtonGoOriginZ = new QPushButton(frame_4);
        pushButtonGoOriginZ->setObjectName(QString::fromUtf8("pushButtonGoOriginZ"));
        pushButtonGoOriginZ->setGeometry(QRect(10, 10, 121, 51));
        pushButtonStartScanZ = new QPushButton(frame_4);
        pushButtonStartScanZ->setObjectName(QString::fromUtf8("pushButtonStartScanZ"));
        pushButtonStartScanZ->setGeometry(QRect(150, 10, 121, 51));
        pushButtonStopZ = new QPushButton(frame_4);
        pushButtonStopZ->setObjectName(QString::fromUtf8("pushButtonStopZ"));
        pushButtonStopZ->setGeometry(QRect(150, 80, 121, 41));
        toolButtonJogZP = new QToolButton(frame_4);
        toolButtonJogZP->setObjectName(QString::fromUtf8("toolButtonJogZP"));
        toolButtonJogZP->setGeometry(QRect(40, 100, 61, 21));
        toolButtonJogZP->setCheckable(true);
        toolButtonJogZP->setAutoExclusive(false);
        toolButtonJogZM = new QToolButton(frame_4);
        toolButtonJogZM->setObjectName(QString::fromUtf8("toolButtonJogZM"));
        toolButtonJogZM->setGeometry(QRect(40, 70, 61, 21));
        toolButtonJogZM->setCheckable(true);
        toolButtonJogZM->setAutoExclusive(false);
        label_27 = new QLabel(centralWidget);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(10, 10, 281, 21));
        label_27->setFrameShape(QFrame::Panel);
        label_27->setFrameShadow(QFrame::Sunken);
        label_27->setAlignment(Qt::AlignCenter);
        label_28 = new QLabel(centralWidget);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(10, 230, 281, 21));
        label_28->setFrameShape(QFrame::Panel);
        label_28->setFrameShadow(QFrame::Sunken);
        label_28->setAlignment(Qt::AlignCenter);
        pushButtonSetting = new QPushButton(centralWidget);
        pushButtonSetting->setObjectName(QString::fromUtf8("pushButtonSetting"));
        pushButtonSetting->setGeometry(QRect(640, 550, 91, 31));
        checkBoxCoverSensor = new QCheckBox(centralWidget);
        checkBoxCoverSensor->setObjectName(QString::fromUtf8("checkBoxCoverSensor"));
        checkBoxCoverSensor->setGeometry(QRect(310, 370, 141, 17));
        checkBoxButtonRight = new QCheckBox(centralWidget);
        checkBoxButtonRight->setObjectName(QString::fromUtf8("checkBoxButtonRight"));
        checkBoxButtonRight->setGeometry(QRect(310, 330, 76, 17));
        toolButtonSwitchLampR = new QToolButton(centralWidget);
        toolButtonSwitchLampR->setObjectName(QString::fromUtf8("toolButtonSwitchLampR"));
        toolButtonSwitchLampR->setGeometry(QRect(320, 190, 81, 31));
        toolButtonSwitchLampR->setCheckable(true);
        toolButtonSwitchLampL = new QToolButton(centralWidget);
        toolButtonSwitchLampL->setObjectName(QString::fromUtf8("toolButtonSwitchLampL"));
        toolButtonSwitchLampL->setGeometry(QRect(320, 160, 81, 31));
        toolButtonSwitchLampL->setCheckable(true);
        frame_5 = new QFrame(centralWidget);
        frame_5->setObjectName(QString::fromUtf8("frame_5"));
        frame_5->setGeometry(QRect(10, 410, 151, 221));
        frame_5->setFrameShape(QFrame::StyledPanel);
        frame_5->setFrameShadow(QFrame::Sunken);
        label_25 = new QLabel(frame_5);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(0, 0, 151, 21));
        label_25->setFrameShape(QFrame::Panel);
        label_25->setFrameShadow(QFrame::Sunken);
        spinBoxCurrentPulseX = new QSpinBox(frame_5);
        spinBoxCurrentPulseX->setObjectName(QString::fromUtf8("spinBoxCurrentPulseX"));
        spinBoxCurrentPulseX->setGeometry(QRect(10, 70, 71, 22));
        spinBoxCurrentPulseX->setReadOnly(true);
        spinBoxCurrentPulseX->setMinimum(-99999999);
        spinBoxCurrentPulseX->setMaximum(99999999);
        checkBoxALMX = new QCheckBox(frame_5);
        checkBoxALMX->setObjectName(QString::fromUtf8("checkBoxALMX"));
        checkBoxALMX->setGeometry(QRect(80, 120, 61, 17));
        checkBoxTIMX = new QCheckBox(frame_5);
        checkBoxTIMX->setObjectName(QString::fromUtf8("checkBoxTIMX"));
        checkBoxTIMX->setGeometry(QRect(80, 140, 61, 17));
        checkBoxLimitPX = new QCheckBox(frame_5);
        checkBoxLimitPX->setObjectName(QString::fromUtf8("checkBoxLimitPX"));
        checkBoxLimitPX->setGeometry(QRect(80, 160, 61, 17));
        checkBoxLimitMX = new QCheckBox(frame_5);
        checkBoxLimitMX->setObjectName(QString::fromUtf8("checkBoxLimitMX"));
        checkBoxLimitMX->setGeometry(QRect(80, 180, 61, 17));
        checkBoxORGX = new QCheckBox(frame_5);
        checkBoxORGX->setObjectName(QString::fromUtf8("checkBoxORGX"));
        checkBoxORGX->setGeometry(QRect(80, 200, 61, 17));
        checkBoxReadyX = new QCheckBox(frame_5);
        checkBoxReadyX->setObjectName(QString::fromUtf8("checkBoxReadyX"));
        checkBoxReadyX->setGeometry(QRect(80, 100, 61, 17));
        label_6 = new QLabel(frame_5);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(9, 30, 51, 20));
        toolButtonAW0X = new QToolButton(frame_5);
        toolButtonAW0X->setObjectName(QString::fromUtf8("toolButtonAW0X"));
        toolButtonAW0X->setGeometry(QRect(10, 100, 61, 21));
        toolButtonAW0X->setCheckable(true);
        toolButtonFreeX = new QToolButton(frame_5);
        toolButtonFreeX->setObjectName(QString::fromUtf8("toolButtonFreeX"));
        toolButtonFreeX->setGeometry(QRect(10, 120, 61, 21));
        toolButtonFreeX->setCheckable(true);
        toolButtonAlmRstX = new QToolButton(frame_5);
        toolButtonAlmRstX->setObjectName(QString::fromUtf8("toolButtonAlmRstX"));
        toolButtonAlmRstX->setGeometry(QRect(10, 140, 61, 21));
        toolButtonAlmRstX->setCheckable(true);
        lineEditCurrentPosMMX = new QLineEdit(frame_5);
        lineEditCurrentPosMMX->setObjectName(QString::fromUtf8("lineEditCurrentPosMMX"));
        lineEditCurrentPosMMX->setGeometry(QRect(82, 70, 61, 20));
        label_43 = new QLabel(frame_5);
        label_43->setObjectName(QString::fromUtf8("label_43"));
        label_43->setGeometry(QRect(100, 50, 41, 20));
        label_44 = new QLabel(frame_5);
        label_44->setObjectName(QString::fromUtf8("label_44"));
        label_44->setGeometry(QRect(20, 50, 41, 20));
        frame_6 = new QFrame(centralWidget);
        frame_6->setObjectName(QString::fromUtf8("frame_6"));
        frame_6->setGeometry(QRect(160, 410, 151, 221));
        frame_6->setFrameShape(QFrame::StyledPanel);
        frame_6->setFrameShadow(QFrame::Sunken);
        checkBoxALMY = new QCheckBox(frame_6);
        checkBoxALMY->setObjectName(QString::fromUtf8("checkBoxALMY"));
        checkBoxALMY->setGeometry(QRect(80, 120, 61, 17));
        checkBoxTIMY = new QCheckBox(frame_6);
        checkBoxTIMY->setObjectName(QString::fromUtf8("checkBoxTIMY"));
        checkBoxTIMY->setGeometry(QRect(80, 140, 61, 17));
        checkBoxLimitPY = new QCheckBox(frame_6);
        checkBoxLimitPY->setObjectName(QString::fromUtf8("checkBoxLimitPY"));
        checkBoxLimitPY->setGeometry(QRect(80, 160, 61, 17));
        checkBoxLimitMY = new QCheckBox(frame_6);
        checkBoxLimitMY->setObjectName(QString::fromUtf8("checkBoxLimitMY"));
        checkBoxLimitMY->setGeometry(QRect(80, 180, 61, 17));
        checkBoxORGY = new QCheckBox(frame_6);
        checkBoxORGY->setObjectName(QString::fromUtf8("checkBoxORGY"));
        checkBoxORGY->setGeometry(QRect(80, 200, 61, 17));
        checkBoxReadyY = new QCheckBox(frame_6);
        checkBoxReadyY->setObjectName(QString::fromUtf8("checkBoxReadyY"));
        checkBoxReadyY->setGeometry(QRect(80, 100, 61, 17));
        label_21 = new QLabel(frame_6);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(9, 30, 51, 20));
        label_23 = new QLabel(frame_6);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(0, 0, 151, 21));
        label_23->setFrameShape(QFrame::Panel);
        label_23->setFrameShadow(QFrame::Sunken);
        spinBoxCurrentPulseY = new QSpinBox(frame_6);
        spinBoxCurrentPulseY->setObjectName(QString::fromUtf8("spinBoxCurrentPulseY"));
        spinBoxCurrentPulseY->setGeometry(QRect(10, 70, 71, 22));
        spinBoxCurrentPulseY->setReadOnly(true);
        spinBoxCurrentPulseY->setMinimum(-99999999);
        spinBoxCurrentPulseY->setMaximum(99999999);
        toolButtonAW0Y = new QToolButton(frame_6);
        toolButtonAW0Y->setObjectName(QString::fromUtf8("toolButtonAW0Y"));
        toolButtonAW0Y->setGeometry(QRect(10, 100, 61, 21));
        toolButtonAW0Y->setCheckable(true);
        toolButtonAlmRstY = new QToolButton(frame_6);
        toolButtonAlmRstY->setObjectName(QString::fromUtf8("toolButtonAlmRstY"));
        toolButtonAlmRstY->setGeometry(QRect(10, 140, 61, 21));
        toolButtonAlmRstY->setCheckable(true);
        toolButtonFreeY = new QToolButton(frame_6);
        toolButtonFreeY->setObjectName(QString::fromUtf8("toolButtonFreeY"));
        toolButtonFreeY->setGeometry(QRect(10, 120, 61, 21));
        toolButtonFreeY->setCheckable(true);
        lineEditCurrentPosMMY = new QLineEdit(frame_6);
        lineEditCurrentPosMMY->setObjectName(QString::fromUtf8("lineEditCurrentPosMMY"));
        lineEditCurrentPosMMY->setGeometry(QRect(82, 70, 61, 20));
        label_41 = new QLabel(frame_6);
        label_41->setObjectName(QString::fromUtf8("label_41"));
        label_41->setGeometry(QRect(100, 50, 41, 20));
        label_42 = new QLabel(frame_6);
        label_42->setObjectName(QString::fromUtf8("label_42"));
        label_42->setGeometry(QRect(20, 50, 41, 20));
        frame_7 = new QFrame(centralWidget);
        frame_7->setObjectName(QString::fromUtf8("frame_7"));
        frame_7->setGeometry(QRect(310, 410, 151, 221));
        frame_7->setFrameShape(QFrame::StyledPanel);
        frame_7->setFrameShadow(QFrame::Sunken);
        checkBoxALMZ = new QCheckBox(frame_7);
        checkBoxALMZ->setObjectName(QString::fromUtf8("checkBoxALMZ"));
        checkBoxALMZ->setGeometry(QRect(90, 120, 61, 17));
        checkBoxTIMZ = new QCheckBox(frame_7);
        checkBoxTIMZ->setObjectName(QString::fromUtf8("checkBoxTIMZ"));
        checkBoxTIMZ->setGeometry(QRect(90, 140, 61, 17));
        checkBoxLimitPZ = new QCheckBox(frame_7);
        checkBoxLimitPZ->setObjectName(QString::fromUtf8("checkBoxLimitPZ"));
        checkBoxLimitPZ->setGeometry(QRect(90, 160, 61, 17));
        checkBoxLimitMZ = new QCheckBox(frame_7);
        checkBoxLimitMZ->setObjectName(QString::fromUtf8("checkBoxLimitMZ"));
        checkBoxLimitMZ->setGeometry(QRect(90, 180, 61, 17));
        checkBoxORGZ = new QCheckBox(frame_7);
        checkBoxORGZ->setObjectName(QString::fromUtf8("checkBoxORGZ"));
        checkBoxORGZ->setGeometry(QRect(90, 200, 61, 17));
        checkBoxReadyZ = new QCheckBox(frame_7);
        checkBoxReadyZ->setObjectName(QString::fromUtf8("checkBoxReadyZ"));
        checkBoxReadyZ->setGeometry(QRect(90, 100, 61, 17));
        label_22 = new QLabel(frame_7);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(9, 30, 51, 20));
        label_29 = new QLabel(frame_7);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(0, 0, 151, 21));
        label_29->setFrameShape(QFrame::Panel);
        label_29->setFrameShadow(QFrame::Sunken);
        spinBoxCurrentPulseZ = new QSpinBox(frame_7);
        spinBoxCurrentPulseZ->setObjectName(QString::fromUtf8("spinBoxCurrentPulseZ"));
        spinBoxCurrentPulseZ->setGeometry(QRect(10, 70, 71, 22));
        spinBoxCurrentPulseZ->setReadOnly(true);
        spinBoxCurrentPulseZ->setMinimum(-99999999);
        spinBoxCurrentPulseZ->setMaximum(99999999);
        toolButtonAW0Z = new QToolButton(frame_7);
        toolButtonAW0Z->setObjectName(QString::fromUtf8("toolButtonAW0Z"));
        toolButtonAW0Z->setGeometry(QRect(10, 100, 61, 21));
        toolButtonAW0Z->setCheckable(true);
        toolButtonAlmRstZ = new QToolButton(frame_7);
        toolButtonAlmRstZ->setObjectName(QString::fromUtf8("toolButtonAlmRstZ"));
        toolButtonAlmRstZ->setGeometry(QRect(10, 140, 61, 21));
        toolButtonAlmRstZ->setCheckable(true);
        toolButtonFreeZ = new QToolButton(frame_7);
        toolButtonFreeZ->setObjectName(QString::fromUtf8("toolButtonFreeZ"));
        toolButtonFreeZ->setGeometry(QRect(10, 120, 61, 21));
        toolButtonFreeZ->setCheckable(true);
        lineEditCurrentPosMMZ = new QLineEdit(frame_7);
        lineEditCurrentPosMMZ->setObjectName(QString::fromUtf8("lineEditCurrentPosMMZ"));
        lineEditCurrentPosMMZ->setGeometry(QRect(82, 70, 61, 20));
        label_39 = new QLabel(frame_7);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(20, 50, 41, 20));
        label_40 = new QLabel(frame_7);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(100, 50, 41, 20));
        checkBoxEmergency = new QCheckBox(centralWidget);
        checkBoxEmergency->setObjectName(QString::fromUtf8("checkBoxEmergency"));
        checkBoxEmergency->setGeometry(QRect(310, 270, 141, 17));
        toolButtonDirectionDignal = new QToolButton(centralWidget);
        toolButtonDirectionDignal->setObjectName(QString::fromUtf8("toolButtonDirectionDignal"));
        toolButtonDirectionDignal->setGeometry(QRect(320, 230, 81, 31));
        toolButtonDirectionDignal->setCheckable(true);
        toolButtonBlinkMode = new QToolButton(centralWidget);
        toolButtonBlinkMode->setObjectName(QString::fromUtf8("toolButtonBlinkMode"));
        toolButtonBlinkMode->setGeometry(QRect(400, 310, 61, 31));
        toolButtonBlinkMode->setCheckable(true);
        ContecNC3DClass->setCentralWidget(centralWidget);

        retranslateUi(ContecNC3DClass);

        QMetaObject::connectSlotsByName(ContecNC3DClass);
    } // setupUi

    void retranslateUi(QMainWindow *ContecNC3DClass)
    {
        ContecNC3DClass->setWindowTitle(QApplication::translate("ContecNC3DClass", "ContecNC3D", 0, QApplication::UnicodeUTF8));
        label_15->setText(QApplication::translate("ContecNC3DClass", "\343\203\257\343\203\274\343\202\257\343\202\265\343\202\244\343\202\272", 0, QApplication::UnicodeUTF8));
        label_16->setText(QApplication::translate("ContecNC3DClass", "X", 0, QApplication::UnicodeUTF8));
        label_17->setText(QApplication::translate("ContecNC3DClass", "Y", 0, QApplication::UnicodeUTF8));
        label_26->setText(QApplication::translate("ContecNC3DClass", "\347\251\272\350\265\260\350\267\235\351\233\242Y", 0, QApplication::UnicodeUTF8));
        toolButtonPatlightY->setText(QApplication::translate("ContecNC3DClass", "\343\203\221\343\203\210\343\203\251\343\202\244\343\203\210\343\200\200\351\273\204", 0, QApplication::UnicodeUTF8));
        pushButtonConvertToScan->setText(QApplication::translate("ContecNC3DClass", "\343\202\271\343\202\255\343\203\243\343\203\263\345\244\211\346\217\233\343\200\200\342\206\223", 0, QApplication::UnicodeUTF8));
        pushButtonSave->setText(QApplication::translate("ContecNC3DClass", "Save", 0, QApplication::UnicodeUTF8));
        label->setText(QApplication::translate("ContecNC3DClass", "\351\226\213\345\247\213\344\275\215\347\275\256", 0, QApplication::UnicodeUTF8));
        label_2->setText(QApplication::translate("ContecNC3DClass", "X", 0, QApplication::UnicodeUTF8));
        label_3->setText(QApplication::translate("ContecNC3DClass", "Y", 0, QApplication::UnicodeUTF8));
        label_4->setText(QApplication::translate("ContecNC3DClass", "\343\202\271\343\202\255\343\203\243\343\203\263\344\275\215\347\275\256", 0, QApplication::UnicodeUTF8));
        label_5->setText(QApplication::translate("ContecNC3DClass", "\351\200\237\345\272\246", 0, QApplication::UnicodeUTF8));
        label_7->setText(QApplication::translate("ContecNC3DClass", "\347\247\273\345\213\225\351\207\217", 0, QApplication::UnicodeUTF8));
        label_8->setText(QApplication::translate("ContecNC3DClass", "\351\200\237\345\272\246", 0, QApplication::UnicodeUTF8));
        label_9->setText(QApplication::translate("ContecNC3DClass", "\346\250\252\343\202\271\343\203\206\343\203\203\343\203\227", 0, QApplication::UnicodeUTF8));
        label_10->setText(QApplication::translate("ContecNC3DClass", "\351\200\237\345\272\246", 0, QApplication::UnicodeUTF8));
        label_11->setText(QApplication::translate("ContecNC3DClass", "\347\247\273\345\213\225\351\207\217", 0, QApplication::UnicodeUTF8));
        label_12->setText(QApplication::translate("ContecNC3DClass", "\343\202\271\343\202\255\343\203\243\343\203\263\346\225\260", 0, QApplication::UnicodeUTF8));
        label_13->setText(QApplication::translate("ContecNC3DClass", "\343\202\271\343\202\255\343\203\243\343\203\263\346\225\260", 0, QApplication::UnicodeUTF8));
        label_14->setText(QApplication::translate("ContecNC3DClass", "\347\217\276\345\234\250\343\202\271\343\202\255\343\203\243\343\203\263\346\225\260", 0, QApplication::UnicodeUTF8));
        label_18->setText(QApplication::translate("ContecNC3DClass", "\347\247\273\345\213\225\351\207\217", 0, QApplication::UnicodeUTF8));
        label_19->setText(QApplication::translate("ContecNC3DClass", "Z\351\253\230\343\201\225", 0, QApplication::UnicodeUTF8));
        label_20->setText(QApplication::translate("ContecNC3DClass", "\351\200\237\345\272\246", 0, QApplication::UnicodeUTF8));
        label_30->setText(QApplication::translate("ContecNC3DClass", "mm", 0, QApplication::UnicodeUTF8));
        label_31->setText(QApplication::translate("ContecNC3DClass", "mm", 0, QApplication::UnicodeUTF8));
        label_32->setText(QApplication::translate("ContecNC3DClass", "mm", 0, QApplication::UnicodeUTF8));
        label_33->setText(QApplication::translate("ContecNC3DClass", "mm", 0, QApplication::UnicodeUTF8));
        label_34->setText(QApplication::translate("ContecNC3DClass", "mm", 0, QApplication::UnicodeUTF8));
        label_35->setText(QApplication::translate("ContecNC3DClass", "mm/s", 0, QApplication::UnicodeUTF8));
        label_36->setText(QApplication::translate("ContecNC3DClass", "mm/s", 0, QApplication::UnicodeUTF8));
        label_37->setText(QApplication::translate("ContecNC3DClass", "mm/s", 0, QApplication::UnicodeUTF8));
        label_38->setText(QApplication::translate("ContecNC3DClass", "mm/s", 0, QApplication::UnicodeUTF8));
        toolButtonEnableDoorSensor->setText(QApplication::translate("ContecNC3DClass", "\346\211\211\343\202\273\343\203\263\343\202\265\343\203\274\346\234\211\345\212\271", 0, QApplication::UnicodeUTF8));
        toolButtonEnableAreaSensor->setText(QApplication::translate("ContecNC3DClass", "\343\202\250\343\203\252\343\202\242\343\202\273\343\203\263\343\202\265\346\234\211\345\212\271", 0, QApplication::UnicodeUTF8));
        toolButtonPatlightR->setText(QApplication::translate("ContecNC3DClass", "\343\203\221\343\203\210\343\203\251\343\202\244\343\203\210\343\200\200\350\265\244", 0, QApplication::UnicodeUTF8));
        checkBoxVacuumSwitch->setText(QApplication::translate("ContecNC3DClass", "\345\220\270\347\235\200\343\203\220\343\203\253\343\203\226\343\202\271\343\202\244\343\203\203\343\203\201", 0, QApplication::UnicodeUTF8));
        checkBoxAreaSensor->setText(QApplication::translate("ContecNC3DClass", "\343\202\250\343\203\252\343\202\242\343\202\273\343\203\263\343\202\265\343\203\274", 0, QApplication::UnicodeUTF8));
        label_24->setText(QApplication::translate("ContecNC3DClass", "\347\217\276\345\234\250\344\275\215\347\275\256", 0, QApplication::UnicodeUTF8));
        toolButtonVacuum->setText(QApplication::translate("ContecNC3DClass", "\345\220\270\347\235\200", 0, QApplication::UnicodeUTF8));
        toolButtonPatlightG->setText(QApplication::translate("ContecNC3DClass", "\343\203\221\343\203\210\343\203\251\343\202\244\343\203\210\343\200\200\347\267\221", 0, QApplication::UnicodeUTF8));
        checkBoxButtonLeft->setText(QApplication::translate("ContecNC3DClass", "\345\267\246\343\202\271\343\202\277\343\203\274\343\203\210", 0, QApplication::UnicodeUTF8));
        pushButtonGoOriginXY->setText(QApplication::translate("ContecNC3DClass", "\345\216\237\347\202\271\345\276\251\345\270\260", 0, QApplication::UnicodeUTF8));
        pushButtonStartScanXY->setText(QApplication::translate("ContecNC3DClass", "\343\202\271\343\202\255\343\203\243\343\203\263\351\226\213\345\247\213", 0, QApplication::UnicodeUTF8));
        pushButtonGoStartPosXY->setText(QApplication::translate("ContecNC3DClass", "\351\226\213\345\247\213\344\275\215\347\275\256\343\201\270\347\247\273\345\213\225", 0, QApplication::UnicodeUTF8));
        pushButtonStopXY->setText(QApplication::translate("ContecNC3DClass", "\345\201\234\346\255\242", 0, QApplication::UnicodeUTF8));
        toolButtonJogYP->setText(QApplication::translate("ContecNC3DClass", "JOG+", 0, QApplication::UnicodeUTF8));
        toolButtonJogYM->setText(QApplication::translate("ContecNC3DClass", "JOG-", 0, QApplication::UnicodeUTF8));
        toolButtonJogXP->setText(QApplication::translate("ContecNC3DClass", "JOG+", 0, QApplication::UnicodeUTF8));
        toolButtonJogXM->setText(QApplication::translate("ContecNC3DClass", "JOG-", 0, QApplication::UnicodeUTF8));
        pushButtonGoOriginZ->setText(QApplication::translate("ContecNC3DClass", "\345\216\237\347\202\271\345\276\251\345\270\260", 0, QApplication::UnicodeUTF8));
        pushButtonStartScanZ->setText(QApplication::translate("ContecNC3DClass", "\346\214\207\345\256\232\344\275\215\347\275\256\343\201\270\343\201\256\347\247\273\345\213\225", 0, QApplication::UnicodeUTF8));
        pushButtonStopZ->setText(QApplication::translate("ContecNC3DClass", "\345\201\234\346\255\242", 0, QApplication::UnicodeUTF8));
        toolButtonJogZP->setText(QApplication::translate("ContecNC3DClass", "JOG+", 0, QApplication::UnicodeUTF8));
        toolButtonJogZM->setText(QApplication::translate("ContecNC3DClass", "JOG-", 0, QApplication::UnicodeUTF8));
        label_27->setText(QApplication::translate("ContecNC3DClass", "X-X", 0, QApplication::UnicodeUTF8));
        label_28->setText(QApplication::translate("ContecNC3DClass", "Z", 0, QApplication::UnicodeUTF8));
        pushButtonSetting->setText(QApplication::translate("ContecNC3DClass", "Setting", 0, QApplication::UnicodeUTF8));
        checkBoxCoverSensor->setText(QApplication::translate("ContecNC3DClass", "\346\211\211\343\202\273\343\203\263\343\202\265\343\203\274", 0, QApplication::UnicodeUTF8));
        checkBoxButtonRight->setText(QApplication::translate("ContecNC3DClass", "\345\217\263\343\202\271\343\202\277\343\203\274\343\203\210", 0, QApplication::UnicodeUTF8));
        toolButtonSwitchLampR->setText(QApplication::translate("ContecNC3DClass", "\345\217\263\343\202\271\343\202\244\343\203\203\343\203\201\343\203\251\343\203\263\343\203\227", 0, QApplication::UnicodeUTF8));
        toolButtonSwitchLampL->setText(QApplication::translate("ContecNC3DClass", "\345\267\246\343\202\271\343\202\244\343\203\203\343\203\201\343\203\251\343\203\263\343\203\227", 0, QApplication::UnicodeUTF8));
        label_25->setText(QApplication::translate("ContecNC3DClass", "\357\274\270", 0, QApplication::UnicodeUTF8));
        checkBoxALMX->setText(QApplication::translate("ContecNC3DClass", "ALM", 0, QApplication::UnicodeUTF8));
        checkBoxTIMX->setText(QApplication::translate("ContecNC3DClass", "TIM", 0, QApplication::UnicodeUTF8));
        checkBoxLimitPX->setText(QApplication::translate("ContecNC3DClass", "+Limit", 0, QApplication::UnicodeUTF8));
        checkBoxLimitMX->setText(QApplication::translate("ContecNC3DClass", "-Limit", 0, QApplication::UnicodeUTF8));
        checkBoxORGX->setText(QApplication::translate("ContecNC3DClass", "ORG", 0, QApplication::UnicodeUTF8));
        checkBoxReadyX->setText(QApplication::translate("ContecNC3DClass", "Ready", 0, QApplication::UnicodeUTF8));
        label_6->setText(QApplication::translate("ContecNC3DClass", "\347\217\276\345\234\250\344\275\215\347\275\256", 0, QApplication::UnicodeUTF8));
        toolButtonAW0X->setText(QApplication::translate("ContecNC3DClass", "AW0", 0, QApplication::UnicodeUTF8));
        toolButtonFreeX->setText(QApplication::translate("ContecNC3DClass", "FREE", 0, QApplication::UnicodeUTF8));
        toolButtonAlmRstX->setText(QApplication::translate("ContecNC3DClass", "ALMRST", 0, QApplication::UnicodeUTF8));
        label_43->setText(QApplication::translate("ContecNC3DClass", "mm", 0, QApplication::UnicodeUTF8));
        label_44->setText(QApplication::translate("ContecNC3DClass", "Pulse", 0, QApplication::UnicodeUTF8));
        checkBoxALMY->setText(QApplication::translate("ContecNC3DClass", "ALM", 0, QApplication::UnicodeUTF8));
        checkBoxTIMY->setText(QApplication::translate("ContecNC3DClass", "TIM", 0, QApplication::UnicodeUTF8));
        checkBoxLimitPY->setText(QApplication::translate("ContecNC3DClass", "+Limit", 0, QApplication::UnicodeUTF8));
        checkBoxLimitMY->setText(QApplication::translate("ContecNC3DClass", "-Limit", 0, QApplication::UnicodeUTF8));
        checkBoxORGY->setText(QApplication::translate("ContecNC3DClass", "ORG", 0, QApplication::UnicodeUTF8));
        checkBoxReadyY->setText(QApplication::translate("ContecNC3DClass", "Ready", 0, QApplication::UnicodeUTF8));
        label_21->setText(QApplication::translate("ContecNC3DClass", "\347\217\276\345\234\250\344\275\215\347\275\256", 0, QApplication::UnicodeUTF8));
        label_23->setText(QApplication::translate("ContecNC3DClass", "\357\274\271", 0, QApplication::UnicodeUTF8));
        toolButtonAW0Y->setText(QApplication::translate("ContecNC3DClass", "AW0", 0, QApplication::UnicodeUTF8));
        toolButtonAlmRstY->setText(QApplication::translate("ContecNC3DClass", "ALMRST", 0, QApplication::UnicodeUTF8));
        toolButtonFreeY->setText(QApplication::translate("ContecNC3DClass", "FREE", 0, QApplication::UnicodeUTF8));
        label_41->setText(QApplication::translate("ContecNC3DClass", "mm", 0, QApplication::UnicodeUTF8));
        label_42->setText(QApplication::translate("ContecNC3DClass", "Pulse", 0, QApplication::UnicodeUTF8));
        checkBoxALMZ->setText(QApplication::translate("ContecNC3DClass", "ALM", 0, QApplication::UnicodeUTF8));
        checkBoxTIMZ->setText(QApplication::translate("ContecNC3DClass", "TIM", 0, QApplication::UnicodeUTF8));
        checkBoxLimitPZ->setText(QApplication::translate("ContecNC3DClass", "+Limit", 0, QApplication::UnicodeUTF8));
        checkBoxLimitMZ->setText(QApplication::translate("ContecNC3DClass", "-Limit", 0, QApplication::UnicodeUTF8));
        checkBoxORGZ->setText(QApplication::translate("ContecNC3DClass", "ORG", 0, QApplication::UnicodeUTF8));
        checkBoxReadyZ->setText(QApplication::translate("ContecNC3DClass", "Ready", 0, QApplication::UnicodeUTF8));
        label_22->setText(QApplication::translate("ContecNC3DClass", "\347\217\276\345\234\250\344\275\215\347\275\256", 0, QApplication::UnicodeUTF8));
        label_29->setText(QApplication::translate("ContecNC3DClass", "Z", 0, QApplication::UnicodeUTF8));
        toolButtonAW0Z->setText(QApplication::translate("ContecNC3DClass", "AW0", 0, QApplication::UnicodeUTF8));
        toolButtonAlmRstZ->setText(QApplication::translate("ContecNC3DClass", "ALMRST", 0, QApplication::UnicodeUTF8));
        toolButtonFreeZ->setText(QApplication::translate("ContecNC3DClass", "FREE", 0, QApplication::UnicodeUTF8));
        label_39->setText(QApplication::translate("ContecNC3DClass", "Pulse", 0, QApplication::UnicodeUTF8));
        label_40->setText(QApplication::translate("ContecNC3DClass", "mm", 0, QApplication::UnicodeUTF8));
        checkBoxEmergency->setText(QApplication::translate("ContecNC3DClass", "\351\235\236\345\270\270\345\201\234\346\255\242\343\202\271\343\202\244\343\203\203\343\203\201", 0, QApplication::UnicodeUTF8));
        toolButtonDirectionDignal->setText(QApplication::translate("ContecNC3DClass", "\346\226\271\345\220\221\344\277\241\345\217\267", 0, QApplication::UnicodeUTF8));
        toolButtonBlinkMode->setText(QApplication::translate("ContecNC3DClass", "Blink", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class ContecNC3DClass: public Ui_ContecNC3DClass {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_CONTECNC3D_H
