#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(LOADIMAGEINANYPAGELAYER_LIB)
#  define LOADIMAGEINANYPAGELAYER_EXPORT Q_DECL_EXPORT
# else
#  define LOADIMAGEINANYPAGELAYER_EXPORT Q_DECL_IMPORT
# endif
#else
# define LOADIMAGEINANYPAGELAYER_EXPORT
#endif
