#ifndef BUTTONTOSHOWSTATUSCOMMENT_GLOBAL_H
#define BUTTONTOSHOWSTATUSCOMMENT_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONTOSHOWSTATUSCOMMENT_LIB
# define BUTTONTOSHOWSTATUSCOMMENT_EXPORT Q_DECL_EXPORT
#else
# define BUTTONTOSHOWSTATUSCOMMENT_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONTOSHOWSTATUSCOMMENT_GLOBAL_H
