#ifndef BUTTONFILTERUPSIDEDOWN_GLOBAL_H
#define BUTTONFILTERUPSIDEDOWN_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONFILTERUPSIDEDOWN_LIB
# define BUTTONFILTERUPSIDEDOWN_EXPORT Q_DECL_EXPORT
#else
# define BUTTONFILTERUPSIDEDOWN_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONFILTERUPSIDEDOWN_GLOBAL_H
