#ifndef CHANGECAMERASETTINGINVISIBLE_GLOBAL_H
#define CHANGECAMERASETTINGINVISIBLE_GLOBAL_H

#include <qglobal.h>

#ifdef CHANGECAMERASETTINGINVISIBLE_LIB
# define CHANGECAMERASETTINGINVISIBLE_EXPORT Q_DECL_EXPORT
#else
# define CHANGECAMERASETTINGINVISIBLE_EXPORT Q_DECL_IMPORT
#endif

#endif // CHANGECAMERASETTINGINVISIBLE_GLOBAL_H
