#ifndef PARTIALIMAGING_GLOBAL_H
#define PARTIALIMAGING_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PARTIALIMAGING_LIB
# define PARTIALIMAGING_EXPORT Q_DECL_EXPORT
#else
# define PARTIALIMAGING_EXPORT Q_DECL_IMPORT
#endif

#endif // PARTIALIMAGING_GLOBAL_H
