#ifndef PROCESS3DIMAGEPANEL_GLOBAL_H
#define PROCESS3DIMAGEPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PROCESS3DIMAGEPANEL_LIB
# define PROCESS3DIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define PROCESS3DIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // PROCESS3DIMAGEPANEL_GLOBAL_H
