#ifndef INTEGRATIONSTACKNGTHUMBNAIL_GLOBAL_H
#define INTEGRATIONSTACKNGTHUMBNAIL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef INTEGRATIONSTACKNGTHUMBNAIL_LIB
# define INTEGRATIONSTACKNGTHUMBNAIL_EXPORT Q_DECL_EXPORT
#else
# define INTEGRATIONSTACKNGTHUMBNAIL_EXPORT Q_DECL_IMPORT
#endif

#endif // INTEGRATIONSTACKNGTHUMBNAIL_GLOBAL_H
