#ifndef SHOWSTRATEGICALLNUMBER_GLOBAL_H
#define SHOWSTRATEGICALLNUMBER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SHOWSTRATEGICALLNUMBER_LIB
# define SHOWSTRATEGICALLNUMBER_EXPORT Q_DECL_EXPORT
#else
# define SHOWSTRATEGICALLNUMBER_EXPORT Q_DECL_IMPORT
#endif

#endif // SHOWSTRATEGICALLNUMBER_GLOBAL_H
