#ifndef BUTTONSELECTDATABASE_GLOBAL_H
#define BUTTONSELECTDATABASE_GLOBAL_H

#include <qglobal.h>

#ifdef BUTTONSELECTDATABASE_LIB
# define BUTTONSELECTDATABASE_EXPORT Q_DECL_EXPORT
#else
# define BUTTONSELECTDATABASE_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONSELECTDATABASE_GLOBAL_H
