#ifndef BUTTONEXECUTEMACRO_GLOBAL_H
#define BUTTONEXECUTEMACRO_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONEXECUTEMACRO_LIB
# define BUTTONEXECUTEMACRO_EXPORT Q_DECL_EXPORT
#else
# define BUTTONEXECUTEMACRO_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONEXECUTEMACRO_GLOBAL_H
