#ifndef STARTINSPECTIONWITHOUTCAPTURE_GLOBAL_H
#define STARTINSPECTIONWITHOUTCAPTURE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef STARTINSPECTIONWITHOUTCAPTURE_LIB
# define STARTINSPECTIONWITHOUTCAPTURE_EXPORT Q_DECL_EXPORT
#else
# define STARTINSPECTIONWITHOUTCAPTURE_EXPORT Q_DECL_IMPORT
#endif

#endif // STARTINSPECTIONWITHOUTCAPTURE_GLOBAL_H
