#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(INTEGRATIONCHANGECAMERASETTING_LIB)
#  define INTEGRATIONCHANGECAMERASETTING_EXPORT Q_DECL_EXPORT
# else
#  define INTEGRATIONCHANGECAMERASETTING_EXPORT Q_DECL_IMPORT
# endif
#else
# define INTEGRATIONCHANGECAMERASETTING_EXPORT
#endif
