#ifndef SAVEMASTERIMAGEININSPECTION_GLOBAL_H
#define SAVEMASTERIMAGEININSPECTION_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SAVEMASTERIMAGEININSPECTION_LIB
# define SAVEMASTERIMAGEININSPECTION_EXPORT Q_DECL_EXPORT
#else
# define SAVEMASTERIMAGEININSPECTION_EXPORT Q_DECL_IMPORT
#endif

#endif // SAVEMASTERIMAGEININSPECTION_GLOBAL_H
