#ifndef COLORDIFFERENCE_GLOBAL_H
#define COLORDIFFERENCE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef COLORDIFFERENCE_LIB
# define COLORDIFFERENCE_EXPORT Q_DECL_EXPORT
#else
# define COLORDIFFERENCE_EXPORT Q_DECL_IMPORT
#endif

#endif // COLORDIFFERENCE_GLOBAL_H
