#ifndef SELECTDELIVERED_GLOBAL_H
#define SELECTDELIVERED_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SELECTDELIVERED_LIB
# define SELECTDELIVERED_EXPORT Q_DECL_EXPORT
#else
# define SELECTDELIVERED_EXPORT Q_DECL_IMPORT
#endif

#endif // SELECTDELIVERED_GLOBAL_H
