#ifndef PROPERTYTREEMASTER_GLOBAL_H
#define PROPERTYTREEMASTER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PROPERTYTREEMASTER_LIB
# define PROPERTYTREEMASTER_EXPORT Q_DECL_EXPORT
#else
# define PROPERTYTREEMASTER_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTYTREEMASTER_GLOBAL_H
