#ifndef LEDCONTROL16E_GLOBAL_H
#define LEDCONTROL16E_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef LEDCONTROL16E_LIB
# define LEDCONTROL16E_EXPORT Q_DECL_EXPORT
#else
# define LEDCONTROL16E_EXPORT Q_DECL_IMPORT
#endif

#endif // LEDCONTROL16E_GLOBAL_H
