#ifndef HOOKDRAWREGULATIONLINE_GLOBAL_H
#define HOOKDRAWREGULATIONLINE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef HOOKDRAWREGULATIONLINE_LIB
# define HOOKDRAWREGULATIONLINE_EXPORT Q_DECL_EXPORT
#else
# define HOOKDRAWREGULATIONLINE_EXPORT Q_DECL_IMPORT
#endif

#endif // HOOKDRAWREGULATIONLINE_GLOBAL_H
