#ifndef CHECKBRIGHTNESS_GLOBAL_H
#define CHECKBRIGHTNESS_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef CHECKBRIGHTNESS_LIB
# define CHECKBRIGHTNESS_EXPORT Q_DECL_EXPORT
#else
# define CHECKBRIGHTNESS_EXPORT Q_DECL_IMPORT
#endif

#endif // CHECKBRIGHTNESS_GLOBAL_H
