#ifndef MATRIXCELLLIST_GLOBAL_H
#define MATRIXCELLLIST_GLOBAL_H

#include <qglobal.h>

#ifdef MATRIXCELLLIST_LIB
# define MATRIXCELLLIST_EXPORT Q_DECL_EXPORT
#else
# define MATRIXCELLLIST_EXPORT Q_DECL_IMPORT
#endif

#endif // MATRIXCELLLIST_GLOBAL_H
