#ifndef PANELSIMPLEVRS_GLOBAL_H
#define PANELSIMPLEVRS_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PANELSIMPLEVRS_LIB
# define PANELSIMPLEVRS_EXPORT Q_DECL_EXPORT
#else
# define PANELSIMPLEVRS_EXPORT Q_DECL_IMPORT
#endif

#endif // PANELSIMPLEVRS_GLOBAL_H
