#ifndef LINEENHANCERIMAGEPANEL_GLOBAL_H
#define LINEENHANCERIMAGEPANEL_GLOBAL_H

#include <qglobal.h>

#ifdef LINEENHANCERIMAGEPANEL_LIB
# define LINEENHANCERIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define LINEENHANCERIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // LINEENHANCERIMAGEPANEL_GLOBAL_H
