#ifndef PROPERTYZREGULATION_GLOBAL_H
#define PROPERTYZREGULATION_GLOBAL_H

#include <qglobal.h>

#ifdef PROPERTYZREGULATION_LIB
# define PROPERTYZREGULATION_EXPORT Q_DECL_EXPORT
#else
# define PROPERTYZREGULATION_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTYZREGULATION_GLOBAL_H
