#ifndef SHORTCUTKEYINVISIBLE_GLOBAL_H
#define SHORTCUTKEYINVISIBLE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SHORTCUTKEYINVISIBLE_LIB
# define SHORTCUTKEYINVISIBLE_EXPORT Q_DECL_EXPORT
#else
# define SHORTCUTKEYINVISIBLE_EXPORT Q_DECL_IMPORT
#endif

#endif // SHORTCUTKEYINVISIBLE_GLOBAL_H
