#ifndef BUTTONSAVERESULTWITHALL_GLOBAL_H
#define BUTTONSAVERESULTWITHALL_GLOBAL_H

#include <qglobal.h>

#ifdef BUTTONSAVERESULTWITHALL_LIB
# define BUTTONSAVERESULTWITHALL_EXPORT Q_DECL_EXPORT
#else
# define BUTTONSAVERESULTWITHALL_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONSAVERESULTWITHALL_GLOBAL_H
