#ifndef EASYPROPERTYSWITCHPHASE_GLOBAL_H
#define EASYPROPERTYSWITCHPHASE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef EASYPROPERTYSWITCHPHASE_LIB
# define EASYPROPERTYSWITCHPHASE_EXPORT Q_DECL_EXPORT
#else
# define EASYPROPERTYSWITCHPHASE_EXPORT Q_DECL_IMPORT
#endif

#endif // EASYPROPERTYSWITCHPHASE_GLOBAL_H
