#ifndef SHOWPIECERESULTLIST_GLOBAL_H
#define SHOWPIECERESULTLIST_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SHOWPIECERESULTLIST_LIB
# define SHOWPIECERESULTLIST_EXPORT Q_DECL_EXPORT
#else
# define SHOWPIECERESULTLIST_EXPORT Q_DECL_IMPORT
#endif

#endif // SHOWPIECERESULTLIST_GLOBAL_H
