# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = ButtonResetThresholdDotColorMatching
DESTDIR = ../../../GUI
CONFIG += debug
DEFINES += BUTTONRESETTHRESHOLDDOTCOLORMATCHING_LIB
LIBS += -L"./../../../Lib/Release" \
    -lServiceLib \
    -lIntegrationLib
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += .
RCC_DIR += ./GeneratedFiles
include(ButtonResetThresholdDotColorMatching.pri)
