#ifndef DOTREGULATIONIMAGEPANEL_GLOBAL_H
#define DOTREGULATIONIMAGEPANEL_GLOBAL_H

#include <qglobal.h>

#ifdef DOTREGULATIONIMAGEPANEL_LIB
# define DOTREGULATIONIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define DOTREGULATIONIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // DOTREGULATIONIMAGEPANEL_GLOBAL_H
