# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = PIOWatch
DESTDIR = ../../
CONFIG += release
LIBS += -L"./../../Lib/Release" \
    -lSeqLib \
    -lComponent \
    -lServiceLib
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += .
RCC_DIR += .
include(PIOWatch.pri)
win32:RC_FILE = PIOWatch.rc
