#ifndef SENDMESSENGER_GLOBAL_H
#define SENDMESSENGER_GLOBAL_H

#include <qglobal.h>

#ifdef SENDMESSENGER_LIB
# define SENDMESSENGER_EXPORT Q_DECL_EXPORT
#else
# define SENDMESSENGER_EXPORT Q_DECL_IMPORT
#endif

#endif // SENDMESSENGER_GLOBAL_H
