#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(RESULTWRITECSVBARCODELINE_LIB)
#  define RESULTWRITECSVBARCODELINE_EXPORT Q_DECL_EXPORT
# else
#  define RESULTWRITECSVBARCODELINE_EXPORT Q_DECL_IMPORT
# endif
#else
# define RESULTWRITECSVBARCODELINE_EXPORT
#endif
