#ifndef OCRIMAGEPANEL_GLOBAL_H
#define OCRIMAGEPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef OCRIMAGEPANEL_LIB
# define OCRIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define OCRIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // OCRIMAGEPANEL_GLOBAL_H
