# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = ChangeServer
DESTDIR = ../
CONFIG += release
LIBS += -L"./../Lib/Release" \
    -lComponent \
    -lServiceLib
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += .
RCC_DIR += .
include(ChangeServer.pri)
win32:RC_FILE = ChangeServer.rc
