#ifndef CCSCONTROLGUI_GLOBAL_H
#define CCSCONTROLGUI_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef CCSCONTROLGUI_LIB
# define CCSCONTROLGUI_EXPORT Q_DECL_EXPORT
#else
# define CCSCONTROLGUI_EXPORT Q_DECL_IMPORT
#endif

#endif // CCSCONTROLGUI_GLOBAL_H
