#ifndef PARTIALIMAGINGIMAGEPANEL_GLOBAL_H
#define PARTIALIMAGINGIMAGEPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PARTIALIMAGINGIMAGEPANEL_LIB
# define PARTIALIMAGINGIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define PARTIALIMAGINGIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // PARTIALIMAGINGIMAGEPANEL_GLOBAL_H
