#ifndef GUIREVIEWTEMPLATE_GLOBAL_H
#define GUIREVIEWTEMPLATE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef GUIREVIEWTEMPLATE_LIB
# define GUIREVIEWTEMPLATE_EXPORT Q_DECL_EXPORT
#else
# define GUIREVIEWTEMPLATE_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONTOSHOWTOTALNGMAP_GLOBAL_H
