#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(BUTTONCONVERTCOLORDISTRIBUTION_LIB)
#  define BUTTONCONVERTCOLORDISTRIBUTION_EXPORT Q_DECL_EXPORT
# else
#  define BUTTONCONVERTCOLORDISTRIBUTION_EXPORT Q_DECL_IMPORT
# endif
#else
# define BUTTONCONVERTCOLORDISTRIBUTION_EXPORT
#endif
