#ifndef PROPERTYDOTREGULATION_GLOBAL_H
#define PROPERTYDOTREGULATION_GLOBAL_H

#include <qglobal.h>

#ifdef PROPERTYDOTREGULATION_LIB
# define PROPERTYDOTREGULATION_EXPORT Q_DECL_EXPORT
#else
# define PROPERTYDOTREGULATION_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTYDOTREGULATION_GLOBAL_H
