#ifndef EVOBJPROCESSOR_GLOBAL_H
#define EVOBJPROCESSOR_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef EVOBJPROCESSOR_LIB
# define EVOBJPROCESSOR_EXPORT Q_DECL_EXPORT
#else
# define EVOBJPROCESSOR_EXPORT Q_DECL_IMPORT
#endif

#endif // EVOBJPROCESSOR_GLOBAL_H
