#ifndef BUTTONCOPYLIBRARY_GLOBAL_H
#define BUTTONCOPYLIBRARY_GLOBAL_H

#include <qglobal.h>

#ifdef BUTTONCOPYLIBRARY_LIB
# define BUTTONCOPYLIBRARY_EXPORT Q_DECL_EXPORT
#else
# define BUTTONCOPYLIBRARY_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONCOPYLIBRARY_GLOBAL_H
