#ifndef HOOKOVERLAPIMAGE_GLOBAL_H
#define HOOKOVERLAPIMAGE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef HOOKOVERLAPIMAGE_LIB
# define HOOKOVERLAPIMAGE_EXPORT Q_DECL_EXPORT
#else
# define HOOKOVERLAPIMAGE_EXPORT Q_DECL_IMPORT
#endif

#endif // HOOKOVERLAPIMAGE_GLOBAL_H
