#ifndef BUTTONGENERALSTOCKER_GLOBAL_H
#define BUTTONGENERALSTOCKER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONGENERALSTOCKER_LIB
# define BUTTONGENERALSTOCKER_EXPORT Q_DECL_EXPORT
#else
# define BUTTONGENERALSTOCKER_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONGENERALSTOCKER_GLOBAL_H
