/********************************************************************************
** Form generated from reading UI file 'EditLineDialog.ui'
**
** Created by: Qt User Interface Compiler version 6.10.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_EDITLINEDIALOG_H
#define UI_EDITLINEDIALOG_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QListWidget>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_EditLineDialog
{
public:
    QLineEdit *EditLibID;
    QPushButton *ButtonSaveToLibrary;
    QListWidget *listWidgetHistList;
    QFrame *frame;
    QLabel *label_92;
    QSpinBox *EditSearchDot;
    QLineEdit *EditName;
    QLabel *label_4;
    QLabel *label_94;
    QLabel *label_93;
    QDoubleSpinBox *doubleSpinBoxThresholdM;
    QDoubleSpinBox *doubleSpinBoxThresholdP;
    QLabel *label_95;
    QSpinBox *EditEdgeWidth;
    QSpinBox *EditEdgeWidthLib;
    QDoubleSpinBox *doubleSpinBoxThresholdPLib;
    QDoubleSpinBox *doubleSpinBoxThresholdMLib;
    QSpinBox *EditSearchDotLib;
    QCheckBox *checkBoxPrevailLeft;
    QCheckBox *checkBoxPrevailRight;
    QLabel *label_96;
    QDoubleSpinBox *doubleSpinBoxMatchEndPos;
    QLabel *label_97;
    QDoubleSpinBox *doubleSpinBoxMatchStartPos;
    QCheckBox *checkBoxEnable;
    QLabel *label_8;
    QLineEdit *EditItemID;
    QDoubleSpinBox *doubleSpinBoxSearchDot;
    QLabel *labelUnitName_4;
    QLabel *label_98;
    QDoubleSpinBox *doubleSpinBoxThresholdM_2;
    QDoubleSpinBox *doubleSpinBoxThresholdP_2;
    QLabel *labelUnitName_5;
    QLabel *labelUnitName_6;
    QLabel *label_99;
    QLabel *label_100;
    QComboBox *comboBoxUsedLayer;
    QComboBox *comboBoxSearchType;
    QLabel *label_101;
    QLabel *label_102;
    QDoubleSpinBox *doubleSpinBoxBrightnessIdealLeft;
    QDoubleSpinBox *doubleSpinBoxBrightnessIdealRight;
    QLabel *label_103;
    QDoubleSpinBox *doubleSpinBoxThresholdRate;
    QPushButton *pushButtonChangeItemID;
    QLabel *label_104;
    QDoubleSpinBox *doubleSpinBoxBrightnessIdealLeftRange;
    QDoubleSpinBox *doubleSpinBoxBrightnessIdealRightRange;
    QPushButton *ButtonRelrectOnlyBlock;
    QLabel *label_40;
    QFrame *frame_2;
    QPushButton *pushButtonTest;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *labelPosDiffX;
    QLabel *labelPosDiffY;
    QLabel *labelPosDiffYUnit;
    QLabel *labelPosDiffXUnit;
    QLabel *labelUnitName_7;
    QLabel *labelUnitName_8;
    QLabel *label_6;
    QPushButton *pushButtonChangeLib;
    QLabel *label_7;
    QPushButton *ButtonLoadFromLibrary;
    QPushButton *ButtonClose;
    QPushButton *ButtonReflectAllBlocks;
    QLineEdit *Edit_LibName;

    void setupUi(QWidget *EditLineDialog)
    {
        if (EditLineDialog->objectName().isEmpty())
            EditLineDialog->setObjectName("EditLineDialog");
        EditLineDialog->resize(801, 658);
        EditLibID = new QLineEdit(EditLineDialog);
        EditLibID->setObjectName("EditLibID");
        EditLibID->setGeometry(QRect(10, 30, 61, 21));
        EditLibID->setReadOnly(true);
        ButtonSaveToLibrary = new QPushButton(EditLineDialog);
        ButtonSaveToLibrary->setObjectName("ButtonSaveToLibrary");
        ButtonSaveToLibrary->setGeometry(QRect(20, 610, 161, 41));
        listWidgetHistList = new QListWidget(EditLineDialog);
        listWidgetHistList->setObjectName("listWidgetHistList");
        listWidgetHistList->setGeometry(QRect(580, 360, 201, 71));
        frame = new QFrame(EditLineDialog);
        frame->setObjectName("frame");
        frame->setGeometry(QRect(10, 60, 541, 491));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Sunken);
        label_92 = new QLabel(frame);
        label_92->setObjectName("label_92");
        label_92->setGeometry(QRect(10, 120, 331, 21));
        label_92->setFrameShape(QFrame::Panel);
        label_92->setFrameShadow(QFrame::Sunken);
        label_92->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditSearchDot = new QSpinBox(frame);
        EditSearchDot->setObjectName("EditSearchDot");
        EditSearchDot->setGeometry(QRect(350, 120, 91, 22));
        EditSearchDot->setReadOnly(false);
        EditSearchDot->setMaximum(10000);
        EditName = new QLineEdit(frame);
        EditName->setObjectName("EditName");
        EditName->setGeometry(QRect(230, 10, 211, 31));
        QFont font;
        font.setPointSize(12);
        EditName->setFont(font);
        label_4 = new QLabel(frame);
        label_4->setObjectName("label_4");
        label_4->setGeometry(QRect(150, 10, 81, 31));
        QFont font1;
        font1.setPointSize(9);
        label_4->setFont(font1);
        label_4->setFrameShape(QFrame::Panel);
        label_4->setFrameShadow(QFrame::Sunken);
        label_4->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_94 = new QLabel(frame);
        label_94->setObjectName("label_94");
        label_94->setGeometry(QRect(10, 220, 331, 21));
        label_94->setFrameShape(QFrame::Panel);
        label_94->setFrameShadow(QFrame::Sunken);
        label_94->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_93 = new QLabel(frame);
        label_93->setObjectName("label_93");
        label_93->setGeometry(QRect(10, 170, 331, 21));
        label_93->setFrameShape(QFrame::Panel);
        label_93->setFrameShadow(QFrame::Sunken);
        label_93->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        doubleSpinBoxThresholdM = new QDoubleSpinBox(frame);
        doubleSpinBoxThresholdM->setObjectName("doubleSpinBoxThresholdM");
        doubleSpinBoxThresholdM->setGeometry(QRect(350, 170, 91, 22));
        doubleSpinBoxThresholdP = new QDoubleSpinBox(frame);
        doubleSpinBoxThresholdP->setObjectName("doubleSpinBoxThresholdP");
        doubleSpinBoxThresholdP->setGeometry(QRect(350, 220, 91, 22));
        label_95 = new QLabel(frame);
        label_95->setObjectName("label_95");
        label_95->setGeometry(QRect(10, 270, 331, 21));
        label_95->setFrameShape(QFrame::Panel);
        label_95->setFrameShadow(QFrame::Sunken);
        label_95->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditEdgeWidth = new QSpinBox(frame);
        EditEdgeWidth->setObjectName("EditEdgeWidth");
        EditEdgeWidth->setGeometry(QRect(350, 270, 91, 22));
        EditEdgeWidth->setMaximum(255);
        EditEdgeWidthLib = new QSpinBox(frame);
        EditEdgeWidthLib->setObjectName("EditEdgeWidthLib");
        EditEdgeWidthLib->setGeometry(QRect(450, 270, 81, 22));
        QPalette palette;
        QBrush brush(QColor(255, 255, 0, 255));
        brush.setStyle(Qt::BrushStyle::SolidPattern);
        palette.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush);
        palette.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush);
        QBrush brush1(QColor(212, 208, 200, 255));
        brush1.setStyle(Qt::BrushStyle::SolidPattern);
        palette.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush1);
        EditEdgeWidthLib->setPalette(palette);
        EditEdgeWidthLib->setReadOnly(true);
        EditEdgeWidthLib->setMaximum(255);
        doubleSpinBoxThresholdPLib = new QDoubleSpinBox(frame);
        doubleSpinBoxThresholdPLib->setObjectName("doubleSpinBoxThresholdPLib");
        doubleSpinBoxThresholdPLib->setGeometry(QRect(450, 220, 81, 22));
        QPalette palette1;
        palette1.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush);
        palette1.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush);
        palette1.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush1);
        doubleSpinBoxThresholdPLib->setPalette(palette1);
        doubleSpinBoxThresholdPLib->setReadOnly(true);
        doubleSpinBoxThresholdMLib = new QDoubleSpinBox(frame);
        doubleSpinBoxThresholdMLib->setObjectName("doubleSpinBoxThresholdMLib");
        doubleSpinBoxThresholdMLib->setGeometry(QRect(450, 170, 81, 22));
        QPalette palette2;
        palette2.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush);
        palette2.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush);
        palette2.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush1);
        doubleSpinBoxThresholdMLib->setPalette(palette2);
        doubleSpinBoxThresholdMLib->setReadOnly(true);
        EditSearchDotLib = new QSpinBox(frame);
        EditSearchDotLib->setObjectName("EditSearchDotLib");
        EditSearchDotLib->setGeometry(QRect(450, 120, 81, 22));
        QPalette palette3;
        palette3.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush);
        palette3.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush);
        palette3.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush1);
        EditSearchDotLib->setPalette(palette3);
        EditSearchDotLib->setReadOnly(true);
        EditSearchDotLib->setMaximum(100);
        checkBoxPrevailLeft = new QCheckBox(frame);
        checkBoxPrevailLeft->setObjectName("checkBoxPrevailLeft");
        checkBoxPrevailLeft->setGeometry(QRect(10, 360, 191, 21));
        checkBoxPrevailRight = new QCheckBox(frame);
        checkBoxPrevailRight->setObjectName("checkBoxPrevailRight");
        checkBoxPrevailRight->setGeometry(QRect(10, 390, 191, 21));
        label_96 = new QLabel(frame);
        label_96->setObjectName("label_96");
        label_96->setGeometry(QRect(10, 310, 281, 21));
        label_96->setFrameShape(QFrame::Panel);
        label_96->setFrameShadow(QFrame::Sunken);
        label_96->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        doubleSpinBoxMatchEndPos = new QDoubleSpinBox(frame);
        doubleSpinBoxMatchEndPos->setObjectName("doubleSpinBoxMatchEndPos");
        doubleSpinBoxMatchEndPos->setGeometry(QRect(300, 330, 71, 22));
        label_97 = new QLabel(frame);
        label_97->setObjectName("label_97");
        label_97->setGeometry(QRect(10, 330, 281, 21));
        label_97->setFrameShape(QFrame::Panel);
        label_97->setFrameShadow(QFrame::Sunken);
        label_97->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        doubleSpinBoxMatchStartPos = new QDoubleSpinBox(frame);
        doubleSpinBoxMatchStartPos->setObjectName("doubleSpinBoxMatchStartPos");
        doubleSpinBoxMatchStartPos->setGeometry(QRect(300, 310, 71, 22));
        checkBoxEnable = new QCheckBox(frame);
        checkBoxEnable->setObjectName("checkBoxEnable");
        checkBoxEnable->setGeometry(QRect(10, 90, 191, 21));
        label_8 = new QLabel(frame);
        label_8->setObjectName("label_8");
        label_8->setGeometry(QRect(0, 0, 62, 20));
        label_8->setFrameShape(QFrame::Panel);
        label_8->setFrameShadow(QFrame::Sunken);
        label_8->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditItemID = new QLineEdit(frame);
        EditItemID->setObjectName("EditItemID");
        EditItemID->setGeometry(QRect(0, 20, 61, 21));
        EditItemID->setReadOnly(true);
        doubleSpinBoxSearchDot = new QDoubleSpinBox(frame);
        doubleSpinBoxSearchDot->setObjectName("doubleSpinBoxSearchDot");
        doubleSpinBoxSearchDot->setGeometry(QRect(350, 140, 91, 22));
        QPalette palette4;
        QBrush brush2(QColor(255, 170, 0, 255));
        brush2.setStyle(Qt::BrushStyle::SolidPattern);
        palette4.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush2);
        palette4.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush2);
        QBrush brush3(QColor(240, 240, 240, 255));
        brush3.setStyle(Qt::BrushStyle::SolidPattern);
        palette4.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush3);
        doubleSpinBoxSearchDot->setPalette(palette4);
        doubleSpinBoxSearchDot->setMaximum(9999999999.000000000000000);
        labelUnitName_4 = new QLabel(frame);
        labelUnitName_4->setObjectName("labelUnitName_4");
        labelUnitName_4->setGeometry(QRect(250, 140, 91, 20));
        labelUnitName_4->setFrameShape(QFrame::NoFrame);
        labelUnitName_4->setFrameShadow(QFrame::Sunken);
        labelUnitName_4->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_98 = new QLabel(frame);
        label_98->setObjectName("label_98");
        label_98->setGeometry(QRect(450, 100, 81, 21));
        label_98->setFrameShape(QFrame::Panel);
        label_98->setFrameShadow(QFrame::Sunken);
        label_98->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        doubleSpinBoxThresholdM_2 = new QDoubleSpinBox(frame);
        doubleSpinBoxThresholdM_2->setObjectName("doubleSpinBoxThresholdM_2");
        doubleSpinBoxThresholdM_2->setGeometry(QRect(350, 190, 91, 22));
        QPalette palette5;
        palette5.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush2);
        palette5.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush2);
        palette5.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush3);
        doubleSpinBoxThresholdM_2->setPalette(palette5);
        doubleSpinBoxThresholdM_2->setMaximum(9999999999.000000000000000);
        doubleSpinBoxThresholdP_2 = new QDoubleSpinBox(frame);
        doubleSpinBoxThresholdP_2->setObjectName("doubleSpinBoxThresholdP_2");
        doubleSpinBoxThresholdP_2->setGeometry(QRect(350, 240, 91, 22));
        QPalette palette6;
        palette6.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush2);
        palette6.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush2);
        palette6.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush3);
        doubleSpinBoxThresholdP_2->setPalette(palette6);
        doubleSpinBoxThresholdP_2->setMaximum(9999999999.000000000000000);
        labelUnitName_5 = new QLabel(frame);
        labelUnitName_5->setObjectName("labelUnitName_5");
        labelUnitName_5->setGeometry(QRect(250, 190, 91, 20));
        labelUnitName_5->setFrameShape(QFrame::NoFrame);
        labelUnitName_5->setFrameShadow(QFrame::Sunken);
        labelUnitName_5->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        labelUnitName_6 = new QLabel(frame);
        labelUnitName_6->setObjectName("labelUnitName_6");
        labelUnitName_6->setGeometry(QRect(250, 240, 91, 20));
        labelUnitName_6->setFrameShape(QFrame::NoFrame);
        labelUnitName_6->setFrameShadow(QFrame::Sunken);
        labelUnitName_6->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_99 = new QLabel(frame);
        label_99->setObjectName("label_99");
        label_99->setGeometry(QRect(350, 100, 81, 21));
        label_99->setFrameShape(QFrame::Panel);
        label_99->setFrameShadow(QFrame::Sunken);
        label_99->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_100 = new QLabel(frame);
        label_100->setObjectName("label_100");
        label_100->setGeometry(QRect(10, 60, 211, 21));
        label_100->setFrameShape(QFrame::Panel);
        label_100->setFrameShadow(QFrame::Sunken);
        label_100->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        comboBoxUsedLayer = new QComboBox(frame);
        comboBoxUsedLayer->setObjectName("comboBoxUsedLayer");
        comboBoxUsedLayer->setGeometry(QRect(230, 60, 161, 22));
        comboBoxSearchType = new QComboBox(frame);
        comboBoxSearchType->addItem(QString());
        comboBoxSearchType->addItem(QString());
        comboBoxSearchType->addItem(QString());
        comboBoxSearchType->addItem(QString());
        comboBoxSearchType->addItem(QString());
        comboBoxSearchType->addItem(QString());
        comboBoxSearchType->addItem(QString());
        comboBoxSearchType->addItem(QString());
        comboBoxSearchType->setObjectName("comboBoxSearchType");
        comboBoxSearchType->setGeometry(QRect(240, 360, 291, 22));
        label_101 = new QLabel(frame);
        label_101->setObjectName("label_101");
        label_101->setGeometry(QRect(190, 410, 131, 21));
        label_101->setFrameShape(QFrame::Panel);
        label_101->setFrameShadow(QFrame::Sunken);
        label_101->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_102 = new QLabel(frame);
        label_102->setObjectName("label_102");
        label_102->setGeometry(QRect(190, 430, 131, 21));
        label_102->setFrameShape(QFrame::Panel);
        label_102->setFrameShadow(QFrame::Sunken);
        label_102->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        doubleSpinBoxBrightnessIdealLeft = new QDoubleSpinBox(frame);
        doubleSpinBoxBrightnessIdealLeft->setObjectName("doubleSpinBoxBrightnessIdealLeft");
        doubleSpinBoxBrightnessIdealLeft->setGeometry(QRect(330, 410, 101, 21));
        doubleSpinBoxBrightnessIdealLeft->setMaximum(255.000000000000000);
        doubleSpinBoxBrightnessIdealRight = new QDoubleSpinBox(frame);
        doubleSpinBoxBrightnessIdealRight->setObjectName("doubleSpinBoxBrightnessIdealRight");
        doubleSpinBoxBrightnessIdealRight->setGeometry(QRect(330, 430, 101, 21));
        doubleSpinBoxBrightnessIdealRight->setMaximum(255.000000000000000);
        label_103 = new QLabel(frame);
        label_103->setObjectName("label_103");
        label_103->setGeometry(QRect(190, 460, 131, 21));
        label_103->setFrameShape(QFrame::Panel);
        label_103->setFrameShadow(QFrame::Sunken);
        label_103->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        doubleSpinBoxThresholdRate = new QDoubleSpinBox(frame);
        doubleSpinBoxThresholdRate->setObjectName("doubleSpinBoxThresholdRate");
        doubleSpinBoxThresholdRate->setGeometry(QRect(330, 460, 121, 21));
        doubleSpinBoxThresholdRate->setDecimals(5);
        doubleSpinBoxThresholdRate->setMaximum(255.000000000000000);
        pushButtonChangeItemID = new QPushButton(frame);
        pushButtonChangeItemID->setObjectName("pushButtonChangeItemID");
        pushButtonChangeItemID->setGeometry(QRect(60, 20, 31, 22));
        label_104 = new QLabel(frame);
        label_104->setObjectName("label_104");
        label_104->setGeometry(QRect(440, 390, 91, 21));
        label_104->setFrameShape(QFrame::Panel);
        label_104->setFrameShadow(QFrame::Sunken);
        label_104->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        doubleSpinBoxBrightnessIdealLeftRange = new QDoubleSpinBox(frame);
        doubleSpinBoxBrightnessIdealLeftRange->setObjectName("doubleSpinBoxBrightnessIdealLeftRange");
        doubleSpinBoxBrightnessIdealLeftRange->setGeometry(QRect(440, 410, 91, 21));
        doubleSpinBoxBrightnessIdealLeftRange->setMaximum(255.000000000000000);
        doubleSpinBoxBrightnessIdealRightRange = new QDoubleSpinBox(frame);
        doubleSpinBoxBrightnessIdealRightRange->setObjectName("doubleSpinBoxBrightnessIdealRightRange");
        doubleSpinBoxBrightnessIdealRightRange->setGeometry(QRect(440, 430, 91, 21));
        doubleSpinBoxBrightnessIdealRightRange->setMaximum(255.000000000000000);
        ButtonRelrectOnlyBlock = new QPushButton(EditLineDialog);
        ButtonRelrectOnlyBlock->setObjectName("ButtonRelrectOnlyBlock");
        ButtonRelrectOnlyBlock->setGeometry(QRect(20, 560, 161, 41));
        label_40 = new QLabel(EditLineDialog);
        label_40->setObjectName("label_40");
        label_40->setGeometry(QRect(580, 340, 201, 21));
        label_40->setFrameShape(QFrame::Panel);
        label_40->setFrameShadow(QFrame::Sunken);
        label_40->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        frame_2 = new QFrame(EditLineDialog);
        frame_2->setObjectName("frame_2");
        frame_2->setGeometry(QRect(560, 60, 231, 151));
        frame_2->setFrameShape(QFrame::StyledPanel);
        frame_2->setFrameShadow(QFrame::Sunken);
        pushButtonTest = new QPushButton(frame_2);
        pushButtonTest->setObjectName("pushButtonTest");
        pushButtonTest->setGeometry(QRect(30, 10, 151, 31));
        label_10 = new QLabel(frame_2);
        label_10->setObjectName("label_10");
        label_10->setGeometry(QRect(20, 50, 121, 21));
        label_10->setFrameShape(QFrame::Panel);
        label_10->setFrameShadow(QFrame::Sunken);
        label_10->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_11 = new QLabel(frame_2);
        label_11->setObjectName("label_11");
        label_11->setGeometry(QRect(20, 100, 121, 21));
        label_11->setFrameShape(QFrame::Panel);
        label_11->setFrameShadow(QFrame::Sunken);
        label_11->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        labelPosDiffX = new QLabel(frame_2);
        labelPosDiffX->setObjectName("labelPosDiffX");
        labelPosDiffX->setGeometry(QRect(140, 50, 81, 21));
        labelPosDiffX->setFrameShape(QFrame::Panel);
        labelPosDiffX->setFrameShadow(QFrame::Sunken);
        labelPosDiffX->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        labelPosDiffY = new QLabel(frame_2);
        labelPosDiffY->setObjectName("labelPosDiffY");
        labelPosDiffY->setGeometry(QRect(140, 100, 81, 21));
        labelPosDiffY->setFrameShape(QFrame::Panel);
        labelPosDiffY->setFrameShadow(QFrame::Sunken);
        labelPosDiffY->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        labelPosDiffYUnit = new QLabel(frame_2);
        labelPosDiffYUnit->setObjectName("labelPosDiffYUnit");
        labelPosDiffYUnit->setGeometry(QRect(140, 120, 81, 21));
        QPalette palette7;
        QBrush brush4(QColor(255, 255, 255, 255));
        brush4.setStyle(Qt::BrushStyle::SolidPattern);
        palette7.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush4);
        palette7.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Window, brush2);
        palette7.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush4);
        palette7.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Window, brush2);
        palette7.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush2);
        palette7.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Window, brush2);
        labelPosDiffYUnit->setPalette(palette7);
        labelPosDiffYUnit->setAutoFillBackground(true);
        labelPosDiffYUnit->setFrameShape(QFrame::Panel);
        labelPosDiffYUnit->setFrameShadow(QFrame::Sunken);
        labelPosDiffYUnit->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        labelPosDiffXUnit = new QLabel(frame_2);
        labelPosDiffXUnit->setObjectName("labelPosDiffXUnit");
        labelPosDiffXUnit->setGeometry(QRect(140, 70, 81, 21));
        QPalette palette8;
        palette8.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush4);
        palette8.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Window, brush2);
        palette8.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush4);
        palette8.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Window, brush2);
        palette8.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush2);
        palette8.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Window, brush2);
        labelPosDiffXUnit->setPalette(palette8);
        labelPosDiffXUnit->setAutoFillBackground(true);
        labelPosDiffXUnit->setFrameShape(QFrame::Panel);
        labelPosDiffXUnit->setFrameShadow(QFrame::Sunken);
        labelPosDiffXUnit->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        labelUnitName_7 = new QLabel(frame_2);
        labelUnitName_7->setObjectName("labelUnitName_7");
        labelUnitName_7->setGeometry(QRect(40, 70, 91, 20));
        labelUnitName_7->setFrameShape(QFrame::NoFrame);
        labelUnitName_7->setFrameShadow(QFrame::Sunken);
        labelUnitName_7->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        labelUnitName_8 = new QLabel(frame_2);
        labelUnitName_8->setObjectName("labelUnitName_8");
        labelUnitName_8->setGeometry(QRect(40, 120, 91, 20));
        labelUnitName_8->setFrameShape(QFrame::NoFrame);
        labelUnitName_8->setFrameShadow(QFrame::Sunken);
        labelUnitName_8->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_6 = new QLabel(EditLineDialog);
        label_6->setObjectName("label_6");
        label_6->setGeometry(QRect(10, 10, 62, 20));
        label_6->setFrameShape(QFrame::Panel);
        label_6->setFrameShadow(QFrame::Sunken);
        label_6->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        pushButtonChangeLib = new QPushButton(EditLineDialog);
        pushButtonChangeLib->setObjectName("pushButtonChangeLib");
        pushButtonChangeLib->setGeometry(QRect(310, 30, 31, 23));
        label_7 = new QLabel(EditLineDialog);
        label_7->setObjectName("label_7");
        label_7->setGeometry(QRect(70, 10, 241, 20));
        label_7->setFrameShape(QFrame::Panel);
        label_7->setFrameShadow(QFrame::Sunken);
        label_7->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        ButtonLoadFromLibrary = new QPushButton(EditLineDialog);
        ButtonLoadFromLibrary->setObjectName("ButtonLoadFromLibrary");
        ButtonLoadFromLibrary->setGeometry(QRect(190, 610, 161, 41));
        ButtonClose = new QPushButton(EditLineDialog);
        ButtonClose->setObjectName("ButtonClose");
        ButtonClose->setGeometry(QRect(620, 610, 171, 41));
        ButtonReflectAllBlocks = new QPushButton(EditLineDialog);
        ButtonReflectAllBlocks->setObjectName("ButtonReflectAllBlocks");
        ButtonReflectAllBlocks->setGeometry(QRect(190, 560, 201, 41));
        Edit_LibName = new QLineEdit(EditLineDialog);
        Edit_LibName->setObjectName("Edit_LibName");
        Edit_LibName->setGeometry(QRect(70, 30, 241, 21));
        Edit_LibName->setReadOnly(true);

        retranslateUi(EditLineDialog);

        QMetaObject::connectSlotsByName(EditLineDialog);
    } // setupUi

    void retranslateUi(QWidget *EditLineDialog)
    {
        EditLineDialog->setWindowTitle(QCoreApplication::translate("EditLineDialog", "Threshold MeasureLineMove Line", nullptr));
        EditLibID->setText(QCoreApplication::translate("EditLineDialog", "12345", nullptr));
        ButtonSaveToLibrary->setText(QCoreApplication::translate("EditLineDialog", "\343\203\251\343\202\244\343\203\226\343\203\251\343\203\252\343\201\253\344\277\235\345\255\230", nullptr));
        label_92->setText(QCoreApplication::translate("EditLineDialog", "\346\216\242\347\264\242\343\203\211\343\203\203\343\203\210", nullptr));
        EditName->setText(QString());
        label_4->setText(QCoreApplication::translate("EditLineDialog", "\345\200\213\345\210\245\345\220\215\347\247\260", nullptr));
        label_94->setText(QCoreApplication::translate("EditLineDialog", "\343\202\272\343\203\254\343\200\200\344\270\212\351\231\220\343\201\227\343\201\215\343\201\204\345\200\244\357\274\210\346\234\200\345\260\217\357\274\220\357\274\211", nullptr));
        label_93->setText(QCoreApplication::translate("EditLineDialog", "\343\202\272\343\203\254\343\200\200\344\270\213\351\231\220\343\201\227\343\201\215\343\201\204\345\200\244\357\274\210\346\234\200\345\260\217\357\274\220\357\274\211", nullptr));
        label_95->setText(QCoreApplication::translate("EditLineDialog", "\350\274\252\351\203\255\345\271\205", nullptr));
        checkBoxPrevailLeft->setText(QCoreApplication::translate("EditLineDialog", "Prevail left brightness", nullptr));
        checkBoxPrevailRight->setText(QCoreApplication::translate("EditLineDialog", "Prevail right brightness", nullptr));
        label_96->setText(QCoreApplication::translate("EditLineDialog", "\343\203\236\343\203\203\343\203\201\343\203\263\343\202\260\351\226\213\345\247\213\344\275\215\347\275\256(0.0-1.0)", nullptr));
        label_97->setText(QCoreApplication::translate("EditLineDialog", "\343\203\236\343\203\203\343\203\201\343\203\263\343\202\260\347\265\202\344\272\206\344\275\215\347\275\256(0.0-1.0)", nullptr));
        checkBoxEnable->setText(QCoreApplication::translate("EditLineDialog", "Enable", nullptr));
        label_8->setText(QCoreApplication::translate("EditLineDialog", "ItemID", nullptr));
        EditItemID->setText(QCoreApplication::translate("EditLineDialog", "12345", nullptr));
        labelUnitName_4->setText(QCoreApplication::translate("EditLineDialog", "mm", nullptr));
        label_98->setText(QCoreApplication::translate("EditLineDialog", "Library", nullptr));
        labelUnitName_5->setText(QCoreApplication::translate("EditLineDialog", "mm", nullptr));
        labelUnitName_6->setText(QCoreApplication::translate("EditLineDialog", "mm", nullptr));
        label_99->setText(QCoreApplication::translate("EditLineDialog", "Value", nullptr));
        label_100->setText(QCoreApplication::translate("EditLineDialog", "Used layer", nullptr));
        comboBoxSearchType->setItemText(0, QCoreApplication::translate("EditLineDialog", "Separated smart match", nullptr));
        comboBoxSearchType->setItemText(1, QCoreApplication::translate("EditLineDialog", "Comparable brightness difference", nullptr));
        comboBoxSearchType->setItemText(2, QCoreApplication::translate("EditLineDialog", "Distance-Line:Inside=HighVariance", nullptr));
        comboBoxSearchType->setItemText(3, QCoreApplication::translate("EditLineDialog", "Simple brightness difference", nullptr));
        comboBoxSearchType->setItemText(4, QCoreApplication::translate("EditLineDialog", "Simple brightness difference Rate", nullptr));
        comboBoxSearchType->setItemText(5, QCoreApplication::translate("EditLineDialog", "Div from outside", nullptr));
        comboBoxSearchType->setItemText(6, QCoreApplication::translate("EditLineDialog", "Div center", nullptr));
        comboBoxSearchType->setItemText(7, QCoreApplication::translate("EditLineDialog", "Max Difference of deviation", nullptr));

        label_101->setText(QCoreApplication::translate("EditLineDialog", "\345\267\246\345\201\264\347\220\206\346\203\263\350\274\235\345\272\246", nullptr));
        label_102->setText(QCoreApplication::translate("EditLineDialog", "\345\217\263\345\201\264\347\220\206\346\203\263\350\274\235\345\272\246", nullptr));
        label_103->setText(QCoreApplication::translate("EditLineDialog", "\346\261\272\345\256\232\345\211\262\345\220\210", nullptr));
        pushButtonChangeItemID->setText(QCoreApplication::translate("EditLineDialog", "...", nullptr));
        label_104->setText(QCoreApplication::translate("EditLineDialog", "\350\274\235\345\272\246\347\257\204\345\233\262", nullptr));
        ButtonRelrectOnlyBlock->setText(QCoreApplication::translate("EditLineDialog", "\343\201\223\343\201\256\347\267\232\343\201\240\343\201\221\343\201\253\345\217\215\346\230\240", nullptr));
        label_40->setText(QCoreApplication::translate("EditLineDialog", "\345\275\223\350\251\262\347\256\207\346\211\200\343\201\256\343\203\220\343\203\251\343\201\244\343\201\215\343\202\260\343\203\251\343\203\225", nullptr));
        pushButtonTest->setText(QCoreApplication::translate("EditLineDialog", "Test", nullptr));
        label_10->setText(QCoreApplication::translate("EditLineDialog", "\357\274\270\346\226\271\345\220\221\344\275\215\347\275\256\343\202\272\343\203\254", nullptr));
        label_11->setText(QCoreApplication::translate("EditLineDialog", "\357\274\271\346\226\271\345\220\221\344\275\215\347\275\256\343\202\272\343\203\254", nullptr));
        labelPosDiffX->setText(QString());
        labelPosDiffY->setText(QString());
        labelPosDiffYUnit->setText(QString());
        labelPosDiffXUnit->setText(QString());
        labelUnitName_7->setText(QCoreApplication::translate("EditLineDialog", "mm", nullptr));
        labelUnitName_8->setText(QCoreApplication::translate("EditLineDialog", "mm", nullptr));
        label_6->setText(QCoreApplication::translate("EditLineDialog", "\343\203\251\343\202\244\343\203\226\343\203\251\343\203\252\357\274\251\357\274\244", nullptr));
        pushButtonChangeLib->setText(QCoreApplication::translate("EditLineDialog", "...", nullptr));
        label_7->setText(QCoreApplication::translate("EditLineDialog", "\343\203\251\343\202\244\343\203\226\343\203\251\343\203\252\345\220\215\347\247\260", nullptr));
        ButtonLoadFromLibrary->setText(QCoreApplication::translate("EditLineDialog", "\343\203\251\343\202\244\343\203\226\343\203\251\343\203\252\343\201\213\343\202\211\350\252\255\343\201\277\345\207\272\343\201\227", nullptr));
        ButtonClose->setText(QCoreApplication::translate("EditLineDialog", "\351\226\211\343\201\230\343\202\213", nullptr));
        ButtonReflectAllBlocks->setText(QCoreApplication::translate("EditLineDialog", "\345\220\214\344\270\200\347\250\256\351\241\236\343\201\256\347\267\232\343\201\253\345\217\215\346\230\240", nullptr));
        Edit_LibName->setText(QCoreApplication::translate("EditLineDialog", "XXX", nullptr));
    } // retranslateUi

};

namespace Ui {
    class EditLineDialog: public Ui_EditLineDialog {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_EDITLINEDIALOG_H
