#ifndef PROPERTYSKIPMARK_GLOBAL_H
#define PROPERTYSKIPMARK_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PROPERTYSKIPMARK_LIB
# define PROPERTYSKIPMARK_EXPORT Q_DECL_EXPORT
#else
# define PROPERTYSKIPMARK_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTYSKIPMARK_GLOBAL_H
