#ifndef SETFILTERTOMOVEXY_GLOBAL_H
#define SETFILTERTOMOVEXY_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SETFILTERTOMOVEXY_LIB
# define SETFILTERTOMOVEXY_EXPORT Q_DECL_EXPORT
#else
# define SETFILTERTOMOVEXY_EXPORT Q_DECL_IMPORT
#endif

#endif // SETFILTERTOMOVEXY_GLOBAL_H
