#ifndef INTEGRATIONSHOWTOTAL_GLOBAL_H
#define INTEGRATIONSHOWTOTAL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef INTEGRATIONSHOWTOTAL_LIB
# define INTEGRATIONSHOWTOTAL_EXPORT Q_DECL_EXPORT
#else
# define INTEGRATIONSHOWTOTAL_EXPORT Q_DECL_IMPORT
#endif

#endif // INTEGRATIONSHOWTOTAL_GLOBAL_H
