#ifndef CCSCONTROLBYPIO2CH_GLOBAL_H
#define CCSCONTROLBYPIO2CH_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef CCSCONTROLBYPIO2CH_LIB
# define CCSCONTROLBYPIO2CH_EXPORT Q_DECL_EXPORT
#else
# define CCSCONTROLBYPIO2CH_EXPORT Q_DECL_IMPORT
#endif

#endif // CCSCONTROLBYPIO2CH_GLOBAL_H
