#ifndef PROPERTYALIGNMENTPROJECTION_GLOBAL_H
#define PROPERTYALIGNMENTPROJECTION_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PROPERTYALIGNMENTPROJECTION_LIB
# define PROPERTYALIGNMENTPROJECTION_EXPORT Q_DECL_EXPORT
#else
# define PROPERTYALIGNMENTPROJECTION_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTYALIGNMENTPROJECTION_GLOBAL_H
