# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./PropertyAlignmentProjection.h \
    ./PropertyAlignmentProjectionPacket.h \
    ./propertyalignmentprojection_global.h \
    ./AddItemDialog.h \
    ./PropertyAlignmentProjectionForm.h
SOURCES += ../../Algorithm/AlignmentProjection/XAlignmentProjectionCommon.cpp \
    ../../Open/GUIDllCommon.cpp \
    ../../Open/SystemVersion.cpp \
    ./AddItemDialog.cpp \
    ./PropertyAlignmentProjection.cpp \
    ./PropertyAlignmentProjectionForm.cpp \
    ./PropertyAlignmentProjectionPacket.cpp
FORMS += ./PropertyAlignmentProjectionForm.ui \
    ./AddItemDialog.ui
