#ifndef INTEGRATIONOUTPUTCONTROLLER_GLOBAL_H
#define INTEGRATIONOUTPUTCONTROLLER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef INTEGRATIONOUTPUTCONTROLLER_LIB
# define INTEGRATIONOUTPUTCONTROLLER_EXPORT Q_DECL_EXPORT
#else
# define INTEGRATIONOUTPUTCONTROLLER_EXPORT Q_DECL_IMPORT
#endif

#endif // INTEGRATIONOUTPUTCONTROLLER_GLOBAL_H
