#ifndef BUTTONLOADMONOBMPINANYPAGELAYER_GLOBAL_H
#define BUTTONLOADMONOBMPINANYPAGELAYER_GLOBAL_H

#include <qglobal.h>

#ifdef BUTTONLOADMONOBMPINANYPAGELAYER_LIB
# define BUTTONLOADMONOBMPINANYPAGELAYER_EXPORT Q_DECL_EXPORT
#else
# define BUTTONLOADMONOBMPINANYPAGELAYER_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONLOADMONOBMPINANYPAGELAYER_GLOBAL_H
