#ifndef INTEGRATIONCLEARNGTHUMBNAIL_GLOBAL_H
#define INTEGRATIONCLEARNGTHUMBNAIL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef INTEGRATIONCLEARNGTHUMBNAIL_LIB
# define INTEGRATIONCLEARNGTHUMBNAIL_EXPORT Q_DECL_EXPORT
#else
# define INTEGRATIONCLEARNGTHUMBNAIL_EXPORT Q_DECL_IMPORT
#endif

#endif // INTEGRATIONCLEARNGTHUMBNAIL_GLOBAL_H
