#ifndef INTEGRATIONRESULTLOADER_GLOBAL_H
#define INTEGRATIONRESULTLOADER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef INTEGRATIONRESULTLOADER_LIB
# define INTEGRATIONRESULTLOADER_EXPORT Q_DECL_EXPORT
#else
# define INTEGRATIONRESULTLOADER_EXPORT Q_DECL_IMPORT
#endif

#endif // INTEGRATIONRESULTLOADER_GLOBAL_H
