#ifndef MULTIFILEMAPIMAGEPANEL_GLOBAL_H
#define MULTIFILEMAPIMAGEPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef MULTIFILEMAPIMAGEPANEL_LIB
# define MULTIFILEMAPIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define MULTIFILEMAPIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // MULTIFILEMAPIMAGEPANEL_GLOBAL_H
