#ifndef DENTIMAGEPANEL_GLOBAL_H
#define DENTIMAGEPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef DENTIMAGEPANEL_LIB
# define DENTIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define DENTIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // DENTIMAGEPANEL_GLOBAL_H
