#ifndef INTEGRATIONCHANGEPHASE_GLOBAL_H
#define INTEGRATIONCHANGEPHASE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef INTEGRATIONCHANGEPHASE_LIB
# define INTEGRATIONCHANGEPHASE_EXPORT Q_DECL_EXPORT
#else
# define INTEGRATIONCHANGEPHASE_EXPORT Q_DECL_IMPORT
#endif

#endif // INTEGRATIONCHANGEPHASE_GLOBAL_H
