#ifndef BUTTONLEARNINGOK_GLOBAL_H
#define BUTTONLEARNINGOK_GLOBAL_H

#include <qglobal.h>

#ifdef BUTTONLEARNINGOK_LIB
# define BUTTONLEARNINGOK_EXPORT Q_DECL_EXPORT
#else
# define BUTTONLEARNINGOK_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONLEARNINGOK_GLOBAL_H
