#ifndef PROPERTYCHECKBRIGHTNESS_GLOBAL_H
#define PROPERTYCHECKBRIGHTNESS_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PROPERTYCHECKBRIGHTNESS_LIB
# define PROPERTYCHECKBRIGHTNESS_EXPORT Q_DECL_EXPORT
#else
# define PROPERTYCHECKBRIGHTNESS_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTYCHECKBRIGHTNESS_GLOBAL_H
