#ifndef EVOBJBUTTONAUTOINSPECTION_GLOBAL_H
#define EVOBJBUTTONAUTOINSPECTION_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef EVOBJBUTTONAUTOINSPECTION_LIB
# define EVOBJBUTTONAUTOINSPECTION_EXPORT Q_DECL_EXPORT
#else
# define EVOBJBUTTONAUTOINSPECTION_EXPORT Q_DECL_IMPORT
#endif

#endif // EVOBJBUTTONAUTOINSPECTION_GLOBAL_H
