#ifndef CATEGORIZEDSHADER_GLOBAL_H
#define CATEGORIZEDSHADER_GLOBAL_H

#include <qglobal.h>

#ifdef CATEGORIZEDSHADER_LIB
# define CATEGORIZEDSHADER_EXPORT Q_DECL_EXPORT
#else
# define CATEGORIZEDSHADER_EXPORT Q_DECL_IMPORT
#endif

#endif // CATEGORIZEDSHADER_GLOBAL_H
