#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(BUTTONREPLACECOLORINLIBID_LIB)
#  define BUTTONREPLACECOLORINLIBID_EXPORT Q_DECL_EXPORT
# else
#  define BUTTONREPLACECOLORINLIBID_EXPORT Q_DECL_IMPORT
# endif
#else
# define BUTTONREPLACECOLORINLIBID_EXPORT
#endif
