#ifndef GRAPHTRENDKIDA_GLOBAL_H
#define GRAPHTRENDKIDA_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef GRAPHTRENDKIDA_LIB
# define GRAPHTRENDKIDA_EXPORT Q_DECL_EXPORT
#else
# define GRAPHTRENDKIDA_EXPORT Q_DECL_IMPORT
#endif

#endif // GRAPHTRENDKIDA_GLOBAL_H
