#ifndef BUTTONALIGNMENTLARGETRANSFORM_GLOBAL_H
#define BUTTONALIGNMENTLARGETRANSFORM_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONALIGNMENTLARGETRANSFORM_LIB
# define BUTTONALIGNMENTLARGETRANSFORM_EXPORT Q_DECL_EXPORT
#else
# define BUTTONALIGNMENTLARGETRANSFORM_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONALIGNMENTLARGETRANSFORM_GLOBAL_H
