#ifndef CACHETARGETIMAGE_GLOBAL_H
#define CACHETARGETIMAGE_GLOBAL_H

#include <qglobal.h>

#ifdef CACHETARGETIMAGE_LIB
# define CACHETARGETIMAGE_EXPORT Q_DECL_EXPORT
#else
# define CACHETARGETIMAGE_EXPORT Q_DECL_IMPORT
#endif

#endif // CACHETARGETIMAGE_GLOBAL_H
