#ifndef VCUTIMAGEPANEL_GLOBAL_H
#define VCUTIMAGEPANEL_GLOBAL_H

#include <qglobal.h>

#ifdef VCUTIMAGEPANEL_LIB
# define VCUTIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define VCUTIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // VCUTIMAGEPANEL_GLOBAL_H
