#ifndef BUTTONCLEARHISTOGRAM_GLOBAL_H
#define BUTTONCLEARHISTOGRAM_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONCLEARHISTOGRAM_LIB
# define BUTTONCLEARHISTOGRAM_EXPORT Q_DECL_EXPORT
#else
# define BUTTONCLEARHISTOGRAM_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONCLEARHISTOGRAM_GLOBAL_H
