#ifndef BUTTONLOADMASTERDATAWITHOUTMACHINE_GLOBAL_H
#define BUTTONLOADMASTERDATAWITHOUTMACHINE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONLOADMASTERDATAWITHOUTMACHINE_LIB
# define BUTTONLOADMASTERDATAWITHOUTMACHINE_EXPORT Q_DECL_EXPORT
#else
# define BUTTONLOADMASTERDATAWITHOUTMACHINE_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONLOADMASTERDATAWITHOUTMACHINE_GLOBAL_H
