#ifndef FILTERUDCOLORSHIFT_GLOBAL_H
#define FILTERUDCOLORSHIFT_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef FILTERUDCOLORSHIFT_LIB
# define FILTERUDCOLORSHIFT_EXPORT Q_DECL_EXPORT
#else
# define FILTERUDCOLORSHIFT_EXPORT Q_DECL_IMPORT
#endif

#endif // FILTERUDCOLORSHIFT_GLOBAL_H
