# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------
QT += core gui network sql widgets

TEMPLATE = lib
TARGET = Alignment
DESTDIR = ../
CONFIG += release
DEFINES += ALIGNMENT_LIB
LIBS += -L"./../../Lib/Release" \
    -lComponent \
    -lDisplayImage \
    -lModelPageLayerItem \
    -lServiceLib
MOC_DIR += ./GeneratedFiles/$(ConfigurationName)
OBJECTS_DIR += release
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles
INCLUDEPATH += ./GeneratedFiles/$(ConfigurationName)
DEPENDPATH += ./GeneratedFiles/$(ConfigurationName)
INCLUDEPATH += ./GeneratedFiles
DEPENDPATH += ./GeneratedFiles
INCLUDEPATH += ../../Algorithm/Alignment
DEPENDPATH += ../../Algorithm/Alignment
INCLUDEPATH += ../../OpenSource/Component
DEPENDPATH += ../../OpenSource/Component
INCLUDEPATH += ../../OpenSource/DisplayImage
DEPENDPATH += ../../OpenSource/DisplayImage
INCLUDEPATH += ../../Open
DEPENDPATH += ../../Open
INCLUDEPATH += ./GeneratedFiles/$(Configuration)
DEPENDPATH += ./GeneratedFiles/$(Configuration)
unix: LIBS += -L$$PWD/../../../../Qt5.15.8/5.15.8/gcc_64/lib/ -lQt5Core
unix: LIBS += -L$$PWD/../../../../Qt5.15.8/5.15.8/gcc_64/lib/ -lQt5Gui
unix: LIBS += -L$$PWD/../../../../Qt5.15.8/5.15.8/gcc_64/lib/ -lQt5Network
unix: LIBS += -L$$PWD/../../../../Qt5.15.8/5.15.8/gcc_64/lib/ -lQt5Sql
unix: LIBS += -L$$PWD/../../../../Qt5.15.8/5.15.8/gcc_64/lib/ -lQt5Widgets
INCLUDEPATH += $$PWD/../../../../Qt5.15.8/5.15.8/gcc_64/include/\QtCore
INCLUDEPATH += $$PWD/../../../../Qt5.15.8/5.15.8/gcc_64/include/\QtGui
INCLUDEPATH += $$PWD/../../../../Qt5.15.8/5.15.8/gcc_64/include/\QtNetwork
INCLUDEPATH += $$PWD/../../../../Qt5.15.8/5.15.8/gcc_64/include/\QtSql
INCLUDEPATH += $$PWD/../../../../Qt5.15.8/5.15.8/gcc_64/include/\QtWidgets
INCLUDEPATH += $$PWD/../../../../Qt5.15.8/5.15.8/gcc_64/include/
DEPENDPATH += $$PWD/../../../../Qt5.15.8/5.15.8/gcc_64/include/
include(Alignment.pri)
