/********************************************************************************
** Form generated from reading UI file 'XMLExplorer.ui'
**
** Created by: Qt User Interface Compiler version 6.10.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_XMLEXPLORER_H
#define UI_XMLEXPLORER_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLayout>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QListWidget>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QToolBox>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_XMLExplorerClass
{
public:
    QWidget *centralWidget;
    QFrame *frame;
    QLabel *label;
    QSpinBox *spinBoxPortNumber;
    QPushButton *pushButtonConnect;
    QLabel *label_2;
    QLineEdit *lineEditIPAddress;
    QListWidget *listWidgetOperationalHandleList;
    QLabel *label_3;
    QPushButton *pushButtonOpenXMLOperation;
    QPushButton *pushButtonClose;
    QPushButton *pushButtonDup;
    QLineEdit *lineEditTableStr;
    QLabel *label_5;
    QLabel *label_38;
    QListWidget *listWidgetTableList;
    QPushButton *pushButtonEnumTable;
    QLabel *label_39;
    QLineEdit *lineEditEnumTableFilter;
    QPushButton *pushButtonBackup;
    QPushButton *pushButtonRestore;
    QPushButton *pushButtonRemove;
    QFrame *frame_2;
    QToolBox *toolBox;
    QWidget *page;
    QLabel *label_4;
    QTextEdit *textEditInsertXMLStr;
    QPushButton *pushButtonExecuteInsertXML;
    QLabel *label_27;
    QTextEdit *textEditInsertXMLWhereStr;
    QWidget *page_3;
    QTextEdit *textEditUpdateXMLStr;
    QPushButton *pushButtonExecuteUpdateXML;
    QLabel *label_6;
    QWidget *page_4;
    QFrame *frame_3;
    QPushButton *pushButtonExecuteDeleteXML;
    QFrame *frame_4;
    QTextEdit *textEditDeleteXMLWhereStr;
    QLabel *label_40;
    QPushButton *pushButtonExecuteDeleteMultiXML;
    QWidget *page_5;
    QTextEdit *textEditInsUpdateAttrXMLStr;
    QPushButton *pushButtonExecuteInsUpdateAttrXML;
    QLabel *label_7;
    QWidget *page_6;
    QPushButton *pushButtonExecuteDeleteAttrXML;
    QTextEdit *textEditDeleteAttrXMLStr;
    QLabel *label_8;
    QWidget *page_7;
    QTextEdit *textEditSelectXMLOutputStr;
    QPushButton *pushButtonExecuteSelectXML;
    QLabel *label_9;
    QTextEdit *textEditSelectXMLWhereStr;
    QLabel *label_10;
    QLabel *label_11;
    QTextEdit *textEditSelectXMLOrderStr;
    QLabel *label_12;
    QListWidget *listWidgetSelectXMLResultStr;
    QWidget *page_8;
    QLabel *label_13;
    QLabel *label_14;
    QPushButton *pushButtonExecuteSelectFirstXML;
    QLabel *label_15;
    QTextEdit *textEditSelectFirstXMLOutputStr;
    QTextEdit *textEditSelectFirstXMLOrderStr;
    QLabel *label_16;
    QTextEdit *textEditSelectFirstXMLWhereStr;
    QTextEdit *textEditSelectFirstXMLResultStr;
    QWidget *page_13;
    QPushButton *pushButtonExecuteSelectLastXML;
    QTextEdit *textEditSelectLastXMLResultStr;
    QTextEdit *textEditSelectLastXMLOutputStr;
    QLabel *label_28;
    QLabel *label_29;
    QTextEdit *textEditSelectLastXMLOrderStr;
    QTextEdit *textEditSelectLastXMLWhereStr;
    QLabel *label_30;
    QLabel *label_31;
    QWidget *page_9;
    QPushButton *pushButtonExecuteSelectNextXML;
    QLabel *label_25;
    QTextEdit *textEditSelectNextXMLResultStr;
    QWidget *page_14;
    QLabel *label_32;
    QPushButton *pushButtonExecuteSelectPrevXML;
    QTextEdit *textEditSelectPrevXMLResultStr;
    QWidget *page_10;
    QLabel *label_17;
    QLabel *label_18;
    QPushButton *pushButtonExecuteChildSelectXML;
    QLabel *label_19;
    QTextEdit *textEditChildSelectXMLOutputStr;
    QTextEdit *textEditChildSelectXMLOrderStr;
    QLabel *label_20;
    QTextEdit *textEditChildSelectXMLWhereStr;
    QListWidget *listWidgetChildSelectXMLResultStr;
    QWidget *page_11;
    QPushButton *pushButtonExecuteChildSelectFirstXML;
    QLabel *label_21;
    QTextEdit *textEditChildSelectFirstXMLOrderStr;
    QLabel *label_22;
    QLabel *label_23;
    QTextEdit *textEditChildSelectFirstXMLWhereStr;
    QTextEdit *textEditChildSelectFirstXMLOutputStr;
    QLabel *label_24;
    QTextEdit *textEditChildSelectFirstXMLResultStr;
    QWidget *page_15;
    QTextEdit *textEditChildSelectLastXMLWhereStr;
    QLabel *label_33;
    QTextEdit *textEditChildSelectLastXMLResultStr;
    QLabel *label_34;
    QTextEdit *textEditChildSelectLastXMLOutputStr;
    QLabel *label_35;
    QLabel *label_36;
    QPushButton *pushButtonExecuteChildSelectFirstXML_2;
    QTextEdit *textEditChildSelectLastXMLOrderStr;
    QWidget *page_12;
    QPushButton *pushButtonExecuteChildSelectNextXML;
    QLabel *label_26;
    QTextEdit *textEditChildSelectNextXMLResultStr;
    QWidget *page_16;
    QTextEdit *textEditChildSelectPrevXMLResultStr;
    QLabel *label_37;
    QPushButton *pushButtonExecuteChildSelectPrevXML;
    QWidget *page_2;
    QPushButton *pushButtonCopyPointer;
    QCheckBox *checkBoxResult;
    QPushButton *pushButtonSetting;

    void setupUi(QMainWindow *XMLExplorerClass)
    {
        if (XMLExplorerClass->objectName().isEmpty())
            XMLExplorerClass->setObjectName("XMLExplorerClass");
        XMLExplorerClass->resize(1069, 928);
        centralWidget = new QWidget(XMLExplorerClass);
        centralWidget->setObjectName("centralWidget");
        frame = new QFrame(centralWidget);
        frame->setObjectName("frame");
        frame->setGeometry(QRect(0, 10, 301, 911));
        frame->setFrameShape(QFrame::Panel);
        frame->setFrameShadow(QFrame::Sunken);
        label = new QLabel(frame);
        label->setObjectName("label");
        label->setGeometry(QRect(10, 10, 81, 20));
        label->setFrameShape(QFrame::Panel);
        label->setFrameShadow(QFrame::Sunken);
        label->setAlignment(Qt::AlignCenter);
        spinBoxPortNumber = new QSpinBox(frame);
        spinBoxPortNumber->setObjectName("spinBoxPortNumber");
        spinBoxPortNumber->setGeometry(QRect(90, 40, 71, 22));
        spinBoxPortNumber->setMaximum(65535);
        spinBoxPortNumber->setValue(12345);
        pushButtonConnect = new QPushButton(frame);
        pushButtonConnect->setObjectName("pushButtonConnect");
        pushButtonConnect->setGeometry(QRect(180, 40, 91, 31));
        label_2 = new QLabel(frame);
        label_2->setObjectName("label_2");
        label_2->setGeometry(QRect(10, 40, 81, 20));
        label_2->setFrameShape(QFrame::Panel);
        label_2->setFrameShadow(QFrame::Sunken);
        label_2->setAlignment(Qt::AlignCenter);
        lineEditIPAddress = new QLineEdit(frame);
        lineEditIPAddress->setObjectName("lineEditIPAddress");
        lineEditIPAddress->setGeometry(QRect(90, 10, 201, 20));
        listWidgetOperationalHandleList = new QListWidget(frame);
        listWidgetOperationalHandleList->setObjectName("listWidgetOperationalHandleList");
        listWidgetOperationalHandleList->setGeometry(QRect(10, 220, 281, 81));
        label_3 = new QLabel(frame);
        label_3->setObjectName("label_3");
        label_3->setGeometry(QRect(10, 200, 281, 20));
        label_3->setFrameShape(QFrame::Panel);
        label_3->setFrameShadow(QFrame::Sunken);
        label_3->setAlignment(Qt::AlignCenter);
        pushButtonOpenXMLOperation = new QPushButton(frame);
        pushButtonOpenXMLOperation->setObjectName("pushButtonOpenXMLOperation");
        pushButtonOpenXMLOperation->setGeometry(QRect(10, 140, 281, 41));
        pushButtonClose = new QPushButton(frame);
        pushButtonClose->setObjectName("pushButtonClose");
        pushButtonClose->setGeometry(QRect(150, 310, 141, 31));
        pushButtonDup = new QPushButton(frame);
        pushButtonDup->setObjectName("pushButtonDup");
        pushButtonDup->setGeometry(QRect(10, 310, 141, 31));
        lineEditTableStr = new QLineEdit(frame);
        lineEditTableStr->setObjectName("lineEditTableStr");
        lineEditTableStr->setGeometry(QRect(10, 110, 281, 20));
        label_5 = new QLabel(frame);
        label_5->setObjectName("label_5");
        label_5->setGeometry(QRect(10, 90, 281, 20));
        label_5->setFrameShape(QFrame::Panel);
        label_5->setFrameShadow(QFrame::Sunken);
        label_5->setAlignment(Qt::AlignCenter);
        label_38 = new QLabel(frame);
        label_38->setObjectName("label_38");
        label_38->setGeometry(QRect(10, 440, 281, 20));
        label_38->setFrameShape(QFrame::Panel);
        label_38->setFrameShadow(QFrame::Sunken);
        label_38->setAlignment(Qt::AlignCenter);
        listWidgetTableList = new QListWidget(frame);
        listWidgetTableList->setObjectName("listWidgetTableList");
        listWidgetTableList->setGeometry(QRect(10, 460, 281, 401));
        listWidgetTableList->setSelectionMode(QAbstractItemView::MultiSelection);
        listWidgetTableList->setSelectionBehavior(QAbstractItemView::SelectRows);
        listWidgetTableList->setWordWrap(true);
        pushButtonEnumTable = new QPushButton(frame);
        pushButtonEnumTable->setObjectName("pushButtonEnumTable");
        pushButtonEnumTable->setGeometry(QRect(200, 410, 91, 31));
        label_39 = new QLabel(frame);
        label_39->setObjectName("label_39");
        label_39->setGeometry(QRect(10, 400, 171, 20));
        label_39->setFrameShape(QFrame::Panel);
        label_39->setFrameShadow(QFrame::Sunken);
        label_39->setAlignment(Qt::AlignCenter);
        lineEditEnumTableFilter = new QLineEdit(frame);
        lineEditEnumTableFilter->setObjectName("lineEditEnumTableFilter");
        lineEditEnumTableFilter->setGeometry(QRect(10, 420, 171, 20));
        pushButtonBackup = new QPushButton(frame);
        pushButtonBackup->setObjectName("pushButtonBackup");
        pushButtonBackup->setGeometry(QRect(10, 870, 91, 31));
        pushButtonRestore = new QPushButton(frame);
        pushButtonRestore->setObjectName("pushButtonRestore");
        pushButtonRestore->setGeometry(QRect(110, 870, 91, 31));
        pushButtonRemove = new QPushButton(frame);
        pushButtonRemove->setObjectName("pushButtonRemove");
        pushButtonRemove->setGeometry(QRect(210, 870, 81, 31));
        frame_2 = new QFrame(centralWidget);
        frame_2->setObjectName("frame_2");
        frame_2->setGeometry(QRect(320, 10, 741, 881));
        frame_2->setFrameShape(QFrame::StyledPanel);
        frame_2->setFrameShadow(QFrame::Sunken);
        toolBox = new QToolBox(frame_2);
        toolBox->setObjectName("toolBox");
        toolBox->setGeometry(QRect(10, 10, 721, 861));
        page = new QWidget();
        page->setObjectName("page");
        page->setGeometry(QRect(0, 0, 721, 445));
        label_4 = new QLabel(page);
        label_4->setObjectName("label_4");
        label_4->setGeometry(QRect(0, 60, 721, 20));
        label_4->setFrameShape(QFrame::Panel);
        label_4->setFrameShadow(QFrame::Sunken);
        label_4->setAlignment(Qt::AlignCenter);
        textEditInsertXMLStr = new QTextEdit(page);
        textEditInsertXMLStr->setObjectName("textEditInsertXMLStr");
        textEditInsertXMLStr->setGeometry(QRect(0, 80, 721, 131));
        pushButtonExecuteInsertXML = new QPushButton(page);
        pushButtonExecuteInsertXML->setObjectName("pushButtonExecuteInsertXML");
        pushButtonExecuteInsertXML->setGeometry(QRect(310, 220, 91, 31));
        label_27 = new QLabel(page);
        label_27->setObjectName("label_27");
        label_27->setGeometry(QRect(0, 0, 721, 20));
        label_27->setFrameShape(QFrame::Panel);
        label_27->setFrameShadow(QFrame::Sunken);
        label_27->setAlignment(Qt::AlignCenter);
        textEditInsertXMLWhereStr = new QTextEdit(page);
        textEditInsertXMLWhereStr->setObjectName("textEditInsertXMLWhereStr");
        textEditInsertXMLWhereStr->setGeometry(QRect(0, 20, 721, 31));
        toolBox->addItem(page, QString::fromUtf8("InsertXML"));
        page_3 = new QWidget();
        page_3->setObjectName("page_3");
        page_3->setGeometry(QRect(0, 0, 721, 445));
        textEditUpdateXMLStr = new QTextEdit(page_3);
        textEditUpdateXMLStr->setObjectName("textEditUpdateXMLStr");
        textEditUpdateXMLStr->setGeometry(QRect(0, 30, 721, 181));
        pushButtonExecuteUpdateXML = new QPushButton(page_3);
        pushButtonExecuteUpdateXML->setObjectName("pushButtonExecuteUpdateXML");
        pushButtonExecuteUpdateXML->setGeometry(QRect(300, 220, 91, 31));
        label_6 = new QLabel(page_3);
        label_6->setObjectName("label_6");
        label_6->setGeometry(QRect(0, 10, 721, 20));
        label_6->setFrameShape(QFrame::Panel);
        label_6->setFrameShadow(QFrame::Sunken);
        label_6->setAlignment(Qt::AlignCenter);
        toolBox->addItem(page_3, QString::fromUtf8("UpdateXML"));
        page_4 = new QWidget();
        page_4->setObjectName("page_4");
        page_4->setGeometry(QRect(0, 0, 721, 445));
        frame_3 = new QFrame(page_4);
        frame_3->setObjectName("frame_3");
        frame_3->setGeometry(QRect(19, 10, 691, 80));
        frame_3->setFrameShape(QFrame::StyledPanel);
        frame_3->setFrameShadow(QFrame::Sunken);
        pushButtonExecuteDeleteXML = new QPushButton(frame_3);
        pushButtonExecuteDeleteXML->setObjectName("pushButtonExecuteDeleteXML");
        pushButtonExecuteDeleteXML->setGeometry(QRect(240, 20, 201, 31));
        frame_4 = new QFrame(page_4);
        frame_4->setObjectName("frame_4");
        frame_4->setGeometry(QRect(20, 120, 691, 111));
        frame_4->setFrameShape(QFrame::StyledPanel);
        frame_4->setFrameShadow(QFrame::Sunken);
        textEditDeleteXMLWhereStr = new QTextEdit(frame_4);
        textEditDeleteXMLWhereStr->setObjectName("textEditDeleteXMLWhereStr");
        textEditDeleteXMLWhereStr->setGeometry(QRect(10, 30, 661, 31));
        label_40 = new QLabel(frame_4);
        label_40->setObjectName("label_40");
        label_40->setGeometry(QRect(10, 10, 661, 20));
        label_40->setFrameShape(QFrame::Panel);
        label_40->setFrameShadow(QFrame::Sunken);
        label_40->setAlignment(Qt::AlignCenter);
        pushButtonExecuteDeleteMultiXML = new QPushButton(frame_4);
        pushButtonExecuteDeleteMultiXML->setObjectName("pushButtonExecuteDeleteMultiXML");
        pushButtonExecuteDeleteMultiXML->setGeometry(QRect(240, 70, 201, 31));
        toolBox->addItem(page_4, QString::fromUtf8("DeleteXML"));
        page_5 = new QWidget();
        page_5->setObjectName("page_5");
        page_5->setGeometry(QRect(0, 0, 721, 445));
        textEditInsUpdateAttrXMLStr = new QTextEdit(page_5);
        textEditInsUpdateAttrXMLStr->setObjectName("textEditInsUpdateAttrXMLStr");
        textEditInsUpdateAttrXMLStr->setGeometry(QRect(0, 30, 721, 61));
        pushButtonExecuteInsUpdateAttrXML = new QPushButton(page_5);
        pushButtonExecuteInsUpdateAttrXML->setObjectName("pushButtonExecuteInsUpdateAttrXML");
        pushButtonExecuteInsUpdateAttrXML->setGeometry(QRect(300, 100, 91, 31));
        label_7 = new QLabel(page_5);
        label_7->setObjectName("label_7");
        label_7->setGeometry(QRect(0, 10, 721, 20));
        label_7->setFrameShape(QFrame::Panel);
        label_7->setFrameShadow(QFrame::Sunken);
        label_7->setAlignment(Qt::AlignCenter);
        toolBox->addItem(page_5, QString::fromUtf8("InsUpdateAttr"));
        page_6 = new QWidget();
        page_6->setObjectName("page_6");
        page_6->setGeometry(QRect(0, 0, 721, 445));
        pushButtonExecuteDeleteAttrXML = new QPushButton(page_6);
        pushButtonExecuteDeleteAttrXML->setObjectName("pushButtonExecuteDeleteAttrXML");
        pushButtonExecuteDeleteAttrXML->setGeometry(QRect(300, 100, 91, 31));
        textEditDeleteAttrXMLStr = new QTextEdit(page_6);
        textEditDeleteAttrXMLStr->setObjectName("textEditDeleteAttrXMLStr");
        textEditDeleteAttrXMLStr->setGeometry(QRect(0, 30, 721, 61));
        label_8 = new QLabel(page_6);
        label_8->setObjectName("label_8");
        label_8->setGeometry(QRect(0, 10, 721, 20));
        label_8->setFrameShape(QFrame::Panel);
        label_8->setFrameShadow(QFrame::Sunken);
        label_8->setAlignment(Qt::AlignCenter);
        toolBox->addItem(page_6, QString::fromUtf8("DeleteAttr"));
        page_7 = new QWidget();
        page_7->setObjectName("page_7");
        page_7->setGeometry(QRect(0, 0, 721, 445));
        textEditSelectXMLOutputStr = new QTextEdit(page_7);
        textEditSelectXMLOutputStr->setObjectName("textEditSelectXMLOutputStr");
        textEditSelectXMLOutputStr->setGeometry(QRect(0, 20, 721, 31));
        pushButtonExecuteSelectXML = new QPushButton(page_7);
        pushButtonExecuteSelectXML->setObjectName("pushButtonExecuteSelectXML");
        pushButtonExecuteSelectXML->setGeometry(QRect(620, 130, 91, 31));
        label_9 = new QLabel(page_7);
        label_9->setObjectName("label_9");
        label_9->setGeometry(QRect(0, 0, 721, 20));
        label_9->setFrameShape(QFrame::Panel);
        label_9->setFrameShadow(QFrame::Sunken);
        label_9->setAlignment(Qt::AlignCenter);
        textEditSelectXMLWhereStr = new QTextEdit(page_7);
        textEditSelectXMLWhereStr->setObjectName("textEditSelectXMLWhereStr");
        textEditSelectXMLWhereStr->setGeometry(QRect(0, 80, 721, 31));
        label_10 = new QLabel(page_7);
        label_10->setObjectName("label_10");
        label_10->setGeometry(QRect(0, 60, 721, 20));
        label_10->setFrameShape(QFrame::Panel);
        label_10->setFrameShadow(QFrame::Sunken);
        label_10->setAlignment(Qt::AlignCenter);
        label_11 = new QLabel(page_7);
        label_11->setObjectName("label_11");
        label_11->setGeometry(QRect(0, 120, 591, 20));
        label_11->setFrameShape(QFrame::Panel);
        label_11->setFrameShadow(QFrame::Sunken);
        label_11->setAlignment(Qt::AlignCenter);
        textEditSelectXMLOrderStr = new QTextEdit(page_7);
        textEditSelectXMLOrderStr->setObjectName("textEditSelectXMLOrderStr");
        textEditSelectXMLOrderStr->setGeometry(QRect(0, 140, 591, 31));
        label_12 = new QLabel(page_7);
        label_12->setObjectName("label_12");
        label_12->setGeometry(QRect(0, 180, 721, 20));
        label_12->setFrameShape(QFrame::Panel);
        label_12->setFrameShadow(QFrame::Sunken);
        label_12->setAlignment(Qt::AlignCenter);
        listWidgetSelectXMLResultStr = new QListWidget(page_7);
        listWidgetSelectXMLResultStr->setObjectName("listWidgetSelectXMLResultStr");
        listWidgetSelectXMLResultStr->setGeometry(QRect(0, 200, 721, 241));
        toolBox->addItem(page_7, QString::fromUtf8("Select"));
        page_8 = new QWidget();
        page_8->setObjectName("page_8");
        page_8->setGeometry(QRect(0, 0, 721, 445));
        label_13 = new QLabel(page_8);
        label_13->setObjectName("label_13");
        label_13->setGeometry(QRect(0, 60, 721, 20));
        label_13->setFrameShape(QFrame::Panel);
        label_13->setFrameShadow(QFrame::Sunken);
        label_13->setAlignment(Qt::AlignCenter);
        label_14 = new QLabel(page_8);
        label_14->setObjectName("label_14");
        label_14->setGeometry(QRect(0, 180, 721, 20));
        label_14->setFrameShape(QFrame::Panel);
        label_14->setFrameShadow(QFrame::Sunken);
        label_14->setAlignment(Qt::AlignCenter);
        pushButtonExecuteSelectFirstXML = new QPushButton(page_8);
        pushButtonExecuteSelectFirstXML->setObjectName("pushButtonExecuteSelectFirstXML");
        pushButtonExecuteSelectFirstXML->setGeometry(QRect(620, 130, 91, 31));
        label_15 = new QLabel(page_8);
        label_15->setObjectName("label_15");
        label_15->setGeometry(QRect(0, 0, 721, 20));
        label_15->setFrameShape(QFrame::Panel);
        label_15->setFrameShadow(QFrame::Sunken);
        label_15->setAlignment(Qt::AlignCenter);
        textEditSelectFirstXMLOutputStr = new QTextEdit(page_8);
        textEditSelectFirstXMLOutputStr->setObjectName("textEditSelectFirstXMLOutputStr");
        textEditSelectFirstXMLOutputStr->setGeometry(QRect(0, 20, 721, 31));
        textEditSelectFirstXMLOrderStr = new QTextEdit(page_8);
        textEditSelectFirstXMLOrderStr->setObjectName("textEditSelectFirstXMLOrderStr");
        textEditSelectFirstXMLOrderStr->setGeometry(QRect(0, 140, 591, 31));
        label_16 = new QLabel(page_8);
        label_16->setObjectName("label_16");
        label_16->setGeometry(QRect(0, 120, 591, 20));
        label_16->setFrameShape(QFrame::Panel);
        label_16->setFrameShadow(QFrame::Sunken);
        label_16->setAlignment(Qt::AlignCenter);
        textEditSelectFirstXMLWhereStr = new QTextEdit(page_8);
        textEditSelectFirstXMLWhereStr->setObjectName("textEditSelectFirstXMLWhereStr");
        textEditSelectFirstXMLWhereStr->setGeometry(QRect(0, 80, 721, 31));
        textEditSelectFirstXMLResultStr = new QTextEdit(page_8);
        textEditSelectFirstXMLResultStr->setObjectName("textEditSelectFirstXMLResultStr");
        textEditSelectFirstXMLResultStr->setGeometry(QRect(0, 200, 721, 161));
        toolBox->addItem(page_8, QString::fromUtf8("SelectFirst"));
        page_13 = new QWidget();
        page_13->setObjectName("page_13");
        page_13->setGeometry(QRect(0, 0, 721, 445));
        pushButtonExecuteSelectLastXML = new QPushButton(page_13);
        pushButtonExecuteSelectLastXML->setObjectName("pushButtonExecuteSelectLastXML");
        pushButtonExecuteSelectLastXML->setGeometry(QRect(620, 130, 91, 31));
        textEditSelectLastXMLResultStr = new QTextEdit(page_13);
        textEditSelectLastXMLResultStr->setObjectName("textEditSelectLastXMLResultStr");
        textEditSelectLastXMLResultStr->setGeometry(QRect(0, 200, 721, 241));
        textEditSelectLastXMLOutputStr = new QTextEdit(page_13);
        textEditSelectLastXMLOutputStr->setObjectName("textEditSelectLastXMLOutputStr");
        textEditSelectLastXMLOutputStr->setGeometry(QRect(0, 20, 721, 31));
        label_28 = new QLabel(page_13);
        label_28->setObjectName("label_28");
        label_28->setGeometry(QRect(0, 0, 721, 20));
        label_28->setFrameShape(QFrame::Panel);
        label_28->setFrameShadow(QFrame::Sunken);
        label_28->setAlignment(Qt::AlignCenter);
        label_29 = new QLabel(page_13);
        label_29->setObjectName("label_29");
        label_29->setGeometry(QRect(0, 180, 721, 20));
        label_29->setFrameShape(QFrame::Panel);
        label_29->setFrameShadow(QFrame::Sunken);
        label_29->setAlignment(Qt::AlignCenter);
        textEditSelectLastXMLOrderStr = new QTextEdit(page_13);
        textEditSelectLastXMLOrderStr->setObjectName("textEditSelectLastXMLOrderStr");
        textEditSelectLastXMLOrderStr->setGeometry(QRect(0, 140, 591, 31));
        textEditSelectLastXMLWhereStr = new QTextEdit(page_13);
        textEditSelectLastXMLWhereStr->setObjectName("textEditSelectLastXMLWhereStr");
        textEditSelectLastXMLWhereStr->setGeometry(QRect(0, 80, 721, 31));
        label_30 = new QLabel(page_13);
        label_30->setObjectName("label_30");
        label_30->setGeometry(QRect(0, 60, 721, 20));
        label_30->setFrameShape(QFrame::Panel);
        label_30->setFrameShadow(QFrame::Sunken);
        label_30->setAlignment(Qt::AlignCenter);
        label_31 = new QLabel(page_13);
        label_31->setObjectName("label_31");
        label_31->setGeometry(QRect(0, 120, 591, 20));
        label_31->setFrameShape(QFrame::Panel);
        label_31->setFrameShadow(QFrame::Sunken);
        label_31->setAlignment(Qt::AlignCenter);
        toolBox->addItem(page_13, QString::fromUtf8("SelectLast"));
        page_9 = new QWidget();
        page_9->setObjectName("page_9");
        page_9->setGeometry(QRect(0, 0, 721, 445));
        pushButtonExecuteSelectNextXML = new QPushButton(page_9);
        pushButtonExecuteSelectNextXML->setObjectName("pushButtonExecuteSelectNextXML");
        pushButtonExecuteSelectNextXML->setGeometry(QRect(320, 0, 91, 31));
        label_25 = new QLabel(page_9);
        label_25->setObjectName("label_25");
        label_25->setGeometry(QRect(0, 40, 721, 20));
        label_25->setFrameShape(QFrame::Panel);
        label_25->setFrameShadow(QFrame::Sunken);
        label_25->setAlignment(Qt::AlignCenter);
        textEditSelectNextXMLResultStr = new QTextEdit(page_9);
        textEditSelectNextXMLResultStr->setObjectName("textEditSelectNextXMLResultStr");
        textEditSelectNextXMLResultStr->setGeometry(QRect(0, 60, 721, 231));
        toolBox->addItem(page_9, QString::fromUtf8("SelectNext"));
        page_14 = new QWidget();
        page_14->setObjectName("page_14");
        page_14->setGeometry(QRect(0, 0, 721, 445));
        label_32 = new QLabel(page_14);
        label_32->setObjectName("label_32");
        label_32->setGeometry(QRect(0, 40, 721, 20));
        label_32->setFrameShape(QFrame::Panel);
        label_32->setFrameShadow(QFrame::Sunken);
        label_32->setAlignment(Qt::AlignCenter);
        pushButtonExecuteSelectPrevXML = new QPushButton(page_14);
        pushButtonExecuteSelectPrevXML->setObjectName("pushButtonExecuteSelectPrevXML");
        pushButtonExecuteSelectPrevXML->setGeometry(QRect(320, 0, 91, 31));
        textEditSelectPrevXMLResultStr = new QTextEdit(page_14);
        textEditSelectPrevXMLResultStr->setObjectName("textEditSelectPrevXMLResultStr");
        textEditSelectPrevXMLResultStr->setGeometry(QRect(0, 60, 721, 221));
        toolBox->addItem(page_14, QString::fromUtf8("SelectPrev"));
        page_10 = new QWidget();
        page_10->setObjectName("page_10");
        page_10->setGeometry(QRect(0, 0, 721, 445));
        label_17 = new QLabel(page_10);
        label_17->setObjectName("label_17");
        label_17->setGeometry(QRect(0, 60, 721, 20));
        label_17->setFrameShape(QFrame::Panel);
        label_17->setFrameShadow(QFrame::Sunken);
        label_17->setAlignment(Qt::AlignCenter);
        label_18 = new QLabel(page_10);
        label_18->setObjectName("label_18");
        label_18->setGeometry(QRect(0, 180, 721, 20));
        label_18->setFrameShape(QFrame::Panel);
        label_18->setFrameShadow(QFrame::Sunken);
        label_18->setAlignment(Qt::AlignCenter);
        pushButtonExecuteChildSelectXML = new QPushButton(page_10);
        pushButtonExecuteChildSelectXML->setObjectName("pushButtonExecuteChildSelectXML");
        pushButtonExecuteChildSelectXML->setGeometry(QRect(620, 130, 91, 31));
        label_19 = new QLabel(page_10);
        label_19->setObjectName("label_19");
        label_19->setGeometry(QRect(0, 0, 721, 20));
        label_19->setFrameShape(QFrame::Panel);
        label_19->setFrameShadow(QFrame::Sunken);
        label_19->setAlignment(Qt::AlignCenter);
        textEditChildSelectXMLOutputStr = new QTextEdit(page_10);
        textEditChildSelectXMLOutputStr->setObjectName("textEditChildSelectXMLOutputStr");
        textEditChildSelectXMLOutputStr->setGeometry(QRect(0, 20, 721, 31));
        textEditChildSelectXMLOrderStr = new QTextEdit(page_10);
        textEditChildSelectXMLOrderStr->setObjectName("textEditChildSelectXMLOrderStr");
        textEditChildSelectXMLOrderStr->setGeometry(QRect(0, 140, 591, 31));
        label_20 = new QLabel(page_10);
        label_20->setObjectName("label_20");
        label_20->setGeometry(QRect(0, 120, 591, 20));
        label_20->setFrameShape(QFrame::Panel);
        label_20->setFrameShadow(QFrame::Sunken);
        label_20->setAlignment(Qt::AlignCenter);
        textEditChildSelectXMLWhereStr = new QTextEdit(page_10);
        textEditChildSelectXMLWhereStr->setObjectName("textEditChildSelectXMLWhereStr");
        textEditChildSelectXMLWhereStr->setGeometry(QRect(0, 80, 721, 31));
        listWidgetChildSelectXMLResultStr = new QListWidget(page_10);
        listWidgetChildSelectXMLResultStr->setObjectName("listWidgetChildSelectXMLResultStr");
        listWidgetChildSelectXMLResultStr->setGeometry(QRect(0, 200, 721, 241));
        toolBox->addItem(page_10, QString::fromUtf8("ChildSelect"));
        page_11 = new QWidget();
        page_11->setObjectName("page_11");
        page_11->setGeometry(QRect(0, 0, 721, 445));
        pushButtonExecuteChildSelectFirstXML = new QPushButton(page_11);
        pushButtonExecuteChildSelectFirstXML->setObjectName("pushButtonExecuteChildSelectFirstXML");
        pushButtonExecuteChildSelectFirstXML->setGeometry(QRect(620, 130, 91, 31));
        label_21 = new QLabel(page_11);
        label_21->setObjectName("label_21");
        label_21->setGeometry(QRect(0, 120, 591, 20));
        label_21->setFrameShape(QFrame::Panel);
        label_21->setFrameShadow(QFrame::Sunken);
        label_21->setAlignment(Qt::AlignCenter);
        textEditChildSelectFirstXMLOrderStr = new QTextEdit(page_11);
        textEditChildSelectFirstXMLOrderStr->setObjectName("textEditChildSelectFirstXMLOrderStr");
        textEditChildSelectFirstXMLOrderStr->setGeometry(QRect(0, 140, 591, 31));
        label_22 = new QLabel(page_11);
        label_22->setObjectName("label_22");
        label_22->setGeometry(QRect(0, 60, 721, 20));
        label_22->setFrameShape(QFrame::Panel);
        label_22->setFrameShadow(QFrame::Sunken);
        label_22->setAlignment(Qt::AlignCenter);
        label_23 = new QLabel(page_11);
        label_23->setObjectName("label_23");
        label_23->setGeometry(QRect(0, 180, 721, 20));
        label_23->setFrameShape(QFrame::Panel);
        label_23->setFrameShadow(QFrame::Sunken);
        label_23->setAlignment(Qt::AlignCenter);
        textEditChildSelectFirstXMLWhereStr = new QTextEdit(page_11);
        textEditChildSelectFirstXMLWhereStr->setObjectName("textEditChildSelectFirstXMLWhereStr");
        textEditChildSelectFirstXMLWhereStr->setGeometry(QRect(0, 80, 721, 31));
        textEditChildSelectFirstXMLOutputStr = new QTextEdit(page_11);
        textEditChildSelectFirstXMLOutputStr->setObjectName("textEditChildSelectFirstXMLOutputStr");
        textEditChildSelectFirstXMLOutputStr->setGeometry(QRect(0, 20, 721, 31));
        label_24 = new QLabel(page_11);
        label_24->setObjectName("label_24");
        label_24->setGeometry(QRect(0, 0, 721, 20));
        label_24->setFrameShape(QFrame::Panel);
        label_24->setFrameShadow(QFrame::Sunken);
        label_24->setAlignment(Qt::AlignCenter);
        textEditChildSelectFirstXMLResultStr = new QTextEdit(page_11);
        textEditChildSelectFirstXMLResultStr->setObjectName("textEditChildSelectFirstXMLResultStr");
        textEditChildSelectFirstXMLResultStr->setGeometry(QRect(0, 200, 721, 81));
        toolBox->addItem(page_11, QString::fromUtf8("ChildSelectFirst"));
        page_15 = new QWidget();
        page_15->setObjectName("page_15");
        page_15->setGeometry(QRect(0, 0, 721, 445));
        textEditChildSelectLastXMLWhereStr = new QTextEdit(page_15);
        textEditChildSelectLastXMLWhereStr->setObjectName("textEditChildSelectLastXMLWhereStr");
        textEditChildSelectLastXMLWhereStr->setGeometry(QRect(0, 80, 721, 31));
        label_33 = new QLabel(page_15);
        label_33->setObjectName("label_33");
        label_33->setGeometry(QRect(0, 180, 721, 20));
        label_33->setFrameShape(QFrame::Panel);
        label_33->setFrameShadow(QFrame::Sunken);
        label_33->setAlignment(Qt::AlignCenter);
        textEditChildSelectLastXMLResultStr = new QTextEdit(page_15);
        textEditChildSelectLastXMLResultStr->setObjectName("textEditChildSelectLastXMLResultStr");
        textEditChildSelectLastXMLResultStr->setGeometry(QRect(0, 200, 721, 81));
        label_34 = new QLabel(page_15);
        label_34->setObjectName("label_34");
        label_34->setGeometry(QRect(0, 0, 721, 20));
        label_34->setFrameShape(QFrame::Panel);
        label_34->setFrameShadow(QFrame::Sunken);
        label_34->setAlignment(Qt::AlignCenter);
        textEditChildSelectLastXMLOutputStr = new QTextEdit(page_15);
        textEditChildSelectLastXMLOutputStr->setObjectName("textEditChildSelectLastXMLOutputStr");
        textEditChildSelectLastXMLOutputStr->setGeometry(QRect(0, 20, 721, 31));
        label_35 = new QLabel(page_15);
        label_35->setObjectName("label_35");
        label_35->setGeometry(QRect(0, 60, 721, 20));
        label_35->setFrameShape(QFrame::Panel);
        label_35->setFrameShadow(QFrame::Sunken);
        label_35->setAlignment(Qt::AlignCenter);
        label_36 = new QLabel(page_15);
        label_36->setObjectName("label_36");
        label_36->setGeometry(QRect(0, 120, 591, 20));
        label_36->setFrameShape(QFrame::Panel);
        label_36->setFrameShadow(QFrame::Sunken);
        label_36->setAlignment(Qt::AlignCenter);
        pushButtonExecuteChildSelectFirstXML_2 = new QPushButton(page_15);
        pushButtonExecuteChildSelectFirstXML_2->setObjectName("pushButtonExecuteChildSelectFirstXML_2");
        pushButtonExecuteChildSelectFirstXML_2->setGeometry(QRect(620, 130, 91, 31));
        textEditChildSelectLastXMLOrderStr = new QTextEdit(page_15);
        textEditChildSelectLastXMLOrderStr->setObjectName("textEditChildSelectLastXMLOrderStr");
        textEditChildSelectLastXMLOrderStr->setGeometry(QRect(0, 140, 591, 31));
        toolBox->addItem(page_15, QString::fromUtf8("ChildSelectLast"));
        page_12 = new QWidget();
        page_12->setObjectName("page_12");
        page_12->setGeometry(QRect(0, 0, 721, 445));
        pushButtonExecuteChildSelectNextXML = new QPushButton(page_12);
        pushButtonExecuteChildSelectNextXML->setObjectName("pushButtonExecuteChildSelectNextXML");
        pushButtonExecuteChildSelectNextXML->setGeometry(QRect(320, 0, 91, 31));
        label_26 = new QLabel(page_12);
        label_26->setObjectName("label_26");
        label_26->setGeometry(QRect(0, 40, 721, 20));
        label_26->setFrameShape(QFrame::Panel);
        label_26->setFrameShadow(QFrame::Sunken);
        label_26->setAlignment(Qt::AlignCenter);
        textEditChildSelectNextXMLResultStr = new QTextEdit(page_12);
        textEditChildSelectNextXMLResultStr->setObjectName("textEditChildSelectNextXMLResultStr");
        textEditChildSelectNextXMLResultStr->setGeometry(QRect(0, 60, 721, 221));
        toolBox->addItem(page_12, QString::fromUtf8("ChildSelectNext"));
        page_16 = new QWidget();
        page_16->setObjectName("page_16");
        page_16->setGeometry(QRect(0, 0, 721, 445));
        textEditChildSelectPrevXMLResultStr = new QTextEdit(page_16);
        textEditChildSelectPrevXMLResultStr->setObjectName("textEditChildSelectPrevXMLResultStr");
        textEditChildSelectPrevXMLResultStr->setGeometry(QRect(0, 60, 721, 221));
        label_37 = new QLabel(page_16);
        label_37->setObjectName("label_37");
        label_37->setGeometry(QRect(0, 40, 721, 20));
        label_37->setFrameShape(QFrame::Panel);
        label_37->setFrameShadow(QFrame::Sunken);
        label_37->setAlignment(Qt::AlignCenter);
        pushButtonExecuteChildSelectPrevXML = new QPushButton(page_16);
        pushButtonExecuteChildSelectPrevXML->setObjectName("pushButtonExecuteChildSelectPrevXML");
        pushButtonExecuteChildSelectPrevXML->setGeometry(QRect(320, 0, 91, 31));
        toolBox->addItem(page_16, QString::fromUtf8("ChildSelectPrev"));
        page_2 = new QWidget();
        page_2->setObjectName("page_2");
        page_2->setGeometry(QRect(0, 0, 721, 445));
        pushButtonCopyPointer = new QPushButton(page_2);
        pushButtonCopyPointer->setObjectName("pushButtonCopyPointer");
        pushButtonCopyPointer->setGeometry(QRect(250, 10, 191, 51));
        toolBox->addItem(page_2, QString::fromUtf8("CopyPointerFromChild"));
        checkBoxResult = new QCheckBox(centralWidget);
        checkBoxResult->setObjectName("checkBoxResult");
        checkBoxResult->setGeometry(QRect(570, 900, 171, 17));
        pushButtonSetting = new QPushButton(centralWidget);
        pushButtonSetting->setObjectName("pushButtonSetting");
        pushButtonSetting->setGeometry(QRect(980, 900, 75, 23));
        XMLExplorerClass->setCentralWidget(centralWidget);

        retranslateUi(XMLExplorerClass);
        QObject::connect(pushButtonConnect, SIGNAL(clicked()), XMLExplorerClass, SLOT(SlotConnect()));
        QObject::connect(pushButtonExecuteInsertXML, SIGNAL(clicked()), XMLExplorerClass, SLOT(SlotInsertXML()));
        QObject::connect(pushButtonOpenXMLOperation, SIGNAL(clicked()), XMLExplorerClass, SLOT(SlotOpenXMLOperation()));
        QObject::connect(pushButtonDup, SIGNAL(clicked()), XMLExplorerClass, SLOT(SlotDup()));
        QObject::connect(pushButtonClose, SIGNAL(clicked()), XMLExplorerClass, SLOT(slotCloseOperation()));
        QObject::connect(pushButtonExecuteUpdateXML, SIGNAL(clicked()), XMLExplorerClass, SLOT(slotUpdateXML()));
        QObject::connect(pushButtonExecuteDeleteXML, SIGNAL(clicked()), XMLExplorerClass, SLOT(slotDeleteXML()));
        QObject::connect(pushButtonExecuteInsUpdateAttrXML, SIGNAL(clicked()), XMLExplorerClass, SLOT(slotInsUpdateAttr()));
        QObject::connect(pushButtonExecuteDeleteAttrXML, SIGNAL(clicked()), XMLExplorerClass, SLOT(slotDeleteAttr()));
        QObject::connect(pushButtonExecuteSelectXML, SIGNAL(clicked()), XMLExplorerClass, SLOT(slotSelect()));
        QObject::connect(pushButtonExecuteSelectFirstXML, SIGNAL(clicked()), XMLExplorerClass, SLOT(slotSelectFirst()));
        QObject::connect(pushButtonExecuteSelectNextXML, SIGNAL(clicked()), XMLExplorerClass, SLOT(slotSelectNext()));
        QObject::connect(pushButtonExecuteChildSelectXML, SIGNAL(clicked()), XMLExplorerClass, SLOT(slotChildSelect()));
        QObject::connect(pushButtonExecuteChildSelectFirstXML, SIGNAL(clicked()), XMLExplorerClass, SLOT(slotChildSelectFirst()));
        QObject::connect(pushButtonExecuteChildSelectNextXML, SIGNAL(clicked()), XMLExplorerClass, SLOT(slotChildSelectNext()));
        QObject::connect(pushButtonExecuteSelectLastXML, SIGNAL(clicked()), XMLExplorerClass, SLOT(slotSelectLast()));
        QObject::connect(pushButtonExecuteSelectPrevXML, SIGNAL(clicked()), XMLExplorerClass, SLOT(slotSelectPrev()));
        QObject::connect(pushButtonExecuteChildSelectFirstXML_2, SIGNAL(clicked()), XMLExplorerClass, SLOT(slotChildSelectLast()));
        QObject::connect(pushButtonExecuteChildSelectPrevXML, SIGNAL(clicked()), XMLExplorerClass, SLOT(slotChildSelectPrev()));
        QObject::connect(pushButtonEnumTable, SIGNAL(clicked()), XMLExplorerClass, SLOT(slotEnumTable()));

        toolBox->setCurrentIndex(2);


        QMetaObject::connectSlotsByName(XMLExplorerClass);
    } // setupUi

    void retranslateUi(QMainWindow *XMLExplorerClass)
    {
        XMLExplorerClass->setWindowTitle(QCoreApplication::translate("XMLExplorerClass", "XMLExplorer", nullptr));
        label->setText(QCoreApplication::translate("XMLExplorerClass", "IPAddress", nullptr));
        pushButtonConnect->setText(QCoreApplication::translate("XMLExplorerClass", "Connect", nullptr));
        label_2->setText(QCoreApplication::translate("XMLExplorerClass", "Port Number", nullptr));
        lineEditIPAddress->setText(QCoreApplication::translate("XMLExplorerClass", "localhost", nullptr));
        label_3->setText(QCoreApplication::translate("XMLExplorerClass", "OperationHandle", nullptr));
        pushButtonOpenXMLOperation->setText(QCoreApplication::translate("XMLExplorerClass", "Open OperationHandle", nullptr));
        pushButtonClose->setText(QCoreApplication::translate("XMLExplorerClass", "Close OperationHandle", nullptr));
        pushButtonDup->setText(QCoreApplication::translate("XMLExplorerClass", "Dup OperationHandle", nullptr));
        label_5->setText(QCoreApplication::translate("XMLExplorerClass", "Inserted Table name", nullptr));
        label_38->setText(QCoreApplication::translate("XMLExplorerClass", "Table List", nullptr));
        pushButtonEnumTable->setText(QCoreApplication::translate("XMLExplorerClass", "Enum Table", nullptr));
        label_39->setText(QCoreApplication::translate("XMLExplorerClass", "Folder Filter", nullptr));
        lineEditEnumTableFilter->setText(QCoreApplication::translate("XMLExplorerClass", "*", nullptr));
        pushButtonBackup->setText(QCoreApplication::translate("XMLExplorerClass", "Backup", nullptr));
        pushButtonRestore->setText(QCoreApplication::translate("XMLExplorerClass", "Restore", nullptr));
        pushButtonRemove->setText(QCoreApplication::translate("XMLExplorerClass", "Remove", nullptr));
        label_4->setText(QCoreApplication::translate("XMLExplorerClass", "Inserted String", nullptr));
        pushButtonExecuteInsertXML->setText(QCoreApplication::translate("XMLExplorerClass", "Execute", nullptr));
        label_27->setText(QCoreApplication::translate("XMLExplorerClass", "Search(Where) String", nullptr));
        toolBox->setItemText(toolBox->indexOf(page), QCoreApplication::translate("XMLExplorerClass", "InsertXML", nullptr));
        pushButtonExecuteUpdateXML->setText(QCoreApplication::translate("XMLExplorerClass", "Execute", nullptr));
        label_6->setText(QCoreApplication::translate("XMLExplorerClass", "Updated String", nullptr));
        toolBox->setItemText(toolBox->indexOf(page_3), QCoreApplication::translate("XMLExplorerClass", "UpdateXML", nullptr));
        pushButtonExecuteDeleteXML->setText(QCoreApplication::translate("XMLExplorerClass", "Execute deletion of Current Point", nullptr));
        label_40->setText(QCoreApplication::translate("XMLExplorerClass", "Search(Where) String", nullptr));
        pushButtonExecuteDeleteMultiXML->setText(QCoreApplication::translate("XMLExplorerClass", "Execute deletion of all selected XMLs", nullptr));
        toolBox->setItemText(toolBox->indexOf(page_4), QCoreApplication::translate("XMLExplorerClass", "DeleteXML", nullptr));
        pushButtonExecuteInsUpdateAttrXML->setText(QCoreApplication::translate("XMLExplorerClass", "Execute", nullptr));
        label_7->setText(QCoreApplication::translate("XMLExplorerClass", "Inserted Attr String", nullptr));
        toolBox->setItemText(toolBox->indexOf(page_5), QCoreApplication::translate("XMLExplorerClass", "InsUpdateAttr", nullptr));
        pushButtonExecuteDeleteAttrXML->setText(QCoreApplication::translate("XMLExplorerClass", "Execute", nullptr));
        label_8->setText(QCoreApplication::translate("XMLExplorerClass", "Deleted attr String", nullptr));
        toolBox->setItemText(toolBox->indexOf(page_6), QCoreApplication::translate("XMLExplorerClass", "DeleteAttr", nullptr));
        pushButtonExecuteSelectXML->setText(QCoreApplication::translate("XMLExplorerClass", "Execute", nullptr));
        label_9->setText(QCoreApplication::translate("XMLExplorerClass", "Output format String", nullptr));
        label_10->setText(QCoreApplication::translate("XMLExplorerClass", "Search(Where) String", nullptr));
        label_11->setText(QCoreApplication::translate("XMLExplorerClass", "Order String", nullptr));
        label_12->setText(QCoreApplication::translate("XMLExplorerClass", "Result list", nullptr));
        toolBox->setItemText(toolBox->indexOf(page_7), QCoreApplication::translate("XMLExplorerClass", "Select", nullptr));
        label_13->setText(QCoreApplication::translate("XMLExplorerClass", "Search(Where) String", nullptr));
        label_14->setText(QCoreApplication::translate("XMLExplorerClass", "Result list", nullptr));
        pushButtonExecuteSelectFirstXML->setText(QCoreApplication::translate("XMLExplorerClass", "Execute", nullptr));
        label_15->setText(QCoreApplication::translate("XMLExplorerClass", "Output format String", nullptr));
        label_16->setText(QCoreApplication::translate("XMLExplorerClass", "Order String", nullptr));
        toolBox->setItemText(toolBox->indexOf(page_8), QCoreApplication::translate("XMLExplorerClass", "SelectFirst", nullptr));
        pushButtonExecuteSelectLastXML->setText(QCoreApplication::translate("XMLExplorerClass", "Execute", nullptr));
        label_28->setText(QCoreApplication::translate("XMLExplorerClass", "Output format String", nullptr));
        label_29->setText(QCoreApplication::translate("XMLExplorerClass", "Result list", nullptr));
        label_30->setText(QCoreApplication::translate("XMLExplorerClass", "Search(Where) String", nullptr));
        label_31->setText(QCoreApplication::translate("XMLExplorerClass", "Order String", nullptr));
        toolBox->setItemText(toolBox->indexOf(page_13), QCoreApplication::translate("XMLExplorerClass", "SelectLast", nullptr));
        pushButtonExecuteSelectNextXML->setText(QCoreApplication::translate("XMLExplorerClass", "Execute", nullptr));
        label_25->setText(QCoreApplication::translate("XMLExplorerClass", "Result list", nullptr));
        toolBox->setItemText(toolBox->indexOf(page_9), QCoreApplication::translate("XMLExplorerClass", "SelectNext", nullptr));
        label_32->setText(QCoreApplication::translate("XMLExplorerClass", "Result list", nullptr));
        pushButtonExecuteSelectPrevXML->setText(QCoreApplication::translate("XMLExplorerClass", "Execute", nullptr));
        toolBox->setItemText(toolBox->indexOf(page_14), QCoreApplication::translate("XMLExplorerClass", "SelectPrev", nullptr));
        label_17->setText(QCoreApplication::translate("XMLExplorerClass", "Search(Where) String", nullptr));
        label_18->setText(QCoreApplication::translate("XMLExplorerClass", "Result list", nullptr));
        pushButtonExecuteChildSelectXML->setText(QCoreApplication::translate("XMLExplorerClass", "Execute", nullptr));
        label_19->setText(QCoreApplication::translate("XMLExplorerClass", "Output format String", nullptr));
        label_20->setText(QCoreApplication::translate("XMLExplorerClass", "Order String", nullptr));
        toolBox->setItemText(toolBox->indexOf(page_10), QCoreApplication::translate("XMLExplorerClass", "ChildSelect", nullptr));
        pushButtonExecuteChildSelectFirstXML->setText(QCoreApplication::translate("XMLExplorerClass", "Execute", nullptr));
        label_21->setText(QCoreApplication::translate("XMLExplorerClass", "Order String", nullptr));
        label_22->setText(QCoreApplication::translate("XMLExplorerClass", "Search(Where) String", nullptr));
        label_23->setText(QCoreApplication::translate("XMLExplorerClass", "Result list", nullptr));
        label_24->setText(QCoreApplication::translate("XMLExplorerClass", "Output format String", nullptr));
        toolBox->setItemText(toolBox->indexOf(page_11), QCoreApplication::translate("XMLExplorerClass", "ChildSelectFirst", nullptr));
        label_33->setText(QCoreApplication::translate("XMLExplorerClass", "Result list", nullptr));
        label_34->setText(QCoreApplication::translate("XMLExplorerClass", "Output format String", nullptr));
        label_35->setText(QCoreApplication::translate("XMLExplorerClass", "Search(Where) String", nullptr));
        label_36->setText(QCoreApplication::translate("XMLExplorerClass", "Order String", nullptr));
        pushButtonExecuteChildSelectFirstXML_2->setText(QCoreApplication::translate("XMLExplorerClass", "Execute", nullptr));
        toolBox->setItemText(toolBox->indexOf(page_15), QCoreApplication::translate("XMLExplorerClass", "ChildSelectLast", nullptr));
        pushButtonExecuteChildSelectNextXML->setText(QCoreApplication::translate("XMLExplorerClass", "Execute", nullptr));
        label_26->setText(QCoreApplication::translate("XMLExplorerClass", "Result list", nullptr));
        toolBox->setItemText(toolBox->indexOf(page_12), QCoreApplication::translate("XMLExplorerClass", "ChildSelectNext", nullptr));
        label_37->setText(QCoreApplication::translate("XMLExplorerClass", "Result list", nullptr));
        pushButtonExecuteChildSelectPrevXML->setText(QCoreApplication::translate("XMLExplorerClass", "Execute", nullptr));
        toolBox->setItemText(toolBox->indexOf(page_16), QCoreApplication::translate("XMLExplorerClass", "ChildSelectPrev", nullptr));
        pushButtonCopyPointer->setText(QCoreApplication::translate("XMLExplorerClass", "CopyPointer", nullptr));
        toolBox->setItemText(toolBox->indexOf(page_2), QCoreApplication::translate("XMLExplorerClass", "CopyPointerFromChild", nullptr));
        checkBoxResult->setText(QCoreApplication::translate("XMLExplorerClass", "Checked in returning true ", nullptr));
        pushButtonSetting->setText(QCoreApplication::translate("XMLExplorerClass", "Setting", nullptr));
    } // retranslateUi

};

namespace Ui {
    class XMLExplorerClass: public Ui_XMLExplorerClass {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_XMLEXPLORER_H
