#ifndef EDITPASSWORDONCONTROL_GLOBAL_H
#define EDITPASSWORDONCONTROL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef EDITPASSWORDONCONTROL_LIB
# define EDITPASSWORDONCONTROL_EXPORT Q_DECL_EXPORT
#else
# define EDITPASSWORDONCONTROL_EXPORT Q_DECL_IMPORT
#endif

#endif // EDITPASSWORDONCONTROL_GLOBAL_H
