# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = EasyPropertyMeasure
DESTDIR = ../IntegratePlayer/x64/Release
CONFIG += release
DEFINES += EASYPROPERTYMEASURE_LIB
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles
include(EasyPropertyMeasure.pri)
