#ifndef SHOWTHINMETALRESULTLIST_GLOBAL_H
#define SHOWTHINMETALRESULTLIST_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SHOWTHINMETALRESULTLIST_LIB
# define SHOWTHINMETALRESULTLIST_EXPORT Q_DECL_EXPORT
#else
# define SHOWTHINMETALRESULTLIST_EXPORT Q_DECL_IMPORT
#endif

#endif // SHOWTHINMETALRESULTLIST_GLOBAL_H
