#ifndef BUTTONCHANGEEXPOSURETIME_GLOBAL_H
#define BUTTONCHANGEEXPOSURETIME_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONCHANGEEXPOSURETIME_LIB
# define BUTTONCHANGEEXPOSURETIME_EXPORT Q_DECL_EXPORT
#else
# define BUTTONCHANGEEXPOSURETIME_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONCHANGEEXPOSURETIME_GLOBAL_H
