#ifndef INTEGRATIONCLOSE_GLOBAL_H
#define INTEGRATIONCLOSE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef INTEGRATIONCLOSE_LIB
# define INTEGRATIONCLOSE_EXPORT Q_DECL_EXPORT
#else
# define INTEGRATIONCLOSE_EXPORT Q_DECL_IMPORT
#endif

#endif // INTEGRATIONCLOSE_GLOBAL_H
