#ifndef SHOWMATCHSHIFTROTATION_GLOBAL_H
#define SHOWMATCHSHIFTROTATION_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SHOWMATCHSHIFTROTATION_LIB
# define SHOWMATCHSHIFTROTATION_EXPORT Q_DECL_EXPORT
#else
# define SHOWMATCHSHIFTROTATION_EXPORT Q_DECL_IMPORT
#endif

#endif // SHOWMATCHSHIFTROTATION_GLOBAL_H
