#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(INTEGRATIONBUTTONCOPYALGORITHM_LIB)
#  define INTEGRATIONBUTTONCOPYALGORITHM_EXPORT Q_DECL_EXPORT
# else
#  define INTEGRATIONBUTTONCOPYALGORITHM_EXPORT Q_DECL_IMPORT
# endif
#else
# define INTEGRATIONBUTTONCOPYALGORITHM_EXPORT
#endif
