#ifndef BUTTONCLEARSTOCKEDRESULT_GLOBAL_H
#define BUTTONCLEARSTOCKEDRESULT_GLOBAL_H

#include <qglobal.h>

#ifdef BUTTONCLEARSTOCKEDRESULT_LIB
# define BUTTONCLEARSTOCKEDRESULT_EXPORT Q_DECL_EXPORT
#else
# define BUTTONCLEARSTOCKEDRESULT_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONCLEARSTOCKEDRESULT_GLOBAL_H
