#ifndef CCSCONTROLBYLAN_GLOBAL_H
#define CCSCONTROLBYLAN_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef CCSCONTROLBYLAN_LIB
# define CCSCONTROLBYLAN_EXPORT Q_DECL_EXPORT
#else
# define CCSCONTROLBYLAN_EXPORT Q_DECL_IMPORT
#endif

#endif // CCSCONTROLBYLAN_GLOBAL_H
