#ifndef EASYPROPERTYDENTMEASURE_GLOBAL_H
#define EASYPROPERTYDENTMEASURE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef EASYPROPERTYDENTMEASURE_LIB
# define EASYPROPERTYDENTMEASURE_EXPORT Q_DECL_EXPORT
#else
# define EASYPROPERTYDENTMEASURE_EXPORT Q_DECL_IMPORT
#endif

#endif // EASYPROPERTYDENTMEASURE_GLOBAL_H
