# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = CheckBoard
DESTDIR = ../../
CONFIG += release
DEFINES += QT_LARGEFILE_SUPPORT
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += .
RCC_DIR += .
include(CheckBoard.pri)

FORMS += \
    ShowRebootForm.ui

HEADERS += \
    ShowRebootForm.h

SOURCES += \
    ShowRebootForm.cpp
