#ifndef BUTTONCOPYIMAGE_GLOBAL_H
#define BUTTONCOPYIMAGE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONCOPYIMAGE_LIB
# define BUTTONCOPYIMAGE_EXPORT Q_DECL_EXPORT
#else
# define BUTTONCOPYIMAGE_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONCOPYIMAGE_GLOBAL_H
