#ifndef FILTERMEDIANSMOOTH_GLOBAL_H
#define FILTERMEDIANSMOOTH_GLOBAL_H

#include <qglobal.h>

#ifdef FILTERMEDIANSMOOTH_LIB
# define FILTERMEDIANSMOOTH_EXPORT Q_DECL_EXPORT
#else
# define FILTERMEDIANSMOOTH_EXPORT Q_DECL_IMPORT
#endif

#endif // FILTERMEDIANSMOOTH_GLOBAL_H
