#ifndef CHECKPROGRAMRUNINVISIBLE_GLOBAL_H
#define CHECKPROGRAMRUNINVISIBLE_GLOBAL_H

#include <qglobal.h>

#ifdef CHECKPROGRAMRUNINVISIBLE_LIB
# define CHECKPROGRAMRUNINVISIBLE_EXPORT Q_DECL_EXPORT
#else
# define CHECKPROGRAMRUNINVISIBLE_EXPORT Q_DECL_IMPORT
#endif

#endif // CHECKPROGRAMRUNINVISIBLE_GLOBAL_H
