#ifndef EASYPROPERTYMASKING_GLOBAL_H
#define EASYPROPERTYMASKING_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef EASYPROPERTYMASKING_LIB
# define EASYPROPERTYMASKING_EXPORT Q_DECL_EXPORT
#else
# define EASYPROPERTYMASKING_EXPORT Q_DECL_IMPORT
#endif

#endif // EASYPROPERTYMASKING_GLOBAL_H
