#ifndef FILTERREMOVENOISELINE_GLOBAL_H
#define FILTERREMOVENOISELINE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef FILTERREMOVENOISELINE_LIB
# define FILTERREMOVENOISELINE_EXPORT Q_DECL_EXPORT
#else
# define FILTERREMOVENOISELINE_EXPORT Q_DECL_IMPORT
#endif

#endif // FILTERREMOVENOISELINE_GLOBAL_H
