#ifndef STEPLINEENHANCERLIMAGEPANEL_GLOBAL_H
#define STEPLINEENHANCERLIMAGEPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef STEPLINEENHANCERLIMAGEPANEL_LIB
# define STEPLINEENHANCERLIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define STEPLINEENHANCERLIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // STEPLINEENHANCERLIMAGEPANEL_GLOBAL_H
