#ifndef STARTSCANNINGAGAIN_GLOBAL_H
#define STARTSCANNINGAGAIN_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef STARTSCANNINGAGAIN_LIB
# define STARTSCANNINGAGAIN_EXPORT Q_DECL_EXPORT
#else
# define STARTSCANNINGAGAIN_EXPORT Q_DECL_IMPORT
#endif

#endif // STARTSCANNINGAGAIN_GLOBAL_H
