#ifndef SHOWCYCLETIME_GLOBAL_H
#define SHOWCYCLETIME_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SHOWCYCLETIME_LIB
# define SHOWCYCLETIME_EXPORT Q_DECL_EXPORT
#else
# define SHOWCYCLETIME_EXPORT Q_DECL_IMPORT
#endif

#endif // SHOWCYCLETIME_GLOBAL_H
