#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(BUTTONREPLACEIMAGECONTROL_LIB)
#  define BUTTONREPLACEIMAGECONTROL_EXPORT Q_DECL_EXPORT
# else
#  define BUTTONREPLACEIMAGECONTROL_EXPORT Q_DECL_IMPORT
# endif
#else
# define BUTTONREPLACEIMAGECONTROL_EXPORT
#endif
