#ifndef BUTTONCOPYANYPHASEPAGELAYER_GLOBAL_H
#define BUTTONCOPYANYPHASEPAGELAYER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONCOPYANYPHASEPAGELAYER_LIB
# define BUTTONCOPYANYPHASEPAGELAYER_EXPORT Q_DECL_EXPORT
#else
# define BUTTONCOPYANYPHASEPAGELAYER_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONCOPYANYPHASEPAGELAYER_GLOBAL_H
