#ifndef PROPERTYPIECEFORREVIEW_GLOBAL_H
#define PROPERTYPIECEFORREVIEW_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PROPERTYPIECEFORREVIEW_LIB
# define PROPERTYPIECEFORREVIEW_EXPORT Q_DECL_EXPORT
#else
# define PROPERTYPIECEFORREVIEW_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTYPIECEFORREVIEW_GLOBAL_H
