#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(BUTTONCOPYSHADOWTREEALGORITHM_LIB)
#  define BUTTONCOPYSHADOWTREEALGORITHM_EXPORT Q_DECL_EXPORT
# else
#  define BUTTONCOPYSHADOWTREEALGORITHM_EXPORT Q_DECL_IMPORT
# endif
#else
# define BUTTONCOPYSHADOWTREEALGORITHM_EXPORT
#endif
