# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = NetworkPIOLib
DESTDIR = ../../../Lib/Release
CONFIG += staticlib debug
DEFINES += QT_LARGEFILE_SUPPORT NETWORKPIOLIB_LIB
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles
include(NetworkPIOLib.pri)
