#ifndef BUTTONTOSHOWREVIEWSETTING_GLOBAL_H
#define BUTTONTOSHOWREVIEWSETTING_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONTOSHOWREVIEWSETTING_LIB
# define BUTTONTOSHOWREVIEWSETTING_EXPORT Q_DECL_EXPORT
#else
# define BUTTONTOSHOWREVIEWSETTING_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONTOSHOWTOTALNGMAP_GLOBAL_H
