#ifndef DFSLIBRARY_GLOBAL_H
#define DFSLIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef DFSLIBRARY_LIB
# define DFSLIBRARY_EXPORT Q_DECL_EXPORT
#else
# define DFSLIBRARY_EXPORT Q_DECL_IMPORT
#endif

#endif // DFSLIBRARY_GLOBAL_H
