#ifndef SAVEPARTIALIMAGE_GLOBAL_H
#define SAVEPARTIALIMAGE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SAVEPARTIALIMAGE_LIB
# define SAVEPARTIALIMAGE_EXPORT Q_DECL_EXPORT
#else
# define SAVEPARTIALIMAGE_EXPORT Q_DECL_IMPORT
#endif

#endif // SAVEPARTIALIMAGE_GLOBAL_H
