#ifndef BUTTONFORMARKINGON_GLOBAL_H
#define BUTTONFORMARKINGON_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONFORMARKINGON_LIB
# define BUTTONFORMARKINGON_EXPORT Q_DECL_EXPORT
#else
# define BUTTONFORMARKINGON_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONFORMARKINGON_GLOBAL_H
