#ifndef BUTTONPASSWORDOPENER_GLOBAL_H
#define BUTTONPASSWORDOPENER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONPASSWORDOPENER_LIB
# define BUTTONPASSWORDOPENER_EXPORT Q_DECL_EXPORT
#else
# define BUTTONPASSWORDOPENER_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONPASSWORDOPENER_GLOBAL_H
