#ifndef BUTTONLOADRELEASE_GLOBAL_H
#define BUTTONLOADRELEASE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONLOADRELEASE_LIB
# define BUTTONLOADRELEASE_EXPORT Q_DECL_EXPORT
#else
# define BUTTONLOADRELEASE_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONLOADRELEASE_GLOBAL_H
