#ifndef MATCHINGALIGNMENT_GLOBAL_H
#define MATCHINGALIGNMENT_GLOBAL_H

#include <qglobal.h>

#ifdef MATCHINGALIGNMENT_LIB
# define MATCHINGALIGNMENT_EXPORT Q_DECL_EXPORT
#else
# define MATCHINGALIGNMENT_EXPORT Q_DECL_IMPORT
#endif

#endif // MATCHINGALIGNMENT_GLOBAL_H
