#ifndef PROPERTYDOTCOLORMATCHING_GLOBAL_H
#define PROPERTYDOTCOLORMATCHING_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PROPERTYDOTCOLORMATCHING_LIB
# define PROPERTYDOTCOLORMATCHING_EXPORT Q_DECL_EXPORT
#else
# define PROPERTYDOTCOLORMATCHING_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTYDOTCOLORMATCHING_GLOBAL_H
