# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../Open/XDisplaySimPanel.h \
    ./PropertyDotColorMatchingResource.h \
    ./XPropertyDotColorMatchingPacket.h \
    ./PropertyDotColorMatching.h \
    ./propertydotcolormatching_global.h \
    ./CreateManualDotColorMatchingDialog.h \
    ./EditDotColorMatchingLibraryDialog.h \
    ./PropertyDotColorMatchingForm.h
SOURCES += ../../GeneralSource/XDisplaySimPanel.cpp \
    ../../Open/GUIDllCommon.cpp \
    ../../Open/SystemVersion.cpp \
    ./CreateManualDotColorMatchingDialog.cpp \
    ./EditDotColorMatchingLibraryDialog.cpp \
    ./PropertyDotColorMatching.cpp \
    ./PropertyDotColorMatchingForm.cpp \
    ./PropertyDotColorMatchingResource.cpp \
    ./XPropertyDotColorMatchingPacket.cpp
FORMS += ./CreateManualDotColorMatchingDialog.ui \
    ./EditDotColorMatchingLibraryDialog.ui \
    ./PropertyDotColorMatchingForm.ui
