#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(INTEGRATIONCREATETHRESHOLD_LIB)
#  define INTEGRATIONCREATETHRESHOLD_EXPORT Q_DECL_EXPORT
# else
#  define INTEGRATIONCREATETHRESHOLD_EXPORT Q_DECL_IMPORT
# endif
#else
# define INTEGRATIONCREATETHRESHOLD_EXPORT
#endif
