#ifndef DXFOPERATIONIMAGEPANEL_GLOBAL_H
#define DXFOPERATIONIMAGEPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef DXFOPERATIONIMAGEPANEL_LIB
# define DXFOPERATIONIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define DXFOPERATIONIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // DXFOPERATIONIMAGEPANEL_GLOBAL_H
