#ifndef BUSLINEIMAGEPANEL_GLOBAL_H
#define BUSLINEIMAGEPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUSLINEIMAGEPANEL_LIB
# define BUSLINEIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define BUSLINEIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // BUSLINEIMAGEPANEL_GLOBAL_H
