#ifndef FILTERUPSIDEDOWN_GLOBAL_H
#define FILTERUPSIDEDOWN_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef FILTERUPSIDEDOWN_LIB
# define FILTERUPSIDEDOWN_EXPORT Q_DECL_EXPORT
#else
# define FILTERUPSIDEDOWN_EXPORT Q_DECL_IMPORT
#endif

#endif // FILTERUPSIDEDOWN_GLOBAL_H
