#ifndef STEPLINEENHANCERL_GLOBAL_H
#define STEPLINEENHANCERL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef STEPLINEENHANCERL_LIB
# define STEPLINEENHANCERL_EXPORT Q_DECL_EXPORT
#else
# define STEPLINEENHANCERL_EXPORT Q_DECL_IMPORT
#endif

#endif // STEPLINEENHANCERL_GLOBAL_H
