#ifndef SHOWTHUMBNAIL_GLOBAL_H
#define SHOWTHUMBNAIL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SHOWTHUMBNAIL_LIB
# define SHOWTHUMBNAIL_EXPORT Q_DECL_EXPORT
#else
# define SHOWTHUMBNAIL_EXPORT Q_DECL_IMPORT
#endif

#endif // SHOWTHUMBNAIL_GLOBAL_H
