#ifndef PIECELISTREVIEWSIDE_GLOBAL_H
#define PIECELISTREVIEWSIDE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PIECELISTREVIEWSIDE_LIB
# define PIECELISTREVIEWSIDE_EXPORT Q_DECL_EXPORT
#else
# define PIECELISTREVIEWSIDE_EXPORT Q_DECL_IMPORT
#endif

#endif // PIECELISTREVIEWSIDE_GLOBAL_H
