#ifndef LISTMASTERDATAANDLOADWITHOUTMACHINE_GLOBAL_H
#define LISTMASTERDATAANDLOADWITHOUTMACHINE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef LISTMASTERDATAANDLOADWITHOUTMACHINE_LIB
# define LISTMASTERDATAANDLOADWITHOUTMACHINE_EXPORT Q_DECL_EXPORT
#else
# define LISTMASTERDATAANDLOADWITHOUTMACHINE_EXPORT Q_DECL_IMPORT
#endif

#endif // LISTMASTERDATAANDLOADWITHOUTMACHINE_GLOBAL_H
