#ifndef PROGRESSONIDLE_GLOBAL_H
#define PROGRESSONIDLE_GLOBAL_H

#include <qglobal.h>

#ifdef PROGRESSONIDLE_LIB
# define PROGRESSONIDLE_EXPORT Q_DECL_EXPORT
#else
# define PROGRESSONIDLE_EXPORT Q_DECL_IMPORT
#endif

#endif // PROGRESSONIDLE_GLOBAL_H
