#ifndef LISTBOXPROCESSTIME_GLOBAL_H
#define LISTBOXPROCESSTIME_GLOBAL_H

#include <qglobal.h>

#ifdef LISTBOXPROCESSTIME_LIB
# define LISTBOXPROCESSTIME_EXPORT Q_DECL_EXPORT
#else
# define LISTBOXPROCESSTIME_EXPORT Q_DECL_IMPORT
#endif

#endif // LISTBOXPROCESSTIME_GLOBAL_H
