#ifndef LISTBOXGUITIME_GLOBAL_H
#define LISTBOXGUITIME_GLOBAL_H

#include <qglobal.h>

#ifdef LISTBOXGUITIME_LIB
# define LISTBOXGUITIME_EXPORT Q_DECL_EXPORT
#else
# define LISTBOXGUITIME_EXPORT Q_DECL_IMPORT
#endif

#endif // LISTBOXGUITIME_GLOBAL_H
