#ifndef BUTTONTOSTORESAMPLESTHINMETAL_GLOBAL_H
#define BUTTONTOSTORESAMPLESTHINMETAL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONTOSTORESAMPLESTHINMETAL_LIB
# define BUTTONTOSTORESAMPLESTHINMETAL_EXPORT Q_DECL_EXPORT
#else
# define BUTTONTOSTORESAMPLESTHINMETAL_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONTOSTORESAMPLESTHINMETAL_GLOBAL_H
