/********************************************************************************
** Form generated from reading UI file 'MonoOutlineForm.ui'
**
** Created by: Qt User Interface Compiler version 6.10.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MONOOUTLINEFORM_H
#define UI_MONOOUTLINEFORM_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QDialog>
#include <QtWidgets/QFrame>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QToolButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MonoOutlineFormClass
{
public:
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_4;
    QFrame *frame_27;
    QLabel *label_90;
    QFrame *frame_28;
    QLabel *label_91;
    QSpinBox *EditSelfSearch;
    QLabel *label_92;
    QFrame *frame_29;
    QLabel *label_93;
    QFrame *frame_30;
    QLabel *label_94;
    QSpinBox *EditAdjustLimitLInside;
    QLabel *label_95;
    QSpinBox *EditAdjustLimitHInside;
    QLabel *label_96;
    QCheckBox *checkBoxAdjustMode;
    QSpinBox *EditAdjustLimitHOutside;
    QSpinBox *EditAdjustLimitLOutside;
    QLabel *label_97;
    QLabel *label_98;
    QFrame *frame_5;
    QLabel *label_31;
    QLabel *labelResultOutsideN;
    QLabel *labelResultInsideB;
    QPushButton *ButtonCalc;
    QLabel *labelResultOutsideB;
    QLabel *labelResultInsideN;
    QLabel *label_15;
    QLabel *label_16;
    QLabel *label_17;
    QLabel *label_18;
    QPushButton *ButtonReflectAllBlocks;
    QStackedWidget *stackedWidgetParts;
    QWidget *page;
    QPushButton *ButtonRefrectOnlyBlock;
    QWidget *page_3;
    QPushButton *ButtonRelrectSaveParts;
    QWidget *page_2;
    QPushButton *ButtonLoadFromLibrary;
    QPushButton *ButtonSaveToLibrary;
    QPushButton *pushButtonClose;
    QFrame *frame;
    QCheckBox *checkBoxEffectiveBInside;
    QFrame *frameTrInside;
    QFrame *frameOutside;
    QLabel *label_48;
    QSpinBox *EditBInsideOKDot;
    QSpinBox *EditBOutsideOKDot;
    QCheckBox *checkBoxEffectiveBOutside;
    QFrame *frameTrOutside;
    QFrame *frameInside;
    QLabel *label_50;
    QSpinBox *EditNInsideOKDot;
    QSpinBox *EditNOutsideOKDot;
    QCheckBox *checkBoxEffectiveNInside;
    QCheckBox *checkBoxEffectiveNOutside;
    QLabel *label_49;
    QLabel *label_51;
    QLabel *label_67;
    QSpinBox *EditBOutsideColorL;
    QSpinBox *EditBOutsideColorH;
    QLabel *label_69;
    QSpinBox *EditNOutsideColorH;
    QSpinBox *EditNOutsideColorL;
    QLabel *label_70;
    QLabel *label_68;
    QSpinBox *EditBTrOutsideColorH;
    QSpinBox *EditBTrOutsideColorL;
    QLabel *label_71;
    QLabel *label_72;
    QSpinBox *EditNTrOutsideColorH;
    QSpinBox *EditNTrOutsideColorL;
    QLabel *label_73;
    QLabel *label_74;
    QSpinBox *EditBTrInsideColorH;
    QSpinBox *EditBTrInsideColorL;
    QLabel *label_75;
    QLabel *label_76;
    QSpinBox *EditNTrInsideColorH;
    QSpinBox *EditNTrInsideColorL;
    QLabel *label_77;
    QLabel *label_78;
    QSpinBox *EditBInsideColorH;
    QSpinBox *EditBInsideColorL;
    QLabel *label_79;
    QLabel *label_80;
    QSpinBox *EditNInsideColorH;
    QSpinBox *EditNInsideColorL;
    QLabel *label_81;
    QLabel *label_82;
    QFrame *line;
    QFrame *line_3;
    QFrame *frame_2;
    QToolButton *toolButtonSelectN;
    QToolButton *toolButtonSelectB;
    QSpinBox *EditOutsideCenterColorOnMaster;
    QLabel *label_83;
    QSpinBox *EditOutsideCenterColorOnTarget;
    QLabel *label_84;
    QSpinBox *EditOutsideTrCenterColorOnTarget;
    QSpinBox *EditOutsideTrCenterColorOnMaster;
    QLabel *label_85;
    QSpinBox *EditInsideTrCenterColorOnTarget;
    QSpinBox *EditInsideTrCenterColorOnMaster;
    QLabel *label_86;
    QSpinBox *EditInsideCenterColorOnTarget;
    QSpinBox *EditInsideCenterColorOnMaster;
    QLabel *label_9;
    QLineEdit *EditLibName;
    QLineEdit *EditLibID;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *label_12;
    QFrame *frameMaster;
    QLabel *label_13;
    QFrame *frameThresholdB;
    QFrame *frameTarget;
    QLabel *label_14;
    QFrame *frameThresholdN;
    QFrame *frame_6;
    QLabel *label_32;
    QPushButton *ButtonOptimizeOnly;
    QPushButton *ButtonOptimizeAll;
    QLabel *label_7;
    QLabel *label_8;
    QSpinBox *EditBExtendRate;
    QSpinBox *EditNExtendRate;
    QFrame *frame_31;
    QLabel *label_104;
    QFrame *frame_32;
    QLabel *label_105;
    QCheckBox *checkBoxDiffMode;
    QCheckBox *checkBoxMatchSlideOnMaster;
    QCheckBox *checkBoxAbsMode;

    void setupUi(QDialog *MonoOutlineFormClass)
    {
        if (MonoOutlineFormClass->objectName().isEmpty())
            MonoOutlineFormClass->setObjectName("MonoOutlineFormClass");
        MonoOutlineFormClass->resize(1024, 875);
        label = new QLabel(MonoOutlineFormClass);
        label->setObjectName("label");
        label->setGeometry(QRect(0, 20, 31, 141));
        label->setFrameShape(QFrame::Panel);
        label->setFrameShadow(QFrame::Sunken);
        label->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_2 = new QLabel(MonoOutlineFormClass);
        label_2->setObjectName("label_2");
        label_2->setGeometry(QRect(0, 170, 31, 141));
        label_2->setFrameShape(QFrame::Panel);
        label_2->setFrameShadow(QFrame::Sunken);
        label_2->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_2->setWordWrap(true);
        label_3 = new QLabel(MonoOutlineFormClass);
        label_3->setObjectName("label_3");
        label_3->setGeometry(QRect(0, 320, 31, 141));
        label_3->setFrameShape(QFrame::Panel);
        label_3->setFrameShadow(QFrame::Sunken);
        label_3->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_3->setWordWrap(true);
        label_4 = new QLabel(MonoOutlineFormClass);
        label_4->setObjectName("label_4");
        label_4->setGeometry(QRect(0, 470, 31, 141));
        label_4->setFrameShape(QFrame::Panel);
        label_4->setFrameShadow(QFrame::Sunken);
        label_4->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        frame_27 = new QFrame(MonoOutlineFormClass);
        frame_27->setObjectName("frame_27");
        frame_27->setGeometry(QRect(10, 660, 311, 41));
        frame_27->setFrameShape(QFrame::StyledPanel);
        frame_27->setFrameShadow(QFrame::Sunken);
        label_90 = new QLabel(frame_27);
        label_90->setObjectName("label_90");
        label_90->setGeometry(QRect(0, 0, 20, 41));
        label_90->setFrameShape(QFrame::Panel);
        label_90->setFrameShadow(QFrame::Raised);
        label_90->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_90->setIndent(1);
        frame_28 = new QFrame(frame_27);
        frame_28->setObjectName("frame_28");
        frame_28->setGeometry(QRect(10, 120, 371, 101));
        frame_28->setFrameShape(QFrame::StyledPanel);
        frame_28->setFrameShadow(QFrame::Sunken);
        label_91 = new QLabel(frame_28);
        label_91->setObjectName("label_91");
        label_91->setGeometry(QRect(0, 0, 20, 61));
        label_91->setFrameShape(QFrame::Panel);
        label_91->setFrameShadow(QFrame::Raised);
        label_91->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_91->setIndent(1);
        EditSelfSearch = new QSpinBox(frame_27);
        EditSelfSearch->setObjectName("EditSelfSearch");
        EditSelfSearch->setGeometry(QRect(240, 10, 61, 22));
        label_92 = new QLabel(frame_27);
        label_92->setObjectName("label_92");
        label_92->setGeometry(QRect(30, 10, 201, 21));
        label_92->setFrameShape(QFrame::Panel);
        label_92->setFrameShadow(QFrame::Sunken);
        label_92->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        frame_29 = new QFrame(MonoOutlineFormClass);
        frame_29->setObjectName("frame_29");
        frame_29->setGeometry(QRect(10, 700, 311, 81));
        frame_29->setFrameShape(QFrame::StyledPanel);
        frame_29->setFrameShadow(QFrame::Sunken);
        label_93 = new QLabel(frame_29);
        label_93->setObjectName("label_93");
        label_93->setGeometry(QRect(0, 0, 20, 81));
        label_93->setFrameShape(QFrame::Panel);
        label_93->setFrameShadow(QFrame::Raised);
        label_93->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_93->setIndent(1);
        frame_30 = new QFrame(frame_29);
        frame_30->setObjectName("frame_30");
        frame_30->setGeometry(QRect(10, 120, 371, 101));
        frame_30->setFrameShape(QFrame::StyledPanel);
        frame_30->setFrameShadow(QFrame::Sunken);
        label_94 = new QLabel(frame_30);
        label_94->setObjectName("label_94");
        label_94->setGeometry(QRect(0, 0, 20, 61));
        label_94->setFrameShape(QFrame::Panel);
        label_94->setFrameShadow(QFrame::Raised);
        label_94->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_94->setIndent(1);
        EditAdjustLimitLInside = new QSpinBox(frame_29);
        EditAdjustLimitLInside->setObjectName("EditAdjustLimitLInside");
        EditAdjustLimitLInside->setGeometry(QRect(180, 30, 61, 22));
        label_95 = new QLabel(frame_29);
        label_95->setObjectName("label_95");
        label_95->setGeometry(QRect(30, 30, 151, 21));
        label_95->setFrameShape(QFrame::Panel);
        label_95->setFrameShadow(QFrame::Sunken);
        label_95->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditAdjustLimitHInside = new QSpinBox(frame_29);
        EditAdjustLimitHInside->setObjectName("EditAdjustLimitHInside");
        EditAdjustLimitHInside->setGeometry(QRect(180, 50, 61, 22));
        label_96 = new QLabel(frame_29);
        label_96->setObjectName("label_96");
        label_96->setGeometry(QRect(30, 50, 151, 21));
        label_96->setFrameShape(QFrame::Panel);
        label_96->setFrameShadow(QFrame::Sunken);
        label_96->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        checkBoxAdjustMode = new QCheckBox(frame_29);
        checkBoxAdjustMode->setObjectName("checkBoxAdjustMode");
        checkBoxAdjustMode->setGeometry(QRect(30, 10, 151, 18));
        EditAdjustLimitHOutside = new QSpinBox(frame_29);
        EditAdjustLimitHOutside->setObjectName("EditAdjustLimitHOutside");
        EditAdjustLimitHOutside->setGeometry(QRect(240, 50, 61, 22));
        EditAdjustLimitLOutside = new QSpinBox(frame_29);
        EditAdjustLimitLOutside->setObjectName("EditAdjustLimitLOutside");
        EditAdjustLimitLOutside->setGeometry(QRect(240, 30, 61, 22));
        label_97 = new QLabel(frame_29);
        label_97->setObjectName("label_97");
        label_97->setGeometry(QRect(240, 10, 61, 21));
        label_97->setFrameShape(QFrame::Panel);
        label_97->setFrameShadow(QFrame::Sunken);
        label_97->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_98 = new QLabel(frame_29);
        label_98->setObjectName("label_98");
        label_98->setGeometry(QRect(180, 10, 61, 21));
        label_98->setFrameShape(QFrame::Panel);
        label_98->setFrameShadow(QFrame::Sunken);
        label_98->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        frame_5 = new QFrame(MonoOutlineFormClass);
        frame_5->setObjectName("frame_5");
        frame_5->setGeometry(QRect(330, 650, 151, 171));
        frame_5->setFrameShape(QFrame::StyledPanel);
        frame_5->setFrameShadow(QFrame::Sunken);
        label_31 = new QLabel(frame_5);
        label_31->setObjectName("label_31");
        label_31->setGeometry(QRect(0, 0, 151, 21));
        label_31->setFrameShape(QFrame::Panel);
        label_31->setFrameShadow(QFrame::Sunken);
        label_31->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        labelResultOutsideN = new QLabel(frame_5);
        labelResultOutsideN->setObjectName("labelResultOutsideN");
        labelResultOutsideN->setGeometry(QRect(90, 100, 51, 21));
        labelResultOutsideN->setFrameShape(QFrame::Panel);
        labelResultOutsideN->setFrameShadow(QFrame::Sunken);
        labelResultOutsideN->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        labelResultInsideB = new QLabel(frame_5);
        labelResultInsideB->setObjectName("labelResultInsideB");
        labelResultInsideB->setGeometry(QRect(30, 120, 51, 21));
        labelResultInsideB->setFrameShape(QFrame::Panel);
        labelResultInsideB->setFrameShadow(QFrame::Sunken);
        labelResultInsideB->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        ButtonCalc = new QPushButton(frame_5);
        ButtonCalc->setObjectName("ButtonCalc");
        ButtonCalc->setGeometry(QRect(20, 30, 111, 41));
        labelResultOutsideB = new QLabel(frame_5);
        labelResultOutsideB->setObjectName("labelResultOutsideB");
        labelResultOutsideB->setGeometry(QRect(30, 100, 51, 21));
        labelResultOutsideB->setFrameShape(QFrame::Panel);
        labelResultOutsideB->setFrameShadow(QFrame::Sunken);
        labelResultOutsideB->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        labelResultInsideN = new QLabel(frame_5);
        labelResultInsideN->setObjectName("labelResultInsideN");
        labelResultInsideN->setGeometry(QRect(90, 120, 51, 21));
        labelResultInsideN->setFrameShape(QFrame::Panel);
        labelResultInsideN->setFrameShadow(QFrame::Sunken);
        labelResultInsideN->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_15 = new QLabel(frame_5);
        label_15->setObjectName("label_15");
        label_15->setGeometry(QRect(30, 80, 51, 21));
        label_15->setFrameShape(QFrame::Panel);
        label_15->setFrameShadow(QFrame::Sunken);
        label_15->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_16 = new QLabel(frame_5);
        label_16->setObjectName("label_16");
        label_16->setGeometry(QRect(90, 80, 51, 21));
        label_16->setFrameShape(QFrame::Panel);
        label_16->setFrameShadow(QFrame::Sunken);
        label_16->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_17 = new QLabel(frame_5);
        label_17->setObjectName("label_17");
        label_17->setGeometry(QRect(0, 100, 21, 21));
        label_17->setFrameShape(QFrame::Panel);
        label_17->setFrameShadow(QFrame::Sunken);
        label_17->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_18 = new QLabel(frame_5);
        label_18->setObjectName("label_18");
        label_18->setGeometry(QRect(0, 120, 21, 21));
        label_18->setFrameShape(QFrame::Panel);
        label_18->setFrameShadow(QFrame::Sunken);
        label_18->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        ButtonReflectAllBlocks = new QPushButton(MonoOutlineFormClass);
        ButtonReflectAllBlocks->setObjectName("ButtonReflectAllBlocks");
        ButtonReflectAllBlocks->setGeometry(QRect(840, 720, 171, 31));
        stackedWidgetParts = new QStackedWidget(MonoOutlineFormClass);
        stackedWidgetParts->setObjectName("stackedWidgetParts");
        stackedWidgetParts->setGeometry(QRect(680, 720, 151, 31));
        page = new QWidget();
        page->setObjectName("page");
        ButtonRefrectOnlyBlock = new QPushButton(page);
        ButtonRefrectOnlyBlock->setObjectName("ButtonRefrectOnlyBlock");
        ButtonRefrectOnlyBlock->setGeometry(QRect(0, 0, 151, 31));
        stackedWidgetParts->addWidget(page);
        page_3 = new QWidget();
        page_3->setObjectName("page_3");
        ButtonRelrectSaveParts = new QPushButton(page_3);
        ButtonRelrectSaveParts->setObjectName("ButtonRelrectSaveParts");
        ButtonRelrectSaveParts->setGeometry(QRect(0, 0, 171, 31));
        stackedWidgetParts->addWidget(page_3);
        page_2 = new QWidget();
        page_2->setObjectName("page_2");
        stackedWidgetParts->addWidget(page_2);
        ButtonLoadFromLibrary = new QPushButton(MonoOutlineFormClass);
        ButtonLoadFromLibrary->setObjectName("ButtonLoadFromLibrary");
        ButtonLoadFromLibrary->setGeometry(QRect(840, 750, 171, 31));
        ButtonSaveToLibrary = new QPushButton(MonoOutlineFormClass);
        ButtonSaveToLibrary->setObjectName("ButtonSaveToLibrary");
        ButtonSaveToLibrary->setGeometry(QRect(680, 750, 151, 31));
        pushButtonClose = new QPushButton(MonoOutlineFormClass);
        pushButtonClose->setObjectName("pushButtonClose");
        pushButtonClose->setGeometry(QRect(840, 790, 171, 41));
        frame = new QFrame(MonoOutlineFormClass);
        frame->setObjectName("frame");
        frame->setGeometry(QRect(30, 0, 991, 621));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Sunken);
        checkBoxEffectiveBInside = new QCheckBox(frame);
        checkBoxEffectiveBInside->setObjectName("checkBoxEffectiveBInside");
        checkBoxEffectiveBInside->setGeometry(QRect(700, 340, 76, 18));
        frameTrInside = new QFrame(frame);
        frameTrInside->setObjectName("frameTrInside");
        frameTrInside->setGeometry(QRect(10, 320, 681, 141));
        frameTrInside->setFrameShape(QFrame::NoFrame);
        frameTrInside->setFrameShadow(QFrame::Raised);
        frameOutside = new QFrame(frame);
        frameOutside->setObjectName("frameOutside");
        frameOutside->setGeometry(QRect(10, 20, 681, 141));
        frameOutside->setFrameShape(QFrame::NoFrame);
        frameOutside->setFrameShadow(QFrame::Raised);
        label_48 = new QLabel(frame);
        label_48->setObjectName("label_48");
        label_48->setGeometry(QRect(700, 50, 71, 21));
        label_48->setFrameShape(QFrame::Panel);
        label_48->setFrameShadow(QFrame::Sunken);
        label_48->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditBInsideOKDot = new QSpinBox(frame);
        EditBInsideOKDot->setObjectName("EditBInsideOKDot");
        EditBInsideOKDot->setGeometry(QRect(780, 360, 51, 22));
        EditBInsideOKDot->setMaximum(99999999);
        EditBOutsideOKDot = new QSpinBox(frame);
        EditBOutsideOKDot->setObjectName("EditBOutsideOKDot");
        EditBOutsideOKDot->setGeometry(QRect(780, 50, 51, 22));
        EditBOutsideOKDot->setMaximum(99999999);
        checkBoxEffectiveBOutside = new QCheckBox(frame);
        checkBoxEffectiveBOutside->setObjectName("checkBoxEffectiveBOutside");
        checkBoxEffectiveBOutside->setGeometry(QRect(700, 30, 76, 18));
        frameTrOutside = new QFrame(frame);
        frameTrOutside->setObjectName("frameTrOutside");
        frameTrOutside->setGeometry(QRect(10, 170, 681, 141));
        frameTrOutside->setFrameShape(QFrame::NoFrame);
        frameTrOutside->setFrameShadow(QFrame::Raised);
        frameInside = new QFrame(frame);
        frameInside->setObjectName("frameInside");
        frameInside->setGeometry(QRect(10, 470, 681, 141));
        frameInside->setFrameShape(QFrame::NoFrame);
        frameInside->setFrameShadow(QFrame::Raised);
        label_50 = new QLabel(frame);
        label_50->setObjectName("label_50");
        label_50->setGeometry(QRect(700, 360, 71, 21));
        label_50->setFrameShape(QFrame::Panel);
        label_50->setFrameShadow(QFrame::Sunken);
        label_50->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditNInsideOKDot = new QSpinBox(frame);
        EditNInsideOKDot->setObjectName("EditNInsideOKDot");
        EditNInsideOKDot->setGeometry(QRect(930, 360, 51, 22));
        EditNInsideOKDot->setMaximum(99999999);
        EditNOutsideOKDot = new QSpinBox(frame);
        EditNOutsideOKDot->setObjectName("EditNOutsideOKDot");
        EditNOutsideOKDot->setGeometry(QRect(930, 50, 51, 22));
        EditNOutsideOKDot->setMaximum(99999999);
        checkBoxEffectiveNInside = new QCheckBox(frame);
        checkBoxEffectiveNInside->setObjectName("checkBoxEffectiveNInside");
        checkBoxEffectiveNInside->setGeometry(QRect(850, 340, 76, 18));
        checkBoxEffectiveNOutside = new QCheckBox(frame);
        checkBoxEffectiveNOutside->setObjectName("checkBoxEffectiveNOutside");
        checkBoxEffectiveNOutside->setGeometry(QRect(850, 30, 76, 18));
        label_49 = new QLabel(frame);
        label_49->setObjectName("label_49");
        label_49->setGeometry(QRect(850, 50, 71, 21));
        label_49->setFrameShape(QFrame::Panel);
        label_49->setFrameShadow(QFrame::Sunken);
        label_49->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_51 = new QLabel(frame);
        label_51->setObjectName("label_51");
        label_51->setGeometry(QRect(850, 360, 71, 21));
        label_51->setFrameShape(QFrame::Panel);
        label_51->setFrameShadow(QFrame::Sunken);
        label_51->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_67 = new QLabel(frame);
        label_67->setObjectName("label_67");
        label_67->setGeometry(QRect(770, 90, 61, 21));
        label_67->setFrameShape(QFrame::Panel);
        label_67->setFrameShadow(QFrame::Sunken);
        label_67->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditBOutsideColorL = new QSpinBox(frame);
        EditBOutsideColorL->setObjectName("EditBOutsideColorL");
        EditBOutsideColorL->setGeometry(QRect(700, 110, 61, 22));
        EditBOutsideColorL->setMaximum(1000000);
        EditBOutsideColorH = new QSpinBox(frame);
        EditBOutsideColorH->setObjectName("EditBOutsideColorH");
        EditBOutsideColorH->setGeometry(QRect(770, 110, 61, 22));
        EditBOutsideColorH->setMaximum(1000000);
        label_69 = new QLabel(frame);
        label_69->setObjectName("label_69");
        label_69->setGeometry(QRect(700, 90, 61, 21));
        label_69->setFrameShape(QFrame::Panel);
        label_69->setFrameShadow(QFrame::Sunken);
        label_69->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditNOutsideColorH = new QSpinBox(frame);
        EditNOutsideColorH->setObjectName("EditNOutsideColorH");
        EditNOutsideColorH->setGeometry(QRect(920, 110, 61, 22));
        EditNOutsideColorH->setMaximum(1000000);
        EditNOutsideColorL = new QSpinBox(frame);
        EditNOutsideColorL->setObjectName("EditNOutsideColorL");
        EditNOutsideColorL->setGeometry(QRect(850, 110, 61, 22));
        EditNOutsideColorL->setMaximum(1000000);
        label_70 = new QLabel(frame);
        label_70->setObjectName("label_70");
        label_70->setGeometry(QRect(850, 90, 61, 21));
        label_70->setFrameShape(QFrame::Panel);
        label_70->setFrameShadow(QFrame::Sunken);
        label_70->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_68 = new QLabel(frame);
        label_68->setObjectName("label_68");
        label_68->setGeometry(QRect(920, 90, 61, 21));
        label_68->setFrameShape(QFrame::Panel);
        label_68->setFrameShadow(QFrame::Sunken);
        label_68->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditBTrOutsideColorH = new QSpinBox(frame);
        EditBTrOutsideColorH->setObjectName("EditBTrOutsideColorH");
        EditBTrOutsideColorH->setGeometry(QRect(770, 240, 61, 22));
        EditBTrOutsideColorH->setMaximum(1000000);
        EditBTrOutsideColorL = new QSpinBox(frame);
        EditBTrOutsideColorL->setObjectName("EditBTrOutsideColorL");
        EditBTrOutsideColorL->setGeometry(QRect(700, 240, 61, 22));
        EditBTrOutsideColorL->setMaximum(1000000);
        label_71 = new QLabel(frame);
        label_71->setObjectName("label_71");
        label_71->setGeometry(QRect(700, 220, 61, 21));
        label_71->setFrameShape(QFrame::Panel);
        label_71->setFrameShadow(QFrame::Sunken);
        label_71->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_72 = new QLabel(frame);
        label_72->setObjectName("label_72");
        label_72->setGeometry(QRect(770, 220, 61, 21));
        label_72->setFrameShape(QFrame::Panel);
        label_72->setFrameShadow(QFrame::Sunken);
        label_72->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditNTrOutsideColorH = new QSpinBox(frame);
        EditNTrOutsideColorH->setObjectName("EditNTrOutsideColorH");
        EditNTrOutsideColorH->setGeometry(QRect(920, 240, 61, 22));
        EditNTrOutsideColorH->setMaximum(1000000);
        EditNTrOutsideColorL = new QSpinBox(frame);
        EditNTrOutsideColorL->setObjectName("EditNTrOutsideColorL");
        EditNTrOutsideColorL->setGeometry(QRect(850, 240, 61, 22));
        EditNTrOutsideColorL->setMaximum(1000000);
        label_73 = new QLabel(frame);
        label_73->setObjectName("label_73");
        label_73->setGeometry(QRect(850, 220, 61, 21));
        label_73->setFrameShape(QFrame::Panel);
        label_73->setFrameShadow(QFrame::Sunken);
        label_73->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_74 = new QLabel(frame);
        label_74->setObjectName("label_74");
        label_74->setGeometry(QRect(920, 220, 61, 21));
        label_74->setFrameShape(QFrame::Panel);
        label_74->setFrameShadow(QFrame::Sunken);
        label_74->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditBTrInsideColorH = new QSpinBox(frame);
        EditBTrInsideColorH->setObjectName("EditBTrInsideColorH");
        EditBTrInsideColorH->setGeometry(QRect(770, 420, 61, 22));
        EditBTrInsideColorH->setMaximum(1000000);
        EditBTrInsideColorL = new QSpinBox(frame);
        EditBTrInsideColorL->setObjectName("EditBTrInsideColorL");
        EditBTrInsideColorL->setGeometry(QRect(700, 420, 61, 22));
        EditBTrInsideColorL->setMaximum(1000000);
        label_75 = new QLabel(frame);
        label_75->setObjectName("label_75");
        label_75->setGeometry(QRect(700, 400, 61, 21));
        label_75->setFrameShape(QFrame::Panel);
        label_75->setFrameShadow(QFrame::Sunken);
        label_75->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_76 = new QLabel(frame);
        label_76->setObjectName("label_76");
        label_76->setGeometry(QRect(770, 400, 61, 21));
        label_76->setFrameShape(QFrame::Panel);
        label_76->setFrameShadow(QFrame::Sunken);
        label_76->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditNTrInsideColorH = new QSpinBox(frame);
        EditNTrInsideColorH->setObjectName("EditNTrInsideColorH");
        EditNTrInsideColorH->setGeometry(QRect(920, 420, 61, 22));
        EditNTrInsideColorH->setMaximum(1000000);
        EditNTrInsideColorL = new QSpinBox(frame);
        EditNTrInsideColorL->setObjectName("EditNTrInsideColorL");
        EditNTrInsideColorL->setGeometry(QRect(850, 420, 61, 22));
        EditNTrInsideColorL->setMaximum(1000000);
        label_77 = new QLabel(frame);
        label_77->setObjectName("label_77");
        label_77->setGeometry(QRect(850, 400, 61, 21));
        label_77->setFrameShape(QFrame::Panel);
        label_77->setFrameShadow(QFrame::Sunken);
        label_77->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_78 = new QLabel(frame);
        label_78->setObjectName("label_78");
        label_78->setGeometry(QRect(920, 400, 61, 21));
        label_78->setFrameShape(QFrame::Panel);
        label_78->setFrameShadow(QFrame::Sunken);
        label_78->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditBInsideColorH = new QSpinBox(frame);
        EditBInsideColorH->setObjectName("EditBInsideColorH");
        EditBInsideColorH->setGeometry(QRect(770, 530, 61, 22));
        EditBInsideColorH->setMaximum(1000000);
        EditBInsideColorL = new QSpinBox(frame);
        EditBInsideColorL->setObjectName("EditBInsideColorL");
        EditBInsideColorL->setGeometry(QRect(700, 530, 61, 22));
        EditBInsideColorL->setMaximum(1000000);
        label_79 = new QLabel(frame);
        label_79->setObjectName("label_79");
        label_79->setGeometry(QRect(700, 510, 61, 21));
        label_79->setFrameShape(QFrame::Panel);
        label_79->setFrameShadow(QFrame::Sunken);
        label_79->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_80 = new QLabel(frame);
        label_80->setObjectName("label_80");
        label_80->setGeometry(QRect(770, 510, 61, 21));
        label_80->setFrameShape(QFrame::Panel);
        label_80->setFrameShadow(QFrame::Sunken);
        label_80->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditNInsideColorH = new QSpinBox(frame);
        EditNInsideColorH->setObjectName("EditNInsideColorH");
        EditNInsideColorH->setGeometry(QRect(920, 530, 61, 22));
        EditNInsideColorH->setMaximum(1000000);
        EditNInsideColorL = new QSpinBox(frame);
        EditNInsideColorL->setObjectName("EditNInsideColorL");
        EditNInsideColorL->setGeometry(QRect(850, 530, 61, 22));
        EditNInsideColorL->setMaximum(1000000);
        label_81 = new QLabel(frame);
        label_81->setObjectName("label_81");
        label_81->setGeometry(QRect(850, 510, 61, 21));
        label_81->setFrameShape(QFrame::Panel);
        label_81->setFrameShadow(QFrame::Sunken);
        label_81->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_82 = new QLabel(frame);
        label_82->setObjectName("label_82");
        label_82->setGeometry(QRect(920, 510, 61, 21));
        label_82->setFrameShape(QFrame::Panel);
        label_82->setFrameShadow(QFrame::Sunken);
        label_82->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        line = new QFrame(frame);
        line->setObjectName("line");
        line->setGeometry(QRect(830, 20, 20, 601));
        line->setFrameShape(QFrame::Shape::VLine);
        line->setFrameShadow(QFrame::Shadow::Sunken);
        line_3 = new QFrame(frame);
        line_3->setObjectName("line_3");
        line_3->setGeometry(QRect(690, 310, 301, 16));
        line_3->setFrameShape(QFrame::Shape::HLine);
        line_3->setFrameShadow(QFrame::Shadow::Sunken);
        frame_2 = new QFrame(frame);
        frame_2->setObjectName("frame_2");
        frame_2->setGeometry(QRect(690, 0, 301, 21));
        frame_2->setFrameShape(QFrame::StyledPanel);
        frame_2->setFrameShadow(QFrame::Raised);
        toolButtonSelectN = new QToolButton(frame_2);
        toolButtonSelectN->setObjectName("toolButtonSelectN");
        toolButtonSelectN->setGeometry(QRect(150, 0, 151, 21));
        toolButtonSelectN->setCheckable(true);
        toolButtonSelectN->setChecked(false);
        toolButtonSelectN->setAutoExclusive(true);
        toolButtonSelectB = new QToolButton(frame_2);
        toolButtonSelectB->setObjectName("toolButtonSelectB");
        toolButtonSelectB->setGeometry(QRect(0, 0, 151, 21));
        toolButtonSelectB->setCheckable(true);
        toolButtonSelectB->setChecked(true);
        toolButtonSelectB->setAutoExclusive(true);
        EditOutsideCenterColorOnMaster = new QSpinBox(frame);
        EditOutsideCenterColorOnMaster->setObjectName("EditOutsideCenterColorOnMaster");
        EditOutsideCenterColorOnMaster->setGeometry(QRect(840, 140, 61, 22));
        QPalette palette;
        QBrush brush(QColor(0, 255, 255, 255));
        brush.setStyle(Qt::BrushStyle::SolidPattern);
        palette.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush);
        palette.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush);
        QBrush brush1(QColor(212, 208, 200, 255));
        brush1.setStyle(Qt::BrushStyle::SolidPattern);
        palette.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush1);
        EditOutsideCenterColorOnMaster->setPalette(palette);
        EditOutsideCenterColorOnMaster->setReadOnly(true);
        EditOutsideCenterColorOnMaster->setMaximum(1000000);
        label_83 = new QLabel(frame);
        label_83->setObjectName("label_83");
        label_83->setGeometry(QRect(700, 140, 141, 21));
        label_83->setFrameShape(QFrame::Panel);
        label_83->setFrameShadow(QFrame::Sunken);
        label_83->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditOutsideCenterColorOnTarget = new QSpinBox(frame);
        EditOutsideCenterColorOnTarget->setObjectName("EditOutsideCenterColorOnTarget");
        EditOutsideCenterColorOnTarget->setGeometry(QRect(900, 140, 61, 22));
        QPalette palette1;
        palette1.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush);
        palette1.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush);
        palette1.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush1);
        EditOutsideCenterColorOnTarget->setPalette(palette1);
        EditOutsideCenterColorOnTarget->setReadOnly(true);
        EditOutsideCenterColorOnTarget->setMaximum(1000000);
        label_84 = new QLabel(frame);
        label_84->setObjectName("label_84");
        label_84->setGeometry(QRect(700, 290, 141, 21));
        label_84->setFrameShape(QFrame::Panel);
        label_84->setFrameShadow(QFrame::Sunken);
        label_84->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditOutsideTrCenterColorOnTarget = new QSpinBox(frame);
        EditOutsideTrCenterColorOnTarget->setObjectName("EditOutsideTrCenterColorOnTarget");
        EditOutsideTrCenterColorOnTarget->setGeometry(QRect(900, 290, 61, 22));
        QPalette palette2;
        palette2.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush);
        palette2.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush);
        palette2.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush1);
        EditOutsideTrCenterColorOnTarget->setPalette(palette2);
        EditOutsideTrCenterColorOnTarget->setReadOnly(true);
        EditOutsideTrCenterColorOnTarget->setMaximum(1000000);
        EditOutsideTrCenterColorOnMaster = new QSpinBox(frame);
        EditOutsideTrCenterColorOnMaster->setObjectName("EditOutsideTrCenterColorOnMaster");
        EditOutsideTrCenterColorOnMaster->setGeometry(QRect(840, 290, 61, 22));
        QPalette palette3;
        palette3.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush);
        palette3.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush);
        palette3.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush1);
        EditOutsideTrCenterColorOnMaster->setPalette(palette3);
        EditOutsideTrCenterColorOnMaster->setReadOnly(true);
        EditOutsideTrCenterColorOnMaster->setMaximum(1000000);
        label_85 = new QLabel(frame);
        label_85->setObjectName("label_85");
        label_85->setGeometry(QRect(700, 450, 141, 21));
        label_85->setFrameShape(QFrame::Panel);
        label_85->setFrameShadow(QFrame::Sunken);
        label_85->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditInsideTrCenterColorOnTarget = new QSpinBox(frame);
        EditInsideTrCenterColorOnTarget->setObjectName("EditInsideTrCenterColorOnTarget");
        EditInsideTrCenterColorOnTarget->setGeometry(QRect(900, 450, 61, 22));
        QPalette palette4;
        palette4.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush);
        palette4.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush);
        palette4.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush1);
        EditInsideTrCenterColorOnTarget->setPalette(palette4);
        EditInsideTrCenterColorOnTarget->setReadOnly(true);
        EditInsideTrCenterColorOnTarget->setMaximum(1000000);
        EditInsideTrCenterColorOnMaster = new QSpinBox(frame);
        EditInsideTrCenterColorOnMaster->setObjectName("EditInsideTrCenterColorOnMaster");
        EditInsideTrCenterColorOnMaster->setGeometry(QRect(840, 450, 61, 22));
        QPalette palette5;
        palette5.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush);
        palette5.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush);
        palette5.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush1);
        EditInsideTrCenterColorOnMaster->setPalette(palette5);
        EditInsideTrCenterColorOnMaster->setReadOnly(true);
        EditInsideTrCenterColorOnMaster->setMaximum(1000000);
        label_86 = new QLabel(frame);
        label_86->setObjectName("label_86");
        label_86->setGeometry(QRect(700, 580, 141, 21));
        label_86->setFrameShape(QFrame::Panel);
        label_86->setFrameShadow(QFrame::Sunken);
        label_86->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditInsideCenterColorOnTarget = new QSpinBox(frame);
        EditInsideCenterColorOnTarget->setObjectName("EditInsideCenterColorOnTarget");
        EditInsideCenterColorOnTarget->setGeometry(QRect(900, 580, 61, 22));
        QPalette palette6;
        palette6.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush);
        palette6.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush);
        palette6.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush1);
        EditInsideCenterColorOnTarget->setPalette(palette6);
        EditInsideCenterColorOnTarget->setReadOnly(true);
        EditInsideCenterColorOnTarget->setMaximum(1000000);
        EditInsideCenterColorOnMaster = new QSpinBox(frame);
        EditInsideCenterColorOnMaster->setObjectName("EditInsideCenterColorOnMaster");
        EditInsideCenterColorOnMaster->setGeometry(QRect(840, 580, 61, 22));
        QPalette palette7;
        palette7.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush);
        palette7.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush);
        palette7.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush1);
        EditInsideCenterColorOnMaster->setPalette(palette7);
        EditInsideCenterColorOnMaster->setReadOnly(true);
        EditInsideCenterColorOnMaster->setMaximum(1000000);
        label_9 = new QLabel(MonoOutlineFormClass);
        label_9->setObjectName("label_9");
        label_9->setGeometry(QRect(680, 640, 101, 20));
        label_9->setFrameShape(QFrame::Panel);
        label_9->setFrameShadow(QFrame::Sunken);
        label_9->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditLibName = new QLineEdit(MonoOutlineFormClass);
        EditLibName->setObjectName("EditLibName");
        EditLibName->setGeometry(QRect(780, 660, 191, 21));
        EditLibName->setReadOnly(true);
        EditLibID = new QLineEdit(MonoOutlineFormClass);
        EditLibID->setObjectName("EditLibID");
        EditLibID->setGeometry(QRect(780, 640, 61, 21));
        EditLibID->setReadOnly(true);
        label_10 = new QLabel(MonoOutlineFormClass);
        label_10->setObjectName("label_10");
        label_10->setGeometry(QRect(680, 660, 101, 20));
        label_10->setFrameShape(QFrame::Panel);
        label_10->setFrameShadow(QFrame::Sunken);
        label_10->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_11 = new QLabel(MonoOutlineFormClass);
        label_11->setObjectName("label_11");
        label_11->setGeometry(QRect(160, 630, 81, 21));
        label_12 = new QLabel(MonoOutlineFormClass);
        label_12->setObjectName("label_12");
        label_12->setGeometry(QRect(260, 630, 71, 21));
        frameMaster = new QFrame(MonoOutlineFormClass);
        frameMaster->setObjectName("frameMaster");
        frameMaster->setGeometry(QRect(30, 631, 21, 20));
        frameMaster->setFrameShape(QFrame::NoFrame);
        frameMaster->setFrameShadow(QFrame::Plain);
        label_13 = new QLabel(MonoOutlineFormClass);
        label_13->setObjectName("label_13");
        label_13->setGeometry(QRect(60, 630, 81, 21));
        frameThresholdB = new QFrame(MonoOutlineFormClass);
        frameThresholdB->setObjectName("frameThresholdB");
        frameThresholdB->setGeometry(QRect(240, 630, 21, 21));
        frameThresholdB->setFrameShape(QFrame::NoFrame);
        frameThresholdB->setFrameShadow(QFrame::Plain);
        frameTarget = new QFrame(MonoOutlineFormClass);
        frameTarget->setObjectName("frameTarget");
        frameTarget->setGeometry(QRect(140, 630, 21, 21));
        frameTarget->setFrameShape(QFrame::NoFrame);
        frameTarget->setFrameShadow(QFrame::Plain);
        label_14 = new QLabel(MonoOutlineFormClass);
        label_14->setObjectName("label_14");
        label_14->setGeometry(QRect(360, 630, 71, 21));
        frameThresholdN = new QFrame(MonoOutlineFormClass);
        frameThresholdN->setObjectName("frameThresholdN");
        frameThresholdN->setGeometry(QRect(340, 630, 21, 21));
        frameThresholdN->setFrameShape(QFrame::NoFrame);
        frameThresholdN->setFrameShadow(QFrame::Plain);
        frame_6 = new QFrame(MonoOutlineFormClass);
        frame_6->setObjectName("frame_6");
        frame_6->setGeometry(QRect(490, 640, 181, 151));
        frame_6->setFrameShape(QFrame::StyledPanel);
        frame_6->setFrameShadow(QFrame::Sunken);
        label_32 = new QLabel(frame_6);
        label_32->setObjectName("label_32");
        label_32->setGeometry(QRect(0, 0, 181, 21));
        label_32->setFrameShape(QFrame::Panel);
        label_32->setFrameShadow(QFrame::Sunken);
        label_32->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        ButtonOptimizeOnly = new QPushButton(frame_6);
        ButtonOptimizeOnly->setObjectName("ButtonOptimizeOnly");
        ButtonOptimizeOnly->setGeometry(QRect(20, 80, 141, 31));
        ButtonOptimizeAll = new QPushButton(frame_6);
        ButtonOptimizeAll->setObjectName("ButtonOptimizeAll");
        ButtonOptimizeAll->setGeometry(QRect(20, 110, 141, 31));
        label_7 = new QLabel(frame_6);
        label_7->setObjectName("label_7");
        label_7->setGeometry(QRect(10, 30, 71, 21));
        label_7->setFrameShape(QFrame::Panel);
        label_7->setFrameShadow(QFrame::Sunken);
        label_7->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_8 = new QLabel(frame_6);
        label_8->setObjectName("label_8");
        label_8->setGeometry(QRect(90, 30, 71, 21));
        label_8->setFrameShape(QFrame::Panel);
        label_8->setFrameShadow(QFrame::Sunken);
        label_8->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditBExtendRate = new QSpinBox(frame_6);
        EditBExtendRate->setObjectName("EditBExtendRate");
        EditBExtendRate->setGeometry(QRect(20, 50, 61, 22));
        EditBExtendRate->setMaximum(1000000);
        EditNExtendRate = new QSpinBox(frame_6);
        EditNExtendRate->setObjectName("EditNExtendRate");
        EditNExtendRate->setGeometry(QRect(100, 50, 61, 22));
        EditNExtendRate->setMaximum(1000000);
        frame_31 = new QFrame(MonoOutlineFormClass);
        frame_31->setObjectName("frame_31");
        frame_31->setGeometry(QRect(10, 780, 311, 71));
        frame_31->setFrameShape(QFrame::StyledPanel);
        frame_31->setFrameShadow(QFrame::Sunken);
        label_104 = new QLabel(frame_31);
        label_104->setObjectName("label_104");
        label_104->setGeometry(QRect(0, 0, 20, 71));
        label_104->setFrameShape(QFrame::Panel);
        label_104->setFrameShadow(QFrame::Raised);
        label_104->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_104->setIndent(1);
        frame_32 = new QFrame(frame_31);
        frame_32->setObjectName("frame_32");
        frame_32->setGeometry(QRect(10, 120, 371, 101));
        frame_32->setFrameShape(QFrame::StyledPanel);
        frame_32->setFrameShadow(QFrame::Sunken);
        label_105 = new QLabel(frame_32);
        label_105->setObjectName("label_105");
        label_105->setGeometry(QRect(0, 0, 20, 61));
        label_105->setFrameShape(QFrame::Panel);
        label_105->setFrameShadow(QFrame::Raised);
        label_105->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_105->setIndent(1);
        checkBoxDiffMode = new QCheckBox(frame_31);
        checkBoxDiffMode->setObjectName("checkBoxDiffMode");
        checkBoxDiffMode->setGeometry(QRect(40, 10, 261, 20));
        checkBoxMatchSlideOnMaster = new QCheckBox(frame_31);
        checkBoxMatchSlideOnMaster->setObjectName("checkBoxMatchSlideOnMaster");
        checkBoxMatchSlideOnMaster->setGeometry(QRect(40, 30, 261, 18));
        checkBoxAbsMode = new QCheckBox(frame_31);
        checkBoxAbsMode->setObjectName("checkBoxAbsMode");
        checkBoxAbsMode->setGeometry(QRect(40, 50, 261, 18));

        retranslateUi(MonoOutlineFormClass);

        stackedWidgetParts->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(MonoOutlineFormClass);
    } // setupUi

    void retranslateUi(QDialog *MonoOutlineFormClass)
    {
        MonoOutlineFormClass->setWindowTitle(QCoreApplication::translate("MonoOutlineFormClass", "MonoOutlineForm", nullptr));
        label->setText(QCoreApplication::translate("MonoOutlineFormClass", "\345\244\226\345\201\264", nullptr));
        label_2->setText(QCoreApplication::translate("MonoOutlineFormClass", "\351\201\267\347\247\273\345\244\226\345\201\264", nullptr));
        label_3->setText(QCoreApplication::translate("MonoOutlineFormClass", "\351\201\267\347\247\273\345\206\205\345\201\264", nullptr));
        label_4->setText(QCoreApplication::translate("MonoOutlineFormClass", "\345\206\205\345\201\264", nullptr));
        label_90->setText(QCoreApplication::translate("MonoOutlineFormClass", "\346\216\242\n"
"\347\264\242", nullptr));
        label_91->setText(QCoreApplication::translate("MonoOutlineFormClass", "\350\274\235\n"
"\345\272\246", nullptr));
        label_92->setText(QCoreApplication::translate("MonoOutlineFormClass", "\343\203\226\343\203\255\343\203\203\343\202\257\345\215\230\344\275\223\343\201\247\343\201\256\346\216\242\347\264\242\343\203\211\343\203\203\343\203\210\346\225\260", nullptr));
        label_93->setText(QCoreApplication::translate("MonoOutlineFormClass", "\350\274\235\n"
"\345\272\246\n"
"\350\243\234\n"
"\346\255\243", nullptr));
        label_94->setText(QCoreApplication::translate("MonoOutlineFormClass", "\350\274\235\n"
"\345\272\246", nullptr));
        label_95->setText(QCoreApplication::translate("MonoOutlineFormClass", "\346\234\200\345\244\247\346\232\227\345\201\264\350\243\234\346\255\243\350\274\235\345\272\246\351\207\217", nullptr));
        label_96->setText(QCoreApplication::translate("MonoOutlineFormClass", "\346\234\200\345\244\247\346\230\216\345\201\264\350\243\234\346\255\243\350\274\235\345\272\246\351\207\217", nullptr));
        checkBoxAdjustMode->setText(QCoreApplication::translate("MonoOutlineFormClass", "\350\274\235\345\272\246\350\243\234\346\255\243\343\201\256\345\256\237\350\241\214", nullptr));
        label_97->setText(QCoreApplication::translate("MonoOutlineFormClass", "\345\244\226\345\201\264", nullptr));
        label_98->setText(QCoreApplication::translate("MonoOutlineFormClass", "\345\206\205\345\201\264", nullptr));
        label_31->setText(QCoreApplication::translate("MonoOutlineFormClass", "\345\275\223\350\251\262\347\256\207\346\211\200\343\201\256\345\210\244\345\256\232\347\265\220\346\236\234", nullptr));
        labelResultOutsideN->setText(QCoreApplication::translate("MonoOutlineFormClass", "123", nullptr));
        labelResultInsideB->setText(QCoreApplication::translate("MonoOutlineFormClass", "123", nullptr));
        ButtonCalc->setText(QCoreApplication::translate("MonoOutlineFormClass", "\350\250\210\347\256\227", nullptr));
        labelResultOutsideB->setText(QCoreApplication::translate("MonoOutlineFormClass", "123", nullptr));
        labelResultInsideN->setText(QCoreApplication::translate("MonoOutlineFormClass", "123", nullptr));
        label_15->setText(QCoreApplication::translate("MonoOutlineFormClass", "\345\272\203\345\237\237", nullptr));
        label_16->setText(QCoreApplication::translate("MonoOutlineFormClass", "\347\213\255\345\237\237", nullptr));
        label_17->setText(QCoreApplication::translate("MonoOutlineFormClass", "O", nullptr));
        label_18->setText(QCoreApplication::translate("MonoOutlineFormClass", "I", nullptr));
        ButtonReflectAllBlocks->setText(QCoreApplication::translate("MonoOutlineFormClass", "\345\220\214\344\270\200\347\250\256\351\241\236\343\201\256\343\203\226\343\203\255\343\203\203\343\202\257\343\201\253\345\217\215\346\230\240", nullptr));
        ButtonRefrectOnlyBlock->setText(QCoreApplication::translate("MonoOutlineFormClass", "\343\201\223\343\201\256\343\203\226\343\203\255\343\203\203\343\202\257\343\201\240\343\201\221\343\201\253\345\217\215\346\230\240", nullptr));
        ButtonRelrectSaveParts->setText(QCoreApplication::translate("MonoOutlineFormClass", "\351\203\250\345\223\201\344\277\235\345\255\230", nullptr));
        ButtonLoadFromLibrary->setText(QCoreApplication::translate("MonoOutlineFormClass", "\343\203\251\343\202\244\343\203\226\343\203\251\343\203\252\343\201\213\343\202\211\350\252\255\343\201\277\345\207\272\343\201\227", nullptr));
        ButtonSaveToLibrary->setText(QCoreApplication::translate("MonoOutlineFormClass", "\343\203\251\343\202\244\343\203\226\343\203\251\343\203\252\343\201\253\344\277\235\345\255\230", nullptr));
        pushButtonClose->setText(QCoreApplication::translate("MonoOutlineFormClass", "\351\226\211\343\201\230\343\202\213", nullptr));
        checkBoxEffectiveBInside->setText(QCoreApplication::translate("MonoOutlineFormClass", "\347\265\220\346\236\234\345\207\272\345\212\233", nullptr));
        label_48->setText(QCoreApplication::translate("MonoOutlineFormClass", "OK\343\203\211\343\203\203\343\203\210\346\225\260", nullptr));
        checkBoxEffectiveBOutside->setText(QCoreApplication::translate("MonoOutlineFormClass", "\347\265\220\346\236\234\345\207\272\345\212\233", nullptr));
        label_50->setText(QCoreApplication::translate("MonoOutlineFormClass", "OK\343\203\211\343\203\203\343\203\210\346\225\260", nullptr));
        checkBoxEffectiveNInside->setText(QCoreApplication::translate("MonoOutlineFormClass", "\347\265\220\346\236\234\345\207\272\345\212\233", nullptr));
        checkBoxEffectiveNOutside->setText(QCoreApplication::translate("MonoOutlineFormClass", "\347\265\220\346\236\234\345\207\272\345\212\233", nullptr));
        label_49->setText(QCoreApplication::translate("MonoOutlineFormClass", "OK\343\203\211\343\203\203\343\203\210\346\225\260", nullptr));
        label_51->setText(QCoreApplication::translate("MonoOutlineFormClass", "OK\343\203\211\343\203\203\343\203\210\346\225\260", nullptr));
        label_67->setText(QCoreApplication::translate("MonoOutlineFormClass", "\346\230\216\345\201\264", nullptr));
        label_69->setText(QCoreApplication::translate("MonoOutlineFormClass", "\346\232\227\345\201\264", nullptr));
        label_70->setText(QCoreApplication::translate("MonoOutlineFormClass", "\346\232\227\345\201\264", nullptr));
        label_68->setText(QCoreApplication::translate("MonoOutlineFormClass", "\346\230\216\345\201\264", nullptr));
        label_71->setText(QCoreApplication::translate("MonoOutlineFormClass", "\346\232\227\345\201\264", nullptr));
        label_72->setText(QCoreApplication::translate("MonoOutlineFormClass", "\346\230\216\345\201\264", nullptr));
        label_73->setText(QCoreApplication::translate("MonoOutlineFormClass", "\346\232\227\345\201\264", nullptr));
        label_74->setText(QCoreApplication::translate("MonoOutlineFormClass", "\346\230\216\345\201\264", nullptr));
        label_75->setText(QCoreApplication::translate("MonoOutlineFormClass", "\346\232\227\345\201\264", nullptr));
        label_76->setText(QCoreApplication::translate("MonoOutlineFormClass", "\346\230\216\345\201\264", nullptr));
        label_77->setText(QCoreApplication::translate("MonoOutlineFormClass", "\346\232\227\345\201\264", nullptr));
        label_78->setText(QCoreApplication::translate("MonoOutlineFormClass", "\346\230\216\345\201\264", nullptr));
        label_79->setText(QCoreApplication::translate("MonoOutlineFormClass", "\346\232\227\345\201\264", nullptr));
        label_80->setText(QCoreApplication::translate("MonoOutlineFormClass", "\346\230\216\345\201\264", nullptr));
        label_81->setText(QCoreApplication::translate("MonoOutlineFormClass", "\346\232\227\345\201\264", nullptr));
        label_82->setText(QCoreApplication::translate("MonoOutlineFormClass", "\346\230\216\345\201\264", nullptr));
        toolButtonSelectN->setText(QCoreApplication::translate("MonoOutlineFormClass", "\347\213\255\345\237\237", nullptr));
        toolButtonSelectB->setText(QCoreApplication::translate("MonoOutlineFormClass", "\345\272\203\345\237\237", nullptr));
        label_83->setText(QCoreApplication::translate("MonoOutlineFormClass", "\344\270\255\345\277\203\350\274\235\345\272\246 Master/Target", nullptr));
        label_84->setText(QCoreApplication::translate("MonoOutlineFormClass", "\344\270\255\345\277\203\350\274\235\345\272\246 Master/Target", nullptr));
        label_85->setText(QCoreApplication::translate("MonoOutlineFormClass", "\344\270\255\345\277\203\350\274\235\345\272\246 Master/Target", nullptr));
        label_86->setText(QCoreApplication::translate("MonoOutlineFormClass", "\344\270\255\345\277\203\350\274\235\345\272\246 Master/Target", nullptr));
        label_9->setText(QCoreApplication::translate("MonoOutlineFormClass", "\343\203\251\343\202\244\343\203\226\343\203\251\343\203\252\357\274\251\357\274\244", nullptr));
        EditLibName->setText(QCoreApplication::translate("MonoOutlineFormClass", "XXX", nullptr));
        EditLibID->setText(QCoreApplication::translate("MonoOutlineFormClass", "12345", nullptr));
        label_10->setText(QCoreApplication::translate("MonoOutlineFormClass", "\343\203\251\343\202\244\343\203\226\343\203\251\343\203\252\345\220\215\347\247\260", nullptr));
        label_11->setText(QCoreApplication::translate("MonoOutlineFormClass", "\346\244\234\346\237\273\347\224\273\345\203\217", nullptr));
        label_12->setText(QCoreApplication::translate("MonoOutlineFormClass", "\345\272\203\345\237\237\343\201\227\343\201\215\343\201\204\345\200\244", nullptr));
        label_13->setText(QCoreApplication::translate("MonoOutlineFormClass", "\343\203\236\343\202\271\343\202\277\343\203\274\347\224\273\345\203\217", nullptr));
        label_14->setText(QCoreApplication::translate("MonoOutlineFormClass", "\347\213\255\345\237\237\343\201\227\343\201\215\343\201\204\345\200\244", nullptr));
        label_32->setText(QCoreApplication::translate("MonoOutlineFormClass", "\346\234\200\351\201\251\345\214\226", nullptr));
        ButtonOptimizeOnly->setText(QCoreApplication::translate("MonoOutlineFormClass", "\345\275\223\350\251\262\343\203\226\343\203\255\343\203\203\343\202\257\343\201\256\343\201\277\346\234\200\351\201\251\345\214\226", nullptr));
        ButtonOptimizeAll->setText(QCoreApplication::translate("MonoOutlineFormClass", "\345\205\250\343\203\226\343\203\255\343\203\203\343\202\257\343\201\256\346\234\200\351\201\251\345\214\226", nullptr));
        label_7->setText(QCoreApplication::translate("MonoOutlineFormClass", "\345\272\203\345\237\237\343\203\236\343\203\274\343\202\270\343\203\263\357\274\205", nullptr));
        label_8->setText(QCoreApplication::translate("MonoOutlineFormClass", "\347\213\255\345\237\237\343\203\236\343\203\274\343\202\270\343\203\263\357\274\205", nullptr));
        label_104->setText(QCoreApplication::translate("MonoOutlineFormClass", "\346\244\234\n"
"\346\237\273", nullptr));
        label_105->setText(QCoreApplication::translate("MonoOutlineFormClass", "\350\274\235\n"
"\345\272\246", nullptr));
        checkBoxDiffMode->setText(QCoreApplication::translate("MonoOutlineFormClass", "\345\267\256\345\210\206\346\244\234\346\237\273", nullptr));
        checkBoxMatchSlideOnMaster->setText(QCoreApplication::translate("MonoOutlineFormClass", "\343\203\236\343\202\271\343\202\277\343\203\274\344\275\215\347\275\256\343\201\247\343\203\236\343\203\203\343\203\201\343\203\263\343\202\260\347\247\273\345\213\225", nullptr));
        checkBoxAbsMode->setText(QCoreApplication::translate("MonoOutlineFormClass", "\347\265\266\345\257\276\350\274\235\345\272\246", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MonoOutlineFormClass: public Ui_MonoOutlineFormClass {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MONOOUTLINEFORM_H
