#ifndef DISPLACEMENTMETERIL_GLOBAL_H
#define DISPLACEMENTMETERIL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef DISPLACEMENTMETERIL_LIB
# define DISPLACEMENTMETERIL_EXPORT Q_DECL_EXPORT
#else
# define DISPLACEMENTMETERIL_EXPORT Q_DECL_IMPORT
#endif

#endif // DISPLACEMENTMETERIL_GLOBAL_H
