#ifndef BUTTONTRANSFERSENDGLOBALPARAM_GLOBAL_H
#define BUTTONTRANSFERSENDGLOBALPARAM_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONTRANSFERSENDGLOBALPARAM_LIB
# define BUTTONTRANSFERSENDGLOBALPARAM_EXPORT Q_DECL_EXPORT
#else
# define BUTTONTRANSFERSENDGLOBALPARAM_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONTRANSFERSENDGLOBALPARAM_GLOBAL_H
