#ifndef LANGUAGEMANAGERLIB_GLOBAL_H
#define LANGUAGEMANAGERLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef LANGUAGEMANAGERLIB_LIB
# define LANGUAGEMANAGERLIB_EXPORT Q_DECL_EXPORT
#else
# define LANGUAGEMANAGERLIB_EXPORT Q_DECL_IMPORT
#endif

#endif // LANGUAGEMANAGERLIB_GLOBAL_H
