# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------
QT += core gui network sql widgets

TEMPLATE = lib
TARGET = ShowColorDifferenceEditManual
DESTDIR = ../
CONFIG += release
DEFINES += QT_LARGEFILE_SUPPORT ShowColorDifferenceEditManual_LIB
LIBS += -L"./../../Lib/Release" \
    -lServiceLib
MOC_DIR += .
OBJECTS_DIR += release
include(ShowColorDifferenceEditManual.pri)

FORMS += \
    ShowColorDifferenceEditManualForm.ui

HEADERS += \
    ShowColorDifferenceEditManualForm.h

SOURCES += \
    ShowColorDifferenceEditManualForm.cpp
