#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(SHOWCOLORDIFFERENCEEDITMANUAL_LIB)
#  define SHOWCOLORDIFFERENCEEDITMANUAL_EXPORT Q_DECL_EXPORT
# else
#  define SHOWCOLORDIFFERENCEEDITMANUAL_EXPORT Q_DECL_IMPORT
# endif
#else
# define SHOWCOLORDIFFERENCEEDITMANUAL_EXPORT
#endif
