# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = AutoStartList
DESTDIR = ../
CONFIG += debug
LIBS += -L"./../Lib/Release" \
    -lCommonGUIDLL \
    -lComponent \
    -lServiceLib \
    -lPsapi.Lib
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += .
RCC_DIR += .
include(AutoStartList.pri)
win32:RC_FILE = AutoStartList.rc
