#ifndef BUTTONLIGHTSHORTCUT_GLOBAL_H
#define BUTTONLIGHTSHORTCUT_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONLIGHTSHORTCUT_LIB
# define BUTTONLIGHTSHORTCUT_EXPORT Q_DECL_EXPORT
#else
# define BUTTONLIGHTSHORTCUT_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONLIGHTSHORTCUT_GLOBAL_H
