#ifndef PROPERTYSPOTREDUCER_GLOBAL_H
#define PROPERTYSPOTREDUCER_GLOBAL_H

#include <qglobal.h>

#ifdef PROPERTYSPOTREDUCER_LIB
# define PROPERTYSPOTREDUCER_EXPORT Q_DECL_EXPORT
#else
# define PROPERTYSPOTREDUCER_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTYSPOTREDUCER_GLOBAL_H
