# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


TEMPLATE = subdirs
SUBDIRS += SampleDLL/SampleDLL.pro \
    LogWriter/LogWriter.pro \
    MachineT01For64Connector/MachineT01For64Connector.pro \
    SeqFor64Connector/SeqFor64Connector.pro \
    IOLogger/IOLogger.pro \
    OutputMessager/OutputMessager.pro \
    CheckProgramRun/CheckProgramRun.pro \
    ShutDownDLL/ShutDownDLL.pro \
    PlaySound/PlaySound.pro \
    mtMachineT04Command/mtMachineT04Command/mtMachineT04Command.pro \
    MachineT04Connector/MachineT04Connector.pro \
    MachineLR210Connector/MachineLR210Connector.pro \
    MotorControlle/MotorControlle/MotorControlle.pro \
    mtVRSCommand/mtVRSCommand/mtVRSCommand.pro \
    mtVRSCommand2/mtVRSCommand2/mtVRSCommand2.pro \
    LCD_4DSystem_1/LCD_4DSystem_1.pro \
    mtNGMarkMachineCommand/mtNGMarkMachineCommand.pro \
    AFVI_CommPLC/AFVI_CommPLC.pro \
    SeqRelay4ByFTDI/SeqRelay4ByFTDI.pro \
    SeqRelayLCUS2/SeqRelayLCUS2.pro
