#ifndef THINMETALIMAGEPANEL_GLOBAL_H
#define THINMETALIMAGEPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef THINMETALIMAGEPANEL_LIB
# define THINMETALIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define THINMETALIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // THINMETALIMAGEPANEL_GLOBAL_H
