#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(BUTTONSETTINGCONTROLPOINTSFORPAGES_LIB)
#  define BUTTONSETTINGCONTROLPOINTSFORPAGES_EXPORT Q_DECL_EXPORT
# else
#  define BUTTONSETTINGCONTROLPOINTSFORPAGES_EXPORT Q_DECL_IMPORT
# endif
#else
# define BUTTONSETTINGCONTROLPOINTSFORPAGES_EXPORT
#endif
