# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = ButtonSettingControlPointsForPages
DESTDIR = ../
CONFIG += debug
DEFINES += BUTTONSETTINGCONTROLPOINTSFORPAGES_LIB
LIBS += -L"./../../Lib/Release" \
    -lServiceLib
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles
include(ButtonSettingControlPointsForPages.pri)
