#ifndef SHOWRESULTINFORMATION_GLOBAL_H
#define SHOWRESULTINFORMATION_GLOBAL_H

#include <qglobal.h>

#ifdef SHOWRESULTINFORMATION_LIB
# define SHOWRESULTINFORMATION_EXPORT Q_DECL_EXPORT
#else
# define SHOWRESULTINFORMATION_EXPORT Q_DECL_IMPORT
#endif

#endif // SHOWRESULTINFORMATION_GLOBAL_H
