#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(INTEGRATIONCAMERAADJUSTMENT_LIB)
#  define INTEGRATIONCAMERAADJUSTMENT_EXPORT Q_DECL_EXPORT
# else
#  define INTEGRATIONCAMERAADJUSTMENT_EXPORT Q_DECL_IMPORT
# endif
#else
# define INTEGRATIONCAMERAADJUSTMENT_EXPORT
#endif
