#ifndef COPYMIRROREDTRANSFER_GLOBAL_H
#define COPYMIRROREDTRANSFER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef COPYMIRROREDTRANSFER_LIB
# define COPYMIRROREDTRANSFER_EXPORT Q_DECL_EXPORT
#else
# define COPYMIRROREDTRANSFER_EXPORT Q_DECL_IMPORT
#endif

#endif // COPYMIRROREDTRANSFER_GLOBAL_H
