#ifndef PROPERTYCATEGORIZEDSHADER_GLOBAL_H
#define PROPERTYCATEGORIZEDSHADER_GLOBAL_H

#include <qglobal.h>

#ifdef PROPERTYCATEGORIZEDSHADER_LIB
# define PROPERTYCATEGORIZEDSHADER_EXPORT Q_DECL_EXPORT
#else
# define PROPERTYCATEGORIZEDSHADER_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTYCATEGORIZEDSHADER_GLOBAL_H
