#ifndef DRAWHOOKCONTROLPANEL_GLOBAL_H
#define DRAWHOOKCONTROLPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef DRAWHOOKCONTROLPANEL_LIB
# define DRAWHOOKCONTROLPANEL_EXPORT Q_DECL_EXPORT
#else
# define DRAWHOOKCONTROLPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // DRAWHOOKCONTROLPANEL_GLOBAL_H
