#ifndef BUTTONOUTPUTTOPRINTER_GLOBAL_H
#define BUTTONOUTPUTTOPRINTER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONOUTPUTTOPRINTER_LIB
# define BUTTONOUTPUTTOPRINTER_EXPORT Q_DECL_EXPORT
#else
# define BUTTONOUTPUTTOPRINTER_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONOUTPUTTOPRINTER_GLOBAL_H
