#ifndef EASYPROPERTYDXFOPERATION_GLOBAL_H
#define EASYPROPERTYDXFOPERATION_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef EASYPROPERTYDXFOPERATION_LIB
# define EASYPROPERTYDXFOPERATION_EXPORT Q_DECL_EXPORT
#else
# define EASYPROPERTYDXFOPERATION_EXPORT Q_DECL_IMPORT
#endif

#endif // EASYPROPERTYDXFOPERATION_GLOBAL_H
