#ifndef INTEGRATIONSHOWNGARROW_GLOBAL_H
#define INTEGRATIONSHOWNGARROW_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef INTEGRATIONSHOWNGARROW_LIB
# define INTEGRATIONSHOWNGARROW_EXPORT Q_DECL_EXPORT
#else
# define INTEGRATIONSHOWNGARROW_EXPORT Q_DECL_IMPORT
#endif

#endif // INTEGRATIONSHOWNGARROW_GLOBAL_H
