#ifndef HOLEWALLINSPECTION_GLOBAL_H
#define HOLEWALLINSPECTION_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef HOLEWALLINSPECTION_LIB
# define HOLEWALLINSPECTION_EXPORT Q_DECL_EXPORT
#else
# define HOLEWALLINSPECTION_EXPORT Q_DECL_IMPORT
#endif

#endif // HOLEWALLINSPECTION_GLOBAL_H
