# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./DesktopMachineMenu.h \
    ./DesktopMachineMenuResource.h \
    ./desktopmachinemenu_global.h \
    ../StartStatisticScanButton/StartStatisticScanBase.h \
    ../StartCaptureButton/XPushCmdPacket.h \
    ./DesktopMachineMenuProperty.h \
    ./DesktopStartStatisticScan.h \
    ./NextMasterForm.h \
    ../StartCaptureButton/StartCaptureButton.h \
    ../StartInspectionButton/StartInspectionButton.h
SOURCES += ./DesktopMachineMenu.cpp \
    ./DesktopMachineMenuProperty.cpp \
    ./DesktopStartStatisticScan.cpp \
    ../../Open/GUIDllCommon.cpp \
    ./NextMasterForm.cpp \
    ../StartCaptureButton/StartCaptureButtonForm.cpp \
    ../StartInspectionButton/StartInspectionButtonForm.cpp \
    ../StartInspectionButton/StartInspectionButtonFormResource.cpp \
    ../StartStatisticScanButton/StartStatisticScanBase.cpp \
    ../../Open/SystemVersion.cpp \
    ../StartCaptureButton/XPushCmdPacket.cpp
FORMS += ./DesktopMachineMenuProperty.ui \
    ./NextMasterForm.ui
RESOURCES += DesktopMachineMenu.qrc
