#ifndef LIGHTDLL2PORTV9_GLOBAL_H
#define LIGHTDLL2PORTV9_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef LIGHTDLL2PORTV9_LIB
# define LIGHTDLL2PORTV9_EXPORT Q_DECL_EXPORT
#else
# define LIGHTDLL2PORTV9_EXPORT Q_DECL_IMPORT
#endif

#endif // LIGHTDLL2PORTV9_GLOBAL_H
