#ifndef COPYITEMSBETWEENPHASE_GLOBAL_H
#define COPYITEMSBETWEENPHASE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef COPYITEMSBETWEENPHASE_LIB
# define COPYITEMSBETWEENPHASE_EXPORT Q_DECL_EXPORT
#else
# define COPYITEMSBETWEENPHASE_EXPORT Q_DECL_IMPORT
#endif

#endif // COPYITEMSBETWEENPHASE_GLOBAL_H
