#ifndef LIVECAMERAMIGHTEXUSB2_GLOBAL_H
#define LIVECAMERAMIGHTEXUSB2_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef LIVECAMERAMIGHTEXUSB2_LIB
# define LIVECAMERAMIGHTEXUSB2_EXPORT Q_DECL_EXPORT
#else
# define LIVECAMERAMIGHTEXUSB2_EXPORT Q_DECL_IMPORT
#endif

#endif // LIVECAMERAMIGHTEXUSB2_GLOBAL_H
