#ifndef PRECISIONCHECKERLIB_GLOBAL_H
#define PRECISIONCHECKERLIB_GLOBAL_H

#include <qglobal.h>

#ifdef PRECISIONCHECKERLIB_LIB
# define PRECISIONCHECKERLIB_EXPORT Q_DECL_EXPORT
#else
# define PRECISIONCHECKERLIB_EXPORT Q_DECL_IMPORT
#endif

#endif // PRECISIONCHECKERLIB_GLOBAL_H
