#ifndef FILTERIMAGESHADINGAREA_GLOBAL_H
#define FILTERIMAGESHADINGAREA_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef FILTERIMAGESHADINGAREA_LIB
# define FILTERIMAGESHADINGAREA_EXPORT Q_DECL_EXPORT
#else
# define FILTERIMAGESHADINGAREA_EXPORT Q_DECL_IMPORT
#endif

#endif // FILTERIMAGESHADINGAREA_GLOBAL_H
