#ifndef PROPERTYBUSLINE_GLOBAL_H
#define PROPERTYBUSLINE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PROPERTYBUSLINE_LIB
# define PROPERTYBUSLINE_EXPORT Q_DECL_EXPORT
#else
# define PROPERTYBUSLINE_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTYBUSLINE_GLOBAL_H
