#ifndef VCUTPROPERTY_GLOBAL_H
#define VCUTPROPERTY_GLOBAL_H

#include <qglobal.h>

#ifdef VCUTPROPERTY_LIB
# define VCUTPROPERTY_EXPORT Q_DECL_EXPORT
#else
# define VCUTPROPERTY_EXPORT Q_DECL_IMPORT
#endif

#endif // VCUTPROPERTY_GLOBAL_H
