#ifndef STMARM_CONTROLPIO_A_GLOBAL_H
#define STMARM_CONTROLPIO_A_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef STMARM_CONTROLPIO_A_LIB
# define STMARM_CONTROLPIO_A_EXPORT Q_DECL_EXPORT
#else
# define STMARM_CONTROLPIO_A_EXPORT Q_DECL_IMPORT
#endif

#endif // STMARM_CONTROLPIO_A_GLOBAL_H
