#ifndef FILTERREVERSELENS_GLOBAL_H
#define FILTERREVERSELENS_GLOBAL_H

#include <qglobal.h>

#ifdef FILTERREVERSELENS_LIB
# define FILTERREVERSELENS_EXPORT Q_DECL_EXPORT
#else
# define FILTERREVERSELENS_EXPORT Q_DECL_IMPORT
#endif

#endif // FILTERREVERSELENS_GLOBAL_H
