#ifndef BUTTONTRANSFERSENDMASTERDATA_GLOBAL_H
#define BUTTONTRANSFERSENDMASTERDATA_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONTRANSFERSENDMASTERDATA_LIB
# define BUTTONTRANSFERSENDMASTERDATA_EXPORT Q_DECL_EXPORT
#else
# define BUTTONTRANSFERSENDMASTERDATA_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONTRANSFERSENDMASTERDATA_GLOBAL_H
