#ifndef PROPERTYSAVEPARTIALIMAGE_GLOBAL_H
#define PROPERTYSAVEPARTIALIMAGE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PROPERTYSAVEPARTIALIMAGE_LIB
# define PROPERTYSAVEPARTIALIMAGE_EXPORT Q_DECL_EXPORT
#else
# define PROPERTYSAVEPARTIALIMAGE_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTYSAVEPARTIALIMAGE_GLOBAL_H
