#ifndef INTEGRATIONSHOWCONNECTIONSTATE_GLOBAL_H
#define INTEGRATIONSHOWCONNECTIONSTATE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef INTEGRATIONSHOWCONNECTIONSTATE_LIB
# define INTEGRATIONSHOWCONNECTIONSTATE_EXPORT Q_DECL_EXPORT
#else
# define INTEGRATIONSHOWCONNECTIONSTATE_EXPORT Q_DECL_IMPORT
#endif

#endif // INTEGRATIONSHOWCONNECTIONSTATE_GLOBAL_H
