#ifndef GRAPHTRENDCOLORDIFFERENCE_GLOBAL_H
#define GRAPHTRENDCOLORDIFFERENCE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef GRAPHTRENDCOLORDIFFERENCE_LIB
# define GRAPHTRENDCOLORDIFFERENCE_EXPORT Q_DECL_EXPORT
#else
# define GRAPHTRENDCOLORDIFFERENCE_EXPORT Q_DECL_IMPORT
#endif

#endif // GRAPHTRENDCOLORDIFFERENCE_GLOBAL_H
