#ifndef USB_CONTROL8PIO_GLOBAL_H
#define USB_CONTROL8PIO_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef USB_CONTROL8PIO_LIB
# define USB_CONTROL8PIO_EXPORT Q_DECL_EXPORT
#else
# define USB_CONTROL8PIO_EXPORT Q_DECL_IMPORT
#endif

#endif // USB_CONTROL8PIO_GLOBAL_H
