# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = ShutDownDLL
DESTDIR = ../../../
CONFIG += release
DEFINES += SHUTDOWNDLL_LIB
LIBS += -L"./../../../Lib/Release" \
    -lServiceLib
DEPENDPATH += .
MOC_DIR += ./GeneratedFiles/$(ConfigurationName)
OBJECTS_DIR += release
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles
include(ShutDownDLL.pri)
