#ifndef CCSCONTROLBYPIO_GLOBAL_H
#define CCSCONTROLBYPIO_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef CCSCONTROLBYPIO_LIB
# define CCSCONTROLBYPIO_EXPORT Q_DECL_EXPORT
#else
# define CCSCONTROLBYPIO_EXPORT Q_DECL_IMPORT
#endif

#endif // CCSCONTROLBYPIO_GLOBAL_H
