#ifndef SHOWCURRENTOPINION_GLOBAL_H
#define SHOWCURRENTOPINION_GLOBAL_H

#include <qglobal.h>

#ifdef SHOWCURRENTOPINION_LIB
# define SHOWCURRENTOPINION_EXPORT Q_DECL_EXPORT
#else
# define SHOWCURRENTOPINION_EXPORT Q_DECL_IMPORT
#endif

#endif // SHOWCURRENTOPINION_GLOBAL_H
