#ifndef SHOWINSPECTIONNUMBER_GLOBAL_H
#define SHOWINSPECTIONNUMBER_GLOBAL_H

#include <qglobal.h>

#ifdef SHOWINSPECTIONNUMBER_LIB
# define SHOWINSPECTIONNUMBER_EXPORT Q_DECL_EXPORT
#else
# define SHOWINSPECTIONNUMBER_EXPORT Q_DECL_IMPORT
#endif

#endif // SHOWINSPECTIONNUMBER_GLOBAL_H
