# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = CameraXtiumPx8MonoLineTrigger
DESTDIR = ../x64/Release
CONFIG += release
DEFINES += CAMERAXTIUMPX8MONOLINETRIGGER_LIB
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles
include(CameraXtiumPx8MonoLineTrigger.pri)
