#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(CAMERAXTIUMPX8MONOLINETRIGGER_LIB)
#  define CAMERAXTIUMPX8MONOLINETRIGGER_EXPORT Q_DECL_EXPORT
# else
#  define CAMERAXTIUMPX8MONOLINETRIGGER_EXPORT Q_DECL_IMPORT
# endif
#else
# define CAMERAXTIUMPX8MONOLINETRIGGER_EXPORT
#endif
