#ifndef PROJECTEDINSPECTION_GLOBAL_H
#define PROJECTEDINSPECTION_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PROJECTEDINSPECTION_LIB
# define PROJECTEDINSPECTION_EXPORT Q_DECL_EXPORT
#else
# define PROJECTEDINSPECTION_EXPORT Q_DECL_IMPORT
#endif

#endif // PROJECTEDINSPECTION_GLOBAL_H
