#ifndef PROPERTYSWITCHPHASE_GLOBAL_H
#define PROPERTYSWITCHPHASE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PROPERTYSWITCHPHASE_LIB
# define PROPERTYSWITCHPHASE_EXPORT Q_DECL_EXPORT
#else
# define PROPERTYSWITCHPHASE_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTYSWITCHPHASE_GLOBAL_H
