# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = ShowMeasureHolePosResultList
DESTDIR = ../
CONFIG += release
DEFINES += SHOWMEASUREHOLEPOSRESULTLIST_LIB
LIBS += -L"./../../Lib/Release" \
    -lComponent \
    -lServiceLib \
    -lDisplayImage
DEPENDPATH += .
MOC_DIR += GeneratedFiles/$(ConfigurationName)
OBJECTS_DIR += release
UI_DIR += GeneratedFiles
RCC_DIR += GeneratedFiles
include(ShowMeasureHolePosResultList.pri)

FORMS += \
    ShowMeasureHolePosResultListForm.ui

HEADERS += \
    ShowMeasureHolePosResultListForm.h

SOURCES += \
    ShowMeasureHolePosResultListForm.cpp
