#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(SHOWMEASUREHOLEPOSRESULTLIST_LIB)
#  define SHOWMEASUREHOLEPOSRESULTLIST_EXPORT Q_DECL_EXPORT
# else
#  define SHOWMEASUREHOLEPOSRESULTLIST_EXPORT Q_DECL_IMPORT
# endif
#else
# define SHOWMEASUREHOLEPOSRESULTLIST_EXPORT
#endif
