#ifndef INTEGRATIONRESULTLIST_GLOBAL_H
#define INTEGRATIONRESULTLIST_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef INTEGRATIONRESULTLIST_LIB
# define INTEGRATIONRESULTLIST_EXPORT Q_DECL_EXPORT
#else
# define INTEGRATIONRESULTLIST_EXPORT Q_DECL_IMPORT
#endif

#endif // INTEGRATIONRESULTLIST_GLOBAL_H
