#ifndef FILTERVERTICALLINEAR_GLOBAL_H
#define FILTERVERTICALLINEAR_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef FILTERVERTICALLINEAR_LIB
# define FILTERVERTICALLINEAR_EXPORT Q_DECL_EXPORT
#else
# define FILTERVERTICALLINEAR_EXPORT Q_DECL_IMPORT
#endif

#endif // FILTERVERTICALLINEAR_GLOBAL_H
