# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./TrueColorBlockImagePanelResource.h \
    ./truecolorblockimagepanel_global.h \
    ../PropertyTrueColorBlock/XPropertyTrueColorBlockPacket.h \
    ./TrueColorBlockImagePanel.h
SOURCES += ../../Open/GUIDllCommon.cpp \
    ../../Open/SystemVersion.cpp \
    ./TrueColorBlockImagePanel.cpp \
    ../PropertyTrueColorBlock/XPropertyTrueColorBlockPacket.cpp \
    ./TrueColorBlockImagePanelResource.cpp
RESOURCES += TrueColorBlockImagePanel.qrc
