#ifndef BUTTONAUTOGENERATEMEASURELINEMOVE_GLOBAL_H
#define BUTTONAUTOGENERATEMEASURELINEMOVE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONAUTOGENERATEMEASURELINEMOVE_LIB
# define BUTTONAUTOGENERATEMEASURELINEMOVE_EXPORT Q_DECL_EXPORT
#else
# define BUTTONAUTOGENERATEMEASURELINEMOVE_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONAUTOGENERATEMEASURELINEMOVE_GLOBAL_H
