#ifndef SHOWIMAGELIST_GLOBAL_H
#define SHOWIMAGELIST_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SHOWIMAGELIST_LIB
# define SHOWIMAGELIST_EXPORT Q_DECL_EXPORT
#else
# define SHOWIMAGELIST_EXPORT Q_DECL_IMPORT
#endif

#endif // SHOWIMAGELIST_GLOBAL_H
