#ifndef LEDCONTROL16A_GLOBAL_H
#define LEDCONTROL16A_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef LEDCONTROL16A_LIB
# define LEDCONTROL16A_EXPORT Q_DECL_EXPORT
#else
# define LEDCONTROL16A_EXPORT Q_DECL_IMPORT
#endif

#endif // LEDCONTROL16A_GLOBAL_H
