#ifndef CHANGECAMERASETTING_GLOBAL_H
#define CHANGECAMERASETTING_GLOBAL_H

#include <qglobal.h>

#ifdef CHANGECAMERASETTING_LIB
# define CHANGECAMERASETTING_EXPORT Q_DECL_EXPORT
#else
# define CHANGECAMERASETTING_EXPORT Q_DECL_IMPORT
#endif

#endif // CHANGECAMERASETTING_GLOBAL_H
