#ifndef LISTBOXUNCOVEREDAREA_GLOBAL_H
#define LISTBOXUNCOVEREDAREA_GLOBAL_H

#include <qglobal.h>

#ifdef LISTBOXUNCOVEREDAREA_LIB
# define LISTBOXUNCOVEREDAREA_EXPORT Q_DECL_EXPORT
#else
# define LISTBOXUNCOVEREDAREA_EXPORT Q_DECL_IMPORT
#endif

#endif // LISTBOXUNCOVEREDAREA_GLOBAL_H
