#ifndef PROPERTYVIAINSPECTION_GLOBAL_H
#define PROPERTYVIAINSPECTION_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PROPERTYVIAINSPECTION_LIB
# define PROPERTYVIAINSPECTION_EXPORT Q_DECL_EXPORT
#else
# define PROPERTYVIAINSPECTION_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTYVIAINSPECTION_GLOBAL_H
