#ifndef PROPERTYPROCESS3D_GLOBAL_H
#define PROPERTYPROCESS3D_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PROPERTYPROCESS3D_LIB
# define PROPERTYPROCESS3D_EXPORT Q_DECL_EXPORT
#else
# define PROPERTYPROCESS3D_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTYPROCESS3D_GLOBAL_H
