#ifndef NETWORKSIOCLIENTLIB_GLOBAL_H
#define NETWORKSIOCLIENTLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef NETWORKSIOCLIENTLIB_LIB
# define NETWORKSIOCLIENTLIB_EXPORT Q_DECL_EXPORT
#else
# define NETWORKSIOCLIENTLIB_EXPORT Q_DECL_IMPORT
#endif

#endif // NETWORKSIOCLIENTLIB_GLOBAL_H
