#ifndef SHOWFILELISTBROWSER_GLOBAL_H
#define SHOWFILELISTBROWSER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SHOWFILELISTBROWSER_LIB
# define SHOWFILELISTBROWSER_EXPORT Q_DECL_EXPORT
#else
# define SHOWFILELISTBROWSER_EXPORT Q_DECL_IMPORT
#endif

#endif // SHOWFILELISTBROWSER_GLOBAL_H
