#ifndef VIAINSPECTION_GLOBAL_H
#define VIAINSPECTION_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef VIAINSPECTION_LIB
# define VIAINSPECTION_EXPORT Q_DECL_EXPORT
#else
# define VIAINSPECTION_EXPORT Q_DECL_IMPORT
#endif

#endif // VIAINSPECTION_GLOBAL_H
