#ifndef FILTERREVERSELENSONESIDE2_GLOBAL_H
#define FILTERREVERSELENSONESIDE2_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef FILTERREVERSELENSONESIDE2_LIB
# define FILTERREVERSELENSONESIDE2_EXPORT Q_DECL_EXPORT
#else
# define FILTERREVERSELENSONESIDE2_EXPORT Q_DECL_IMPORT
#endif

#endif // FILTERREVERSELENSONESIDE2_GLOBAL_H
