#ifndef EASYDOTCOLORMATCHIMAGEPANEL_GLOBAL_H
#define EASYDOTCOLORMATCHIMAGEPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef EASYDOTCOLORMATCHIMAGEPANEL_LIB
# define EASYDOTCOLORMATCHIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define EASYDOTCOLORMATCHIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // EASYDOTCOLORMATCHIMAGEPANEL_GLOBAL_H
