#ifndef OCRINSPECTION_GLOBAL_H
#define OCRINSPECTION_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef OCRINSPECTION_LIB
# define OCRINSPECTION_EXPORT Q_DECL_EXPORT
#else
# define OCRINSPECTION_EXPORT Q_DECL_IMPORT
#endif

#endif // OCRINSPECTION_GLOBAL_H
