#ifndef SETOUTLINEOFFSET_GLOBAL_H
#define SETOUTLINEOFFSET_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SETOUTLINEOFFSET_LIB
# define SETOUTLINEOFFSET_EXPORT Q_DECL_EXPORT
#else
# define SETOUTLINEOFFSET_EXPORT Q_DECL_IMPORT
#endif

#endif // SETOUTLINEOFFSET_GLOBAL_H
