#ifndef SHOWREVIEWMASTERNAME_GLOBAL_H
#define SHOWREVIEWMASTERNAME_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SHOWREVIEWMASTERNAME_LIB
# define SHOWREVIEWMASTERNAME_EXPORT Q_DECL_EXPORT
#else
# define SHOWREVIEWMASTERNAME_EXPORT Q_DECL_IMPORT
#endif

#endif // SHOWREVIEWMASTERNAME_GLOBAL_H
