# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = IOLogger
DESTDIR = ../../
CONFIG += release
DEFINES += IOLOGGER_LIB
LIBS += -L"./../../../Lib/Release" \
    -lServiceLib \
    -lSeqLib
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles
include(IOLogger.pri)
