#ifndef DISPLAYTHUMBNAILIMAGE_GLOBAL_H
#define DISPLAYTHUMBNAILIMAGE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef DISPLAYTHUMBNAILIMAGE_LIB
# define DISPLAYTHUMBNAILIMAGE_EXPORT Q_DECL_EXPORT
#else
# define DISPLAYTHUMBNAILIMAGE_EXPORT Q_DECL_IMPORT
#endif

#endif // DISPLAYTHUMBNAILIMAGE_GLOBAL_H
