#ifndef DUSTREDUCERAI_GLOBAL_H
#define DUSTREDUCERAI_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef DUSTREDUCERAI_LIB
# define DUSTREDUCERAI_EXPORT Q_DECL_EXPORT
#else
# define DUSTREDUCERAI_EXPORT Q_DECL_IMPORT
#endif

#endif // DUSTREDUCERAI_GLOBAL_H
