#ifndef DOTCOLORMATCHINGIMAGEPANEL_GLOBAL_H
#define DOTCOLORMATCHINGIMAGEPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef DOTCOLORMATCHINGIMAGEPANEL_LIB
# define DOTCOLORMATCHINGIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define DOTCOLORMATCHINGIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // DOTCOLORMATCHINGIMAGEPANEL_GLOBAL_H
