#ifndef ZOOMMECHANICALPANEL_GLOBAL_H
#define ZOOMMECHANICALPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef ZOOMMECHANICALPANEL_LIB
# define ZOOMMECHANICALPANEL_EXPORT Q_DECL_EXPORT
#else
# define ZOOMMECHANICALPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // ZOOMMECHANICALPANEL_GLOBAL_H
