/********************************************************************************
** Form generated from reading UI file 'EditStatisticBlockLibrary.ui'
**
** Created by: Qt User Interface Compiler version 6.10.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_EDITSTATISTICBLOCKLIBRARY_H
#define UI_EDITSTATISTICBLOCKLIBRARY_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDialog>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QToolButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_EditStatisticBlockLibraryClass
{
public:
    QStackedWidget *stackedWidget;
    QWidget *page;
    QFrame *frame_3;
    QSpinBox *EditMinBlockSize;
    QLabel *label_9;
    QSpinBox *EditMaxBlockSize;
    QLabel *label_10;
    QSpinBox *EditMinBlockDots;
    QLabel *label_12;
    QSpinBox *EditMaxBlockDots;
    QLabel *label_11;
    QLabel *label_13;
    QSpinBox *EditLimitBlockSize;
    QLabel *label_32;
    QFrame *frame_5;
    QLabel *label_36;
    QComboBox *comboBGenerationCategory;
    QCheckBox *checkBTransparent;
    QCheckBox *checkBLeftPickup;
    QCheckBox *checkBOverlappedGen;
    QFrame *frame_2;
    QLabel *label_7;
    QSpinBox *EditPickupL;
    QLabel *label_8;
    QSpinBox *EditPickupH;
    QLabel *label_30;
    QFrame *frame_4;
    QLabel *label_14;
    QSpinBox *EditSpaceToOutline;
    QLabel *label_15;
    QSpinBox *EditNoiseSize;
    QLabel *label_16;
    QSpinBox *EditPriority;
    QLabel *label_33;
    QLabel *label_21;
    QSpinBox *EditOverlapDot;
    QWidget *page_3;
    QFrame *frame_6;
    QLabel *label_35;
    QLabel *label_20;
    QLabel *label_17;
    QSpinBox *EditOKDotH;
    QLabel *label_18;
    QSpinBox *EditOKDotL;
    QLabel *label_19;
    QLabel *label_29;
    QSpinBox *EditOKLengthL;
    QSpinBox *EditOKLengthH;
    QLineEdit *EditBrightWidthL;
    QLineEdit *EditBrightWidthH;
    QFrame *frame_9;
    QLabel *label_39;
    QFrame *frame_10;
    QLabel *label_40;
    QCheckBox *checkBModeAbsoluteBright;
    QCheckBox *checkBModeNGCluster;
    QCheckBox *checkBModeBlackMask;
    QCheckBox *checkBModeEnabled;
    QCheckBox *checkBModeWhiteMask;
    QFrame *frame_11;
    QLabel *label_41;
    QFrame *frame_12;
    QLabel *label_42;
    QSpinBox *EditAdjustBlack;
    QSpinBox *EditAdjustWhite;
    QLabel *label_26;
    QLabel *label_25;
    QFrame *frame_13;
    QLabel *label_45;
    QFrame *frame_15;
    QLabel *label_46;
    QCheckBox *checkEliminateAcnode;
    QCheckBox *checkUseMorphology;
    QLabel *label_27;
    QSpinBox *EditErosionDotCount;
    QSpinBox *EditDilationDotCount;
    QLabel *label_28;
    QComboBox *comboBoxMorphologyApplyTo;
    QLabel *label;
    QWidget *page_2;
    QToolButton *toolButtonInspect;
    QTableWidget *tableWidgetLibList;
    QLineEdit *EditLibID;
    QToolButton *toolButtonPickup;
    QFrame *frameLibFolder;
    QLabel *label_4;
    QLineEdit *EditLibName;
    QPushButton *ButtonLibDelete;
    QPushButton *ButtonLibNew;
    QPushButton *ButtonLibSave;
    QPushButton *ButtonLibSaveNew;
    QPushButton *pushButton;

    void setupUi(QDialog *EditStatisticBlockLibraryClass)
    {
        if (EditStatisticBlockLibraryClass->objectName().isEmpty())
            EditStatisticBlockLibraryClass->setObjectName("EditStatisticBlockLibraryClass");
        EditStatisticBlockLibraryClass->resize(633, 570);
        stackedWidget = new QStackedWidget(EditStatisticBlockLibraryClass);
        stackedWidget->setObjectName("stackedWidget");
        stackedWidget->setGeometry(QRect(250, 90, 381, 401));
        page = new QWidget();
        page->setObjectName("page");
        frame_3 = new QFrame(page);
        frame_3->setObjectName("frame_3");
        frame_3->setGeometry(QRect(0, 70, 371, 141));
        frame_3->setFrameShape(QFrame::StyledPanel);
        frame_3->setFrameShadow(QFrame::Sunken);
        EditMinBlockSize = new QSpinBox(frame_3);
        EditMinBlockSize->setObjectName("EditMinBlockSize");
        EditMinBlockSize->setGeometry(QRect(150, 10, 81, 22));
        EditMinBlockSize->setMaximum(1000000);
        label_9 = new QLabel(frame_3);
        label_9->setObjectName("label_9");
        label_9->setGeometry(QRect(30, 30, 111, 21));
        label_9->setFrameShape(QFrame::Panel);
        label_9->setFrameShadow(QFrame::Sunken);
        label_9->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditMaxBlockSize = new QSpinBox(frame_3);
        EditMaxBlockSize->setObjectName("EditMaxBlockSize");
        EditMaxBlockSize->setGeometry(QRect(150, 30, 81, 22));
        EditMaxBlockSize->setMaximum(1000000);
        label_10 = new QLabel(frame_3);
        label_10->setObjectName("label_10");
        label_10->setGeometry(QRect(30, 10, 111, 21));
        label_10->setFrameShape(QFrame::Panel);
        label_10->setFrameShadow(QFrame::Sunken);
        label_10->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditMinBlockDots = new QSpinBox(frame_3);
        EditMinBlockDots->setObjectName("EditMinBlockDots");
        EditMinBlockDots->setGeometry(QRect(150, 60, 101, 22));
        EditMinBlockDots->setMaximum(2000000000);
        label_12 = new QLabel(frame_3);
        label_12->setObjectName("label_12");
        label_12->setGeometry(QRect(30, 60, 111, 21));
        label_12->setFrameShape(QFrame::Panel);
        label_12->setFrameShadow(QFrame::Sunken);
        label_12->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditMaxBlockDots = new QSpinBox(frame_3);
        EditMaxBlockDots->setObjectName("EditMaxBlockDots");
        EditMaxBlockDots->setGeometry(QRect(150, 80, 101, 22));
        EditMaxBlockDots->setMaximum(2000000000);
        EditMaxBlockDots->setValue(2000000000);
        label_11 = new QLabel(frame_3);
        label_11->setObjectName("label_11");
        label_11->setGeometry(QRect(30, 80, 111, 21));
        label_11->setFrameShape(QFrame::Panel);
        label_11->setFrameShadow(QFrame::Sunken);
        label_11->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_13 = new QLabel(frame_3);
        label_13->setObjectName("label_13");
        label_13->setGeometry(QRect(30, 110, 111, 21));
        label_13->setFrameShape(QFrame::Panel);
        label_13->setFrameShadow(QFrame::Sunken);
        label_13->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditLimitBlockSize = new QSpinBox(frame_3);
        EditLimitBlockSize->setObjectName("EditLimitBlockSize");
        EditLimitBlockSize->setGeometry(QRect(150, 110, 61, 22));
        EditLimitBlockSize->setMaximum(99999);
        label_32 = new QLabel(frame_3);
        label_32->setObjectName("label_32");
        label_32->setGeometry(QRect(0, 0, 20, 141));
        label_32->setFrameShape(QFrame::Panel);
        label_32->setFrameShadow(QFrame::Raised);
        label_32->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_32->setIndent(1);
        frame_5 = new QFrame(page);
        frame_5->setObjectName("frame_5");
        frame_5->setGeometry(QRect(0, 310, 371, 81));
        frame_5->setFrameShape(QFrame::StyledPanel);
        frame_5->setFrameShadow(QFrame::Sunken);
        label_36 = new QLabel(frame_5);
        label_36->setObjectName("label_36");
        label_36->setGeometry(QRect(0, 0, 20, 81));
        label_36->setFrameShape(QFrame::Panel);
        label_36->setFrameShadow(QFrame::Raised);
        label_36->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_36->setIndent(1);
        comboBGenerationCategory = new QComboBox(frame_5);
        comboBGenerationCategory->addItem(QString());
        comboBGenerationCategory->addItem(QString());
        comboBGenerationCategory->addItem(QString());
        comboBGenerationCategory->addItem(QString());
        comboBGenerationCategory->addItem(QString());
        comboBGenerationCategory->addItem(QString());
        comboBGenerationCategory->addItem(QString());
        comboBGenerationCategory->addItem(QString());
        comboBGenerationCategory->setObjectName("comboBGenerationCategory");
        comboBGenerationCategory->setGeometry(QRect(30, 10, 111, 22));
        checkBTransparent = new QCheckBox(frame_5);
        checkBTransparent->setObjectName("checkBTransparent");
        checkBTransparent->setGeometry(QRect(160, 10, 161, 18));
        checkBLeftPickup = new QCheckBox(frame_5);
        checkBLeftPickup->setObjectName("checkBLeftPickup");
        checkBLeftPickup->setGeometry(QRect(160, 30, 161, 18));
        checkBOverlappedGen = new QCheckBox(frame_5);
        checkBOverlappedGen->setObjectName("checkBOverlappedGen");
        checkBOverlappedGen->setGeometry(QRect(160, 50, 161, 18));
        frame_2 = new QFrame(page);
        frame_2->setObjectName("frame_2");
        frame_2->setGeometry(QRect(0, 0, 371, 61));
        frame_2->setFrameShape(QFrame::StyledPanel);
        frame_2->setFrameShadow(QFrame::Sunken);
        label_7 = new QLabel(frame_2);
        label_7->setObjectName("label_7");
        label_7->setGeometry(QRect(30, 10, 111, 21));
        label_7->setFrameShape(QFrame::Panel);
        label_7->setFrameShadow(QFrame::Sunken);
        label_7->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditPickupL = new QSpinBox(frame_2);
        EditPickupL->setObjectName("EditPickupL");
        EditPickupL->setGeometry(QRect(150, 10, 61, 22));
        EditPickupL->setMaximum(255);
        label_8 = new QLabel(frame_2);
        label_8->setObjectName("label_8");
        label_8->setGeometry(QRect(30, 30, 111, 21));
        label_8->setFrameShape(QFrame::Panel);
        label_8->setFrameShadow(QFrame::Sunken);
        label_8->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditPickupH = new QSpinBox(frame_2);
        EditPickupH->setObjectName("EditPickupH");
        EditPickupH->setGeometry(QRect(150, 30, 61, 22));
        EditPickupH->setMaximum(255);
        label_30 = new QLabel(frame_2);
        label_30->setObjectName("label_30");
        label_30->setGeometry(QRect(0, 0, 20, 61));
        label_30->setFrameShape(QFrame::Panel);
        label_30->setFrameShadow(QFrame::Raised);
        label_30->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_30->setIndent(1);
        frame_4 = new QFrame(page);
        frame_4->setObjectName("frame_4");
        frame_4->setGeometry(QRect(0, 220, 371, 81));
        frame_4->setFrameShape(QFrame::StyledPanel);
        frame_4->setFrameShadow(QFrame::Sunken);
        label_14 = new QLabel(frame_4);
        label_14->setObjectName("label_14");
        label_14->setGeometry(QRect(30, 10, 111, 21));
        label_14->setFrameShape(QFrame::Panel);
        label_14->setFrameShadow(QFrame::Sunken);
        label_14->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditSpaceToOutline = new QSpinBox(frame_4);
        EditSpaceToOutline->setObjectName("EditSpaceToOutline");
        EditSpaceToOutline->setGeometry(QRect(150, 10, 61, 23));
        label_15 = new QLabel(frame_4);
        label_15->setObjectName("label_15");
        label_15->setGeometry(QRect(30, 30, 111, 21));
        label_15->setFrameShape(QFrame::Panel);
        label_15->setFrameShadow(QFrame::Sunken);
        label_15->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditNoiseSize = new QSpinBox(frame_4);
        EditNoiseSize->setObjectName("EditNoiseSize");
        EditNoiseSize->setGeometry(QRect(150, 30, 61, 23));
        QFont font;
        font.setPointSize(9);
        EditNoiseSize->setFont(font);
        label_16 = new QLabel(frame_4);
        label_16->setObjectName("label_16");
        label_16->setGeometry(QRect(30, 50, 111, 21));
        label_16->setFrameShape(QFrame::Panel);
        label_16->setFrameShadow(QFrame::Sunken);
        label_16->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditPriority = new QSpinBox(frame_4);
        EditPriority->setObjectName("EditPriority");
        EditPriority->setGeometry(QRect(150, 50, 61, 23));
        EditPriority->setFont(font);
        label_33 = new QLabel(frame_4);
        label_33->setObjectName("label_33");
        label_33->setGeometry(QRect(0, 0, 20, 101));
        label_33->setFrameShape(QFrame::Panel);
        label_33->setFrameShadow(QFrame::Raised);
        label_33->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_33->setIndent(1);
        label_21 = new QLabel(frame_4);
        label_21->setObjectName("label_21");
        label_21->setGeometry(QRect(240, 10, 111, 21));
        label_21->setFrameShape(QFrame::Panel);
        label_21->setFrameShadow(QFrame::Sunken);
        label_21->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditOverlapDot = new QSpinBox(frame_4);
        EditOverlapDot->setObjectName("EditOverlapDot");
        EditOverlapDot->setGeometry(QRect(290, 40, 61, 23));
        EditOverlapDot->setFont(font);
        stackedWidget->addWidget(page);
        page_3 = new QWidget();
        page_3->setObjectName("page_3");
        frame_6 = new QFrame(page_3);
        frame_6->setObjectName("frame_6");
        frame_6->setGeometry(QRect(0, 0, 371, 101));
        frame_6->setFrameShape(QFrame::StyledPanel);
        frame_6->setFrameShadow(QFrame::Sunken);
        label_35 = new QLabel(frame_6);
        label_35->setObjectName("label_35");
        label_35->setGeometry(QRect(0, 0, 20, 101));
        label_35->setFrameShape(QFrame::Panel);
        label_35->setFrameShadow(QFrame::Raised);
        label_35->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_35->setIndent(1);
        label_20 = new QLabel(frame_6);
        label_20->setObjectName("label_20");
        label_20->setGeometry(QRect(250, 10, 81, 21));
        label_20->setFrameShape(QFrame::Panel);
        label_20->setFrameShadow(QFrame::Sunken);
        label_20->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_17 = new QLabel(frame_6);
        label_17->setObjectName("label_17");
        label_17->setGeometry(QRect(30, 30, 121, 21));
        label_17->setFrameShape(QFrame::Panel);
        label_17->setFrameShadow(QFrame::Sunken);
        label_17->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditOKDotH = new QSpinBox(frame_6);
        EditOKDotH->setObjectName("EditOKDotH");
        EditOKDotH->setGeometry(QRect(250, 50, 81, 22));
        EditOKDotH->setMaximum(99999999);
        label_18 = new QLabel(frame_6);
        label_18->setObjectName("label_18");
        label_18->setGeometry(QRect(30, 50, 121, 21));
        label_18->setFrameShape(QFrame::Panel);
        label_18->setFrameShadow(QFrame::Sunken);
        label_18->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditOKDotL = new QSpinBox(frame_6);
        EditOKDotL->setObjectName("EditOKDotL");
        EditOKDotL->setGeometry(QRect(160, 50, 81, 22));
        EditOKDotL->setMaximum(99999999);
        label_19 = new QLabel(frame_6);
        label_19->setObjectName("label_19");
        label_19->setGeometry(QRect(160, 10, 81, 21));
        label_19->setFrameShape(QFrame::Panel);
        label_19->setFrameShadow(QFrame::Sunken);
        label_19->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_29 = new QLabel(frame_6);
        label_29->setObjectName("label_29");
        label_29->setGeometry(QRect(30, 70, 121, 21));
        label_29->setFrameShape(QFrame::Panel);
        label_29->setFrameShadow(QFrame::Sunken);
        label_29->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditOKLengthL = new QSpinBox(frame_6);
        EditOKLengthL->setObjectName("EditOKLengthL");
        EditOKLengthL->setGeometry(QRect(160, 70, 81, 22));
        EditOKLengthL->setMaximum(99999999);
        EditOKLengthH = new QSpinBox(frame_6);
        EditOKLengthH->setObjectName("EditOKLengthH");
        EditOKLengthH->setGeometry(QRect(250, 70, 81, 22));
        EditOKLengthH->setMaximum(99999999);
        EditBrightWidthL = new QLineEdit(frame_6);
        EditBrightWidthL->setObjectName("EditBrightWidthL");
        EditBrightWidthL->setGeometry(QRect(160, 30, 81, 20));
        EditBrightWidthH = new QLineEdit(frame_6);
        EditBrightWidthH->setObjectName("EditBrightWidthH");
        EditBrightWidthH->setGeometry(QRect(250, 30, 81, 20));
        frame_9 = new QFrame(page_3);
        frame_9->setObjectName("frame_9");
        frame_9->setGeometry(QRect(0, 200, 371, 71));
        frame_9->setFrameShape(QFrame::StyledPanel);
        frame_9->setFrameShadow(QFrame::Sunken);
        label_39 = new QLabel(frame_9);
        label_39->setObjectName("label_39");
        label_39->setGeometry(QRect(0, 0, 20, 71));
        label_39->setFrameShape(QFrame::Panel);
        label_39->setFrameShadow(QFrame::Raised);
        label_39->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_39->setIndent(1);
        frame_10 = new QFrame(frame_9);
        frame_10->setObjectName("frame_10");
        frame_10->setGeometry(QRect(10, 120, 371, 101));
        frame_10->setFrameShape(QFrame::StyledPanel);
        frame_10->setFrameShadow(QFrame::Sunken);
        label_40 = new QLabel(frame_10);
        label_40->setObjectName("label_40");
        label_40->setGeometry(QRect(0, 0, 20, 61));
        label_40->setFrameShape(QFrame::Panel);
        label_40->setFrameShadow(QFrame::Raised);
        label_40->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_40->setIndent(1);
        checkBModeAbsoluteBright = new QCheckBox(frame_9);
        checkBModeAbsoluteBright->setObjectName("checkBModeAbsoluteBright");
        checkBModeAbsoluteBright->setGeometry(QRect(30, 30, 141, 18));
        checkBModeNGCluster = new QCheckBox(frame_9);
        checkBModeNGCluster->setObjectName("checkBModeNGCluster");
        checkBModeNGCluster->setGeometry(QRect(30, 50, 141, 18));
        checkBModeBlackMask = new QCheckBox(frame_9);
        checkBModeBlackMask->setObjectName("checkBModeBlackMask");
        checkBModeBlackMask->setGeometry(QRect(190, 50, 141, 18));
        checkBModeEnabled = new QCheckBox(frame_9);
        checkBModeEnabled->setObjectName("checkBModeEnabled");
        checkBModeEnabled->setGeometry(QRect(30, 10, 141, 18));
        checkBModeWhiteMask = new QCheckBox(frame_9);
        checkBModeWhiteMask->setObjectName("checkBModeWhiteMask");
        checkBModeWhiteMask->setGeometry(QRect(190, 30, 141, 18));
        frame_11 = new QFrame(page_3);
        frame_11->setObjectName("frame_11");
        frame_11->setGeometry(QRect(0, 280, 371, 71));
        frame_11->setFrameShape(QFrame::StyledPanel);
        frame_11->setFrameShadow(QFrame::Sunken);
        label_41 = new QLabel(frame_11);
        label_41->setObjectName("label_41");
        label_41->setGeometry(QRect(0, 0, 20, 71));
        label_41->setFrameShape(QFrame::Panel);
        label_41->setFrameShadow(QFrame::Raised);
        label_41->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_41->setIndent(1);
        frame_12 = new QFrame(frame_11);
        frame_12->setObjectName("frame_12");
        frame_12->setGeometry(QRect(10, 120, 371, 101));
        frame_12->setFrameShape(QFrame::StyledPanel);
        frame_12->setFrameShadow(QFrame::Sunken);
        label_42 = new QLabel(frame_12);
        label_42->setObjectName("label_42");
        label_42->setGeometry(QRect(0, 0, 20, 61));
        label_42->setFrameShape(QFrame::Panel);
        label_42->setFrameShadow(QFrame::Raised);
        label_42->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_42->setIndent(1);
        EditAdjustBlack = new QSpinBox(frame_11);
        EditAdjustBlack->setObjectName("EditAdjustBlack");
        EditAdjustBlack->setGeometry(QRect(240, 10, 81, 22));
        EditAdjustBlack->setMaximum(255);
        EditAdjustWhite = new QSpinBox(frame_11);
        EditAdjustWhite->setObjectName("EditAdjustWhite");
        EditAdjustWhite->setGeometry(QRect(240, 40, 81, 22));
        EditAdjustWhite->setMaximum(255);
        label_26 = new QLabel(frame_11);
        label_26->setObjectName("label_26");
        label_26->setGeometry(QRect(30, 40, 201, 21));
        label_26->setFrameShape(QFrame::Panel);
        label_26->setFrameShadow(QFrame::Sunken);
        label_26->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_25 = new QLabel(frame_11);
        label_25->setObjectName("label_25");
        label_25->setGeometry(QRect(30, 10, 201, 21));
        label_25->setFrameShape(QFrame::Panel);
        label_25->setFrameShadow(QFrame::Sunken);
        label_25->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        frame_13 = new QFrame(page_3);
        frame_13->setObjectName("frame_13");
        frame_13->setGeometry(QRect(0, 110, 371, 81));
        frame_13->setFrameShape(QFrame::StyledPanel);
        frame_13->setFrameShadow(QFrame::Sunken);
        label_45 = new QLabel(frame_13);
        label_45->setObjectName("label_45");
        label_45->setGeometry(QRect(0, 0, 20, 81));
        label_45->setFrameShape(QFrame::Panel);
        label_45->setFrameShadow(QFrame::Raised);
        label_45->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_45->setIndent(1);
        frame_15 = new QFrame(frame_13);
        frame_15->setObjectName("frame_15");
        frame_15->setGeometry(QRect(10, 120, 371, 101));
        frame_15->setFrameShape(QFrame::StyledPanel);
        frame_15->setFrameShadow(QFrame::Sunken);
        label_46 = new QLabel(frame_15);
        label_46->setObjectName("label_46");
        label_46->setGeometry(QRect(0, 0, 20, 61));
        label_46->setFrameShape(QFrame::Panel);
        label_46->setFrameShadow(QFrame::Raised);
        label_46->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_46->setIndent(1);
        checkEliminateAcnode = new QCheckBox(frame_13);
        checkEliminateAcnode->setObjectName("checkEliminateAcnode");
        checkEliminateAcnode->setEnabled(false);
        checkEliminateAcnode->setGeometry(QRect(170, 10, 191, 20));
        checkUseMorphology = new QCheckBox(frame_13);
        checkUseMorphology->setObjectName("checkUseMorphology");
        checkUseMorphology->setGeometry(QRect(30, 10, 111, 18));
        label_27 = new QLabel(frame_13);
        label_27->setObjectName("label_27");
        label_27->setGeometry(QRect(170, 30, 131, 21));
        label_27->setFrameShape(QFrame::Panel);
        label_27->setFrameShadow(QFrame::Sunken);
        label_27->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditErosionDotCount = new QSpinBox(frame_13);
        EditErosionDotCount->setObjectName("EditErosionDotCount");
        EditErosionDotCount->setEnabled(false);
        EditErosionDotCount->setGeometry(QRect(310, 50, 51, 22));
        EditErosionDotCount->setMaximum(255);
        EditDilationDotCount = new QSpinBox(frame_13);
        EditDilationDotCount->setObjectName("EditDilationDotCount");
        EditDilationDotCount->setEnabled(false);
        EditDilationDotCount->setGeometry(QRect(310, 30, 51, 22));
        EditDilationDotCount->setMaximum(255);
        label_28 = new QLabel(frame_13);
        label_28->setObjectName("label_28");
        label_28->setGeometry(QRect(170, 50, 131, 21));
        label_28->setFrameShape(QFrame::Panel);
        label_28->setFrameShadow(QFrame::Sunken);
        label_28->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        comboBoxMorphologyApplyTo = new QComboBox(frame_13);
        comboBoxMorphologyApplyTo->addItem(QString());
        comboBoxMorphologyApplyTo->addItem(QString());
        comboBoxMorphologyApplyTo->addItem(QString());
        comboBoxMorphologyApplyTo->setObjectName("comboBoxMorphologyApplyTo");
        comboBoxMorphologyApplyTo->setEnabled(false);
        comboBoxMorphologyApplyTo->setGeometry(QRect(30, 50, 131, 22));
        label = new QLabel(frame_13);
        label->setObjectName("label");
        label->setGeometry(QRect(30, 30, 131, 16));
        stackedWidget->addWidget(page_3);
        page_2 = new QWidget();
        page_2->setObjectName("page_2");
        stackedWidget->addWidget(page_2);
        toolButtonInspect = new QToolButton(EditStatisticBlockLibraryClass);
        toolButtonInspect->setObjectName("toolButtonInspect");
        toolButtonInspect->setGeometry(QRect(470, 10, 141, 31));
        toolButtonInspect->setCheckable(true);
        toolButtonInspect->setAutoExclusive(true);
        tableWidgetLibList = new QTableWidget(EditStatisticBlockLibraryClass);
        if (tableWidgetLibList->columnCount() < 2)
            tableWidgetLibList->setColumnCount(2);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        tableWidgetLibList->setHorizontalHeaderItem(0, __qtablewidgetitem);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        tableWidgetLibList->setHorizontalHeaderItem(1, __qtablewidgetitem1);
        tableWidgetLibList->setObjectName("tableWidgetLibList");
        tableWidgetLibList->setGeometry(QRect(10, 270, 221, 211));
        tableWidgetLibList->setSelectionMode(QAbstractItemView::SingleSelection);
        tableWidgetLibList->setSelectionBehavior(QAbstractItemView::SelectRows);
        EditLibID = new QLineEdit(EditStatisticBlockLibraryClass);
        EditLibID->setObjectName("EditLibID");
        EditLibID->setEnabled(false);
        EditLibID->setGeometry(QRect(300, 50, 81, 31));
        QFont font1;
        font1.setPointSize(12);
        EditLibID->setFont(font1);
        EditLibID->setReadOnly(true);
        toolButtonPickup = new QToolButton(EditStatisticBlockLibraryClass);
        toolButtonPickup->setObjectName("toolButtonPickup");
        toolButtonPickup->setGeometry(QRect(250, 10, 141, 31));
        toolButtonPickup->setCheckable(true);
        toolButtonPickup->setChecked(true);
        toolButtonPickup->setAutoExclusive(true);
        frameLibFolder = new QFrame(EditStatisticBlockLibraryClass);
        frameLibFolder->setObjectName("frameLibFolder");
        frameLibFolder->setGeometry(QRect(10, 50, 221, 201));
        frameLibFolder->setFrameShape(QFrame::StyledPanel);
        frameLibFolder->setFrameShadow(QFrame::Sunken);
        label_4 = new QLabel(EditStatisticBlockLibraryClass);
        label_4->setObjectName("label_4");
        label_4->setGeometry(QRect(250, 50, 51, 31));
        label_4->setFont(font1);
        label_4->setFrameShape(QFrame::Panel);
        label_4->setFrameShadow(QFrame::Sunken);
        label_4->setAlignment(Qt::AlignCenter|Qt::AlignHCenter|Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EditLibName = new QLineEdit(EditStatisticBlockLibraryClass);
        EditLibName->setObjectName("EditLibName");
        EditLibName->setGeometry(QRect(380, 50, 211, 31));
        EditLibName->setFont(font1);
        ButtonLibDelete = new QPushButton(EditStatisticBlockLibraryClass);
        ButtonLibDelete->setObjectName("ButtonLibDelete");
        ButtonLibDelete->setGeometry(QRect(350, 490, 81, 31));
        QFont font2;
        font2.setPointSize(11);
        ButtonLibDelete->setFont(font2);
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/Qtres/Delete.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        ButtonLibDelete->setIcon(icon);
        ButtonLibNew = new QPushButton(EditStatisticBlockLibraryClass);
        ButtonLibNew->setObjectName("ButtonLibNew");
        ButtonLibNew->setGeometry(QRect(250, 490, 91, 31));
        ButtonLibNew->setFont(font2);
        QIcon icon1;
        icon1.addFile(QString::fromUtf8(":/Qtres/ClearNew.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        ButtonLibNew->setIcon(icon1);
        ButtonLibSave = new QPushButton(EditStatisticBlockLibraryClass);
        ButtonLibSave->setObjectName("ButtonLibSave");
        ButtonLibSave->setGeometry(QRect(540, 490, 81, 31));
        ButtonLibSave->setFont(font2);
        QIcon icon2;
        icon2.addFile(QString::fromUtf8(":/Qtres/Update.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        ButtonLibSave->setIcon(icon2);
        ButtonLibSaveNew = new QPushButton(EditStatisticBlockLibraryClass);
        ButtonLibSaveNew->setObjectName("ButtonLibSaveNew");
        ButtonLibSaveNew->setGeometry(QRect(440, 490, 91, 31));
        ButtonLibSaveNew->setFont(font2);
        QIcon icon3;
        icon3.addFile(QString::fromUtf8(":/Qtres/SaveNew.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        ButtonLibSaveNew->setIcon(icon3);
        pushButton = new QPushButton(EditStatisticBlockLibraryClass);
        pushButton->setObjectName("pushButton");
        pushButton->setGeometry(QRect(540, 530, 81, 31));
        pushButton->setFont(font2);
        QIcon icon4;
        icon4.addFile(QString::fromUtf8(":/Qtres/Close.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        pushButton->setIcon(icon4);
        QWidget::setTabOrder(tableWidgetLibList, toolButtonPickup);
        QWidget::setTabOrder(toolButtonPickup, toolButtonInspect);
        QWidget::setTabOrder(toolButtonInspect, EditLibID);
        QWidget::setTabOrder(EditLibID, EditLibName);
        QWidget::setTabOrder(EditLibName, EditPickupL);
        QWidget::setTabOrder(EditPickupL, EditPickupH);
        QWidget::setTabOrder(EditPickupH, EditMinBlockSize);
        QWidget::setTabOrder(EditMinBlockSize, EditMaxBlockSize);
        QWidget::setTabOrder(EditMaxBlockSize, EditMinBlockDots);
        QWidget::setTabOrder(EditMinBlockDots, EditMaxBlockDots);
        QWidget::setTabOrder(EditMaxBlockDots, EditLimitBlockSize);
        QWidget::setTabOrder(EditLimitBlockSize, EditSpaceToOutline);
        QWidget::setTabOrder(EditSpaceToOutline, EditNoiseSize);
        QWidget::setTabOrder(EditNoiseSize, EditPriority);
        QWidget::setTabOrder(EditPriority, comboBGenerationCategory);
        QWidget::setTabOrder(comboBGenerationCategory, checkBTransparent);
        QWidget::setTabOrder(checkBTransparent, checkBLeftPickup);
        QWidget::setTabOrder(checkBLeftPickup, checkBOverlappedGen);
        QWidget::setTabOrder(checkBOverlappedGen, EditBrightWidthL);
        QWidget::setTabOrder(EditBrightWidthL, EditOKDotL);
        QWidget::setTabOrder(EditOKDotL, EditOKLengthL);
        QWidget::setTabOrder(EditOKLengthL, EditBrightWidthH);
        QWidget::setTabOrder(EditBrightWidthH, EditOKDotH);
        QWidget::setTabOrder(EditOKDotH, EditOKLengthH);
        QWidget::setTabOrder(EditOKLengthH, checkUseMorphology);
        QWidget::setTabOrder(checkUseMorphology, checkEliminateAcnode);
        QWidget::setTabOrder(checkEliminateAcnode, EditDilationDotCount);
        QWidget::setTabOrder(EditDilationDotCount, EditErosionDotCount);
        QWidget::setTabOrder(EditErosionDotCount, checkBModeEnabled);
        QWidget::setTabOrder(checkBModeEnabled, checkBModeAbsoluteBright);
        QWidget::setTabOrder(checkBModeAbsoluteBright, checkBModeNGCluster);
        QWidget::setTabOrder(checkBModeNGCluster, checkBModeWhiteMask);
        QWidget::setTabOrder(checkBModeWhiteMask, checkBModeBlackMask);
        QWidget::setTabOrder(checkBModeBlackMask, EditAdjustBlack);
        QWidget::setTabOrder(EditAdjustBlack, EditAdjustWhite);
        QWidget::setTabOrder(EditAdjustWhite, ButtonLibNew);
        QWidget::setTabOrder(ButtonLibNew, ButtonLibDelete);
        QWidget::setTabOrder(ButtonLibDelete, ButtonLibSaveNew);
        QWidget::setTabOrder(ButtonLibSaveNew, ButtonLibSave);
        QWidget::setTabOrder(ButtonLibSave, pushButton);

        retranslateUi(EditStatisticBlockLibraryClass);

        stackedWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(EditStatisticBlockLibraryClass);
    } // setupUi

    void retranslateUi(QDialog *EditStatisticBlockLibraryClass)
    {
        EditStatisticBlockLibraryClass->setWindowTitle(QCoreApplication::translate("EditStatisticBlockLibraryClass", "EditStatisticBlockLibrary", nullptr));
        label_9->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "\343\203\226\343\203\255\343\203\203\343\202\257\346\234\200\345\244\247\343\202\265\343\202\244\343\202\272", nullptr));
        label_10->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "\343\203\226\343\203\255\343\203\203\343\202\257\346\234\200\345\260\217\343\202\265\343\202\244\343\202\272", nullptr));
        label_12->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "\343\203\226\343\203\255\343\203\203\343\202\257\346\234\200\345\260\217\351\235\242\347\251\215", nullptr));
        label_11->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "\343\203\226\343\203\255\343\203\203\343\202\257\346\234\200\345\244\247\351\235\242\347\251\215", nullptr));
        label_13->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "\351\231\220\347\225\214\343\202\265\343\202\244\343\202\272", nullptr));
        label_32->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "\343\202\265\n"
"\343\202\244\n"
"\343\202\272", nullptr));
        label_36->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "\343\201\235\n"
"\343\201\256\n"
"\344\273\226", nullptr));
        comboBGenerationCategory->setItemText(0, QCoreApplication::translate("EditStatisticBlockLibraryClass", "Pad", nullptr));
        comboBGenerationCategory->setItemText(1, QCoreApplication::translate("EditStatisticBlockLibraryClass", "Hole", nullptr));
        comboBGenerationCategory->setItemText(2, QCoreApplication::translate("EditStatisticBlockLibraryClass", "Silk", nullptr));
        comboBGenerationCategory->setItemText(3, QCoreApplication::translate("EditStatisticBlockLibraryClass", "Resist", nullptr));
        comboBGenerationCategory->setItemText(4, QCoreApplication::translate("EditStatisticBlockLibraryClass", "OtherMask", nullptr));
        comboBGenerationCategory->setItemText(5, QCoreApplication::translate("EditStatisticBlockLibraryClass", "FinePad", nullptr));
        comboBGenerationCategory->setItemText(6, QCoreApplication::translate("EditStatisticBlockLibraryClass", "Surround", nullptr));
        comboBGenerationCategory->setItemText(7, QCoreApplication::translate("EditStatisticBlockLibraryClass", "Any", nullptr));

        checkBTransparent->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "\346\216\222\344\273\226\347\224\237\346\210\220", nullptr));
        checkBLeftPickup->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "\346\256\213\343\202\250\343\203\252\343\202\242", nullptr));
        checkBOverlappedGen->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "\351\207\215\350\244\207\347\224\237\346\210\220", nullptr));
        label_7->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "\346\212\275\345\207\272\350\274\235\345\272\246\343\200\200\346\232\227\345\201\264", nullptr));
        label_8->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "\346\212\275\345\207\272\350\274\235\345\272\246\343\200\200\346\230\216\345\201\264", nullptr));
        label_30->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "\350\274\235\n"
"\345\272\246", nullptr));
        label_14->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "\350\274\252\351\203\255\343\201\213\343\202\211\343\201\256\351\226\223\351\232\224", nullptr));
        label_15->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "\343\203\216\343\202\244\343\202\272\343\202\265\343\202\244\343\202\272", nullptr));
        label_16->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "\345\204\252\345\205\210\345\272\246", nullptr));
        label_33->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "\347\224\237\n"
"\346\210\220", nullptr));
        label_21->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "\351\207\215\350\244\207\343\203\211\343\203\203\343\203\210\346\225\260", nullptr));
        label_35->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "\343\203\241\n"
"\343\202\244\n"
"\343\203\263", nullptr));
        label_20->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "\346\230\216\345\201\264", nullptr));
        label_17->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "OK\343\201\256\346\250\231\346\272\226\345\201\217\345\267\256\345\200\215\347\216\207", nullptr));
        label_18->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "OK\343\203\211\343\203\203\343\203\210\346\225\260", nullptr));
        label_19->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "\346\232\227\345\201\264", nullptr));
        label_29->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "\343\201\223\343\202\214\344\273\245\344\270\212\343\201\256\351\225\267\343\201\225\343\201\247\357\274\256\357\274\247", nullptr));
        label_39->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "\345\261\236\n"
"\346\200\247", nullptr));
        label_40->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "\350\274\235\n"
"\345\272\246", nullptr));
        checkBModeAbsoluteBright->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "\347\265\266\345\257\276\350\274\235\345\272\246", nullptr));
        checkBModeNGCluster->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "\345\241\212\346\244\234\346\237\273", nullptr));
        checkBModeBlackMask->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "\351\273\222\343\203\236\343\202\271\343\202\257", nullptr));
        checkBModeEnabled->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "\346\244\234\346\237\273\346\234\211\345\212\271", nullptr));
        checkBModeWhiteMask->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "\347\231\275\343\203\236\343\202\271\343\202\257", nullptr));
        label_41->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "\350\243\234\n"
"\346\255\243", nullptr));
        label_42->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "\350\274\235\n"
"\345\272\246", nullptr));
        label_26->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "\346\230\216\345\201\264\343\200\200\346\234\200\345\244\247\350\243\234\346\255\243\350\274\235\345\272\246\351\207\217", nullptr));
        label_25->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "\346\232\227\345\201\264\343\200\200\346\234\200\345\244\247\350\243\234\346\255\243\350\274\235\345\272\246\351\207\217", nullptr));
        label_45->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "\350\206\250\n"
"\345\274\265\n"
" \343\203\273\n"
"\345\217\216\n"
"\347\270\256", nullptr));
        label_46->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "\350\274\235\n"
"\345\272\246", nullptr));
        checkEliminateAcnode->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "\345\255\244\347\253\213\347\202\271\343\201\256\351\231\244\345\216\273", nullptr));
        checkUseMorphology->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "\350\206\250\345\274\265\343\203\273\345\217\216\347\270\256\343\202\222\343\201\231\343\202\213", nullptr));
        label_27->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "\350\206\250\345\274\265\343\203\211\343\203\203\343\203\210\346\225\260", nullptr));
        label_28->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "\345\217\216\347\270\256\343\203\211\343\203\203\343\203\210\346\225\260", nullptr));
        comboBoxMorphologyApplyTo->setItemText(0, QCoreApplication::translate("EditStatisticBlockLibraryClass", "\346\232\227\345\201\264\343\203\273\346\230\216\345\201\264\344\270\241\346\226\271", nullptr));
        comboBoxMorphologyApplyTo->setItemText(1, QCoreApplication::translate("EditStatisticBlockLibraryClass", "\346\232\227\345\201\264\343\201\256\343\201\277", nullptr));
        comboBoxMorphologyApplyTo->setItemText(2, QCoreApplication::translate("EditStatisticBlockLibraryClass", "\346\230\216\345\201\264\343\201\256\343\201\277", nullptr));

        label->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "\351\201\251\347\224\250\345\205\210\357\274\232", nullptr));
        toolButtonInspect->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "\346\244\234\346\237\273\343\201\256\343\203\227\343\203\255\343\203\221\343\203\206\343\202\243", nullptr));
        QTableWidgetItem *___qtablewidgetitem = tableWidgetLibList->horizontalHeaderItem(0);
        ___qtablewidgetitem->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "ID", nullptr));
        QTableWidgetItem *___qtablewidgetitem1 = tableWidgetLibList->horizontalHeaderItem(1);
        ___qtablewidgetitem1->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "Name", nullptr));
        EditLibID->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "12345", nullptr));
        toolButtonPickup->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "\347\224\237\346\210\220\343\201\256\343\203\227\343\203\255\343\203\221\343\203\206\343\202\243", nullptr));
        label_4->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "\345\220\215\347\247\260", nullptr));
        EditLibName->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "Library Name", nullptr));
        ButtonLibDelete->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "Delete", nullptr));
        ButtonLibNew->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "Clear new", nullptr));
        ButtonLibSave->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "Update", nullptr));
        ButtonLibSaveNew->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "Save New", nullptr));
        pushButton->setText(QCoreApplication::translate("EditStatisticBlockLibraryClass", "\351\226\211\343\201\230\343\202\213", nullptr));
    } // retranslateUi

};

namespace Ui {
    class EditStatisticBlockLibraryClass: public Ui_EditStatisticBlockLibraryClass {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_EDITSTATISTICBLOCKLIBRARY_H
