#ifndef NICKINSPECTIONIMAGEPANEL_GLOBAL_H
#define NICKINSPECTIONIMAGEPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef NICKINSPECTIONIMAGEPANEL_LIB
# define NICKINSPECTIONIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define NICKINSPECTIONIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // NICKINSPECTIONIMAGEPANEL_GLOBAL_H
