#ifndef EASYSWITCHPHASEIMAGEPANEL_GLOBAL_H
#define EASYSWITCHPHASEIMAGEPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef EASYSWITCHPHASEIMAGEPANEL_LIB
# define EASYSWITCHPHASEIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define EASYSWITCHPHASEIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // EASYSWITCHPHASEIMAGEPANEL_GLOBAL_H
