# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = TestPIODLL
DESTDIR = ../../
CONFIG += release
DEFINES += QT_LARGEFILE_SUPPORT TESTPIODLL_LIB
LIBS += -L"./../../../Lib/Release" \
    -lServiceLib
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += .
RCC_DIR += ./GeneratedFiles
include(TestPIODLL.pri)
