#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(PROPERTYRASTERREFERENCE_LIB)
#  define PROPERTYRASTERREFERENCE_EXPORT Q_DECL_EXPORT
# else
#  define PROPERTYRASTERREFERENCE_EXPORT Q_DECL_IMPORT
# endif
#else
# define PROPERTYRASTERREFERENCE_EXPORT
#endif
