#ifndef BUTTONSETTINGCOLORDIFFERENCE_GLOBAL_H
#define BUTTONSETTINGCOLORDIFFERENCE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BUTTONSETTINGCOLORDIFFERENCE_LIB
# define BUTTONSETTINGCOLORDIFFERENCE_EXPORT Q_DECL_EXPORT
#else
# define BUTTONSETTINGCOLORDIFFERENCE_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONSETTINGCOLORDIFFERENCE_GLOBAL_H
