#ifndef EASYPROPERTYCOLORDIFFERENCE_GLOBAL_H
#define EASYPROPERTYCOLORDIFFERENCE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef EASYPROPERTYCOLORDIFFERENCE_LIB
# define EASYPROPERTYCOLORDIFFERENCE_EXPORT Q_DECL_EXPORT
#else
# define EASYPROPERTYCOLORDIFFERENCE_EXPORT Q_DECL_IMPORT
#endif

#endif // EASYPROPERTYCOLORDIFFERENCE_GLOBAL_H
