# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = IntegrationStackMultiNGThumbnail
DESTDIR = ../x64/Release
CONFIG += release
DEFINES += INTEGRATIONSTACKMULTINGTHUMBNAIL_LIB
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += GeneratedFiles
RCC_DIR += GeneratedFiles
include(IntegrationStackMultiNGThumbnail.pri)

FORMS += \
    IntegrationStackMultiNGThumbnailForm.ui

HEADERS += \
    IntegrationStackMultiNGThumbnailForm.h

SOURCES += \
    IntegrationStackMultiNGThumbnailForm.cpp
