#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(INTEGRATIONSTACKMULTINGTHUMBNAIL_LIB)
#  define INTEGRATIONSTACKMULTINGTHUMBNAIL_EXPORT Q_DECL_EXPORT
# else
#  define INTEGRATIONSTACKMULTINGTHUMBNAIL_EXPORT Q_DECL_IMPORT
# endif
#else
# define INTEGRATIONSTACKMULTINGTHUMBNAIL_EXPORT
#endif
