#ifndef CAMERAUSBSTANDARD_GLOBAL_H
#define CAMERAUSBSTANDARD_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef CAMERAUSBSTANDARD_LIB
# define CAMERAUSBSTANDARD_EXPORT Q_DECL_EXPORT
#else
# define CAMERAUSBSTANDARD_EXPORT Q_DECL_IMPORT
#endif

#endif // CAMERAUSBSTANDARD_GLOBAL_H
