#ifndef PROPERTYLINEENHANCER1L_GLOBAL_H
#define PROPERTYLINEENHANCER1L_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PROPERTYLINEENHANCER1L_LIB
# define PROPERTYLINEENHANCER1L_EXPORT Q_DECL_EXPORT
#else
# define PROPERTYLINEENHANCER1L_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTYLINEENHANCER1L_GLOBAL_H
