#ifndef BUTTONSHUTDOWN_GLOBAL_H
#define BUTTONSHUTDOWN_GLOBAL_H

#include <qglobal.h>

#ifdef BUTTONSHUTDOWN_LIB
# define BUTTONSHUTDOWN_EXPORT Q_DECL_EXPORT
#else
# define BUTTONSHUTDOWN_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONSHUTDOWN_GLOBAL_H
