#ifndef BUTTONTHRESHOLD2_GLOBAL_H
#define BUTTONTHRESHOLD2_GLOBAL_H

#include <qglobal.h>

#ifdef BUTTONTHRESHOLD2_LIB
# define BUTTONTHRESHOLD2_EXPORT Q_DECL_EXPORT
#else
# define BUTTONTHRESHOLD2_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONTHRESHOLD2_GLOBAL_H
