#ifndef FILTERREPLACECOLOR_GLOBAL_H
#define FILTERREPLACECOLOR_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef FILTERREPLACECOLOR_LIB
# define FILTERREPLACECOLOR_EXPORT Q_DECL_EXPORT
#else
# define FILTERREPLACECOLOR_EXPORT Q_DECL_IMPORT
#endif

#endif // FILTERREPLACECOLOR_GLOBAL_H
