#ifndef BUTTONMOVEALL_GLOBAL_H
#define BUTTONMOVEALL_GLOBAL_H

#include <qglobal.h>

#ifdef BUTTONMOVEALL_LIB
# define BUTTONMOVEALL_EXPORT Q_DECL_EXPORT
#else
# define BUTTONMOVEALL_EXPORT Q_DECL_IMPORT
#endif

#endif // BUTTONMOVEALL_GLOBAL_H
