#ifndef ARARRANGEIMAGEPANEL_GLOBAL_H
#define ARARRANGEIMAGEPANEL_GLOBAL_H

#include <qglobal.h>

#ifdef ARARRANGEIMAGEPANEL_LIB
# define ARARRANGEIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define ARARRANGEIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // ARARRANGEIMAGEPANEL_GLOBAL_H
