#ifndef FILTEREVENODD_GLOBAL_H
#define FILTEREVENODD_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef FILTEREVENODD_LIB
# define FILTEREVENODD_EXPORT Q_DECL_EXPORT
#else
# define FILTEREVENODD_EXPORT Q_DECL_IMPORT
#endif

#endif // FILTEREVENODD_GLOBAL_H
