#ifndef ZAXISREGULATION_GLOBAL_H
#define ZAXISREGULATION_GLOBAL_H

#include <qglobal.h>

#ifdef ZAXISREGULATION_LIB
# define ZAXISREGULATION_EXPORT Q_DECL_EXPORT
#else
# define ZAXISREGULATION_EXPORT Q_DECL_IMPORT
#endif

#endif // ZAXISREGULATION_GLOBAL_H
