# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = InputInTouchPanel
DESTDIR = ../../Lib/Release
QT += core sql network widgets
CONFIG += staticlib release
DEFINES += INPUTINTOUCHPANEL_LIB
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += .
RCC_DIR += ./GeneratedFiles
include(InputInTouchPanel.pri)
