#ifndef INPUTINTOUCHPANEL_GLOBAL_H
#define INPUTINTOUCHPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef INPUTINTOUCHPANEL_LIB
# define INPUTINTOUCHPANEL_EXPORT Q_DECL_EXPORT
#else
# define INPUTINTOUCHPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // INPUTINTOUCHPANEL_GLOBAL_H
