# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


TEMPLATE = subdirs
SUBDIRS += /ResultTIM_NGMark/ResultTIM_NGMark.pro \
    /ResultPhoneCover/ResultPhoneCover.pro \
    /ResultBattery/ResultBattery.pro \
    /ResultXMLSmallLot/ResultXMLSmallLot.pro \
    /ResultXMLV3/ResultXMLV3.pro \
    /ResultXMLPrintFast/ResultXMLPrintFast.pro \
    /ResultXMLMultiDelivery/ResultXMLMultiDelivery.pro \
    /ResultXMLForPiece/ResultXMLForPiece.pro \
    /ResultXMLBarcodeAppender/ResultXMLBarcodeAppender.pro \
    /ResultWriteCSV/ResultWriteCSV.pro \
    /ResultSaveTargetImage/ResultSaveTargetImage.pro \
    /ResultFrameDLL/ResultFrameDLL.pro \
    /ResultDLLIntoFile/ResultDLLIntoFile.pro
