#ifndef AUTOCLASSIFYIMAGEPANEL_GLOBAL_H
#define AUTOCLASSIFYIMAGEPANEL_GLOBAL_H

#include <qglobal.h>

#ifdef AUTOCLASSIFYIMAGEPANEL_LIB
# define AUTOCLASSIFYIMAGEPANEL_EXPORT Q_DECL_EXPORT
#else
# define AUTOCLASSIFYIMAGEPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // AUTOCLASSIFYIMAGEPANEL_GLOBAL_H
