#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(CHECKDATAVALIDATIONIMAGEPANEL_LIB)
#  define CHECKDATAVALIDATIONIMAGEPANEL_EXPORT Q_DECL_EXPORT
# else
#  define CHECKDATAVALIDATIONIMAGEPANEL_EXPORT Q_DECL_IMPORT
# endif
#else
# define CHECKDATAVALIDATIONIMAGEPANEL_EXPORT
#endif
