# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../CheckEverydayImagePanel/XCheckEverydayGUIPacket.h \
    ./CheckEverydayResultHistory.h \
    ./CheckEverydayResultHistoryResource.h \
    ./resource.h \
    ./checkeverydayresulthistory_global.h \
    ./CheckEverydayResultHistoryForm.h
SOURCES += ../../Algorithm/CheckEveryday/XCheckEverydayCommon.cpp \
    ../../Open/GUIDllCommon.cpp \
    ../../Open/SystemVersion.cpp \
    ../CheckEverydayImagePanel/XCheckEverydayGUIPacket.cpp \
    ./CheckEverydayResultHistory.cpp \
    ./CheckEverydayResultHistoryForm.cpp \
    ./CheckEverydayResultHistoryResource.cpp
FORMS += ./CheckEverydayResultHistoryForm.ui
RESOURCES += CheckEverydayResultHistory.qrc
