#ifndef CHECKEVERYDAYRESULTHISTORY_GLOBAL_H
#define CHECKEVERYDAYRESULTHISTORY_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef CHECKEVERYDAYRESULTHISTORY_LIB
# define CHECKEVERYDAYRESULTHISTORY_EXPORT Q_DECL_EXPORT
#else
# define CHECKEVERYDAYRESULTHISTORY_EXPORT Q_DECL_IMPORT
#endif

#endif // CHECKEVERYDAYRESULTHISTORY_GLOBAL_H
