#ifndef EXPANDMAININTAB_GLOBAL_H
#define EXPANDMAININTAB_GLOBAL_H

#include <qglobal.h>

#ifdef EXPANDMAININTAB_LIB
# define EXPANDMAININTAB_EXPORT Q_DECL_EXPORT
#else
# define EXPANDMAININTAB_EXPORT Q_DECL_IMPORT
#endif

#endif // EXPANDMAININTAB_GLOBAL_H
