#ifndef PUSHTOSAVEPIX_GLOBAL_H
#define PUSHTOSAVEPIX_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PUSHTOSAVEPIX_LIB
# define PUSHTOSAVEPIX_EXPORT Q_DECL_EXPORT
#else
# define PUSHTOSAVEPIX_EXPORT Q_DECL_IMPORT
#endif

#endif // PUSHTOSAVEPIX_GLOBAL_H
